/*
 * Original pixel art for Plants vs Undead, as character grids (one character per pixel,
 * "." = transparent). Every design is the game's own: round cartoon plant parts with big eyes
 * (a leaf, a squash that flings seeds, a knot of roots, a thorny stem, a stem pipe with
 * xylem/phloem stripes, a bell flower, a berry, a fiddlehead fern, a leaf whose mouth is a
 * stoma, a chloroplast) and goofy undead (a skeleton gardener, a moldy blob, beetles, a frosty
 * ghost, a gloomy cloud, a walking stump and the Weed Lich). Undead face left.
 * Grids were laid out with a small shape helper, then hand-tuned.
 */

export const PAL: Record<string, string> = {
  k: "#1b1030", w: "#ffffff", K: "#0a0f2e",
  g: "#43d664", G: "#1f8a3a", l: "#a8ff7a", h: "#7fbf4a", H: "#4a6a20",
  y: "#ffd23f", o: "#ff8c2e", O: "#c0571a", r: "#e3262f", R: "#8a1020", p: "#ff8fc8",
  b: "#9a6233", B: "#5a3418", t: "#e8c088", s: "#f2ead0", S: "#b8ae8c",
  u: "#6ea0ff", U: "#2456e8", c: "#7ff3ff", f: "#dff6ff", v: "#9b5de5", V: "#5a2a8a",
  x: "#9aa0b8", X: "#4a4f68", m: "#6a0f24", n: "#141a3a",
};

export const GRIDS: Record<string, string[]> = {
  "sunleaf": [
    ".......klgk.......",
    ".....k.klGk.k.....",
    "....klkklgkklk....",
    "....klllllglgk....",
    "...klllllllgggk...",
    "..kllllggggggggk..",
    ".klllgggggggggggk.",
    ".kllgwwggggwwgggk.",
    ".klggwKggggwKgggk.",
    ".kgggwKggggwKggGk.",
    ".kggggggggggggGGk.",
    ".kggpggmggmggpGGk.",
    "..kgggggmmggGGGk..",
    "...kgggggGGGGGk...",
    "..kkkggGGGGGGkkk..",
    ".kgggggkGGkgggggk.",
    "kggglggGGGggglggGk",
    ".kgggGGkGGkgggGGk.",
    "..kkkbbbGGbbbkkk..",
    "..kbbbBbbbbBbbbk..",
  ],
  "slinger": [
    ".......kGGggk.....",
    ".......kGGkk......",
    "......kkGGkk......",
    ".....kggggggk.....",
    "....kOgggggGOk....",
    "...kyOyyGGooOok...",
    "..kyyOyyooooOook..",
    ".kyyyOwwoowwOoook.",
    ".kyyyOwKoowKOoook.",
    ".kyooOwKoowKOoook.",
    "kooooOooooooOoooOk",
    ".koooOoooooommmmk.",
    ".kooopoooooommttmk",
    ".koooOoooooommmmk.",
    "..kooOoooooOOOOk..",
    "..kkoOooOOOOOOkk..",
    ".kggggoOOOOOggggk.",
    "kggglggGGGggglggGk",
    ".kgggGGbGGbgggGGk.",
    "..kbbbBbbbbBbbbk..",
  ],
  "rootknot": [
    ".....kkkkkkkkk....",
    "....kgggGGggggk...",
    "....kgggGGggggk...",
    ".....kkkGGkkkk....",
    "....ktttttbbbk....",
    "...ktttttbbbbbk...",
    "..ktkkBbbbbbkkbk..",
    ".kttBtkbbbbkbbBbk.",
    ".kttbwwbbbbwwbbbk.",
    ".ktbbwKbbbbwKbbbk.",
    "kbbbbwKbbbbwKbbBBk",
    ".kBbbbbbbbbbbbBBk.",
    ".kbbbbbmmmbbbbBBk.",
    ".kbbbbbbbbbbbtBBk.",
    "..kbBbbbbbbBBBBk..",
    "..kbbbbbbBBBBBbk..",
    ".kbkkbBBbBBBBkkbk.",
    ".kbkkBkkbkkkBk.kbk",
    "kbk.kBkkbk.kBk.kbk",
    "bk.kBk.kbk..kBk.kb",
  ],
  "thorn": [
    "...kkkkk..kkkkk...",
    "..klllllkkgggggk..",
    "..kllllllggggggk..",
    "...kkllggggggkk...",
    "...kgggggggggGk...",
    "..kkkkgggggGkk....",
    ".kwttlkkGGkkGk....",
    "..kkklwwggwwGkkk..",
    "....klwKggwKGttwk.",
    "....klwKggwKGkkk..",
    "..kkklgggggGGk....",
    ".kwttlgmmmmGGk....",
    "..kkklggmmgGGkkk..",
    "....klgggggGGttwk.",
    "....klgggggGGkkk..",
    "..kkkGGGGGGGGk....",
    ".kwttlgggggGGk....",
    "..kkklgggggGGk....",
    "...kklgggggGGkk...",
    "..kbbbBbbbbBbbbk..",
  ],
  "stem": [
    "......kllllk......",
    ".....kkllllkk.....",
    "....kGGGGGGGGk....",
    "....kGGGGGGGGk....",
    "....kguwwwwygk....",
    "....kguwKwKygk....",
    "....kguwKwKygk....",
    "....kguggggygk....",
    "....kgumggmygk....",
    "....kgugmmgygk....",
    "....kGGGGGGGGk....",
    "kkkkkguggggygkkkkk",
    "GggggguggggygggggG",
    "uuuuuuuuuuuuuuuuuu",
    "yyyyyyyyyyyyyyyyyy",
    "GggggguggggygggggG",
    "kkkkkguggggygkkkkk",
    "....kguggggygk....",
    "...kkguggggygkk...",
    "..kbbbBbbbbBbbbk..",
  ],
  "pollen": [
    "..........y.......",
    ".......y..........",
    "..kk.ykk...ky..kk.",
    ".kpvkkpvk.kpvkkpvk",
    ".kvvkkvvk.kvvkkvvk",
    ".kvvkkyyyyyyvkkvvk",
    "..kkpppyyyyvvvkkk.",
    "..kpvvvvvvvvvvvk..",
    ".kvvvvwwvvwwvVVVk.",
    "..kvvvwKvvwKVVVk..",
    "..kvvvwKvvwKvVVk..",
    "...kvvvvvvvvVVk...",
    "....kpvvmmVVpk....",
    ".....kvVmmVVk.....",
    "......kkGGkk......",
    "..kkkkkkGGkkkkkk..",
    ".kgggggkGGkgggggk.",
    "kggglggGGGggglggGk",
    ".kgggGGbGGbgggGGk.",
    "..kbbbBbbbbBbbbk..",
  ],
  "berry": [
    ".......kGGk.......",
    ".......kGGk.......",
    ".....kkkGGkkk.....",
    "....kggggggggk....",
    "...kggggggggGgk...",
    "...kpppgGGGrrrk...",
    "..kppppprrrrrrck..",
    ".kppppprrrrrrrcuk.",
    ".kpypwwrrrwwrrrrk.",
    "kppprwKrrrwKrryrrk",
    "kpprrwKrrrwKrrrrrk",
    "kryrrrrrrrrrrrrrRk",
    "krrrrrrrrrrrrrrRRk",
    "krrrrrrmmrrrrrRyRk",
    ".krryrrmmrrrrRRRk.",
    ".krrrrrrrryrRyRRk.",
    "..krrryrrrRRRRRk..",
    "...krrrryRRRRRk...",
    "....kkrRRRRRkk....",
    "......kkkkkk......",
  ],
  "frond": [
    "......kkkkkk......",
    ".....kllllggk.....",
    "....klllgggggk....",
    "...kllGGGGGgggk...",
    "..kllwwgggwwgggk..",
    "..klgwKGGGwKgggk..",
    "..kggwKGggwKgGGk..",
    "..kggGgGGGGggGGk..",
    "...kggGgmmgGGGk...",
    "..klkggGGGGGGklk..",
    "..kggkggGGGGkggk..",
    "...klggkGGkgglk...",
    "...kggkggggkggk...",
    "....klgkGGkglk....",
    "....kgkggggkgk....",
    ".....kggGGggk.....",
    "......kkggkk......",
    ".....kkkGGkkk.....",
    "...kkbbbGGbbbkk...",
    "..kbbbBbbbbBbbbk..",
  ],
  "stoma": [
    "..................",
    "..................",
    "...k.kkkkkkkk.k...",
    ".kkgkllllllllkgkk.",
    "kggllllllllllllggk",
    ".klllwwlllwwllllk.",
    "kllllwKlllwKlllllk",
    "kllllwKlllwKlllllk",
    "kllllllllllllllllk",
    "kllpllllllllllplgk",
    "kllllllGGGGlllgggk",
    "klllllGkckkGllgggk",
    ".kllllGkkckGggggk.",
    "..kllllGGGGggggk..",
    "...kkllggggggkk...",
    ".....kkkGGkkk.....",
    ".......kGGk.......",
    ".....kkkGGkkk.....",
    "...kkbbbGGbbbkk...",
    "..kbbbBbbbbBbbbk..",
  ],
  "chloro": [
    "..................",
    "..................",
    ".......kkkk.......",
    "....kkkllllkkk....",
    "...kllllllggggk...",
    "..kllwwhhhwwgggk..",
    ".kllhwKhhhwKhhggk.",
    ".kllhwKhhhwKhhggk.",
    "kllhhhhhhhhhhyhggk",
    "kllhhGGGmmhhyyhggk",
    "kghhhlllhhhhhyhhgk",
    "kghhhGGGhhhhhyhhGk",
    "kggGGGhhhhhGGyhGGk",
    "kgglllhhhhhllyhGGk",
    ".kgGGGhGGGhGGyGGk.",
    ".kgghhhlllhhhyGGk.",
    "..kggghGGGhhGGGk..",
    "...kgggGGGGGGGk...",
    "....kkkGGGGkkk....",
    ".......kkkk.......",
  ],
  "grumbones0": [
    "...kttttttttk...",
    "...kttttttttk...",
    ".kkkrrrrrrrrkkk.",
    "kttttttttttttttk",
    ".ktkkkkssskkkbk.",
    "..k.kkkssskkkk..",
    "kkkksykkskkssk..",
    "xxxxskksskkssk..",
    "xbxkssssssssSk..",
    "kbkksssssssSSk..",
    ".kbkkwkwkwwSk...",
    ".kbkkkkSSSkkk...",
    ".kbksUuUUUuUsk..",
    "..kssUuUUUuUsk..",
    "..kbsUUuuuUUsk..",
    "...kbUUuuuUUsk..",
    "...kbUUUUUUUk...",
    "....kUUUUUUUk...",
    ".....kskkksk....",
    ".....ksk.ksk....",
    ".....ksk.ksk....",
    "....ksk...ksk...",
    "...kksk...ksk...",
    "..kSSSk..kSSSk..",
  ],
  "grumbones1": [
    "...kttttttttk...",
    "...kttttttttk...",
    ".kkkrrrrrrrrkkk.",
    "kttttttttttttttk",
    ".ktkkkkssskkkbk.",
    "..k.kkkssskkkk..",
    "kkkksykkskkssk..",
    "xxxxskksskkssk..",
    "xbxkssssssssSk..",
    "kbkksssssssSSk..",
    ".kbkkwkwkwwSk...",
    ".kbkkkkSSSkkk...",
    ".kbksUuUUUuUsk..",
    "..kssUuUUUuUsk..",
    "..kbsUUuuuUUsk..",
    "...kbUUuuuUUsk..",
    "...kbUUUUUUUk...",
    "....kUUUUUUUk...",
    ".....kskkksk....",
    ".....ksk.ksk....",
    ".....ksk.ksk....",
    "......ksksk.....",
    ".....kksksk.....",
    "....kSSSSSSk....",
  ],
  "rotling0": [
    "................",
    "................",
    "................",
    "........k.......",
    ".......kvk......",
    ".......kkHk.....",
    "......khhhk.....",
    ".....khhhhhk....",
    "....kkhhhhhkk...",
    "...klllhhvVhhk..",
    "..klllllhhhhhhk.",
    "..klvVhhhhhhhhk.",
    ".kllwwhhhkkhvVhk",
    ".kllKwhhhhhkkhhk",
    ".klhKwhhhhKwhhhk",
    "khhhhhhhhhhhhhhH",
    ".khhhhhhhhhhhhHk",
    ".khhhhhhhhhvVHHk",
    ".khhmmmmmhhhHHHk",
    "..khhpphhhhHHHk.",
    "..khhhhhhHHHHHk.",
    "...khhhHHHHHHk..",
    "..k.kkHHHHHkk.k.",
    ".kHkkHkkHkkHkkHk",
  ],
  "rotling1": [
    "................",
    "................",
    "................",
    "................",
    "........k.......",
    ".......kvk......",
    "......kkhHk.....",
    ".....khhhhhk....",
    "....khhhhhhhk...",
    "....kkhhhvVkk...",
    "...kllllhhhhhk..",
    "..klvVllhhhhhhk.",
    ".kllwwhhhkkhvVhk",
    ".kllKwhhhhhkkhhk",
    ".klhKwhhhhKwhhhk",
    ".khhhhhhhhhhhhhk",
    ".khhhhhhhhhhhhHk",
    ".khhhhhhhhhvVHHk",
    ".khhmmmmmhhhHHHk",
    ".khhhpphhhhhHHHk",
    "..khhhhhhhHHHHk.",
    "...khhhhHHHHHk..",
    "...kkkHHHHHkk..k",
    "..kHkkHkkHkkHkkH",
  ],
  "blightbug0": [
    ".....kk...",
    "k..kkvvkk.",
    ".kkvyVVVVk",
    "kwXVVVVyVV",
    "XKXXVyVVVn",
    "kXXVVVVnnk",
    ".kkkknnkk.",
    "...k.kkk..",
  ],
  "blightbug1": [
    ".....kk...",
    "k..kkvvkk.",
    ".kkvyVVVVk",
    "kwXVVVVyVV",
    "XKXXVyVVVn",
    "kXXVVVVnnk",
    ".kkkknnkk.",
    "....kkk.k.",
  ],
  "frostwraith0": [
    "....U..U..U.....",
    "...UcUUcUUcU.U..",
    "...UwUwwwwwUUcU.",
    "....UwwwwfffUU..",
    "...UwwwwfffffU..",
    "..UwwwwfffffffU.",
    "..UwwfffffffffU.",
    ".UwwwUfffwUffffU",
    ".UwfUUfffUUffffU",
    ".UffUUfffUUfcccU",
    ".UffffffffffcccU",
    ".UfffUfffUffcccU",
    ".UffffUUUfffcccU",
    ".UffffffffffcccU",
    ".UuuuuuuuuuuuucU",
    "UuffffffffffcccU",
    "uUffffffffffcccU",
    "UUccffffccfffccc",
    ".UccUffUccUffUcc",
    ".UccUffUccUffUcc",
    "..UUUffUUUUffUUU",
    "....UffU..UffU..",
    ".....UU....UU...",
    "................",
  ],
  "frostwraith1": [
    "....U..U..U.....",
    "...UcUUcUUcU.U..",
    "...UwUwwwwwUUcU.",
    "....UwwwwfffUU..",
    "...UwwwwfffffU..",
    "..UwwwwfffffffU.",
    "..UwwfffffffffU.",
    ".UwwwUfffwUffffU",
    ".UwfUUfffUUffffU",
    ".UffUUfffUUfcccU",
    ".UffffffffffcccU",
    ".UfffUfffUffcccU",
    ".UffffUUUfffcccU",
    ".UffffffffffcccU",
    ".UuuuuuuuuuuuucU",
    "UuffffffffffcccU",
    "uUffffffffffcccU",
    "UUccffffccfffccc",
    ".UccUffUccUffUcc",
    ".UccUffUccUffUcc",
    ".UccUUUUccUUUUcc",
    ".UccU..UccU..Ucc",
    "..UU....UU....UU",
    "................",
  ],
  "shade0": [
    "..................",
    ".......nnnnn......",
    "......nXXXXXn.....",
    ".....nXXXXXXXnnn..",
    "....nXXxxxXXXXXXn.",
    "...nnXxxxxxXXXXXXn",
    "..nXXXXxxxXXXXXXXn",
    ".nXXXXXXXXXXXXXXXn",
    "nXXXXXXXXXXXXXXXXX",
    "nXXXXXXXXXXXXXXXXn",
    "nXXXXyKyXXXyKyXXXn",
    ".nXXXXXXXXXXXXXXXn",
    ".nXXXXXXXXXXXXXXn.",
    ".nXXXXXXkkkXXXnnn.",
    "..nXXXXXXXXXXnnn..",
    "...nnXXXXnnnnn....",
    ".....nnnnn........",
    "....u.......u.....",
    "........u.........",
    ".........u........",
    ".....u.......u....",
    "..................",
  ],
  "shade1": [
    "..................",
    ".......nnnnn......",
    "......nXXXXXn.....",
    ".....nXXXXXXXnnn..",
    "....nXXxxxXXXXXXn.",
    "...nnXxxxxxXXXXXXn",
    "..nXXXXxxxXXXXXXXn",
    ".nXXXXXXXXXXXXXXXn",
    "nXXXXXXXXXXXXXXXXX",
    "nXXXXXXXXXXXXXXXXn",
    "nXXXXyKyXXXyKyXXXn",
    ".nXXXXXXXXXXXXXXXn",
    ".nXXXXXXXXXXXXXXn.",
    ".nXXXXXXkkkXXXnnn.",
    "..nXXXXXXXXXXnnn..",
    "...nnXXXXnnnnn....",
    ".....nnnnn........",
    "...u.......u......",
    ".......u..........",
    "........u.........",
    "....u.......u.....",
    "..................",
  ],
  "stump0": [
    "................",
    "................",
    "...kkkkkkkkkk...",
    "..kttttttttttk..",
    ".kttbbbttbbbttk.",
    ".kbtttttttttBBk.",
    ".kbkkbbbbbkkBBk.",
    ".kbbbkkbkkbbBBkk",
    ".kbbwwbbwwbbBrrr",
    "kkbbKwbbKwBbrrwr",
    "BkbbKwbbKwBbBrtr",
    "kBBbBbbbbbBbBBtk",
    "kkbbBbbbbbBbBBk.",
    "rwrrmwmmwmBbBBk.",
    "kkbbmmmmmmBbBBk.",
    ".kbbBbbbbbBbBBk.",
    ".kbbBbbbbbBbBBk.",
    ".kbbbbbbbbBbBBk.",
    ".kbbbbbbbbbbBBk.",
    "..kkkkBkkkBkkk..",
    ".....kBk.kBk....",
    ".....kBk.kBk....",
    "....kBk...kBk...",
    "....kBk...kBk...",
  ],
  "stump1": [
    "................",
    "................",
    "...kkkkkkkkkk...",
    "..kttttttttttk..",
    ".kttbbbttbbbttk.",
    ".kbtttttttttBBk.",
    ".kbkkbbbbbkkBBk.",
    ".kbbbkkbkkbbBBkk",
    ".kbbwwbbwwbbBrrr",
    "kkbbKwbbKwBbrrwr",
    "BkbbKwbbKwBbBrtr",
    "kBBbBbbbbbBbBBtk",
    "kkbbBbbbbbBbBBk.",
    "rwrrmwmmwmBbBBk.",
    "kkbbmmmmmmBbBBk.",
    ".kbbBbbbbbBbBBk.",
    ".kbbBbbbbbBbBBk.",
    ".kbbbbbbbbBbBBk.",
    ".kbbbbbbbbbbBBk.",
    "..kkkkBkkkBkkk..",
    ".....kBk.kBk....",
    ".....kBk.kBk....",
    "......kBkBk.....",
    "......kBkBk.....",
  ],
  "weedlich0": [
    "....kvkkvkkvkkvk..kvkkvkkvk...",
    "....kvkkvkkvkkvk..kvkkvkkvk...",
    ".....kvkvkkkvkvpkkvkkkvkvk....",
    ".....kvkkvppvppvvvvvvvkkvk....",
    ".....kvkpvppvpvvvvvvvvvkvk....",
    "......kppppvvvvvvvvvvvvvk.....",
    "....k.kppvvvvvvvvvvvvvvvk.....",
    "..kkpkvvvvvvvvvvvvvvvvvvVk....",
    ".kpprrrvvvvvvvvvvvvvvVVVk.....",
    ".kprrrrvvvvvvvvvvvvvVVVVk.....",
    "krrrrrrRkvvvvvvvvvVVVVVk......",
    ".krrrrRGGGGGGGGGGGGGGGGGk.....",
    ".krrrRRGGGGGGGGGGGGGGGGGk.....",
    "..kkRkkgGgGgGsssssGgGgGgk.....",
    "...kbk.kkkksssssssskkkkk......",
    "...kbk...kskksssskkssk........",
    "...kbk..kswwssssswwsssk.......",
    "...kbk..kwwwssssswwwssk.......",
    "...kbk.ksKKwsssssKKwssSk......",
    "...kbk..kwwwssssswwwSSk.......",
    "...kbk..kssssssssssSSSk.......",
    "...kbk...kssmmmmmmmSSk........",
    "...kbk....ksswsSwSSSk.........",
    "...kbk....kkkSSSSSkkk.........",
    "...kbk...khhhhhGhhhhhk........",
    "...kbkk.khhhhhhGhhhhhk........",
    "...kbsskhhhhhhhGhhhhhhk.......",
    "...kbkksHHHHHHHGHHHHHHk.......",
    "...kbkkHssHHHHHGHHHHHHHk......",
    "...kbkkHHHHHHHHGHHHHHHHk......",
    "...kbkhhhhhhhhhGhhhhhhhhk.....",
    "...kbkhhhhhhhhhGhhhhhhhhk.....",
    "...kbhhhhhhhhhhGhhhhhhhhhk....",
    "...kbHHHHHHHHHHGHHHHHHHHHk....",
    "...kbHHHHHHHHHHGHHHHHHHHHHk...",
    "..kHbHHHHHHHHHHGHHHHHHHHHHHk..",
    "..khbhhhhhhhhhhGhhhhhhhhhhhk..",
    ".khhbhhhhhhhhhhGhhhhhhhhhhhhk.",
    ".khhbhhhhhhhhhhGhhhhhhhhhhhhk.",
    "kHHHbHHHHHHHHHHGHHHHHHHHHHHHHk",
    ".kkkbkkkHkkkHkkkHkkkHkkkHkkkk.",
    "..kHbkkHk.kHk.kHk.kHk.kHk.....",
  ],
  "weedlich1": [
    "....kvkkvkkvkkvk..kvkkvkkvk...",
    "....kvkkvkkvkkvk..kvkkvkkvk...",
    ".....kvkvkkkvkvpkkvkkkvkvk....",
    ".....kvkkvppvppvvvvvvvkkvk....",
    ".....kvkpvppvpvvvvvvvvvkvk....",
    "......kppppvvvvvvvvvvvvvk.....",
    "....k.kppvvvvvvvvvvvvvvvk.....",
    "..kkpkvvvvvvvvvvvvvvvvvvVk....",
    ".kpprrrvvvvvvvvvvvvvvVVVk.....",
    ".kprrrrvvvvvvvvvvvvvVVVVk.....",
    "krrrrrrRkvvvvvvvvvVVVVVk......",
    ".krrrrRGGGGGGGGGGGGGGGGGk.....",
    ".krrrRRGGGGGGGGGGGGGGGGGk.....",
    "..kkRkkgGgGgGsssssGgGgGgk.....",
    "...kbk.kkkksssssssskkkkk......",
    "...kbk...kskksssskkssk........",
    "...kbk..kswwssssswwsssk.......",
    "...kbk..kwwwssssswwwssk.......",
    "...kbk.ksKKwsssssKKwssSk......",
    "...kbk..kwwwssssswwwSSk.......",
    "...kbk..kssssssssssSSSk.......",
    "...kbk...kssmmmmmmmSSk........",
    "...kbk....ksswsSwSSSk.........",
    "...kbk....kkkSSSSSkkk.........",
    "...kbk...khhhhhGhhhhhk........",
    "...kbkk.khhhhhhGhhhhhk........",
    "...kbsskhhhhhhhGhhhhhhk.......",
    "...kbkksHHHHHHHGHHHHHHk.......",
    "...kbkkHssHHHHHGHHHHHHHk......",
    "...kbkkHHHHHHHHGHHHHHHHk......",
    "...kbkhhhhhhhhhGhhhhhhhhk.....",
    "...kbkhhhhhhhhhGhhhhhhhhk.....",
    "...kbhhhhhhhhhhGhhhhhhhhhk....",
    "...kbHHHHHHHHHHGHHHHHHHHHk....",
    "...kbHHHHHHHHHHGHHHHHHHHHHk...",
    "..kHbHHHHHHHHHHGHHHHHHHHHHHk..",
    "..khbhhhhhhhhhhGhhhhhhhhhhhk..",
    ".khhbhhhhhhhhhhGhhhhhhhhhhhhk.",
    ".khhbhhhhhhhhhhGhhhhhhhhhhhhk.",
    "kHHHbHHHHHHHHHHGHHHHHHHHHHHHHk",
    ".kkkbkkkHkkkHkkkHkkkHkkkHkkkk.",
    "...kbHk.kHk.kHk.kHk.kHk.kHk...",
  ],
  "cart": [
    ".......krk........",
    ".......krk........",
    ".......kkrkk......",
    "......krrrrrk.....",
    "......krrrrrk.....",
    "......krrrrrk....k",
    "......ktKtKtk...kb",
    ".......kpppk..kkbk",
    ".kkkkkkwwwwwkkbbk.",
    "kxxxxxxwwwwwxbkk..",
    "kxxxxxxxwwwxxxk...",
    "kxxxxxxxxxxxxxk...",
    "kxXXXXXXXXbXXxk...",
    ".kkXXxXXkkbkkk....",
    "..kXXXXXkkbk......",
    "...kXXXk.kbk......",
  ],
  "sun": [
    ".....y.....",
    ".y.......y.",
    "....wwy....",
    "...wwyyy...",
    "..wwyyyyy..",
    "y.yyyyyyo.y",
    "..yyyyyoo..",
    "...yyyoo...",
    "....ooo....",
    ".y.......y.",
    ".....y.....",
  ],
  "drop": [
    "..kuk..",
    ".kuuuk.",
    ".kuuuk.",
    ".kccuk.",
    "kcwuuuk",
    "kuuuuuk",
    "kuuuuuk",
    "kuuuuUk",
    ".kuUUk.",
  ],
  "co2": [
    ".....X.....",
    "..XXXxXXX..",
    ".XXwxxxxXX.",
    ".XwxxxxxxX.",
    ".XxxxxxxxX.",
    "XxkkxkkkxxX",
    ".XkxxkxkxX.",
    ".XkkxkkkwX.",
    ".XXxxxxxXw.",
    "..XXXxXXX..",
    ".....X.....",
  ],
  "glucose": [
    "...ywy...",
    "..y...y..",
    "yy.ooo.yy",
    "y.ooooo.y",
    "y.ooyoo.y",
    "y.ooooo.y",
    "yy.ooo.yy",
    "..y...y..",
    "...yyy...",
  ],
  "o2": [
    "....c....",
    "..ccfcc..",
    ".cwffffc.",
    ".cfcccfc.",
    "cffcfcffc",
    ".cfcccfc.",
    ".cfffffc.",
    "..ccfcc..",
    "....c....",
  ],
  "seedshot": [
    ".....",
    ".wtt.",
    "ttttb",
    ".ttb.",
    ".....",
  ],
  "leafshot": [
    ".........",
    ".........",
    "....l....",
    ".llggggg.",
    "gGGGGGGGG",
    ".gggggGG.",
    "....G....",
    ".........",
    ".........",
  ],
};

/** Eyelid colour per plant (blink frames paint the eye whites with it). */
export const LID: Record<string, string> = {
  sunleaf: "g", slinger: "o", rootknot: "b", thorn: "g", stem: "g", pollen: "v", berry: "r", frond: "g", stoma: "l", chloro: "h",
};

export type Variant = "n" | "flash" | "blink" | "frost";

const cache = new Map<string, HTMLCanvasElement>();

/** A sprite as a canvas (cached). `flash` = white hit flash, `frost` = icy tint, `blink` = eyes shut. */
export function sprite(name: string, variant: Variant = "n"): HTMLCanvasElement {
  const key = `${name}|${variant}`;
  let c = cache.get(key);
  if (c) return c;
  const rows = GRIDS[name] ?? GRIDS.sun;
  c = document.createElement("canvas");
  c.width = rows[0].length;
  c.height = rows.length;
  const g = c.getContext("2d")!;
  const lid = LID[name];
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      let ch = row[x];
      if (ch === ".") continue;
      if (variant === "blink" && lid) {
        if (ch === "w") ch = lid;
        else if (ch === "K") ch = "k";
      }
      let col = PAL[ch] ?? "#ff00ff";
      if (variant === "flash") col = ch === "k" ? "#ffd23f" : "#ffffff";
      else if (variant === "frost") col = ch === "k" ? "#2456e8" : mix(col, "#bfefff", 0.38);
      g.fillStyle = col;
      g.fillRect(x, y, 1, 1);
    }
  });
  cache.set(key, c);
  return c;
}

function mix(a: string, b: string, t: number): string {
  const pa = parseInt(a.slice(1), 16);
  const pb = parseInt(b.slice(1), 16);
  const ch = (s: number) => Math.round(((pa >> s) & 255) * (1 - t) + ((pb >> s) & 255) * t);
  return `rgb(${ch(16)},${ch(8)},${ch(0)})`;
}

/** A sprite as a PNG data URL at an integer scale (for seed cards and question icons). */
export function spriteURL(name: string, scale = 3): string {
  const s = sprite(name);
  const c = document.createElement("canvas");
  c.width = s.width * scale;
  c.height = s.height * scale;
  const g = c.getContext("2d")!;
  g.imageSmoothingEnabled = false;
  g.drawImage(s, 0, 0, c.width, c.height);
  return c.toDataURL();
}
