import type { Question } from "../../types";
// Grade 12 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Economics and Personal Finance: economic systems, market structures, supply and demand
// (EPF.E.1.1–1.3, EPF.E.1); macroeconomic indicators and policy (EPF.E.2.1, EPF.E.2); income, education and paychecks (EPF.IE.1.1–1.3, EPF.IE.1); money and credit management:
// spending plans, renting and mortgages, financial institutions, interest, credit (EPF.MCM.1.1–1.4, EPF.MCM.2.1–2.3, EPF.MCM.3.1, EPF.MCM.3); investing, planning and giving
// (EPF.FP.1.1–1.3, EPF.FP.1); consumer decisions (EPF.CC.1.1–1.3, EPF.CC.1).
const questions: Question[] = [
  {
    id: "soc-g12-01",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.1",
    skill: "Economic systems",
    prompt: "An economy where customs decide what to produce is...",
    choices: ["Traditional", "Command", "Market", "Mixed"],
    answer: 0,
    explanation: "In a traditional economy, people produce what their ancestors did.",
    quick: true,
  },
  {
    id: "soc-g12-02",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.1",
    skill: "Economic systems",
    prompt: "Most economies, including the U.S., are...",
    choices: ["Mixed", "Pure command", "Traditional", "Pure market"],
    answer: 0,
    explanation: "The U.S. mixes free markets with some government rules and services.",
    quick: true,
  },
  {
    id: "soc-g12-03",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.3",
    skill: "Supply and demand",
    prompt: "When a price rises, quantity demanded usually...",
    choices: ["Falls", "Rises", "Stays same", "Doubles"],
    answer: 0,
    explanation: "The law of demand: higher prices mean people buy less.",
    quick: true,
  },
  {
    id: "soc-g12-04",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "Opportunity cost",
    prompt: "The value of the next-best option you give up is the opportunity...",
    choices: ["Cost", "Profit", "Market", "Budget"],
    answer: 0,
    explanation: "Every choice has an opportunity cost, the value of what you did not choose.",
    quick: true,
  },
  {
    id: "soc-g12-05",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2.1",
    skill: "Inflation",
    prompt: "A general rise in prices over time is...",
    choices: ["Inflation", "Deflation", "Recession", "Interest"],
    answer: 0,
    explanation: "Inflation means each dollar buys less than before.",
    quick: true,
  },
  {
    id: "soc-g12-06",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2",
    skill: "Monetary policy",
    prompt: "The Federal Reserve is the U.S....",
    choices: ["Central bank", "Tax agency", "Stock market", "Trade court"],
    answer: 0,
    explanation: "The Fed manages the money supply and sets key interest rates.",
    quick: true,
  },
  {
    id: "soc-g12-07",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2.1",
    skill: "GDP",
    prompt: "GDP measures a country's total...",
    choices: ["Output", "Debt", "Savings", "Population"],
    answer: 0,
    explanation: "Gross domestic product is the value of all final goods and services made in a country in a year.",
    quick: true,
  },
  {
    id: "soc-g12-08",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.1",
    skill: "Education and income",
    prompt: "On average, more education is linked to higher...",
    choices: ["Earnings", "Prices", "Rent", "Inflation"],
    answer: 0,
    explanation: "Workers with more education or training tend to earn more and face less unemployment.",
    quick: true,
  },
  {
    id: "soc-g12-09",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1",
    skill: "Paychecks",
    prompt: "Paycheck money withheld for Social Security and Medicare is called...",
    choices: ["FICA", "Interest", "Tips", "Dividends"],
    answer: 0,
    explanation: "FICA taxes fund Social Security and Medicare.",
    quick: true,
  },
  {
    id: "soc-g12-10",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.1",
    skill: "Budgeting",
    prompt: "A plan for spending and saving money is a...",
    choices: ["Budget", "Loan", "Tax", "Bond"],
    answer: 0,
    explanation: "A budget compares income and expenses so you can reach goals.",
    quick: true,
  },
  {
    id: "soc-g12-11",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.3",
    skill: "Credit",
    prompt: "A credit score mainly shows how well you...",
    choices: ["Repay debts", "Earn money", "Invest", "Spend cash"],
    answer: 0,
    explanation: "Lenders use credit scores to judge how likely you are to pay back a loan.",
    quick: true,
  },
  {
    id: "soc-g12-12",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.2.2",
    skill: "Interest",
    prompt: "Interest earned on both principal and past interest is...",
    choices: ["Compound", "Simple", "Fixed", "Flat"],
    answer: 0,
    explanation: "Compound interest grows faster over time because interest earns interest.",
    quick: true,
  },
  {
    id: "soc-g12-13",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Investing",
    prompt: "Spreading money across many investments is called...",
    choices: ["Diversifying", "Borrowing", "Budgeting", "Leasing"],
    answer: 0,
    explanation: "Diversifying lowers risk because one bad investment hurts less.",
    quick: true,
  },
  {
    id: "soc-g12-14",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Risk and return",
    prompt: "Which usually has the highest long-term risk and return?",
    choices: ["Stocks", "Savings acct", "CDs", "Gov't bonds"],
    answer: 0,
    explanation: "Stocks rise and fall more, but historically they have earned more over long periods.",
    quick: true,
  },
  {
    id: "soc-g12-15",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1.1",
    skill: "Advertising",
    prompt: "An ad where a famous athlete praises a product uses...",
    choices: ["An endorsement", "A warranty", "A rebate", "A recall"],
    answer: 0,
    explanation: "Endorsements try to persuade consumers by linking a product to someone they admire.",
    quick: true,
  },
  {
    id: "soc-g12-16",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1",
    skill: "Consumer protection",
    prompt: "A phishing email tries to...",
    choices: ["Steal info", "Save money", "Pay taxes", "Send refunds"],
    answer: 0,
    explanation: "Phishing messages pretend to be trusted companies to trick you into sharing passwords or account numbers.",
    quick: true,
  },
  {
    id: "soc-g12-17",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.1",
    skill: "Budgeting",
    passage:
      "Kia's take-home pay is $2,400 a month. She follows the 50/30/20 rule: 50% for needs, 30% for wants and 20% for savings and paying down debt.",
    prompt: "Using the 50/30/20 rule, how much should Kia save each month?",
    choices: ["$480", "$720", "$1,200", "$240"],
    answer: 0,
    explanation: "20% of $2,400 is $480. Needs get $1,200 and wants get $720.",
  },
  {
    id: "soc-g12-18",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1",
    skill: "Compound interest",
    passage:
      "Sam deposits $1,000 in a savings account that pays 5% interest, compounded once a year. He makes no other deposits or withdrawals.",
    prompt: "How much will be in the account after 2 years?",
    choices: ["$1,102.50", "$1,100.00", "$1,050.00", "$1,200.00"],
    answer: 0,
    explanation: "Year 1: $1,000 × 1.05 = $1,050. Year 2: $1,050 × 1.05 = $1,102.50.",
  },
  {
    id: "soc-g12-19",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.2",
    skill: "Market structures",
    prompt: "A market with only one seller is a...",
    choices: ["Monopoly", "Oligopoly", "Competition", "Barter"],
    answer: 0,
    explanation: "A monopoly has no competitors, so it has great power over price.",
    quick: true,
  },
  {
    id: "soc-g12-20",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.3",
    skill: "Supply and demand",
    prompt: "A government maximum price, like rent control, is a price...",
    choices: ["Ceiling", "Floor", "Index", "Margin"],
    answer: 0,
    explanation: "A price ceiling set below equilibrium can cause shortages.",
    quick: true,
  },
  {
    id: "soc-g12-21",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.3",
    skill: "Supply and demand",
    passage:
      "Market for school T-shirts: at $2, buyers want 60 and sellers offer 20. At $3, buyers want 45 and sellers offer 30. At $4, buyers want 35 and sellers offer 35. At $5, buyers want 25 and sellers offer 40.",
    prompt: "What is the equilibrium price?",
    choices: ["$4", "$2", "$3", "$5"],
    answer: 0,
    explanation: "At $4, buyers want 35 and sellers offer 35, so quantity demanded equals quantity supplied.",
  },
  {
    id: "soc-g12-22",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.3",
    skill: "Supply and demand",
    prompt: "If a price is set above equilibrium, the market will have a...",
    choices: ["Surplus", "Shortage", "Monopoly", "Recession"],
    answer: 0,
    explanation: "At a high price, sellers offer more than buyers want, so goods pile up unsold.",
    quick: true,
  },
  {
    id: "soc-g12-23",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2.1",
    skill: "Business cycle",
    prompt: "Two quarters in a row of falling real GDP is a common sign of a...",
    choices: ["Recession", "Boom", "Inflation", "Surplus"],
    answer: 0,
    explanation: "It is a rule of thumb. Officially, a group of economists (the NBER) dates U.S. recessions.",
    quick: true,
  },
  {
    id: "soc-g12-24",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2.1",
    skill: "Economic indicators",
    prompt: "The Consumer Price Index (CPI) is used to measure...",
    choices: ["Inflation", "Unemployment", "GDP", "Interest"],
    answer: 0,
    explanation: "The CPI tracks the prices of a 'basket' of goods and services that households buy.",
    quick: true,
  },
  {
    id: "soc-g12-25",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2",
    skill: "Monetary policy",
    prompt: "To fight high inflation, the Federal Reserve usually...",
    choices: ["Raises rates", "Cuts rates", "Prints money", "Cuts taxes"],
    answer: 0,
    explanation: "Higher interest rates make borrowing costlier, which slows spending and price increases.",
    quick: true,
  },
  {
    id: "soc-g12-26",
    subject: "social",
    grade: "12",
    standard: "EPF.E.2.1",
    skill: "Economic indicators",
    prompt: "People without jobs who are actively looking for work are counted as...",
    choices: ["Unemployed", "Retired", "Employed", "Students"],
    answer: 0,
    explanation: "The unemployment rate counts people who are jobless and looking for work.",
    quick: true,
  },
  {
    id: "soc-g12-27",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1.3",
    skill: "Consumer decisions",
    prompt: "When many consumers stop buying a product, producers will likely...",
    choices: ["Make less", "Make more", "Hire workers", "Build plants"],
    answer: 0,
    explanation: "Consumer choices send signals. Lower demand leads firms to cut production.",
    quick: true,
  },
  {
    id: "soc-g12-28",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.1",
    skill: "Paychecks",
    prompt: "Your pay before any taxes or deductions are taken out is...",
    choices: ["Gross pay", "Net pay", "Tips", "A bonus"],
    answer: 0,
    explanation: "Gross pay is total earnings. Net pay, or take-home pay, is what is left after deductions.",
    quick: true,
  },
  {
    id: "soc-g12-29",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1",
    skill: "Paychecks",
    passage:
      "Ana works 20 hours a week at $15 an hour. Each week her employer withholds 7.65% of her gross pay for FICA (Social Security and Medicare) and $18 for federal income tax.",
    prompt: "What is Ana's weekly net pay?",
    choices: ["$259.05", "$300.00", "$277.05", "$282.00"],
    answer: 0,
    explanation: "Gross pay is 20 × $15 = $300. FICA is 7.65% × $300 = $22.95. Net pay is $300 − $22.95 − $18 = $259.05.",
  },
  {
    id: "soc-g12-30",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1",
    skill: "Taxes",
    prompt: "The form a new employee fills out to set federal tax withholding is the...",
    choices: ["W-4", "W-2", "1099", "1040"],
    answer: 0,
    explanation: "The W-4 tells your employer how much federal income tax to withhold.",
    quick: true,
  },
  {
    id: "soc-g12-31",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.3",
    skill: "Paying for college",
    prompt: "College aid based on need that you don't have to repay is a...",
    choices: ["Grant", "Loan", "Mortgage", "Lease"],
    answer: 0,
    explanation: "Grants, like the federal Pell Grant, do not have to be repaid. Loans do.",
    quick: true,
  },
  {
    id: "soc-g12-32",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.3",
    skill: "Paying for college",
    prompt: "The form students file to apply for federal college aid is the...",
    choices: ["FAFSA", "W-4", "1040", "SAT"],
    answer: 0,
    explanation: "The Free Application for Federal Student Aid is used for grants, work-study and federal loans.",
    quick: true,
  },
  {
    id: "soc-g12-33",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.2",
    skill: "Career choices",
    passage:
      "Jordan can (A) take a job now paying $32,000 a year, or (B) spend 2 years as an apprentice electrician earning $20,000 a year, then earn $55,000 a year.",
    prompt: "After 5 years, which option has earned more in total?",
    choices: ["Option B, by $45,000", "Option A, by $45,000", "Option B, by $23,000", "They earn the same"],
    answer: 0,
    explanation: "A: 5 × $32,000 = $160,000. B: 2 × $20,000 + 3 × $55,000 = $205,000. B earns $45,000 more.",
  },
  {
    id: "soc-g12-34",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.1",
    skill: "Spending plans",
    prompt: "Costs that stay the same each month, like rent, are ___ expenses.",
    choices: ["Fixed", "Variable", "Optional", "Hidden"],
    answer: 0,
    explanation: "Fixed expenses stay the same. Variable expenses, like groceries, change from month to month.",
    quick: true,
  },
  {
    id: "soc-g12-35",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.1",
    skill: "Spending plans",
    prompt: "Money set aside for surprise costs like car repairs is an ___ fund.",
    choices: ["Emergency", "Vacation", "Index", "Mutual"],
    answer: 0,
    explanation: "Many experts suggest saving three to six months of expenses in an emergency fund.",
    quick: true,
  },
  {
    id: "soc-g12-36",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.2",
    skill: "Spending plans",
    passage:
      "Devon's monthly take-home pay is $2,000. His plan: rent $750, car payment $300, food $350, phone $60, gas $140 and savings $200.",
    prompt: "How much is left unbudgeted each month?",
    choices: ["$200", "$400", "$0", "$140"],
    answer: 0,
    explanation: "Expenses total $750 + $300 + $350 + $60 + $140 + $200 = $1,800. $2,000 − $1,800 = $200.",
  },
  {
    id: "soc-g12-37",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.3",
    skill: "Renting, leasing, owning",
    prompt: "A contract to use a car for a set time without owning it is a...",
    choices: ["Lease", "Title", "Deed", "Warranty"],
    answer: 0,
    explanation: "Leasing often has lower monthly payments, but you do not own the car at the end.",
    quick: true,
  },
  {
    id: "soc-g12-38",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.4",
    skill: "Mortgages",
    prompt: "Which mortgage keeps the same interest rate for the whole loan?",
    choices: ["Fixed-rate", "Adjustable", "Balloon", "Interest-only"],
    answer: 0,
    explanation: "A fixed-rate mortgage keeps the same rate, so the principal-and-interest payment stays the same.",
    quick: true,
  },
  {
    id: "soc-g12-39",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.1.4",
    skill: "Mortgages",
    prompt: "A $200,000 home needs a 20% down payment. How much is the mortgage loan?",
    choices: ["$160,000", "$40,000", "$180,000", "$200,000"],
    answer: 0,
    explanation: "20% of $200,000 is $40,000 down, so the buyer borrows $200,000 − $40,000 = $160,000.",
    quick: true,
  },
  {
    id: "soc-g12-40",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.2.1",
    skill: "Financial institutions",
    prompt: "The FDIC insures bank deposits up to how much per depositor, per bank, per account type?",
    choices: ["$250,000", "$100,000", "$1,000,000", "$25,000"],
    answer: 0,
    explanation: "FDIC insurance protects deposits up to $250,000 if a bank fails. Credit unions have similar NCUA insurance.",
    quick: true,
  },
  {
    id: "soc-g12-41",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.2.2",
    skill: "Interest",
    passage:
      "Jamal borrows $1,500 at 6% simple interest per year and repays it all after 3 years.",
    prompt: "How much interest will Jamal pay?",
    choices: ["$270", "$90", "$1,770", "$300"],
    answer: 0,
    explanation: "Simple interest = $1,500 × 0.06 × 3 = $270. He repays $1,770 in all.",
  },
  {
    id: "soc-g12-42",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.2.3",
    skill: "Credit cards",
    passage:
      "Maria has a $1,000 credit card balance with a 24% APR. She makes no new purchases and pays nothing this month. (Assume monthly interest is the APR divided by 12.)",
    prompt: "About how much interest is added this month?",
    choices: ["$20", "$240", "$24", "$2"],
    answer: 0,
    explanation: "24% a year is 2% a month. 2% of $1,000 is $20.",
  },
  {
    id: "soc-g12-43",
    subject: "social",
    grade: "12",
    standard: "EPF.MCM.3.1",
    skill: "Credit sources",
    prompt: "Which usually charges the highest interest rates?",
    choices: ["Payday loans", "Credit unions", "Mortgages", "Car loans"],
    answer: 0,
    explanation: "Payday loans often have fees equal to an APR of 300% or more.",
    quick: true,
  },
  {
    id: "soc-g12-44",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Investing",
    prompt: "A fund that tracks a market index like the S&P 500 is an ___ fund.",
    choices: ["Index", "Emergency", "Hedge", "Pension"],
    answer: 0,
    explanation: "Index funds spread money across many companies and usually have low fees.",
    quick: true,
  },
  {
    id: "soc-g12-45",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Compound growth",
    prompt: "By the Rule of 72, money earning 8% a year doubles in about...",
    choices: ["9 years", "8 years", "72 years", "4 years"],
    answer: 0,
    explanation: "Divide 72 by the rate: 72 ÷ 8 = 9 years.",
    quick: true,
  },
  {
    id: "soc-g12-46",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1",
    skill: "Insurance",
    prompt: "The amount you pay before your insurance starts to pay is the...",
    choices: ["Deductible", "Premium", "Policy", "Claim"],
    answer: 0,
    explanation: "The premium is what you pay to have insurance. The deductible is what you pay first when you file a claim.",
    quick: true,
  },
  {
    id: "soc-g12-47",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.3",
    skill: "Giving",
    prompt: "Donating money or time to help others or causes is called...",
    choices: ["Philanthropy", "Inflation", "Arbitrage", "Leverage"],
    answer: 0,
    explanation: "Philanthropy supports nonprofits, which serve communities in many ways.",
    quick: true,
  },
  {
    id: "soc-g12-48",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1.2",
    skill: "Consumer information",
    prompt: "Which source is most reliable for a product's safety ratings?",
    choices: ["An independent testing group", "The company's own ad", "A paid influencer's post", "A pop-up ad"],
    answer: 0,
    explanation: "Independent testers have no stake in selling the product, so their ratings are less biased.",
  },
];

export default questions;
