import type { Question } from "../../types";
// Grade 11 science — NC Standard Course of Study for Science (2023), Chemistry (PS.Chm). Atomic structure and
// nuclear chemistry (PS.Chm.1); the periodic table and periodic trends (PS.Chm.2); bonding and molecular structure
// (PS.Chm.3); reactions and stoichiometry (PS.Chm.4); gases, solutions and acids/bases (PS.Chm.5).
const questions: Question[] = [
  {
    id: "sci-g11-01",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1",
    skill: "Atomic structure",
    prompt: "Isotopes of the same element differ in their number of...",
    choices: ["Neutrons", "Protons", "Electrons", "Elements"],
    answer: 0,
    explanation: "Isotopes have the same number of protons (so the same element) but different numbers of neutrons, so different masses.",
    quick: true,
  },
  {
    id: "sci-g11-02",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Nuclear decay",
    prompt: "An alpha particle is the same as the nucleus of which element?",
    choices: ["Helium", "Hydrogen", "Carbon", "Uranium"],
    answer: 0,
    explanation: "An alpha particle is 2 protons and 2 neutrons, a helium-4 nucleus. Alpha decay lowers the atomic number by 2.",
    quick: true,
  },
  {
    id: "sci-g11-03",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Half-life",
    passage: "A lab has an 80 g sample of a radioactive isotope with a half-life of 5 days.",
    prompt: "How much of the original isotope remains after 15 days?",
    choices: ["10 g", "20 g", "40 g", "0 g"],
    answer: 0,
    explanation: "15 days is 3 half-lives: 80 → 40 → 20 → 10 g. Each half-life cuts the amount in half; it never drops straight to zero.",
  },
  {
    id: "sci-g11-04",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1",
    skill: "Atomic structure",
    prompt: "An element's atomic number equals its number of...",
    choices: ["Protons", "Neutrons", "Shells", "Isotopes"],
    answer: 0,
    explanation: "The atomic number is the proton count, which defines the element. The mass number is protons plus neutrons.",
    quick: true,
  },
  {
    id: "sci-g11-05",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Moving left to right across a period, atomic radius generally...",
    choices: ["Decreases", "Increases", "Stays same", "Doubles"],
    answer: 0,
    explanation: "More protons in the same energy level pull electrons in more tightly, so atoms get smaller across a period.",
    quick: true,
  },
  {
    id: "sci-g11-06",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Which element has the highest electronegativity?",
    choices: ["Fluorine", "Cesium", "Sodium", "Iron"],
    answer: 0,
    explanation: "Electronegativity increases up and to the right on the periodic table, making fluorine the highest.",
    quick: true,
  },
  {
    id: "sci-g11-07",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Group 1 metals are very reactive because they easily do what to one electron?",
    choices: ["Lose it", "Gain it", "Share it", "Split it"],
    answer: 0,
    explanation: "Alkali metals have one valence electron with low ionization energy, so they give it up easily to form +1 ions.",
    quick: true,
  },
  {
    id: "sci-g11-08",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Chemical bonding",
    prompt: "Sodium chloride (NaCl) is held together by which bonds?",
    choices: ["Ionic", "Covalent", "Metallic", "Hydrogen"],
    answer: 0,
    explanation: "Na gives an electron to Cl, forming Na⁺ and Cl⁻ ions that attract each other in an ionic lattice.",
    quick: true,
  },
  {
    id: "sci-g11-09",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Chemical bonding",
    prompt: "Two nonmetal atoms sharing pairs of electrons form which bond?",
    choices: ["Covalent", "Ionic", "Metallic", "Nuclear"],
    answer: 0,
    explanation: "Covalent bonds form when atoms share electrons, typically between nonmetals, as in H₂O and CO₂.",
    quick: true,
  },
  {
    id: "sci-g11-10",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Molecular shape",
    prompt: "What is the molecular shape of a water molecule?",
    choices: ["Bent", "Linear", "Octahedral", "Square"],
    answer: 0,
    explanation: "Oxygen's two lone pairs push the two O–H bonds together into a bent shape (about 104.5°), making water polar.",
    quick: true,
  },
  {
    id: "sci-g11-11",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Bonding and properties",
    passage: "Melting points: sodium chloride (NaCl) 801°C; table sugar (C₁₂H₂₂O₁₁) about 186°C; paraffin wax about 60°C.",
    prompt: "Why does sodium chloride have by far the highest melting point?",
    choices: [
      "Strong attractions between ions in a lattice must be overcome",
      "Its molecules are the largest of the three",
      "It contains the most covalent bonds",
      "Sodium is a metal, and all metals melt above 800°C",
    ],
    answer: 0,
    explanation: "Melting NaCl means pulling apart oppositely charged ions held in a lattice. Sugar and wax only need weaker forces between molecules overcome.",
  },
  {
    id: "sci-g11-12",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4",
    skill: "Balancing equations",
    prompt: "Balance: _H₂ + O₂ → 2H₂O. What coefficient goes before H₂?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "2H₂O has 4 H atoms, so you need 2H₂. Balanced equations show atoms are conserved.",
    quick: true,
  },
  {
    id: "sci-g11-13",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4",
    skill: "The mole",
    prompt: "How many moles are in 36 g of water (molar mass 18 g/mol)?",
    choices: ["2 mol", "0.5 mol", "18 mol", "648 mol"],
    answer: 0,
    explanation: "moles = mass ÷ molar mass = 36 g ÷ 18 g/mol = 2 mol.",
    quick: true,
  },
  {
    id: "sci-g11-14",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4",
    skill: "Reaction types",
    prompt: "A + B → AB is which type of reaction?",
    choices: ["Synthesis", "Decomposition", "Combustion", "Replacement"],
    answer: 0,
    explanation: "In synthesis, simpler substances combine into one product. Decomposition is the reverse: AB → A + B.",
    quick: true,
  },
  {
    id: "sci-g11-15",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4",
    skill: "Limiting reactant",
    passage: "Reaction: 2H₂ + O₂ → 2H₂O. A container holds 4 mol of H₂ and 1 mol of O₂, and the reaction runs to completion.",
    prompt: "Which reactant is limiting, and how much water forms?",
    choices: ["O₂; 2 mol H₂O", "H₂; 4 mol H₂O", "O₂; 1 mol H₂O", "H₂; 2 mol H₂O"],
    answer: 0,
    explanation: "1 mol O₂ needs only 2 mol H₂, so O₂ runs out first. 1 mol O₂ makes 2 mol H₂O, and 2 mol H₂ is left over.",
  },
  {
    id: "sci-g11-16",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5",
    skill: "Gas laws",
    prompt: "At constant temperature, doubling the pressure on a gas makes its volume...",
    choices: ["Halve", "Double", "Stay the same", "Quadruple"],
    answer: 0,
    explanation: "Boyle's law: P₁V₁ = P₂V₂. Pressure and volume are inversely related, so doubling P halves V.",
    quick: true,
  },
  {
    id: "sci-g11-17",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5",
    skill: "Acids and bases",
    prompt: "A solution with a pH of 3 is...",
    choices: ["Acidic", "Basic", "Neutral", "Salty"],
    answer: 0,
    explanation: "pH below 7 is acidic, 7 is neutral, and above 7 is basic. Each pH step is a tenfold change in H⁺ concentration.",
    quick: true,
  },
  {
    id: "sci-g11-18",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5",
    skill: "Solutions",
    prompt: "Molarity is moles of solute per...",
    choices: ["L of solution", "kg of solvent", "g of solute", "mL of water"],
    answer: 0,
    explanation: "Molarity (M) = mol solute ÷ liters of solution. Moles per kilogram of solvent is molality, a different unit.",
    quick: true,
  },
];
export default questions;
