import type { Question } from "../../types";
// Grade 2 science — NC Standard Course of Study for Science (2023). Solids and liquids changing with heating and
// cooling (PS.2.1), weather, weather tools and seasonal patterns (ESS.2.1), animal life cycles (LS.2.1), and how
// offspring are like and unlike their parents (LS.2.2).
const questions: Question[] = [
  {
    id: "sci-g2-01",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "What happens to ice when it gets warm?",
    choices: ["It melts", "It grows", "It freezes", "It hardens"],
    answer: 0,
    explanation: "Heat makes ice melt. The solid ice turns into liquid water.",
    quick: true,
  },
  {
    id: "sci-g2-02",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Water in a freezer turns into...",
    choices: ["Ice", "Steam", "Juice", "Sand"],
    answer: 0,
    explanation: "Cooling water enough makes it freeze. Liquid water becomes solid ice.",
    quick: true,
  },
  {
    id: "sci-g2-03",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Butter in a hot pan will...",
    choices: ["Melt", "Freeze", "Grow", "Turn to ice"],
    answer: 0,
    explanation: "Heat changes solid butter into a liquid. That change is called melting.",
    quick: true,
  },
  {
    id: "sci-g2-04",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Melted chocolate put in a fridge becomes...",
    choices: ["Solid again", "A gas", "Water", "Sand"],
    answer: 0,
    explanation: "Cooling turns the liquid chocolate back into a solid. Some changes can go back and forth.",
    quick: true,
  },
  {
    id: "sci-g2-05",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.2",
    skill: "Water before and after freezing",
    passage:
      "Maria filled a cup with water up to a line and weighed it. She put the cup in the freezer overnight. In the morning the ice was above the line. She weighed the cup again, and it weighed the same.",
    prompt: "What changed when Maria's water froze?",
    choices: ["It took up more space", "It got heavier", "It got lighter", "Nothing changed at all"],
    answer: 0,
    explanation: "Water spreads out a little when it freezes, so ice takes up more space. The amount of water did not change, so the weight stayed the same.",
  },
  {
    id: "sci-g2-06",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Solids and liquids",
    prompt: "Is ice a solid or a liquid?",
    choices: ["Solid", "Liquid", "Gas", "Neither"],
    answer: 0,
    explanation: "Ice is a solid. It keeps its own shape. Liquid water takes the shape of its cup.",
    quick: true,
  },
  {
    id: "sci-g2-07",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather tools",
    prompt: "What tool shows which way the wind blows?",
    choices: ["Wind vane", "Ruler", "Scale", "Magnet"],
    answer: 0,
    explanation: "A wind vane turns to point into the wind, showing the direction it is blowing from.",
    quick: true,
  },
  {
    id: "sci-g2-08",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather tools",
    prompt: "A rain gauge measures...",
    choices: ["Rain", "Wind", "Heat", "Sunlight"],
    answer: 0,
    explanation: "A rain gauge collects rain so you can measure how much fell.",
    quick: true,
  },
  {
    id: "sci-g2-09",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Clouds are made of tiny...",
    choices: ["Water drops", "Cotton", "Smoke", "Feathers"],
    answer: 0,
    explanation: "Clouds are made of tiny drops of water or bits of ice floating in the air.",
    quick: true,
  },
  {
    id: "sci-g2-10",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Which storm has lightning and thunder?",
    choices: ["Thunderstorm", "Snow flurry", "Fog", "Drizzle"],
    answer: 0,
    explanation: "Thunderstorms have lightning, and lightning makes the loud sound of thunder.",
    quick: true,
  },
  {
    id: "sci-g2-11",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Which weather is best for flying a kite?",
    choices: ["Windy", "Calm", "Foggy", "Rainy"],
    answer: 0,
    explanation: "Moving air, or wind, lifts a kite into the sky.",
    quick: true,
  },
  {
    id: "sci-g2-12",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather patterns",
    passage:
      "A class kept a weather chart for one week. Monday: sunny. Tuesday: rainy. Wednesday: rainy. Thursday: sunny. Friday: rainy.",
    prompt: "Which kind of weather happened the most that week?",
    choices: ["Rainy", "Sunny", "Snowy", "Windy"],
    answer: 0,
    explanation: "There were 3 rainy days and 2 sunny days. Counting the days on a chart helps us find weather patterns.",
  },
  {
    id: "sci-g2-13",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather patterns",
    prompt: "In North Carolina, which season is usually the hottest?",
    choices: ["Summer", "Winter", "Fall", "Spring"],
    answer: 0,
    explanation: "Summer is usually the hottest season. Weather follows a pattern through the year.",
    quick: true,
  },
  {
    id: "sci-g2-14",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "A caterpillar grows into a...",
    choices: ["Butterfly", "Frog", "Bird", "Bee"],
    answer: 0,
    explanation: "A butterfly's life cycle is egg, caterpillar (larva), chrysalis (pupa), then adult butterfly.",
    quick: true,
  },
  {
    id: "sci-g2-15",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "What does a tadpole grow into?",
    choices: ["Frog", "Fish", "Snake", "Turtle"],
    answer: 0,
    explanation: "A tadpole grows legs, loses its tail and becomes a frog.",
    quick: true,
  },
  {
    id: "sci-g2-16",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "What comes first in a chicken's life cycle?",
    choices: ["Egg", "Chick", "Hen", "Rooster"],
    answer: 0,
    explanation: "A chicken starts as an egg, hatches into a chick, and grows into an adult hen or rooster.",
    quick: true,
  },
  {
    id: "sci-g2-17",
    subject: "science",
    grade: "2",
    standard: "LS.2.2",
    skill: "Traits from parents",
    prompt: "Why do puppies look like their parents?",
    choices: ["Share traits", "Same food", "Copying them", "Good luck"],
    answer: 0,
    explanation: "Babies get traits from their parents, like fur color and ear shape. That is why they look alike.",
    quick: true,
  },
  {
    id: "sci-g2-18",
    subject: "science",
    grade: "2",
    standard: "LS.2.2",
    skill: "Traits from parents",
    prompt: "Kittens from the same mom can have different...",
    choices: ["Fur colors", "Number of legs", "Animal kinds", "Number of eyes"],
    answer: 0,
    explanation: "Kittens are like their parents in many ways but can still differ in things like fur color.",
    quick: true,
  },
];
export default questions;
