import type { Question } from "../../types";
// Grade 5 science — NC Standard Course of Study for Science (2023). Matter and energy interactions: weight before and
// after, mixtures, heating/cooling (PS.5.1); force and motion: gravity, friction, mass, speed (PS.5.2); weather and the
// water cycle (ESS.5.1); human body organization (LS.5.1); ecosystems (LS.5.2); inherited vs. acquired traits and
// instinct vs. learned behavior (LS.5.3).
const questions: Question[] = [
  {
    id: "sci-g5-01",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.1",
    skill: "Conservation of mass",
    passage:
      "Sam put vinegar and a small cup of baking soda inside a zip bag and sealed it. The whole bag weighed 200 g. Then he tipped the cup so they mixed. The bag bubbled and puffed up, but nothing escaped.",
    prompt: "What will the sealed bag weigh now?",
    choices: ["200 g", "More than 200 g", "Less than 200 g", "0 g, because gas has no weight"],
    answer: 0,
    explanation: "Matter is not created or destroyed. The gas made is still inside the sealed bag, so the total weight stays 200 g.",
  },
  {
    id: "sci-g5-02",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.2",
    skill: "Mixtures and new substances",
    prompt: "Stirring sand and iron filings together makes a...",
    choices: ["Mixture", "New substance", "Gas", "Liquid"],
    answer: 0,
    explanation: "In a mixture, each part keeps its properties. You could pull the iron out with a magnet.",
    quick: true,
  },
  {
    id: "sci-g5-03",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.2",
    skill: "Mixtures and new substances",
    prompt: "Which change makes a new substance?",
    choices: ["Burning wood", "Melting ice", "Cutting paper", "Salt in water"],
    answer: 0,
    explanation: "Burning turns wood into ash, smoke and gases, which are new substances. The others only change shape or state or mix.",
    quick: true,
  },
  {
    id: "sci-g5-04",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.3",
    skill: "Heating and cooling materials",
    prompt: "Hot water helps loosen a tight metal jar lid because heated metal...",
    choices: ["Expands", "Shrinks", "Melts", "Freezes"],
    answer: 0,
    explanation: "Most materials expand when heated. The metal lid grows slightly, making it easier to twist off.",
    quick: true,
  },
  {
    id: "sci-g5-05",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Gravity and friction",
    prompt: "Which force pulls objects toward the center of Earth?",
    choices: ["Gravity", "Friction", "Magnetism", "Air resistance"],
    answer: 0,
    explanation: "Gravity pulls everything toward Earth's center. That is why a dropped ball falls down.",
    quick: true,
  },
  {
    id: "sci-g5-06",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Speed",
    prompt: "A car travels 120 miles in 2 hours. What is its average speed?",
    choices: ["60 mph", "240 mph", "122 mph", "30 mph"],
    answer: 0,
    explanation: "Speed = distance ÷ time. 120 miles ÷ 2 hours = 60 miles per hour.",
    quick: true,
  },
  {
    id: "sci-g5-07",
    subject: "science",
    grade: "5",
    standard: "LS.5.3",
    skill: "Inherited and acquired traits",
    prompt: "A scar from falling off a bike is what kind of trait?",
    choices: ["Acquired", "Inherited", "Instinct", "Dominant"],
    answer: 0,
    explanation: "Acquired traits come from life experiences, not from parents. A scar cannot be passed to your children.",
    quick: true,
  },
  {
    id: "sci-g5-08",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Mass and motion",
    passage:
      "Two identical wagons are pulled with the same force across the same smooth sidewalk. Wagon A is empty. Wagon B is loaded with bricks.",
    prompt: "Which wagon speeds up faster, and why?",
    choices: [
      "Wagon A, because it has less mass",
      "Wagon B, because more weight means more speed",
      "Both the same, because the force is the same",
      "Neither moves, because friction stops them",
    ],
    answer: 0,
    explanation: "With the same force, an object with less mass changes its motion more quickly. More mass means slower speed-up.",
  },
  {
    id: "sci-g5-09",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.1",
    skill: "Weather data",
    passage:
      "High temperatures in Raleigh one week in March: Monday 58°F, Tuesday 62°F, Wednesday 49°F, Thursday 51°F, Friday 55°F.",
    prompt: "Between which two days did the high temperature drop the most?",
    choices: ["Tuesday to Wednesday", "Monday to Tuesday", "Wednesday to Thursday", "Thursday to Friday"],
    answer: 0,
    explanation: "From Tuesday to Wednesday it fell 13°F (62 to 49). A big, sudden drop like that often means a cold front passed.",
  },
  {
    id: "sci-g5-10",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "What provides the energy that drives the water cycle?",
    choices: ["The sun", "The moon", "Earthquakes", "Volcanoes"],
    answer: 0,
    explanation: "The sun heats water so it evaporates. That energy keeps water moving through the cycle.",
    quick: true,
  },
  {
    id: "sci-g5-11",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "Water vapor cooling into tiny droplets is called...",
    choices: ["Condensation", "Evaporation", "Precipitation", "Runoff"],
    answer: 0,
    explanation: "Condensation is gas turning to liquid as it cools. It forms clouds and the water drops on a cold glass.",
    quick: true,
  },
  {
    id: "sci-g5-12",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "Plants give off water vapor through their leaves. This is...",
    choices: ["Transpiration", "Condensation", "Precipitation", "Erosion"],
    answer: 0,
    explanation: "Transpiration is how plants release water vapor from tiny openings in their leaves.",
    quick: true,
  },
  {
    id: "sci-g5-13",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1",
    skill: "Weather prediction",
    prompt: "Air pressure is falling quickly. What weather is most likely soon?",
    choices: ["Stormy", "Clear and dry", "No change", "Cold and sunny"],
    answer: 0,
    explanation: "Falling air pressure usually means rising air, clouds and storms. Rising pressure usually brings clearer skies.",
    quick: true,
  },
  {
    id: "sci-g5-14",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.1",
    skill: "Body organization",
    prompt: "Which list goes from smallest to largest in the human body?",
    choices: [
      "Cell, tissue, organ, organ system, organism",
      "Organ, cell, tissue, organism, organ system",
      "Tissue, cell, organ system, organ, organism",
      "Organism, organ system, organ, tissue, cell",
    ],
    answer: 0,
    explanation: "Cells form tissues, tissues form organs, organs work together in systems, and systems make up the whole organism.",
  },
  {
    id: "sci-g5-15",
    subject: "science",
    grade: "5",
    standard: "LS.5.1",
    skill: "Body systems",
    prompt: "Which organ pumps blood through your body?",
    choices: ["Heart", "Lungs", "Stomach", "Brain"],
    answer: 0,
    explanation: "The heart is a muscle that pumps blood through the circulatory system.",
    quick: true,
  },
  {
    id: "sci-g5-16",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.1",
    skill: "Ecosystems",
    prompt: "In an estuary, river fresh water mixes with...",
    choices: ["Ocean water", "Lava", "Oil", "Snow"],
    answer: 0,
    explanation: "Estuaries like North Carolina's sounds mix fresh and salt water. They are nurseries for many fish and shellfish.",
    quick: true,
  },
  {
    id: "sci-g5-17",
    subject: "science",
    grade: "5",
    standard: "LS.5.2",
    skill: "Food webs",
    prompt: "Organisms that break down dead plants and animals are...",
    choices: ["Decomposers", "Producers", "Predators", "Herbivores"],
    answer: 0,
    explanation: "Decomposers like fungi and bacteria break down dead things and return nutrients to the soil.",
    quick: true,
  },
  {
    id: "sci-g5-18",
    subject: "science",
    grade: "5",
    standard: "LS.5.3",
    skill: "Instinct and learned behavior",
    prompt: "Which is a learned behavior?",
    choices: ["Riding a bike", "Blinking", "Sneezing", "Spinning webs"],
    answer: 0,
    explanation: "You must practice to ride a bike, so it is learned. Blinking, sneezing and a spider spinning webs happen by instinct.",
    quick: true,
  },
];
export default questions;
