import type { Question } from "../../types";
// Grade 6 science — NC Standard Course of Study for Science (2023). Particle motion, phase changes and physical
// properties such as density (PS.6.1); heat transfer, expansion and contraction, and insulators (PS.6.2); wave
// properties and the electromagnetic spectrum and sight (PS.6.3); sun-Earth-moon motion (seasons, tides, phases,
// eclipses) and the planets (ESS.6.1); Earth's layers and plate tectonics (ESS.6.2); soil quality and land use
// (ESS.6.3); photosynthesis, respiration and transpiration, and vascular vs. nonvascular plants (LS.6.1); energy
// flow from the sun through ecosystems, and biomes (LS.6.2).
const questions: Question[] = [
  {
    id: "sci-g6-01",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.3",
    skill: "Density",
    prompt: "Density equals mass divided by...",
    choices: ["Volume", "Weight", "Speed", "Area"],
    answer: 0,
    explanation: "Density = mass ÷ volume. It tells how much matter is packed into a given space.",
    quick: true,
  },
  {
    id: "sci-g6-02",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.3",
    skill: "Density",
    passage:
      "A small block has a mass of 60 g and a volume of 20 cm³. Fresh water has a density of 1 g/cm³.",
    prompt: "What is the block's density, and will it float or sink in fresh water?",
    choices: ["3 g/cm³; it sinks", "3 g/cm³; it floats", "1200 g/cm³; it sinks", "0.33 g/cm³; it floats"],
    answer: 0,
    explanation: "60 g ÷ 20 cm³ = 3 g/cm³. Objects denser than water (more than 1 g/cm³) sink.",
  },
  {
    id: "sci-g6-03",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.2",
    skill: "Particle motion",
    prompt: "When a substance is heated, its particles...",
    choices: ["Move faster", "Slow down", "Get bigger", "Stop moving"],
    answer: 0,
    explanation: "Adding thermal energy makes particles move faster and spread apart. The particles themselves do not grow.",
    quick: true,
  },
  {
    id: "sci-g6-04",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "A metal spoon in hot soup gets hot. This transfer is...",
    choices: ["Conduction", "Convection", "Radiation", "Insulation"],
    answer: 0,
    explanation: "Conduction is heat moving through direct contact, particle to particle, like along a metal spoon.",
    quick: true,
  },
  {
    id: "sci-g6-05",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "Warm air rising and cool air sinking in a room is...",
    choices: ["Convection", "Conduction", "Radiation", "Reflection"],
    answer: 0,
    explanation: "Convection moves heat through fluids (liquids and gases) as warmer, less dense material rises and cooler material sinks.",
    quick: true,
  },
  {
    id: "sci-g6-06",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "How does the sun's energy reach Earth through space?",
    choices: ["Radiation", "Conduction", "Convection", "Friction"],
    answer: 0,
    explanation: "Space is nearly empty, so heat cannot be conducted or convected. It travels as radiation (electromagnetic waves).",
    quick: true,
  },
  {
    id: "sci-g6-07",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.3",
    skill: "Insulators",
    passage:
      "Students poured 80°C water into three cups of the same size: metal, glass and foam. After 20 minutes the water temperatures were: metal 45°C, glass 55°C, foam 70°C.",
    prompt: "Which conclusion do the data best support?",
    choices: [
      "Foam is the best insulator of the three",
      "Metal is the best insulator of the three",
      "All three cups insulate equally well",
      "Glass let the most heat escape",
    ],
    answer: 0,
    explanation: "The foam cup lost the least heat (only 10°C), so it slowed heat transfer best. Metal lost the most, so it is a good conductor.",
  },
  {
    id: "sci-g6-08",
    subject: "science",
    grade: "6",
    standard: "PS.6.3",
    skill: "Waves",
    prompt: "A wave's height from rest to crest, linked to its energy, is its...",
    choices: ["Amplitude", "Frequency", "Wavelength", "Speed"],
    answer: 0,
    explanation: "Amplitude is how far a wave moves from its rest position. Bigger amplitude means more energy, like a louder sound.",
    quick: true,
  },
  {
    id: "sci-g6-09",
    subject: "science",
    grade: "6",
    standard: "PS.6.3",
    skill: "Waves",
    prompt: "Sound cannot travel through...",
    choices: ["Empty space", "Water", "Steel", "Air"],
    answer: 0,
    explanation: "Sound is a mechanical wave that needs particles to vibrate. Space is a vacuum, so there is no sound there.",
    quick: true,
  },
  {
    id: "sci-g6-10",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1",
    skill: "Seasons",
    prompt: "What mainly causes Earth's seasons?",
    choices: ["Tilted axis", "Sun distance", "Moon's pull", "Cloud cover"],
    answer: 0,
    explanation: "Earth's tilted axis makes each hemisphere get more direct sunlight for part of the year. Distance to the sun barely changes.",
    quick: true,
  },
  {
    id: "sci-g6-11",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1",
    skill: "Gravity and orbits",
    prompt: "What keeps the planets in orbit around the sun?",
    choices: ["Gravity", "Magnetism", "Friction", "Solar wind"],
    answer: 0,
    explanation: "The sun's gravity pulls on the planets and keeps them moving in orbits.",
    quick: true,
  },
  {
    id: "sci-g6-12",
    subject: "science",
    grade: "6",
    standard: "ESS.6.2",
    skill: "Plate tectonics",
    passage:
      "An ocean plate and a continental plate are moving toward each other. The denser ocean plate slides beneath the continental plate.",
    prompt: "Which features are most likely to form at this boundary?",
    choices: [
      "A deep ocean trench and a chain of volcanoes",
      "A mid-ocean ridge with new seafloor",
      "A wide, flat plain with no earthquakes",
      "A river delta",
    ],
    answer: 0,
    explanation: "When one plate subducts, a trench forms and the sinking plate melts, feeding volcanoes, like the Andes. Ridges form where plates pull apart.",
  },
  {
    id: "sci-g6-13",
    subject: "science",
    grade: "6",
    standard: "ESS.6.2",
    skill: "Changes to Earth's surface",
    prompt: "Weathering and erosion are examples of which kind of force?",
    choices: ["Destructive", "Constructive", "Magnetic", "Electric"],
    answer: 0,
    explanation: "Destructive forces wear land down. Constructive forces, like volcanoes and deposition, build land up.",
    quick: true,
  },
  {
    id: "sci-g6-14",
    subject: "science",
    grade: "6",
    standard: "ESS.6.3",
    skill: "Soil stewardship",
    prompt: "Farmers plant cover crops in winter mainly to...",
    choices: ["Stop erosion", "Kill insects", "Warm the air", "Dry the soil"],
    answer: 0,
    explanation: "Cover crop roots hold soil in place and add nutrients, protecting soil quality between harvests.",
    quick: true,
  },
  {
    id: "sci-g6-15",
    subject: "science",
    grade: "6",
    standard: "LS.6.1",
    skill: "Plant processes",
    prompt: "Plants make their own food (sugar) using light by...",
    choices: ["Photosynthesis", "Respiration", "Digestion", "Pollination"],
    answer: 0,
    explanation: "In photosynthesis, plants use light energy, carbon dioxide and water to make sugar and release oxygen.",
    quick: true,
  },
  {
    id: "sci-g6-16",
    subject: "science",
    grade: "6",
    standard: "LS.6.1",
    skill: "Plant structures",
    prompt: "Tiny openings in leaves that let gases in and out are...",
    choices: ["Stomata", "Xylem", "Roots", "Petals"],
    answer: 0,
    explanation: "Stomata let carbon dioxide in and oxygen and water vapor out. Xylem carries water up from the roots.",
    quick: true,
  },
  {
    id: "sci-g6-17",
    subject: "science",
    grade: "6",
    standard: "LS.6.2",
    skill: "Biomes",
    prompt: "Which biome has frozen ground (permafrost) and almost no trees?",
    choices: ["Tundra", "Rainforest", "Grassland", "Desert"],
    answer: 0,
    explanation: "The tundra is cold with permafrost, so deep tree roots cannot grow. Low plants like mosses and lichens survive.",
    quick: true,
  },
  {
    id: "sci-g6-18",
    subject: "science",
    grade: "6",
    standard: "LS.6.2",
    skill: "Abiotic and biotic factors",
    passage:
      "A student grew bean plants in four trays with the same soil and water. Tray 1 got 12 hours of light a day, Tray 2 got 8 hours, Tray 3 got 4 hours, and Tray 4 got none. After two weeks, Tray 1 plants were tallest and greenest; Tray 4 plants were pale and weak.",
    prompt: "Which factor was tested, and what type of factor is it?",
    choices: [
      "Amount of sunlight; abiotic",
      "Amount of sunlight; biotic",
      "Type of soil; abiotic",
      "Kind of plant; biotic",
    ],
    answer: 0,
    explanation: "Only light changed between trays, so light was tested. Sunlight is nonliving, which makes it an abiotic factor.",
  },
  {
    id: "sci-g6-19",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "Which gas do plants take in to make sugar?",
    choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    answer: 0,
    explanation: "Plants take in carbon dioxide through their leaves and combine it with water to make sugar.",
    quick: true,
  },
  {
    id: "sci-g6-20",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "Which gas do plants release during photosynthesis?",
    choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Methane"],
    answer: 0,
    explanation: "Photosynthesis releases oxygen into the air, which animals and people breathe.",
    quick: true,
  },
  {
    id: "sci-g6-21",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "The green pigment that captures light energy is...",
    choices: ["Chlorophyll", "Glucose", "Xylem", "Pollen"],
    answer: 0,
    explanation: "Chlorophyll in chloroplasts absorbs light energy to power photosynthesis. It also makes leaves green.",
    quick: true,
  },
  {
    id: "sci-g6-22",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "In which cell part does photosynthesis happen?",
    choices: ["Chloroplast", "Nucleus", "Cell wall", "Vacuole"],
    answer: 0,
    explanation: "Chloroplasts hold chlorophyll and are where light energy is used to make sugar.",
    quick: true,
  },
  {
    id: "sci-g6-23",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "Photosynthesis changes light energy into...",
    choices: ["Chemical energy", "Sound energy", "Nuclear energy", "Magnetic energy"],
    answer: 0,
    explanation: "The energy from light is stored in the chemical bonds of sugar (glucose).",
  },
  {
    id: "sci-g6-24",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    prompt: "Photosynthesis needs light, carbon dioxide and...",
    choices: ["Water", "Oxygen", "Soil", "Nitrogen"],
    answer: 0,
    explanation: "Plants use light energy to combine carbon dioxide and water into sugar, releasing oxygen.",
    quick: true,
  },
  {
    id: "sci-g6-25",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Respiration and transpiration",
    prompt: "Plants break down sugar to release energy by...",
    choices: ["Respiration", "Photosynthesis", "Transpiration", "Pollination"],
    answer: 0,
    explanation: "Like animals, plants use cellular respiration to release the energy stored in sugar.",
    quick: true,
  },
  {
    id: "sci-g6-26",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Respiration and transpiration",
    prompt: "Water evaporating from leaves through stomata is...",
    choices: ["Transpiration", "Respiration", "Condensation", "Germination"],
    answer: 0,
    explanation: "Transpiration pulls water up from the roots as it evaporates out of the leaves.",
    quick: true,
  },
  {
    id: "sci-g6-27",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Respiration and transpiration",
    prompt: "Guard cells around a stoma control the opening to...",
    choices: ["Let gases pass", "Make pollen", "Absorb soil", "Store seeds"],
    answer: 0,
    explanation: "Guard cells open and close each stoma, letting carbon dioxide in and oxygen and water vapor out.",
    quick: true,
  },
  {
    id: "sci-g6-28",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.2",
    skill: "Vascular and nonvascular plants",
    prompt: "Xylem tubes in a plant carry...",
    choices: ["Water upward", "Sugar downward", "Pollen out", "Air in"],
    answer: 0,
    explanation: "Xylem carries water and minerals from the roots up to the leaves. Phloem carries sugar.",
    quick: true,
  },
  {
    id: "sci-g6-29",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.2",
    skill: "Vascular and nonvascular plants",
    prompt: "Phloem tubes carry which material through a plant?",
    choices: ["Sugar", "Soil", "Oxygen", "Sand"],
    answer: 0,
    explanation: "Phloem moves sugar made in the leaves to other parts of the plant.",
    quick: true,
  },
  {
    id: "sci-g6-30",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.2",
    skill: "Vascular and nonvascular plants",
    prompt: "Which plant is nonvascular?",
    choices: ["Moss", "Oak tree", "Fern", "Corn"],
    answer: 0,
    explanation: "Mosses have no xylem or phloem, so they stay small and grow in damp places.",
    quick: true,
  },
  {
    id: "sci-g6-31",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.2",
    skill: "Vascular and nonvascular plants",
    prompt: "Why do mosses grow low and close to the ground?",
    choices: ["No water tubes", "Too much sun", "Heavy flowers", "Deep roots"],
    answer: 0,
    explanation: "Without vascular tissue, mosses can only move water short distances, cell to cell.",
    quick: true,
  },
  {
    id: "sci-g6-32",
    subject: "science",
    grade: "6",
    standard: "LS.6.2.1",
    skill: "Energy flow from the sun",
    prompt: "The original source of energy in most food chains is...",
    choices: ["The sun", "Soil", "Water", "Decomposers"],
    answer: 0,
    explanation: "Plants capture the sun's energy and pass it to consumers that eat them.",
    quick: true,
  },
  {
    id: "sci-g6-33",
    subject: "science",
    grade: "6",
    standard: "LS.6.2.2",
    skill: "Biomes",
    prompt: "Which biome has the most rain and the most kinds of living things?",
    choices: ["Rainforest", "Desert", "Tundra", "Taiga"],
    answer: 0,
    explanation: "Tropical rainforests are warm and very wet, and they hold more species than any other land biome.",
    quick: true,
  },
  {
    id: "sci-g6-34",
    subject: "science",
    grade: "6",
    standard: "LS.6.2.2",
    skill: "Biomes",
    prompt: "A forest of evergreen conifers with long, cold winters is...",
    choices: ["Taiga", "Grassland", "Desert", "Rainforest"],
    answer: 0,
    explanation: "The taiga (boreal forest) is full of cone-bearing evergreens that survive cold winters.",
    quick: true,
  },
  {
    id: "sci-g6-35",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.2",
    skill: "Particles and phase changes",
    prompt: "In which state are particles packed tightly and only vibrate in place?",
    choices: ["Solid", "Liquid", "Gas", "Plasma"],
    answer: 0,
    explanation: "Solid particles are locked close together and just vibrate. Liquid particles slide past each other, and gas particles fly apart.",
    quick: true,
  },
  {
    id: "sci-g6-36",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.3",
    skill: "Physical properties",
    prompt: "Which property stays the same no matter the sample size?",
    choices: ["Density", "Mass", "Volume", "Weight"],
    answer: 0,
    explanation: "Density depends only on the substance. Mass, volume and weight change with the amount.",
    quick: true,
  },
  {
    id: "sci-g6-37",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Expansion and contraction",
    prompt: "Gaps are left in sidewalks because concrete in summer heat...",
    choices: ["Expands", "Shrinks", "Melts", "Evaporates"],
    answer: 0,
    explanation: "Heated materials expand. The gaps give the concrete room so it does not crack.",
    quick: true,
  },
  {
    id: "sci-g6-38",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.3",
    skill: "Insulators",
    prompt: "Double-pane windows keep homes warm because the trapped gas between panes is a good...",
    choices: ["Insulator", "Conductor", "Radiator", "Mirror"],
    answer: 0,
    explanation: "Gases like air conduct heat poorly, so the layer between the panes slows heat from escaping.",
    quick: true,
  },
  {
    id: "sci-g6-39",
    subject: "science",
    grade: "6",
    standard: "PS.6.3.1",
    skill: "Wave properties",
    prompt: "The number of waves that pass a point each second is...",
    choices: ["Frequency", "Amplitude", "Wavelength", "Crest"],
    answer: 0,
    explanation: "Frequency counts waves per second and is measured in hertz (Hz).",
    quick: true,
  },
  {
    id: "sci-g6-40",
    subject: "science",
    grade: "6",
    standard: "PS.6.3.2",
    skill: "Light and sight",
    prompt: "We see a red apple because it...",
    choices: ["Reflects red", "Absorbs red", "Makes light", "Bends red"],
    answer: 0,
    explanation: "The apple absorbs most colors and reflects red light into our eyes.",
    quick: true,
  },
  {
    id: "sci-g6-41",
    subject: "science",
    grade: "6",
    standard: "PS.6.3.2",
    skill: "Light and sight",
    prompt: "Which kind of EM wave can human eyes detect?",
    choices: ["Visible light", "Radio waves", "X-rays", "Microwaves"],
    answer: 0,
    explanation: "Visible light is the only part of the electromagnetic spectrum our eyes can see.",
    quick: true,
  },
  {
    id: "sci-g6-42",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1.1",
    skill: "Sun, Earth and moon",
    prompt: "A solar eclipse happens when the moon is between...",
    choices: ["Sun and Earth", "Earth and Mars", "Two stars", "Earth and moon"],
    answer: 0,
    explanation: "In a solar eclipse, the moon passes between the sun and Earth and blocks the sun.",
    quick: true,
  },
  {
    id: "sci-g6-43",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1.1",
    skill: "Sun, Earth and moon",
    prompt: "Ocean tides are caused mainly by the gravity of the...",
    choices: ["Moon", "Wind", "Clouds", "Earth's core"],
    answer: 0,
    explanation: "The moon's gravity pulls on Earth's oceans, making bulges that cause high and low tides.",
    quick: true,
  },
  {
    id: "sci-g6-44",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1.2",
    skill: "Planets",
    passage:
      "Surface gravity compared with Earth (Earth = 1.00): Mars 0.38, Venus 0.91, Jupiter 2.53.",
    prompt: "About how much would a student who weighs 100 pounds on Earth weigh on Mars?",
    choices: ["38 pounds", "100 pounds", "253 pounds", "91 pounds"],
    answer: 0,
    explanation: "Weight depends on gravity. Mars has 0.38 times Earth's gravity, so 100 × 0.38 = 38 pounds. Mass stays the same.",
  },
  {
    id: "sci-g6-45",
    subject: "science",
    grade: "6",
    standard: "ESS.6.2.1",
    skill: "Earth's layers",
    prompt: "Earth's thin, rocky outer layer is the...",
    choices: ["Crust", "Mantle", "Outer core", "Inner core"],
    answer: 0,
    explanation: "The crust is the thinnest layer. Below it are the mantle, outer core and inner core.",
    quick: true,
  },
  {
    id: "sci-g6-46",
    subject: "science",
    grade: "6",
    standard: "ESS.6.3.2",
    skill: "Land use",
    prompt: "Which practice best protects soil on a farm?",
    choices: ["Crop rotation", "Clear-cutting", "Overgrazing", "Bare fields"],
    answer: 0,
    explanation: "Rotating crops keeps soil healthy and reduces erosion and nutrient loss.",
    quick: true,
  },
  {
    id: "sci-g6-47",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Photosynthesis",
    passage:
      "Students put a water plant in a test tube. Bubbles of gas formed on its leaves. In bright light: 30 bubbles per minute. In dim light: 8 per minute. In the dark: 0.",
    prompt: "Which conclusion do the results support?",
    choices: [
      "Photosynthesis needs light",
      "Photosynthesis needs darkness",
      "Plants make oxygen only at night",
      "Light has no effect on plants",
    ],
    answer: 0,
    explanation: "Bubbles are oxygen from photosynthesis. More light made more bubbles, so photosynthesis needs light.",
  },
  {
    id: "sci-g6-48",
    subject: "science",
    grade: "6",
    standard: "LS.6.1.1",
    skill: "Respiration and transpiration",
    passage:
      "Rosa tied a clear plastic bag over a leafy branch on a sunny morning. By afternoon, drops of water had formed inside the bag.",
    prompt: "Why did water collect inside the bag?",
    choices: [
      "Water left the leaves by transpiration",
      "Rain leaked into the bag",
      "The plant made water from sugar",
      "The bag melted in the sun",
    ],
    answer: 0,
    explanation: "Leaves release water vapor through stomata. The vapor condensed into drops on the bag.",
  },
];
export default questions;
