import type { Question } from "../../types";
// Grade 7 science — NC Standard Course of Study for Science (2023). Motion, speed, velocity and motion graphs
// (PS.7.1); kinetic/potential energy and conservation in mechanical systems (PS.7.2); atmosphere, water cycle and
// weather (ESS.7.1); air quality and stewardship (ESS.7.2); cells, single-celled organisms and body systems (LS.7.1);
// reproduction and heredity (LS.7.2).
const questions: Question[] = [
  {
    id: "sci-g7-01",
    subject: "science",
    grade: "7",
    standard: "PS.7.1",
    skill: "Motion graphs",
    passage:
      "A distance-time graph for a bike ride shows a straight line rising from 0 to 4 seconds, then a flat horizontal line from 4 to 8 seconds.",
    prompt: "What was the bike doing from 4 to 8 seconds?",
    choices: ["Stopped", "Moving at a constant speed", "Speeding up", "Moving backward"],
    answer: 0,
    explanation: "A flat line on a distance-time graph means the distance is not changing, so the object is at rest.",
  },
  {
    id: "sci-g7-02",
    subject: "science",
    grade: "7",
    standard: "PS.7.1",
    skill: "Speed and velocity",
    prompt: "Velocity is speed plus...",
    choices: ["Direction", "Mass", "Time", "Force"],
    answer: 0,
    explanation: "Velocity tells both how fast and which way. 20 m/s north is a velocity; 20 m/s alone is a speed.",
    quick: true,
  },
  {
    id: "sci-g7-03",
    subject: "science",
    grade: "7",
    standard: "PS.7.1",
    skill: "Speed and velocity",
    prompt: "A runner goes 100 m in 20 s. What is her average speed?",
    choices: ["5 m/s", "2000 m/s", "0.2 m/s", "120 m/s"],
    answer: 0,
    explanation: "Average speed = distance ÷ time = 100 m ÷ 20 s = 5 m/s.",
    quick: true,
  },
  {
    id: "sci-g7-04",
    subject: "science",
    grade: "7",
    standard: "PS.7.1",
    skill: "Frame of reference",
    prompt: "Compared with her seat, a rider sitting on a moving train is...",
    choices: ["Not moving", "Moving fast", "Speeding up", "Falling"],
    answer: 0,
    explanation: "Motion depends on the reference point. She stays in the same place relative to her seat, though she moves relative to the ground.",
    quick: true,
  },
  {
    id: "sci-g7-05",
    subject: "science",
    grade: "7",
    standard: "PS.7.1",
    skill: "Acceleration",
    prompt: "A change in velocity over time is called...",
    choices: ["Acceleration", "Speed", "Distance", "Inertia"],
    answer: 0,
    explanation: "Acceleration is any change in speed or direction. Slowing down and turning are accelerations too.",
    quick: true,
  },
  {
    id: "sci-g7-06",
    subject: "science",
    grade: "7",
    standard: "PS.7.2",
    skill: "Kinetic and potential energy",
    prompt: "The energy of a moving object is called...",
    choices: ["Kinetic", "Potential", "Chemical", "Nuclear"],
    answer: 0,
    explanation: "Kinetic energy is energy of motion. Potential energy is stored energy, such as from height.",
    quick: true,
  },
  {
    id: "sci-g7-07",
    subject: "science",
    grade: "7",
    standard: "PS.7.2",
    skill: "Kinetic and potential energy",
    prompt: "Where does a roller coaster car have the most gravitational potential energy?",
    choices: ["At the top", "At the bottom", "Halfway down", "Moving fastest"],
    answer: 0,
    explanation: "Gravitational potential energy depends on height. At the top of the highest hill it is greatest.",
    quick: true,
  },
  {
    id: "sci-g7-08",
    subject: "science",
    grade: "7",
    standard: "PS.7.2",
    skill: "Kinetic and potential energy",
    passage: "A 2 kg bowling ball and a 4 kg bowling ball roll down a lane at the same speed of 3 m/s.",
    prompt: "How does the kinetic energy of the 4 kg ball compare with the 2 kg ball?",
    choices: [
      "It is twice as much",
      "It is four times as much",
      "They are the same, since speed is the same",
      "It is half as much",
    ],
    answer: 0,
    explanation: "Kinetic energy = ½mv². At the same speed, doubling the mass doubles the kinetic energy.",
  },
  {
    id: "sci-g7-09",
    subject: "science",
    grade: "7",
    standard: "PS.7.2",
    skill: "Conservation of energy",
    prompt: "Energy cannot be created or...",
    choices: ["Destroyed", "Moved", "Changed", "Stored"],
    answer: 0,
    explanation: "Energy is conserved. It can move and change form, but the total amount stays the same.",
    quick: true,
  },
  {
    id: "sci-g7-10",
    subject: "science",
    grade: "7",
    standard: "ESS.7.1.1",
    skill: "Atmosphere layers",
    prompt: "In which layer of the atmosphere does almost all weather happen?",
    choices: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
    answer: 0,
    explanation: "The troposphere is the lowest layer. It holds most of the air's water vapor, so clouds and storms form there.",
    quick: true,
  },
  {
    id: "sci-g7-11",
    subject: "science",
    grade: "7",
    standard: "ESS.7.1.1",
    skill: "Atmosphere composition",
    prompt: "Which gas makes up most of the air we breathe?",
    choices: ["Nitrogen", "Oxygen", "Carbon dioxide", "Helium"],
    answer: 0,
    explanation: "Air is about 78% nitrogen and 21% oxygen. Carbon dioxide is less than 1%.",
    quick: true,
  },
  {
    id: "sci-g7-12",
    subject: "science",
    grade: "7",
    standard: "ESS.7.1.1",
    skill: "Air pressure",
    prompt: "As you climb higher in the atmosphere, air pressure...",
    choices: ["Decreases", "Increases", "Stays same", "Doubles"],
    answer: 0,
    explanation: "Higher up, there is less air above pressing down, so air pressure drops.",
    quick: true,
  },
  {
    id: "sci-g7-13",
    subject: "science",
    grade: "7",
    standard: "ESS.7.1",
    skill: "Air masses and fronts",
    passage:
      "A cold, dry air mass moves quickly into an area of warm, humid air. The dense cold air wedges under the warm air.",
    prompt: "What weather is most likely along this front?",
    choices: [
      "Warm air is forced up fast, forming thunderstorms",
      "Clear skies, because cold air holds more water",
      "Days of light drizzle as warm air slides gently over",
      "No change, because air masses do not mix",
    ],
    answer: 0,
    explanation: "At a cold front, warm moist air is pushed up quickly, cools and condenses into tall clouds and storms. Gentle drizzle is typical of warm fronts.",
  },
  {
    id: "sci-g7-14",
    subject: "science",
    grade: "7",
    standard: "ESS.7.2.1",
    skill: "Air quality",
    prompt: "Which is a major source of air pollution?",
    choices: ["Car exhaust", "Solar panels", "Wind turbines", "Trees"],
    answer: 0,
    explanation: "Burning gasoline releases pollutants such as nitrogen oxides and particles. Monitoring air quality helps protect health.",
    quick: true,
  },
  {
    id: "sci-g7-15",
    subject: "science",
    grade: "7",
    standard: "LS.7.1",
    skill: "Cell structures",
    prompt: "Which cell part controls what enters and leaves the cell?",
    choices: ["Cell membrane", "Nucleus", "Vacuole", "Chloroplast"],
    answer: 0,
    explanation: "The cell membrane is a flexible barrier that lets some materials in and keeps others out.",
    quick: true,
  },
  {
    id: "sci-g7-16",
    subject: "science",
    grade: "7",
    standard: "LS.7.1",
    skill: "Single-celled organisms",
    prompt: "A paramecium moves using tiny hair-like structures called...",
    choices: ["Cilia", "Flagella", "Pseudopods", "Roots"],
    answer: 0,
    explanation: "Paramecia beat cilia to swim. Euglena uses a whip-like flagellum, and amoebas crawl with pseudopods.",
    quick: true,
  },
  {
    id: "sci-g7-17",
    subject: "science",
    grade: "7",
    standard: "LS.7.2",
    skill: "Reproduction",
    prompt: "Asexual reproduction makes offspring that are genetically...",
    choices: ["Identical", "Varied", "Half-alike", "Random"],
    answer: 0,
    explanation: "With only one parent, offspring get a copy of the same genetic information. Sexual reproduction creates variation.",
    quick: true,
  },
  {
    id: "sci-g7-18",
    subject: "science",
    grade: "7",
    standard: "LS.7.2",
    skill: "Punnett squares",
    passage:
      "In pea plants, purple flowers (P) are dominant over white flowers (p). A purple-flowered plant with genotype Pp is crossed with a white-flowered plant (pp).",
    prompt: "What percent of the offspring are expected to have white flowers?",
    choices: ["50%", "25%", "75%", "0%"],
    answer: 0,
    explanation: "The Punnett square gives Pp, Pp, pp, pp. Two of four boxes are pp, so 50% are expected to be white.",
  },
];
export default questions;
