import type { Question } from "../../types";
// Grade 9 science — NC Standard Course of Study for Science (2023), Earth and Environmental Science (ESS.EES).
// Earth in the universe and solar system, solar energy, seasons and tides (ESS.EES.1); plate tectonics, earthquakes,
// the rock cycle and Earth's history (ESS.EES.2); the hydrosphere and atmosphere, weather and climate (ESS.EES.3); the
// biosphere and its links to other Earth systems (ESS.EES.4); resources and human impact, including water quality
// (ESS.EES.5); natural hazards (ESS.EES.6).
const questions: Question[] = [
  {
    id: "sci-g9-01",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Seasons",
    prompt: "Earth's seasons are caused mainly by...",
    choices: ["Axial tilt", "Sun distance", "Solar flares", "Moon phases"],
    answer: 0,
    explanation: "Earth's 23.5° tilt changes how directly sunlight hits each hemisphere. Earth is actually closest to the sun in January.",
    quick: true,
  },
  {
    id: "sci-g9-02",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Solar energy",
    prompt: "The sun produces its energy by nuclear...",
    choices: ["Fusion", "Fission", "Combustion", "Friction"],
    answer: 0,
    explanation: "In the sun's core, hydrogen nuclei fuse into helium, releasing energy that reaches Earth as radiation.",
    quick: true,
  },
  {
    id: "sci-g9-03",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Tides",
    prompt: "Spring tides (the biggest tidal range) happen when the sun, moon and Earth are...",
    choices: ["Lined up", "At 90 degrees", "Far apart", "In shadow"],
    answer: 0,
    explanation: "When the sun and moon line up (new or full moon), their pulls combine for extra-high and extra-low tides. At right angles you get neap tides.",
    quick: true,
  },
  {
    id: "sci-g9-04",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Seasons",
    passage:
      "At noon in Raleigh (about 36°N), the sun is about 77° above the horizon in late June but only about 31° above it in late December. June days also last about 14.5 hours, versus about 9.5 hours in December.",
    prompt: "Why does Raleigh receive much more solar energy in June?",
    choices: [
      "Sunlight is more direct and days are longer",
      "Earth is much closer to the sun in June",
      "The sun gives off more energy in summer",
      "There are fewer clouds in June everywhere on Earth",
    ],
    answer: 0,
    explanation: "A high sun spreads its energy over a smaller area, and longer days add more hours of heating. Both come from Earth's tilt.",
  },
  {
    id: "sci-g9-05",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2.2",
    skill: "Plate boundaries",
    prompt: "Most earthquakes and volcanoes occur...",
    choices: ["At plate edges", "Mid-plate", "At the poles", "Randomly"],
    answer: 0,
    explanation: "Plates grinding, colliding or separating at their boundaries cause most earthquakes and volcanoes, like the Pacific Ring of Fire.",
    quick: true,
  },
  {
    id: "sci-g9-06",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Rock cycle",
    prompt: "Rock changed by heat and pressure without melting is...",
    choices: ["Metamorphic", "Igneous", "Sedimentary", "Magma"],
    answer: 0,
    explanation: "Metamorphic rocks, like gneiss and marble, form when existing rock is transformed by heat and pressure while still solid.",
    quick: true,
  },
  {
    id: "sci-g9-07",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Seafloor spreading",
    passage:
      "Rock samples from the seafloor on both sides of a mid-ocean ridge give these ages: at the ridge, 0 million years; 200 km away, 10 million years; 400 km away, 20 million years. The pattern is the same on both sides.",
    prompt: "What do these data show, and about how fast is each side moving?",
    choices: [
      "Seafloor spreading; about 2 cm per year",
      "Seafloor spreading; about 20 km per year",
      "Subduction; about 2 cm per year",
      "The ridge is the oldest crust; no movement",
    ],
    answer: 0,
    explanation: "Crust gets older away from the ridge, so new crust forms there and spreads out. 200 km = 20,000,000 cm in 10,000,000 years = 2 cm/yr.",
  },
  {
    id: "sci-g9-08",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate boundaries",
    prompt: "Where two ocean plates pull apart, you find...",
    choices: ["Ocean ridges", "Trenches", "Fold mountains", "Island arcs"],
    answer: 0,
    explanation: "At divergent boundaries, magma rises to form new crust, building mid-ocean ridges like the Mid-Atlantic Ridge.",
    quick: true,
  },
  {
    id: "sci-g9-09",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Groundwater",
    prompt: "Water stored in pores and cracks of rock underground is...",
    choices: ["Groundwater", "Runoff", "Humidity", "Sea spray"],
    answer: 0,
    explanation: "Groundwater fills spaces in soil and rock. A rock layer that holds and transmits usable water is an aquifer.",
    quick: true,
  },
  {
    id: "sci-g9-10",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5.2",
    skill: "Water pollution",
    passage:
      "After heavy rains, fertilizer from nearby farms and lawns washes into a lake. Within weeks a thick algae bloom covers the surface. Later, many fish are found dead.",
    prompt: "What most directly caused the fish to die?",
    choices: [
      "Bacteria decomposing dead algae used up the dissolved oxygen",
      "The fertilizer poisoned the fish directly",
      "The algae ate the fish's food",
      "The rain made the water too cold",
    ],
    answer: 0,
    explanation: "This is eutrophication: extra nutrients feed algae, and when the algae die, decomposers consume oxygen, leaving too little for fish.",
  },
  {
    id: "sci-g9-11",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Greenhouse effect",
    prompt: "Which heat-trapping gas is increasing mainly from burning fossil fuels?",
    choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Argon"],
    answer: 0,
    explanation: "CO₂ absorbs infrared energy radiated by Earth. Burning coal, oil and gas adds CO₂, strengthening the greenhouse effect.",
    quick: true,
  },
  {
    id: "sci-g9-12",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Weather",
    prompt: "Air moving from high pressure toward low pressure is...",
    choices: ["Wind", "Humidity", "Fog", "Dew"],
    answer: 0,
    explanation: "Uneven heating creates pressure differences, and air flows from high to low pressure as wind.",
    quick: true,
  },
  {
    id: "sci-g9-13",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Climate data",
    passage:
      "Average atmospheric CO₂ measured at Mauna Loa, Hawaii: about 317 ppm in 1960, about 354 ppm in 1990, and about 414 ppm in 2020.",
    prompt: "What was the approximate average rate of increase from 1990 to 2020?",
    choices: ["About 2 ppm per year", "About 0.5 ppm per year", "About 6 ppm per year", "About 60 ppm per year"],
    answer: 0,
    explanation: "414 − 354 = 60 ppm over 30 years = 2 ppm per year. That is faster than the 1960–1990 rate (about 1.2 ppm/yr).",
  },
  {
    id: "sci-g9-14",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Severe weather",
    prompt: "Hurricanes get most of their energy from...",
    choices: ["Warm seawater", "Cold fronts", "Mountains", "Deserts"],
    answer: 0,
    explanation: "Warm ocean water evaporates, and heat released when the vapor condenses powers the storm. Hurricanes weaken over land or cold water.",
    quick: true,
  },
  {
    id: "sci-g9-15",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5",
    skill: "Natural resources",
    prompt: "Which energy resource is nonrenewable?",
    choices: ["Natural gas", "Sunlight", "Wind", "Tides"],
    answer: 0,
    explanation: "Natural gas is a fossil fuel formed over millions of years, so we use it far faster than it forms.",
    quick: true,
  },
  {
    id: "sci-g9-16",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5",
    skill: "Human impact",
    prompt: "Clearing forests on hillsides usually increases...",
    choices: ["Soil erosion", "Biodiversity", "Groundwater", "Shade"],
    answer: 0,
    explanation: "Tree roots hold soil and leaves soften rainfall. Without them, runoff carries soil away and less water soaks in.",
    quick: true,
  },
  {
    id: "sci-g9-17",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Which natural hazard is the biggest threat to North Carolina's coast?",
    choices: ["Hurricanes", "Volcanoes", "Blizzards", "Avalanches"],
    answer: 0,
    explanation: "NC's coast sticks out into the Atlantic, so hurricanes bring storm surge, flooding and wind damage.",
    quick: true,
  },
  {
    id: "sci-g9-18",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Building homes on a river floodplain mainly increases the risk of...",
    choices: ["Flood damage", "Earthquakes", "Volcanoes", "Landslides"],
    answer: 0,
    explanation: "Floodplains are flat land that rivers cover during floods. Building there puts people and property in the water's path.",
    quick: true,
  },
  {
    id: "sci-g9-19",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Earth in the solar system",
    prompt: "Sunlight takes about how long to reach Earth?",
    choices: ["8 minutes", "8 seconds", "8 hours", "8 days"],
    answer: 0,
    explanation: "Light travels about 150 million km from the sun in roughly 8 minutes and 20 seconds.",
    quick: true,
  },
  {
    id: "sci-g9-20",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Earth in the universe",
    prompt: "Most scientists think the universe began with the...",
    choices: ["Big Bang", "Ice Age", "Solar wind", "Supernova"],
    answer: 0,
    explanation: "Evidence like the expanding universe and cosmic background radiation supports the Big Bang about 13.8 billion years ago.",
    quick: true,
  },
  {
    id: "sci-g9-21",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Earth in the solar system",
    prompt: "Earth's orbit around the sun is shaped like an...",
    choices: ["Ellipse", "Perfect circle", "Spiral", "Square"],
    answer: 0,
    explanation: "Earth's orbit is a slightly stretched oval called an ellipse, very close to a circle.",
    quick: true,
  },
  {
    id: "sci-g9-22",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Earth in the solar system",
    prompt: "Earth is closest to the sun in which month?",
    choices: ["January", "July", "April", "October"],
    answer: 0,
    explanation: "Earth reaches perihelion in early January, during Northern Hemisphere winter. Distance does not cause the seasons.",
    quick: true,
  },
  {
    id: "sci-g9-23",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Earth in the solar system",
    prompt: "A planet moves fastest in its orbit when it is...",
    choices: ["Closest to sun", "Farthest away", "Behind a moon", "Halfway out"],
    answer: 0,
    explanation: "Kepler's second law: a planet speeds up near the sun and slows down far from it.",
    quick: true,
  },
  {
    id: "sci-g9-24",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Solar energy and seasons",
    prompt: "On the June solstice, the noon sun is directly overhead at the...",
    choices: ["Tropic of Cancer", "Equator", "Tropic of Capricorn", "Arctic Circle"],
    answer: 0,
    explanation: "In June, the Northern Hemisphere tilts toward the sun, so the direct rays hit 23.5° N, the Tropic of Cancer.",
  },
  {
    id: "sci-g9-25",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate tectonics",
    prompt: "Two continental plates collide. What usually forms?",
    choices: ["Tall mountains", "Ocean ridges", "Deep trenches", "Hot spots"],
    answer: 0,
    explanation: "Neither continental plate sinks easily, so the crust crumples upward, like the Himalayas.",
    quick: true,
  },
  {
    id: "sci-g9-26",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate tectonics",
    prompt: "California's San Andreas Fault is which kind of boundary?",
    choices: ["Transform", "Convergent", "Divergent", "Hot spot"],
    answer: 0,
    explanation: "At a transform boundary, plates slide past each other sideways, causing earthquakes.",
    quick: true,
  },
  {
    id: "sci-g9-27",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Earth's interior",
    prompt: "Which seismic waves cannot travel through liquid?",
    choices: ["S waves", "P waves", "Surface waves", "Sound waves"],
    answer: 0,
    explanation: "S waves stop at the outer core. That shadow zone shows the outer core is liquid.",
    quick: true,
  },
  {
    id: "sci-g9-28",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate tectonics",
    prompt: "Hawaii's volcanoes formed over a...",
    choices: ["Hot spot", "Trench", "Transform", "Rift valley"],
    answer: 0,
    explanation: "A hot spot is a plume of hot mantle. As the Pacific Plate moves over it, a chain of islands forms.",
    quick: true,
  },
  {
    id: "sci-g9-29",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Rock cycle",
    prompt: "Sedimentary rock forms when sediments are...",
    choices: ["Compacted", "Melted", "Vaporized", "Magnetized"],
    answer: 0,
    explanation: "Layers of sediment are pressed together (compacted) and glued (cemented) into rock.",
    quick: true,
  },
  {
    id: "sci-g9-30",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate tectonics",
    prompt: "How did the Appalachian Mountains form?",
    choices: ["Plates collided", "Plates pulled apart", "A meteor hit", "Glaciers piled rock"],
    answer: 0,
    explanation: "The Appalachians rose when ancient continents collided while forming the supercontinent Pangaea.",
  },
  {
    id: "sci-g9-31",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Atmosphere and wind",
    prompt: "The Coriolis effect turns Northern Hemisphere winds to the...",
    choices: ["Right", "Left", "North only", "Up"],
    answer: 0,
    explanation: "Earth's rotation deflects moving air to the right in the Northern Hemisphere and to the left in the Southern.",
    quick: true,
  },
  {
    id: "sci-g9-32",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Greenhouse effect",
    prompt: "Which gas is the most abundant greenhouse gas?",
    choices: ["Water vapor", "Oxygen", "Nitrogen", "Argon"],
    answer: 0,
    explanation: "Water vapor traps the most heat overall. Oxygen and nitrogen are not greenhouse gases.",
    quick: true,
  },
  {
    id: "sci-g9-33",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Hydrosphere",
    prompt: "All the land that drains into one river is its...",
    choices: ["Watershed", "Aquifer", "Estuary", "Delta"],
    answer: 0,
    explanation: "A watershed (drainage basin) collects rain and runoff that flows to the same river.",
    quick: true,
  },
  {
    id: "sci-g9-34",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Weather and climate",
    prompt: "El Niño is unusually warm surface water in the...",
    choices: ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean", "Red Sea"],
    answer: 0,
    explanation: "El Niño warms the tropical Pacific and shifts weather patterns around the world.",
    quick: true,
  },
  {
    id: "sci-g9-35",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Weather and climate",
    prompt: "Climate describes weather averaged over about...",
    choices: ["30 years", "1 day", "1 week", "1 month"],
    answer: 0,
    explanation: "Weather is day to day. Climate is the long-term pattern, usually averaged over 30 years.",
    quick: true,
  },
  {
    id: "sci-g9-36",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Biosphere and carbon",
    prompt: "Which process returns carbon dioxide to the air?",
    choices: ["Respiration", "Photosynthesis", "Sedimentation", "Condensation"],
    answer: 0,
    explanation: "Living things release CO₂ when they break down sugar in respiration.",
    quick: true,
  },
  {
    id: "sci-g9-37",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Biosphere and oceans",
    prompt: "Water that is too warm can make corals lose their algae. This is...",
    choices: ["Bleaching", "Erosion", "Freezing", "Upwelling"],
    answer: 0,
    explanation: "Heat-stressed corals expel their algae, turn white, and may starve. This is coral bleaching.",
    quick: true,
  },
  {
    id: "sci-g9-38",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Biosphere and nutrients",
    prompt: "Nitrogen-fixing bacteria live in root nodules of...",
    choices: ["Legumes", "Pine trees", "Cacti", "Mosses"],
    answer: 0,
    explanation: "Bacteria in the roots of peas, beans and clover change nitrogen gas into forms plants can use.",
    quick: true,
  },
  {
    id: "sci-g9-39",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Biosphere and soil",
    prompt: "Lichens growing on bare rock help start...",
    choices: ["Soil formation", "Earthquakes", "Erosion only", "Tides"],
    answer: 0,
    explanation: "Lichens break down rock and add organic matter, the first step of soil formation in primary succession.",
    quick: true,
  },
  {
    id: "sci-g9-40",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5.2",
    skill: "Water quality",
    prompt: "Which is point-source pollution?",
    choices: ["Factory pipe", "Farm runoff", "Lawn runoff", "Street runoff"],
    answer: 0,
    explanation: "Point-source pollution comes from one identifiable spot, like a discharge pipe. Runoff is nonpoint.",
    quick: true,
  },
  {
    id: "sci-g9-41",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5.2",
    skill: "Water quality",
    prompt: "Overpumping coastal wells can draw in salt water. This is...",
    choices: ["Saltwater intrusion", "Upwelling", "Eutrophication", "Transpiration"],
    answer: 0,
    explanation: "When fresh groundwater is pumped out faster than it refills, seawater moves into the aquifer.",
  },
  {
    id: "sci-g9-42",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5.2",
    skill: "Water quality",
    prompt: "Strips of trees and plants along streams mainly...",
    choices: ["Filter runoff", "Raise floods", "Warm water", "Add sediment"],
    answer: 0,
    explanation: "Riparian buffers trap sediment and fertilizer before they reach the stream and shade the water.",
    quick: true,
  },
  {
    id: "sci-g9-43",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "A magnitude 6 quake releases about how many times the energy of a 5?",
    choices: ["About 32", "About 10", "About 2", "About 100"],
    answer: 0,
    explanation: "Each whole magnitude step is 10 times more ground shaking and about 32 times more energy.",
    quick: true,
  },
  {
    id: "sci-g9-44",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Hurricane storm surge is...",
    choices: ["High seawater", "Heavy rain", "Strong gusts", "Lightning"],
    answer: 0,
    explanation: "Storm surge is seawater pushed ashore by a storm's winds. It causes much of a hurricane's flooding and deaths.",
    quick: true,
  },
  {
    id: "sci-g9-45",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Which NC region has the highest landslide risk?",
    choices: ["Mountains", "Coastal Plain", "Piedmont", "Outer Banks"],
    answer: 0,
    explanation: "Steep slopes plus heavy rain make landslides most likely in western NC's mountains.",
    quick: true,
  },
  {
    id: "sci-g9-46",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Earthquakes",
    passage:
      "At Station A, the S wave arrived 40 seconds after the P wave. At Station B, it arrived 20 seconds after the P wave.",
    prompt: "Which station is closer to the earthquake?",
    choices: ["Station B", "Station A", "They are equally close", "It cannot be determined"],
    answer: 0,
    explanation: "P waves outrun S waves, so the gap between them grows with distance. The smaller gap at B means B is closer.",
  },
  {
    id: "sci-g9-47",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Earth's history",
    passage:
      "A rock sample contains 25% of its original uranium-235. The half-life of uranium-235 is about 704 million years.",
    prompt: "About how old is the rock?",
    choices: [
      "About 1.4 billion years",
      "About 704 million years",
      "About 2.8 billion years",
      "About 352 million years",
    ],
    answer: 0,
    explanation: "25% left means two half-lives passed (100% → 50% → 25%). 2 × 704 million ≈ 1.4 billion years.",
  },
  {
    id: "sci-g9-48",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Weather and climate",
    passage:
      "A tide gauge on the North Carolina coast shows that average sea level rose 9 cm (90 mm) from 2000 to 2020.",
    prompt: "What was the average rate of sea-level rise?",
    choices: ["4.5 mm per year", "9 mm per year", "0.45 mm per year", "45 mm per year"],
    answer: 0,
    explanation: "90 mm ÷ 20 years = 4.5 mm per year. Rising seas make coastal flooding more common.",
  },
];
export default questions;
