import type { Question } from "../../types";
// Grade 9 science — NC Standard Course of Study for Science (2023), Earth and Environmental Science (ESS.EES).
// Earth in the solar system, solar energy, seasons and tides (ESS.EES.1); plate tectonics and the rock cycle
// (ESS.EES.2); hydrosphere and water quality (ESS.EES.3); atmosphere, weather and climate (ESS.EES.4); resources
// and human impact (ESS.EES.5); natural hazards (ESS.EES.6).
const questions: Question[] = [
  {
    id: "sci-g9-01",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Seasons",
    prompt: "Earth's seasons are caused mainly by...",
    choices: ["Axial tilt", "Sun distance", "Solar flares", "Moon phases"],
    answer: 0,
    explanation: "Earth's 23.5° tilt changes how directly sunlight hits each hemisphere. Earth is actually closest to the sun in January.",
    quick: true,
  },
  {
    id: "sci-g9-02",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Solar energy",
    prompt: "The sun produces its energy by nuclear...",
    choices: ["Fusion", "Fission", "Combustion", "Friction"],
    answer: 0,
    explanation: "In the sun's core, hydrogen nuclei fuse into helium, releasing energy that reaches Earth as radiation.",
    quick: true,
  },
  {
    id: "sci-g9-03",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Tides",
    prompt: "Spring tides (the biggest tidal range) happen when the sun, moon and Earth are...",
    choices: ["Lined up", "At 90 degrees", "Far apart", "In shadow"],
    answer: 0,
    explanation: "When the sun and moon line up (new or full moon), their pulls combine for extra-high and extra-low tides. At right angles you get neap tides.",
    quick: true,
  },
  {
    id: "sci-g9-04",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.1",
    skill: "Seasons",
    passage:
      "At noon in Raleigh (about 36°N), the sun is about 77° above the horizon in late June but only about 31° above it in late December. June days also last about 14.5 hours, versus about 9.5 hours in December.",
    prompt: "Why does Raleigh receive much more solar energy in June?",
    choices: [
      "Sunlight is more direct and days are longer",
      "Earth is much closer to the sun in June",
      "The sun gives off more energy in summer",
      "There are fewer clouds in June everywhere on Earth",
    ],
    answer: 0,
    explanation: "A high sun spreads its energy over a smaller area, and longer days add more hours of heating. Both come from Earth's tilt.",
  },
  {
    id: "sci-g9-05",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2.2",
    skill: "Plate boundaries",
    prompt: "Most earthquakes and volcanoes occur...",
    choices: ["At plate edges", "Mid-plate", "At the poles", "Randomly"],
    answer: 0,
    explanation: "Plates grinding, colliding or separating at their boundaries cause most earthquakes and volcanoes, like the Pacific Ring of Fire.",
    quick: true,
  },
  {
    id: "sci-g9-06",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Rock cycle",
    prompt: "Rock changed by heat and pressure without melting is...",
    choices: ["Metamorphic", "Igneous", "Sedimentary", "Magma"],
    answer: 0,
    explanation: "Metamorphic rocks, like gneiss and marble, form when existing rock is transformed by heat and pressure while still solid.",
    quick: true,
  },
  {
    id: "sci-g9-07",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Seafloor spreading",
    passage:
      "Rock samples from the seafloor on both sides of a mid-ocean ridge give these ages: at the ridge, 0 million years; 200 km away, 10 million years; 400 km away, 20 million years. The pattern is the same on both sides.",
    prompt: "What do these data show, and about how fast is each side moving?",
    choices: [
      "Seafloor spreading; about 2 cm per year",
      "Seafloor spreading; about 20 km per year",
      "Subduction; about 2 cm per year",
      "The ridge is the oldest crust; no movement",
    ],
    answer: 0,
    explanation: "Crust gets older away from the ridge, so new crust forms there and spreads out. 200 km = 20,000,000 cm in 10,000,000 years = 2 cm/yr.",
  },
  {
    id: "sci-g9-08",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.2",
    skill: "Plate boundaries",
    prompt: "Where two ocean plates pull apart, you find...",
    choices: ["Ocean ridges", "Trenches", "Fold mountains", "Island arcs"],
    answer: 0,
    explanation: "At divergent boundaries, magma rises to form new crust, building mid-ocean ridges like the Mid-Atlantic Ridge.",
    quick: true,
  },
  {
    id: "sci-g9-09",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Groundwater",
    prompt: "Water stored in pores and cracks of rock underground is...",
    choices: ["Groundwater", "Runoff", "Humidity", "Sea spray"],
    answer: 0,
    explanation: "Groundwater fills spaces in soil and rock. A rock layer that holds and transmits usable water is an aquifer.",
    quick: true,
  },
  {
    id: "sci-g9-10",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.3",
    skill: "Water pollution",
    passage:
      "After heavy rains, fertilizer from nearby farms and lawns washes into a lake. Within weeks a thick algae bloom covers the surface. Later, many fish are found dead.",
    prompt: "What most directly caused the fish to die?",
    choices: [
      "Bacteria decomposing dead algae used up the dissolved oxygen",
      "The fertilizer poisoned the fish directly",
      "The algae ate the fish's food",
      "The rain made the water too cold",
    ],
    answer: 0,
    explanation: "This is eutrophication: extra nutrients feed algae, and when the algae die, decomposers consume oxygen, leaving too little for fish.",
  },
  {
    id: "sci-g9-11",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Greenhouse effect",
    prompt: "Which heat-trapping gas is increasing mainly from burning fossil fuels?",
    choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Argon"],
    answer: 0,
    explanation: "CO₂ absorbs infrared energy radiated by Earth. Burning coal, oil and gas adds CO₂, strengthening the greenhouse effect.",
    quick: true,
  },
  {
    id: "sci-g9-12",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Weather",
    prompt: "Air moving from high pressure toward low pressure is...",
    choices: ["Wind", "Humidity", "Fog", "Dew"],
    answer: 0,
    explanation: "Uneven heating creates pressure differences, and air flows from high to low pressure as wind.",
    quick: true,
  },
  {
    id: "sci-g9-13",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Climate data",
    passage:
      "Average atmospheric CO₂ measured at Mauna Loa, Hawaii: about 317 ppm in 1960, about 354 ppm in 1990, and about 414 ppm in 2020.",
    prompt: "What was the approximate average rate of increase from 1990 to 2020?",
    choices: ["About 2 ppm per year", "About 0.5 ppm per year", "About 6 ppm per year", "About 60 ppm per year"],
    answer: 0,
    explanation: "414 − 354 = 60 ppm over 30 years = 2 ppm per year. That is faster than the 1960–1990 rate (about 1.2 ppm/yr).",
  },
  {
    id: "sci-g9-14",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.4",
    skill: "Severe weather",
    prompt: "Hurricanes get most of their energy from...",
    choices: ["Warm seawater", "Cold fronts", "Mountains", "Deserts"],
    answer: 0,
    explanation: "Warm ocean water evaporates, and heat released when the vapor condenses powers the storm. Hurricanes weaken over land or cold water.",
    quick: true,
  },
  {
    id: "sci-g9-15",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5",
    skill: "Natural resources",
    prompt: "Which energy resource is nonrenewable?",
    choices: ["Natural gas", "Sunlight", "Wind", "Tides"],
    answer: 0,
    explanation: "Natural gas is a fossil fuel formed over millions of years, so we use it far faster than it forms.",
    quick: true,
  },
  {
    id: "sci-g9-16",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.5",
    skill: "Human impact",
    prompt: "Clearing forests on hillsides usually increases...",
    choices: ["Soil erosion", "Biodiversity", "Groundwater", "Shade"],
    answer: 0,
    explanation: "Tree roots hold soil and leaves soften rainfall. Without them, runoff carries soil away and less water soaks in.",
    quick: true,
  },
  {
    id: "sci-g9-17",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Which natural hazard is the biggest threat to North Carolina's coast?",
    choices: ["Hurricanes", "Volcanoes", "Blizzards", "Avalanches"],
    answer: 0,
    explanation: "NC's coast sticks out into the Atlantic, so hurricanes bring storm surge, flooding and wind damage.",
    quick: true,
  },
  {
    id: "sci-g9-18",
    subject: "science",
    grade: "9",
    standard: "ESS.EES.6",
    skill: "Natural hazards",
    prompt: "Building homes on a river floodplain mainly increases the risk of...",
    choices: ["Flood damage", "Earthquakes", "Volcanoes", "Landslides"],
    answer: 0,
    explanation: "Floodplains are flat land that rivers cover during floods. Building there puts people and property in the water's path.",
    quick: true,
  },
];
export default questions;
