import type { Question } from "../../types";
// Grade K science — NC Standard Course of Study for Science (2023). Sorting objects by physical properties (PS.K.1),
// pushes, pulls and ways things move (PS.K.2), daily and seasonal weather (ESS.K.1), living vs. nonliving (LS.K.1),
// and how animals of the same kind are alike and different (LS.K.2).
const questions: Question[] = [
  {
    id: "sci-gK-01",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one feels soft?",
    choices: ["Pillow", "Rock", "Spoon", "Brick"],
    answer: 0,
    explanation: "A pillow is soft. Rocks, spoons and bricks are hard. How a thing feels is one of its properties.",
    quick: true,
  },
  {
    id: "sci-gK-02",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one is the heaviest?",
    choices: ["Bowling ball", "Feather", "Leaf", "Balloon"],
    answer: 0,
    explanation: "A bowling ball is very heavy. A feather, a leaf and a balloon are light. Weight is a property we can feel.",
    quick: true,
  },
  {
    id: "sci-gK-03",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one can bend and stretch?",
    choices: ["Rubber band", "Rock", "Brick", "Wood block"],
    answer: 0,
    explanation: "A rubber band is flexible, so it can bend and stretch. Rocks, bricks and wood blocks are stiff.",
    quick: true,
  },
  {
    id: "sci-gK-04",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "What are most windows made of?",
    choices: ["Glass", "Paper", "Cloth", "Clay"],
    answer: 0,
    explanation: "Windows are made of glass because you can see through it and it keeps rain out.",
    quick: true,
  },
  {
    id: "sci-gK-05",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "Which is best for making a warm coat?",
    choices: ["Cloth", "Paper", "Glass", "Rock"],
    answer: 0,
    explanation: "Cloth is soft, bends easily and keeps you warm. That is why coats are made of cloth.",
    quick: true,
  },
  {
    id: "sci-gK-06",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "A push moves a thing which way?",
    choices: ["Away from you", "Toward you", "Up only", "Nowhere"],
    answer: 0,
    explanation: "A push moves a thing away from you. A pull moves a thing toward you.",
    quick: true,
  },
  {
    id: "sci-gK-07",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "To open a drawer, you give it a...",
    choices: ["Pull", "Push", "Kick", "Hug"],
    answer: 0,
    explanation: "You pull a drawer toward you to open it. You push it away to close it.",
    quick: true,
  },
  {
    id: "sci-gK-08",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "What happens when you drop a ball?",
    choices: ["It falls down", "It floats up", "It stays put", "It melts"],
    answer: 0,
    explanation: "When you let go of a ball, it falls down to the ground. Things fall when they are dropped.",
    quick: true,
  },
  {
    id: "sci-gK-09",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "A harder kick makes a ball go...",
    choices: ["Farther", "Less far", "Nowhere", "Backward"],
    answer: 0,
    explanation: "A bigger push makes a ball go faster and farther. A soft kick makes it go only a little way.",
    quick: true,
  },
  {
    id: "sci-gK-10",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "How does a swing move?",
    choices: ["Back and forth", "Zigzag", "In a circle", "It can't move"],
    answer: 0,
    explanation: "A swing moves back and forth. Other things move straight, zigzag, or round and round.",
    quick: true,
  },
  {
    id: "sci-gK-11",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "What should you wear on a snowy day?",
    choices: ["Warm coat", "Swimsuit", "Sandals", "Shorts"],
    answer: 0,
    explanation: "Snowy days are cold, so a warm coat keeps you cozy. We change what we wear when the weather changes.",
    quick: true,
  },
  {
    id: "sci-gK-12",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "What falls from clouds on a rainy day?",
    choices: ["Water drops", "Sand", "Leaves", "Rocks"],
    answer: 0,
    explanation: "Rain is drops of water falling from clouds. Rain makes puddles and helps plants grow.",
    quick: true,
  },
  {
    id: "sci-gK-13",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.2",
    skill: "Seasons",
    prompt: "Which season is the coldest?",
    choices: ["Winter", "Summer", "Spring", "Fall"],
    answer: 0,
    explanation: "Winter is the coldest season. Summer is the hottest. The weather changes through the year.",
    quick: true,
  },
  {
    id: "sci-gK-14",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.2",
    skill: "Weather",
    prompt: "What tool tells how hot or cold it is?",
    choices: ["Thermometer", "Ruler", "Clock", "Spoon"],
    answer: 0,
    explanation: "A thermometer measures temperature, which tells how hot or cold it is.",
    quick: true,
  },
  {
    id: "sci-gK-15",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.1",
    skill: "Living and nonliving",
    prompt: "Which one is alive?",
    choices: ["Dog", "Rock", "Chair", "Ball"],
    answer: 0,
    explanation: "A dog is alive. It eats, drinks, grows and moves on its own. Rocks, chairs and balls do not.",
    quick: true,
  },
  {
    id: "sci-gK-16",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.1",
    skill: "Living and nonliving",
    prompt: "What do all living things need?",
    choices: ["Water", "Toys", "TV", "Shoes"],
    answer: 0,
    explanation: "Every living thing needs water. Plants, animals and people all need water to live.",
    quick: true,
  },
  {
    id: "sci-gK-17",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.1",
    skill: "Animals alike and different",
    prompt: "What do a robin and a crow both have?",
    choices: ["Feathers", "Fur", "Scales", "Fins"],
    answer: 0,
    explanation: "Robins and crows are both birds, and all birds have feathers.",
    quick: true,
  },
  {
    id: "sci-gK-18",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.1",
    skill: "Animals alike and different",
    prompt: "Two dogs can look different. What can be different?",
    choices: ["Fur color", "Being a dog", "Having a nose", "Needing food"],
    answer: 0,
    explanation: "Dogs can have different fur colors and sizes, but they are all dogs with noses who need food.",
    quick: true,
  },
];
export default questions;
