import type { Question } from "../../types";
// Grade 5 science — NC Standard Course of Study for Science (2023). Matter and energy interactions: weight before and
// after, mixtures, heating/cooling (PS.5.1); force and motion: gravity, friction, mass, position, direction and speed
// (PS.5.2); weather data, severe weather, the ocean's influence on NC weather, and the water cycle (ESS.5.1); human body
// organization and systems (LS.5.1); producers, consumers, decomposers and interconnected ecosystems (LS.5.2);
// inherited vs. acquired traits and instinct vs. learned behavior (LS.5.3).
const questions: Question[] = [
  {
    id: "sci-g5-01",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.1",
    skill: "Conservation of mass",
    passage:
      "Sam put vinegar and a small cup of baking soda inside a zip bag and sealed it. The whole bag weighed 200 g. Then he tipped the cup so they mixed. The bag bubbled and puffed up, but nothing escaped.",
    prompt: "What will the sealed bag weigh now?",
    choices: ["200 g", "More than 200 g", "Less than 200 g", "0 g, because gas has no weight"],
    answer: 0,
    explanation: "Matter is not created or destroyed. The gas made is still inside the sealed bag, so the total weight stays 200 g.",
  },
  {
    id: "sci-g5-02",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.2",
    skill: "Mixtures and new substances",
    prompt: "Stirring sand and iron filings together makes a...",
    choices: ["Mixture", "New substance", "Gas", "Liquid"],
    answer: 0,
    explanation: "In a mixture, each part keeps its properties. You could pull the iron out with a magnet.",
    quick: true,
  },
  {
    id: "sci-g5-03",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.2",
    skill: "Mixtures and new substances",
    prompt: "Which change makes a new substance?",
    choices: ["Burning wood", "Melting ice", "Cutting paper", "Salt in water"],
    answer: 0,
    explanation: "Burning turns wood into ash, smoke and gases, which are new substances. The others only change shape or state or mix.",
    quick: true,
  },
  {
    id: "sci-g5-04",
    subject: "science",
    grade: "5",
    standard: "PS.5.1.3",
    skill: "Heating and cooling materials",
    prompt: "Hot water helps loosen a tight metal jar lid because heated metal...",
    choices: ["Expands", "Shrinks", "Melts", "Freezes"],
    answer: 0,
    explanation: "Most materials expand when heated. The metal lid grows slightly, making it easier to twist off.",
    quick: true,
  },
  {
    id: "sci-g5-05",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Gravity and friction",
    prompt: "Which force pulls objects toward the center of Earth?",
    choices: ["Gravity", "Friction", "Magnetism", "Air resistance"],
    answer: 0,
    explanation: "Gravity pulls everything toward Earth's center. That is why a dropped ball falls down.",
    quick: true,
  },
  {
    id: "sci-g5-06",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Speed",
    prompt: "A car travels 120 miles in 2 hours. What is its average speed?",
    choices: ["60 mph", "240 mph", "122 mph", "30 mph"],
    answer: 0,
    explanation: "Speed = distance ÷ time. 120 miles ÷ 2 hours = 60 miles per hour.",
    quick: true,
  },
  {
    id: "sci-g5-07",
    subject: "science",
    grade: "5",
    standard: "LS.5.3",
    skill: "Inherited and acquired traits",
    prompt: "A scar from falling off a bike is what kind of trait?",
    choices: ["Acquired", "Inherited", "Instinct", "Dominant"],
    answer: 0,
    explanation: "Acquired traits come from life experiences, not from parents. A scar cannot be passed to your children.",
    quick: true,
  },
  {
    id: "sci-g5-08",
    subject: "science",
    grade: "5",
    standard: "PS.5.2",
    skill: "Mass and motion",
    passage:
      "Two identical wagons are pulled with the same force across the same smooth sidewalk. Wagon A is empty. Wagon B is loaded with bricks.",
    prompt: "Which wagon speeds up faster, and why?",
    choices: [
      "Wagon A, because it has less mass",
      "Wagon B, because more weight means more speed",
      "Both the same, because the force is the same",
      "Neither moves, because friction stops them",
    ],
    answer: 0,
    explanation: "With the same force, an object with less mass changes its motion more quickly. More mass means slower speed-up.",
  },
  {
    id: "sci-g5-09",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.1",
    skill: "Weather data",
    passage:
      "High temperatures in Raleigh one week in March: Monday 58°F, Tuesday 62°F, Wednesday 49°F, Thursday 51°F, Friday 55°F.",
    prompt: "Between which two days did the high temperature drop the most?",
    choices: ["Tuesday to Wednesday", "Monday to Tuesday", "Wednesday to Thursday", "Thursday to Friday"],
    answer: 0,
    explanation: "From Tuesday to Wednesday it fell 13°F (62 to 49). A big, sudden drop like that often means a cold front passed.",
  },
  {
    id: "sci-g5-10",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "What provides the energy that drives the water cycle?",
    choices: ["The sun", "The moon", "Earthquakes", "Volcanoes"],
    answer: 0,
    explanation: "The sun heats water so it evaporates. That energy keeps water moving through the cycle.",
    quick: true,
  },
  {
    id: "sci-g5-11",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "Water vapor cooling into tiny droplets is called...",
    choices: ["Condensation", "Evaporation", "Precipitation", "Runoff"],
    answer: 0,
    explanation: "Condensation is gas turning to liquid as it cools. It forms clouds and the water drops on a cold glass.",
    quick: true,
  },
  {
    id: "sci-g5-12",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "Plants give off water vapor through their leaves. This is...",
    choices: ["Transpiration", "Condensation", "Precipitation", "Erosion"],
    answer: 0,
    explanation: "Transpiration is how plants release water vapor from tiny openings in their leaves.",
    quick: true,
  },
  {
    id: "sci-g5-13",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1",
    skill: "Weather prediction",
    prompt: "Air pressure is falling quickly. What weather is most likely soon?",
    choices: ["Stormy", "Clear and dry", "No change", "Cold and sunny"],
    answer: 0,
    explanation: "Falling air pressure usually means rising air, clouds and storms. Rising pressure usually brings clearer skies.",
    quick: true,
  },
  {
    id: "sci-g5-14",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.1",
    skill: "Body organization",
    prompt: "Which list goes from smallest to largest in the human body?",
    choices: [
      "Cell, tissue, organ, organ system, organism",
      "Organ, cell, tissue, organism, organ system",
      "Tissue, cell, organ system, organ, organism",
      "Organism, organ system, organ, tissue, cell",
    ],
    answer: 0,
    explanation: "Cells form tissues, tissues form organs, organs work together in systems, and systems make up the whole organism.",
  },
  {
    id: "sci-g5-15",
    subject: "science",
    grade: "5",
    standard: "LS.5.1",
    skill: "Body systems",
    prompt: "Which organ pumps blood through your body?",
    choices: ["Heart", "Lungs", "Stomach", "Brain"],
    answer: 0,
    explanation: "The heart is a muscle that pumps blood through the circulatory system.",
    quick: true,
  },
  {
    id: "sci-g5-16",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.1",
    skill: "Ecosystems",
    prompt: "In an estuary, river fresh water mixes with...",
    choices: ["Ocean water", "Lava", "Oil", "Snow"],
    answer: 0,
    explanation: "Estuaries like North Carolina's sounds mix fresh and salt water. They are nurseries for many fish and shellfish.",
    quick: true,
  },
  {
    id: "sci-g5-17",
    subject: "science",
    grade: "5",
    standard: "LS.5.2",
    skill: "Food webs",
    prompt: "Organisms that break down dead plants and animals are...",
    choices: ["Decomposers", "Producers", "Predators", "Herbivores"],
    answer: 0,
    explanation: "Decomposers like fungi and bacteria break down dead things and return nutrients to the soil.",
    quick: true,
  },
  {
    id: "sci-g5-18",
    subject: "science",
    grade: "5",
    standard: "LS.5.3",
    skill: "Instinct and learned behavior",
    prompt: "Which is a learned behavior?",
    choices: ["Riding a bike", "Blinking", "Sneezing", "Spinning webs"],
    answer: 0,
    explanation: "You must practice to ride a bike, so it is learned. Blinking, sneezing and a spider spinning webs happen by instinct.",
    quick: true,
  },
  {
    id: "sci-g5-19",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.1",
    skill: "Gravity, friction and mass",
    prompt: "Which surface gives a sliding box the most friction?",
    choices: ["Carpet", "Ice", "Waxed floor", "Wet tile"],
    answer: 0,
    explanation: "Rough surfaces like carpet grip more, so they make more friction and slow things down.",
    quick: true,
  },
  {
    id: "sci-g5-20",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.1",
    skill: "Gravity, friction and mass",
    prompt: "A dropped ball falls more slowly on the moon because the moon has less...",
    choices: ["Gravity", "Air", "Light", "Water"],
    answer: 0,
    explanation: "The moon's gravity is about one-sixth of Earth's, so falling objects speed up much more slowly there.",
    quick: true,
  },
  {
    id: "sci-g5-21",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.1",
    skill: "Gravity, friction and mass",
    prompt: "Why do bike brakes slow the wheel?",
    choices: ["Friction", "Gravity", "Magnetism", "Buoyancy"],
    answer: 0,
    explanation: "Brake pads rub on the wheel. That rubbing force, friction, slows the bike.",
    quick: true,
  },
  {
    id: "sci-g5-22",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.1",
    skill: "Gravity, friction and mass",
    prompt: "A ball rolls off a table. What force pulls it to the floor?",
    choices: ["Gravity", "Friction", "Magnetism", "Wind"],
    answer: 0,
    explanation: "Gravity pulls everything toward Earth's center, so the ball falls.",
    quick: true,
  },
  {
    id: "sci-g5-23",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.2",
    skill: "Position, direction and speed",
    prompt: "A bird flies 30 meters in 3 seconds. What is its speed?",
    choices: ["10 m/s", "90 m/s", "33 m/s", "3 m/s"],
    answer: 0,
    explanation: "Speed = distance ÷ time. 30 m ÷ 3 s = 10 m per second.",
    quick: true,
  },
  {
    id: "sci-g5-24",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.2",
    skill: "Position, direction and speed",
    prompt: "To describe motion fully, give speed and...",
    choices: ["Direction", "Color", "Weight", "Size"],
    answer: 0,
    explanation: "Saying how fast and which way (like 5 m/s north) describes motion completely.",
    quick: true,
  },
  {
    id: "sci-g5-25",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.2",
    skill: "Weather data and severe weather",
    prompt: "A spinning column of air touching the ground is a...",
    choices: ["Tornado", "Hurricane", "Blizzard", "Drought"],
    answer: 0,
    explanation: "A tornado is a narrow, violently spinning column of air that reaches the ground.",
    quick: true,
  },
  {
    id: "sci-g5-26",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.2",
    skill: "Weather data and severe weather",
    prompt: "Hurricanes form over which kind of water?",
    choices: ["Warm ocean", "Cold lakes", "Rivers", "Ice sheets"],
    answer: 0,
    explanation: "Hurricanes get their energy from warm ocean water, usually 80°F or warmer.",
    quick: true,
  },
  {
    id: "sci-g5-27",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.2",
    skill: "Weather data and severe weather",
    prompt: "Which tool measures air pressure?",
    choices: ["Barometer", "Thermometer", "Rain gauge", "Anemometer"],
    answer: 0,
    explanation: "A barometer measures air pressure. Falling pressure often means stormy weather is coming.",
    quick: true,
  },
  {
    id: "sci-g5-28",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.2",
    skill: "Weather data and severe weather",
    prompt: "Puffy, flat-bottomed clouds on a nice day are...",
    choices: ["Cumulus", "Cirrus", "Stratus", "Nimbus"],
    answer: 0,
    explanation: "Cumulus clouds look like puffy cotton and usually mean fair weather.",
    quick: true,
  },
  {
    id: "sci-g5-29",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.3",
    skill: "Ocean and weather",
    prompt: "Coastal NC is milder in winter than the mountains, partly because...",
    choices: ["Ocean holds heat", "More snow", "Higher up", "Fewer trees"],
    answer: 0,
    explanation: "Water warms and cools slowly. The ocean keeps nearby land milder in winter and cooler in summer.",
  },
  {
    id: "sci-g5-30",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.3",
    skill: "Ocean and weather",
    prompt: "The Gulf Stream is a warm...",
    choices: ["Ocean current", "Wind", "River", "Mountain"],
    answer: 0,
    explanation: "The Gulf Stream is a warm ocean current that flows past North Carolina's coast.",
    quick: true,
  },
  {
    id: "sci-g5-31",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.4",
    skill: "Water cycle",
    prompt: "Liquid water turning into water vapor is called...",
    choices: ["Evaporation", "Condensation", "Precipitation", "Freezing"],
    answer: 0,
    explanation: "When the sun heats water, it evaporates into an invisible gas called water vapor.",
    quick: true,
  },
  {
    id: "sci-g5-32",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.2",
    skill: "Body systems",
    prompt: "Which system carries oxygen to your cells?",
    choices: ["Circulatory", "Digestive", "Skeletal", "Muscular"],
    answer: 0,
    explanation: "The circulatory system (heart, blood and blood vessels) carries oxygen and nutrients to every cell.",
    quick: true,
  },
  {
    id: "sci-g5-33",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.2",
    skill: "Body systems",
    prompt: "Which system breaks food into nutrients?",
    choices: ["Digestive", "Respiratory", "Nervous", "Skeletal"],
    answer: 0,
    explanation: "The digestive system breaks food down into nutrients your body can absorb.",
    quick: true,
  },
  {
    id: "sci-g5-34",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.2",
    skill: "Body systems",
    prompt: "Your lungs belong to which system?",
    choices: ["Respiratory", "Circulatory", "Digestive", "Nervous"],
    answer: 0,
    explanation: "The respiratory system takes in oxygen and gets rid of carbon dioxide.",
    quick: true,
  },
  {
    id: "sci-g5-35",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.2",
    skill: "Body systems",
    prompt: "Which system sends messages using the brain and nerves?",
    choices: ["Nervous", "Digestive", "Skeletal", "Respiratory"],
    answer: 0,
    explanation: "The nervous system uses the brain, spinal cord and nerves to send signals around the body.",
    quick: true,
  },
  {
    id: "sci-g5-36",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.2",
    skill: "Producers, consumers, decomposers",
    prompt: "Grass makes its own food from sunlight. Grass is a...",
    choices: ["Producer", "Consumer", "Decomposer", "Predator"],
    answer: 0,
    explanation: "Producers, like plants, make their own food using the sun's energy.",
    quick: true,
  },
  {
    id: "sci-g5-37",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.2",
    skill: "Producers, consumers, decomposers",
    prompt: "A rabbit eats clover. The rabbit is a...",
    choices: ["Consumer", "Producer", "Decomposer", "Fungus"],
    answer: 0,
    explanation: "Consumers get energy by eating other living things.",
    quick: true,
  },
  {
    id: "sci-g5-38",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.2",
    skill: "Producers, consumers, decomposers",
    prompt: "Mushrooms on a rotting log are...",
    choices: ["Decomposers", "Producers", "Predators", "Herbivores"],
    answer: 0,
    explanation: "Mushrooms are fungi that break down dead matter and return nutrients to the soil.",
    quick: true,
  },
  {
    id: "sci-g5-39",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.3",
    skill: "Interconnected ecosystems",
    prompt: "In a food chain, arrows point in the direction energy...",
    choices: ["Flows", "Is lost", "Is made", "Freezes"],
    answer: 0,
    explanation: "Arrows go from the food to the eater, showing which way energy flows.",
    quick: true,
  },
  {
    id: "sci-g5-40",
    subject: "science",
    grade: "5",
    standard: "LS.5.3.1",
    skill: "Instinct and learned behavior",
    prompt: "A spider spins a web without being taught. This is...",
    choices: ["Instinct", "Learned", "Acquired", "A habit"],
    answer: 0,
    explanation: "An instinct is a behavior an animal is born knowing how to do.",
    quick: true,
  },
  {
    id: "sci-g5-41",
    subject: "science",
    grade: "5",
    standard: "LS.5.3.2",
    skill: "Inherited and acquired traits",
    prompt: "Which trait is inherited?",
    choices: ["Eye color", "A tattoo", "Big muscles", "Short hair cut"],
    answer: 0,
    explanation: "Eye color is passed from parents through genes. The others come from experiences or choices.",
    quick: true,
  },
  {
    id: "sci-g5-42",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.2",
    skill: "Position, direction and speed",
    passage:
      "A car's distance from home: 0 h: 0 miles. 1 h: 50 miles. 2 h: 100 miles. 3 h: 100 miles. 4 h: 150 miles.",
    prompt: "During which part of the trip was the car stopped?",
    choices: ["From 2 to 3 hours", "From 0 to 1 hour", "From 1 to 2 hours", "From 3 to 4 hours"],
    answer: 0,
    explanation: "The car's position did not change between hour 2 and hour 3, so it was not moving.",
  },
  {
    id: "sci-g5-43",
    subject: "science",
    grade: "5",
    standard: "PS.5.2.1",
    skill: "Gravity, friction and mass",
    passage:
      "A toy car rolled down a ramp onto three surfaces. It rolled 40 cm on sandpaper, 120 cm on wood, and 180 cm on wax paper.",
    prompt: "Which ramp surface had the most friction?",
    choices: ["Sandpaper", "Wood", "Wax paper", "They were all equal"],
    answer: 0,
    explanation: "The car went the shortest distance on sandpaper because the rough surface made the most friction.",
  },
  {
    id: "sci-g5-44",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.2",
    skill: "Weather data and severe weather",
    passage:
      "Over six hours, the air pressure kept falling, the humidity rose to 95%, and dark clouds moved in from the west.",
    prompt: "What weather is most likely coming soon?",
    choices: ["Rain or storms", "Clear, dry skies", "A heat wave", "No change at all"],
    answer: 0,
    explanation: "Falling pressure, thickening clouds and rising humidity are signs that a storm or rain is on the way.",
  },
  {
    id: "sci-g5-45",
    subject: "science",
    grade: "5",
    standard: "LS.5.2.3",
    skill: "Interconnected ecosystems",
    passage:
      "In a field, grass is eaten by mice, mice are eaten by snakes, and snakes are eaten by hawks.",
    prompt: "What will most likely happen if the snakes disappear?",
    choices: [
      "Mice will increase, and grass will decrease",
      "Mice will decrease, and hawks will increase",
      "Grass will increase, and mice will decrease",
      "Nothing will change",
    ],
    answer: 0,
    explanation: "Snakes eat mice. With fewer predators, mice grow in number and eat more grass.",
  },
  {
    id: "sci-g5-46",
    subject: "science",
    grade: "5",
    standard: "LS.5.1.2",
    skill: "Body systems",
    passage:
      "During a race, Ana breathes faster and her heart beats faster so more oxygen reaches her muscles.",
    prompt: "Which two systems are working together most directly?",
    choices: [
      "Respiratory and circulatory",
      "Digestive and skeletal",
      "Nervous and digestive",
      "Skeletal and muscular",
    ],
    answer: 0,
    explanation: "The lungs (respiratory) bring in oxygen, and the heart and blood (circulatory) carry it to the muscles.",
  },
  {
    id: "sci-g5-47",
    subject: "science",
    grade: "5",
    standard: "LS.5.3.2",
    skill: "Inherited and acquired traits",
    passage:
      "Lia has dimples like her dad. She learned to play the violin last year, has a scar from a bike fall, and just got a short haircut.",
    prompt: "Which of Lia's traits was most likely inherited?",
    choices: ["Her dimples", "Her violin skill", "The scar on her knee", "Her short haircut"],
    answer: 0,
    explanation: "Dimples are passed down from parents through genes. Skills, scars and haircuts are acquired during life.",
  },
  {
    id: "sci-g5-48",
    subject: "science",
    grade: "5",
    standard: "ESS.5.1.3",
    skill: "Ocean and weather",
    passage:
      "On a January afternoon, the beach sand at Wrightsville Beach was 45°F, but the ocean water was 55°F.",
    prompt: "Which statement best explains the difference?",
    choices: [
      "Water changes temperature more slowly than land",
      "The ocean makes its own heat",
      "Sand blocks sunlight",
      "The beach gets less sunlight",
    ],
    answer: 0,
    explanation: "Water heats up and cools down slowly, so in winter it stays warmer than the land near it.",
  },
];
export default questions;
