import type { Question } from "../../types";
// Grade 8 science — NC Standard Course of Study for Science (2023). Atoms, elements, compounds, chemical change and
// conservation of mass (PS.8.1); renewable and nonrenewable energy resources (PS.8.2); Earth's history, rock layers
// and fossils (ESS.8.1); the hydrosphere and water quality (ESS.8.2); microbes and disease (LS.8.1); energy flow and
// matter cycling in ecosystems (LS.8.2); evolution and natural selection (LS.8.3).
const questions: Question[] = [
  {
    id: "sci-g8-01",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Atomic structure",
    prompt: "Which positively charged particles are found in an atom's nucleus?",
    choices: ["Protons", "Electrons", "Neutrons", "Photons"],
    answer: 0,
    explanation: "Protons (+) and neutrons (no charge) are in the nucleus. Electrons (−) move around outside it.",
    quick: true,
  },
  {
    id: "sci-g8-02",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Elements, compounds, mixtures",
    prompt: "Water (H₂O) is best classified as a...",
    choices: ["Compound", "Element", "Mixture", "Single atom"],
    answer: 0,
    explanation: "A compound is two or more elements chemically bonded in a fixed ratio. Water is always 2 hydrogen atoms to 1 oxygen.",
    quick: true,
  },
  {
    id: "sci-g8-03",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Chemical changes",
    prompt: "Which is evidence that a chemical change happened?",
    choices: ["A gas forms", "Ice melts", "Paper is torn", "Salt dissolves"],
    answer: 0,
    explanation: "Unexpected gas, color change, light, or a new solid can show new substances formed. Melting, tearing and dissolving are physical changes.",
    quick: true,
  },
  {
    id: "sci-g8-04",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Conservation of mass",
    passage:
      "In a sealed flask, 10 g of substance A reacts completely with 5 g of substance B. A new solid and a gas are produced, and nothing leaves the flask.",
    prompt: "What is the total mass of the products?",
    choices: ["15 g", "10 g", "5 g", "Less than 15 g, because gas weighs nothing"],
    answer: 0,
    explanation: "In a closed system, atoms are rearranged but not created or destroyed, so mass is conserved: 10 g + 5 g = 15 g.",
  },
  {
    id: "sci-g8-05",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Periodic table",
    prompt: "Elements in the same column (group) of the periodic table have similar...",
    choices: ["Properties", "Masses", "Names", "Discoverers"],
    answer: 0,
    explanation: "Elements in a group have the same number of outer electrons, so they react in similar ways.",
    quick: true,
  },
  {
    id: "sci-g8-06",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Evidence of evolution",
    prompt: "Bat wings and human arms have similar bones. This is evidence of...",
    choices: ["Evolution", "Erosion", "Metamorphism", "Digestion"],
    answer: 0,
    explanation: "Similar (homologous) structures suggest bats and humans share a common ancestor.",
    quick: true,
  },
  {
    id: "sci-g8-07",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Which energy resource is renewable?",
    choices: ["Wind", "Coal", "Natural gas", "Oil"],
    answer: 0,
    explanation: "Wind is replaced naturally and will not run out. Coal, oil and natural gas are fossil fuels that take millions of years to form.",
    quick: true,
  },
  {
    id: "sci-g8-08",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Burning coal releases which greenhouse gas?",
    choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    answer: 0,
    explanation: "Coal is mostly carbon. Burning it combines carbon with oxygen, making carbon dioxide, which traps heat.",
    quick: true,
  },
  {
    id: "sci-g8-09",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Rock layers",
    prompt: "In undisturbed rock layers, where is the oldest layer?",
    choices: ["Bottom", "Top", "Middle", "Surface"],
    answer: 0,
    explanation: "This is the law of superposition: layers are deposited on top of older ones, so the oldest is at the bottom.",
    quick: true,
  },
  {
    id: "sci-g8-10",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Relative dating",
    passage:
      "A cliff shows three flat rock layers: A on top, B in the middle, C on the bottom. A band of igneous rock (an intrusion) cuts through layers C and B but stops at the bottom of layer A.",
    prompt: "What is the correct order of events, oldest to youngest?",
    choices: ["C, B, intrusion, A", "A, B, C, intrusion", "Intrusion, C, B, A", "C, intrusion, B, A"],
    answer: 0,
    explanation: "C and B formed first. The intrusion must be younger than the layers it cuts, and older than layer A, which covers it.",
  },
  {
    id: "sci-g8-11",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Fossils",
    prompt: "Fossils used to date rock layers because they lived briefly but widely are...",
    choices: ["Index fossils", "Trace fossils", "Casts", "Molds"],
    answer: 0,
    explanation: "Index fossils come from species that lived for a short time over a wide area, so they pinpoint a layer's age.",
    quick: true,
  },
  {
    id: "sci-g8-12",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere",
    prompt: "Most of Earth's water is...",
    choices: ["Salt water", "Glacier ice", "Groundwater", "River water"],
    answer: 0,
    explanation: "About 97% of Earth's water is salty ocean water. Only a small part is fresh water we can use.",
    quick: true,
  },
  {
    id: "sci-g8-13",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere",
    prompt: "An estuary forms where a river meets...",
    choices: ["The ocean", "A mountain", "A glacier", "A desert"],
    answer: 0,
    explanation: "Estuaries, like the Albemarle-Pamlico Sound, mix fresh river water with salty ocean water.",
    quick: true,
  },
  {
    id: "sci-g8-14",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Water quality",
    passage:
      "Dissolved oxygen (DO) measured in a stream: at 10°C, 11 mg/L; at 20°C, 9 mg/L; at 30°C, 7.5 mg/L. Many fish become stressed below about 5 mg/L.",
    prompt: "Which conclusion is best supported by these data?",
    choices: [
      "Warmer water holds less oxygen, which can stress fish",
      "Warmer water holds more oxygen, which helps fish",
      "Temperature has no effect on dissolved oxygen",
      "Fish need warmer water to get enough oxygen",
    ],
    answer: 0,
    explanation: "As temperature rose, DO fell. Warm water holds less dissolved gas, so hot summers or warm runoff can harm aquatic life.",
  },
  {
    id: "sci-g8-15",
    subject: "science",
    grade: "8",
    standard: "LS.8.1",
    skill: "Microbes and disease",
    prompt: "Antibiotics can treat illnesses caused by...",
    choices: ["Bacteria", "Viruses", "The flu", "A cold"],
    answer: 0,
    explanation: "Antibiotics kill bacteria. Colds and flu are caused by viruses, so antibiotics do not help them.",
    quick: true,
  },
  {
    id: "sci-g8-16",
    subject: "science",
    grade: "8",
    standard: "LS.8.1",
    skill: "Microbes and disease",
    prompt: "What does a vaccine help the body do?",
    choices: ["Build immunity", "Digest food", "Grow taller", "Make vitamins"],
    answer: 0,
    explanation: "A vaccine trains the immune system to recognize a germ, so the body can fight it quickly later.",
    quick: true,
  },
  {
    id: "sci-g8-17",
    subject: "science",
    grade: "8",
    standard: "LS.8.2",
    skill: "Energy flow in ecosystems",
    prompt: "About how much energy passes from one level of a food chain to the next?",
    choices: ["10%", "50%", "90%", "100%"],
    answer: 0,
    explanation: "Only about 10% is passed on. Most energy is used for life processes or lost as heat.",
    quick: true,
  },
  {
    id: "sci-g8-18",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Natural selection",
    passage:
      "Before the 1800s, most peppered moths in England were light-colored and blended in with pale tree bark. Factory soot then darkened the trees. Within decades, most moths in those areas were dark.",
    prompt: "What best explains the change?",
    choices: [
      "Dark moths were eaten less on dark bark, survived and passed on the trait",
      "Light moths turned dark to hide from birds",
      "Soot dyed the light moths' wings dark",
      "Moths chose to become dark because they needed to",
    ],
    answer: 0,
    explanation: "Natural selection: variation already existed, and the trait that improved survival became more common over generations. Individuals do not change on purpose.",
  },
];
export default questions;
