import type { Question } from "../../types";
// Grade 12 science — NC Standard Course of Study for Science (2023), Physics (PS.Phy). Motion and stability: kinematics,
// Newton's laws and momentum (PS.Phy.1–PS.Phy.3); energy, work and power (PS.Phy.6); waves (PS.Phy.7); electricity
// and electric forces (PS.Phy.8).
const questions: Question[] = [
  {
    id: "sci-g12-01",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "A car goes from 0 to 20 m/s in 4 s. What is its acceleration?",
    choices: ["5 m/s²", "80 m/s²", "0.2 m/s²", "24 m/s²"],
    answer: 0,
    explanation: "a = Δv ÷ t = (20 − 0) m/s ÷ 4 s = 5 m/s².",
    quick: true,
  },
  {
    id: "sci-g12-02",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Motion graphs",
    passage: "A velocity-time graph for a cart is a straight line from 0 m/s at t = 0 s up to 10 m/s at t = 5 s.",
    prompt: "How far does the cart travel during those 5 seconds?",
    choices: ["25 m", "50 m", "10 m", "2 m"],
    answer: 0,
    explanation: "Displacement is the area under a velocity-time graph: a triangle, ½ × 5 s × 10 m/s = 25 m.",
  },
  {
    id: "sci-g12-03",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Free fall",
    prompt: "A ball is thrown straight up. At its highest point, its velocity is...",
    choices: ["Zero", "At its maximum", "9.8 m/s up", "Doubled"],
    answer: 0,
    explanation: "At the top the ball momentarily stops, so v = 0. Its acceleration is still 9.8 m/s² downward the whole time.",
    quick: true,
  },
  {
    id: "sci-g12-04",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Projectile motion",
    prompt: "Ignoring air, one rock is dropped and one thrown sideways from the same height. Which lands first?",
    choices: ["Same time", "Dropped one", "Thrown one", "It depends"],
    answer: 0,
    explanation: "Horizontal and vertical motion are independent. Both start with zero vertical velocity and fall with the same acceleration.",
    quick: true,
  },
  {
    id: "sci-g12-05",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's second law",
    prompt: "A 10 N net force acts on a 2 kg cart. What is its acceleration?",
    choices: ["5 m/s²", "20 m/s²", "12 m/s²", "0.2 m/s²"],
    answer: 0,
    explanation: "Newton's second law: a = F_net ÷ m = 10 N ÷ 2 kg = 5 m/s².",
    quick: true,
  },
  {
    id: "sci-g12-06",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's first law",
    prompt: "An object moving at constant velocity has a net force of...",
    choices: ["Zero", "Its weight", "Increasing", "Its mass"],
    answer: 0,
    explanation: "Newton's first law: with balanced forces (net force zero), an object keeps a constant velocity. A force is not needed to keep moving.",
    quick: true,
  },
  {
    id: "sci-g12-07",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's third law",
    prompt: "You push on a wall with 50 N. How hard does the wall push on you?",
    choices: ["50 N", "0 N", "25 N", "100 N"],
    answer: 0,
    explanation: "Newton's third law: forces come in equal and opposite pairs, so the wall pushes back with 50 N.",
    quick: true,
  },
  {
    id: "sci-g12-08",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Net force and friction",
    passage: "A 10 kg box on a level floor is pulled to the right with a 30 N force. Friction on the box is 10 N to the left.",
    prompt: "What is the box's acceleration?",
    choices: ["2 m/s² to the right", "3 m/s² to the right", "4 m/s² to the right", "0 m/s²; the forces balance"],
    answer: 0,
    explanation: "Net force = 30 N − 10 N = 20 N right. a = 20 N ÷ 10 kg = 2 m/s² to the right.",
  },
  {
    id: "sci-g12-09",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Momentum",
    prompt: "Momentum equals mass times...",
    choices: ["Velocity", "Acceleration", "Force", "Time"],
    answer: 0,
    explanation: "p = mv. Momentum has direction, like velocity, and is measured in kg·m/s.",
    quick: true,
  },
  {
    id: "sci-g12-10",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Conservation of momentum",
    passage:
      "On a frictionless track, a 2 kg cart moving at 3 m/s collides with a 1 kg cart at rest. The carts stick together and move off as one.",
    prompt: "What is their speed right after the collision?",
    choices: ["2 m/s", "3 m/s", "1.5 m/s", "6 m/s"],
    answer: 0,
    explanation: "Momentum is conserved: 2 kg × 3 m/s = 6 kg·m/s before. After: 6 kg·m/s ÷ 3 kg = 2 m/s.",
  },
  {
    id: "sci-g12-11",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Kinetic energy",
    prompt: "What is the kinetic energy of a 2 kg ball moving at 3 m/s?",
    choices: ["9 J", "6 J", "18 J", "3 J"],
    answer: 0,
    explanation: "KE = ½mv² = ½ × 2 kg × (3 m/s)² = 9 J. Speed is squared, so doubling speed would quadruple KE.",
    quick: true,
  },
  {
    id: "sci-g12-12",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Work",
    prompt: "Lifting a 10 N box straight up 2 m does how much work?",
    choices: ["20 J", "5 J", "12 J", "0.2 J"],
    answer: 0,
    explanation: "Work = force × distance in the direction of the force = 10 N × 2 m = 20 J.",
    quick: true,
  },
  {
    id: "sci-g12-13",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Conservation of energy",
    passage:
      "A 50 kg skateboarder starts from rest at the top of a 5 m high frictionless ramp and rolls to the bottom. Use g = 10 m/s².",
    prompt: "How fast is the skateboarder moving at the bottom?",
    choices: ["10 m/s", "50 m/s", "100 m/s", "5 m/s"],
    answer: 0,
    explanation: "PE at top becomes KE at bottom: mgh = ½mv², so v = √(2gh) = √(2 × 10 × 5) = √100 = 10 m/s. Mass cancels out.",
  },
  {
    id: "sci-g12-14",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Power",
    prompt: "Power is work divided by...",
    choices: ["Time", "Distance", "Force", "Mass"],
    answer: 0,
    explanation: "P = W ÷ t. One watt is one joule per second.",
    quick: true,
  },
  {
    id: "sci-g12-15",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Wave equation",
    prompt: "A wave has frequency 5 Hz and wavelength 2 m. What is its speed?",
    choices: ["10 m/s", "2.5 m/s", "7 m/s", "0.4 m/s"],
    answer: 0,
    explanation: "v = fλ = 5 Hz × 2 m = 10 m/s.",
    quick: true,
  },
  {
    id: "sci-g12-16",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Types of waves",
    prompt: "Which of these waves needs a medium to travel?",
    choices: ["Sound", "Light", "Radio", "X-ray"],
    answer: 0,
    explanation: "Sound is a mechanical wave carried by vibrating particles. Light, radio and X-rays are electromagnetic and can cross a vacuum.",
    quick: true,
  },
  {
    id: "sci-g12-17",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Ohm's law",
    prompt: "A 12 V battery is connected across a 4 Ω resistor. What current flows?",
    choices: ["3 A", "48 A", "8 A", "16 A"],
    answer: 0,
    explanation: "Ohm's law: I = V ÷ R = 12 V ÷ 4 Ω = 3 A.",
    quick: true,
  },
  {
    id: "sci-g12-18",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Electric force",
    prompt: "Doubling the distance between two charges changes the force between them to...",
    choices: ["1/4 as much", "1/2 as much", "2 times", "4 times"],
    answer: 0,
    explanation: "Coulomb's law is an inverse-square law: F ∝ 1/r². Twice the distance gives (1/2)² = 1/4 the force.",
    quick: true,
  },
];
export default questions;
