import type { Question } from "../../types";
// Grade 12 science — NC Standard Course of Study for Science (2023), Physics (PS.Phy). Kinematics and projectiles
// (PS.Phy.1); Newton's laws, gravitation, friction and circular motion (PS.Phy.2); momentum and impulse (PS.Phy.3);
// work, energy, power and efficiency (PS.Phy.6); waves, sound and light (PS.Phy.7); electric circuits, charge and
// electromagnetism (PS.Phy.8). Standard numbers above PS.Phy.1 are unconfirmed (see NOTES.md).
const questions: Question[] = [
  {
    id: "sci-g12-01",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "A car goes from 0 to 20 m/s in 4 s. What is its acceleration?",
    choices: ["5 m/s²", "80 m/s²", "0.2 m/s²", "24 m/s²"],
    answer: 0,
    explanation: "a = Δv ÷ t = (20 − 0) m/s ÷ 4 s = 5 m/s².",
    quick: true,
  },
  {
    id: "sci-g12-02",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Motion graphs",
    passage: "A velocity-time graph for a cart is a straight line from 0 m/s at t = 0 s up to 10 m/s at t = 5 s.",
    prompt: "How far does the cart travel during those 5 seconds?",
    choices: ["25 m", "50 m", "10 m", "2 m"],
    answer: 0,
    explanation: "Displacement is the area under a velocity-time graph: a triangle, ½ × 5 s × 10 m/s = 25 m.",
  },
  {
    id: "sci-g12-03",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Free fall",
    prompt: "A ball is thrown straight up. At its highest point, its velocity is...",
    choices: ["Zero", "At its maximum", "9.8 m/s up", "Doubled"],
    answer: 0,
    explanation: "At the top the ball momentarily stops, so v = 0. Its acceleration is still 9.8 m/s² downward the whole time.",
    quick: true,
  },
  {
    id: "sci-g12-04",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Projectile motion",
    prompt: "Ignoring air, one rock is dropped and one thrown sideways from the same height. Which lands first?",
    choices: ["Same time", "Dropped one", "Thrown one", "It depends"],
    answer: 0,
    explanation: "Horizontal and vertical motion are independent. Both start with zero vertical velocity and fall with the same acceleration.",
    quick: true,
  },
  {
    id: "sci-g12-05",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's second law",
    prompt: "A 10 N net force acts on a 2 kg cart. What is its acceleration?",
    choices: ["5 m/s²", "20 m/s²", "12 m/s²", "0.2 m/s²"],
    answer: 0,
    explanation: "Newton's second law: a = F_net ÷ m = 10 N ÷ 2 kg = 5 m/s².",
    quick: true,
  },
  {
    id: "sci-g12-06",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's first law",
    prompt: "An object moving at constant velocity has a net force of...",
    choices: ["Zero", "Its weight", "Increasing", "Its mass"],
    answer: 0,
    explanation: "Newton's first law: with balanced forces (net force zero), an object keeps a constant velocity. A force is not needed to keep moving.",
    quick: true,
  },
  {
    id: "sci-g12-07",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's third law",
    prompt: "You push on a wall with 50 N. How hard does the wall push on you?",
    choices: ["50 N", "0 N", "25 N", "100 N"],
    answer: 0,
    explanation: "Newton's third law: forces come in equal and opposite pairs, so the wall pushes back with 50 N.",
    quick: true,
  },
  {
    id: "sci-g12-08",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Net force and friction",
    passage: "A 10 kg box on a level floor is pulled to the right with a 30 N force. Friction on the box is 10 N to the left.",
    prompt: "What is the box's acceleration?",
    choices: ["2 m/s² to the right", "3 m/s² to the right", "4 m/s² to the right", "0 m/s²; the forces balance"],
    answer: 0,
    explanation: "Net force = 30 N − 10 N = 20 N right. a = 20 N ÷ 10 kg = 2 m/s² to the right.",
  },
  {
    id: "sci-g12-09",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Momentum",
    prompt: "Momentum equals mass times...",
    choices: ["Velocity", "Acceleration", "Force", "Time"],
    answer: 0,
    explanation: "p = mv. Momentum has direction, like velocity, and is measured in kg·m/s.",
    quick: true,
  },
  {
    id: "sci-g12-10",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Conservation of momentum",
    passage:
      "On a frictionless track, a 2 kg cart moving at 3 m/s collides with a 1 kg cart at rest. The carts stick together and move off as one.",
    prompt: "What is their speed right after the collision?",
    choices: ["2 m/s", "3 m/s", "1.5 m/s", "6 m/s"],
    answer: 0,
    explanation: "Momentum is conserved: 2 kg × 3 m/s = 6 kg·m/s before. After: 6 kg·m/s ÷ 3 kg = 2 m/s.",
  },
  {
    id: "sci-g12-11",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Kinetic energy",
    prompt: "What is the kinetic energy of a 2 kg ball moving at 3 m/s?",
    choices: ["9 J", "6 J", "18 J", "3 J"],
    answer: 0,
    explanation: "KE = ½mv² = ½ × 2 kg × (3 m/s)² = 9 J. Speed is squared, so doubling speed would quadruple KE.",
    quick: true,
  },
  {
    id: "sci-g12-12",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Work",
    prompt: "Lifting a 10 N box straight up 2 m does how much work?",
    choices: ["20 J", "5 J", "12 J", "0.2 J"],
    answer: 0,
    explanation: "Work = force × distance in the direction of the force = 10 N × 2 m = 20 J.",
    quick: true,
  },
  {
    id: "sci-g12-13",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Conservation of energy",
    passage:
      "A 50 kg skateboarder starts from rest at the top of a 5 m high frictionless ramp and rolls to the bottom. Use g = 10 m/s².",
    prompt: "How fast is the skateboarder moving at the bottom?",
    choices: ["10 m/s", "50 m/s", "100 m/s", "5 m/s"],
    answer: 0,
    explanation: "PE at top becomes KE at bottom: mgh = ½mv², so v = √(2gh) = √(2 × 10 × 5) = √100 = 10 m/s. Mass cancels out.",
  },
  {
    id: "sci-g12-14",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Power",
    prompt: "Power is work divided by...",
    choices: ["Time", "Distance", "Force", "Mass"],
    answer: 0,
    explanation: "P = W ÷ t. One watt is one joule per second.",
    quick: true,
  },
  {
    id: "sci-g12-15",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Wave equation",
    prompt: "A wave has frequency 5 Hz and wavelength 2 m. What is its speed?",
    choices: ["10 m/s", "2.5 m/s", "7 m/s", "0.4 m/s"],
    answer: 0,
    explanation: "v = fλ = 5 Hz × 2 m = 10 m/s.",
    quick: true,
  },
  {
    id: "sci-g12-16",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Types of waves",
    prompt: "Which of these waves needs a medium to travel?",
    choices: ["Sound", "Light", "Radio", "X-ray"],
    answer: 0,
    explanation: "Sound is a mechanical wave carried by vibrating particles. Light, radio and X-rays are electromagnetic and can cross a vacuum.",
    quick: true,
  },
  {
    id: "sci-g12-17",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Ohm's law",
    prompt: "A 12 V battery is connected across a 4 Ω resistor. What current flows?",
    choices: ["3 A", "48 A", "8 A", "16 A"],
    answer: 0,
    explanation: "Ohm's law: I = V ÷ R = 12 V ÷ 4 Ω = 3 A.",
    quick: true,
  },
  {
    id: "sci-g12-18",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Electric force",
    prompt: "Doubling the distance between two charges changes the force between them to...",
    choices: ["1/4 as much", "1/2 as much", "2 times", "4 times"],
    answer: 0,
    explanation: "Coulomb's law is an inverse-square law: F ∝ 1/r². Twice the distance gives (1/2)² = 1/4 the force.",
    quick: true,
  },
  {
    id: "sci-g12-19",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "Displacement is a vector because it includes...",
    choices: ["Direction", "Mass", "Time", "Energy"],
    answer: 0,
    explanation: "A vector has size and direction. Displacement says how far and which way.",
    quick: true,
  },
  {
    id: "sci-g12-20",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "A car moves at a constant 15 m/s for 4 s. How far does it go?",
    choices: ["60 m", "3.75 m", "19 m", "11 m"],
    answer: 0,
    explanation: "Distance = speed × time = 15 m/s × 4 s = 60 m.",
    quick: true,
  },
  {
    id: "sci-g12-21",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "Near Earth's surface, free-fall acceleration is about...",
    choices: ["9.8 m/s²", "9.8 m/s", "1 m/s²", "98 m/s²"],
    answer: 0,
    explanation: "Ignoring air, everything falls with acceleration g ≈ 9.8 m/s² downward.",
    quick: true,
  },
  {
    id: "sci-g12-22",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Motion graphs",
    prompt: "On a velocity-time graph, the slope equals...",
    choices: ["Acceleration", "Distance", "Velocity", "Mass"],
    answer: 0,
    explanation: "Slope = change in velocity ÷ change in time, which is acceleration. Area under the line is displacement.",
    quick: true,
  },
  {
    id: "sci-g12-23",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Kinematics",
    prompt: "A rock dropped from rest falls for 2 s (g = 10 m/s²). How fast is it going?",
    choices: ["20 m/s", "10 m/s", "5 m/s", "40 m/s"],
    answer: 0,
    explanation: "v = gt = 10 m/s² × 2 s = 20 m/s.",
    quick: true,
  },
  {
    id: "sci-g12-24",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Projectiles",
    prompt: "Ignoring air, a projectile's horizontal velocity...",
    choices: ["Stays constant", "Increases", "Decreases", "Becomes zero"],
    answer: 0,
    explanation: "No horizontal force acts on it, so horizontal velocity does not change. Only vertical velocity changes.",
    quick: true,
  },
  {
    id: "sci-g12-25",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's laws",
    prompt: "What is the weight of a 50 kg person? (g = 9.8 m/s²)",
    choices: ["490 N", "50 N", "5.1 N", "4900 N"],
    answer: 0,
    explanation: "Weight = mg = 50 kg × 9.8 m/s² = 490 N.",
    quick: true,
  },
  {
    id: "sci-g12-26",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Newton's laws",
    prompt: "Newton's first law is also called the law of...",
    choices: ["Inertia", "Gravity", "Momentum", "Action"],
    answer: 0,
    explanation: "An object keeps its state of motion unless a net force acts on it. That resistance to change is inertia.",
    quick: true,
  },
  {
    id: "sci-g12-27",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Gravitation",
    prompt: "If one of two masses doubles, the gravitational force between them...",
    choices: ["Doubles", "Halves", "Quadruples", "Is unchanged"],
    answer: 0,
    explanation: "Gravitational force is proportional to the product of the masses, so doubling one mass doubles the force.",
    quick: true,
  },
  {
    id: "sci-g12-28",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Friction",
    prompt: "μ = 0.2 and the normal force is 100 N. What is the friction force?",
    choices: ["20 N", "500 N", "0.2 N", "100 N"],
    answer: 0,
    explanation: "Friction = μ × normal force = 0.2 × 100 N = 20 N.",
    quick: true,
  },
  {
    id: "sci-g12-29",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.2",
    skill: "Circular motion",
    prompt: "For an object moving in a circle, the net force points...",
    choices: ["Toward center", "Outward", "Forward", "Straight up"],
    answer: 0,
    explanation: "Centripetal force always points toward the center of the circle.",
    quick: true,
  },
  {
    id: "sci-g12-30",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Momentum and impulse",
    prompt: "Impulse equals force multiplied by...",
    choices: ["Time", "Mass", "Distance", "Velocity"],
    answer: 0,
    explanation: "Impulse = FΔt, and it equals the change in momentum.",
    quick: true,
  },
  {
    id: "sci-g12-31",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Momentum and impulse",
    prompt: "What is the momentum of a 1000 kg car moving at 20 m/s?",
    choices: ["20,000 kg·m/s", "50 kg·m/s", "1,020 kg·m/s", "200 kg·m/s"],
    answer: 0,
    explanation: "p = mv = 1000 kg × 20 m/s = 20,000 kg·m/s.",
    quick: true,
  },
  {
    id: "sci-g12-32",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Momentum and impulse",
    prompt: "Airbags reduce the force on a driver by increasing the stopping...",
    choices: ["Time", "Speed", "Mass", "Momentum"],
    answer: 0,
    explanation: "The momentum change is the same, so a longer stopping time means a smaller average force.",
    quick: true,
  },
  {
    id: "sci-g12-33",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Work and energy",
    prompt: "What is the gravitational PE of a 2 kg book 5 m up? (g = 10 m/s²)",
    choices: ["100 J", "10 J", "25 J", "50 J"],
    answer: 0,
    explanation: "PE = mgh = 2 kg × 10 m/s² × 5 m = 100 J.",
    quick: true,
  },
  {
    id: "sci-g12-34",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Power",
    prompt: "A 60 W bulb runs for 10 s. How much energy does it use?",
    choices: ["600 J", "6 J", "70 J", "0.17 J"],
    answer: 0,
    explanation: "Energy = power × time = 60 J/s × 10 s = 600 J.",
    quick: true,
  },
  {
    id: "sci-g12-35",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Sound",
    prompt: "Sound travels fastest through...",
    choices: ["Steel", "Air", "Water", "A vacuum"],
    answer: 0,
    explanation: "Sound moves fastest in stiff solids like steel, slower in water, slower still in air, and not at all in a vacuum.",
    quick: true,
  },
  {
    id: "sci-g12-36",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Sound",
    prompt: "As an ambulance drives toward you, its siren's pitch sounds...",
    choices: ["Higher", "Lower", "The same", "Silent"],
    answer: 0,
    explanation: "The Doppler effect: waves bunch up ahead of a moving source, so the frequency you hear rises.",
    quick: true,
  },
  {
    id: "sci-g12-37",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Electromagnetic waves",
    prompt: "Which electromagnetic wave has the shortest wavelength?",
    choices: ["Gamma rays", "Radio waves", "Microwaves", "Visible light"],
    answer: 0,
    explanation: "Gamma rays have the shortest wavelength and highest frequency and energy.",
    quick: true,
  },
  {
    id: "sci-g12-38",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Wave interactions",
    prompt: "Two waves meet crest to trough and cancel out. This is...",
    choices: ["Destructive", "Constructive", "Refraction", "Diffraction"],
    answer: 0,
    explanation: "Destructive interference happens when waves are out of phase and their amplitudes subtract.",
    quick: true,
  },
  {
    id: "sci-g12-39",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Circuits",
    prompt: "What is the total resistance of 3 Ω and 5 Ω in series?",
    choices: ["8 Ω", "2 Ω", "15 Ω", "1.9 Ω"],
    answer: 0,
    explanation: "In series, resistances add: 3 Ω + 5 Ω = 8 Ω.",
    quick: true,
  },
  {
    id: "sci-g12-40",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Circuits",
    prompt: "What is the total resistance of two 6 Ω resistors in parallel?",
    choices: ["3 Ω", "12 Ω", "6 Ω", "36 Ω"],
    answer: 0,
    explanation: "1/R = 1/6 + 1/6 = 1/3, so R = 3 Ω. Parallel paths lower total resistance.",
    quick: true,
  },
  {
    id: "sci-g12-41",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Electric power",
    prompt: "A device draws 2 A at 120 V. What is its power?",
    choices: ["240 W", "60 W", "122 W", "0.017 W"],
    answer: 0,
    explanation: "P = IV = 2 A × 120 V = 240 W.",
    quick: true,
  },
  {
    id: "sci-g12-42",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Electromagnetism",
    prompt: "A wire carrying electric current produces a...",
    choices: ["Magnetic field", "Gravity field", "Sound wave", "Nuclear force"],
    answer: 0,
    explanation: "Moving charges create a magnetic field around the wire. Electromagnets use this effect.",
    quick: true,
  },
  {
    id: "sci-g12-43",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Electromagnetism",
    prompt: "A generator changes mechanical energy into...",
    choices: ["Electrical", "Chemical", "Nuclear", "Sound"],
    answer: 0,
    explanation: "Spinning a coil in a magnetic field induces an electric current (electromagnetic induction).",
    quick: true,
  },
  {
    id: "sci-g12-44",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.6",
    skill: "Efficiency",
    passage:
      "An electric motor uses 500 J of electrical energy and does 400 J of useful work lifting a load.",
    prompt: "What is the motor's efficiency?",
    choices: ["80%", "125%", "20%", "40%"],
    answer: 0,
    explanation: "Efficiency = useful output ÷ input = 400 J ÷ 500 J = 0.80, or 80%. The rest becomes heat and sound.",
  },
  {
    id: "sci-g12-45",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.8",
    skill: "Circuits",
    passage:
      "A 12 V battery is connected to a 2 Ω resistor and a 4 Ω resistor in series.",
    prompt: "What current flows through the circuit?",
    choices: ["2 A", "6 A", "3 A", "24 A"],
    answer: 0,
    explanation: "Total resistance = 2 Ω + 4 Ω = 6 Ω. I = V/R = 12 V ÷ 6 Ω = 2 A.",
  },
  {
    id: "sci-g12-46",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.1",
    skill: "Projectiles",
    passage:
      "A ball is kicked horizontally off a 20 m high cliff at 5 m/s. Use g = 10 m/s² and ignore air resistance.",
    prompt: "How far from the base of the cliff does the ball land?",
    choices: ["10 m", "5 m", "20 m", "100 m"],
    answer: 0,
    explanation: "Fall time: 20 = ½(10)t², so t = 2 s. Horizontal distance = 5 m/s × 2 s = 10 m.",
  },
  {
    id: "sci-g12-47",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.3",
    skill: "Conservation of momentum",
    passage:
      "Two skaters stand at rest on ice. A 60 kg skater pushes a 40 kg skater, who moves away at 3 m/s.",
    prompt: "What is the velocity of the 60 kg skater?",
    choices: ["2 m/s, opposite way", "3 m/s, opposite way", "2 m/s, same way", "4.5 m/s, opposite way"],
    answer: 0,
    explanation: "Total momentum starts at zero. 40 kg × 3 m/s = 120 kg·m/s, so the 60 kg skater moves 120 ÷ 60 = 2 m/s the opposite way.",
  },
  {
    id: "sci-g12-48",
    subject: "science",
    grade: "12",
    standard: "PS.Phy.7",
    skill: "Wave equation",
    passage:
      "A tuning fork vibrates at 440 Hz. The speed of sound in the room is 343 m/s.",
    prompt: "About what is the wavelength of the sound?",
    choices: ["0.78 m", "1.28 m", "151,000 m", "97 m"],
    answer: 0,
    explanation: "λ = v ÷ f = 343 m/s ÷ 440 Hz ≈ 0.78 m.",
  },
];
export default questions;
