import type { Question } from "../../types";
// Grade 2 science — NC Standard Course of Study for Science (2023). Solids and liquids changing with heating and
// cooling (PS.2.1); sound and vibrating objects, including the parts of the body that make and hear sound (PS.2.2);
// the sun warming land, air and water, weather conditions, patterns and tools (ESS.2.1); animal life cycles
// (LS.2.1); how young animals resemble their parents (LS.2.2).
const questions: Question[] = [
  {
    id: "sci-g2-01",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "What happens to ice when it gets warm?",
    choices: ["It melts", "It grows", "It freezes", "It hardens"],
    answer: 0,
    explanation: "Heat makes ice melt. The solid ice turns into liquid water.",
    quick: true,
  },
  {
    id: "sci-g2-02",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Water in a freezer turns into...",
    choices: ["Ice", "Steam", "Juice", "Sand"],
    answer: 0,
    explanation: "Cooling water enough makes it freeze. Liquid water becomes solid ice.",
    quick: true,
  },
  {
    id: "sci-g2-03",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Butter in a hot pan will...",
    choices: ["Melt", "Freeze", "Grow", "Turn to ice"],
    answer: 0,
    explanation: "Heat changes solid butter into a liquid. That change is called melting.",
    quick: true,
  },
  {
    id: "sci-g2-04",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Heating and cooling",
    prompt: "Melted chocolate put in a fridge becomes...",
    choices: ["Solid again", "A gas", "Water", "Sand"],
    answer: 0,
    explanation: "Cooling turns the liquid chocolate back into a solid. Some changes can go back and forth.",
    quick: true,
  },
  {
    id: "sci-g2-05",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.2",
    skill: "Water before and after freezing",
    passage:
      "Maria filled a cup with water up to a line and weighed it. She put the cup in the freezer overnight. In the morning the ice was above the line. She weighed the cup again, and it weighed the same.",
    prompt: "What changed when Maria's water froze?",
    choices: ["It took up more space", "It got heavier", "It got lighter", "Nothing changed at all"],
    answer: 0,
    explanation: "Water spreads out a little when it freezes, so ice takes up more space. The amount of water did not change, so the weight stayed the same.",
  },
  {
    id: "sci-g2-06",
    subject: "science",
    grade: "2",
    standard: "PS.2.1.1",
    skill: "Solids and liquids",
    prompt: "Is ice a solid or a liquid?",
    choices: ["Solid", "Liquid", "Gas", "Neither"],
    answer: 0,
    explanation: "Ice is a solid. It keeps its own shape. Liquid water takes the shape of its cup.",
    quick: true,
  },
  {
    id: "sci-g2-07",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather tools",
    prompt: "What tool shows which way the wind blows?",
    choices: ["Wind vane", "Ruler", "Scale", "Magnet"],
    answer: 0,
    explanation: "A wind vane turns to point into the wind, showing the direction it is blowing from.",
    quick: true,
  },
  {
    id: "sci-g2-08",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather tools",
    prompt: "A rain gauge measures...",
    choices: ["Rain", "Wind", "Heat", "Sunlight"],
    answer: 0,
    explanation: "A rain gauge collects rain so you can measure how much fell.",
    quick: true,
  },
  {
    id: "sci-g2-09",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Clouds are made of tiny...",
    choices: ["Water drops", "Cotton", "Smoke", "Feathers"],
    answer: 0,
    explanation: "Clouds are made of tiny drops of water or bits of ice floating in the air.",
    quick: true,
  },
  {
    id: "sci-g2-10",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Which storm has lightning and thunder?",
    choices: ["Thunderstorm", "Snow flurry", "Fog", "Drizzle"],
    answer: 0,
    explanation: "Thunderstorms have lightning, and lightning makes the loud sound of thunder.",
    quick: true,
  },
  {
    id: "sci-g2-11",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather",
    prompt: "Which weather is best for flying a kite?",
    choices: ["Windy", "Calm", "Foggy", "Rainy"],
    answer: 0,
    explanation: "Moving air, or wind, lifts a kite into the sky.",
    quick: true,
  },
  {
    id: "sci-g2-12",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather patterns",
    passage:
      "A class kept a weather chart for one week. Monday: sunny. Tuesday: rainy. Wednesday: rainy. Thursday: sunny. Friday: rainy.",
    prompt: "Which kind of weather happened the most that week?",
    choices: ["Rainy", "Sunny", "Snowy", "Windy"],
    answer: 0,
    explanation: "There were 3 rainy days and 2 sunny days. Counting the days on a chart helps us find weather patterns.",
  },
  {
    id: "sci-g2-13",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1",
    skill: "Weather patterns",
    prompt: "In North Carolina, which season is usually the hottest?",
    choices: ["Summer", "Winter", "Fall", "Spring"],
    answer: 0,
    explanation: "Summer is usually the hottest season. Weather follows a pattern through the year.",
    quick: true,
  },
  {
    id: "sci-g2-14",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "A caterpillar grows into a...",
    choices: ["Butterfly", "Frog", "Bird", "Bee"],
    answer: 0,
    explanation: "A butterfly's life cycle is egg, caterpillar (larva), chrysalis (pupa), then adult butterfly.",
    quick: true,
  },
  {
    id: "sci-g2-15",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "What does a tadpole grow into?",
    choices: ["Frog", "Fish", "Snake", "Turtle"],
    answer: 0,
    explanation: "A tadpole grows legs, loses its tail and becomes a frog.",
    quick: true,
  },
  {
    id: "sci-g2-16",
    subject: "science",
    grade: "2",
    standard: "LS.2.1",
    skill: "Animal life cycles",
    prompt: "What comes first in a chicken's life cycle?",
    choices: ["Egg", "Chick", "Hen", "Rooster"],
    answer: 0,
    explanation: "A chicken starts as an egg, hatches into a chick, and grows into an adult hen or rooster.",
    quick: true,
  },
  {
    id: "sci-g2-17",
    subject: "science",
    grade: "2",
    standard: "LS.2.2",
    skill: "Traits from parents",
    prompt: "Why do puppies look like their parents?",
    choices: ["Share traits", "Same food", "Copying them", "Good luck"],
    answer: 0,
    explanation: "Babies get traits from their parents, like fur color and ear shape. That is why they look alike.",
    quick: true,
  },
  {
    id: "sci-g2-18",
    subject: "science",
    grade: "2",
    standard: "LS.2.2",
    skill: "Traits from parents",
    prompt: "Kittens from the same mom can have different...",
    choices: ["Fur colors", "Number of legs", "Animal kinds", "Number of eyes"],
    answer: 0,
    explanation: "Kittens are like their parents in many ways but can still differ in things like fur color.",
    quick: true,
  },
  {
    id: "sci-g2-19",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.1",
    skill: "Sound and vibration",
    prompt: "Sound is made when things...",
    choices: ["Vibrate", "Freeze", "Melt", "Glow"],
    answer: 0,
    explanation: "A vibration is a quick back-and-forth shake. Vibrating things make sound.",
    quick: true,
  },
  {
    id: "sci-g2-20",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.2",
    skill: "Sound and the body",
    prompt: "Hum with your hand on your throat. What do you feel?",
    choices: ["Vibrations", "Ice", "Wind", "Water"],
    answer: 0,
    explanation: "When you hum, parts inside your throat vibrate. You can feel the shaking with your hand.",
    quick: true,
  },
  {
    id: "sci-g2-21",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.1",
    skill: "Sound and vibration",
    prompt: "You hit a drum harder. The sound gets...",
    choices: ["Louder", "Softer", "Slower", "Silent"],
    answer: 0,
    explanation: "A harder hit makes bigger vibrations, and bigger vibrations make a louder sound.",
    quick: true,
  },
  {
    id: "sci-g2-22",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.1",
    skill: "Sound and vibration",
    prompt: "Which plucked rubber band makes a higher sound?",
    choices: ["Short, tight", "Long, loose", "Long, slack", "Thick, loose"],
    answer: 0,
    explanation: "Short, tight rubber bands vibrate faster, and faster vibrations make higher sounds.",
    quick: true,
  },
  {
    id: "sci-g2-23",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.1",
    skill: "Sound and vibration",
    prompt: "Blowing across a bottle top makes a sound. What vibrates?",
    choices: ["Air inside", "The label", "The cap", "The table"],
    answer: 0,
    explanation: "Blowing makes the column of air inside the bottle vibrate, and that makes the sound.",
    quick: true,
  },
  {
    id: "sci-g2-24",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.2",
    skill: "Sound and the body",
    prompt: "Which part of your ear vibrates when sound comes in?",
    choices: ["Eardrum", "Earlobe", "Ear wax", "Hair"],
    answer: 0,
    explanation: "Sound makes your eardrum vibrate. Your ear sends that message to your brain so you can hear.",
    quick: true,
  },
  {
    id: "sci-g2-25",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.2",
    skill: "Sound and the body",
    prompt: "Which body parts vibrate to make your voice?",
    choices: ["Vocal cords", "Knees", "Hair", "Fingernails"],
    answer: 0,
    explanation: "Air from your lungs makes your vocal cords vibrate. That is the sound of your voice.",
    quick: true,
  },
  {
    id: "sci-g2-26",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.1",
    skill: "The sun warms Earth",
    prompt: "What warms the land, air and water on Earth?",
    choices: ["The sun", "The moon", "Clouds", "Wind"],
    answer: 0,
    explanation: "Energy from the sun gives us light and warms the land, air and water.",
    quick: true,
  },
  {
    id: "sci-g2-27",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.1",
    skill: "The sun warms Earth",
    prompt: "At noon on a sunny day, which feels the hottest?",
    choices: ["Dark pavement", "Shady grass", "Pond water", "A cool cave"],
    answer: 0,
    explanation: "Dark pavement soaks up a lot of sunlight and gets hot fast. Shade, water and caves stay cooler.",
    quick: true,
  },
  {
    id: "sci-g2-28",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.1",
    skill: "The sun warms Earth",
    prompt: "Why is it cooler under a tree than in the open?",
    choices: ["Less sunlight", "More rain", "Less air", "More sand"],
    answer: 0,
    explanation: "The tree's leaves block sunlight, so less of the sun's energy warms the ground in the shade.",
    quick: true,
  },
  {
    id: "sci-g2-29",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.2",
    skill: "Weather conditions",
    prompt: "The thermometer reads 95°F. The day is...",
    choices: ["Hot", "Freezing", "Snowy", "Icy"],
    answer: 0,
    explanation: "95°F is a hot temperature. Water freezes at 32°F.",
    quick: true,
  },
  {
    id: "sci-g2-30",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.2",
    skill: "Weather conditions",
    prompt: "Water freezes at which temperature?",
    choices: ["32°F", "0°F", "50°F", "100°F"],
    answer: 0,
    explanation: "Water freezes into ice at 32 degrees Fahrenheit. Below that, puddles turn to ice.",
    quick: true,
  },
  {
    id: "sci-g2-31",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.2",
    skill: "Weather conditions",
    prompt: "Rain, snow, sleet and hail are all kinds of...",
    choices: ["Precipitation", "Wind", "Clouds", "Fog"],
    answer: 0,
    explanation: "Precipitation is any water that falls from clouds to the ground.",
    quick: true,
  },
  {
    id: "sci-g2-32",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.3",
    skill: "Weather patterns",
    prompt: "What time of day is usually the warmest?",
    choices: ["Afternoon", "Early morning", "Midnight", "Before sunrise"],
    answer: 0,
    explanation: "The sun warms the land all morning, so the afternoon is usually the warmest time of day.",
    quick: true,
  },
  {
    id: "sci-g2-33",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.3",
    skill: "Weather patterns",
    prompt: "Compared with summer days, winter days are...",
    choices: ["Shorter", "Longer", "Hotter", "The same"],
    answer: 0,
    explanation: "In winter there are fewer hours of daylight, so the days are shorter.",
    quick: true,
  },
  {
    id: "sci-g2-34",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.4",
    skill: "Weather tools",
    prompt: "Which tool measures how fast the wind blows?",
    choices: ["Anemometer", "Rain gauge", "Thermometer", "Wind vane"],
    answer: 0,
    explanation: "An anemometer has cups that spin in the wind. The faster they spin, the faster the wind.",
    quick: true,
  },
  {
    id: "sci-g2-35",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.4",
    skill: "Weather tools",
    prompt: "A windsock hangs straight down. This means...",
    choices: ["No wind", "Strong wind", "Heavy rain", "Hot sun"],
    answer: 0,
    explanation: "Wind fills a windsock and lifts it. When it hangs down, the air is calm.",
    quick: true,
  },
  {
    id: "sci-g2-36",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.4",
    skill: "Weather tools",
    prompt: "Forecasters use satellite pictures from space to see...",
    choices: ["Clouds, storms", "Earthquakes", "Deep caves", "Fish"],
    answer: 0,
    explanation: "Weather satellites take pictures of clouds and storms so forecasters can predict the weather.",
    quick: true,
  },
  {
    id: "sci-g2-37",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.2",
    skill: "Animal life cycles",
    prompt: "Which animal hatches from an egg?",
    choices: ["Turtle", "Dog", "Cow", "Horse"],
    answer: 0,
    explanation: "Turtles hatch from eggs. Dogs, cows and horses are born live.",
    quick: true,
  },
  {
    id: "sci-g2-38",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.2",
    skill: "Animal life cycles",
    prompt: "Puppies are born live. Which baby is also born live?",
    choices: ["Kitten", "Chick", "Tadpole", "Duckling"],
    answer: 0,
    explanation: "Kittens are born live, like puppies. Chicks, tadpoles and ducklings hatch from eggs.",
    quick: true,
  },
  {
    id: "sci-g2-39",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.2",
    skill: "Animal life cycles",
    prompt: "Butterfly life cycle: egg, larva, pupa, then...",
    choices: ["Adult", "Seed", "Tadpole", "Egg"],
    answer: 0,
    explanation: "After the pupa (chrysalis) stage, an adult butterfly comes out.",
    quick: true,
  },
  {
    id: "sci-g2-40",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.1",
    skill: "Animal life cycles",
    prompt: "Inside a chrysalis, a caterpillar...",
    choices: ["Changes form", "Lays eggs", "Eats leaves", "Hatches"],
    answer: 0,
    explanation: "Inside the chrysalis, the caterpillar's body changes into a butterfly.",
    quick: true,
  },
  {
    id: "sci-g2-41",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.1",
    skill: "Animal life cycles",
    prompt: "Which stage is part of every animal's life cycle?",
    choices: ["Growing up", "Having wings", "Being a pupa", "Living in water"],
    answer: 0,
    explanation: "Every animal is born or hatches, grows up, can have young, and dies.",
  },
  {
    id: "sci-g2-42",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.2",
    skill: "Animal life cycles",
    prompt: "A young grasshopper looks like a small adult. It is called a...",
    choices: ["Nymph", "Pupa", "Tadpole", "Calf"],
    answer: 0,
    explanation: "Young grasshoppers are nymphs. They grow and shed their skin until they are adults.",
    quick: true,
  },
  {
    id: "sci-g2-43",
    subject: "science",
    grade: "2",
    standard: "LS.2.2.1",
    skill: "Like their parents",
    prompt: "Which trait does a calf get from its parents?",
    choices: ["Spot pattern", "A scar", "Its name", "Muddy legs"],
    answer: 0,
    explanation: "Spot patterns are passed from parents to young. Scars, names and mud are not.",
    quick: true,
  },
  {
    id: "sci-g2-44",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.2",
    skill: "Weather conditions",
    passage:
      "Ms. Lee's class read the thermometer at noon. Monday: 50°F. Tuesday: 55°F. Wednesday: 62°F. Thursday: 70°F.",
    prompt: "What pattern do the temperatures show?",
    choices: ["It got warmer each day", "It got colder each day", "It stayed the same", "It went up and down"],
    answer: 0,
    explanation: "Each day's temperature was higher than the day before, so it warmed up all week.",
  },
  {
    id: "sci-g2-45",
    subject: "science",
    grade: "2",
    standard: "PS.2.2.1",
    skill: "Sound and vibration",
    passage:
      "Zoe stretched plastic wrap over a bowl and sprinkled rice on top. When she banged a pot nearby, the rice jumped.",
    prompt: "Why did the rice jump?",
    choices: ["The sound made the wrap vibrate", "Wind blew the rice", "The rice got hot", "A magnet pulled the rice"],
    answer: 0,
    explanation: "Sound travels as vibrations. The vibrations shook the plastic wrap and bounced the rice.",
  },
  {
    id: "sci-g2-46",
    subject: "science",
    grade: "2",
    standard: "LS.2.1.2",
    skill: "Animal life cycles",
    passage:
      "A butterfly starts as an egg, then a caterpillar, then a pupa, then an adult. A frog starts as an egg, then a tadpole, then a froglet, then an adult.",
    prompt: "What is true of both animals?",
    choices: [
      "Their young look different from the adults",
      "They both have feathers",
      "They are both born live",
      "They both live in trees",
    ],
    answer: 0,
    explanation: "A caterpillar looks very different from a butterfly, and a tadpole looks very different from a frog.",
  },
  {
    id: "sci-g2-47",
    subject: "science",
    grade: "2",
    standard: "ESS.2.1.1",
    skill: "The sun warms Earth",
    passage:
      "Kim filled two cups with cool water. She put one cup in the sun and one in the shade for an hour.",
    prompt: "Which cup of water will be warmer?",
    choices: ["The cup in the sun", "The cup in the shade", "They will be the same", "Both will freeze"],
    answer: 0,
    explanation: "Sunlight warms water. The cup in the sun gets more of the sun's energy, so it gets warmer.",
  },
  {
    id: "sci-g2-48",
    subject: "science",
    grade: "2",
    standard: "LS.2.2.1",
    skill: "Like their parents",
    passage:
      "A gray mother cat had four kittens. Two kittens are gray, one is black, and one is gray with white paws.",
    prompt: "Which is most likely true about the kittens?",
    choices: [
      "They look like cats but not all alike",
      "They will grow up to be dogs",
      "They all look exactly the same",
      "They do not look like their mom",
    ],
    answer: 0,
    explanation: "Young animals look a lot like their parents, but each one can be a little different, like fur color.",
  },
];
export default questions;
