import type { Question } from "../../types";
// Grade 6 science — NC Standard Course of Study for Science (2023). Matter: atoms, particle motion, density (PS.6.1);
// thermal energy transfer, conductors and insulators (PS.6.2); waves (PS.6.3); Earth-moon-sun system (ESS.6.1);
// lithosphere and plate tectonics (ESS.6.2); soil stewardship (ESS.6.3); plant structures and processes (LS.6.1);
// biomes and abiotic/biotic factors (LS.6.2).
const questions: Question[] = [
  {
    id: "sci-g6-01",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.3",
    skill: "Density",
    prompt: "Density equals mass divided by...",
    choices: ["Volume", "Weight", "Speed", "Area"],
    answer: 0,
    explanation: "Density = mass ÷ volume. It tells how much matter is packed into a given space.",
    quick: true,
  },
  {
    id: "sci-g6-02",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.3",
    skill: "Density",
    passage:
      "A small block has a mass of 60 g and a volume of 20 cm³. Fresh water has a density of 1 g/cm³.",
    prompt: "What is the block's density, and will it float or sink in fresh water?",
    choices: ["3 g/cm³; it sinks", "3 g/cm³; it floats", "1200 g/cm³; it sinks", "0.33 g/cm³; it floats"],
    answer: 0,
    explanation: "60 g ÷ 20 cm³ = 3 g/cm³. Objects denser than water (more than 1 g/cm³) sink.",
  },
  {
    id: "sci-g6-03",
    subject: "science",
    grade: "6",
    standard: "PS.6.1.2",
    skill: "Particle motion",
    prompt: "When a substance is heated, its particles...",
    choices: ["Move faster", "Slow down", "Get bigger", "Stop moving"],
    answer: 0,
    explanation: "Adding thermal energy makes particles move faster and spread apart. The particles themselves do not grow.",
    quick: true,
  },
  {
    id: "sci-g6-04",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "A metal spoon in hot soup gets hot. This transfer is...",
    choices: ["Conduction", "Convection", "Radiation", "Insulation"],
    answer: 0,
    explanation: "Conduction is heat moving through direct contact, particle to particle, like along a metal spoon.",
    quick: true,
  },
  {
    id: "sci-g6-05",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "Warm air rising and cool air sinking in a room is...",
    choices: ["Convection", "Conduction", "Radiation", "Reflection"],
    answer: 0,
    explanation: "Convection moves heat through fluids (liquids and gases) as warmer, less dense material rises and cooler material sinks.",
    quick: true,
  },
  {
    id: "sci-g6-06",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.1",
    skill: "Heat transfer",
    prompt: "How does the sun's energy reach Earth through space?",
    choices: ["Radiation", "Conduction", "Convection", "Friction"],
    answer: 0,
    explanation: "Space is nearly empty, so heat cannot be conducted or convected. It travels as radiation (electromagnetic waves).",
    quick: true,
  },
  {
    id: "sci-g6-07",
    subject: "science",
    grade: "6",
    standard: "PS.6.2.3",
    skill: "Insulators",
    passage:
      "Students poured 80°C water into three cups of the same size: metal, glass and foam. After 20 minutes the water temperatures were: metal 45°C, glass 55°C, foam 70°C.",
    prompt: "Which conclusion do the data best support?",
    choices: [
      "Foam is the best insulator of the three",
      "Metal is the best insulator of the three",
      "All three cups insulate equally well",
      "Glass let the most heat escape",
    ],
    answer: 0,
    explanation: "The foam cup lost the least heat (only 10°C), so it slowed heat transfer best. Metal lost the most, so it is a good conductor.",
  },
  {
    id: "sci-g6-08",
    subject: "science",
    grade: "6",
    standard: "PS.6.3",
    skill: "Waves",
    prompt: "A wave's height from rest to crest, linked to its energy, is its...",
    choices: ["Amplitude", "Frequency", "Wavelength", "Speed"],
    answer: 0,
    explanation: "Amplitude is how far a wave moves from its rest position. Bigger amplitude means more energy, like a louder sound.",
    quick: true,
  },
  {
    id: "sci-g6-09",
    subject: "science",
    grade: "6",
    standard: "PS.6.3",
    skill: "Waves",
    prompt: "Sound cannot travel through...",
    choices: ["Empty space", "Water", "Steel", "Air"],
    answer: 0,
    explanation: "Sound is a mechanical wave that needs particles to vibrate. Space is a vacuum, so there is no sound there.",
    quick: true,
  },
  {
    id: "sci-g6-10",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1",
    skill: "Seasons",
    prompt: "What mainly causes Earth's seasons?",
    choices: ["Tilted axis", "Sun distance", "Moon's pull", "Cloud cover"],
    answer: 0,
    explanation: "Earth's tilted axis makes each hemisphere get more direct sunlight for part of the year. Distance to the sun barely changes.",
    quick: true,
  },
  {
    id: "sci-g6-11",
    subject: "science",
    grade: "6",
    standard: "ESS.6.1",
    skill: "Gravity and orbits",
    prompt: "What keeps the planets in orbit around the sun?",
    choices: ["Gravity", "Magnetism", "Friction", "Solar wind"],
    answer: 0,
    explanation: "The sun's gravity pulls on the planets and keeps them moving in orbits.",
    quick: true,
  },
  {
    id: "sci-g6-12",
    subject: "science",
    grade: "6",
    standard: "ESS.6.2",
    skill: "Plate tectonics",
    passage:
      "An ocean plate and a continental plate are moving toward each other. The denser ocean plate slides beneath the continental plate.",
    prompt: "Which features are most likely to form at this boundary?",
    choices: [
      "A deep ocean trench and a chain of volcanoes",
      "A mid-ocean ridge with new seafloor",
      "A wide, flat plain with no earthquakes",
      "A river delta",
    ],
    answer: 0,
    explanation: "When one plate subducts, a trench forms and the sinking plate melts, feeding volcanoes, like the Andes. Ridges form where plates pull apart.",
  },
  {
    id: "sci-g6-13",
    subject: "science",
    grade: "6",
    standard: "ESS.6.2",
    skill: "Changes to Earth's surface",
    prompt: "Weathering and erosion are examples of which kind of force?",
    choices: ["Destructive", "Constructive", "Magnetic", "Electric"],
    answer: 0,
    explanation: "Destructive forces wear land down. Constructive forces, like volcanoes and deposition, build land up.",
    quick: true,
  },
  {
    id: "sci-g6-14",
    subject: "science",
    grade: "6",
    standard: "ESS.6.3",
    skill: "Soil stewardship",
    prompt: "Farmers plant cover crops in winter mainly to...",
    choices: ["Stop erosion", "Kill insects", "Warm the air", "Dry the soil"],
    answer: 0,
    explanation: "Cover crop roots hold soil in place and add nutrients, protecting soil quality between harvests.",
    quick: true,
  },
  {
    id: "sci-g6-15",
    subject: "science",
    grade: "6",
    standard: "LS.6.1",
    skill: "Plant processes",
    prompt: "Plants make their own food (sugar) using light by...",
    choices: ["Photosynthesis", "Respiration", "Digestion", "Pollination"],
    answer: 0,
    explanation: "In photosynthesis, plants use light energy, carbon dioxide and water to make sugar and release oxygen.",
    quick: true,
  },
  {
    id: "sci-g6-16",
    subject: "science",
    grade: "6",
    standard: "LS.6.1",
    skill: "Plant structures",
    prompt: "Tiny openings in leaves that let gases in and out are...",
    choices: ["Stomata", "Xylem", "Roots", "Petals"],
    answer: 0,
    explanation: "Stomata let carbon dioxide in and oxygen and water vapor out. Xylem carries water up from the roots.",
    quick: true,
  },
  {
    id: "sci-g6-17",
    subject: "science",
    grade: "6",
    standard: "LS.6.2",
    skill: "Biomes",
    prompt: "Which biome has frozen ground (permafrost) and almost no trees?",
    choices: ["Tundra", "Rainforest", "Grassland", "Desert"],
    answer: 0,
    explanation: "The tundra is cold with permafrost, so deep tree roots cannot grow. Low plants like mosses and lichens survive.",
    quick: true,
  },
  {
    id: "sci-g6-18",
    subject: "science",
    grade: "6",
    standard: "LS.6.2",
    skill: "Abiotic and biotic factors",
    passage:
      "A student grew bean plants in four trays with the same soil and water. Tray 1 got 12 hours of light a day, Tray 2 got 8 hours, Tray 3 got 4 hours, and Tray 4 got none. After two weeks, Tray 1 plants were tallest and greenest; Tray 4 plants were pale and weak.",
    prompt: "Which factor was tested, and what type of factor is it?",
    choices: [
      "Amount of sunlight; abiotic",
      "Amount of sunlight; biotic",
      "Type of soil; abiotic",
      "Kind of plant; biotic",
    ],
    answer: 0,
    explanation: "Only light changed between trays, so light was tested. Sunlight is nonliving, which makes it an abiotic factor.",
  },
];
export default questions;
