import type { Question } from "../../types";

// Grade K ELA — NC Standard Course of Study for ELA (2017). RF.K.1 print concepts, RF.K.3 phonological awareness, RF.K.4 phonics/sight words, RL.K.3, RL.K.6, L.K.1, L.K.5
const questions: Question[] = [
  {
    id: "ela-gK-01",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with cat?",
    choices: ["hat", "dog", "cup", "sun"],
    answer: 0,
    explanation: "Cat and hat both end with the -at sound, so they rhyme.",
    quick: true,
  },
  {
    id: "ela-gK-02",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with bug?",
    choices: ["rug", "bed", "cap", "fox"],
    answer: 0,
    explanation: "Bug and rug both end with -ug. Rhyming words sound the same at the end.",
    quick: true,
  },
  {
    id: "ela-gK-03",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with pig?",
    choices: ["wig", "pan", "top", "sit"],
    answer: 0,
    explanation: "Pig and wig both end with -ig, so they rhyme.",
    quick: true,
  },
  {
    id: "ela-gK-04",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Beginning sounds",
    prompt: "Which word starts with the same sound as ball?",
    choices: ["bat", "cat", "sun", "map"],
    answer: 0,
    explanation: "Ball and bat both start with the /b/ sound.",
    quick: true,
  },
  {
    id: "ela-gK-05",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Beginning sounds",
    prompt: "Which word starts with the /s/ sound?",
    choices: ["sock", "fish", "moon", "tree"],
    answer: 0,
    explanation: "Sock starts with /s/, like snake and sun.",
    quick: true,
  },
  {
    id: "ela-gK-06",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Syllables",
    prompt: "Clap it out! How many syllables are in rabbit?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "Rab-bit has two claps, so it has two syllables.",
    quick: true,
  },
  {
    id: "ela-gK-07",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Ending sounds",
    prompt: "Which word ends with the /t/ sound?",
    choices: ["hat", "dog", "bus", "cup"],
    answer: 0,
    explanation: "Hat ends with /t/. Say it slowly: h-a-t.",
    quick: true,
  },
  {
    id: "ela-gK-08",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Middle sounds",
    prompt: "What is the middle sound in sun?",
    choices: ["/u/", "/s/", "/n/", "/a/"],
    answer: 0,
    explanation: "Sun is s-u-n. The sound in the middle is the short u, /u/.",
    quick: true,
  },
  {
    id: "ela-gK-09",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Letter sounds",
    prompt: "Which letter makes the first sound in fan?",
    choices: ["F", "V", "P", "T"],
    answer: 0,
    explanation: "Fan starts with /f/, and the letter F makes that sound.",
    quick: true,
  },
  {
    id: "ela-gK-10",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Sight words",
    prompt: "Which word says 'the'?",
    choices: ["the", "then", "they", "tea"],
    answer: 0,
    explanation: "T-h-e spells the. It is a sight word we see in almost every book.",
    quick: true,
  },
  {
    id: "ela-gK-11",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Short vowels",
    prompt: "Change the a in cat to u. What new word do you get?",
    choices: ["cut", "cot", "kit", "cap"],
    answer: 0,
    explanation: "C-a-t becomes c-u-t. Changing the middle vowel makes a new word.",
    quick: true,
  },
  {
    id: "ela-gK-12",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Print concepts",
    prompt: "Which way do we read words in English?",
    choices: ["Left to right", "Right to left", "Bottom to top", "Any way"],
    answer: 0,
    explanation: "In English we read from left to right, then go down to the next line.",
    quick: true,
  },
  {
    id: "ela-gK-13",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Print concepts",
    prompt: "What goes between words in a sentence?",
    choices: ["Spaces", "Pictures", "Numbers", "Colors"],
    answer: 0,
    explanation: "Spaces show where one word ends and the next word begins.",
    quick: true,
  },
  {
    id: "ela-gK-14",
    subject: "ela",
    grade: "K",
    standard: "L.K.1",
    skill: "Plurals",
    prompt: "Which word means more than one dog?",
    choices: ["dogs", "dog", "dug", "dig"],
    answer: 0,
    explanation: "Adding -s to dog makes dogs, which means more than one.",
    quick: true,
  },
  {
    id: "ela-gK-15",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Opposites",
    prompt: "What is the opposite of hot?",
    choices: ["cold", "warm", "big", "fast"],
    answer: 0,
    explanation: "Cold is the opposite of hot. Warm is only a little bit hot.",
    quick: true,
  },
  {
    id: "ela-gK-16",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Sorting words",
    prompt: "Which one is a fruit?",
    choices: ["apple", "carrot", "bread", "milk"],
    answer: 0,
    explanation: "An apple is a fruit. A carrot is a vegetable.",
    quick: true,
  },
  {
    id: "ela-gK-17",
    subject: "ela",
    grade: "K",
    standard: "RL.K.3",
    skill: "Story elements",
    prompt: "Where and when a story happens is called the...",
    choices: ["setting", "character", "title", "author"],
    answer: 0,
    explanation: "The setting tells where and when a story takes place.",
    quick: true,
  },
  {
    id: "ela-gK-18",
    subject: "ela",
    grade: "K",
    standard: "RL.K.6",
    skill: "Author and illustrator",
    prompt: "Who writes the words in a book?",
    choices: ["author", "illustrator", "reader", "teacher"],
    answer: 0,
    explanation: "The author writes the words. The illustrator draws the pictures.",
    quick: true,
  },
];

export default questions;
