import type { DeliveryRule } from "./types";

/*
 * Science delivery rules, K–12 (NC Standard Course of Study for Science, 2023).
 * Codes follow the kit's science banks: LS.3.x, PS.4.x, ESS.EES.x, LS.Bio.x, PS.Chm.x, PS.Phy.x.
 * Items were chosen so each one is clearly in or out (no "it depends" cases).
 * Chemical formulas use the font's subscript markup: CO[2] draws as CO₂.
 */

const ROCKS_IGNEOUS = ["GRANITE", "BASALT", "OBSIDIAN", "PUMICE", "GABBRO", "RHYOLITE", "ANDESITE", "DIORITE", "SCORIA"];
const ROCKS_SEDIMENTARY = ["SANDSTONE", "LIMESTONE", "SHALE", "COAL", "CHALK", "BRECCIA", "SILTSTONE", "MUDSTONE", "ROCK SALT"];
const ROCKS_METAMORPHIC = ["MARBLE", "SLATE", "QUARTZITE", "GNEISS", "SCHIST", "PHYLLITE", "SOAPSTONE", "HORNFELS"];

export const SCIENCE_RULES: DeliveryRule[] = [
  // ---------------------------------------------------------------- K
  {
    id: "s-k-living", subject: "science", grades: ["K", "1"], standard: "LS.K.1.1", skill: "Living and nonliving",
    target: "LIVING THINGS", prompt: "Deliver to LIVING things.",
    yes: ["DOG", "TREE", "CAT", "BIRD", "FROG", "FLOWER", "FISH", "BABY", "GRASS", "BEE"],
    no: ["ROCK", "BALL", "CAR", "CHAIR", "SPOON", "SHOE", "BOOK", "CUP", "KITE", "ROBOT"],
    yesWhy: "A {x} is alive: it grows, needs food and water, and makes more of its kind.",
    noWhy: "A {x} is not alive: it does not grow, eat or breathe.",
    notes: { ROBOT: "A robot can move, but it is not alive: it does not grow, eat or have babies." },
  },
  {
    id: "s-k-fly", subject: "science", grades: ["K"], standard: "LS.K.2.1", skill: "How animals move",
    target: "ANIMALS THAT FLY", prompt: "Deliver to ANIMALS THAT FLY.",
    yes: ["BIRD", "BEE", "BAT", "OWL", "DUCK", "EAGLE", "BUTTERFLY", "MOTH", "CROW", "PARROT"],
    no: ["DOG", "CAT", "FISH", "PIG", "COW", "SNAKE", "FROG", "HORSE", "PENGUIN", "TURTLE"],
    yesWhy: "A {x} can fly with its wings.", noWhy: "A {x} cannot fly.",
    notes: { PENGUIN: "A penguin is a bird, but it cannot fly. It uses its wings to swim!", BAT: "A bat is not a bird, but it flies with wings made of skin." },
  },
  {
    id: "s-k-soft", subject: "science", grades: ["K"], standard: "PS.K.1.1", skill: "Sorting by properties",
    target: "SOFT THINGS", prompt: "Deliver to SOFT things.",
    yes: ["PILLOW", "FEATHER", "COTTON", "SPONGE", "BLANKET", "YARN", "SOCK", "TISSUE", "TEDDY BEAR"],
    no: ["ROCK", "BRICK", "SPOON", "NAIL", "KEY", "SHELL", "COIN", "BLOCK", "PAN"],
    yesWhy: "A {x} is soft: it squishes when you press it.", noWhy: "A {x} is hard: it does not squish when you press it.",
  },
  // ---------------------------------------------------------------- 1
  {
    id: "s-1-plants", subject: "science", grades: ["1"], standard: "LS.1.1", skill: "Plants and their needs",
    target: "PLANTS", prompt: "Deliver to PLANTS. Plants make their own food from sunlight, water and air.",
    yes: ["OAK", "CACTUS", "FERN", "MOSS", "GRASS", "ROSE", "CORN", "TULIP", "IVY", "PINE"],
    no: ["DOG", "ANT", "FROG", "WORM", "SNAIL", "HAWK", "BEAR", "SPIDER", "RABBIT"],
    yesWhy: "A {x} is a plant: it makes its own food from sunlight, water and air.",
    noWhy: "A {x} is an animal: it must eat food to live.",
  },
  {
    id: "s-1-parts", subject: "science", grades: ["1"], standard: "LS.1.1", skill: "Plant parts",
    target: "PLANT PARTS", prompt: "Deliver to PLANT PARTS.",
    yes: ["ROOT", "STEM", "LEAF", "FLOWER", "SEED", "FRUIT", "PETAL", "BRANCH"],
    no: ["FUR", "WING", "BEAK", "TAIL", "CLAW", "FIN", "PAW", "FEATHER", "HOOF"],
    yesWhy: "A {x} is a part of a plant.", noWhy: "A {x} is an animal part.",
  },
  {
    id: "s-1-needs", subject: "science", grades: ["1", "2"], standard: "LS.1.2", skill: "Animal homes",
    target: "ANIMAL HOMES", prompt: "Deliver to ANIMAL HOMES: shelters animals live in.",
    yes: ["NEST", "DEN", "HIVE", "BURROW", "WEB", "CAVE", "ANTHILL", "TREE HOLE"],
    no: ["ACORN", "CHEESE", "HONEY", "BONE", "SEED", "WORM", "EGG", "CARROT"],
    yesWhy: "A {x} is a shelter where animals live and stay safe.",
    noWhy: "A {x} is not a home. Many animals eat it or use it, but they do not live in it.",
    notes: { EGG: "An egg is where a baby animal grows before it hatches, not a home animals live in." },
  },
  // ---------------------------------------------------------------- 2
  {
    id: "s-2-solids", subject: "science", grades: ["2", "3"], standard: "PS.2.1.1", skill: "Solids and liquids",
    target: "SOLIDS", prompt: "Deliver to SOLIDS: they keep their own shape.",
    yes: ["ROCK", "ICE", "WOOD", "COIN", "SPOON", "BRICK", "CRAYON", "NAIL", "BLOCK"],
    no: ["WATER", "MILK", "JUICE", "OIL", "HONEY", "SYRUP", "RAIN", "TEA", "VINEGAR"],
    yesWhy: "A {x} is a solid: it keeps its shape.", noWhy: "{x} is a liquid: it flows and takes the shape of its container.",
    notes: { ICE: "Ice is water that froze. As a solid, it keeps its shape.", HONEY: "Honey is thick and slow, but it still flows and fills its jar: it is a liquid." },
  },
  {
    id: "s-2-melt", subject: "science", grades: ["2"], standard: "PS.2.1.1", skill: "Heating and cooling",
    target: "MELTS ON A HOT DAY", prompt: "Deliver to things that MELT ON A HOT DAY.",
    yes: ["ICE", "BUTTER", "CHOCOLATE", "POPSICLE", "ICE CREAM", "SNOWMAN", "SNOW", "ICE CUBE"],
    no: ["ROCK", "WOOD", "SPOON", "BRICK", "PAPER", "SHELL", "SHOE", "SAND", "PENNY"],
    yesWhy: "{x} melts: heat from a hot day turns it from a solid into a liquid.",
    noWhy: "{x} stays solid on a hot day. It needs much more heat to melt, or it does not melt at all.",
  },
  {
    id: "s-2-eggs", subject: "science", grades: ["2"], standard: "LS.2.1", skill: "Animal life cycles",
    target: "HATCH FROM EGGS", prompt: "Deliver to animals that HATCH FROM EGGS.",
    yes: ["CHICKEN", "DUCK", "FROG", "TURTLE", "ROBIN", "ALLIGATOR", "BUTTERFLY", "OSTRICH", "PENGUIN"],
    no: ["DOG", "CAT", "COW", "HORSE", "BEAR", "WHALE", "PIG", "RABBIT", "GOAT"],
    yesWhy: "A {x} starts life inside an egg and hatches out.", noWhy: "A {x} is a mammal: its babies are born alive, not hatched from eggs.",
    notes: { BUTTERFLY: "A butterfly's life cycle starts as an egg. A caterpillar hatches out!", WHALE: "Whales live in water, but they are mammals: baby whales are born alive." },
  },
  // ---------------------------------------------------------------- 3
  {
    id: "s-3-gases", subject: "science", grades: ["3"], standard: "PS.3.1.2", skill: "States of matter",
    target: "GASES", prompt: "Deliver to GASES: they spread out to fill any space.",
    yes: ["STEAM", "OXYGEN", "HELIUM", "AIR", "NEON", "NITROGEN", "HYDROGEN", "CO[2]"],
    no: ["ICE", "WATER", "MILK", "ROCK", "SAND", "JUICE", "WOOD", "OIL", "IRON"],
    yesWhy: "{x} is a gas: it has no shape of its own and spreads out to fill its container.",
    noWhy: "{x} is not a gas: it is a solid or a liquid.",
    notes: { "CO[2]": "CO₂ is carbon dioxide, the gas you breathe out and that makes soda fizz.", STEAM: "Steam is water heated so much that it became a gas." },
  },
  {
    id: "s-3-bones", subject: "science", grades: ["3"], standard: "LS.3.1.1", skill: "Skeletal and muscular systems",
    target: "BONES", prompt: "Deliver to BONES of the human skeleton.",
    yes: ["SKULL", "RIB", "FEMUR", "SPINE", "PELVIS", "KNEECAP", "JAWBONE", "SHINBONE", "COLLARBONE"],
    no: ["HEART", "BICEPS", "LUNG", "STOMACH", "BRAIN", "SKIN", "TONGUE", "TRICEPS", "LIVER"],
    yesWhy: "The {x} is part of the skeleton, which holds up and protects the body.",
    noWhy: "The {x} is not a bone.",
    notes: { BICEPS: "The biceps is a muscle. Muscles pull on bones to move them.", TRICEPS: "The triceps is a muscle on the back of the arm. It straightens the elbow.", TONGUE: "The tongue is made of muscles, not bone.", SPINE: "The spine is a stack of small bones called vertebrae." },
  },
  {
    id: "s-3-vertebrates", subject: "science", grades: ["3", "4"], standard: "LS.3.1.1", skill: "Animals with backbones",
    target: "VERTEBRATES", prompt: "Deliver to VERTEBRATES: animals with a backbone.",
    yes: ["SHARK", "FROG", "SNAKE", "EAGLE", "HORSE", "TURTLE", "SALMON", "LIZARD", "WHALE", "BAT"],
    no: ["SPIDER", "WORM", "JELLYFISH", "OCTOPUS", "SNAIL", "CRAB", "ANT", "BEE", "SEA STAR", "CLAM"],
    yesWhy: "A {x} has a backbone, so it is a vertebrate.", noWhy: "A {x} has no backbone, so it is an invertebrate.",
    notes: { OCTOPUS: "An octopus is smart, but it has no bones at all: it is an invertebrate.", SHARK: "A shark's skeleton is cartilage, but it still has a backbone: it is a vertebrate.", "SEA STAR": "A sea star (starfish) is not a fish and has no backbone." },
  },
  // ---------------------------------------------------------------- 4
  {
    id: "s-4-conductors", subject: "science", grades: ["4"], standard: "PS.4.2", skill: "Conductors and insulators",
    target: "CONDUCTORS", prompt: "Deliver to electrical CONDUCTORS: electricity flows through them easily.",
    yes: ["COPPER", "SILVER", "GOLD", "ALUMINUM", "IRON", "STEEL", "SALT WATER", "GRAPHITE", "BRASS", "TIN"],
    no: ["RUBBER", "PLASTIC", "GLASS", "WOOD", "PAPER", "CERAMIC", "STYROFOAM", "WAX", "CORK", "WOOL"],
    yesWhy: "{x} is a conductor: electricity flows through it easily.", noWhy: "{x} is an insulator: it blocks electricity.",
    notes: { GRAPHITE: "Graphite (pencil 'lead') is not a metal, but it conducts electricity.", "SALT WATER": "Salt water conducts electricity because the dissolved salt makes charged particles that can move." },
  },
  {
    id: "s-4-magnetic", subject: "science", grades: ["4"], standard: "PS.4.1.1", skill: "Magnets",
    target: "MAGNETIC", prompt: "Deliver to things a MAGNET ATTRACTS.",
    yes: ["IRON", "STEEL", "COBALT", "IRON NAIL", "PAPERCLIP", "STAPLE", "MAGNETITE", "CAST IRON"],
    no: ["COPPER", "ALUMINUM", "GOLD", "PLASTIC", "WOOD", "GLASS", "RUBBER", "PAPER", "PENNY", "CORK"],
    yesWhy: "{x} contains iron or cobalt, so a magnet attracts it.", noWhy: "A magnet does not attract {x}.",
    notes: { ALUMINUM: "Aluminum is a metal, but magnets do not attract it.", COPPER: "Copper is a metal, but magnets do not attract it.", PENNY: "A penny is made of copper and zinc, which magnets do not attract.", MAGNETITE: "Magnetite is an iron mineral. It is a natural magnet!" },
  },
  {
    id: "s-4-minerals", subject: "science", grades: ["4"], standard: "ESS.4.2.1", skill: "Rocks and minerals",
    target: "MINERALS", prompt: "Deliver to MINERALS (not rocks). A rock is made of one or more minerals.",
    yes: ["QUARTZ", "FELDSPAR", "MICA", "CALCITE", "HALITE", "GYPSUM", "TALC", "DIAMOND", "PYRITE"],
    no: ["GRANITE", "BASALT", "MARBLE", "SANDSTONE", "LIMESTONE", "SHALE", "OBSIDIAN", "SLATE", "PUMICE"],
    yesWhy: "{x} is a mineral: a natural solid with the same makeup all the way through.",
    noWhy: "{x} is a rock: it is made of one or more minerals (or, like obsidian, natural glass).",
    notes: { GRANITE: "Granite is a rock made of the minerals quartz, feldspar and mica.", HALITE: "Halite is the mineral we call rock salt." },
  },
  // ---------------------------------------------------------------- 5
  {
    id: "s-5-producers", subject: "science", grades: ["5"], standard: "LS.5.2", skill: "Producers, consumers, decomposers",
    target: "PRODUCERS", prompt: "Deliver to PRODUCERS: living things that make their own food.",
    yes: ["GRASS", "OAK TREE", "ALGAE", "CACTUS", "CORN", "FERN", "MOSS", "KELP", "SUNFLOWER"],
    no: ["RABBIT", "HAWK", "DEER", "FOX", "MUSHROOM", "BEAR", "FROG", "MOUSE", "OWL", "EARTHWORM"],
    yesWhy: "{x} is a producer: it uses sunlight to make its own food.",
    noWhy: "{x} is not a producer: it gets energy by eating other living things or by breaking down dead ones.",
    notes: { MUSHROOM: "A mushroom is a fungus, a decomposer. It cannot make its own food from sunlight.", KELP: "Kelp is a giant seaweed (an alga). It makes food from sunlight like plants do.", EARTHWORM: "An earthworm is a decomposer: it eats dead leaves and waste." },
  },
  {
    id: "s-5-decomposers", subject: "science", grades: ["5"], standard: "LS.5.2.1", skill: "Decomposers",
    target: "DECOMPOSERS", prompt: "Deliver to DECOMPOSERS: they break down dead things and wastes.",
    yes: ["MUSHROOM", "MOLD", "BACTERIA", "FUNGI", "EARTHWORM", "PUFFBALL", "TOADSTOOL", "MILDEW"],
    no: ["GRASS", "RABBIT", "HAWK", "OAK TREE", "DEER", "ALGAE", "FROG", "SNAKE", "LION", "CORN"],
    yesWhy: "{x} is a decomposer: it breaks down dead plants and animals and returns nutrients to the soil.",
    noWhy: "{x} is not a decomposer: it is a producer or a consumer.",
  },
  {
    id: "s-5-inherited", subject: "science", grades: ["5"], standard: "LS.5.3", skill: "Inherited and acquired traits",
    target: "INHERITED TRAITS", prompt: "Deliver to INHERITED traits: passed down from parents.",
    yes: ["EYE COLOR", "CURLY HAIR", "DIMPLES", "BLOOD TYPE", "EAR SHAPE", "NOSE SHAPE", "FUR COLOR", "HAIR COLOR"],
    no: ["SCAR", "SUNTAN", "READING", "TATTOO", "BIKING", "SWIMMING", "HAIRCUT", "BROKEN ARM", "PIERCING"],
    yesWhy: "{x} is inherited: it comes from genes passed down from parents.",
    noWhy: "{x} is acquired: it comes from life, learning or the environment, not from parents' genes.",
  },
  // ---------------------------------------------------------------- 6
  {
    id: "s-6-insulators", subject: "science", grades: ["6"], standard: "PS.6.2.3", skill: "Thermal energy transfer",
    target: "HEAT INSULATORS", prompt: "Deliver to THERMAL INSULATORS: they slow the flow of heat.",
    yes: ["WOOL", "FOAM", "STYROFOAM", "AIR", "CORK", "WOOD", "FIBERGLASS", "FLEECE", "FEATHERS"],
    no: ["COPPER", "ALUMINUM", "IRON", "STEEL", "SILVER", "GOLD", "TIN", "METAL PAN", "BRASS"],
    yesWhy: "{x} is an insulator: heat moves through it slowly.", noWhy: "{x} is a metal, a good conductor: heat moves through it quickly.",
    notes: { AIR: "Trapped air is a great insulator. That is why foam, fleece and feathers keep you warm." },
  },
  {
    id: "s-6-abiotic", subject: "science", grades: ["6"], standard: "LS.6.2", skill: "Biotic and abiotic factors",
    target: "ABIOTIC", prompt: "Deliver to ABIOTIC factors: nonliving parts of an ecosystem.",
    yes: ["SUNLIGHT", "WATER", "ROCKS", "AIR", "WIND", "RAIN", "SAND", "SNOW", "SALT"],
    no: ["TREES", "GRASS", "FUNGI", "BIRDS", "INSECTS", "BACTERIA", "DEER", "ALGAE", "WORMS"],
    yesWhy: "{x} is abiotic: a nonliving part of the ecosystem.", noWhy: "{x} is biotic: a living part of the ecosystem.",
  },
  {
    id: "s-6-floats", subject: "science", grades: ["6"], standard: "PS.6.1.3", skill: "Density",
    target: "FLOATS IN WATER", prompt: "Deliver to things that FLOAT IN WATER (less dense than water).",
    yes: ["CORK", "ICE", "STYROFOAM", "APPLE", "OIL", "BALSA WOOD", "BEACH BALL", "LIFE VEST"],
    no: ["ROCK", "PENNY", "IRON NAIL", "MARBLE", "SAND", "KEY", "BRICK", "GOLD", "LEAD", "STEEL BALL"],
    yesWhy: "{x} floats: it is less dense than water.", noWhy: "{x} sinks: it is denser than water.",
    notes: { ICE: "Ice floats because water expands when it freezes, so ice is less dense than liquid water.", OIL: "Oil floats on top of water because it is less dense." },
  },
  {
    id: "s-6-tundra", subject: "science", grades: ["6"], standard: "LS.6.2", skill: "Biomes",
    target: "TUNDRA", prompt: "Deliver to things found in the TUNDRA biome.",
    yes: ["PERMAFROST", "LICHEN", "CARIBOU", "ARCTIC FOX", "MUSK OX", "LEMMING", "SNOWY OWL", "SNOW GOOSE"],
    no: ["CACTUS", "CAMEL", "JAGUAR", "TOUCAN", "SCORPION", "MONKEY", "PALM TREE", "ZEBRA", "IGUANA"],
    yesWhy: "{x} belongs in the tundra: a cold, treeless biome with frozen ground.",
    noWhy: "{x} lives in a warm biome (desert, savanna or rainforest), not the cold tundra.",
  },
  {
    id: "s-6-igneous", subject: "science", grades: ["6", "7"], standard: "ESS.6.2", skill: "Rock cycle",
    target: "IGNEOUS ROCKS", prompt: "Deliver to IGNEOUS rocks: formed when magma or lava cools.",
    yes: ROCKS_IGNEOUS,
    no: [...ROCKS_SEDIMENTARY.slice(0, 5), ...ROCKS_METAMORPHIC.slice(0, 5)],
    yesWhy: "{x} is igneous: it formed from cooled magma or lava.",
    noWhy: "{x} is not igneous: it is sedimentary (pressed layers) or metamorphic (changed by heat and pressure).",
  },
  // ---------------------------------------------------------------- 7
  {
    id: "s-7-eukaryotes", subject: "science", grades: ["7"], standard: "LS.7.1", skill: "Cells and single-celled organisms",
    target: "EUKARYOTES", prompt: "Deliver to EUKARYOTES: organisms whose cells have a nucleus.",
    yes: ["AMOEBA", "PARAMECIUM", "YEAST", "EUGLENA", "MUSHROOM", "OAK TREE", "HUMAN", "DIATOM", "MOLD", "FROG"],
    no: ["E. COLI", "SALMONELLA", "LISTERIA", "ARCHAEA", "STREP", "STAPH", "BACTERIA", "VIBRIO"],
    yesWhy: "{x} is a eukaryote: its cells have a nucleus.", noWhy: "{x} is a prokaryote: a single cell with no nucleus.",
    notes: { YEAST: "Yeast is a single-celled fungus, but its cell has a nucleus: it is a eukaryote.", AMOEBA: "An amoeba is one cell, but that cell has a nucleus, so it is a eukaryote." },
  },
  {
    id: "s-7-digestive", subject: "science", grades: ["7"], standard: "LS.7.1", skill: "Body systems",
    target: "DIGESTIVE SYSTEM", prompt: "Deliver to organs of the DIGESTIVE system.",
    yes: ["STOMACH", "LIVER", "ESOPHAGUS", "PANCREAS", "COLON", "MOUTH", "RECTUM", "DUODENUM"],
    no: ["HEART", "LUNGS", "KIDNEY", "BRAIN", "TRACHEA", "BLADDER", "SKIN", "ARTERY", "FEMUR"],
    yesWhy: "The {x} is part of the digestive system, which breaks down food.",
    noWhy: "The {x} belongs to another body system.",
    notes: { TRACHEA: "The trachea (windpipe) carries air to the lungs: it is part of the respiratory system. Food goes down the esophagus.", KIDNEY: "Kidneys filter blood and make urine: they are part of the excretory (urinary) system.", LIVER: "The liver makes bile, which helps digest fats." },
  },
  {
    id: "s-7-speed", subject: "science", grades: ["7"], standard: "PS.7.1", skill: "Speed and motion",
    target: "UNITS OF SPEED", prompt: "Deliver to UNITS OF SPEED: distance per time.",
    yes: ["m/s", "km/h", "mph", "ft/s", "cm/s", "knots", "km/s", "m/min"],
    no: ["kg", "meters", "seconds", "N", "J", "m/s{2}", "liters", "°C", "grams"],
    yesWhy: "{x} is a unit of speed: a distance divided by a time.", noWhy: "{x} is not a unit of speed.",
    notes: { "m/s{2}": "m/s² is a unit of acceleration (how fast speed changes), not speed.", N: "N (newton) is a unit of force.", J: "J (joule) is a unit of energy.", knots: "A knot is one nautical mile per hour: a speed unit used by ships and planes." },
  },
  // ---------------------------------------------------------------- 8
  {
    id: "s-8-elements", subject: "science", grades: ["8"], standard: "PS.8.1", skill: "Elements, compounds and mixtures",
    target: "ELEMENTS", prompt: "Deliver to ELEMENTS: pure substances made of one kind of atom.",
    yes: ["OXYGEN", "IRON", "GOLD", "CARBON", "HELIUM", "NEON", "SODIUM", "COPPER", "HYDROGEN", "SILVER"],
    no: ["WATER", "SALT", "SUGAR", "CO[2]", "RUST", "AMMONIA", "METHANE", "AIR", "BRASS", "STEEL"],
    yesWhy: "{x} is an element: it is made of only one kind of atom.",
    noWhy: "{x} is not an element: it contains more than one kind of atom.",
    notes: { AIR: "Air is a mixture of gases (mostly nitrogen and oxygen).", BRASS: "Brass is a mixture (alloy) of copper and zinc.", STEEL: "Steel is a mixture (alloy) of iron and carbon.", WATER: "Water (H₂O) is a compound of hydrogen and oxygen." },
  },
  {
    id: "s-8-compounds", subject: "science", grades: ["8"], standard: "PS.8.1", skill: "Elements, compounds and mixtures",
    target: "COMPOUNDS", prompt: "Deliver to COMPOUNDS: two or more elements chemically joined.",
    yes: ["WATER", "SALT", "SUGAR", "CO[2]", "H[2]O", "NaCl", "RUST", "AMMONIA", "METHANE", "GLUCOSE"],
    no: ["OXYGEN", "IRON", "GOLD", "HELIUM", "NEON", "AIR", "BRASS", "SAND+WATER", "COPPER", "TRAIL MIX"],
    yesWhy: "{x} is a compound: two or more elements chemically bonded in a fixed ratio.",
    noWhy: "{x} is not a compound: it is an element or a mixture.",
    notes: { AIR: "Air is a mixture: its gases are not chemically joined.", BRASS: "Brass is an alloy (a mixture) of copper and zinc.", "SAND+WATER": "Sand and water is a mixture: you can separate them by filtering." },
  },
  {
    id: "s-8-chemical", subject: "science", grades: ["8"], standard: "PS.8.1", skill: "Physical and chemical changes",
    target: "CHEMICAL CHANGES", prompt: "Deliver to CHEMICAL CHANGES: new substances form.",
    yes: ["RUSTING", "BURNING", "BAKING", "ROTTING", "TARNISHING", "FERMENTING", "TOASTING", "RIPENING"],
    no: ["MELTING", "FREEZING", "BOILING", "CUTTING", "TEARING", "DISSOLVING", "BENDING", "CRUSHING", "SHREDDING", "CONDENSING"],
    yesWhy: "{x} is a chemical change: a new substance forms.",
    noWhy: "{x} is a physical change: the substance is the same, only its shape, size or state changes.",
    notes: { DISSOLVING: "Dissolving sugar is physical: evaporate the water and the sugar is still there.", BOILING: "Boiling water makes steam, but steam is still H₂O: a physical change." },
  },
  {
    id: "s-8-renewable", subject: "science", grades: ["8", "9"], standard: "PS.8.2", skill: "Energy resources",
    target: "RENEWABLE", prompt: "Deliver to RENEWABLE energy resources: they are replaced naturally.",
    yes: ["SOLAR", "WIND", "HYDROPOWER", "GEOTHERMAL", "BIOMASS", "TIDAL", "WAVE", "BIOFUEL"],
    no: ["COAL", "OIL", "PETROLEUM", "URANIUM", "PROPANE", "GASOLINE", "DIESEL", "KEROSENE", "TAR SANDS"],
    yesWhy: "{x} is renewable: nature replaces it quickly.", noWhy: "{x} is nonrenewable: it took millions of years to form, or it is a mined fuel that runs out.",
    notes: { URANIUM: "Uranium powers nuclear plants without burning, but it is mined and runs out: nonrenewable." },
  },
  {
    id: "s-8-sedimentary", subject: "science", grades: ["8"], standard: "ESS.8.1", skill: "Rock layers",
    target: "SEDIMENTARY", prompt: "Deliver to SEDIMENTARY rocks: layers of sediment pressed and cemented.",
    yes: ROCKS_SEDIMENTARY,
    no: [...ROCKS_IGNEOUS.slice(0, 5), ...ROCKS_METAMORPHIC.slice(0, 5)],
    yesWhy: "{x} is sedimentary: bits of rock, shells or plants were laid down in layers and cemented.",
    noWhy: "{x} is not sedimentary: it is igneous (cooled magma) or metamorphic (changed by heat and pressure).",
    notes: { COAL: "Coal is sedimentary: it formed from layers of ancient plants." },
  },
  // ---------------------------------------------------------------- 9 (Earth & Environmental Science)
  {
    id: "s-9-metamorphic", subject: "science", grades: ["9"], standard: "ESS.EES.2", skill: "Rock cycle",
    target: "METAMORPHIC", prompt: "Deliver to METAMORPHIC rocks: changed by heat and pressure.",
    yes: ROCKS_METAMORPHIC,
    no: [...ROCKS_IGNEOUS.slice(0, 5), ...ROCKS_SEDIMENTARY.slice(0, 5)],
    yesWhy: "{x} is metamorphic: another rock was changed by heat and pressure without melting.",
    noWhy: "{x} is not metamorphic: it is igneous (cooled magma) or sedimentary (cemented layers).",
    notes: { MARBLE: "Marble is metamorphosed limestone.", SLATE: "Slate is metamorphosed shale.", QUARTZITE: "Quartzite is metamorphosed sandstone." },
  },
  {
    id: "s-9-greenhouse", subject: "science", grades: ["9"], standard: "ESS.EES.4", skill: "Atmosphere and climate",
    target: "GREENHOUSE GASES", prompt: "Deliver to GREENHOUSE GASES: they trap heat in the atmosphere.",
    yes: ["CO[2]", "METHANE", "N[2]O", "OZONE", "H[2]O VAPOR", "CFCs", "HFCs", "SF[6]"],
    no: ["OXYGEN", "NITROGEN", "ARGON", "HELIUM", "NEON", "KRYPTON", "XENON", "RADON"],
    yesWhy: "{x} is a greenhouse gas: it absorbs infrared (heat) radiation from Earth's surface.",
    noWhy: "{x} is not a greenhouse gas: it does not absorb Earth's infrared radiation in any important amount.",
    notes: { NITROGEN: "Nitrogen (N₂) is 78% of the air, but it barely absorbs infrared, so it is not a greenhouse gas.", OXYGEN: "Oxygen (O₂) is 21% of the air, but it barely absorbs infrared.", "H[2]O VAPOR": "Water vapor is the most abundant greenhouse gas." },
  },
  // ---------------------------------------------------------------- 10 (Biology)
  {
    id: "s-10-organelles", subject: "science", grades: ["10"], standard: "LS.Bio.1", skill: "Cell structure",
    target: "ORGANELLES", prompt: "Deliver to ORGANELLES: structures inside a cell.",
    yes: ["NUCLEUS", "RIBOSOME", "LYSOSOME", "VACUOLE", "GOLGI", "CENTRIOLE", "ROUGH ER", "PEROXISOME"],
    no: ["GLUCOSE", "PROTEIN", "LIPID", "ENZYME", "TISSUE", "ORGAN", "NEURON", "STARCH", "AMINO ACID"],
    yesWhy: "The {x} is an organelle, a structure with a job inside the cell.",
    noWhy: "{x} is not an organelle: it is a molecule, a whole cell, or a group of cells.",
    notes: { NEURON: "A neuron is a whole nerve cell, not a part inside a cell.", TISSUE: "A tissue is a group of cells working together.", ENZYME: "An enzyme is a protein molecule that speeds up reactions." },
  },
  {
    id: "s-10-prokaryotes", subject: "science", grades: ["10"], standard: "LS.Bio.1", skill: "Prokaryotes and eukaryotes",
    target: "PROKARYOTES", prompt: "Deliver to PROKARYOTES: cells with no nucleus.",
    yes: ["E. COLI", "SALMONELLA", "LISTERIA", "ARCHAEA", "STREP", "STAPH", "BACTERIA", "VIBRIO"],
    no: ["AMOEBA", "PARAMECIUM", "YEAST", "EUGLENA", "MUSHROOM", "OAK TREE", "HUMAN", "DIATOM", "MOLD"],
    yesWhy: "{x} is a prokaryote: no nucleus and no membrane-bound organelles.",
    noWhy: "{x} is a eukaryote: its cells have a nucleus.",
    notes: { ARCHAEA: "Archaea look like bacteria and have no nucleus: they are prokaryotes too." },
  },
  // ---------------------------------------------------------------- 11 (Chemistry)
  {
    id: "s-11-ionic", subject: "science", grades: ["11"], standard: "PS.Chm.3", skill: "Ionic and covalent bonds",
    target: "IONIC", prompt: "Deliver to IONIC compounds: a metal bonded to a nonmetal.",
    yes: ["NaCl", "KBr", "MgO", "CaCl[2]", "LiF", "NaF", "KCl", "CaO", "MgCl[2]", "Al[2]O[3]"],
    no: ["H[2]O", "CO[2]", "CH[4]", "NH[3]", "O[2]", "C[6]H[12]O[6]", "HCl", "N[2]", "SO[2]", "CCl[4]"],
    yesWhy: "{x} is ionic: a metal gives electrons to a nonmetal, forming ions.",
    noWhy: "{x} is covalent: nonmetal atoms share electrons.",
    notes: { HCl: "HCl (hydrogen chloride) is a molecule of two nonmetals sharing electrons: covalent (polar).", "O[2]": "O₂ is two oxygen atoms sharing electrons: a nonpolar covalent bond." },
  },
  {
    id: "s-11-metals", subject: "science", grades: ["11"], standard: "PS.Chm.2", skill: "Periodic table",
    target: "METALS", prompt: "Deliver to METALS on the periodic table.",
    yes: ["IRON", "COPPER", "SODIUM", "ZINC", "CALCIUM", "MERCURY", "TIN", "NICKEL", "LITHIUM", "MAGNESIUM"],
    no: ["OXYGEN", "SULFUR", "CARBON", "NITROGEN", "CHLORINE", "NEON", "IODINE", "PHOSPHORUS", "SELENIUM", "ARGON"],
    yesWhy: "{x} is a metal: it is on the left side of the staircase and tends to lose electrons.",
    noWhy: "{x} is a nonmetal: it is on the right side of the staircase.",
    notes: { MERCURY: "Mercury is a metal even though it is a liquid at room temperature.", SODIUM: "Sodium is a soft, very reactive alkali metal." },
  },
  // ---------------------------------------------------------------- 12 (Physics)
  {
    id: "s-12-longwave", subject: "science", grades: ["12"], standard: "PS.Phy.7", skill: "Electromagnetic spectrum",
    target: "LONGER THAN LIGHT", prompt: "Deliver to EM waves with LONGER wavelengths than visible light.",
    yes: ["RADIO", "MICROWAVE", "INFRARED", "FM RADIO", "AM RADIO", "RADAR", "WI-FI", "TV REMOTE"],
    no: ["UV", "UV-A", "UV-B", "UV-C", "X-RAYS", "GAMMA RAYS", "CT SCAN", "MAMMOGRAM"],
    yesWhy: "{x} has a longer wavelength (lower frequency) than visible light. Order: radio, microwave, infrared, visible.",
    noWhy: "{x} has a shorter wavelength (higher frequency) than visible light. Order: visible, UV, X-rays, gamma rays.",
    notes: { "TV REMOTE": "A TV remote sends infrared light, which is just longer than red light.", "WI-FI": "Wi-Fi uses microwaves (radio waves around 2.4 or 5 GHz).", "CT SCAN": "A CT scan uses X-rays.", MAMMOGRAM: "A mammogram is a low-dose X-ray image." },
  },
  {
    id: "s-12-mechanical", subject: "science", grades: ["12"], standard: "PS.Phy.7", skill: "Mechanical and EM waves",
    target: "MECHANICAL WAVES", prompt: "Deliver to MECHANICAL waves: they need a medium to travel.",
    yes: ["SOUND", "SEISMIC", "OCEAN WAVE", "ULTRASOUND", "SONAR", "ECHO", "P WAVE", "S WAVE"],
    no: ["RADIO", "MICROWAVE", "INFRARED", "LIGHT", "UV", "X-RAYS", "GAMMA RAYS", "RADAR"],
    yesWhy: "{x} is a mechanical wave: it needs matter (a medium) to travel through.",
    noWhy: "{x} is an electromagnetic wave: it can travel through empty space.",
    notes: { SONAR: "Sonar uses sound pulses in water: a mechanical wave.", RADAR: "Radar uses radio waves: electromagnetic, so it works even through a vacuum." },
  },
  {
    id: "s-12-contact", subject: "science", grades: ["12"], standard: "PS.Phy.2", skill: "Forces",
    target: "CONTACT FORCES", prompt: "Deliver to CONTACT forces: objects must touch.",
    yes: ["FRICTION", "TENSION", "NORMAL", "AIR DRAG", "SPRING", "APPLIED", "PUSH", "ROPE PULL"],
    no: ["GRAVITY", "MAGNETIC", "ELECTRIC", "WEIGHT", "NUCLEAR", "COULOMB", "SUN'S PULL", "WEAK FORCE"],
    yesWhy: "{x} is a contact force: it acts only where objects touch.",
    noWhy: "{x} is a field (non-contact) force: it acts at a distance.",
    notes: { WEIGHT: "Weight is the force of gravity on an object: a field force.", NORMAL: "The normal force is a surface pushing back on an object resting on it.", "AIR DRAG": "Air drag comes from air molecules hitting the object: a contact force." },
  },
  {
    id: "s-12-vectors", subject: "science", grades: ["12"], standard: "PS.Phy.1", skill: "Vectors and scalars",
    target: "VECTORS", prompt: "Deliver to VECTOR quantities: they have size AND direction.",
    yes: ["VELOCITY", "FORCE", "MOMENTUM", "WEIGHT", "IMPULSE", "TORQUE", "ACCEL.", "THRUST"],
    no: ["SPEED", "MASS", "TIME", "ENERGY", "DISTANCE", "POWER", "WORK", "VOLUME", "DENSITY"],
    yesWhy: "{x} is a vector: it has a size and a direction.", noWhy: "{x} is a scalar: it has only a size.",
    notes: { SPEED: "Speed is a scalar. Velocity (speed with a direction) is the vector.", DISTANCE: "Distance is a scalar. Displacement is the vector.", WORK: "Work is a scalar, even though it comes from force and displacement." },
  },
];
