import type { Question } from "../../types";
// Grade 8 social studies — NC Standard Course of Study for Social Studies (adopted 2021). North Carolina and United States history: conflict and cooperation from the colonial
// era to civil rights (8.H.1); location and movement (8.G.1.1, 8.G.1); democratic principles and constitutions (8.C&G.1.1, 8.C&G.1); economic growth and decline, farming and
// industry (8.E.1.1, 8.E.1); relationships among groups (8.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g8-01",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Regulators",
    prompt: "NC's Regulator Movement was backcountry farmers protesting...",
    choices: ["Unfair fees", "Free schools", "Railroads", "Low prices"],
    answer: 0,
    explanation: "Regulators protested corrupt officials, high fees and taxes. Governor Tryon defeated them at Alamance in 1771.",
    quick: true,
  },
  {
    id: "soc-g8-02",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Revolution in NC",
    prompt: "The 1781 Battle of Guilford Courthouse weakened the army of...",
    choices: ["Cornwallis", "Washington", "Lee", "Sherman"],
    answer: 0,
    explanation: "British General Cornwallis won the field but lost many men, helping lead to his surrender at Yorktown.",
    quick: true,
  },
  {
    id: "soc-g8-03",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Ratification",
    prompt: "NC delayed ratifying the Constitution until Congress proposed a...",
    choices: ["Bill of Rights", "King", "New capital", "Navy"],
    answer: 0,
    explanation: "NC refused to ratify the Constitution in 1788, then ratified it in November 1789 after amendments protecting rights were proposed.",
    quick: true,
  },
  {
    id: "soc-g8-04",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Constitution",
    prompt: "The first three words of the U.S. Constitution are...",
    choices: ["We the People", "All men are", "Four score and", "In God We"],
    answer: 0,
    explanation: "'We the People' shows that power comes from the people.",
    quick: true,
  },
  {
    id: "soc-g8-05",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Federalism",
    prompt: "Dividing power between national and state governments is...",
    choices: ["Federalism", "Monarchy", "Anarchy", "Tyranny"],
    answer: 0,
    explanation: "Under federalism, both national and state governments have their own powers.",
    quick: true,
  },
  {
    id: "soc-g8-06",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Sectional conflict",
    prompt: "The Missouri Compromise (1820) tried to settle disputes over...",
    choices: ["Slavery", "Tea", "Railroads", "Gold"],
    answer: 0,
    explanation: "The compromise admitted Missouri as a slave state and Maine as a free state, but tensions kept growing.",
    quick: true,
  },
  {
    id: "soc-g8-07",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil War",
    prompt: "North Carolina left the Union in May 1861 to join the...",
    choices: ["Confederacy", "British", "Mexico", "Union Army"],
    answer: 0,
    explanation: "NC seceded on May 20, 1861, after President Lincoln called for troops.",
    quick: true,
  },
  {
    id: "soc-g8-08",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Reconstruction",
    prompt: "The 13th Amendment (1865)...",
    choices: ["Ended slavery", "Women's vote", "Free speech", "Income tax"],
    answer: 0,
    explanation: "The 13th Amendment abolished slavery throughout the United States.",
    quick: true,
  },
  {
    id: "soc-g8-09",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Wilmington 1898",
    prompt: "In 1898, white supremacist mobs in Wilmington violently overthrew the city's...",
    choices: ["Government", "Governor", "King", "Railroad"],
    answer: 0,
    explanation: "The Wilmington coup forced out an elected, biracial city government and killed many Black residents. It helped bring Jim Crow laws and the loss of Black voting rights across NC.",
    quick: true,
  },
  {
    id: "soc-g8-10",
    subject: "social",
    grade: "8",
    standard: "8.E.1",
    skill: "Sharecropping",
    prompt: "After the Civil War, many landless NC farmers worked as...",
    choices: ["Sharecroppers", "Pilots", "Miners", "Sailors"],
    answer: 0,
    explanation: "Sharecroppers farmed someone else's land and paid with part of the crop, which often kept them in debt.",
    quick: true,
  },
  {
    id: "soc-g8-11",
    subject: "social",
    grade: "8",
    standard: "8.E.1",
    skill: "Industrialization",
    prompt: "In the late 1800s, NC's Piedmont grew with mills making textiles and...",
    choices: ["Cigarettes", "Cars", "Airplanes", "Computers"],
    answer: 0,
    explanation: "Textile mills and tobacco factories, like those of the Duke and Reynolds families, grew in the Piedmont.",
    quick: true,
  },
  {
    id: "soc-g8-12",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Modern NC",
    prompt: "Research Triangle Park (1959) is near Raleigh, Durham and...",
    choices: ["Chapel Hill", "Asheville", "Wilmington", "Boone"],
    answer: 0,
    explanation: "The park is anchored by NC State, Duke and UNC-Chapel Hill, and it drew research jobs to NC.",
    quick: true,
  },
  {
    id: "soc-g8-13",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil rights",
    prompt: "The 1960 student sit-ins led to what group being formed at Shaw University?",
    choices: ["SNCC", "NAACP", "UN", "NATO"],
    answer: 0,
    explanation: "Ella Baker helped students form the Student Nonviolent Coordinating Committee in Raleigh in April 1960.",
    quick: true,
  },
  {
    id: "soc-g8-14",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Location",
    prompt: "Why did NC develop few big seaports?",
    choices: ["Shallow inlets", "No rivers", "Too cold", "No trees"],
    answer: 0,
    explanation: "Barrier islands, shifting sandbars and shallow inlets made it hard for big ships to reach NC harbors.",
    quick: true,
  },
  {
    id: "soc-g8-15",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Desegregation",
    prompt: "Swann v. Charlotte-Mecklenburg (1971) upheld using busing to...",
    choices: ["Desegregate", "Build roads", "Raise taxes", "End elections"],
    answer: 0,
    explanation: "The Supreme Court ruled that busing could be used to integrate schools.",
    quick: true,
  },
  {
    id: "soc-g8-16",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Revolution in NC",
    passage:
      "On April 12, 1776, North Carolina's Provincial Congress met in Halifax. It told NC's delegates to the Continental Congress to vote with the other colonies for declaring independence from Britain.",
    prompt: "What principle do the Halifax Resolves show?",
    choices: ["Colonists had a right to independence", "The king should rule forever", "NC wanted to leave the other colonies", "Taxes should be raised"],
    answer: 0,
    explanation: "The Resolves supported independence, showing NC's move from protest to revolution.",
  },
  {
    id: "soc-g8-17",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Migration",
    passage:
      "From about 1910 to 1970, millions of Black Southerners, including many North Carolinians, moved to cities like New York, Philadelphia and Washington, D.C. This is called the Great Migration.",
    prompt: "Which was a push factor for these migrants?",
    choices: ["Jim Crow laws and few good jobs", "Cold winters in the North", "Free land in the West", "A gold rush in NC"],
    answer: 0,
    explanation: "Push factors drive people away from a place. Segregation, violence and low farm wages pushed people to leave.",
  },
  {
    id: "soc-g8-18",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Timelines",
    passage:
      "Timeline: 1789 NC ratifies the U.S. Constitution. 1795 UNC admits its first students. 1861 NC leaves the Union. 1903 The Wright brothers fly at Kitty Hawk.",
    prompt: "Which event happened first?",
    choices: ["NC ratifies Constitution", "UNC admits students", "NC leaves the Union", "Wright brothers fly"],
    answer: 0,
    explanation: "NC ratified the Constitution in 1789, six years before UNC, the first public university in the U.S. to admit students, opened in 1795.",
  },
  {
    id: "soc-g8-19",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Colonial NC",
    prompt: "In 1663, King Charles II granted Carolina to eight Lords...",
    choices: ["Proprietors", "Governors", "Generals", "Bishops"],
    answer: 0,
    explanation: "The Lords Proprietors owned Carolina until the king bought out most of them in 1729.",
    quick: true,
  },
  {
    id: "soc-g8-20",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Colonial NC",
    prompt: "The pirate Blackbeard was killed in 1718 near which NC island?",
    choices: ["Ocracoke", "Roanoke", "Bald Head", "Hatteras"],
    answer: 0,
    explanation: "Blackbeard (Edward Teach) died at Ocracoke Inlet fighting sailors sent by Virginia's governor.",
    quick: true,
  },
  {
    id: "soc-g8-21",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Revolution in NC",
    prompt: "Which signer of the Declaration of Independence represented NC?",
    choices: ["Joseph Hewes", "John Hancock", "John Adams", "Ben Franklin"],
    answer: 0,
    explanation: "NC's signers were Joseph Hewes, William Hooper and John Penn.",
    quick: true,
  },
  {
    id: "soc-g8-22",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Indian removal",
    prompt: "The Cherokee were forced west on the Trail of Tears mainly in...",
    choices: ["1838", "1776", "1865", "1898"],
    answer: 0,
    explanation: "Soldiers forced about 16,000 Cherokee west in 1838–39. Thousands died along the way.",
    quick: true,
  },
  {
    id: "soc-g8-23",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Indian removal",
    prompt: "In Worcester v. Georgia (1832), the Supreme Court sided with the...",
    choices: ["Cherokee", "Georgia", "U.S. Army", "Settlers"],
    answer: 0,
    explanation: "The Court said Georgia's laws had no force on Cherokee land, but President Jackson did not enforce the ruling.",
    quick: true,
  },
  {
    id: "soc-g8-24",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Sectional conflict",
    prompt: "The 1857 Dred Scott ruling said Congress could not ban slavery in the...",
    choices: ["Territories", "Navy", "Cities", "Courts"],
    answer: 0,
    explanation: "The ruling also said Black Americans could not be citizens. It deepened the divide before the Civil War.",
    quick: true,
  },
  {
    id: "soc-g8-25",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil War",
    prompt: "Zebulon ___ was NC's governor for most of the Civil War.",
    choices: ["Vance", "Holden", "Tryon", "Aycock"],
    answer: 0,
    explanation: "Vance was governor from 1862 to 1865 and often argued with the Confederate government over NC's rights.",
    quick: true,
  },
  {
    id: "soc-g8-26",
    subject: "social",
    grade: "8",
    standard: "8.B.1.1",
    skill: "Relationships among groups",
    prompt: "In 1958, Lumbee people near Maxton broke up a Ku Klux Klan rally at the Battle of...",
    choices: ["Hayes Pond", "Alamance", "Bentonville", "Moores Creek"],
    answer: 0,
    explanation: "Hundreds of Lumbee people surrounded the rally, and the Klan fled. The event drew national attention to the Lumbee stand against intimidation.",
    quick: true,
  },
  {
    id: "soc-g8-27",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Reconstruction",
    prompt: "During Reconstruction, which group used violence to stop Black citizens from voting?",
    choices: ["Ku Klux Klan", "Union League", "Red Cross", "Regulators"],
    answer: 0,
    explanation: "The Klan used threats and violence. Congress passed laws against it in 1870–71, and Governor Holden fought it in NC.",
    quick: true,
  },
  {
    id: "soc-g8-28",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Reconstruction",
    prompt: "The Freedmen's Bureau (1865) helped formerly enslaved people with...",
    choices: ["Schools", "Weapons", "Ships", "Taxes"],
    answer: 0,
    explanation: "The Bureau set up schools, gave out food and helped people sign fair work contracts.",
    quick: true,
  },
  {
    id: "soc-g8-29",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Progressive era",
    prompt: "Governor Charles Aycock (1901–1905) was known for building many...",
    choices: ["Schools", "Railroads", "Ports", "Prisons"],
    answer: 0,
    explanation: "Aycock promoted public schools, though Black schools got far less money. He also helped lead the campaign that took the vote from most Black men.",
    quick: true,
  },
  {
    id: "soc-g8-30",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Voting rights",
    prompt: "NC's 1900 literacy test and grandfather clause mostly kept whom from voting?",
    choices: ["Black men", "White men", "Veterans", "Landowners"],
    answer: 0,
    explanation: "The grandfather clause let many poor white men vote while the literacy test blocked most Black men.",
    quick: true,
  },
  {
    id: "soc-g8-31",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "World War II",
    prompt: "German submarines sank many ships off NC's coast in 1942. They were called...",
    choices: ["U-boats", "Zeppelins", "Tanks", "Biplanes"],
    answer: 0,
    explanation: "So many ships sank near Cape Hatteras that the area was nicknamed 'Torpedo Junction.'",
    quick: true,
  },
  {
    id: "soc-g8-32",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil rights",
    prompt: "The 1963 March on Washington is famous for which speech?",
    choices: ["I Have a Dream", "Four Freedoms", "Day of Infamy", "Cross of Gold"],
    answer: 0,
    explanation: "Dr. Martin Luther King Jr. gave his 'I Have a Dream' speech at the Lincoln Memorial.",
    quick: true,
  },
  {
    id: "soc-g8-33",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Timelines",
    passage:
      "A) NC secedes from the Union. B) NC adopts the Halifax Resolves. C) The Greensboro sit-ins begin. D) The Wilmington coup overthrows the city government.",
    prompt: "Which shows these events in the correct order?",
    choices: ["B, A, D, C", "A, B, C, D", "B, D, A, C", "D, B, A, C"],
    answer: 0,
    explanation: "The Halifax Resolves (1776) came first, then secession (1861), the Wilmington coup (1898) and the sit-ins (1960).",
  },
  {
    id: "soc-g8-34",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Migration and settlement",
    prompt: "The Great Wagon Road brought many settlers into NC's backcountry from...",
    choices: ["Pennsylvania", "Florida", "Texas", "Georgia"],
    answer: 0,
    explanation: "In the 1700s, Scots-Irish and German families moved south along the road into the Piedmont.",
    quick: true,
  },
  {
    id: "soc-g8-35",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Transportation",
    prompt: "When finished in 1840, the Wilmington & Weldon was the world's longest...",
    choices: ["Railroad", "Canal", "Bridge", "Highway"],
    answer: 0,
    explanation: "The 161-mile railroad linked Wilmington's port to Virginia's rail lines.",
    quick: true,
  },
  {
    id: "soc-g8-36",
    subject: "social",
    grade: "8",
    standard: "8.G.1",
    skill: "Location and industry",
    prompt: "Why did textile mills cluster in NC's Piedmont?",
    choices: ["Fast-flowing rivers could power the machines", "The Piedmont had the most beaches", "Mills needed salt water", "The mountains were too flat"],
    answer: 0,
    explanation: "Rivers dropping through the Piedmont turned water wheels, and cotton grew nearby.",
  },
  {
    id: "soc-g8-37",
    subject: "social",
    grade: "8",
    standard: "8.G.1",
    skill: "Population",
    prompt: "Today, NC's two largest metro areas, Charlotte and Raleigh, are in the...",
    choices: ["Piedmont", "Mountains", "Outer Banks", "Sandhills"],
    answer: 0,
    explanation: "Most of NC's population growth is in the Piedmont's big metro areas.",
    quick: true,
  },
  {
    id: "soc-g8-38",
    subject: "social",
    grade: "8",
    standard: "8.E.1.1",
    skill: "Economic decline",
    prompt: "During the Great Depression, many NC farmers struggled because crop prices...",
    choices: ["Fell", "Rose", "Doubled", "Froze"],
    answer: 0,
    explanation: "Tobacco and cotton prices dropped so low that many farmers could not pay their debts.",
    quick: true,
  },
  {
    id: "soc-g8-39",
    subject: "social",
    grade: "8",
    standard: "8.E.1.1",
    skill: "New Deal",
    prompt: "Which New Deal program put young men to work in parks and forests?",
    choices: ["CCC", "NATO", "FBI", "NASA"],
    answer: 0,
    explanation: "The Civilian Conservation Corps (1933) planted trees and built trails, including in NC's mountains.",
    quick: true,
  },
  {
    id: "soc-g8-40",
    subject: "social",
    grade: "8",
    standard: "8.E.1.1",
    skill: "Economic growth",
    prompt: "During World War II, NC's economy grew as the military built...",
    choices: ["Bases", "Casinos", "Malls", "Stadiums"],
    answer: 0,
    explanation: "Camp Lejeune, Fort Bragg and other bases brought jobs and people to NC.",
    quick: true,
  },
  {
    id: "soc-g8-41",
    subject: "social",
    grade: "8",
    standard: "8.E.1",
    skill: "New Deal",
    prompt: "The Blue Ridge Parkway, begun in 1935, was a New Deal project that boosted...",
    choices: ["Tourism", "Mining", "Whaling", "Cotton"],
    answer: 0,
    explanation: "The scenic road gave jobs during the Depression and still brings millions of visitors.",
    quick: true,
  },
  {
    id: "soc-g8-42",
    subject: "social",
    grade: "8",
    standard: "8.E.1.1",
    skill: "Economic change",
    passage:
      "Chart – Jobs in Millville, a made-up NC mill town: 1970: 3,000 mill jobs. 1990: 2,000 mill jobs. 2010: 300 mill jobs, plus 1,500 new jobs at a hospital and a community college.",
    prompt: "What best describes Millville's economy?",
    choices: ["It shifted from manufacturing to services", "It depended more on mills over time", "It lost all of its jobs", "It grew only because of mills"],
    answer: 0,
    explanation: "Mill jobs fell while health care and education jobs grew, like in many real NC towns.",
  },
  {
    id: "soc-g8-43",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1.1",
    skill: "Founding documents",
    prompt: "The Declaration says people have rights to life, liberty and the pursuit of...",
    choices: ["Happiness", "Property", "Wealth", "Land"],
    answer: 0,
    explanation: "Jefferson wrote 'Life, Liberty and the pursuit of Happiness.' Locke had written 'life, liberty and property.'",
    quick: true,
  },
  {
    id: "soc-g8-44",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1.1",
    skill: "NC constitutions",
    prompt: "North Carolina's first state constitution was adopted in...",
    choices: ["1776", "1789", "1868", "1971"],
    answer: 0,
    explanation: "NC adopted its first constitution at Halifax in December 1776. New ones followed in 1868 and 1971.",
    quick: true,
  },
  {
    id: "soc-g8-45",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "NC constitutions",
    prompt: "NC's 1868 constitution, written during Reconstruction, set up free public...",
    choices: ["Schools", "Railroads", "Churches", "Newspapers"],
    answer: 0,
    explanation: "The 1868 constitution required a system of free public schools and let all men vote regardless of property.",
    quick: true,
  },
  {
    id: "soc-g8-46",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Desegregation",
    prompt: "The 1954 Brown ruling said segregated public schools were...",
    choices: ["Unequal", "Fair", "Required", "Cheaper"],
    answer: 0,
    explanation: "Brown v. Board of Education said 'separate educational facilities are inherently unequal.'",
    quick: true,
  },
  {
    id: "soc-g8-47",
    subject: "social",
    grade: "8",
    standard: "8.B.1.1",
    skill: "Changing population",
    prompt: "In recent decades, NC's Hispanic and Latino population has...",
    choices: ["Grown quickly", "Disappeared", "Stayed tiny", "Moved away"],
    answer: 0,
    explanation: "NC's Hispanic population grew from under 100,000 in 1990 to over a million by 2020, adding to the state's cultures.",
    quick: true,
  },
  {
    id: "soc-g8-48",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Primary sources",
    passage:
      "From 'On Liberty and Slavery' by George Moses Horton (1829): 'Alas! and am I born for this, / To wear this slavish chain? / Deprived of all created bliss, / Through hardship, toil and pain!'",
    prompt: "What does Horton express in these lines?",
    choices: ["Sorrow and a longing for freedom", "Happiness with his life", "Praise for slavery", "A wish to sail to England"],
    answer: 0,
    explanation: "George Moses Horton, enslaved in Chatham County, was the first Black author to publish a book in the South (1829).",
  },
];

export default questions;
