import type { Question } from "../../types";
// Grade 3 science — NC Standard Course of Study for Science (2023). Air as matter, and properties and changes of solids,
// liquids and gases (PS.3.1); forces changing speed and direction, and comparing speeds (PS.3.2); the sun, solar system,
// shadows and star patterns (ESS.3.1); saltwater and freshwater features and land features (ESS.3.2); skeletal and
// muscular systems and skin (LS.3.1); plant structures and functions and the seed-plant life cycle (LS.3.2);
// environmental conditions, soil and plant growth (LS.3.3).
const questions: Question[] = [
  {
    id: "sci-g3-01",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Which state of matter keeps its own shape?",
    choices: ["Solid", "Liquid", "Gas", "Steam"],
    answer: 0,
    explanation: "A solid has a definite shape. Liquids take the shape of their container, and gases spread out to fill it.",
    quick: true,
  },
  {
    id: "sci-g3-02",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Juice poured into a bowl takes the shape of the...",
    choices: ["Bowl", "Tall glass", "Juice box", "Spoon"],
    answer: 0,
    explanation: "Liquids flow and take the shape of whatever container they are in, but the amount stays the same.",
    quick: true,
  },
  {
    id: "sci-g3-03",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Which state of matter spreads out to fill any container?",
    choices: ["Gas", "Solid", "Liquid", "Ice"],
    answer: 0,
    explanation: "A gas has no fixed shape or volume. It spreads out to fill all the space it is in, like air in a balloon.",
    quick: true,
  },
  {
    id: "sci-g3-04",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.3",
    skill: "Heating and cooling matter",
    prompt: "Boiling water long enough turns it into...",
    choices: ["Water vapor", "Ice", "Salt", "Sand"],
    answer: 0,
    explanation: "Heating liquid water makes it change into a gas called water vapor.",
    quick: true,
  },
  {
    id: "sci-g3-05",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.3",
    skill: "Heating and cooling matter",
    prompt: "A puddle dries up on a sunny day. Where did the water go?",
    choices: ["Into the air", "Into the sun", "It vanished", "Turned to salt"],
    answer: 0,
    explanation: "The sun's heat made the water evaporate. It became water vapor, an invisible gas in the air.",
    quick: true,
  },
  {
    id: "sci-g3-06",
    subject: "science",
    grade: "3",
    standard: "PS.3.2",
    skill: "Forces and motion",
    passage:
      "Two identical toy carts sit on a smooth floor. Jada gives Cart A a gentle push. Ben gives Cart B a much stronger push in the same direction.",
    prompt: "Which cart will speed up more, and why?",
    choices: [
      "Cart B, because a bigger force causes a bigger change in motion",
      "Cart A, because gentle pushes last longer",
      "Both the same, because the carts are identical",
      "Neither, because carts only move downhill",
    ],
    answer: 0,
    explanation: "When the mass is the same, a stronger push (force) makes a bigger change in speed.",
  },
  {
    id: "sci-g3-07",
    subject: "science",
    grade: "3",
    standard: "PS.3.2",
    skill: "Forces and motion",
    prompt: "Friction is a force that usually does what to moving things?",
    choices: ["Slows them", "Speeds them", "Lifts them", "Colors them"],
    answer: 0,
    explanation: "Friction happens when surfaces rub together. It works against motion and slows things down.",
    quick: true,
  },
  {
    id: "sci-g3-08",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.2",
    skill: "Soil and plant growth",
    passage:
      "Students poured 100 mL of water through three cups of soil. They measured how much water drained out the bottom. Sand: 80 mL. Loam: 50 mL. Clay: 20 mL.",
    prompt: "Which soil held on to the most water?",
    choices: ["Clay", "Sand", "Loam", "They all held the same"],
    answer: 0,
    explanation: "Only 20 mL drained from clay, so it kept 80 mL. Clay has tiny particles packed close together that hold water.",
  },
  {
    id: "sci-g3-09",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "The sun is a...",
    choices: ["Star", "Planet", "Moon", "Comet"],
    answer: 0,
    explanation: "The sun is a star. It looks bigger and brighter than other stars because it is so much closer to us.",
    quick: true,
  },
  {
    id: "sci-g3-10",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.2",
    skill: "Shadows and the sun",
    prompt: "When is your shadow the shortest?",
    choices: ["Around noon", "Early morning", "Late evening", "At sunrise"],
    answer: 0,
    explanation: "Around noon the sun is highest in the sky, so shadows are short. Low sun makes long shadows.",
    quick: true,
  },
  {
    id: "sci-g3-11",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.2",
    skill: "Shadows and the sun",
    passage:
      "Leo measured the flagpole's shadow three times in one day. At 8 a.m. it was long and pointed west. At noon it was short. At 4 p.m. it was long and pointed east.",
    prompt: "What best explains why the shadow changed?",
    choices: [
      "The sun's position in the sky changed during the day",
      "The flagpole grew taller and then shorter",
      "Clouds pushed the shadow around",
      "The ground turned under the flagpole in one day",
    ],
    answer: 0,
    explanation: "As Earth spins, the sun appears to move across the sky. Shadows point away from the sun, so they change length and direction.",
  },
  {
    id: "sci-g3-12",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "Which planet is closest to the sun?",
    choices: ["Mercury", "Earth", "Mars", "Neptune"],
    answer: 0,
    explanation: "Mercury is the closest planet to the sun. Neptune is the farthest.",
    quick: true,
  },
  {
    id: "sci-g3-13",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "What does Earth travel around once each year?",
    choices: ["The sun", "The moon", "Mars", "The stars"],
    answer: 0,
    explanation: "Earth orbits the sun. One trip around the sun takes about one year.",
    quick: true,
  },
  {
    id: "sci-g3-14",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.2",
    skill: "Land features",
    prompt: "Land with water all around it is called an...",
    choices: ["Island", "Valley", "Canyon", "Mountain"],
    answer: 0,
    explanation: "An island is land completely surrounded by water, like the Outer Banks islands of North Carolina.",
    quick: true,
  },
  {
    id: "sci-g3-15",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.2",
    skill: "Land features",
    prompt: "A deep, narrow valley with steep rock walls is a...",
    choices: ["Canyon", "Island", "Plain", "Beach"],
    answer: 0,
    explanation: "A canyon is a deep valley with steep sides, often carved by a river over a long time.",
    quick: true,
  },
  {
    id: "sci-g3-16",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.1",
    skill: "Bones and muscles",
    prompt: "Which bones protect your brain?",
    choices: ["Skull", "Ribs", "Kneecap", "Toe bones"],
    answer: 0,
    explanation: "Your skull is a hard case of bone that protects your brain. Your ribs protect your heart and lungs.",
    quick: true,
  },
  {
    id: "sci-g3-17",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.1",
    skill: "Bones and muscles",
    prompt: "How do muscles move your bones?",
    choices: ["By pulling", "By pushing", "By melting", "By glowing"],
    answer: 0,
    explanation: "Muscles can only pull. They work in pairs: one pulls to bend a joint, another pulls to straighten it.",
    quick: true,
  },
  {
    id: "sci-g3-18",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.2",
    skill: "Plant life cycles",
    prompt: "A bean plant's life cycle begins with a...",
    choices: ["Seed", "Flower", "Leaf", "Stem"],
    answer: 0,
    explanation: "A seed sprouts (germinates), grows into a plant, makes flowers, and the flowers make new seeds.",
    quick: true,
  },
  {
    id: "sci-g3-19",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Which part carries water from the roots to the leaves?",
    choices: ["Stem", "Petal", "Seed", "Flower"],
    answer: 0,
    explanation: "The stem has tiny tubes that carry water and nutrients from the roots up to the leaves.",
    quick: true,
  },
  {
    id: "sci-g3-20",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "What is the main job of a leaf?",
    choices: ["Make food", "Hold seeds", "Grip the soil", "Make pollen"],
    answer: 0,
    explanation: "Leaves use sunlight, water and air to make food (sugar) for the plant.",
    quick: true,
  },
  {
    id: "sci-g3-21",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Bright, sweet-smelling petals help a flower...",
    choices: ["Attract bees", "Store water", "Grow roots", "Block wind"],
    answer: 0,
    explanation: "Colorful petals and sweet smells attract bees and other pollinators.",
    quick: true,
  },
  {
    id: "sci-g3-22",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Pollen moving from flower to flower helps a plant make...",
    choices: ["Seeds", "Roots", "Leaves", "Bark"],
    answer: 0,
    explanation: "When pollen reaches another flower of the same kind, the flower can make seeds.",
    quick: true,
  },
  {
    id: "sci-g3-23",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "A seed coat protects the...",
    choices: ["Baby plant", "Flower", "Old leaves", "Soil"],
    answer: 0,
    explanation: "The tough seed coat protects the tiny baby plant (embryo) inside the seed.",
    quick: true,
  },
  {
    id: "sci-g3-24",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Before it grows leaves, a sprouting seed gets energy from...",
    choices: ["Stored food", "Sunlight", "Worms", "Rain"],
    answer: 0,
    explanation: "A seed holds stored food that feeds the young plant until its leaves can make food.",
    quick: true,
  },
  {
    id: "sci-g3-25",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Carrots and radishes are which plant part?",
    choices: ["Roots", "Stems", "Leaves", "Flowers"],
    answer: 0,
    explanation: "Carrots and radishes are roots that store food for the plant.",
    quick: true,
  },
  {
    id: "sci-g3-26",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    prompt: "Which part of a plant grows into a fruit?",
    choices: ["Flower", "Root", "Leaf", "Stem"],
    answer: 0,
    explanation: "After pollination, part of the flower swells and becomes the fruit that holds the seeds.",
    quick: true,
  },
  {
    id: "sci-g3-27",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.2",
    skill: "Seed-plant life cycle",
    prompt: "Seeds with tiny hooks that stick to fur are spread by...",
    choices: ["Animals", "Water", "Wind", "Fire"],
    answer: 0,
    explanation: "Hooked seeds catch on an animal's fur and fall off somewhere new.",
    quick: true,
  },
  {
    id: "sci-g3-28",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.2",
    skill: "Seed-plant life cycle",
    prompt: "When a seed starts to sprout, it is called...",
    choices: ["Germination", "Pollination", "Erosion", "Evaporation"],
    answer: 0,
    explanation: "Germination is when a seed takes in water and the young plant begins to grow.",
    quick: true,
  },
  {
    id: "sci-g3-29",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.2",
    skill: "Seed-plant life cycle",
    prompt: "What comes right after a seed sprouts?",
    choices: ["Seedling", "Fruit", "Flower", "Seed pod"],
    answer: 0,
    explanation: "A sprouted seed becomes a seedling, a young plant. Later it grows flowers, fruit and seeds.",
    quick: true,
  },
  {
    id: "sci-g3-30",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.1",
    skill: "Plants and their environment",
    prompt: "A plant gets too little water. It will...",
    choices: ["Wilt", "Bloom more", "Grow faster", "Turn purple"],
    answer: 0,
    explanation: "Without enough water, the plant's leaves and stem droop. This is called wilting.",
    quick: true,
  },
  {
    id: "sci-g3-31",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.2",
    skill: "Soil",
    prompt: "Which part of soil comes from rotted plants and animals?",
    choices: ["Humus", "Sand", "Clay", "Pebbles"],
    answer: 0,
    explanation: "Humus is the dark part of soil made from decayed plants and animals. It is full of nutrients.",
    quick: true,
  },
  {
    id: "sci-g3-32",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.2",
    skill: "Soil",
    prompt: "Which kind of soil has the biggest grains?",
    choices: ["Sand", "Clay", "Silt", "Humus"],
    answer: 0,
    explanation: "Sand grains are the biggest, then silt. Clay grains are the tiniest.",
    quick: true,
  },
  {
    id: "sci-g3-33",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.1",
    skill: "Air is matter",
    prompt: "A balloon gets bigger when you blow in because air...",
    choices: ["Takes up space", "Weighs nothing", "Is a solid", "Is a liquid"],
    answer: 0,
    explanation: "Air is matter, so it takes up space. More air inside pushes the balloon outward.",
    quick: true,
  },
  {
    id: "sci-g3-34",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.3",
    skill: "Star patterns",
    prompt: "A group of stars that seems to form a picture is a...",
    choices: ["Constellation", "Planet", "Comet", "Moon"],
    answer: 0,
    explanation: "Constellations are star patterns, like the Big Dipper and Orion.",
    quick: true,
  },
  {
    id: "sci-g3-35",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.3",
    skill: "Star patterns",
    prompt: "From year to year, the shape of the Big Dipper...",
    choices: ["Stays the same", "Changes a lot", "Disappears", "Doubles"],
    answer: 0,
    explanation: "Star patterns look the same year after year. People have used them as guides for thousands of years.",
    quick: true,
  },
  {
    id: "sci-g3-36",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "The sun looks bigger than other stars because it is...",
    choices: ["Closest to us", "The biggest", "The hottest", "The youngest"],
    answer: 0,
    explanation: "Many stars are bigger than the sun. The sun looks biggest because it is the closest star to Earth.",
    quick: true,
  },
  {
    id: "sci-g3-37",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.1",
    skill: "Water on Earth",
    prompt: "A glacier is a huge, slow-moving body of...",
    choices: ["Ice", "Sand", "Salt water", "Mud"],
    answer: 0,
    explanation: "Glaciers are giant sheets of ice. They hold much of Earth's fresh water.",
    quick: true,
  },
  {
    id: "sci-g3-38",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.2",
    skill: "Land features",
    prompt: "A high, flat landform with steep sides is a...",
    choices: ["Plateau", "Valley", "Canyon", "Island"],
    answer: 0,
    explanation: "A plateau is high like a mountain but flat on top.",
    quick: true,
  },
  {
    id: "sci-g3-39",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.2",
    skill: "Skin",
    prompt: "Which organ covers and protects your whole body?",
    choices: ["Skin", "Heart", "Lungs", "Stomach"],
    answer: 0,
    explanation: "Skin is your body's largest organ. It keeps germs out and holds water in.",
    quick: true,
  },
  {
    id: "sci-g3-40",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.1",
    skill: "Skeletal and muscular systems",
    prompt: "Your rib cage protects your...",
    choices: ["Heart, lungs", "Brain", "Knees", "Toes"],
    answer: 0,
    explanation: "Your ribs form a cage around your heart and lungs to protect them.",
    quick: true,
  },
  {
    id: "sci-g3-41",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.1",
    skill: "Plants and their environment",
    passage:
      "Two bean plants got the same amount of water. Plant A sat by a sunny window. Plant B sat in a dark closet. After two weeks, Plant B was pale and thin.",
    prompt: "Which explanation fits the results best?",
    choices: [
      "Plant B did not get enough light to make food",
      "Plant B got too much water",
      "Closets are too cold for every plant",
      "Plant B was a different kind of plant",
    ],
    answer: 0,
    explanation: "Both plants got the same water, so light was the difference. Without light, a plant cannot make the food it needs.",
  },
  {
    id: "sci-g3-42",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.1",
    skill: "Plant structures",
    passage:
      "Jon put a celery stalk in a cup of water with blue food coloring. The next day, the leaves at the top had blue lines in them.",
    prompt: "What does this show?",
    choices: [
      "The stem carries water up to the leaves",
      "Leaves make blue food",
      "Roots turn water blue",
      "Celery drinks water through its leaves",
    ],
    answer: 0,
    explanation: "The blue water traveled up tiny tubes in the stem and reached the leaves.",
  },
  {
    id: "sci-g3-43",
    subject: "science",
    grade: "3",
    standard: "PS.3.2.2",
    skill: "Comparing speeds",
    passage:
      "Three toy cars raced 10 meters. Red took 5 seconds. Blue took 8 seconds. Green took 4 seconds.",
    prompt: "Which car was the fastest?",
    choices: ["Green", "Red", "Blue", "They tied"],
    answer: 0,
    explanation: "All cars went the same distance. Green took the least time (4 seconds), so it was fastest.",
  },
  {
    id: "sci-g3-44",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.1",
    skill: "Air is matter",
    passage:
      "Ty weighed a flat ball: 400 grams. He pumped air into it and weighed it again: 410 grams.",
    prompt: "What does this show?",
    choices: ["Air has mass", "Air has no mass", "Pumps add metal to balls", "The ball got colder"],
    answer: 0,
    explanation: "The ball got heavier when only air was added, so air must have mass.",
  },
  {
    id: "sci-g3-45",
    subject: "science",
    grade: "3",
    standard: "LS.3.3.2",
    skill: "Soil",
    passage:
      "Kai filled three cups with sand, clay, and dark topsoil. He planted the same seeds and gave each cup the same water. The topsoil plants grew tallest.",
    prompt: "Why did the topsoil plants grow best?",
    choices: [
      "Topsoil has nutrients from decayed matter",
      "Topsoil has the biggest grains",
      "Topsoil holds no water",
      "Topsoil is mostly salt",
    ],
    answer: 0,
    explanation: "Topsoil is rich in humus, which gives plants nutrients. Sand and clay alone have fewer nutrients.",
  },
  {
    id: "sci-g3-46",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.3",
    skill: "Star patterns",
    passage:
      "At 8 p.m., Maya saw Orion low in the eastern sky. At 11 p.m., Orion was much higher in the sky.",
    prompt: "Why did Orion seem to move?",
    choices: ["Earth rotated", "Orion's stars moved", "The moon pushed it", "Clouds carried it"],
    answer: 0,
    explanation: "Earth spins, so stars seem to rise in the east and move across the sky, just like the sun.",
  },
  {
    id: "sci-g3-47",
    subject: "science",
    grade: "3",
    standard: "PS.3.2.1",
    skill: "Forces and motion",
    passage:
      "A ball is rolling east across a gym floor. Ana kicks it from the side, toward the north.",
    prompt: "What happens to the ball?",
    choices: ["It changes direction", "It keeps the same path", "It stops forever", "It gets heavier"],
    answer: 0,
    explanation: "A push from the side changes the direction the ball moves.",
  },
  {
    id: "sci-g3-48",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.1",
    skill: "Water on Earth",
    prompt: "Which list has only freshwater features?",
    choices: ["Lake, river, pond", "Ocean, sea, bay", "River, ocean, pond", "Sea, lake, gulf"],
    answer: 0,
    explanation: "Lakes, rivers and ponds hold fresh water. Oceans, seas, bays and gulfs hold salt water.",
  },
];
export default questions;
