import type { Question } from "../../types";
// Grade 7 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Modern world, 1400 to present: turning points (7.H.1.1), the impact of diverse groups
// (7.H.1.2) and 20th-century conflicts (7.H.1); revolutions, religion and changing governments (7.C&G.1.1, 7.C&G.1.2, 7.C&G.1); economic systems and the Columbian Exchange
// (7.E.1.1, 7.E.1); migration, globalization and cities (7.G.1.1, 7.G.1); elements of culture (7.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g7-01",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Turning points",
    prompt: "Movable-type printing in Europe was developed around 1440 by...",
    choices: ["Gutenberg", "Columbus", "Napoleon", "Galileo"],
    answer: 0,
    explanation: "Gutenberg's press made books faster and cheaper, spreading ideas widely.",
    quick: true,
  },
  {
    id: "soc-g7-02",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Turning points",
    prompt: "Columbus's 1492 voyage began lasting contact between Europe and...",
    choices: ["The Americas", "China", "Australia", "Antarctica"],
    answer: 0,
    explanation: "After 1492, contact between Europe, Africa and the Americas changed life on every continent.",
    quick: true,
  },
  {
    id: "soc-g7-03",
    subject: "social",
    grade: "7",
    standard: "7.E.1",
    skill: "Columbian Exchange",
    prompt: "Which crop went from the Americas to Europe in the Columbian Exchange?",
    choices: ["Potatoes", "Wheat", "Sugarcane", "Rice"],
    answer: 0,
    explanation: "Potatoes, corn and tomatoes came from the Americas. Wheat, sugarcane and rice went the other way.",
    quick: true,
  },
  {
    id: "soc-g7-04",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Industrial Revolution",
    prompt: "The Industrial Revolution began in the 1700s in...",
    choices: ["Great Britain", "Japan", "Brazil", "Egypt"],
    answer: 0,
    explanation: "Coal, iron, capital and inventions like the steam engine helped Britain industrialize first.",
    quick: true,
  },
  {
    id: "soc-g7-05",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "The French Revolution began in...",
    choices: ["1789", "1492", "1917", "1945"],
    answer: 0,
    explanation: "In 1789 French people rose against the king's absolute power and demanded rights.",
    quick: true,
  },
  {
    id: "soc-g7-06",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "The 1917 Russian Revolution led to a government run by...",
    choices: ["Communists", "Pharaohs", "Samurai", "Vikings"],
    answer: 0,
    explanation: "The Bolsheviks, led by Lenin, took power and later formed the Soviet Union.",
    quick: true,
  },
  {
    id: "soc-g7-07",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "World War I began in...",
    choices: ["1914", "1939", "1861", "1776"],
    answer: 0,
    explanation: "World War I lasted from 1914 to 1918.",
    quick: true,
  },
  {
    id: "soc-g7-08",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "World War II ended in...",
    choices: ["1945", "1918", "1965", "1939"],
    answer: 0,
    explanation: "World War II lasted from 1939 to 1945.",
    quick: true,
  },
  {
    id: "soc-g7-09",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "Nazi Germany's murder of about six million Jews is called the...",
    choices: ["Holocaust", "Cold War", "Crusades", "Renaissance"],
    answer: 0,
    explanation: "The Holocaust was the state-sponsored murder of six million Jews and millions of others by Nazi Germany.",
    quick: true,
  },
  {
    id: "soc-g7-10",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1",
    skill: "Changing governments",
    prompt: "Nelson Mandela became South Africa's president in 1994 after the end of...",
    choices: ["Apartheid", "The Crusades", "World War I", "Renaissance"],
    answer: 0,
    explanation: "Apartheid was a system of racial segregation. Mandela became the first president elected in a fully democratic vote.",
    quick: true,
  },
  {
    id: "soc-g7-11",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1",
    skill: "International cooperation",
    prompt: "Which group formed in 1945 to promote world peace?",
    choices: ["United Nations", "NASA", "FIFA", "The Olympics"],
    answer: 0,
    explanation: "The United Nations was founded after World War II to prevent future wars.",
    quick: true,
  },
  {
    id: "soc-g7-12",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Cold War",
    prompt: "The Cold War was a rivalry between the U.S. and the...",
    choices: ["Soviet Union", "United Kingdom", "Mexico", "Canada"],
    answer: 0,
    explanation: "From about 1947 to 1991, the U.S. and Soviet Union competed without fighting a direct war.",
    quick: true,
  },
  {
    id: "soc-g7-13",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Cold War",
    prompt: "The Berlin Wall fell in...",
    choices: ["1989", "1945", "1961", "2001"],
    answer: 0,
    explanation: "The wall went up in 1961 and fell in 1989. Germany reunified in 1990.",
    quick: true,
  },
  {
    id: "soc-g7-14",
    subject: "social",
    grade: "7",
    standard: "7.E.1",
    skill: "Market economies",
    prompt: "In a market economy, prices are mostly set by...",
    choices: ["Supply/demand", "One ruler", "A lottery", "The weather"],
    answer: 0,
    explanation: "Buyers and sellers, through supply and demand, set most prices in a market economy.",
    quick: true,
  },
  {
    id: "soc-g7-15",
    subject: "social",
    grade: "7",
    standard: "7.B.1.1",
    skill: "Culture",
    prompt: "Which is an element of culture?",
    choices: ["Language", "Latitude", "Elevation", "Rainfall"],
    answer: 0,
    explanation: "Culture includes language, religion, food, arts and customs. Latitude and rainfall are physical geography.",
    quick: true,
  },
  {
    id: "soc-g7-16",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Globalization",
    prompt: "Globalization means countries are becoming more...",
    choices: ["Connected", "Isolated", "Frozen", "Empty"],
    answer: 0,
    explanation: "Trade, travel and the internet link people and economies around the world.",
    quick: true,
  },
  {
    id: "soc-g7-17",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Nonviolent resistance",
    passage:
      "In 1930, Mohandas Gandhi and his followers walked about 240 miles to the sea to make their own salt, breaking a British law that taxed salt. Thousands were later arrested, and they did not fight back.",
    prompt: "Which method does this passage describe?",
    choices: ["Nonviolent protest", "Armed revolt", "Trade embargo", "Royal decree"],
    answer: 0,
    explanation: "Gandhi led the Salt March to resist British rule without violence.",
  },
  {
    id: "soc-g7-18",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Urbanization",
    passage:
      "Manchester, England, had about 25,000 people in the 1770s. After cotton mills opened, it grew to over 300,000 by the 1850s.",
    prompt: "What best explains the change in Manchester's population?",
    choices: ["People moved from farms to work in factories", "Farming became more popular", "People left cities for the countryside", "A war destroyed nearby towns"],
    answer: 0,
    explanation: "The Industrial Revolution drew workers to factory cities, a trend called urbanization.",
  },
  {
    id: "soc-g7-19",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Encounters",
    prompt: "Spanish conquistadors led by Hernán Cortés defeated the ___ Empire.",
    choices: ["Aztec", "Inca", "Maya", "Mali"],
    answer: 0,
    explanation: "Cortés and his Indigenous allies conquered the Aztec capital, Tenochtitlan, in 1521. Disease also killed many Aztecs.",
    quick: true,
  },
  {
    id: "soc-g7-20",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Turning points",
    prompt: "In 1453, the Ottoman Turks captured...",
    choices: ["Constantinople", "Rome", "Paris", "Cairo"],
    answer: 0,
    explanation: "The fall of Constantinople ended the Byzantine Empire. The city became the Ottoman capital, Istanbul.",
    quick: true,
  },
  {
    id: "soc-g7-21",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Exploration",
    prompt: "Who sailed around Africa to reach India in 1498?",
    choices: ["Vasco da Gama", "Columbus", "Magellan", "Cortés"],
    answer: 0,
    explanation: "Da Gama's voyage opened a sea route from Europe to Asia's spice trade.",
    quick: true,
  },
  {
    id: "soc-g7-22",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Exploration",
    prompt: "The first voyage around the world (1519–1522) was led at first by...",
    choices: ["Magellan", "Columbus", "Drake", "Cook"],
    answer: 0,
    explanation: "Magellan died in the Philippines. Juan Sebastián Elcano led the last ship home.",
    quick: true,
  },
  {
    id: "soc-g7-23",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Scientific Revolution",
    prompt: "In 1543, who published the idea that Earth orbits the sun?",
    choices: ["Copernicus", "Ptolemy", "Aristotle", "Newton"],
    answer: 0,
    explanation: "Copernicus challenged the old idea that Earth was the center of the universe.",
    quick: true,
  },
  {
    id: "soc-g7-24",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Modernization",
    prompt: "Japan began to modernize quickly with the ___ Restoration of 1868.",
    choices: ["Meiji", "Tokugawa", "Ming", "Qing"],
    answer: 0,
    explanation: "Meiji leaders built railroads, factories and a modern army.",
    quick: true,
  },
  {
    id: "soc-g7-25",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World War I",
    prompt: "In 1914, Archduke Franz Ferdinand was assassinated in...",
    choices: ["Sarajevo", "Berlin", "Paris", "London"],
    answer: 0,
    explanation: "His murder in Sarajevo set off a chain of alliances that started World War I.",
    quick: true,
  },
  {
    id: "soc-g7-26",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World War I",
    prompt: "The 1919 treaty that ended WWI with Germany was the Treaty of...",
    choices: ["Versailles", "Ghent", "Tordesillas", "Utrecht"],
    answer: 0,
    explanation: "The Treaty of Versailles blamed Germany and made it pay reparations, causing anger that later helped the Nazis rise.",
    quick: true,
  },
  {
    id: "soc-g7-27",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World War II",
    prompt: "Atomic bombs were dropped on Hiroshima and Nagasaki in...",
    choices: ["1945", "1918", "1939", "1962"],
    answer: 0,
    explanation: "The U.S. dropped the bombs in August 1945, and Japan surrendered weeks later.",
    quick: true,
  },
  {
    id: "soc-g7-28",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Cold War",
    prompt: "The Soviet Union launched the first satellite in 1957, called...",
    choices: ["Sputnik", "Apollo", "Hubble", "Voyager"],
    answer: 0,
    explanation: "Sputnik started the space race between the U.S. and the Soviet Union.",
    quick: true,
  },
  {
    id: "soc-g7-29",
    subject: "social",
    grade: "7",
    standard: "7.H.1.2",
    skill: "Changemakers",
    prompt: "Malala Yousafzai is known for speaking up for girls'...",
    choices: ["Education", "Sports", "Fashion", "Music"],
    answer: 0,
    explanation: "Malala survived an attack for supporting girls' schooling in Pakistan and won the Nobel Peace Prize in 2014.",
    quick: true,
  },
  {
    id: "soc-g7-30",
    subject: "social",
    grade: "7",
    standard: "7.H.1.2",
    skill: "Independence movements",
    prompt: "Who led Ghana to independence from Britain in 1957?",
    choices: ["Kwame Nkrumah", "Jomo Kenyatta", "Nelson Mandela", "Haile Selassie"],
    answer: 0,
    explanation: "Ghana was one of the first African colonies to win independence after World War II, inspiring others across Africa.",
    quick: true,
  },
  {
    id: "soc-g7-31",
    subject: "social",
    grade: "7",
    standard: "7.H.1.2",
    skill: "Changemakers",
    prompt: "Women in Britain who campaigned for the vote were called...",
    choices: ["Suffragettes", "Loyalists", "Puritans", "Cossacks"],
    answer: 0,
    explanation: "British women won partial voting rights in 1918 and equal voting rights in 1928.",
    quick: true,
  },
  {
    id: "soc-g7-32",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "Napoleon Bonaparte crowned himself emperor of...",
    choices: ["France", "Spain", "Russia", "Italy"],
    answer: 0,
    explanation: "Napoleon rose to power after the French Revolution and crowned himself emperor in 1804.",
    quick: true,
  },
  {
    id: "soc-g7-33",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "Simón Bolívar helped lead independence movements in...",
    choices: ["South America", "Africa", "Asia", "Europe"],
    answer: 0,
    explanation: "Bolívar helped free Venezuela, Colombia, Ecuador, Peru and Bolivia from Spanish rule.",
    quick: true,
  },
  {
    id: "soc-g7-34",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "The 1949 communist revolution in China was led by...",
    choices: ["Mao Zedong", "Sun Yat-sen", "Deng Xiaoping", "Kim Il-sung"],
    answer: 0,
    explanation: "Mao's Communist Party won China's civil war and founded the People's Republic of China.",
    quick: true,
  },
  {
    id: "soc-g7-35",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.2",
    skill: "Religion and government",
    prompt: "Martin Luther's protests led to new ___ churches.",
    choices: ["Protestant", "Catholic", "Orthodox", "Buddhist"],
    answer: 0,
    explanation: "The Reformation split Western Christianity, and rulers began choosing their states' religion.",
    quick: true,
  },
  {
    id: "soc-g7-36",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.2",
    skill: "Enlightenment",
    prompt: "Enlightenment thinkers argued government power should come from...",
    choices: ["The people", "The church", "Kings", "Armies"],
    answer: 0,
    explanation: "Thinkers like Locke and Rousseau said governments get their power from the consent of the people.",
    quick: true,
  },
  {
    id: "soc-g7-37",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.2",
    skill: "Religion and government",
    passage:
      "Declaration of the Rights of Man and of the Citizen (France, 1789), Article 10: 'No one shall be disquieted on account of his opinions, including his religious views, provided their manifestation does not disturb the public order established by law.'",
    prompt: "Which change does Article 10 support?",
    choices: ["Freedom of religious belief", "A state church everyone must join", "Rule by a king chosen by God", "Banning all religion"],
    answer: 0,
    explanation: "The French declaration protected people's right to hold their own opinions, including religious beliefs.",
  },
  {
    id: "soc-g7-38",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1",
    skill: "International cooperation",
    prompt: "Many European Union members share a common currency, the...",
    choices: ["Euro", "Dollar", "Peso", "Yen"],
    answer: 0,
    explanation: "The euro is used by many EU countries, which makes trade and travel easier.",
    quick: true,
  },
  {
    id: "soc-g7-39",
    subject: "social",
    grade: "7",
    standard: "7.G.1.1",
    skill: "Migration",
    prompt: "Millions of Africans carried across the Atlantic in the slave trade were part of a ___ migration.",
    choices: ["Forced", "Voluntary", "Seasonal", "Internal"],
    answer: 0,
    explanation: "Forced migration means people are moved against their will. The slave trade was a huge forced migration.",
    quick: true,
  },
  {
    id: "soc-g7-40",
    subject: "social",
    grade: "7",
    standard: "7.G.1.1",
    skill: "Migration",
    prompt: "In 1947, the partition of British India created India and...",
    choices: ["Pakistan", "Bangladesh", "Nepal", "Sri Lanka"],
    answer: 0,
    explanation: "Partition caused one of the largest migrations in history. Bangladesh was East Pakistan until 1971.",
    quick: true,
  },
  {
    id: "soc-g7-41",
    subject: "social",
    grade: "7",
    standard: "7.G.1.1",
    skill: "Migration",
    passage:
      "Starting in 2011, a civil war in Syria forced millions of people to flee their homes. Many crossed into Turkey, Lebanon and Jordan, and others traveled on to Europe.",
    prompt: "Which term best describes these people?",
    choices: ["Refugees", "Tourists", "Colonists", "Nomads"],
    answer: 0,
    explanation: "Refugees are people forced to flee their country because of war or danger.",
  },
  {
    id: "soc-g7-42",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Movement",
    prompt: "The Panama Canal, opened in 1914, links the Atlantic and...",
    choices: ["Pacific", "Indian", "Arctic", "Red Sea"],
    answer: 0,
    explanation: "Ships no longer had to sail around South America.",
    quick: true,
  },
  {
    id: "soc-g7-43",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Urbanization",
    passage:
      "Chart – Share of the world's people living in cities (estimates): 1800: about 7%. 1900: about 16%. 1950: about 30%. 2020: about 56%.",
    prompt: "What trend does the chart show?",
    choices: ["A growing share of people live in cities", "Cities shrank after 1900", "Most people lived in cities in 1800", "The share stayed about the same"],
    answer: 0,
    explanation: "Industry and better farming moved people into cities. Today more than half of all people live in urban areas.",
  },
  {
    id: "soc-g7-44",
    subject: "social",
    grade: "7",
    standard: "7.E.1.1",
    skill: "Economic systems",
    prompt: "An economy where the government makes most decisions is a ___ economy.",
    choices: ["Command", "Market", "Traditional", "Barter"],
    answer: 0,
    explanation: "In a command economy, the government decides what to make and what prices to charge.",
    quick: true,
  },
  {
    id: "soc-g7-45",
    subject: "social",
    grade: "7",
    standard: "7.E.1.1",
    skill: "Economic systems",
    prompt: "Adam Smith's 1776 book argued for...",
    choices: ["Free markets", "Communism", "Feudalism", "Mercantilism"],
    answer: 0,
    explanation: "In The Wealth of Nations, Smith said competition and trade, not government control, create wealth.",
    quick: true,
  },
  {
    id: "soc-g7-46",
    subject: "social",
    grade: "7",
    standard: "7.E.1",
    skill: "Economic systems",
    prompt: "Karl Marx's ideas inspired...",
    choices: ["Communism", "Capitalism", "Feudalism", "Mercantilism"],
    answer: 0,
    explanation: "Marx criticized capitalism and called for workers to own the means of production.",
    quick: true,
  },
  {
    id: "soc-g7-47",
    subject: "social",
    grade: "7",
    standard: "7.B.1.1",
    skill: "Culture",
    prompt: "The Taj Mahal was built by a Mughal emperor in...",
    choices: ["India", "Egypt", "China", "Turkey"],
    answer: 0,
    explanation: "Shah Jahan built the Taj Mahal in the 1600s as a tomb for his wife.",
    quick: true,
  },
  {
    id: "soc-g7-48",
    subject: "social",
    grade: "7",
    standard: "7.B.1.1",
    skill: "Culture",
    prompt: "A Japanese haiku is a type of...",
    choices: ["Poetry", "Dance", "Food", "Clothing"],
    answer: 0,
    explanation: "A haiku is a short poem, often with lines of 5, 7 and 5 syllables.",
    quick: true,
  },
];

export default questions;
