import type { Question } from "../../types";

// Grade 12 ELA — NC Standard Course of Study for ELA (2017). English IV (11-12 band): RL.11-12.1, RL.11-12.2, RL.11-12.3, RL.11-12.4, RL.11-12.5, RL.11-12.6, RL.11-12.9, RI.11-12.2, RI.11-12.5, RI.11-12.6, RI.11-12.8, RI.11-12.9, W.11-12.1, L.11-12.1, L.11-12.2, L.11-12.3, L.11-12.4, L.11-12.5
const questions: Question[] = [
  {
    id: "ela-g12-01",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'All hands on deck' uses a part to stand for the whole. This is...",
    choices: ["synecdoche", "simile", "litotes", "euphemism"],
    answer: 0,
    explanation: "Synecdoche uses a part (hands) to represent the whole (sailors).",
    quick: true,
  },
  {
    id: "ela-g12-02",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "Speaking directly to an absent person or thing, as in 'O Moon!', is...",
    choices: ["apostrophe", "allusion", "ellipsis", "anaphora"],
    answer: 0,
    explanation: "As a figure of speech, apostrophe addresses someone absent or something not human.",
    quick: true,
  },
  {
    id: "ela-g12-03",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Tragedy",
    prompt: "A tragic hero's fatal flaw or error is called...",
    choices: ["hamartia", "catharsis", "denouement", "epiphany"],
    answer: 0,
    explanation: "Hamartia is the flaw or mistake that leads to the tragic hero's downfall.",
    quick: true,
  },
  {
    id: "ela-g12-04",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Tragedy",
    prompt: "The emotional release an audience feels after a tragedy is...",
    choices: ["catharsis", "hamartia", "exposition", "peripeteia"],
    answer: 0,
    explanation: "Aristotle called this purging of pity and fear catharsis.",
    quick: true,
  },
  {
    id: "ela-g12-05",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Poetic forms",
    prompt: "A 14-line poem written in iambic pentameter is a...",
    choices: ["sonnet", "haiku", "limerick", "ballad"],
    answer: 0,
    explanation: "Sonnets have 14 lines, usually in iambic pentameter, with set rhyme schemes.",
    quick: true,
  },
  {
    id: "ela-g12-06",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Poetic forms",
    prompt: "Unrhymed lines written in iambic pentameter are called...",
    choices: ["blank verse", "free verse", "a sonnet", "a couplet"],
    answer: 0,
    explanation: "Blank verse has regular meter but no rhyme. Free verse has neither.",
    quick: true,
  },
  {
    id: "ela-g12-07",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.6",
    skill: "Narrator reliability",
    prompt: "A narrator whose account can't be fully trusted is...",
    choices: ["unreliable", "omniscient", "objective", "second-person"],
    answer: 0,
    explanation: "An unreliable narrator's bias, lies, or limits make readers question the story.",
    quick: true,
  },
  {
    id: "ela-g12-08",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Word origins",
    prompt: "The study of a word's origin and history is...",
    choices: ["etymology", "entomology", "syntax", "phonics"],
    answer: 0,
    explanation: "Etymology traces word histories. Entomology is the study of insects.",
    quick: true,
  },
  {
    id: "ela-g12-09",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Who and whom",
    prompt: "To ___ should I address the letter? Which word fits?",
    choices: ["whom", "who", "whose", "who's"],
    answer: 0,
    explanation: "Use whom as the object of a preposition: to whom.",
    quick: true,
  },
  {
    id: "ela-g12-10",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Subjunctive mood",
    prompt: "The board insisted that he ___ on time. Which verb fits?",
    choices: ["be", "is", "was", "being"],
    answer: 0,
    explanation: "After verbs like insist or demand, formal English uses the subjunctive base form: be.",
    quick: true,
  },
  {
    id: "ela-g12-11",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.8",
    skill: "Reasoning",
    prompt: "An argument that assumes its conclusion in its premise is...",
    choices: ["circular", "deductive", "inductive", "analogical"],
    answer: 0,
    explanation: "Circular reasoning, also called begging the question, goes around in a loop instead of proving anything.",
    quick: true,
  },
  {
    id: "ela-g12-12",
    subject: "ela",
    grade: "12",
    standard: "W.11-12.1",
    skill: "Argument writing",
    prompt: "Admitting the other side has a valid point is called a...",
    choices: ["concession", "thesis", "claim", "hook"],
    answer: 0,
    explanation: "A concession grants part of the opposing view, which builds credibility before a rebuttal.",
    quick: true,
  },
  {
    id: "ela-g12-13",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'He's not unkind' is an example of...",
    choices: ["litotes", "hyperbole", "simile", "oxymoron"],
    answer: 0,
    explanation: "Litotes is understatement by denying the opposite: 'not unkind' means kind.",
    quick: true,
  },
  {
    id: "ela-g12-14",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.6",
    skill: "Satire and purpose",
    prompt: "What is the author's likely purpose?",
    passage: "Clearly, the best way to reduce library noise is to remove all the books. Without books, there will be nothing to discuss, and silence will finally reign.",
    choices: ["To satirize a foolish solution by exaggerating it", "To seriously propose removing books", "To describe a library's history", "To praise librarians"],
    answer: 0,
    explanation: "The absurd 'solution' is exaggerated on purpose to mock simple-minded fixes.",
  },
  {
    id: "ela-g12-15",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "The old clockmaker repaired every clock in the village but let his own stand still. 'Time,' he told his apprentice, 'is for other people.' When he died, the apprentice wound it for the first time, and its chime filled the empty shop.",
    choices: ["A life spent only serving others can go unlived.", "Clocks are difficult to repair.", "Apprentices should not touch tools.", "Villages depend on accurate time."],
    answer: 0,
    explanation: "The clockmaker kept everyone's time but his own; his clock chimes only after his death.",
  },
  {
    id: "ela-g12-16",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.4",
    skill: "Connotation",
    prompt: "What does the word loomed suggest about the mansion?",
    passage: "The mansion did not merely stand on the hill; it loomed, casting its long, cold shadow over the cottages below.",
    choices: ["a threatening, overpowering presence", "a warm and welcoming shelter", "a crumbling ruin", "a hidden location"],
    answer: 0,
    explanation: "Loomed connotes something large and menacing, reinforced by the 'long, cold shadow.'",
  },
  {
    id: "ela-g12-17",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Dangling modifiers",
    prompt: "Which revision fixes 'Having finished the essay, the TV was turned on'?",
    choices: ["Having finished the essay, Lena turned on the TV.", "Having finished the essay, the TV was on.", "The TV, having finished the essay, was on.", "Having finished, the essay turned on the TV."],
    answer: 0,
    explanation: "The opening phrase must describe the person who finished the essay, so Lena must follow it.",
  },
  {
    id: "ela-g12-18",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does loquacious most likely mean?",
    passage: "Though he was usually loquacious, holding forth for hours at dinner parties, Arthur fell silent when the letter arrived.",
    choices: ["talkative", "quiet", "generous", "forgetful"],
    answer: 0,
    explanation: "'Holding forth for hours' is a clue that loquacious means very talkative.",
  },
  {
    id: "ela-g12-19",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Latin roots",
    prompt: "The Latin root magn (as in magnify) means...",
    choices: ["great", "small", "light", "iron"],
    answer: 0,
    explanation: "Magn means great or large, as in magnificent and magnitude.",
    quick: true,
  },
  {
    id: "ela-g12-20",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Greek roots",
    prompt: "The Greek root morph (as in metamorphosis) means...",
    choices: ["form", "death", "light", "sleep"],
    answer: 0,
    explanation: "Morph means form or shape. Metamorphosis is a change of form.",
    quick: true,
  },
  {
    id: "ela-g12-21",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Latin prefixes",
    prompt: "The prefix retro- (as in retrospect) means...",
    choices: ["backward", "again", "forward", "inside"],
    answer: 0,
    explanation: "Retro- means backward. Retrospect is looking back.",
    quick: true,
  },
  {
    id: "ela-g12-22",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Latin roots",
    prompt: "The Latin root vinc/vict (as in invincible) means...",
    choices: ["conquer", "live", "see", "wine"],
    answer: 0,
    explanation: "Vinc and vict mean conquer, as in victory and invincible.",
    quick: true,
  },
  {
    id: "ela-g12-23",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Greek roots",
    prompt: "The Greek root theo (as in theology) means...",
    choices: ["god", "idea", "law", "star"],
    answer: 0,
    explanation: "Theo means god. Theology is the study of religion and God.",
    quick: true,
  },
  {
    id: "ela-g12-24",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Polysyndeton",
    prompt: "Repeating and between items, as in 'and stars and moons and suns,' is...",
    choices: ["polysyndeton", "asyndeton", "anaphora", "zeugma"],
    answer: 0,
    explanation: "Polysyndeton adds extra conjunctions to slow the pace and pile up ideas.",
    quick: true,
  },
  {
    id: "ela-g12-25",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Nuance",
    prompt: "Which word means stubborn in an admiring way?",
    choices: ["resolute", "obstinate", "pigheaded", "mulish"],
    answer: 0,
    explanation: "Resolute praises firm determination. The others criticize stubbornness.",
    quick: true,
  },
  {
    id: "ela-g12-26",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Paradox",
    prompt: "'Less is more' is an example of a...",
    choices: ["paradox", "simile", "pun", "analogy"],
    answer: 0,
    explanation: "A paradox seems to contradict itself but reveals a truth.",
    quick: true,
  },
  {
    id: "ela-g12-27",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Agreement",
    prompt: "Each of the senators ___ voted. Which word fits?",
    choices: ["has", "have", "are", "were"],
    answer: 0,
    explanation: "Each is singular, so it takes has.",
    quick: true,
  },
  {
    id: "ela-g12-28",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Whoever and whomever",
    prompt: "Give the prize to ___ finishes first. Which word fits?",
    choices: ["whoever", "whomever", "whom", "whose"],
    answer: 0,
    explanation: "The pronoun is the subject of finishes, so use whoever.",
    quick: true,
  },
  {
    id: "ela-g12-29",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.2",
    skill: "Semicolons in series",
    prompt: "Which mark separates list items that already contain commas?",
    choices: ["semicolon", "colon", "dash", "period"],
    answer: 0,
    explanation: "Semicolons keep complex list items clear, as in 'Paris, France; Rome, Italy.'",
    quick: true,
  },
  {
    id: "ela-g12-30",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.2",
    skill: "Spelling",
    prompt: "Which spelling is correct?",
    choices: ["millennium", "millenium", "milennium", "millenim"],
    answer: 0,
    explanation: "Millennium has two l's and two n's.",
    quick: true,
  },
  {
    id: "ela-g12-31",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.3",
    skill: "Sentence types",
    prompt: "A sentence that saves its main idea for the end is called a ___ sentence.",
    choices: ["periodic", "loose", "compound", "fragment"],
    answer: 0,
    explanation: "A periodic sentence builds suspense by delaying the main clause.",
    quick: true,
  },
  {
    id: "ela-g12-32",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Drama",
    prompt: "A brief funny scene that eases tension in a tragedy is...",
    choices: ["comic relief", "an aside", "a soliloquy", "catharsis"],
    answer: 0,
    explanation: "Comic relief gives the audience a short break from the tragedy.",
    quick: true,
  },
  {
    id: "ela-g12-33",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Poetic forms",
    prompt: "A poem mourning someone's death is an...",
    choices: ["elegy", "ode", "epic", "idyll"],
    answer: 0,
    explanation: "An elegy is a poem of mourning.",
    quick: true,
  },
  {
    id: "ela-g12-34",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Meter",
    prompt: "A metrical foot with an unstressed then stressed syllable is an...",
    choices: ["iamb", "trochee", "spondee", "anapest"],
    answer: 0,
    explanation: "An iamb sounds like da-DUM, as in 'today.'",
    quick: true,
  },
  {
    id: "ela-g12-35",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.9",
    skill: "American literature",
    prompt: "Poe's and Hawthorne's dark tales belong to which movement?",
    choices: ["Romanticism", "Realism", "Modernism", "Puritanism"],
    answer: 0,
    explanation: "Poe and Hawthorne wrote in the dark strand of American Romanticism.",
    quick: true,
  },
  {
    id: "ela-g12-36",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.9",
    skill: "American literature",
    prompt: "Hemingway and Fitzgerald are leading writers of...",
    choices: ["Modernism", "Romanticism", "Realism", "Puritanism"],
    answer: 0,
    explanation: "These 'Lost Generation' writers of the 1920s are central to American Modernism.",
    quick: true,
  },
  {
    id: "ela-g12-37",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.8",
    skill: "Inductive reasoning",
    prompt: "Reasoning from many specific cases to a general rule is...",
    choices: ["inductive", "deductive", "circular", "analogical"],
    answer: 0,
    explanation: "Inductive reasoning builds a general conclusion from specific examples.",
    quick: true,
  },
  {
    id: "ela-g12-38",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.9",
    skill: "Seminal documents",
    prompt: "Which document opens with 'We the People of the United States'?",
    choices: ["Constitution", "Declaration", "Bill of Rights", "Federalist 10"],
    answer: 0,
    explanation: "The Preamble to the U.S. Constitution begins 'We the People.'",
    quick: true,
  },
  {
    id: "ela-g12-39",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.1",
    skill: "Inference",
    prompt: "What does this detail most strongly imply?",
    passage: "After the trial, Judge Harmon walked home in the rain without opening his umbrella, though it hung from his arm the entire way.",
    choices: ["He is deeply preoccupied by the trial.", "He enjoys the rain.", "His umbrella is broken.", "He forgot where he lived."],
    answer: 0,
    explanation: "Not noticing the umbrella on his arm shows his mind is still on the trial.",
  },
  {
    id: "ela-g12-40",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.3",
    skill: "Setting as symbol",
    prompt: "What does the setting most likely symbolize?",
    passage: "The family's reunion takes place in a house that is being torn down. Between conversations, the walls come down one by one.",
    choices: ["the family's crumbling bonds", "a fresh start in a new home", "the family's wealth", "an interest in construction"],
    answer: 0,
    explanation: "Walls falling during the reunion mirror the family coming apart.",
  },
  {
    id: "ela-g12-41",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.4",
    skill: "Double meanings",
    prompt: "Which double meaning does 'at rest' suggest?",
    passage: "In the final scene, the old soldier says he is finally 'at rest,' sitting in the sun while the town celebrates the end of the war.",
    choices: ["both peace and coming death", "both sleep and work", "both victory and defeat", "both noise and silence"],
    answer: 0,
    explanation: "'At rest' can mean relaxed and at peace, or it can hint at death.",
  },
  {
    id: "ela-g12-42",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Structure",
    prompt: "What does this alternating structure most likely highlight?",
    passage: "Each chapter alternates between a mother's diary from 1968 and her daughter's text messages from 2018.",
    choices: ["parallels between generations", "the history of phones", "the mother's travels", "the events of one day"],
    answer: 0,
    explanation: "Moving between mother and daughter invites readers to compare their lives.",
  },
  {
    id: "ela-g12-43",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.6",
    skill: "Irony",
    prompt: "What type of irony is this?",
    passage: "'Wonderful,' said Mara, staring at the flat tire, the empty spare, and the darkening sky. 'Just what I needed.'",
    choices: ["verbal", "dramatic", "situational", "cosmic"],
    answer: 0,
    explanation: "Mara says 'wonderful' but means the opposite, which is verbal irony.",
  },
  {
    id: "ela-g12-44",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.2",
    skill: "Interacting ideas",
    prompt: "How do the central ideas interact?",
    passage: "Antibiotics transformed medicine, turning once-deadly infections into minor illnesses. But their overuse in people and livestock has bred resistant bacteria, threatening to undo a century of progress.",
    choices: ["A great advance is endangered by misuse.", "Antibiotics never worked.", "Livestock cause all disease.", "Bacteria are harmless."],
    answer: 0,
    explanation: "Antibiotics transformed medicine, but overuse now threatens that progress.",
  },
  {
    id: "ela-g12-45",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.5",
    skill: "Structure",
    prompt: "How is the essay structured?",
    passage: "The essay opens with a single patient's story, widens to hospital statistics, and closes with recommendations for national policy.",
    choices: ["from one case to broad conclusions", "from general to specific", "by century", "as unrelated facts"],
    answer: 0,
    explanation: "It starts with one patient and widens to statistics and national policy.",
  },
  {
    id: "ela-g12-46",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.6",
    skill: "Rhetoric",
    prompt: "What is the main effect of the repeated 'We will build'?",
    passage: "We will build when others doubt. We will build when others quit. We will build until the work is done.",
    choices: ["It creates determination and momentum.", "It shows uncertainty.", "It adds humor.", "It introduces a counterclaim."],
    answer: 0,
    explanation: "Repeating the phrase (anaphora) builds a strong, determined rhythm.",
  },
  {
    id: "ela-g12-47",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does perfunctory mean?",
    passage: "Her apology was perfunctory: a quick 'sorry' tossed over her shoulder as she left, without a glance back.",
    choices: ["done with little care", "deeply sincere", "very long", "formally written"],
    answer: 0,
    explanation: "A quick 'sorry' over her shoulder without looking back shows little care.",
  },
  {
    id: "ela-g12-48",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.3",
    skill: "Concise writing",
    prompt: "Which revision of 'Due to the fact that it was raining, the game was postponed until a later date' is most concise?",
    choices: ["Because it was raining, the game was postponed.", "Due to the fact that it rained, the game was postponed until later.", "The game was postponed until a later date due to the rain falling.", "Because of the fact of rain, the game was put off to a later date."],
    answer: 0,
    explanation: "'Because' replaces 'due to the fact that,' and 'postponed' already means moved to a later date.",
  },
];

export default questions;
