import type { Question } from "../../types";

// Grade 11 ELA — NC Standard Course of Study for ELA (2017). English III (11-12 band): RL.11-12.1, RL.11-12.3, RL.11-12.4, RL.11-12.5, RL.11-12.6, RL.11-12.9, RI.11-12.2, RI.11-12.4, RI.11-12.6, RI.11-12.8, W.11-12.1, L.11-12.1, L.11-12.2, L.11-12.3, L.11-12.4, L.11-12.5
const questions: Question[] = [
  {
    id: "ela-g11-01",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Satire",
    prompt: "A work that mocks human foolishness to push for change is...",
    choices: ["satire", "elegy", "epic", "ode"],
    answer: 0,
    explanation: "Satire uses humor, irony, and exaggeration to criticize and encourage reform.",
    quick: true,
  },
  {
    id: "ela-g11-02",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Understatement",
    prompt: "Calling a hurricane 'a bit of wind' is...",
    choices: ["understatement", "hyperbole", "alliteration", "allusion"],
    answer: 0,
    explanation: "Understatement makes something seem much smaller than it is, often for irony.",
    quick: true,
  },
  {
    id: "ela-g11-03",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'The more you learn, the less you know' is a...",
    choices: ["paradox", "simile", "euphemism", "pun"],
    answer: 0,
    explanation: "A paradox seems self-contradictory but reveals a deeper truth.",
    quick: true,
  },
  {
    id: "ela-g11-04",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'The White House announced a new plan' uses...",
    choices: ["metonymy", "simile", "apostrophe", "hyperbole"],
    answer: 0,
    explanation: "Metonymy names something closely associated (the building) to mean the thing itself (the administration).",
    quick: true,
  },
  {
    id: "ela-g11-05",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Rhetorical devices",
    prompt: "A question asked for effect, not for an answer, is...",
    choices: ["rhetorical", "literal", "factual", "open-ended"],
    answer: 0,
    explanation: "A rhetorical question makes a point or engages the audience rather than seeking a reply.",
    quick: true,
  },
  {
    id: "ela-g11-06",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.4",
    skill: "Diction",
    prompt: "An author's specific word choice is called...",
    choices: ["diction", "syntax", "tone", "imagery"],
    answer: 0,
    explanation: "Diction is word choice. Syntax is how words are arranged.",
    quick: true,
  },
  {
    id: "ela-g11-07",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.3",
    skill: "Syntax",
    prompt: "The arrangement of words and phrases in a sentence is...",
    choices: ["syntax", "diction", "tone", "semantics"],
    answer: 0,
    explanation: "Syntax covers sentence order, length, and structure.",
    quick: true,
  },
  {
    id: "ela-g11-08",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root loqu (as in eloquent) means...",
    choices: ["speak", "write", "light", "lose"],
    answer: 0,
    explanation: "Loqu means speak, as in eloquent, loquacious, and soliloquy.",
    quick: true,
  },
  {
    id: "ela-g11-09",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Greek and Latin roots",
    prompt: "The prefix omni- (as in omnipotent) means...",
    choices: ["all", "none", "some", "power"],
    answer: 0,
    explanation: "Omni- means all, so omnipotent means all-powerful.",
    quick: true,
  },
  {
    id: "ela-g11-10",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.5",
    skill: "Drama",
    prompt: "A long speech by a character alone on stage is a...",
    choices: ["soliloquy", "dialogue", "aside", "epilogue"],
    answer: 0,
    explanation: "In a soliloquy, a character speaks thoughts aloud alone. An aside is a brief remark to the audience.",
    quick: true,
  },
  {
    id: "ela-g11-11",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Hyphens",
    prompt: "Which compound adjective is hyphenated correctly?",
    choices: ["up-to-date app", "up to-date app", "up-to date app", "uptodate app"],
    answer: 0,
    explanation: "Hyphenate all the words of a compound adjective that comes before a noun.",
    quick: true,
  },
  {
    id: "ela-g11-12",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.8",
    skill: "Reasoning",
    prompt: "Reasoning from a general principle to a specific case is...",
    choices: ["deductive", "inductive", "circular", "anecdotal"],
    answer: 0,
    explanation: "Deductive reasoning moves from general to specific; inductive moves from specific cases to a general rule.",
    quick: true,
  },
  {
    id: "ela-g11-13",
    subject: "ela",
    grade: "11",
    standard: "W.11-12.1",
    skill: "Argument writing",
    prompt: "An argument's central, debatable claim is its...",
    choices: ["thesis", "anecdote", "hook", "citation"],
    answer: 0,
    explanation: "The thesis states the precise claim the whole argument supports.",
    quick: true,
  },
  {
    id: "ela-g11-14",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Irony",
    prompt: "What type of irony is in this passage?",
    passage: "The fire station burned down last night. The firefighters, who had been out rescuing a cat from a tree, returned to find their own building in ashes.",
    choices: ["situational irony", "verbal irony", "dramatic irony", "no irony"],
    answer: 0,
    explanation: "Situational irony is when the outcome is the opposite of what we expect: firefighters lose their own station to fire.",
  },
  {
    id: "ela-g11-15",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Rhetorical devices",
    prompt: "Which device appears in 'We did not choose the storm, but we can choose how we weather it'?",
    passage: "We did not choose the storm, but we can choose how we weather it. Let us not ask whether the task is easy; let us ask whether it is right. And if it is right, let us begin, today, together, without delay.",
    choices: ["antithesis", "understatement", "onomatopoeia", "euphemism"],
    answer: 0,
    explanation: "Antithesis sets contrasting ideas side by side in parallel form for emphasis.",
  },
  {
    id: "ela-g11-16",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.3",
    skill: "Syntax and style",
    prompt: "What is the effect of the short sentence followed by a long one?",
    passage: "She ran. She ran past the mill, past the church, past the last lit window of the town, until the road dissolved into dark fields and the only sound was her own breathing.",
    choices: ["The long sentence mirrors her run stretching on.", "It shows that she stopped running.", "It creates a humorous tone.", "It introduces a new character."],
    answer: 0,
    explanation: "The long, flowing sentence carries the reader forward just as the road carries her into the distance.",
  },
  {
    id: "ela-g11-17",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Comma splices",
    prompt: "Which sentence avoids a comma splice?",
    choices: ["The results were clear; the plan had worked.", "The results were clear, the plan had worked.", "The results were clear the plan had worked.", "The results, were clear the plan had worked."],
    answer: 0,
    explanation: "A semicolon can correctly join two independent clauses; a comma alone cannot.",
  },
  {
    id: "ela-g11-18",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does specious most likely mean?",
    passage: "The lawyer's argument was specious: it sounded convincing at first, but under careful examination, its logic fell apart.",
    choices: ["seeming true but actually false", "completely honest", "overly long", "difficult to hear"],
    answer: 0,
    explanation: "The argument sounded convincing but fell apart, so specious means misleadingly plausible.",
  },
  {
    id: "ela-g11-19",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Latin roots",
    prompt: "The Latin root culp (as in culprit) means...",
    choices: ["blame", "hide", "cut", "crowd"],
    answer: 0,
    explanation: "Culp means blame or guilt, as in culpable.",
    quick: true,
  },
  {
    id: "ela-g11-20",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Greek roots",
    prompt: "The Greek root pseudo (as in pseudonym) means...",
    choices: ["false", "name", "new", "hidden"],
    answer: 0,
    explanation: "Pseudo means false. A pseudonym is a false name.",
    quick: true,
  },
  {
    id: "ela-g11-21",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Latin prefixes",
    prompt: "The prefix ante- (as in antebellum) means...",
    choices: ["before", "against", "after", "war"],
    answer: 0,
    explanation: "Ante- means before. Antebellum means before the war.",
    quick: true,
  },
  {
    id: "ela-g11-22",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Latin roots",
    prompt: "The Latin root equi (as in equitable) means...",
    choices: ["equal", "horse", "quick", "calm"],
    answer: 0,
    explanation: "Equi means equal. Equine, meaning horse, comes from a different root.",
    quick: true,
  },
  {
    id: "ela-g11-23",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Word forms",
    prompt: "Which word is the noun form of resilient?",
    choices: ["resilience", "resiliently", "resiling", "resilientness"],
    answer: 0,
    explanation: "The suffix -ence turns resilient into the noun resilience.",
    quick: true,
  },
  {
    id: "ela-g11-24",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Zeugma",
    prompt: "'She broke his car and his heart' is an example of...",
    choices: ["zeugma", "chiasmus", "litotes", "anaphora"],
    answer: 0,
    explanation: "Zeugma uses one word (broke) in two different senses in the same sentence.",
    quick: true,
  },
  {
    id: "ela-g11-25",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Nuance",
    prompt: "Which word implies cleverness used to deceive?",
    choices: ["cunning", "wise", "brilliant", "insightful"],
    answer: 0,
    explanation: "Cunning suggests sly, deceptive cleverness. The others are positive.",
    quick: true,
  },
  {
    id: "ela-g11-26",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Epistrophe",
    prompt: "Repeating a word at the END of successive clauses is...",
    choices: ["epistrophe", "anaphora", "chiasmus", "asyndeton"],
    answer: 0,
    explanation: "Epistrophe repeats at the end. Anaphora repeats at the beginning.",
    quick: true,
  },
  {
    id: "ela-g11-27",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.1",
    skill: "Usage",
    prompt: "There were ___ errors than expected. Which word fits formal writing?",
    choices: ["fewer", "less", "lesser", "lower"],
    answer: 0,
    explanation: "Use fewer with things you can count, like errors. Use less with amounts.",
    quick: true,
  },
  {
    id: "ela-g11-28",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.1",
    skill: "Usage",
    prompt: "The new law will ___ every driver. Which word fits?",
    choices: ["affect", "effect", "effects", "affection"],
    answer: 0,
    explanation: "Affect is usually a verb meaning to influence. Effect is usually a noun.",
    quick: true,
  },
  {
    id: "ela-g11-29",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Spelling",
    prompt: "Which word is spelled correctly?",
    choices: ["privilege", "privelege", "priviledge", "privilage"],
    answer: 0,
    explanation: "Privilege has no d and is spelled p-r-i-v-i-l-e-g-e.",
    quick: true,
  },
  {
    id: "ela-g11-30",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Dashes",
    prompt: "A pair of dashes in a sentence usually sets off...",
    choices: ["interruptions", "questions", "titles", "possessives"],
    answer: 0,
    explanation: "Paired dashes set off an interruption or emphasized aside.",
    quick: true,
  },
  {
    id: "ela-g11-31",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.3",
    skill: "Asyndeton",
    prompt: "Leaving out conjunctions, as in 'I came, I saw, I conquered,' is...",
    choices: ["asyndeton", "polysyndeton", "anaphora", "ellipsis"],
    answer: 0,
    explanation: "Asyndeton drops conjunctions to create speed and force.",
    quick: true,
  },
  {
    id: "ela-g11-32",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.5",
    skill: "Novel forms",
    prompt: "A novel told through letters or diary entries is an ___ novel.",
    choices: ["epistolary", "episodic", "allegorical", "gothic"],
    answer: 0,
    explanation: "Epistolary comes from epistle, meaning letter.",
    quick: true,
  },
  {
    id: "ela-g11-33",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.5",
    skill: "Allegory",
    prompt: "A story whose characters and events stand for abstract ideas is an...",
    choices: ["allegory", "elegy", "epic", "ode"],
    answer: 0,
    explanation: "In an allegory, the surface story represents deeper moral or political ideas.",
    quick: true,
  },
  {
    id: "ela-g11-34",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.9",
    skill: "American literature",
    prompt: "Transcendentalists like Emerson and Thoreau valued...",
    choices: ["self-reliance", "city life", "conformity", "wealth"],
    answer: 0,
    explanation: "Transcendentalists prized individual intuition, nature, and self-reliance.",
    quick: true,
  },
  {
    id: "ela-g11-35",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.9",
    skill: "American literature",
    prompt: "Writers of the Harlem Renaissance mainly explored...",
    choices: ["Black identity", "frontier life", "Puritan faith", "war in Europe"],
    answer: 0,
    explanation: "The Harlem Renaissance celebrated Black culture, identity, and art in the 1920s.",
    quick: true,
  },
  {
    id: "ela-g11-36",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.8",
    skill: "Seminal reasoning",
    prompt: "The Declaration of Independence's argument rests on the idea of...",
    choices: ["natural rights", "divine right", "monarchy", "isolation"],
    answer: 0,
    explanation: "It argues that people have unalienable rights, and government must protect them.",
    quick: true,
  },
  {
    id: "ela-g11-37",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Antithesis",
    prompt: "Placing contrasting ideas in parallel phrases is called...",
    choices: ["antithesis", "hyperbole", "euphemism", "apostrophe"],
    answer: 0,
    explanation: "Antithesis sets opposites side by side for emphasis, as in 'not a burden, but a gift.'",
    quick: true,
  },
  {
    id: "ela-g11-38",
    subject: "ela",
    grade: "11",
    standard: "W.11-12.1",
    skill: "Qualifying claims",
    prompt: "Limiting a claim with words like often or most is called...",
    choices: ["qualifying", "refuting", "summarizing", "citing"],
    answer: 0,
    explanation: "Qualifying a claim makes it more precise and easier to defend.",
    quick: true,
  },
  {
    id: "ela-g11-39",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.1",
    skill: "Uncertainty",
    prompt: "What does the letter's ending leave uncertain?",
    passage: "The letter ended simply: 'The farm is yours now. Do what I could not.' Nothing more. There was no explanation of what he had failed to do.",
    choices: ["what the writer failed to do", "who received the farm", "whether the farm exists", "who the letter is to"],
    answer: 0,
    explanation: "The writer says 'Do what I could not' but never explains what that was.",
  },
  {
    id: "ela-g11-40",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.3",
    skill: "Developing character",
    prompt: "What is the effect of revealing the mayor only through others?",
    passage: "At the barbershop, they called Mayor Briggs a saint. At the diner, a crook. At church, nobody said his name at all.",
    choices: ["He seems mysterious and disputed.", "He seems loved by all.", "His policies are clearly explained.", "His inner thoughts are revealed."],
    answer: 0,
    explanation: "Conflicting opinions and silence make him a contested, mysterious figure.",
  },
  {
    id: "ela-g11-41",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.4",
    skill: "Word choice and tone",
    prompt: "What attitude does the word choice convey?",
    passage: "The new apartment complex rose where the orchard had been, its rows of identical windows staring blankly over the parking lot.",
    choices: ["regret over lost natural beauty", "excitement about growth", "neutral reporting", "admiration for the design"],
    answer: 0,
    explanation: "The lost orchard and windows 'staring blankly' give the scene a sense of loss.",
  },
  {
    id: "ela-g11-42",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.5",
    skill: "Structure and suspense",
    prompt: "What effect does this structure most likely have?",
    passage: "The novel opens at the funeral of its main character, then spends 300 pages tracing the year that led up to it.",
    choices: ["It shifts suspense to why it happens.", "It removes all interest.", "It makes the timeline impossible to follow.", "It makes the death a surprise."],
    answer: 0,
    explanation: "Knowing the ending makes readers ask why and how it happened.",
  },
  {
    id: "ela-g11-43",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Satire",
    prompt: "What is the author's real point?",
    passage: "I humbly suggest we solve traffic by banning cars on weekdays, so that every citizen may enjoy a pleasant thirty-mile walk to work.",
    choices: ["Simplistic fixes for traffic are absurd.", "Walking thirty miles is healthy.", "Cars should be banned.", "Weekends need more traffic."],
    answer: 0,
    explanation: "The ridiculous plan exaggerates to mock oversimplified solutions.",
  },
  {
    id: "ela-g11-44",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.2",
    skill: "Interacting ideas",
    prompt: "How do the passage's two ideas relate?",
    passage: "The interstate highway system made cross-country travel faster than ever. At the same time, it bypassed hundreds of small towns, whose main streets emptied as traffic flowed elsewhere.",
    choices: ["A benefit for some brought losses for others.", "Both describe benefits.", "Both describe losses.", "They are unrelated."],
    answer: 0,
    explanation: "The highways helped travelers but hurt the towns they bypassed.",
  },
  {
    id: "ela-g11-45",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.4",
    skill: "Refining a key term",
    prompt: "How does the author's use of freedom develop?",
    passage: "Early in the essay, the author defines freedom as the absence of restraint. By the end, she argues that freedom also requires the resources to act on one's choices.",
    choices: ["It broadens to include the means to act.", "It stays exactly the same.", "It narrows to mean voting rights.", "The author drops the term."],
    answer: 0,
    explanation: "The definition grows from 'no restraint' to also having resources to act on choices.",
  },
  {
    id: "ela-g11-46",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Rhetoric",
    prompt: "How does the author strengthen the argument?",
    passage: "We are told that change is too costly. But what is the cost of doing nothing? Ask the families whose homes have flooded twice this decade.",
    choices: ["by reframing cost and citing affected families", "by citing a scientific study", "by conceding the cost is too high", "by attacking opponents personally"],
    answer: 0,
    explanation: "The author turns 'too costly' around and points to real families who paid the price.",
  },
  {
    id: "ela-g11-47",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does derivative mean here?",
    passage: "Critics called the director's latest film derivative, noting that nearly every scene borrowed from earlier, better-known movies.",
    choices: ["unoriginal", "groundbreaking", "mathematical", "expensive"],
    answer: 0,
    explanation: "Scenes borrowed from earlier movies show the film was unoriginal.",
  },
  {
    id: "ela-g11-48",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.1",
    skill: "Lie and lay",
    prompt: "Which sentence uses lie and lay correctly?",
    choices: ["I will lie down after I lay the book on the table.", "I will lay down after I lie the book on the table.", "I will lay down after I lay the book on the table.", "I will lie down after I lie the book on the table."],
    answer: 0,
    explanation: "You lie down yourself; you lay an object somewhere.",
  },
];

export default questions;
