import type { Question } from "../../types";

// Grade 6 ELA — NC Standard Course of Study for ELA (2017). RL.6.1, RL.6.2, RL.6.3, RL.6.4, RL.6.5, RL.6.6, RI.6.2, RI.6.4, RI.6.5, RI.6.6, RI.6.8, W.6.1, L.6.1, L.6.2, L.6.3, L.6.4, L.6.5
const questions: Question[] = [
  {
    id: "ela-g6-01",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun case",
    prompt: "Maya and ___ went to the store. Which pronoun fits?",
    choices: ["I", "me", "myself", "mine"],
    answer: 0,
    explanation: "Use the subject pronoun I. Test it alone: I went to the store.",
    quick: true,
  },
  {
    id: "ela-g6-02",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun case",
    prompt: "The coach gave the award to Jordan and ___.",
    choices: ["me", "I", "myself", "mine"],
    answer: 0,
    explanation: "After a preposition like to, use the object pronoun me: gave it to me.",
    quick: true,
  },
  {
    id: "ela-g6-03",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Intensive pronouns",
    prompt: "In 'I built the shed myself,' what kind of pronoun is myself?",
    choices: ["intensive", "possessive", "objective", "relative"],
    answer: 0,
    explanation: "An intensive pronoun adds emphasis. The sentence still works without it.",
    quick: true,
  },
  {
    id: "ela-g6-04",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root chron (as in chronological) means...",
    choices: ["time", "color", "sound", "city"],
    answer: 0,
    explanation: "Chron means time. Chronological order is time order.",
    quick: true,
  },
  {
    id: "ela-g6-05",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Greek and Latin roots",
    prompt: "The root geo (as in geology) means...",
    choices: ["earth", "life", "star", "water"],
    answer: 0,
    explanation: "Geo means earth. Geology is the study of Earth's rocks and layers.",
    quick: true,
  },
  {
    id: "ela-g6-06",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "Which word has the most positive connotation?",
    choices: ["thrifty", "cheap", "stingy", "miserly"],
    answer: 0,
    explanation: "All four mean careful with money, but thrifty sounds wise while the others sound negative.",
    quick: true,
  },
  {
    id: "ela-g6-07",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "Which is a negative way to describe a curious person?",
    choices: ["nosy", "inquisitive", "interested", "eager"],
    answer: 0,
    explanation: "Nosy suggests poking into things that aren't your business, a negative connotation.",
    quick: true,
  },
  {
    id: "ela-g6-08",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Analogies",
    prompt: "Finger is to hand as toe is to...",
    choices: ["foot", "leg", "shoe", "nail"],
    answer: 0,
    explanation: "This is a part-to-whole analogy: a finger is part of a hand; a toe is part of a foot.",
    quick: true,
  },
  {
    id: "ela-g6-09",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Figurative language",
    prompt: "'Her words were daggers.' The metaphor suggests her words were...",
    choices: ["hurtful", "funny", "shiny", "quiet"],
    answer: 0,
    explanation: "Daggers cut, so the metaphor means her words hurt.",
    quick: true,
  },
  {
    id: "ela-g6-10",
    subject: "ela",
    grade: "6",
    standard: "RL.6.6",
    skill: "Point of view",
    prompt: "A narrator who is a character and uses I tells the story in...",
    choices: ["first person", "third person", "omniscient", "second person"],
    answer: 0,
    explanation: "When a character tells the story using I, it is first-person point of view.",
    quick: true,
  },
  {
    id: "ela-g6-11",
    subject: "ela",
    grade: "6",
    standard: "RI.6.5",
    skill: "Text structure",
    prompt: "Which structure best fits a text on why dinosaurs died out?",
    choices: ["cause/effect", "chronology", "comparison", "description"],
    answer: 0,
    explanation: "Explaining why something happened is cause-and-effect structure.",
    quick: true,
  },
  {
    id: "ela-g6-12",
    subject: "ela",
    grade: "6",
    standard: "W.6.1",
    skill: "Argument writing",
    prompt: "In an argument, the writer's main position is the...",
    choices: ["claim", "evidence", "hook", "summary"],
    answer: 0,
    explanation: "The claim is the position the writer argues. Evidence and reasons support it.",
    quick: true,
  },
  {
    id: "ela-g6-13",
    subject: "ela",
    grade: "6",
    standard: "RL.6.2",
    skill: "Theme",
    prompt: "A story's theme is best described as its...",
    choices: ["life lesson", "setting", "main event", "title"],
    answer: 0,
    explanation: "A theme is a message about life that the story develops, not a single event.",
    quick: true,
  },
  {
    id: "ela-g6-14",
    subject: "ela",
    grade: "6",
    standard: "RL.6.4",
    skill: "Mood and word choice",
    prompt: "Which word best describes the mood of this passage?",
    passage: "The house sat at the end of the lane, its windows dark and cracked. Wind moaned through the gaps in the boards, and a single shutter banged, again and again, like someone knocking to get in.",
    choices: ["eerie", "cheerful", "peaceful", "silly"],
    answer: 0,
    explanation: "Words like dark, cracked, moaned, and knocking create an eerie, spooky mood.",
  },
  {
    id: "ela-g6-15",
    subject: "ela",
    grade: "6",
    standard: "RI.6.8",
    skill: "Claims and evidence",
    prompt: "Which statement is an opinion with no evidence to support it?",
    passage: "Schools should start later in the morning. Studies of teenagers show that their sleep cycles shift, making it hard to fall asleep early. One district that moved its start time to 8:30 reported better attendance and higher grades. Besides, everyone enjoys sleeping in.",
    choices: ["Everyone enjoys sleeping in.", "Teen sleep cycles shift later.", "Attendance improved in one district.", "Grades rose in one district."],
    answer: 0,
    explanation: "The other statements come from studies or reports. 'Everyone enjoys sleeping in' is an unsupported opinion.",
  },
  {
    id: "ela-g6-16",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Vague pronouns",
    prompt: "Which sentence has a vague (unclear) pronoun?",
    choices: ["When Ana met Lily, she was nervous.", "Ana was nervous about meeting Lily.", "The dog wagged its tail at Ana.", "Marcus lost his hat at the park."],
    answer: 0,
    explanation: "In the first sentence, she could mean Ana or Lily, so the pronoun is vague.",
  },
  {
    id: "ela-g6-17",
    subject: "ela",
    grade: "6",
    standard: "RL.6.3",
    skill: "Character response",
    prompt: "What does Priya's response reveal about her?",
    passage: "Priya had rehearsed her speech for student council all week. The morning of the election, she discovered her note cards were missing. With minutes to go, she took a breath, walked to the podium, and spoke from memory about the ideas she truly cared about.",
    choices: ["She stays calm under pressure.", "She is careless and forgetful.", "She dislikes public speaking.", "She wants to quit the election."],
    answer: 0,
    explanation: "Instead of panicking, Priya breathes and speaks from memory, showing she is calm and resourceful.",
  },
  {
    id: "ela-g6-18",
    subject: "ela",
    grade: "6",
    standard: "RI.6.6",
    skill: "Author's purpose",
    prompt: "What is the author's main purpose?",
    passage: "Plastic straws might seem harmless, but millions end up in oceans each year, where they can injure sea animals. Switching to paper or metal straws is an easy change that every restaurant should make today.",
    choices: ["to persuade", "to entertain", "to explain how straws are made", "to tell a story"],
    answer: 0,
    explanation: "The words 'every restaurant should' show the author is trying to persuade.",
  },
  {
    id: "ela-g6-19",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Latin roots",
    prompt: "The Latin root dict (as in predict) means...",
    choices: ["say", "see", "write", "lead"],
    answer: 0,
    explanation: "Dict means say. To predict is to say what will happen before it happens.",
    quick: true,
  },
  {
    id: "ela-g6-20",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Latin roots",
    prompt: "The Latin root vis (as in visible) means...",
    choices: ["see", "hear", "live", "move"],
    answer: 0,
    explanation: "Vis means see. Something visible can be seen.",
    quick: true,
  },
  {
    id: "ela-g6-21",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Greek prefixes",
    prompt: "The Greek prefix auto- (as in autobiography) means...",
    choices: ["self", "many", "against", "life"],
    answer: 0,
    explanation: "Auto- means self. An autobiography is a life story written by that person.",
    quick: true,
  },
  {
    id: "ela-g6-22",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Latin roots",
    prompt: "The Latin root scrib/script (as in describe) means...",
    choices: ["write", "look", "speak", "draw"],
    answer: 0,
    explanation: "Scrib and script mean write, as in scribble and manuscript.",
    quick: true,
  },
  {
    id: "ela-g6-23",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Analogies",
    prompt: "Hot is to cold as ancient is to...",
    choices: ["modern", "old", "warm", "history"],
    answer: 0,
    explanation: "Hot and cold are opposites, so the answer is the opposite of ancient: modern.",
    quick: true,
  },
  {
    id: "ela-g6-24",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Word forms",
    prompt: "Which word is the adjective form of danger?",
    choices: ["dangerous", "endanger", "dangerously", "dangers"],
    answer: 0,
    explanation: "The suffix -ous makes an adjective: dangerous. Endanger is a verb.",
    quick: true,
  },
  {
    id: "ela-g6-25",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "Which word for thin has the most positive connotation?",
    choices: ["slender", "scrawny", "skinny", "bony"],
    answer: 0,
    explanation: "Slender sounds graceful. Scrawny, skinny, and bony sound less flattering.",
    quick: true,
  },
  {
    id: "ela-g6-26",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Figures of speech",
    prompt: "'The thunder grumbled like an old man.' This is a...",
    choices: ["simile", "metaphor", "hyperbole", "idiom"],
    answer: 0,
    explanation: "It compares thunder to an old man using like, so it is a simile.",
    quick: true,
  },
  {
    id: "ela-g6-27",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Hyperbole",
    prompt: "'This backpack weighs a ton!' This is an example of...",
    choices: ["hyperbole", "simile", "irony", "alliteration"],
    answer: 0,
    explanation: "Hyperbole is exaggeration for effect. The backpack does not really weigh a ton.",
    quick: true,
  },
  {
    id: "ela-g6-28",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun agreement",
    prompt: "The players grabbed ___ helmets. Which word fits?",
    choices: ["their", "his", "its", "her"],
    answer: 0,
    explanation: "Players is plural, so the pronoun must be plural: their.",
    quick: true,
  },
  {
    id: "ela-g6-29",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun case",
    prompt: "Between you and ___, this is easy. Which word fits?",
    choices: ["me", "I", "myself", "mine"],
    answer: 0,
    explanation: "Between is a preposition, so it takes the objective case: me.",
    quick: true,
  },
  {
    id: "ela-g6-30",
    subject: "ela",
    grade: "6",
    standard: "L.6.2",
    skill: "Commas with extra information",
    prompt: "Where is a comma missing? 'Max, a beagle loves bacon.'",
    choices: ["after beagle", "after Max", "after loves", "after bacon"],
    answer: 0,
    explanation: "Extra information like 'a beagle' needs a comma on both sides.",
    quick: true,
  },
  {
    id: "ela-g6-31",
    subject: "ela",
    grade: "6",
    standard: "L.6.2",
    skill: "Ellipses",
    prompt: "An ellipsis (...) in a quotation shows that...",
    choices: ["words are cut", "a list starts", "a question", "someone yells"],
    answer: 0,
    explanation: "An ellipsis marks words left out of a quotation.",
    quick: true,
  },
  {
    id: "ela-g6-32",
    subject: "ela",
    grade: "6",
    standard: "L.6.3",
    skill: "Formal style",
    prompt: "Which word best fits a formal essay?",
    choices: ["therefore", "gonna", "kinda", "stuff"],
    answer: 0,
    explanation: "Therefore is formal. Gonna, kinda, and stuff are casual.",
    quick: true,
  },
  {
    id: "ela-g6-33",
    subject: "ela",
    grade: "6",
    standard: "RL.6.5",
    skill: "Plot structure",
    prompt: "The turning point of highest tension in a plot is the...",
    choices: ["climax", "exposition", "resolution", "rising action"],
    answer: 0,
    explanation: "The climax is the peak of the story's tension.",
    quick: true,
  },
  {
    id: "ela-g6-34",
    subject: "ela",
    grade: "6",
    standard: "RL.6.3",
    skill: "Plot structure",
    prompt: "The part of a plot that introduces characters and setting is the...",
    choices: ["exposition", "climax", "falling action", "resolution"],
    answer: 0,
    explanation: "The exposition comes first and sets up the story.",
    quick: true,
  },
  {
    id: "ela-g6-35",
    subject: "ela",
    grade: "6",
    standard: "RL.6.2",
    skill: "Objective summaries",
    prompt: "An objective summary should NOT include...",
    choices: ["your opinions", "main events", "key details", "the main idea"],
    answer: 0,
    explanation: "An objective summary sticks to the text and leaves out personal opinions.",
    quick: true,
  },
  {
    id: "ela-g6-36",
    subject: "ela",
    grade: "6",
    standard: "RI.6.8",
    skill: "Claims and evidence",
    prompt: "Facts or examples that back up a claim are called...",
    choices: ["evidence", "opinions", "a hook", "a thesis"],
    answer: 0,
    explanation: "Evidence supports a claim. Without it, a claim is just an opinion.",
    quick: true,
  },
  {
    id: "ela-g6-37",
    subject: "ela",
    grade: "6",
    standard: "W.6.1",
    skill: "Transitions",
    prompt: "Which transition introduces an example?",
    choices: ["for example", "however", "in contrast", "meanwhile"],
    answer: 0,
    explanation: "For example signals that evidence or an example is coming.",
    quick: true,
  },
  {
    id: "ela-g6-38",
    subject: "ela",
    grade: "6",
    standard: "RL.6.4",
    skill: "Sound devices",
    prompt: "Words that imitate sounds, like buzz and sizzle, are examples of...",
    choices: ["onomatopoeia", "alliteration", "rhyme", "simile"],
    answer: 0,
    explanation: "Onomatopoeia is a word that sounds like what it names.",
    quick: true,
  },
  {
    id: "ela-g6-39",
    subject: "ela",
    grade: "6",
    standard: "RL.6.1",
    skill: "Making inferences",
    prompt: "What can you infer about Marisol?",
    passage: "Marisol checked the mailbox for the third time that afternoon. Still nothing. She sighed, closed it gently, and glanced down the road where the mail truck usually appeared.",
    choices: ["She is waiting for an important letter.", "She dislikes the mail carrier.", "She just mailed a package.", "She lost her house key."],
    answer: 0,
    explanation: "Checking three times and watching the road show she is eagerly waiting for mail.",
  },
  {
    id: "ela-g6-40",
    subject: "ela",
    grade: "6",
    standard: "RL.6.2",
    skill: "Theme",
    prompt: "Which theme fits this passage?",
    passage: "Every year, Carlos entered the science fair, and every year he lost. This year he didn't win again, but a judge asked to use his rain-collector design in the school garden. Carlos grinned the whole bus ride home.",
    choices: ["Success can mean more than winning.", "Science fairs are unfair.", "Gardens need rain.", "Judges are always right."],
    answer: 0,
    explanation: "Carlos did not win, but his design was valued, and he was proud.",
  },
  {
    id: "ela-g6-41",
    subject: "ela",
    grade: "6",
    standard: "RL.6.6",
    skill: "Narrator's point of view",
    prompt: "What does the narrator's sarcasm reveal?",
    passage: "Of course I volunteered to walk the neighbor's dog. It's not like I wanted to spend Saturday sleeping in or anything. The dog, naturally, chose the muddiest puddle in the county.",
    choices: ["She is annoyed about walking the dog.", "She loves walking the dog.", "She enjoys mud.", "She is excited for Saturday."],
    answer: 0,
    explanation: "'Of course' and 'not like I wanted to sleep in' are sarcastic. She did not want this job.",
  },
  {
    id: "ela-g6-42",
    subject: "ela",
    grade: "6",
    standard: "RI.6.2",
    skill: "Central idea",
    prompt: "What is the central idea?",
    passage: "Octopuses can change color in a fraction of a second. They use this skill to hide from predators, sneak up on prey, and even signal their mood. Special cells in their skin stretch or shrink to show different pigments.",
    choices: ["Octopuses change color quickly for many purposes.", "Octopuses have eight arms.", "Predators eat octopuses.", "Pigments are colors."],
    answer: 0,
    explanation: "Every detail explains how or why octopuses change color.",
  },
  {
    id: "ela-g6-43",
    subject: "ela",
    grade: "6",
    standard: "RI.6.4",
    skill: "Figurative meaning",
    prompt: "What does 'a monument to waste' suggest?",
    passage: "Critics called the new stadium 'a monument to waste,' noting that it cost twice its original budget.",
    choices: ["The stadium cost too much.", "The stadium is a museum.", "The stadium is beautiful.", "The stadium was cheap."],
    answer: 0,
    explanation: "Calling the stadium a monument to waste says it stands for spending too much money.",
  },
  {
    id: "ela-g6-44",
    subject: "ela",
    grade: "6",
    standard: "RI.6.8",
    skill: "Evaluating arguments",
    prompt: "Why is this argument weak?",
    passage: "Students should not have homework. My cousin says homework is boring. Also, everyone I know hates it.",
    choices: ["It relies on opinions, not evidence.", "It uses too many statistics.", "It is too long.", "It quotes experts."],
    answer: 0,
    explanation: "A cousin's feelings and 'everyone I know' are opinions, not evidence.",
  },
  {
    id: "ela-g6-45",
    subject: "ela",
    grade: "6",
    standard: "RI.6.6",
    skill: "Author's point of view",
    prompt: "What is the author's point of view?",
    passage: "Some say public libraries are outdated now that we have the internet. They are mistaken. Libraries offer free computers, quiet study space, and help from trained librarians. Our city should expand library hours, not cut them.",
    choices: ["Libraries deserve more support.", "Libraries are outdated.", "The internet should be free.", "Librarians work too much."],
    answer: 0,
    explanation: "The author says critics are mistaken and calls for longer library hours.",
  },
  {
    id: "ela-g6-46",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Context clues",
    prompt: "What does inseparable mean?",
    passage: "The two brothers were inseparable; wherever one went, the other was sure to follow.",
    choices: ["always together", "always fighting", "very different", "rarely seen"],
    answer: 0,
    explanation: "'Wherever one went, the other was sure to follow' shows they were always together.",
  },
  {
    id: "ela-g6-47",
    subject: "ela",
    grade: "6",
    standard: "RL.6.3",
    skill: "Character change",
    prompt: "How has Tasha changed?",
    passage: "At the start of the year, Tasha refused to speak in class. By spring, she was arguing passionately for a new recycling program at the student council meeting.",
    choices: ["She grew more confident.", "She became shy.", "She stopped caring.", "She left school."],
    answer: 0,
    explanation: "She went from refusing to speak to arguing passionately in front of a group.",
  },
  {
    id: "ela-g6-48",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "What effect does the word mob have?",
    passage: "The reporter described the protesters as a 'mob' rather than a 'crowd.'",
    choices: ["It makes the group seem unruly.", "It makes the group seem calm.", "It shows the group was small.", "It has no effect."],
    answer: 0,
    explanation: "Mob and crowd mean nearly the same thing, but mob suggests a wild, dangerous group.",
  },
];

export default questions;
