import type { Question } from "../../types";
// Kindergarten social studies — NC Standard Course of Study for Social Studies (adopted 2021). "The World Around Us": change over time and events (K.H.1.1, K.H.1.2, K.H.1),
// maps, globes, physical features and location words (K.G.1.1, K.G.1.2, K.G.1), rules, citizens and symbols (K.C&G.1.1, K.C&G.1), needs, wants, goods, services and jobs
// (K.E.1.1, K.E.1.2, K.E.1), families and cultural practices (K.B.1.1, K.B.1).
const questions: Question[] = [
  {
    id: "soc-gK-01",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "What do we use to find places?",
    choices: ["A map", "A spoon", "A clock", "A bed"],
    answer: 0,
    explanation: "A map is a drawing of a place seen from above. It helps us find where things are.",
    quick: true,
  },
  {
    id: "soc-gK-02",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "A globe is a round model of...",
    choices: ["Earth", "The moon", "The sun", "A ball game"],
    answer: 0,
    explanation: "A globe is shaped like a ball, just like Earth. It shows land and water.",
    quick: true,
  },
  {
    id: "soc-gK-03",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "On a map, blue often shows...",
    choices: ["Water", "Roads", "Trees", "Houses"],
    answer: 0,
    explanation: "Map makers usually color oceans, lakes and rivers blue.",
    quick: true,
  },
  {
    id: "soc-gK-04",
    subject: "social",
    grade: "K",
    standard: "K.G.1",
    skill: "Location words",
    prompt: "The cat is inside the box. The cat is ___ the box.",
    choices: ["In", "On top of", "Under", "Next to"],
    answer: 0,
    explanation: "Inside means in. Words like in, on, under and next to tell where things are.",
    quick: true,
  },
  {
    id: "soc-gK-05",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    prompt: "You were a baby. Now you are big! This shows...",
    choices: ["Change", "Weather", "Money", "A map"],
    answer: 0,
    explanation: "People change over time. You grow and learn new things every year.",
    quick: true,
  },
  {
    id: "soc-gK-06",
    subject: "social",
    grade: "K",
    standard: "K.H.1",
    skill: "Past and present",
    prompt: "Yesterday is in the...",
    choices: ["Past", "Future", "Present", "Weekend"],
    answer: 0,
    explanation: "The past is time that already happened. Yesterday is in the past.",
    quick: true,
  },
  {
    id: "soc-gK-07",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    prompt: "Long ago, people read by candlelight. Today we use...",
    choices: ["Lamps", "Rocks", "Fireflies", "Snow"],
    answer: 0,
    explanation: "Life changes over time. Now we have electric lamps to help us see at night.",
    quick: true,
  },
  {
    id: "soc-gK-08",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1.1",
    skill: "Rules",
    prompt: "Why do we have rules?",
    choices: ["To stay safe", "To be loud", "To get lost", "To be mean"],
    answer: 0,
    explanation: "Rules keep us safe and help everyone get along.",
    quick: true,
  },
  {
    id: "soc-gK-09",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1.1",
    skill: "Rules",
    prompt: "Who helps make rules at school?",
    choices: ["The principal", "A puppy", "The bus", "A tree"],
    answer: 0,
    explanation: "The principal and teachers help make school rules.",
    quick: true,
  },
  {
    id: "soc-gK-10",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Good citizens",
    prompt: "A good citizen...",
    choices: ["Shares", "Pushes", "Litters", "Grabs toys"],
    answer: 0,
    explanation: "Good citizens are kind, share, and help others.",
    quick: true,
  },
  {
    id: "soc-gK-11",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Symbols",
    prompt: "Which color is on the U.S. flag?",
    choices: ["Blue", "Green", "Purple", "Orange"],
    answer: 0,
    explanation: "The U.S. flag is red, white and blue. It has 50 stars and 13 stripes.",
    quick: true,
  },
  {
    id: "soc-gK-12",
    subject: "social",
    grade: "K",
    standard: "K.E.1.1",
    skill: "Needs and wants",
    prompt: "Which is a need?",
    choices: ["Food", "A toy car", "A game", "Candy"],
    answer: 0,
    explanation: "Needs are things we must have to live, like food, water and a home.",
    quick: true,
  },
  {
    id: "soc-gK-13",
    subject: "social",
    grade: "K",
    standard: "K.E.1.1",
    skill: "Needs and wants",
    prompt: "Which is a want?",
    choices: ["A toy", "Water", "Food", "Air"],
    answer: 0,
    explanation: "A want is nice to have, but we can live without it.",
    quick: true,
  },
  {
    id: "soc-gK-14",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Money",
    prompt: "We use money to...",
    choices: ["Buy things", "Grow hair", "Make rain", "Sleep"],
    answer: 0,
    explanation: "People trade money for the things they need and want.",
    quick: true,
  },
  {
    id: "soc-gK-15",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "Who helps sick people get well?",
    choices: ["A doctor", "A chef", "A pilot", "A farmer"],
    answer: 0,
    explanation: "Doctors and nurses are workers who help people stay healthy.",
    quick: true,
  },
  {
    id: "soc-gK-16",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "Who grows food for us to eat?",
    choices: ["A farmer", "A firefighter", "A mail carrier", "A dentist"],
    answer: 0,
    explanation: "Farmers grow fruits, vegetables and grains. Many North Carolina farmers grow sweet potatoes.",
    quick: true,
  },
  {
    id: "soc-gK-17",
    subject: "social",
    grade: "K",
    standard: "K.B.1.1",
    skill: "Families",
    prompt: "Which is a way families celebrate?",
    choices: ["A party", "A fire drill", "Homework", "A bath"],
    answer: 0,
    explanation: "Families celebrate special days in many ways, like parties, meals and songs.",
    quick: true,
  },
  {
    id: "soc-gK-18",
    subject: "social",
    grade: "K",
    standard: "K.B.1",
    skill: "Families",
    prompt: "Friends like different foods. Is that okay?",
    choices: ["Yes", "No", "Only on Monday", "Never"],
    answer: 0,
    explanation: "People are different in many ways, and that is okay. We can learn from each other.",
    quick: true,
  },
  {
    id: "soc-gK-19",
    subject: "social",
    grade: "K",
    standard: "K.G.1.2",
    skill: "Physical features",
    prompt: "A very big body of salty water is an...",
    choices: ["Ocean", "Hill", "Road", "Park"],
    answer: 0,
    explanation: "Oceans are the biggest bodies of water on Earth. Their water is salty.",
    quick: true,
  },
  {
    id: "soc-gK-20",
    subject: "social",
    grade: "K",
    standard: "K.G.1.2",
    skill: "Physical features",
    prompt: "Which one is a landform?",
    choices: ["Mountain", "River", "Lake", "Ocean"],
    answer: 0,
    explanation: "A landform is a shape of the land, like a mountain or a hill. Rivers, lakes and oceans are water.",
    quick: true,
  },
  {
    id: "soc-gK-21",
    subject: "social",
    grade: "K",
    standard: "K.G.1.2",
    skill: "Physical features",
    prompt: "Land with water all around it is an...",
    choices: ["Island", "Mountain", "Valley", "Desert"],
    answer: 0,
    explanation: "An island has water on every side. The Outer Banks of North Carolina are islands.",
    quick: true,
  },
  {
    id: "soc-gK-22",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "A small picture on a map that stands for a real thing is a...",
    choices: ["Symbol", "Clock", "Song", "Coin"],
    answer: 0,
    explanation: "Map symbols are little pictures. A tiny tree can stand for a park or a forest.",
    quick: true,
  },
  {
    id: "soc-gK-23",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "Our home planet is...",
    choices: ["Earth", "Mars", "The Moon", "The Sun"],
    answer: 0,
    explanation: "We live on planet Earth. Maps and globes show places on Earth.",
    quick: true,
  },
  {
    id: "soc-gK-24",
    subject: "social",
    grade: "K",
    standard: "K.G.1",
    skill: "Location words",
    prompt: "The bird is above the tree. The bird is ___ the tree.",
    choices: ["Over", "Under", "Inside", "Behind"],
    answer: 0,
    explanation: "Above and over mean higher than something. The bird is up over the tree.",
    quick: true,
  },
  {
    id: "soc-gK-25",
    subject: "social",
    grade: "K",
    standard: "K.G.1",
    skill: "Location words",
    prompt: "Words like left, right, near and far tell about...",
    choices: ["Location", "Time", "Age", "Weather"],
    answer: 0,
    explanation: "Location words tell where things are. 'The door is on your left' is a location.",
    quick: true,
  },
  {
    id: "soc-gK-26",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    prompt: "Things that will happen later are in the...",
    choices: ["Future", "Past", "Present", "Night"],
    answer: 0,
    explanation: "The future is time that has not happened yet, like tomorrow or next year.",
    quick: true,
  },
  {
    id: "soc-gK-27",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    prompt: "Long ago, children wrote on small slates. Today many write on...",
    choices: ["Paper", "Rocks", "Leaves", "Sand"],
    answer: 0,
    explanation: "School has changed over time. Children once wrote with chalk on slates. Now we use paper and computers.",
    quick: true,
  },
  {
    id: "soc-gK-28",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    prompt: "First a baby, next a child, then a...",
    choices: ["Grown-up", "Baby", "Puppy", "Seed"],
    answer: 0,
    explanation: "People grow and change over time. Babies grow into children, and children grow into grown-ups.",
    quick: true,
  },
  {
    id: "soc-gK-29",
    subject: "social",
    grade: "K",
    standard: "K.H.1.2",
    skill: "Holidays",
    prompt: "Martin Luther King Jr. Day honors a man who worked for...",
    choices: ["Fairness", "Sports", "Weather", "Money"],
    answer: 0,
    explanation: "Dr. King worked so that all people would be treated fairly. We remember him every January.",
    quick: true,
  },
  {
    id: "soc-gK-30",
    subject: "social",
    grade: "K",
    standard: "K.H.1.2",
    skill: "Holidays",
    prompt: "Thanksgiving is a day for giving...",
    choices: ["Thanks", "Homework", "Tickets", "Haircuts"],
    answer: 0,
    explanation: "On Thanksgiving, many families share a meal and say what they are thankful for.",
    quick: true,
  },
  {
    id: "soc-gK-31",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1.1",
    skill: "Rules",
    prompt: "Why do we raise our hands in class?",
    choices: ["To take turns", "To stretch", "To wave bye", "To be loud"],
    answer: 0,
    explanation: "Raising hands lets everyone take turns talking, so we can all be heard.",
    quick: true,
  },
  {
    id: "soc-gK-32",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1.1",
    skill: "Rules",
    prompt: "A red traffic light means...",
    choices: ["Stop", "Go", "Dance", "Run"],
    answer: 0,
    explanation: "Traffic rules keep us safe. Red means stop and green means go.",
    quick: true,
  },
  {
    id: "soc-gK-33",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1.1",
    skill: "Rules",
    prompt: "If you break a rule, there may be a...",
    choices: ["Consequence", "Party", "Prize", "Holiday"],
    answer: 0,
    explanation: "A consequence is what happens because of what you did. Rules have consequences so people follow them.",
    quick: true,
  },
  {
    id: "soc-gK-34",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Community helpers",
    prompt: "Who helps keep our community safe?",
    choices: ["Police officer", "Clown", "Baby", "Painter"],
    answer: 0,
    explanation: "Police officers, firefighters and other helpers work to keep our community safe.",
    quick: true,
  },
  {
    id: "soc-gK-35",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Symbols",
    prompt: "We say the Pledge of Allegiance to the...",
    choices: ["Flag", "Moon", "Bus", "Lunch"],
    answer: 0,
    explanation: "The Pledge of Allegiance is a promise to be loyal to the flag of the United States and our country.",
    quick: true,
  },
  {
    id: "soc-gK-36",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Symbols",
    prompt: "The bald eagle is a symbol of our...",
    choices: ["Country", "School", "Family", "Zoo"],
    answer: 0,
    explanation: "The bald eagle stands for the United States. It is strong and free.",
    quick: true,
  },
  {
    id: "soc-gK-37",
    subject: "social",
    grade: "K",
    standard: "K.E.1.2",
    skill: "Goods and services",
    prompt: "A dentist cleaning your teeth is a...",
    choices: ["Service", "Good", "Want", "Toy"],
    answer: 0,
    explanation: "A service is work someone does for you. A dentist gives a service.",
    quick: true,
  },
  {
    id: "soc-gK-38",
    subject: "social",
    grade: "K",
    standard: "K.E.1.2",
    skill: "Goods and services",
    prompt: "Which is a good you can hold?",
    choices: ["An apple", "A haircut", "A checkup", "A bus ride"],
    answer: 0,
    explanation: "Goods are things you can touch and hold, like an apple. A haircut is a service.",
    quick: true,
  },
  {
    id: "soc-gK-39",
    subject: "social",
    grade: "K",
    standard: "K.E.1.1",
    skill: "Needs and wants",
    prompt: "A home keeps us warm and dry. A home is a...",
    choices: ["Need", "Want", "Toy", "Game"],
    answer: 0,
    explanation: "A home, or shelter, is a need. People need shelter, food, water and clothes.",
    quick: true,
  },
  {
    id: "soc-gK-40",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "People work at jobs to earn...",
    choices: ["Money", "Toys", "Naps", "Snow"],
    answer: 0,
    explanation: "Workers earn money at their jobs. They use money to buy what they need and want.",
    quick: true,
  },
  {
    id: "soc-gK-41",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "Who brings letters to your home?",
    choices: ["Mail carrier", "Chef", "Doctor", "Pilot"],
    answer: 0,
    explanation: "A mail carrier delivers letters and packages to homes and businesses.",
    quick: true,
  },
  {
    id: "soc-gK-42",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Money",
    prompt: "Where can you keep money safe?",
    choices: ["A bank", "A trash can", "A sandbox", "A pond"],
    answer: 0,
    explanation: "A bank keeps money safe until you need it.",
    quick: true,
  },
  {
    id: "soc-gK-43",
    subject: "social",
    grade: "K",
    standard: "K.B.1.1",
    skill: "Culture",
    prompt: "People eat with forks, chopsticks or hands. This is part of their...",
    choices: ["Culture", "Weather", "Address", "Map"],
    answer: 0,
    explanation: "Culture is a group's way of life, including how people eat, talk and celebrate.",
    quick: true,
  },
  {
    id: "soc-gK-44",
    subject: "social",
    grade: "K",
    standard: "K.B.1.1",
    skill: "Languages",
    prompt: "'Hola' means hello in...",
    choices: ["Spanish", "French", "Japanese", "German"],
    answer: 0,
    explanation: "'Hola' is Spanish for hello. People around the world speak many languages.",
    quick: true,
  },
  {
    id: "soc-gK-45",
    subject: "social",
    grade: "K",
    standard: "K.B.1.1",
    skill: "Traditions",
    prompt: "A song your family sings every birthday is a...",
    choices: ["Tradition", "Rule", "Map", "Law"],
    answer: 0,
    explanation: "A tradition is something a family or group does again and again, like a birthday song.",
    quick: true,
  },
  {
    id: "soc-gK-46",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Picture maps",
    passage:
      "A picture map of a classroom shows a door, a teacher's desk, a rug and a bookshelf. The rug is next to the bookshelf. The desk is by the door.",
    prompt: "What is next to the rug?",
    choices: ["The bookshelf", "The door", "The desk", "The window"],
    answer: 0,
    explanation: "The map shows the rug next to the bookshelf. Maps help us see where things are.",
  },
  {
    id: "soc-gK-47",
    subject: "social",
    grade: "K",
    standard: "K.H.1.1",
    skill: "Past and present",
    passage:
      "Grandma went to a school with only one room. Children in all grades learned together. Today, each grade at your school has its own room.",
    prompt: "What changed?",
    choices: ["Schools have more rooms now", "Kids stopped learning", "Schools moved to the moon", "Nothing changed"],
    answer: 0,
    explanation: "Long ago, many schools had one room. Now most schools have a room for each grade.",
  },
  {
    id: "soc-gK-48",
    subject: "social",
    grade: "K",
    standard: "K.E.1.1",
    skill: "Needs and wants",
    passage:
      "Ben has money for only one thing. He needs a warm coat for winter. He wants a toy truck.",
    prompt: "What should Ben buy?",
    choices: ["The coat", "The truck", "Both", "Neither"],
    answer: 0,
    explanation: "Ben needs a coat to stay warm. Needs come before wants.",
  },
];

export default questions;
