/*
 * Cast sprites: every character in the roster as a 16-wide character grid (original art).
 * Faces are drawn on top by mood (face.ts), so each sprite says where its eyes and mouth are.
 * Pure data (no DOM): scripts/check-stories.ts checks every roster character has a sprite.
 */
import type { CharId } from "@/story/roster";

/** Shared colour keys (a sprite may override). */
export const KEYS: Record<string, string> = {
  K: "#000000",
  W: "#ffffff",
  w: "#aaaaaa",
  g: "#555555",
  q: "#33334a",
  S: "#f0b890",
  s: "#c68652",
  T: "#b87848",
  t: "#8a5a3c",
  R: "#e3262f",
  r: "#aa0000",
  B: "#2456e8",
  b: "#1a2a8a",
  L: "#6ea0ff",
  Y: "#ffd23f",
  y: "#aa7a00",
  N: "#aa5500",
  n: "#5a2e0e",
  A: "#c8a060",
  a: "#8a6a30",
  G: "#00aa00",
  H: "#55ff55",
  d: "#005500",
  C: "#55ffff",
  c: "#00aaaa",
  M: "#aa00aa",
  m: "#ff55ff",
  O: "#ff8a2a",
  P: "#55207a",
  p: "#8a50c0",
  V: "#7ff3ff",
  E: "#f5e6c8",
  z: "#5a3020",
  h: "#e3262f",
};

export interface Face {
  /** Left x of each eye, and the eye row. */
  ex: number[];
  ey: number;
  /** Eye size in pixels (default 1x1). */
  ew?: number;
  eh?: number;
  /** Colour key for the eye (default K). */
  eye?: string;
  /** Skin key under the face (used for blinks and to clear the mouth). */
  skin: string;
  /** Mouth: left x (2 px wide) and row; omit for beaks, visors and hoods. */
  mx?: number;
  my?: number;
  /** Mouth colour key (default z, a dark brown). */
  mc?: string;
  /** Eyelid colour key for blinks (default: the skin). */
  lid?: string;
  /** Big cartoon eyes: happy shows ^ ^ eyes. */
  big?: boolean;
}

export interface SpriteDef {
  rows: string[];
  /** Optional second frame (wings, tails, sheet hem). */
  alt?: string[];
  colors?: Record<string, string>;
  face?: Face;
  /** Pixels above the floor (flying/floating characters). */
  lift?: number;
  float?: boolean;
  /** Emote bubbles always shown (no readable face). */
  noFace?: boolean;
}

const pad = (rows: string[], n = 24) => [...Array(Math.max(0, n - rows.length)).fill("................"), ...rows];

export const SPRITES: Record<CharId, SpriteDef> = {
  // The arcade's hero (sprite HERO in the arcade menu), padded to 24 rows.
  hero: {
    rows: pad([
      "......hh........",
      "......hh........",
      "......BB........",
      "......BB........",
      ".....KRRRK......",
      "....KRRRRRK.....",
      "....KRRRRRK.....",
      "....KVVVVVK.....",
      "....KRRRRRK.....",
      ".....KRRRK......",
      "....BBRRRBB.....",
      "....BBYYYBBB....",
      "....BBBYBB.BB...",
      "....BBBBBB..hh..",
      ".....RRRRR......",
      ".....BBBBB......",
      ".....BB.BB......",
      "....BB...BB.....",
      "...hh.....hh....",
    ]),
    noFace: true,
  },

  quill: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..n..........n..",
      "..nN........Nn..",
      "..NNNNNNNNNNNN..",
      ".NNWWWWNNWWWWNN.",
      ".NWWWWWWWWWWWWN.",
      ".NWWWWWYYWWWWWN.",
      ".NNWWWWYYWWWWNN.",
      ".NNNNNNNYNNNNNN.",
      ".NNNEEEEEEEENNN.",
      "NNNEEnEEEEnEENNN",
      "NNNEEEEEEEEEENNN",
      "NNNEEEnEEnEEERRR",
      "NNNEEEEEEEEEERYR",
      ".NNNEEEnnEEENRRR",
      ".NNNNEEEEEENNNN.",
      "..NNNNNNNNNNNN..",
      "...NNNNNNNNNN...",
      "....YY....YY....",
      "...YYYY..YYYY...",
      "................",
    ],
    face: { ex: [4, 11], ey: 8, eh: 2, skin: "W", lid: "N", big: true },
  },

  kid: {
    rows: [
      "................",
      "................",
      "................",
      ".....KKKKKK.....",
      "....KKKKKKKK....",
      "....KTTTTTTK....",
      "....KTTTTTTK....",
      "....KTTTTTTK....",
      ".....TTTTTT.....",
      "......TTTT......",
      ".......tt.......",
      "....OOOOOOOO....",
      "...OOOOOOOOOO...",
      "...OOOOYYOOOO...",
      "...TOOYYYYOOT...",
      "...TOOOYYOOOT...",
      "...TOOOOOOOOT...",
      "....BBBBBBBB....",
      "....BBBBBBBB....",
      "....BBB..BBB....",
      "....BBB..BBB....",
      "....BBB..BBB....",
      "....WWW..WWW....",
      "...WWWW..WWWW...",
    ],
    face: { ex: [6, 9], ey: 6, skin: "T", mx: 7, my: 8 },
  },

  captain: {
    rows: [
      "................",
      "..KKK......KKK..",
      "..KKKKKKKKKKKK..",
      "...KKKKKKKKKK...",
      "..YYYYYYYYYYYY..",
      "....nSSSSSSn....",
      "....nSSSSSSn....",
      "....nSSSSSSn....",
      "....nSSSSSSn....",
      "....nnSSSSnn....",
      ".....n.ss.n.....",
      "....BBBWWBBB....",
      "...BBBBWWBBBB...",
      "..BBBYBWWBYBBB..",
      "..BBBBBWWBBBBB..",
      "..SBBYBBBBYBBS..",
      "...BBBBBBBBBB...",
      "...BBBKKYKKBB...",
      "...BBBBBBBBBB...",
      "....BBBBBBBB....",
      "....WW....WW....",
      "....WW....WW....",
      "....KK....KK....",
      "...KKK....KKK...",
    ],
    face: { ex: [6, 9], ey: 6, skin: "S", mx: 7, my: 8 },
  },

  parrot: {
    rows: [
      "................",
      "......RRRR......",
      ".....RRRRRR.....",
      ".....RWKRRRR....",
      ".....RWWRRYYy...",
      ".....RRRRRYy....",
      "....RRRRRRR.....",
      "...BBRRRRRRR....",
      "..BBYYRRRRRR....",
      ".BBYYGRRRRR.....",
      "BBYGG.RRRR......",
      "BBG....RBB......",
      ".......RBBB.....",
      "........BBB.....",
      ".........BB.....",
    ],
    alt: [
      "................",
      "......RRRR......",
      "BB...RRRRRR.....",
      "BBY..RWKRRRR....",
      ".BYG.RWWRRYYy...",
      "..BYGRRRRRYy....",
      "...BYRRRRRR.....",
      "....BRRRRRRR....",
      ".....RRRRRRR....",
      "......RRRRR.....",
      "......RRRR......",
      ".......RBB......",
      ".......RBBB.....",
      "........BBB.....",
      ".........BB.....",
    ],
    face: { ex: [7], ey: 3, skin: "R" },
    lift: 34,
  },

  robot: {
    rows: [
      ".......R........",
      ".......w........",
      ".......w........",
      "...wwwwwwwwww...",
      "...wggggggggw...",
      "...wgCCCCCCgw...",
      "...wgCCCCCCgw...",
      "...wgCCCCCCgw...",
      "...wgCCCCCCgw...",
      "...wggggggggw...",
      "...wwwwwwwwww...",
      ".....gggggg.....",
      "..wwwwwwwwwwww..",
      ".gwwBBwwRRwwwwg.",
      ".gwwBBwwRRwwwwg.",
      ".gwwwwwwwwwwwwg.",
      ".g.wwYYwwYYww.g.",
      ".w.wwwwwwwwww.w.",
      "...wwwwwwwwww...",
      "....gggggggg....",
      "...KKKKKKKKKK...",
      "...KwKwKwKwKK...",
      "...KKKKKKKKKK...",
      "................",
    ],
    face: { ex: [6, 9], ey: 6, skin: "C", mx: 7, my: 8, mc: "K" },
  },

  scientist: {
    rows: [
      "................",
      "..w..w...w..w...",
      "..wwwwwwwwwwww..",
      ".wwwwwwwwwwwwww.",
      "..wwSSSSSSSSww..",
      "...wSSSSSSSSw...",
      "....SCCKKCCS....",
      "....SSSSSSSS....",
      "....SSSSSSSS....",
      ".....SSSSSS.....",
      ".......ss.......",
      "....WWWGGWWW....",
      "...WWWWGGWWWW...",
      "...WWWWGGWWWW...",
      "..WWwWWGGWWwWW..",
      "..WW.WWGGWW.WW..",
      "..SW.WWWWWW.WS..",
      "....WWWWWWWW....",
      "....WWwwwwWW....",
      "....WWggggWW....",
      ".....gg..gg.....",
      ".....gg..gg.....",
      ".....KK..KK.....",
      "....KKK..KKK....",
    ],
    face: { ex: [5, 10], ey: 6, skin: "S", mx: 7, my: 8 },
  },

  detective: {
    rows: [
      "................",
      "................",
      ".....nnnnnn.....",
      ".....nnnnnn.....",
      "....nKKKKKKn....",
      "..nnnnnnnnnnnn..",
      ".....SSSSSS.....",
      ".....SSSSSS.....",
      ".....SSSSSS.....",
      ".....SSSSSS.....",
      "......SSSS......",
      "....AAAWWAAA....",
      "...AAAAWWAAAA...",
      "..AAAAAWWAAAAA..",
      "..AAAaAAAAaAAA..",
      "..AA.AAAAAA.AA..",
      "..SA.nnnnnn.AS..",
      "....AAAAAAAA....",
      "....AAAAAAAA....",
      "....AAA..AAA....",
      ".....gg..gg.....",
      ".....gg..gg.....",
      ".....KK..KK.....",
      "....KKK..KKK....",
    ],
    face: { ex: [6, 9], ey: 7, skin: "S", mx: 7, my: 9 },
  },

  guard: {
    rows: [
      "................",
      "................",
      ".....bbbbbb.....",
      "....bbbYYbbb....",
      "....bbbbbbbb....",
      "....KKKKKKKK....",
      ".....TTTTTT.....",
      ".....TTTTTT.....",
      ".....TTTTTT.....",
      ".....TTTTTT.....",
      "......TTTT......",
      "....bbbLLbbb....",
      "...bbbbLLbbbb...",
      "..bbYbbLLbbbbb..",
      "..bbbbbLLbbbbb..",
      "..bb.bbbbbb.bb..",
      "..Tb.KKKYKK.bT..",
      "....bbbbbbbb....",
      "....bbbbbbbb....",
      "....bbb..bbb....",
      "....bbb..bbb....",
      "....bbb..bbb....",
      "....KKK..KKK....",
      "...KKKK..KKKK...",
    ],
    face: { ex: [6, 9], ey: 7, skin: "T", mx: 7, my: 9 },
  },

  keeper: {
    rows: [
      "................",
      "................",
      "................",
      "......SSSS......",
      ".....SSSSSS.....",
      "....WSSSSSSW....",
      "....WSSSSSSW....",
      "....WSSSSSSW....",
      "....WWSSSSWW....",
      ".....WWWWWW.....",
      "......WWWW......",
      "....GGGWWGGG....",
      "...GGGGGGGGGG...",
      "..GGGGGGGGGGGG..",
      "..GGdGGGGGGdGG..",
      "..GG.GGGGGG.GG..",
      "..SG.GGGGGG.GS..",
      "....nnnnnnnn.K..",
      "....nnnnnnnnKYK.",
      "....nnn..nnnKYK.",
      "....nnn..nnn.K..",
      "....nnn..nnn....",
      "....KKK..KKK....",
      "...KKKK..KKKK...",
    ],
    face: { ex: [6, 9], ey: 6, skin: "S", mx: 7, my: 8 },
  },

  ghost: {
    rows: pad([
      "......WWWW......",
      "....WWWWWWWW....",
      "...WWWWWWWWWW...",
      "...WWWWWWWWWW...",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      ".WWWWWWWWWWWWWW.",
      "WWwWWWWWWWWWWwWW",
      "WwWWWWWWWWWWWWwW",
      ".WWWWWWWWWWWWWW.",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWWw.",
      "..wWWWWWWWWWWWw.",
      "..wWWWWWWWWWWww.",
      "..wWW.wWWw.wWw..",
      "..w.....w....w..",
    ], 20),
    alt: pad([
      "......WWWW......",
      "....WWWWWWWW....",
      "...WWWWWWWWWW...",
      "...WWWWWWWWWW...",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      ".WWWWWWWWWWWWWW.",
      "WWwWWWWWWWWWWwWW",
      "WwWWWWWWWWWWWWwW",
      ".WWWWWWWWWWWWWW.",
      "..WWWWWWWWWWWW..",
      "..wWWWWWWWWWWWW.",
      "..wWWWWWWWWWWWw.",
      "..wwWWWWWWWWWWw.",
      "...wWWw.wWWw.ww.",
      "....w....w....w.",
    ], 20),
    face: { ex: [5, 10], ey: 6, eh: 2, skin: "W", mx: 7, my: 9, mc: "K" },
    lift: 8,
    float: true,
  },

  dragon: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....y......y....",
      "....yG....Gy....",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "...GGGEEEEGGG...",
      "....GGEEEEGG....",
      ".....GGGGGG.....",
      "d..dGGYYYYGGd..d",
      "dd.dGGYYYYGGd.dd",
      "dddGGGYYYYGGGddd",
      ".ddGGGYYYYGGGdd.",
      "..dGGGYYYYGGGd..",
      "....GGYYYYGG....",
      "....GGGGGGGG..GG",
      "....GG....GG.GG.",
      "....GG....GGGG..",
      "...yyy....yyy...",
      "................",
    ],
    alt: [
      "................",
      "................",
      "................",
      "................",
      "....y......y....",
      "....yG....Gy....",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "...GGGGGGGGGG...",
      "...GGGEEEEGGG...",
      "d...GGEEEEGG...d",
      "dd...GGGGGG...dd",
      "ddd.dGYYYYGd.ddd",
      ".ddddGYYYYGdddd.",
      "..ddGGYYYYGGdd..",
      "...GGGYYYYGGG...",
      "...GGGYYYYGGG...",
      "....GGYYYYGG....",
      "....GGGGGGGG..GG",
      "....GG....GG.GG.",
      "....GG....GGGG..",
      "...yyy....yyy...",
      "................",
    ],
    face: { ex: [5, 10], ey: 8, skin: "G", mx: 7, my: 11, mc: "K" },
  },

  knight: {
    rows: [
      "........RR......",
      ".......RRR......",
      "......RRw.......",
      ".....wwwwww.....",
      "....wwwwwwww....",
      "....wWWwwwww....",
      "....wKKKKKKw....",
      "....wwwKwwww....",
      "....wwwKwwww....",
      ".....wwwwww.....",
      "......gggg......",
      "....wwwwwwww....",
      "...wwWwwwwwww...",
      ".RRRRwwwwwwwww..",
      ".RYYRwwRRwwwww..",
      ".RYYRwwRRwwwgw..",
      ".RRRRwwwwwwwgw..",
      "..RR.gggggg.gw..",
      "....wwwwwwww.w..",
      "....www..www....",
      "....www..www....",
      "....www..www....",
      "....ggg..ggg....",
      "...gggg..gggg...",
    ],
    noFace: true,
  },

  mayor: {
    rows: [
      ".....qqqqqq.....",
      ".....qqqqqq.....",
      ".....qqqqqq.....",
      ".....RRRRRR.....",
      "...qqqqqqqqqq...",
      ".....SSSSSS.....",
      ".....SSSSSS.....",
      ".....SSSSSS.....",
      ".....wwwwww.....",
      ".....SSSSSS.....",
      "......SSSS......",
      "....qqqWWqqq....",
      "...qqqRWWqqqq...",
      "..qqqqqRWqqqqq..",
      "..qqqqqqRYqqqq..",
      "..qq.qqqqRqq.qq.",
      "..Sq.qqqqqRq.qS.",
      "....qqqqqqqq....",
      "....qqqqqqqq....",
      "....ggg..ggg....",
      "....ggg..ggg....",
      "....ggg..ggg....",
      "....KKK..KKK....",
      "...KKKK..KKKK...",
    ],
    face: { ex: [6, 9], ey: 6, skin: "S", mx: 7, my: 9 },
  },

  cat: {
    rows: pad([
      "...O......O.....",
      "...OO....OO.....",
      "...OOOOOOOO.....",
      "..OOOOOOOOOO....",
      "..OONOOOONOO....",
      "...OOOmmOOO.....",
      "....OOOOOO......",
      "...OOEEEEOO.....",
      "..OOOEEEEOOO..O.",
      "..ONOEEEEONO.OO.",
      "..OOOEEEEOOOOO..",
      "...WW.OOO.WW....",
    ]),
    alt: pad([
      "...O......O.....",
      "...OO....OO.....",
      "...OOOOOOOO.....",
      "..OOOOOOOOOO....",
      "..OONOOOONOO....",
      "...OOOmmOOO.....",
      "....OOOOOO......",
      "...OOEEEEOO...O.",
      "..OOOEEEEOOO..O.",
      "..ONOEEEEONO.OO.",
      "..OOOEEEEOOOOO..",
      "...WW.OOO.WW....",
    ]),
    face: { ex: [4, 9], ey: 16, skin: "O", mx: 6, my: 18, mc: "K" },
  },

  stranger: {
    rows: [
      "................",
      "................",
      "......PPPP......",
      ".....PPPPPP.....",
      "....PPPPPPPP....",
      "....PPKKKKPP....",
      "...PPKKKKKKPP...",
      "...PPKKKKKKPP...",
      "...PPKKKKKKPP...",
      "...PPPKKKKPPP...",
      "...PPPPPPPPPP...",
      "..PPPPPPPPPPPP..",
      "..PPPpPPPPpPPP..",
      "..PPPpPPPPpPPP..",
      "..PPPPPPPPPPPP..",
      ".PPPPPpPPpPPPPP.",
      ".PPPPPpPPpPPPPP.",
      ".PPPPPPPPPPPPPP.",
      ".PPPPPpPPpPPPPP.",
      ".PPPPPpPPpPPPPP.",
      "PPPPPPPPPPPPPPPP",
      "PPPPPPPPPPPPPPPP",
      ".pPpPpPpPpPpPpP.",
      "....KK....KK....",
    ],
    face: { ex: [6, 9], ey: 7, eye: "Y", skin: "K" },
  },

  alien: {
    rows: [
      "....H......H....",
      "....m......m....",
      ".....H....H.....",
      "....HHHHHHHH....",
      "...HHHHHHHHHH...",
      "..HHHHHHHHHHHH..",
      "..HHHHHHHHHHHH..",
      "..HHHHHHHHHHHH..",
      "..HHHHHHHHHHHH..",
      "...HHHHHHHHHH...",
      "....HHHHHHHH....",
      "......HHHH......",
      "....pppppppp....",
      "...pppppppppp...",
      "..Hpp.pYYp.ppH..",
      "..H.pppppppp.H..",
      "....pppppppp....",
      "....pppppppp....",
      "....ppp..ppp....",
      "....ppp..ppp....",
      "....ppp..ppp....",
      "....KKK..KKK....",
      "...KKKK..KKKK...",
      "................",
    ],
    face: { ex: [4, 10], ey: 6, ew: 2, eh: 2, skin: "H", mx: 7, my: 9, mc: "d", big: true },
  },
};
