/*
 * Grades 9-12 (English I-IV): advanced roots and affixes, building academic words,
 * and commonly misspelled words.
 *   L.9-10.4 / L.11-12.4 vocabulary: patterns of word changes; roots and affixes
 *   L.9-10.2 / L.11-12.2 conventions continuum: spell correctly
 */
import { build, finish, part, spell } from "../worm/challenges";

const ROOT = "Greek and Latin roots";
const SPELL = "Commonly misspelled words";

export const grade9 = finish("9", [
  part("L.9-10.4", ROOT, "CORP", "CAP PED MORT", 'Shoot the root that means "body"', "CORPORATION"),
  part("L.9-10.4", ROOT, "MORT", "VIT CORP FID", 'Shoot the root that means "death"', "MORTALITY"),
  part("L.9-10.4", ROOT, "VIV", "MORT CORP DUC", 'Shoot the root that means "life"', "SURVIVE"),
  part("L.9-10.4", ROOT, "GEN", "MORT CIDE VOC", 'Shoot the root that means "birth" or "kind"', "GENERATION"),
  part("L.9-10.4", ROOT, "CIDE", "GEN VIV CAP", 'Shoot the root that means "kill"', "PESTICIDE"),
  part("L.9-10.4", ROOT, "CAP", "PED CORP MANU", 'Shoot the root that means "head"', "CAPTAIN"),
  part("L.9-10.4", ROOT, "FLECT", "JECT TRACT DUC", 'Shoot the root that means "bend"', "DEFLECT"),
  part("L.9-10.4", ROOT, "TRACT", "FLECT JECT SCRIB", 'Shoot the root that means "pull" or "drag"', "TRACTOR"),
  part("L.9-10.4", ROOT, "GRAD", "TRACT FLECT VOC", 'Shoot the root that means "step"', "UPGRADE"),
  part("L.9-10.4", ROOT, "SOMN", "MORT LOQU VIV", 'Shoot the root that means "sleep"', "SOMNOLENT"),
  build("L.9-10.4", "IN SOMN IA", "INSOMNIA", "HYPO ISM", "a condition of not being able to sleep"),
  build("L.9-10.4", "RE FLECT ION", "REFLECTION", "DE IN", "an image bent back to you by a mirror"),
  build("L.9-10.4", "MORT AL", "MORTAL", "IM VIT", "certain to die someday"),
  build("L.9-10.4", "DIS TRACT ION", "DISTRACTION", "AT CON", "something that pulls your attention away"),
  build("L.9-10.4", "VIV ID", "VIVID", "MORT IFY", "full of life; bright and strong"),
  build("L.9-10.4", "GRAD UAL", "GRADUAL", "TRACT ENT", "happening step by step"),
  build("L.9-10.4", "IN CORP ORATE", "INCORPORATE", "EX CAP", "to take something in as part of a body or whole"),
  build("L.9-10.4", "PRO CRASTIN ATE", "PROCRASTINATE", "PRE ION", "to put off doing something until later"),
  spell("L.9-10.2", SPELL, "AC COM MO DATE", "ACCOMMODATE", "A OM", { clue: "to make room for; to provide what someone needs", tip: "It is big enough to hold two C's and two M's." }),
  spell("L.9-10.2", SPELL, "RHY THM", "RHYTHM", "RY THUM", { clue: "a strong, regular, repeated pattern of sound or movement", tip: "Rhythm Helps Your Two Hips Move." }),
  spell("L.9-10.2", SPELL, "EN VIRON MENT", "ENVIRONMENT", "VIRO MANT", { clue: "the natural world around us", tip: "Don't forget the N in ENVIRON." }),
  spell("L.9-10.2", SPELL, "GOV ERN MENT", "GOVERNMENT", "ER MANT", { clue: "the group of people who run a country or state", tip: "GOVERN + MENT keeps the N." }),
  spell("L.9-10.2", SPELL, "MAIN TEN ANCE", "MAINTENANCE", "TAIN ENCE", { clue: "the work of keeping something in good condition", tip: "MAINTAIN changes to MAINTEN-ANCE." }),
  spell("L.9-10.2", SPELL, "PRIV I LEGE", "PRIVILEGE", "E LEDGE", { clue: "a special right or advantage", tip: "No D in PRIVILEGE." }),
  spell("L.9-10.2", SPELL, "OC CA SION", "OCCASION", "CC SSION", { clue: "a special event or time", tip: "Two C's, one S." }),
  spell("L.9-10.2", SPELL, "EX AGG ER ATE", "EXAGGERATE", "AG IR", { clue: "to make something seem bigger than it really is", tip: "Double G, like a baGGy exaggeration." }),
]);

export const grade10 = finish("10", [
  part("L.9-10.4", ROOT, "LOQU", "SCRIB FLECT PATH", 'Shoot the root that means "speak"', "ELOQUENT"),
  part("L.9-10.4", ROOT, "SOPH", "PHIL LOG THEO", 'Shoot the root that means "wisdom"', "SOPHISTICATED"),
  part("L.9-10.4", ROOT, "PSEUDO", "NEO PROTO HOMO", 'Shoot the prefix that means "false"', "PSEUDOSCIENCE"),
  part("L.9-10.4", ROOT, "NEO", "PALEO PSEUDO RETRO", 'Shoot the prefix that means "new"', "NEONATAL"),
  part("L.9-10.4", ROOT, "PROTO", "NEO PSEUDO RETRO", 'Shoot the prefix that means "first"', "PROTOTYPE"),
  part("L.9-10.4", ROOT, "RETRO", "PROTO NEO PRO", 'Shoot the prefix that means "backward"', "RETROACTIVE"),
  part("L.9-10.4", ROOT, "EQU", "AMBI DYS POLY", 'Shoot the root that means "equal"', "EQUATION"),
  part("L.9-10.4", ROOT, "AMBI", "EQU OMNI MONO", 'Shoot the prefix that means "both"', "AMBIVALENT"),
  part("L.9-10.4", ROOT, "OMNI", "AMBI MONO NEO", 'Shoot the prefix that means "all"', "OMNIPRESENT"),
  part("L.9-10.4", ROOT, "DYS", "EU AMBI OMNI", 'Shoot the prefix that means "bad" or "difficult"', "DYSLEXIA"),
  build("L.9-10.4", "PSEUDO NYM", "PSEUDONYM", "SYN ANT", "a false name used by an author"),
  build("L.9-10.4", "LOQU ACIOUS", "LOQUACIOUS", "VIV AUD", "very talkative"),
  build("L.9-10.4", "OMNI VORE", "OMNIVORE", "HERBI CARNI", "an animal that eats all kinds of food"),
  build("L.9-10.4", "AMBI DEXTR OUS", "AMBIDEXTROUS", "EQUI IOUS", "able to use both hands equally well"),
  build("L.9-10.4", "DYS FUNCTION AL", "DYSFUNCTIONAL", "EU ISM", "not working normally"),
  build("L.9-10.4", "RETRO SPECT IVE", "RETROSPECTIVE", "PRO INTRO", "looking back on the past"),
  build("L.9-10.4", "NEO LOGISM", "NEOLOGISM", "PALEO GRAM", "a newly made-up word"),
  build("L.9-10.4", "EQUI LIBRIUM", "EQUILIBRIUM", "OMNI ARIUM", "a state of balance between equal forces"),
  spell("L.9-10.2", SPELL, "CON SCIEN TIOUS", "CONSCIENTIOUS", "SCEN CIOUS", { clue: "careful and wanting to do work well", tip: "It holds SCIENCE's cousin: SCIEN + TIOUS." }),
  spell("L.9-10.2", SPELL, "LI AI SON", "LIAISON", "A AS", { clue: "a person who helps two groups communicate", tip: "Two I's: one on each side of the A." }),
  spell("L.9-10.2", SPELL, "PER SEV ER ANCE", "PERSEVERANCE", "ERE ENCE", { clue: "continuing to try even when it is hard", tip: "PERSEVERE drops its last E before ANCE." }),
  spell("L.9-10.2", SPELL, "MIL LEN NI UM", "MILLENNIUM", "I LE", { clue: "a period of one thousand years", tip: "Double L and double N." }),
  spell("L.9-10.2", SPELL, "CEM E TER Y", "CEMETERY", "A TARY", { clue: "a place where people are buried", tip: "Three E's and no A." }),
  spell("L.9-10.2", SPELL, "HAR ASS", "HARASS", "HARR AS", { clue: "to keep bothering or pressuring someone", tip: "One R, two S's." }),
  spell("L.9-10.2", SPELL, "PRO NUN CI A TION", "PRONUNCIATION", "NOUN SI", { clue: "the way a word is said out loud", tip: "PRONOUNCE loses its O: pro-NUN-ciation." }),
  spell("L.9-10.2", SPELL, "IR RES IST IBLE", "IRRESISTIBLE", "I ABLE", { clue: "too tempting or strong to say no to", tip: "Double R, and it ends in IBLE." }),
]);

export const grade11 = finish("11", [
  part("L.11-12.4", ROOT, "CRYPT", "PHAN LUC NYM", 'Shoot the root that means "hidden"', "ENCRYPT"),
  part("L.11-12.4", ROOT, "LUC", "NOCT CRYPT TEMP", 'Shoot the root that means "light"', "TRANSLUCENT"),
  part("L.11-12.4", ROOT, "NOCT", "LUC TEMP CHRON", 'Shoot the root that means "night"', "NOCTURNE"),
  part("L.11-12.4", ROOT, "TEMP", "NOCT LUC LOC", 'Shoot the root that means "time"', "TEMPORARY"),
  part("L.11-12.4", ROOT, "LOC", "TEMP LUC ERR", 'Shoot the root that means "place"', "LOCATION"),
  part("L.11-12.4", ROOT, "ERR", "LOC NOCT CRYPT", 'Shoot the root that means "wander"', "ERROR"),
  part("L.11-12.4", ROOT, "PLAC", "BELL LOQU CRYPT", 'Shoot the root that means "please" or "calm"', "PLACID"),
  part("L.11-12.4", ROOT, "BELL", "PAC PLAC LUC", 'Shoot the root that means "war"', "REBELLION"),
  part("L.11-12.4", ROOT, "PAC", "BELL CRYPT ERR", 'Shoot the root that means "peace"', "PACIFIC"),
  part("L.11-12.4", ROOT, "AMBUL", "BELL LOC NOCT", 'Shoot the root that means "walk"', "AMBULANCE"),
  build("L.11-12.4", "CRYPT IC", "CRYPTIC", "LUC OUS", "having a hidden or mysterious meaning"),
  build("L.11-12.4", "NOCT URNAL", "NOCTURNAL", "DI LUC", "active at night"),
  build("L.11-12.4", "BELL IGERENT", "BELLIGERENT", "PAC PLAC", "eager to fight; hostile"),
  build("L.11-12.4", "PLAC ATE", "PLACATE", "BELL ID", "to calm someone down by pleasing them"),
  build("L.11-12.4", "LUC ID", "LUCID", "PLAC TEMP", "clear and easy to understand"),
  build("L.11-12.4", "ERR ATIC", "ERRATIC", "LOC IC", "moving in an irregular, unpredictable way"),
  build("L.11-12.4", "CON TEMP ORARY", "CONTEMPORARY", "EX LOC", "living or happening at the same time"),
  build("L.11-12.4", "PAC IFY", "PACIFY", "BELL ISM", "to make peaceful or calm"),
  spell("L.11-12.2", SPELL, "CON SEN SUS", "CONSENSUS", "CEN CUS", { clue: "general agreement among a group", tip: "It comes from CONSENT: all S's, no C after CON." }),
  spell("L.11-12.2", SPELL, "SUP ER SEDE", "SUPERSEDE", "CEDE UR", { clue: "to take the place of something older", tip: "The only English word ending in SEDE." }),
  spell("L.11-12.2", SPELL, "IN OC U LATE", "INOCULATE", "NOC OCC", { clue: "to protect against a disease with a vaccine", tip: "One N, one C." }),
  spell("L.11-12.2", SPELL, "MIN US CULE", "MINUSCULE", "IS KULE", { clue: "extremely small", tip: "Think MINUS: MINUS-CULE." }),
  spell("L.11-12.2", SPELL, "PRE ROG A TIVE", "PREROGATIVE", "PER I", { clue: "a special right that belongs to a person or group", tip: "It starts with PRE, not PER." }),
  spell("L.11-12.2", SPELL, "HIER AR CHY", "HIERARCHY", "HEIR KY", { clue: "a ranking of people or things from highest to lowest", tip: "HIER, then ARCHY (rule)." }),
  spell("L.11-12.2", SPELL, "COM MIT MENT", "COMMITMENT", "MITT MANT", { clue: "a promise to do something", tip: "Double M, single T." }),
  spell("L.11-12.2", SPELL, "OC CUR RENCE", "OCCURRENCE", "O RANCE", { clue: "something that happens; an event", tip: "Double C, double R, and ENCE." }),
]);

export const grade12 = finish("12", [
  part("L.11-12.4", ROOT, "CRAT", "PHIL MORPH NYM", 'Shoot the root that means "rule"', "DEMOCRAT"),
  part("L.11-12.4", ROOT, "VERT", "JECT TRACT DUC", 'Shoot the root that means "turn"', "INVERT"),
  part("L.11-12.4", ROOT, "MIT", "VERT DUC CRED", 'Shoot the root that means "send"', "TRANSMIT"),
  part("L.11-12.4", ROOT, "FLU", "FLECT VERT TRACT", 'Shoot the root that means "flow"', "FLUID"),
  part("L.11-12.4", ROOT, "FER", "MIT VERT JECT", 'Shoot the root that means "carry"', "TRANSFER"),
  part("L.11-12.4", ROOT, "ACR", "MAL VERT FLU", 'Shoot the root that means "sharp"', "ACRID"),
  part("L.11-12.4", ROOT, "PSYCH", "CORP THEO CHROM", 'Shoot the root that means "mind"', "PSYCHIC"),
  part("L.11-12.4", ROOT, "SON", "LUC FLU MIT", 'Shoot the root that means "sound"', "SONAR"),
  part("L.11-12.4", ROOT, "VERB", "MORPH CORP FLU", 'Shoot the root that means "word"', "VERBAL"),
  part("L.11-12.4", ROOT, "VOR", "CIDE FLU MIT", 'Shoot the root that means "eat"', "VORACIOUS"),
  build("L.11-12.4", "AUTO CRACY", "AUTOCRACY", "DEMO THEO", "rule by one person with total power"),
  build("L.11-12.4", "IN TRO VERT", "INTROVERT", "EX DUC", "a person who turns inward; quiet and reflective"),
  build("L.11-12.4", "AF FLU ENT", "AFFLUENT", "IN ENCE", "wealthy; having money flowing in"),
  build("L.11-12.4", "SON IC", "SONIC", "LUC FLU", "relating to sound"),
  build("L.11-12.4", "CARNI VOR OUS", "CARNIVOROUS", "HERBI OMNI", "meat-eating"),
  build("L.11-12.4", "PSYCH OLOGY", "PSYCHOLOGY", "SOCI THEO", "the study of the mind and behavior"),
  build("L.11-12.4", "E MIT", "EMIT", "AD O", "to send out light, sound or heat"),
  build("L.11-12.4", "CON FER", "CONFER", "IN RE", "to discuss and exchange opinions"),
  build("L.11-12.4", "VERB OSE", "VERBOSE", "VOC AL", "using more words than needed"),
  spell("L.11-12.2", SPELL, "CON NOIS SEUR", "CONNOISSEUR", "NOI SUER", { clue: "an expert judge of taste, such as in food or art", tip: "Double N, double S, and EUR at the end." }),
  spell("L.11-12.2", SPELL, "MNE MON IC", "MNEMONIC", "NE ICK", { clue: "a trick that helps you remember something", tip: "The M is silent." }),
  spell("L.11-12.2", SPELL, "BUR EAU CRA CY", "BUREAUCRACY", "RO SY", { clue: "a system of government with many offices and rules", tip: "BUREAU + CRACY (rule)." }),
  spell("L.11-12.2", SPELL, "QUES TION NAIRE", "QUESTIONNAIRE", "NAIR NNAIRE", { clue: "a written set of questions for gathering information", tip: "Double N, and it ends with AIRE." }),
  spell("L.11-12.2", SPELL, "PAR AL LEL", "PARALLEL", "PARR ELL", { clue: "running side by side and never meeting, like train tracks", tip: "The double L in the middle looks like two parallel lines." }),
  spell("L.11-12.2", SPELL, "RES TAU RA TEUR", "RESTAURATEUR", "RAN TUER", { clue: "a person who owns and runs a restaurant", tip: "There is no N in RESTAURATEUR." }),
  spell("L.11-12.2", SPELL, "PRE CED ENCE", "PRECEDENCE", "SED ANCE", { clue: "the condition of coming first in importance", tip: "From PRECEDE: PRE + CEDE." }),
  spell("L.11-12.2", SPELL, "DI LEM MA", "DILEMMA", "NA MNA", { clue: "a hard choice between two options", tip: "Double M, no N." }),
]);
