import type { Question } from "../../types";
// Grade 10 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Founding Principles of the United States of America and North Carolina: Civic Literacy.
// Founding documents and principles (CL.C&G.1), federal, state and local branches (CL.C&G.2), citizen rights and responsibilities (CL.C&G.3), Articles of Confederation (CL.H.1), school funding (CL.E.1).
const questions: Question[] = [
  {
    id: "soc-g10-01",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Founding documents",
    prompt: "The Declaration of Independence was adopted in...",
    choices: ["1776", "1787", "1791", "1789"],
    answer: 0,
    explanation: "Congress adopted it on July 4, 1776. The Constitution was written in 1787.",
    quick: true,
  },
  {
    id: "soc-g10-02",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Founding principles",
    prompt: "Popular sovereignty means government power comes from...",
    choices: ["The people", "The king", "The courts", "The military"],
    answer: 0,
    explanation: "The Constitution begins 'We the People' because the people are the source of power.",
    quick: true,
  },
  {
    id: "soc-g10-03",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Bill of Rights",
    prompt: "The first ten amendments are called the...",
    choices: ["Bill of Rights", "Preamble", "Articles", "Federalist"],
    answer: 0,
    explanation: "The Bill of Rights was ratified in 1791 to protect individual liberties.",
    quick: true,
  },
  {
    id: "soc-g10-04",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Rule of law",
    prompt: "Rule of law means everyone, including leaders, must...",
    choices: ["Obey the law", "Own land", "Hold office", "Join a party"],
    answer: 0,
    explanation: "No person is above the law, including government officials.",
    quick: true,
  },
  {
    id: "soc-g10-05",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Congress",
    prompt: "How many U.S. senators does each state have?",
    choices: ["2", "1", "4", "Based on size"],
    answer: 0,
    explanation: "Every state has two senators. House seats are based on population.",
    quick: true,
  },
  {
    id: "soc-g10-06",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Checks and balances",
    prompt: "The President can reject a bill passed by Congress with a...",
    choices: ["Veto", "Filibuster", "Recall", "Pardon"],
    answer: 0,
    explanation: "A veto sends the bill back to Congress.",
    quick: true,
  },
  {
    id: "soc-g10-07",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Checks and balances",
    prompt: "Congress can override a veto with a vote in each house of...",
    choices: ["Two-thirds", "One-half", "Three-fourths", "All members"],
    answer: 0,
    explanation: "A two-thirds vote in both the House and Senate overrides a veto.",
    quick: true,
  },
  {
    id: "soc-g10-08",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "NC courts",
    prompt: "What is North Carolina's highest state court?",
    choices: ["Supreme Court", "Superior Court", "District Court", "Magistrate"],
    answer: 0,
    explanation: "The NC Supreme Court has seven justices, elected by voters, who hear appeals.",
    quick: true,
  },
  {
    id: "soc-g10-09",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Local government",
    prompt: "NC counties are governed by a board of...",
    choices: ["Commissioners", "Senators", "Justices", "Governors"],
    answer: 0,
    explanation: "Each of NC's 100 counties elects a board of county commissioners.",
    quick: true,
  },
  {
    id: "soc-g10-10",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Judicial review",
    prompt: "Marbury v. Madison (1803) set up the Supreme Court's power of judicial...",
    choices: ["Review", "Veto", "Recall", "Appointment"],
    answer: 0,
    explanation: "Judicial review lets courts strike down laws that conflict with the Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-11",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "Voting",
    prompt: "The 26th Amendment (1971) set the voting age at...",
    choices: ["18", "16", "21", "25"],
    answer: 0,
    explanation: "The 26th Amendment lowered the voting age from 21 to 18.",
    quick: true,
  },
  {
    id: "soc-g10-12",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "Citizen responsibilities",
    prompt: "Serving on a jury is a responsibility of...",
    choices: ["Citizens", "Tourists", "Only lawyers", "Only judges"],
    answer: 0,
    explanation: "Juries are made of ordinary citizens, which protects the right to a fair trial.",
    quick: true,
  },
  {
    id: "soc-g10-13",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Ratification",
    prompt: "The Federalist Papers argued for ratifying the...",
    choices: ["Constitution", "Articles", "Declaration", "Magna Carta"],
    answer: 0,
    explanation: "Hamilton, Madison and Jay wrote 85 essays supporting the new Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-14",
    subject: "social",
    grade: "10",
    standard: "CL.H.1",
    skill: "Articles of Confederation",
    prompt: "Under the Articles of Confederation, Congress could not...",
    choices: ["Collect taxes", "Make treaties", "Declare war", "Hold meetings"],
    answer: 0,
    explanation: "Without power to tax, the national government could not pay its debts, leading to the Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-15",
    subject: "social",
    grade: "10",
    standard: "CL.E.1",
    skill: "Public finance",
    prompt: "Which level of government provides the largest share of NC public school funding?",
    choices: ["State", "Federal", "City", "Private"],
    answer: 0,
    explanation: "NC's state government pays most school costs, like teacher salaries. Counties and the federal government add more.",
    quick: true,
  },
  {
    id: "soc-g10-16",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "Civic participation",
    passage:
      "Luis thinks the street by his school needs a crosswalk. The street is run by his town. The town council holds public meetings twice a month where residents may speak.",
    prompt: "What is Luis's best first step?",
    choices: ["Speak at a town council meeting", "Paint his own crosswalk", "Write to the U.S. Supreme Court", "Ask the President"],
    answer: 0,
    explanation: "Traffic signs on town streets are handled by local government, so the town council is the right place to start.",
  },
  {
    id: "soc-g10-17",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "First Amendment",
    passage:
      "A local newspaper prints an article criticizing the mayor's budget. The mayor asks the police to shut down the paper.",
    prompt: "Which right protects the newspaper?",
    choices: ["Freedom of the press", "Right to bear arms", "Right to a jury", "Freedom from quartering"],
    answer: 0,
    explanation: "The 1st Amendment bars government from punishing the press for criticizing officials.",
  },
  {
    id: "soc-g10-18",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Preamble",
    passage:
      "The Preamble: 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty...'",
    prompt: "Which phrase is about keeping peace at home?",
    choices: ["Insure domestic tranquility", "Provide for the common defence", "Promote the general welfare", "Secure the blessings of liberty"],
    answer: 0,
    explanation: "'Domestic tranquility' means peace within the country. Common defence is about outside threats.",
  },
];

export default questions;
