import type { Question } from "../../types";
// Grade 5 social studies — NC Standard Course of Study for Social Studies (adopted 2021). The United States: regions, migration and technology (5.G.1.1–5.G.1.4);
// three branches and checks and balances (5.C&G.1.1–1.2); rights and civic participation (5.C&G.2.1–2.2); identity and the arts (5.B.1.1); revolution, conflict, innovators,
// primary sources (5.H.1.1, 5.H.1.3–1.5); economic growth and budgeting (5.E.1.1, 5.E.1.3, 5.E.2.2).
const questions: Question[] = [
  {
    id: "soc-g5-01",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "Which U.S. region is known for farms growing corn and wheat?",
    choices: ["Midwest", "Northeast", "Southwest", "West Coast"],
    answer: 0,
    explanation: "The flat land and rich soil of the Midwest make it a leading region for corn and wheat.",
    quick: true,
  },
  {
    id: "soc-g5-02",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "Which river did early farmers use to ship crops to New Orleans?",
    choices: ["Mississippi", "Hudson", "Colorado", "Rio Grande"],
    answer: 0,
    explanation: "The Mississippi River flows south to New Orleans, so farmers floated crops downriver to market.",
    quick: true,
  },
  {
    id: "soc-g5-03",
    subject: "social",
    grade: "5",
    standard: "5.G.1.2",
    skill: "Forced migration",
    prompt: "The Trail of Tears was the forced removal of...",
    choices: ["The Cherokee", "Pilgrims", "Gold miners", "Irish workers"],
    answer: 0,
    explanation: "In 1838–39 the U.S. forced thousands of Cherokee west to Indian Territory. Thousands died on the way.",
    quick: true,
  },
  {
    id: "soc-g5-04",
    subject: "social",
    grade: "5",
    standard: "5.G.1.3",
    skill: "Technology and geography",
    prompt: "What was completed in 1869 to link the East and West by rail?",
    choices: ["Railroad", "Interstate", "Airport", "Canal"],
    answer: 0,
    explanation: "The transcontinental railroad cut a months-long trip to about a week.",
    quick: true,
  },
  {
    id: "soc-g5-05",
    subject: "social",
    grade: "5",
    standard: "5.G.1.4",
    skill: "Immigration",
    prompt: "Millions of immigrants in the early 1900s first arrived at...",
    choices: ["Ellis Island", "Hawaii", "Alaska", "Pikes Peak"],
    answer: 0,
    explanation: "Ellis Island in New York Harbor processed about 12 million immigrants from 1892 to 1954.",
    quick: true,
  },
  {
    id: "soc-g5-06",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "Which branch makes federal laws?",
    choices: ["Congress", "President", "Supreme Court", "Governor"],
    answer: 0,
    explanation: "Congress is the legislative branch. It writes and passes laws.",
    quick: true,
  },
  {
    id: "soc-g5-07",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "Which branch decides if laws follow the Constitution?",
    choices: ["Judicial", "Legislative", "Executive", "Military"],
    answer: 0,
    explanation: "The judicial branch, led by the Supreme Court, interprets laws.",
    quick: true,
  },
  {
    id: "soc-g5-08",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.2",
    skill: "Checks and balances",
    prompt: "Checks and balances stop one branch from having...",
    choices: ["Too much power", "A budget", "Any members", "A building"],
    answer: 0,
    explanation: "Each branch can limit the others, so no one branch becomes too powerful.",
    quick: true,
  },
  {
    id: "soc-g5-09",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.1",
    skill: "Voting rights",
    prompt: "The 19th Amendment (1920) gave the right to vote to...",
    choices: ["Women", "18-year-olds", "Landowners", "Soldiers"],
    answer: 0,
    explanation: "After years of advocacy by suffragists, the 19th Amendment protected women's right to vote.",
    quick: true,
  },
  {
    id: "soc-g5-10",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.2",
    skill: "Bill of Rights",
    prompt: "Freedom of speech is protected by the...",
    choices: ["1st Amendment", "2nd Amendment", "10th Amendment", "19th Amendment"],
    answer: 0,
    explanation: "The 1st Amendment protects freedom of speech, religion, press, assembly and petition.",
    quick: true,
  },
  {
    id: "soc-g5-11",
    subject: "social",
    grade: "5",
    standard: "5.H.1.3",
    skill: "American Revolution",
    prompt: "The American Revolution was a fight for independence from...",
    choices: ["Great Britain", "France", "Spain", "Mexico"],
    answer: 0,
    explanation: "The 13 colonies declared independence from Great Britain in 1776 and won the war in 1783.",
    quick: true,
  },
  {
    id: "soc-g5-12",
    subject: "social",
    grade: "5",
    standard: "5.H.1.4",
    skill: "Major conflicts",
    prompt: "The U.S. Civil War was fought from...",
    choices: ["1861–1865", "1776–1783", "1812–1815", "1917–1918"],
    answer: 0,
    explanation: "The Civil War between the Union and the Confederacy lasted from 1861 to 1865.",
    quick: true,
  },
  {
    id: "soc-g5-13",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    prompt: "George Washington Carver found hundreds of uses for...",
    choices: ["Peanuts", "Oil", "Steel", "Rubber"],
    answer: 0,
    explanation: "Carver, a Black scientist, taught Southern farmers to rotate cotton with peanuts to restore worn-out soil.",
    quick: true,
  },
  {
    id: "soc-g5-14",
    subject: "social",
    grade: "5",
    standard: "5.B.1.1",
    skill: "American arts",
    prompt: "Jazz music first grew in which city?",
    choices: ["New Orleans", "Boston", "Seattle", "Denver"],
    answer: 0,
    explanation: "Jazz was created by African American musicians in New Orleans in the early 1900s.",
    quick: true,
  },
  {
    id: "soc-g5-15",
    subject: "social",
    grade: "5",
    standard: "5.E.1.3",
    skill: "Division of labor",
    prompt: "Henry Ford's moving assembly line made cars...",
    choices: ["Cheaper", "Slower", "Rarer", "Heavier"],
    answer: 0,
    explanation: "Each worker did one step, so cars were built faster and cost less.",
    quick: true,
  },
  {
    id: "soc-g5-16",
    subject: "social",
    grade: "5",
    standard: "5.E.1.1",
    skill: "Economic decline",
    prompt: "The Great Depression began after the stock market crash of...",
    choices: ["1929", "1941", "1865", "1776"],
    answer: 0,
    explanation: "The 1929 crash helped start the Great Depression, a time of high unemployment.",
    quick: true,
  },
  {
    id: "soc-g5-17",
    subject: "social",
    grade: "5",
    standard: "5.E.2.2",
    skill: "Budgeting",
    passage:
      "Jada earns $20 a week walking dogs. Her budget says to save 25% of what she earns and spend the rest.",
    prompt: "How much will Jada save each week?",
    choices: ["$5", "$15", "$20", "$25"],
    answer: 0,
    explanation: "25% is one quarter. One quarter of $20 is $5.",
  },
  {
    id: "soc-g5-18",
    subject: "social",
    grade: "5",
    standard: "5.H.1.5",
    skill: "Primary sources",
    passage:
      "A student is researching the American Revolution (1775–1783) and finds four sources in the library.",
    prompt: "Which of these is a primary source about the Revolution?",
    choices: ["A letter written by a soldier in 1777", "A 2020 website about the war", "A textbook chapter from 1990", "A movie made in 2000"],
    answer: 0,
    explanation: "A primary source was created by someone who lived through the event. The others were made much later.",
  },
];

export default questions;
