import type { Question } from "../../types";
// Grade 9 social studies — NC Standard Course of Study for Social Studies (adopted 2021). World History (1200 CE to present): turning points, empires, revolutions, world wars
// and the Cold War (WH.H.1.1, WH.H.1); Renaissance, Reformation and Enlightenment (WH.B.1); power, rights and revolution (WH.C&G.1.1, WH.C&G.1); resources, trade and industry
// (WH.E.1.1, WH.E.1); migration, forced migration and borders (WH.G.1.1, WH.G.1).
const questions: Question[] = [
  {
    id: "soc-g9-01",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Mongol Empire",
    prompt: "The Mongol Empire was founded in the early 1200s by...",
    choices: ["Genghis Khan", "Kublai Khan", "Suleiman", "Akbar"],
    answer: 0,
    explanation: "Genghis Khan united the Mongols in 1206. His grandson Kublai Khan later ruled China.",
    quick: true,
  },
  {
    id: "soc-g9-02",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Trade networks",
    prompt: "Mongol rule made travel safer along the...",
    choices: ["Silk Road", "Erie Canal", "Suez Canal", "Panama Canal"],
    answer: 0,
    explanation: "The 'Pax Mongolica' protected merchants, so trade and ideas flowed across Eurasia.",
    quick: true,
  },
  {
    id: "soc-g9-03",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Black Death",
    prompt: "The Black Death swept across Europe in the...",
    choices: ["1340s", "1540s", "1740s", "1940s"],
    answer: 0,
    explanation: "The plague killed perhaps a third of Europe's people between 1347 and 1351.",
    quick: true,
  },
  {
    id: "soc-g9-04",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Renaissance",
    prompt: "The Renaissance began in the city-states of...",
    choices: ["Italy", "Sweden", "Russia", "Portugal"],
    answer: 0,
    explanation: "Wealthy Italian cities like Florence funded artists and scholars who revived classical learning.",
    quick: true,
  },
  {
    id: "soc-g9-05",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Reformation",
    prompt: "Martin Luther's 95 Theses (1517) sparked the...",
    choices: ["Reformation", "Renaissance", "Crusades", "Enlightenment"],
    answer: 0,
    explanation: "Luther challenged Church practices, leading to Protestant churches.",
    quick: true,
  },
  {
    id: "soc-g9-06",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Enlightenment",
    prompt: "John Locke argued people have natural rights to life, liberty and...",
    choices: ["Property", "Taxes", "Kings", "Land grants"],
    answer: 0,
    explanation: "Locke's ideas about natural rights influenced the Declaration of Independence.",
    quick: true,
  },
  {
    id: "soc-g9-07",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Mercantilism",
    prompt: "Under mercantilism, colonies mainly served to enrich their...",
    choices: ["Home country", "Neighbors", "Native rulers", "Pirates"],
    answer: 0,
    explanation: "Mercantilism said colonies should supply raw materials and buy goods from the ruling country.",
    quick: true,
  },
  {
    id: "soc-g9-08",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Atlantic slave trade",
    prompt: "The Atlantic slave trade forcibly carried millions of Africans to...",
    choices: ["The Americas", "Australia", "Siberia", "Japan"],
    answer: 0,
    explanation: "About 12.5 million Africans were forced onto ships to the Americas from the 1500s to the 1800s.",
    quick: true,
  },
  {
    id: "soc-g9-09",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Revolutions",
    prompt: "A leader of the Haitian Revolution (1791–1804) was...",
    choices: ["Toussaint", "Bolívar", "Napoleon", "Garibaldi"],
    answer: 0,
    explanation: "Toussaint L'Ouverture helped lead the revolt of enslaved people that created independent Haiti.",
    quick: true,
  },
  {
    id: "soc-g9-10",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Industrial Revolution",
    prompt: "Early Industrial Revolution factories were powered by water and...",
    choices: ["Steam", "Electricity", "Oil", "Solar"],
    answer: 0,
    explanation: "Water wheels and then coal-fired steam engines powered the first factories.",
    quick: true,
  },
  {
    id: "soc-g9-11",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Imperialism",
    prompt: "The 1884–85 Berlin Conference set rules for dividing Africa among...",
    choices: ["Europeans", "Africans", "Americans", "Chinese"],
    answer: 0,
    explanation: "European powers claimed African land without African input, drawing many of today's borders.",
    quick: true,
  },
  {
    id: "soc-g9-12",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Independence movements",
    prompt: "Gandhi led India's nonviolent movement for independence from...",
    choices: ["Britain", "France", "Japan", "Portugal"],
    answer: 0,
    explanation: "India gained independence from Britain in 1947.",
    quick: true,
  },
  {
    id: "soc-g9-13",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Human rights",
    prompt: "The Universal Declaration of Human Rights (1948) was adopted by the...",
    choices: ["United Nations", "NATO", "EU", "Warsaw Pact"],
    answer: 0,
    explanation: "The UN General Assembly adopted it after World War II.",
    quick: true,
  },
  {
    id: "soc-g9-14",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Cold War",
    prompt: "The Cold War ended as the Soviet Union dissolved in...",
    choices: ["1991", "1945", "1962", "1975"],
    answer: 0,
    explanation: "The USSR broke into 15 countries in December 1991.",
    quick: true,
  },
  {
    id: "soc-g9-15",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Trade routes",
    prompt: "Which 1869 canal shortened the sea route from Europe to Asia?",
    choices: ["Suez Canal", "Panama Canal", "Erie Canal", "Grand Canal"],
    answer: 0,
    explanation: "The Suez Canal links the Mediterranean and Red Seas, so ships no longer had to sail around Africa.",
    quick: true,
  },
  {
    id: "soc-g9-16",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Rule of law",
    passage:
      "In 1215, English barons forced King John to accept Magna Carta. It said the king could not take free men's property or jail them without lawful judgment, and he could not raise certain taxes without the barons' consent.",
    prompt: "What principle does this event best show?",
    choices: ["Rulers must obey the law too", "Kings have unlimited power", "Barons should rule England", "Taxes are always illegal"],
    answer: 0,
    explanation: "Magna Carta is an early example of limiting a ruler's power by law.",
  },
  {
    id: "soc-g9-17",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Columbian Exchange",
    passage:
      "Historians estimate that central Mexico's Indigenous population fell by up to 90 percent in the century after Spanish arrival in 1519. Epidemics of smallpox, measles and other illnesses swept through towns.",
    prompt: "What best explains the population decline?",
    choices: ["Diseases like smallpox from Europe", "Moving to Europe", "A long drought only", "Better farming"],
    answer: 0,
    explanation: "Indigenous peoples had no immunity to Old World diseases, which caused catastrophic death.",
  },
  {
    id: "soc-g9-18",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Industrial Revolution",
    passage:
      "A British parliament report from 1832 recorded a mill worker saying she began work at age 6, worked from 5 a.m. to 9 p.m., and was beaten when she fell behind.",
    prompt: "Which conclusion is best supported by the source?",
    choices: ["Factory work was long and dangerous for children", "Children rarely worked in factories", "Factories paid children very high wages", "Laws stopped child labor by 1800"],
    answer: 0,
    explanation: "Testimony like this led Britain to pass Factory Acts limiting child labor, starting in 1833.",
  },
  {
    id: "soc-g9-19",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Empires",
    prompt: "Suleiman the Magnificent ruled which empire at its height?",
    choices: ["Ottoman", "Mughal", "Safavid", "Ming"],
    answer: 0,
    explanation: "Suleiman (ruled 1520–1566) expanded the Ottoman Empire and reformed its laws.",
    quick: true,
  },
  {
    id: "soc-g9-20",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Exploration",
    prompt: "The Ming dynasty sent Admiral ___ on huge voyages in the early 1400s.",
    choices: ["Zheng He", "Marco Polo", "Kublai Khan", "Magellan"],
    answer: 0,
    explanation: "Zheng He's treasure fleets sailed as far as East Africa between 1405 and 1433.",
    quick: true,
  },
  {
    id: "soc-g9-21",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Empires",
    prompt: "Akbar the Great promoted religious tolerance as ruler of the...",
    choices: ["Mughal Empire", "Ottoman Empire", "Inca Empire", "Qing dynasty"],
    answer: 0,
    explanation: "Akbar (ruled 1556–1605) welcomed scholars of many faiths to his court in India.",
    quick: true,
  },
  {
    id: "soc-g9-22",
    subject: "social",
    grade: "9",
    standard: "WH.H.1.1",
    skill: "Turning points",
    prompt: "The 1648 Peace of Westphalia ended which war?",
    choices: ["Thirty Years' War", "Hundred Years' War", "Seven Years' War", "Wars of the Roses"],
    answer: 0,
    explanation: "Westphalia ended a long religious war in Europe and helped establish the idea of sovereign states.",
  },
  {
    id: "soc-g9-23",
    subject: "social",
    grade: "9",
    standard: "WH.H.1.1",
    skill: "Turning points",
    prompt: "England's Glorious Revolution (1688) led to the English...",
    choices: ["Bill of Rights", "Magna Carta", "Civil War", "Restoration"],
    answer: 0,
    explanation: "The 1689 English Bill of Rights limited the monarch and strengthened Parliament.",
    quick: true,
  },
  {
    id: "soc-g9-24",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Napoleonic era",
    prompt: "After Napoleon's defeat, European leaders met in 1814–15 at the Congress of...",
    choices: ["Vienna", "Berlin", "Versailles", "Westphalia"],
    answer: 0,
    explanation: "The Congress of Vienna redrew Europe's map and tried to restore a balance of power.",
    quick: true,
  },
  {
    id: "soc-g9-25",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Nationalism",
    prompt: "Germany was unified in 1871 under the leadership of...",
    choices: ["Bismarck", "Garibaldi", "Napoleon", "Metternich"],
    answer: 0,
    explanation: "Prussian Chancellor Otto von Bismarck used diplomacy and war to unite the German states.",
    quick: true,
  },
  {
    id: "soc-g9-26",
    subject: "social",
    grade: "9",
    standard: "WH.H.1.1",
    skill: "Imperialism",
    prompt: "The Opium Wars of the 1800s were fought between China and...",
    choices: ["Britain", "Japan", "Russia", "Brazil"],
    answer: 0,
    explanation: "Britain (joined by France in the second war) won, forcing China to open ports and hand over Hong Kong.",
    quick: true,
  },
  {
    id: "soc-g9-27",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Cold War",
    prompt: "The 1950–53 war on the Korean Peninsula ended in...",
    choices: ["An armistice", "A peace treaty", "Unification", "A U.S. victory"],
    answer: 0,
    explanation: "Fighting stopped with a 1953 armistice. No peace treaty was ever signed, and Korea remains divided.",
    quick: true,
  },
  {
    id: "soc-g9-28",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Genocide",
    prompt: "The 1994 genocide in Rwanda targeted mostly...",
    choices: ["Tutsi", "Hutu", "Zulu", "Maasai"],
    answer: 0,
    explanation: "About 800,000 people, mostly Tutsi, were killed in about 100 days. Moderate Hutu were also killed.",
    quick: true,
  },
  {
    id: "soc-g9-29",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Cold War",
    passage:
      "President Truman to Congress, March 12, 1947: 'I believe that it must be the policy of the United States to support free peoples who are resisting attempted subjugation by armed minorities or by outside pressures.'",
    prompt: "This policy is best described as...",
    choices: ["Containment of communism", "Isolationism", "Imperialism", "Appeasement"],
    answer: 0,
    explanation: "The Truman Doctrine promised U.S. aid to stop the spread of communism, the policy called containment.",
  },
  {
    id: "soc-g9-30",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Independence movements",
    prompt: "Most Latin American countries won independence from Spain and Portugal in the...",
    choices: ["1800s", "1600s", "1700s", "1900s"],
    answer: 0,
    explanation: "Between about 1810 and 1825, leaders like Bolívar and San Martín freed most of Latin America.",
    quick: true,
  },
  {
    id: "soc-g9-31",
    subject: "social",
    grade: "9",
    standard: "WH.G.1.1",
    skill: "Forced migration",
    prompt: "The Middle Passage was the forced voyage of enslaved Africans across the...",
    choices: ["Atlantic", "Pacific", "Indian Ocean", "Sahara"],
    answer: 0,
    explanation: "Enslaved people were packed onto ships for weeks. Many died on the voyage to the Americas.",
    quick: true,
  },
  {
    id: "soc-g9-32",
    subject: "social",
    grade: "9",
    standard: "WH.G.1.1",
    skill: "Migration",
    prompt: "Over a million people left Ireland in the late 1840s because of the...",
    choices: ["Potato famine", "Gold rush", "Black Death", "Crusades"],
    answer: 0,
    explanation: "A potato blight caused famine. Many Irish emigrated to the U.S., Britain and Canada.",
    quick: true,
  },
  {
    id: "soc-g9-33",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Imperialism",
    prompt: "What was one lasting effect of borders drawn at the Berlin Conference?",
    choices: ["They split some ethnic groups and joined rivals together", "They followed traditional African kingdoms exactly", "They were all erased by 1900", "They gave African rulers more land"],
    answer: 0,
    explanation: "Borders drawn without African input caused conflicts that continued after independence.",
  },
  {
    id: "soc-g9-34",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Location",
    prompt: "Which strait links the Mediterranean Sea to the Atlantic Ocean?",
    choices: ["Gibraltar", "Bosporus", "Hormuz", "Malacca"],
    answer: 0,
    explanation: "The Strait of Gibraltar separates Spain from Morocco.",
    quick: true,
  },
  {
    id: "soc-g9-35",
    subject: "social",
    grade: "9",
    standard: "WH.E.1.1",
    skill: "Imperialism",
    prompt: "European demand for rubber drove brutal forced labor in the Congo under...",
    choices: ["Leopold II", "Napoleon", "Bismarck", "Victoria"],
    answer: 0,
    explanation: "Belgium's King Leopold II ran the Congo Free State as his own colony. Millions died before reformers forced change.",
    quick: true,
  },
  {
    id: "soc-g9-36",
    subject: "social",
    grade: "9",
    standard: "WH.E.1.1",
    skill: "Exploration",
    prompt: "Europeans sought a sea route to Asia mainly to buy...",
    choices: ["Spices", "Furs", "Potatoes", "Oil"],
    answer: 0,
    explanation: "Spices like pepper and cloves were very valuable, and land routes were long and costly.",
    quick: true,
  },
  {
    id: "soc-g9-37",
    subject: "social",
    grade: "9",
    standard: "WH.E.1.1",
    skill: "Trade",
    prompt: "The Dutch East India Company (1602) was one of the first companies to sell...",
    choices: ["Shares", "Cars", "Railroads", "Radios"],
    answer: 0,
    explanation: "Selling shares let many investors fund risky voyages and share the profits.",
    quick: true,
  },
  {
    id: "soc-g9-38",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Postwar recovery",
    prompt: "After 1945, Western Europe rebuilt with U.S. aid called the...",
    choices: ["Marshall Plan", "New Deal", "Lend-Lease", "Truman Plan"],
    answer: 0,
    explanation: "The Marshall Plan gave about $13 billion to help Europe recover and resist communism.",
    quick: true,
  },
  {
    id: "soc-g9-39",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Resources",
    prompt: "OPEC is a group of countries that export...",
    choices: ["Oil", "Wheat", "Coffee", "Steel"],
    answer: 0,
    explanation: "OPEC members coordinate oil production, which affects prices worldwide.",
    quick: true,
  },
  {
    id: "soc-g9-40",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Industrial Revolution",
    passage:
      "Estimated share of world manufacturing output (historian Paul Bairoch): 1750 – China 33%, Britain 2%. 1830 – China 30%, Britain 10%. 1880 – China 13%, Britain 23%.",
    prompt: "Which development best explains the change?",
    choices: ["Britain industrialized with machines and factories", "China industrialized before Britain did", "Britain lost all of its colonies", "World trade disappeared"],
    answer: 0,
    explanation: "Machines and steam power let Britain produce far more goods than hand workers could.",
  },
  {
    id: "soc-g9-41",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1.1",
    skill: "Power",
    prompt: "The idea that kings get their power directly from God is...",
    choices: ["Divine right", "Popular rule", "Federalism", "Democracy"],
    answer: 0,
    explanation: "Divine right was used to justify absolute monarchy.",
    quick: true,
  },
  {
    id: "soc-g9-42",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1.1",
    skill: "Absolutism",
    prompt: "Louis XIV ruled France as an ___ monarch, with nearly unlimited power.",
    choices: ["Absolute", "Elected", "Limited", "Figurehead"],
    answer: 0,
    explanation: "Louis XIV built Versailles and centralized power in himself.",
    quick: true,
  },
  {
    id: "soc-g9-43",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1.1",
    skill: "Enlightenment",
    prompt: "Which thinker proposed separating government power into three branches?",
    choices: ["Montesquieu", "Hobbes", "Locke", "Rousseau"],
    answer: 0,
    explanation: "Montesquieu's 'The Spirit of the Laws' (1748) influenced the U.S. Constitution.",
    quick: true,
  },
  {
    id: "soc-g9-44",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Totalitarianism",
    prompt: "Mussolini in Italy and Hitler in Germany led ___ governments.",
    choices: ["Fascist", "Democratic", "Communist", "Monarchist"],
    answer: 0,
    explanation: "Fascist states glorified the nation, crushed opposition and gave all power to one leader.",
    quick: true,
  },
  {
    id: "soc-g9-45",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "International cooperation",
    prompt: "Which organization's Security Council has five permanent members?",
    choices: ["United Nations", "NATO", "Warsaw Pact", "OPEC"],
    answer: 0,
    explanation: "The U.S., UK, France, Russia and China are the permanent members of the UN Security Council.",
    quick: true,
  },
  {
    id: "soc-g9-46",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Independence movements",
    passage:
      "Vietnam's Declaration of Independence (1945) begins by quoting the U.S. Declaration – 'All men are created equal' – and then says: 'This immortal statement was made in the Declaration of Independence of the United States of America in 1776.'",
    prompt: "Why did Ho Chi Minh open Vietnam's 1945 declaration this way?",
    choices: ["To use admired ideas of natural rights to justify independence", "To ask Vietnam to become a U.S. state", "To praise French colonial rule", "To reject all Western ideas"],
    answer: 0,
    explanation: "Quoting the U.S. Declaration appealed to the world's support for Vietnam's freedom from France.",
  },
  {
    id: "soc-g9-47",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Renaissance",
    prompt: "Leonardo da Vinci painted the...",
    choices: ["Mona Lisa", "Starry Night", "The Scream", "Guernica"],
    answer: 0,
    explanation: "Leonardo was a Renaissance painter, inventor and scientist.",
    quick: true,
  },
  {
    id: "soc-g9-48",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Scientific Revolution",
    prompt: "Isaac Newton is famous for describing...",
    choices: ["Gravity", "Evolution", "Germs", "DNA"],
    answer: 0,
    explanation: "Newton's laws of motion and gravity (1687) explained how objects and planets move.",
    quick: true,
  },
];

export default questions;
