/*
 * Builds src/chase/worldData.ts from Natural Earth 1:50m land (public domain), via the
 * world-atlas TopoJSON copy in scripts/data/ (ISC licence, see world-atlas-LICENSE).
 *   node scripts/make-world.cjs
 * Rings are simplified (Douglas-Peucker), tiny islets dropped, and stored as delta-encoded
 * tenths of a degree, so the whole world fits in a small module that both the game (map
 * drawing) and the content tests (pins on land) can read.
 */
const fs = require("fs");
const path = require("path");

const topo = JSON.parse(fs.readFileSync(path.join(__dirname, "data/land-50m.json"), "utf8"));
const { scale, translate } = topo.transform;

// Decode arcs (quantized, delta-encoded) into lon/lat points.
const arcs = topo.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
function arcPts(i) {
  return i >= 0 ? arcs[i] : arcs[~i].slice().reverse();
}
function ring(idx) {
  const out = [];
  idx.forEach((a, k) => {
    const pts = arcPts(a);
    out.push(...(k ? pts.slice(1) : pts));
  });
  return out;
}

function area(r) {
  let s = 0;
  for (let i = 0; i < r.length; i++) {
    const [x1, y1] = r[i];
    const [x2, y2] = r[(i + 1) % r.length];
    s += x1 * y2 - x2 * y1;
  }
  return Math.abs(s) / 2;
}

function dp(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a];
    const [bx, by] = pts[b];
    const dx = bx - ax;
    const dy = by - ay;
    const len = Math.hypot(dx, dy) || 1e-9;
    let best = -1;
    let bi = -1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * (pts[i][0] - ax) - dx * (pts[i][1] - ay)) / len;
      if (d > best) {
        best = d;
        bi = i;
      }
    }
    if (best > tol) {
      keep[bi] = 1;
      stack.push([a, bi], [bi, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

const rings = [];
for (const geom of topo.objects.land.geometries) {
  const polys = geom.type === "Polygon" ? [geom.arcs] : geom.arcs;
  for (const poly of polys) {
    for (const r of poly) {
      const pts = ring(r);
      const a = area(pts);
      if (a < 0.08) continue; // islets smaller than ~1000 km²
      if (pts.every(([, y]) => y < -60)) continue; // Antarctica is off the map
      // A closed ring: split at the point farthest from the start so both halves simplify.
      let far = 0;
      pts.forEach((p, i) => {
        if (Math.hypot(p[0] - pts[0][0], p[1] - pts[0][1]) > Math.hypot(pts[far][0] - pts[0][0], pts[far][1] - pts[0][1])) far = i;
      });
      const tol = a > 50 ? 0.12 : 0.06;
      const simple = [...dp(pts.slice(0, far + 1), tol), ...dp(pts.slice(far), tol).slice(1)];
      if (simple.length >= 4) rings.push(simple);
    }
  }
}

// Delta-encode tenths of a degree.
const enc = rings.map((r) => {
  const out = [];
  let px = 0;
  let py = 0;
  for (const [x, y] of r) {
    const ix = Math.round(x * 10);
    const iy = Math.round(y * 10);
    if (out.length && ix === px && iy === py) continue;
    out.push(ix - px, iy - py);
    px = ix;
    py = iy;
  }
  return out.join(",");
});

const body = `// GENERATED by scripts/make-world.cjs from Natural Earth 1:50m land (public domain) via world-atlas.
// Each ring: delta-encoded [lon*10, lat*10] pairs. Do not edit by hand.
export const LAND_RINGS: string[] = [
${enc.map((s) => `  "${s}",`).join("\n")}
];
`;
const out = path.join(__dirname, "../src/chase/worldData.ts");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`${rings.length} rings, ${rings.reduce((a, r) => a + r.length, 0)} points, ${(body.length / 1024).toFixed(1)} KB`);
