import type { Question } from "../../types";
// Grade 10 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Founding Principles of the United States of America and North Carolina: Civic Literacy.
// Founding documents and principles (CL.C&G.1.1, CL.C&G.1), federal, state and local branches (CL.C&G.2), citizenship and participation (CL.C&G.3.1, CL.C&G.3), the founding era
// (CL.H.1.1, CL.H.1), values and changing norms (CL.B.1.1, CL.B.1.2), government and the economy (CL.E.1, CL.E.1.2), geography and policy (CL.G.1.2, CL.G.1.3).
const questions: Question[] = [
  {
    id: "soc-g10-01",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Founding documents",
    prompt: "The Declaration of Independence was adopted in...",
    choices: ["1776", "1787", "1791", "1789"],
    answer: 0,
    explanation: "Congress adopted it on July 4, 1776. The Constitution was written in 1787.",
    quick: true,
  },
  {
    id: "soc-g10-02",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Founding principles",
    prompt: "Popular sovereignty means government power comes from...",
    choices: ["The people", "The king", "The courts", "The military"],
    answer: 0,
    explanation: "The Constitution begins 'We the People' because the people are the source of power.",
    quick: true,
  },
  {
    id: "soc-g10-03",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Bill of Rights",
    prompt: "The first ten amendments are called the...",
    choices: ["Bill of Rights", "Preamble", "Articles", "Federalist"],
    answer: 0,
    explanation: "The Bill of Rights was ratified in 1791 to protect individual liberties.",
    quick: true,
  },
  {
    id: "soc-g10-04",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Rule of law",
    prompt: "Rule of law means everyone, including leaders, must...",
    choices: ["Obey the law", "Own land", "Hold office", "Join a party"],
    answer: 0,
    explanation: "No person is above the law, including government officials.",
    quick: true,
  },
  {
    id: "soc-g10-05",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Congress",
    prompt: "How many U.S. senators does each state have?",
    choices: ["2", "1", "4", "Based on size"],
    answer: 0,
    explanation: "Every state has two senators. House seats are based on population.",
    quick: true,
  },
  {
    id: "soc-g10-06",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Checks and balances",
    prompt: "The President can reject a bill passed by Congress with a...",
    choices: ["Veto", "Filibuster", "Recall", "Pardon"],
    answer: 0,
    explanation: "A veto sends the bill back to Congress.",
    quick: true,
  },
  {
    id: "soc-g10-07",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Checks and balances",
    prompt: "Congress can override a veto with a vote in each house of...",
    choices: ["Two-thirds", "One-half", "Three-fourths", "All members"],
    answer: 0,
    explanation: "A two-thirds vote in both the House and Senate overrides a veto.",
    quick: true,
  },
  {
    id: "soc-g10-08",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "NC courts",
    prompt: "What is North Carolina's highest state court?",
    choices: ["Supreme Court", "Superior Court", "District Court", "Magistrate"],
    answer: 0,
    explanation: "The NC Supreme Court has seven justices, elected by voters, who hear appeals.",
    quick: true,
  },
  {
    id: "soc-g10-09",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Local government",
    prompt: "NC counties are governed by a board of...",
    choices: ["Commissioners", "Senators", "Justices", "Governors"],
    answer: 0,
    explanation: "Each of NC's 100 counties elects a board of county commissioners.",
    quick: true,
  },
  {
    id: "soc-g10-10",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Judicial review",
    prompt: "Marbury v. Madison (1803) set up the Supreme Court's power of judicial...",
    choices: ["Review", "Veto", "Recall", "Appointment"],
    answer: 0,
    explanation: "Judicial review lets courts strike down laws that conflict with the Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-11",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "Voting",
    prompt: "The 26th Amendment (1971) set the voting age at...",
    choices: ["18", "16", "21", "25"],
    answer: 0,
    explanation: "The 26th Amendment lowered the voting age from 21 to 18.",
    quick: true,
  },
  {
    id: "soc-g10-12",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3.1",
    skill: "Citizen responsibilities",
    prompt: "Serving on a jury is a responsibility of...",
    choices: ["Citizens", "Tourists", "Only lawyers", "Only judges"],
    answer: 0,
    explanation: "Juries are made of ordinary citizens, which protects the right to a fair trial.",
    quick: true,
  },
  {
    id: "soc-g10-13",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Ratification",
    prompt: "The Federalist Papers argued for ratifying the...",
    choices: ["Constitution", "Articles", "Declaration", "Magna Carta"],
    answer: 0,
    explanation: "Hamilton, Madison and Jay wrote 85 essays supporting the new Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-14",
    subject: "social",
    grade: "10",
    standard: "CL.H.1",
    skill: "Articles of Confederation",
    prompt: "Under the Articles of Confederation, Congress could not...",
    choices: ["Collect taxes", "Make treaties", "Declare war", "Hold meetings"],
    answer: 0,
    explanation: "Without power to tax, the national government could not pay its debts, leading to the Constitution.",
    quick: true,
  },
  {
    id: "soc-g10-15",
    subject: "social",
    grade: "10",
    standard: "CL.E.1",
    skill: "Public finance",
    prompt: "Which level of government provides the largest share of NC public school funding?",
    choices: ["State", "Federal", "City", "Private"],
    answer: 0,
    explanation: "NC's state government pays most school costs, like teacher salaries. Counties and the federal government add more.",
    quick: true,
  },
  {
    id: "soc-g10-16",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "Civic participation",
    passage:
      "Luis thinks the street by his school needs a crosswalk. The street is run by his town. The town council holds public meetings twice a month where residents may speak.",
    prompt: "What is Luis's best first step?",
    choices: ["Speak at a town council meeting", "Paint his own crosswalk", "Write to the U.S. Supreme Court", "Ask the President"],
    answer: 0,
    explanation: "Traffic signs on town streets are handled by local government, so the town council is the right place to start.",
  },
  {
    id: "soc-g10-17",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "First Amendment",
    passage:
      "A local newspaper prints an article criticizing the mayor's budget. The mayor asks the police to shut down the paper.",
    prompt: "Which right protects the newspaper?",
    choices: ["Freedom of the press", "Right to bear arms", "Right to a jury", "Freedom from quartering"],
    answer: 0,
    explanation: "The 1st Amendment bars government from punishing the press for criticizing officials.",
  },
  {
    id: "soc-g10-18",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Preamble",
    passage:
      "The Preamble: 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty...'",
    prompt: "Which phrase is about keeping peace at home?",
    choices: ["Insure domestic tranquility", "Provide for the common defence", "Promote the general welfare", "Secure the blessings of liberty"],
    answer: 0,
    explanation: "'Domestic tranquility' means peace within the country. Common defence is about outside threats.",
  },
  {
    id: "soc-g10-19",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Separation of powers",
    prompt: "Separation of powers divides the federal government into...",
    choices: ["Three branches", "Two parties", "50 states", "Four courts"],
    answer: 0,
    explanation: "Legislative, executive and judicial branches each have their own powers.",
    quick: true,
  },
  {
    id: "soc-g10-20",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Limited government",
    prompt: "A constitution that restricts what government may do reflects ___ government.",
    choices: ["Limited", "Unlimited", "Absolute", "Direct"],
    answer: 0,
    explanation: "Limited government means officials can only use the powers the people grant them.",
    quick: true,
  },
  {
    id: "soc-g10-21",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1.1",
    skill: "NC Constitution",
    prompt: "Article I of the NC Constitution is a 'Declaration of...'",
    choices: ["Rights", "Independence", "War", "Sentiments"],
    answer: 0,
    explanation: "NC's Declaration of Rights lists freedoms like speech, religion and education.",
    quick: true,
  },
  {
    id: "soc-g10-22",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Federalism",
    prompt: "Under the Supremacy Clause, valid federal laws are ___ over conflicting state laws.",
    choices: ["Supreme", "Optional", "Advisory", "Equal"],
    answer: 0,
    explanation: "Article VI makes the Constitution and federal laws 'the supreme Law of the Land.'",
    quick: true,
  },
  {
    id: "soc-g10-23",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Federalism",
    prompt: "The 10th Amendment reserves powers not given to the federal government to the...",
    choices: ["States", "President", "Courts", "Congress"],
    answer: 0,
    explanation: "Powers not delegated to the U.S. are reserved to the states or to the people.",
    quick: true,
  },
  {
    id: "soc-g10-24",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Amendments",
    prompt: "How many amendments does the U.S. Constitution have?",
    choices: ["27", "10", "26", "33"],
    answer: 0,
    explanation: "There are 27 amendments. The most recent, about congressional pay, was ratified in 1992.",
    quick: true,
  },
  {
    id: "soc-g10-25",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "Checks and balances",
    passage:
      "James Madison, Federalist No. 51 (1788): 'If men were angels, no government would be necessary. If angels were to govern men, neither external nor internal controls on government would be necessary.'",
    prompt: "Which principle does Madison use this argument to support?",
    choices: ["Checks and balances on government power", "Rule by a monarch", "Getting rid of government", "Direct democracy for every decision"],
    answer: 0,
    explanation: "Because people are not angels, Madison wanted each branch to check the others.",
  },
  {
    id: "soc-g10-26",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.1",
    skill: "First Amendment",
    passage:
      "First Amendment: 'Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.'",
    prompt: "Students sign a letter asking the school board to change a policy. Which right is this?",
    choices: ["Petition the government", "Establishment of religion", "Freedom of the press", "Free exercise of religion"],
    answer: 0,
    explanation: "A public school board is part of government, so the students are petitioning for a change.",
  },
  {
    id: "soc-g10-27",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Congress",
    prompt: "Members of the U.S. House of Representatives serve terms of...",
    choices: ["2 years", "4 years", "6 years", "Life"],
    answer: 0,
    explanation: "House members face voters every two years. Senators serve six-year terms.",
    quick: true,
  },
  {
    id: "soc-g10-28",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Courts",
    prompt: "Federal judges, including Supreme Court justices, serve...",
    choices: ["For life", "4 years", "6 years", "10 years"],
    answer: 0,
    explanation: "Judges serve 'during good behaviour,' so they can rule without worrying about reelection.",
    quick: true,
  },
  {
    id: "soc-g10-29",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Courts",
    prompt: "How many justices sit on the U.S. Supreme Court?",
    choices: ["9", "7", "12", "5"],
    answer: 0,
    explanation: "Congress set the number at nine in 1869. NC's Supreme Court has seven.",
    quick: true,
  },
  {
    id: "soc-g10-30",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Executive branch",
    prompt: "Who is first in line if the President cannot serve?",
    choices: ["Vice President", "Speaker", "Chief Justice", "Sec. of State"],
    answer: 0,
    explanation: "The Vice President is first in line. The Speaker of the House is second.",
    quick: true,
  },
  {
    id: "soc-g10-31",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "NC General Assembly",
    prompt: "The NC General Assembly has a Senate of 50 members and a House of...",
    choices: ["120", "100", "50", "435"],
    answer: 0,
    explanation: "The NC House has 120 members. The U.S. House has 435.",
    quick: true,
  },
  {
    id: "soc-g10-32",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "NC governor",
    prompt: "The NC General Assembly can override a governor's veto with ___ of each house.",
    choices: ["Three-fifths", "Two-thirds", "One-half", "Three-fourths"],
    answer: 0,
    explanation: "NC requires three-fifths of members present and voting in each house, a lower bar than Congress's two-thirds.",
    quick: true,
  },
  {
    id: "soc-g10-33",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "Executive branch",
    prompt: "The President's top advisers who lead executive departments form the...",
    choices: ["Cabinet", "Senate", "Congress", "Judiciary"],
    answer: 0,
    explanation: "Cabinet members, like the Secretary of State, lead departments and advise the President.",
    quick: true,
  },
  {
    id: "soc-g10-34",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.2",
    skill: "NC lawmaking",
    passage:
      "A bill passes the NC House and Senate in the same form and goes to the governor while the General Assembly is in session. Ten days pass, and the governor neither signs nor vetoes it.",
    prompt: "What happens to the bill?",
    choices: ["It becomes law without the governor's signature", "It is automatically vetoed", "It goes to the NC Supreme Court", "It returns to the House for a new vote"],
    answer: 0,
    explanation: "Under the NC Constitution, a bill the governor neither signs nor vetoes within 10 days during a session becomes law.",
  },
  {
    id: "soc-g10-35",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3.1",
    skill: "Citizenship",
    prompt: "To become a naturalized citizen, a person usually must pass a test on English and...",
    choices: ["Civics", "Algebra", "Chemistry", "Driving"],
    answer: 0,
    explanation: "Applicants answer questions about U.S. history and government.",
    quick: true,
  },
  {
    id: "soc-g10-36",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3.1",
    skill: "Duties and responsibilities",
    prompt: "Which is a legal duty rather than a voluntary act?",
    choices: ["Paying taxes", "Voting", "Volunteering", "Joining a party"],
    answer: 0,
    explanation: "Duties are required by law. Voting is a right and a responsibility, but it is not required.",
  },
  {
    id: "soc-g10-37",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3.1",
    skill: "Voting",
    prompt: "In NC, a person may preregister to vote at age...",
    choices: ["16", "18", "21", "14"],
    answer: 0,
    explanation: "NC lets 16- and 17-year-olds preregister so they are ready to vote at 18.",
    quick: true,
  },
  {
    id: "soc-g10-38",
    subject: "social",
    grade: "10",
    standard: "CL.C&G.3",
    skill: "First Amendment",
    prompt: "A peaceful public protest is protected by the right to...",
    choices: ["Assemble", "Bear arms", "Vote", "A jury"],
    answer: 0,
    explanation: "The First Amendment protects the right to assemble peaceably.",
    quick: true,
  },
  {
    id: "soc-g10-39",
    subject: "social",
    grade: "10",
    standard: "CL.H.1.1",
    skill: "Articles of Confederation",
    prompt: "Shays' Rebellion (1786–87) showed the weakness of the...",
    choices: ["Articles", "Constitution", "Monarchy", "Bill of Rights"],
    answer: 0,
    explanation: "The Articles government could not raise an army to stop the uprising, which pushed leaders to write a new constitution.",
    quick: true,
  },
  {
    id: "soc-g10-40",
    subject: "social",
    grade: "10",
    standard: "CL.H.1.1",
    skill: "Constitutional Convention",
    prompt: "The Great Compromise created a Congress with...",
    choices: ["Two houses", "One house", "No senators", "Three houses"],
    answer: 0,
    explanation: "States have equal votes in the Senate and seats by population in the House.",
    quick: true,
  },
  {
    id: "soc-g10-41",
    subject: "social",
    grade: "10",
    standard: "CL.H.1.1",
    skill: "Constitutional Convention",
    prompt: "The Three-Fifths Compromise counted enslaved people as three-fifths of a person for...",
    choices: ["Representation", "Jury duty", "Voting rights", "Militia duty"],
    answer: 0,
    explanation: "It also counted for direct taxes. The 14th Amendment later ended the three-fifths count.",
    quick: true,
  },
  {
    id: "soc-g10-42",
    subject: "social",
    grade: "10",
    standard: "CL.H.1",
    skill: "Ratification",
    prompt: "Anti-Federalists demanded that the Constitution add a...",
    choices: ["Bill of Rights", "King", "State church", "Navy"],
    answer: 0,
    explanation: "Federalists promised amendments, and the Bill of Rights was ratified in 1791.",
    quick: true,
  },
  {
    id: "soc-g10-43",
    subject: "social",
    grade: "10",
    standard: "CL.B.1.2",
    skill: "Changing norms",
    passage:
      "In 1967, the Supreme Court ruled in Loving v. Virginia that state laws banning marriage between people of different races violated the 14th Amendment.",
    prompt: "What does this ruling show?",
    choices: ["Court rulings can reflect and shape changing ideas about equality", "The Court cannot review state laws", "The 14th Amendment applies only to voting", "States may ignore the Constitution"],
    answer: 0,
    explanation: "Loving v. Virginia applied the 14th Amendment's equal protection to marriage, reflecting changing views of equality.",
  },
  {
    id: "soc-g10-44",
    subject: "social",
    grade: "10",
    standard: "CL.B.1.1",
    skill: "Values and public policy",
    prompt: "MADD's campaign helped raise the drinking age to 21 nationwide. This shows...",
    choices: ["Groups shape policy", "Courts make laws", "Laws never change", "Kings decide"],
    answer: 0,
    explanation: "Mothers Against Drunk Driving helped pass the 1984 National Minimum Drinking Age Act.",
  },
  {
    id: "soc-g10-45",
    subject: "social",
    grade: "10",
    standard: "CL.E.1",
    skill: "Public finance",
    prompt: "The federal government's largest source of revenue is...",
    choices: ["Income taxes", "Tariffs", "Lotteries", "Parking fines"],
    answer: 0,
    explanation: "Individual income taxes bring in about half of federal revenue.",
    quick: true,
  },
  {
    id: "soc-g10-46",
    subject: "social",
    grade: "10",
    standard: "CL.E.1.2",
    skill: "Trade",
    prompt: "Tariffs are taxes on...",
    choices: ["Imports", "Wages", "Property", "Gasoline"],
    answer: 0,
    explanation: "Tariffs raise the price of foreign goods, which can protect some industries but cost consumers more.",
    quick: true,
  },
  {
    id: "soc-g10-47",
    subject: "social",
    grade: "10",
    standard: "CL.G.1.2",
    skill: "Representation",
    prompt: "The number of House seats each state gets is updated after each...",
    choices: ["Census", "Election", "War", "Treaty"],
    answer: 0,
    explanation: "Every 10 years the census counts people, and House seats are reapportioned by population.",
    quick: true,
  },
  {
    id: "soc-g10-48",
    subject: "social",
    grade: "10",
    standard: "CL.G.1.3",
    skill: "Global issues",
    prompt: "The 2015 Paris Agreement is an international pact about...",
    choices: ["Climate change", "Trade", "Nuclear arms", "Fishing"],
    answer: 0,
    explanation: "Nations set goals to cut greenhouse gas emissions and limit global warming.",
    quick: true,
  },
];

export default questions;
