import type { Question } from "../../types";
// Grade 3 science — NC Standard Course of Study for Science (2023). Solids, liquids and gases and changes from
// heating and cooling (PS.3.1), forces and motion (PS.3.2), the sun, shadows and the solar system (ESS.3.1),
// Earth's land features (ESS.3.2), skeletal and muscular systems (LS.3.1), seed-plant life cycles (LS.3.2), and
// soil properties that support plant growth (LS.3.3).
const questions: Question[] = [
  {
    id: "sci-g3-01",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Which state of matter keeps its own shape?",
    choices: ["Solid", "Liquid", "Gas", "Steam"],
    answer: 0,
    explanation: "A solid has a definite shape. Liquids take the shape of their container, and gases spread out to fill it.",
    quick: true,
  },
  {
    id: "sci-g3-02",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Juice poured into a bowl takes the shape of the...",
    choices: ["Bowl", "Tall glass", "Juice box", "Spoon"],
    answer: 0,
    explanation: "Liquids flow and take the shape of whatever container they are in, but the amount stays the same.",
    quick: true,
  },
  {
    id: "sci-g3-03",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.2",
    skill: "States of matter",
    prompt: "Which state of matter spreads out to fill any container?",
    choices: ["Gas", "Solid", "Liquid", "Ice"],
    answer: 0,
    explanation: "A gas has no fixed shape or volume. It spreads out to fill all the space it is in, like air in a balloon.",
    quick: true,
  },
  {
    id: "sci-g3-04",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.3",
    skill: "Heating and cooling matter",
    prompt: "Boiling water long enough turns it into...",
    choices: ["Water vapor", "Ice", "Salt", "Sand"],
    answer: 0,
    explanation: "Heating liquid water makes it change into a gas called water vapor.",
    quick: true,
  },
  {
    id: "sci-g3-05",
    subject: "science",
    grade: "3",
    standard: "PS.3.1.3",
    skill: "Heating and cooling matter",
    prompt: "A puddle dries up on a sunny day. Where did the water go?",
    choices: ["Into the air", "Into the sun", "It vanished", "Turned to salt"],
    answer: 0,
    explanation: "The sun's heat made the water evaporate. It became water vapor, an invisible gas in the air.",
    quick: true,
  },
  {
    id: "sci-g3-06",
    subject: "science",
    grade: "3",
    standard: "PS.3.2",
    skill: "Forces and motion",
    passage:
      "Two identical toy carts sit on a smooth floor. Jada gives Cart A a gentle push. Ben gives Cart B a much stronger push in the same direction.",
    prompt: "Which cart will speed up more, and why?",
    choices: [
      "Cart B, because a bigger force causes a bigger change in motion",
      "Cart A, because gentle pushes last longer",
      "Both the same, because the carts are identical",
      "Neither, because carts only move downhill",
    ],
    answer: 0,
    explanation: "When the mass is the same, a stronger push (force) makes a bigger change in speed.",
  },
  {
    id: "sci-g3-07",
    subject: "science",
    grade: "3",
    standard: "PS.3.2",
    skill: "Forces and motion",
    prompt: "Friction is a force that usually does what to moving things?",
    choices: ["Slows them", "Speeds them", "Lifts them", "Colors them"],
    answer: 0,
    explanation: "Friction happens when surfaces rub together. It works against motion and slows things down.",
    quick: true,
  },
  {
    id: "sci-g3-08",
    subject: "science",
    grade: "3",
    standard: "LS.3.3",
    skill: "Soil and plant growth",
    passage:
      "Students poured 100 mL of water through three cups of soil. They measured how much water drained out the bottom. Sand: 80 mL. Loam: 50 mL. Clay: 20 mL.",
    prompt: "Which soil held on to the most water?",
    choices: ["Clay", "Sand", "Loam", "They all held the same"],
    answer: 0,
    explanation: "Only 20 mL drained from clay, so it kept 80 mL. Clay has tiny particles packed close together that hold water.",
  },
  {
    id: "sci-g3-09",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "The sun is a...",
    choices: ["Star", "Planet", "Moon", "Comet"],
    answer: 0,
    explanation: "The sun is a star. It looks bigger and brighter than other stars because it is so much closer to us.",
    quick: true,
  },
  {
    id: "sci-g3-10",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.2",
    skill: "Shadows and the sun",
    prompt: "When is your shadow the shortest?",
    choices: ["Around noon", "Early morning", "Late evening", "At sunrise"],
    answer: 0,
    explanation: "Around noon the sun is highest in the sky, so shadows are short. Low sun makes long shadows.",
    quick: true,
  },
  {
    id: "sci-g3-11",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.2",
    skill: "Shadows and the sun",
    passage:
      "Leo measured the flagpole's shadow three times in one day. At 8 a.m. it was long and pointed west. At noon it was short. At 4 p.m. it was long and pointed east.",
    prompt: "What best explains why the shadow changed?",
    choices: [
      "The sun's position in the sky changed during the day",
      "The flagpole grew taller and then shorter",
      "Clouds pushed the shadow around",
      "The ground turned under the flagpole in one day",
    ],
    answer: 0,
    explanation: "As Earth spins, the sun appears to move across the sky. Shadows point away from the sun, so they change length and direction.",
  },
  {
    id: "sci-g3-12",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "Which planet is closest to the sun?",
    choices: ["Mercury", "Earth", "Mars", "Neptune"],
    answer: 0,
    explanation: "Mercury is the closest planet to the sun. Neptune is the farthest.",
    quick: true,
  },
  {
    id: "sci-g3-13",
    subject: "science",
    grade: "3",
    standard: "ESS.3.1.1",
    skill: "Sun and solar system",
    prompt: "What does Earth travel around once each year?",
    choices: ["The sun", "The moon", "Mars", "The stars"],
    answer: 0,
    explanation: "Earth orbits the sun. One trip around the sun takes about one year.",
    quick: true,
  },
  {
    id: "sci-g3-14",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.2",
    skill: "Land features",
    prompt: "Land with water all around it is called an...",
    choices: ["Island", "Valley", "Canyon", "Mountain"],
    answer: 0,
    explanation: "An island is land completely surrounded by water, like the Outer Banks islands of North Carolina.",
    quick: true,
  },
  {
    id: "sci-g3-15",
    subject: "science",
    grade: "3",
    standard: "ESS.3.2.2",
    skill: "Land features",
    prompt: "A deep, narrow valley with steep rock walls is a...",
    choices: ["Canyon", "Island", "Plain", "Beach"],
    answer: 0,
    explanation: "A canyon is a deep valley with steep sides, often carved by a river over a long time.",
    quick: true,
  },
  {
    id: "sci-g3-16",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.1",
    skill: "Bones and muscles",
    prompt: "Which bones protect your brain?",
    choices: ["Skull", "Ribs", "Kneecap", "Toe bones"],
    answer: 0,
    explanation: "Your skull is a hard case of bone that protects your brain. Your ribs protect your heart and lungs.",
    quick: true,
  },
  {
    id: "sci-g3-17",
    subject: "science",
    grade: "3",
    standard: "LS.3.1.1",
    skill: "Bones and muscles",
    prompt: "How do muscles move your bones?",
    choices: ["By pulling", "By pushing", "By melting", "By glowing"],
    answer: 0,
    explanation: "Muscles can only pull. They work in pairs: one pulls to bend a joint, another pulls to straighten it.",
    quick: true,
  },
  {
    id: "sci-g3-18",
    subject: "science",
    grade: "3",
    standard: "LS.3.2.2",
    skill: "Plant life cycles",
    prompt: "A bean plant's life cycle begins with a...",
    choices: ["Seed", "Flower", "Leaf", "Stem"],
    answer: 0,
    explanation: "A seed sprouts (germinates), grows into a plant, makes flowers, and the flowers make new seeds.",
    quick: true,
  },
];
export default questions;
