import type { Question } from "../../types";
// Grade 1 science — NC Standard Course of Study for Science (2023). Pushes, pulls and gravity (PS.1.1),
// the day and night sky (ESS.1.1), Earth materials such as rocks, soil and water (ESS.1.2), and what plants
// and animals need and how they depend on their surroundings (LS.1.1, LS.1.2).
const questions: Question[] = [
  {
    id: "sci-g1-01",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "What makes a wagon start to move?",
    choices: ["A push or pull", "Nothing", "A sound", "Its color"],
    answer: 0,
    explanation: "Things start moving when something pushes or pulls them. A wagon will not move by itself.",
    quick: true,
  },
  {
    id: "sci-g1-02",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Gravity",
    prompt: "What pulls things down to the ground?",
    choices: ["Gravity", "Wind", "Light", "Sound"],
    answer: 0,
    explanation: "Gravity is a pull that brings things down toward the ground. That is why a dropped apple falls.",
    quick: true,
  },
  {
    id: "sci-g1-03",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "A ball rolls slowest on which ground?",
    choices: ["Thick grass", "Smooth floor", "Ice", "A slide"],
    answer: 0,
    explanation: "Thick grass rubs against the ball and slows it down. Smooth things like ice let it roll easily.",
    quick: true,
  },
  {
    id: "sci-g1-04",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "Which push makes a toy car go the farthest?",
    choices: ["A strong push", "A soft push", "A tiny tap", "No push"],
    answer: 0,
    explanation: "A strong push gives the car more motion, so it goes farther than after a soft push.",
    quick: true,
  },
  {
    id: "sci-g1-05",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "What do we see in the sky in the daytime?",
    choices: ["The sun", "Many stars", "A dark sky", "Fireflies"],
    answer: 0,
    explanation: "In the daytime we see the sun. At night the sky is dark and we can see the moon and stars.",
    quick: true,
  },
  {
    id: "sci-g1-06",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Where does the sun seem to come up in the morning?",
    choices: ["East", "West", "North", "South"],
    answer: 0,
    explanation: "The sun seems to rise in the east and set in the west. It looks like it moves across the sky.",
    quick: true,
  },
  {
    id: "sci-g1-07",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Why can't we see stars in the day?",
    choices: ["Sun too bright", "They go away", "They fall down", "They turn off"],
    answer: 0,
    explanation: "The stars are still there in the day. The sun is so bright that we cannot see them.",
    quick: true,
  },
  {
    id: "sci-g1-08",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Over a month, the moon's shape seems to...",
    choices: ["Change", "Stay the same", "Turn square", "Turn red"],
    answer: 0,
    explanation: "The moon looks like it changes shape. Sometimes it is a thin sliver and sometimes it is full and round.",
    quick: true,
  },
  {
    id: "sci-g1-09",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Which Earth material can you pour?",
    choices: ["Water", "A boulder", "A mountain", "A big rock"],
    answer: 0,
    explanation: "Water is a liquid, so you can pour it. Rocks and boulders are solid and keep their shape.",
    quick: true,
  },
  {
    id: "sci-g1-10",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Most plants grow best in which Earth material?",
    choices: ["Soil", "Bare rock", "Plastic", "Pavement"],
    answer: 0,
    explanation: "Soil holds water and has bits of old plants that help new plants grow.",
    quick: true,
  },
  {
    id: "sci-g1-11",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Tiny pieces of broken rock are called...",
    choices: ["Sand", "Water", "Air", "Clouds"],
    answer: 0,
    explanation: "Sand is made of tiny bits of rock. Over a long time, big rocks break into smaller pieces.",
    quick: true,
  },
  {
    id: "sci-g1-12",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "How can we sort a pile of rocks?",
    choices: ["By size, color", "By their smell", "By their names", "By their mood"],
    answer: 0,
    explanation: "We can sort rocks by what we see and feel, like size, color and how rough or smooth they are.",
    quick: true,
  },
  {
    id: "sci-g1-13",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "What plants need",
    prompt: "What do plants need to grow?",
    choices: ["Sunlight", "Candy", "Darkness", "Toys"],
    answer: 0,
    explanation: "Plants need sunlight, water and air to grow. They use sunlight to make their own food.",
    quick: true,
  },
  {
    id: "sci-g1-14",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "Plant parts",
    prompt: "Which part of a plant takes in water?",
    choices: ["Roots", "Flower", "Fruit", "Seed"],
    answer: 0,
    explanation: "Roots grow in the soil and soak up water for the plant. They also hold the plant in place.",
    quick: true,
  },
  {
    id: "sci-g1-15",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "Plants and animals help each other",
    prompt: "How do bees help flowers?",
    choices: ["Carry pollen", "Eat leaves", "Dig roots", "Break stems"],
    answer: 0,
    explanation: "Bees carry pollen from flower to flower. This helps the plants make seeds.",
    quick: true,
  },
  {
    id: "sci-g1-16",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "Where does a fish live?",
    choices: ["Water", "A tree", "Desert sand", "A nest"],
    answer: 0,
    explanation: "Fish live in water. They use gills to get air from the water.",
    quick: true,
  },
  {
    id: "sci-g1-17",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "What do many birds use to build nests?",
    choices: ["Twigs, grass", "Glass", "Metal", "Ice cubes"],
    answer: 0,
    explanation: "Birds gather twigs, grass and leaves from around them to build nests.",
    quick: true,
  },
  {
    id: "sci-g1-18",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "Why does a rabbit need a hiding place?",
    choices: ["To stay safe", "To get taller", "To turn green", "To eat rocks"],
    answer: 0,
    explanation: "Animals need shelter to stay safe from danger and bad weather.",
    quick: true,
  },
];
export default questions;
