import type { Question } from "../../types";
// Grade 1 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Past and present, people who changed communities, timelines (1.H.1.1, 1.H.1);
// landforms, map symbols and directions (1.G.1.1, 1.G.1.2, 1.G.1); community helpers, making rules and laws, voting (1.C&G.1.1, 1.C&G.1.2, 1.C&G.1);
// scarcity, supply and demand, goods, services and saving (1.E.1.1, 1.E.1.2, 1.E.1); traditions and languages (1.B.1.1, 1.B.1).
const questions: Question[] = [
  {
    id: "soc-g1-01",
    subject: "social",
    grade: "1",
    standard: "1.G.1.2",
    skill: "Map skills",
    prompt: "The part of a map that explains its symbols is the...",
    choices: ["Map key", "Title", "Compass", "Border"],
    answer: 0,
    explanation: "The map key (legend) tells what each symbol on the map means.",
    quick: true,
  },
  {
    id: "soc-g1-02",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map skills",
    prompt: "A compass rose on a map shows...",
    choices: ["Directions", "Weather", "Time", "Money"],
    answer: 0,
    explanation: "A compass rose shows north, south, east and west.",
    quick: true,
  },
  {
    id: "soc-g1-03",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map skills",
    prompt: "Which direction is opposite of north?",
    choices: ["South", "East", "West", "Up"],
    answer: 0,
    explanation: "North and south are opposites. East and west are opposites too.",
    quick: true,
  },
  {
    id: "soc-g1-04",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms and water",
    prompt: "A very tall, rocky landform is a...",
    choices: ["Mountain", "Lake", "Valley", "Plain"],
    answer: 0,
    explanation: "Mountains are the highest landforms. North Carolina has mountains in the west.",
    quick: true,
  },
  {
    id: "soc-g1-05",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms and water",
    prompt: "Which is a body of water?",
    choices: ["Ocean", "Hill", "Desert", "Forest"],
    answer: 0,
    explanation: "Oceans, lakes and rivers are bodies of water.",
    quick: true,
  },
  {
    id: "soc-g1-06",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "A timeline shows events in...",
    choices: ["Order", "Color", "Size", "Secret"],
    answer: 0,
    explanation: "A timeline puts events in the order they happened, from first to last.",
    quick: true,
  },
  {
    id: "soc-g1-07",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "Before cars, many people traveled by...",
    choices: ["Horse", "Airplane", "Rocket", "Subway"],
    answer: 0,
    explanation: "Long ago, people rode horses or used wagons. Transportation has changed over time.",
    quick: true,
  },
  {
    id: "soc-g1-08",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "A photo taken 100 years ago shows the...",
    choices: ["Past", "Future", "Present", "Next week"],
    answer: 0,
    explanation: "Old photos show us what life was like in the past.",
    quick: true,
  },
  {
    id: "soc-g1-09",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Laws and leaders",
    prompt: "Laws are rules made for a...",
    choices: ["Community", "Toy box", "Board game", "Recess"],
    answer: 0,
    explanation: "Laws are rules for everyone in a community, state or country.",
    quick: true,
  },
  {
    id: "soc-g1-10",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Laws and leaders",
    prompt: "Who leads a town or city?",
    choices: ["A mayor", "A coach", "A doctor", "A chef"],
    answer: 0,
    explanation: "A mayor is a leader of a town or city government.",
    quick: true,
  },
  {
    id: "soc-g1-11",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Voting",
    prompt: "Voting is a way to...",
    choices: ["Make a choice", "Get a snack", "Take a nap", "Build a road"],
    answer: 0,
    explanation: "When we vote, each person gets to help make a group choice.",
    quick: true,
  },
  {
    id: "soc-g1-12",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Goods and services",
    prompt: "Something you can buy and hold is a...",
    choices: ["Good", "Service", "Law", "Map"],
    answer: 0,
    explanation: "Goods are things you can touch, like apples and shoes.",
    quick: true,
  },
  {
    id: "soc-g1-13",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Goods and services",
    prompt: "A haircut is a...",
    choices: ["Service", "Good", "Need", "Tax"],
    answer: 0,
    explanation: "A service is work someone does for you, like cutting hair.",
    quick: true,
  },
  {
    id: "soc-g1-14",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Saving",
    prompt: "Keeping money to use later is...",
    choices: ["Saving", "Spending", "Borrowing", "Losing"],
    answer: 0,
    explanation: "When you save, you keep money now so you can use it later.",
    quick: true,
  },
  {
    id: "soc-g1-15",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Trade",
    prompt: "You give a sticker and get a pencil. This is a...",
    choices: ["Trade", "Tax", "Vote", "Map"],
    answer: 0,
    explanation: "A trade is when people swap things with each other.",
    quick: true,
  },
  {
    id: "soc-g1-16",
    subject: "social",
    grade: "1",
    standard: "1.B.1",
    skill: "Traditions",
    prompt: "Special ways a family celebrates are...",
    choices: ["Traditions", "Laws", "Maps", "Jobs"],
    answer: 0,
    explanation: "Traditions are customs passed down in families and communities.",
    quick: true,
  },
  {
    id: "soc-g1-17",
    subject: "social",
    grade: "1",
    standard: "1.B.1.1",
    skill: "Traditions",
    prompt: "Diwali, Hanukkah and Christmas all use...",
    choices: ["Lights", "Snowballs", "Kites", "Masks"],
    answer: 0,
    explanation: "Diwali is a festival of lights, Hanukkah candles are lit on a menorah, and many people use lights at Christmas.",
    quick: true,
  },
  {
    id: "soc-g1-18",
    subject: "social",
    grade: "1",
    standard: "1.B.1.1",
    skill: "Languages",
    prompt: "People around the world speak many...",
    choices: ["Languages", "Maps", "Moons", "Rules"],
    answer: 0,
    explanation: "People speak many languages, like English, Spanish, Cherokee and Chinese.",
    quick: true,
  },
  {
    id: "soc-g1-19",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms",
    prompt: "A low area of land between mountains is a...",
    choices: ["Valley", "Peak", "Island", "Ocean"],
    answer: 0,
    explanation: "A valley is low land between hills or mountains. Rivers often flow through valleys.",
    quick: true,
  },
  {
    id: "soc-g1-20",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms",
    prompt: "A dry place that gets very little rain is a...",
    choices: ["Desert", "Lake", "Swamp", "Rainforest"],
    answer: 0,
    explanation: "Deserts get very little rain. Some are hot and some are cold.",
    quick: true,
  },
  {
    id: "soc-g1-21",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms",
    prompt: "A large, flat area of land is a...",
    choices: ["Plain", "Mountain", "Hill", "Canyon"],
    answer: 0,
    explanation: "Plains are wide and flat. They are good places for farms.",
    quick: true,
  },
  {
    id: "soc-g1-22",
    subject: "social",
    grade: "1",
    standard: "1.G.1.1",
    skill: "Landforms and water",
    prompt: "A long stream of moving water is a...",
    choices: ["River", "Desert", "Island", "Hill"],
    answer: 0,
    explanation: "A river is moving water that flows to a lake, another river or the ocean.",
    quick: true,
  },
  {
    id: "soc-g1-23",
    subject: "social",
    grade: "1",
    standard: "1.G.1.2",
    skill: "Map symbols",
    prompt: "On many maps, a star shows a...",
    choices: ["Capital city", "Lake", "Mountain", "Forest"],
    answer: 0,
    explanation: "A star often marks a capital city. Raleigh has a star on a map of North Carolina.",
    quick: true,
  },
  {
    id: "soc-g1-24",
    subject: "social",
    grade: "1",
    standard: "1.G.1.2",
    skill: "Map symbols",
    prompt: "On a map, a thin blue line usually shows a...",
    choices: ["River", "Road", "Border", "Railroad"],
    answer: 0,
    explanation: "Map makers draw rivers as thin blue lines. The map key tells you for sure.",
    quick: true,
  },
  {
    id: "soc-g1-25",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Directions",
    prompt: "The sun sets in the...",
    choices: ["West", "East", "North", "South"],
    answer: 0,
    explanation: "The sun rises in the east and sets in the west.",
    quick: true,
  },
  {
    id: "soc-g1-26",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Maps and globes",
    prompt: "A globe shows that most of Earth is covered by...",
    choices: ["Water", "Land", "Ice", "Sand"],
    answer: 0,
    explanation: "About 70 percent of Earth is covered by water, mostly oceans.",
    quick: true,
  },
  {
    id: "soc-g1-27",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map directions",
    passage:
      "A map of a park has a compass rose. The pond is north of the playground. The picnic tables are east of the playground. The gate is south of the playground.",
    prompt: "What is north of the playground?",
    choices: ["The pond", "The picnic tables", "The parking lot", "The gate"],
    answer: 0,
    explanation: "The pond is north of the playground. The picnic tables are east of it.",
  },
  {
    id: "soc-g1-28",
    subject: "social",
    grade: "1",
    standard: "1.H.1.1",
    skill: "People who made a difference",
    prompt: "In 1969, Neil Armstrong was the first person to walk on the...",
    choices: ["Moon", "Ocean", "Mountain", "Sun"],
    answer: 0,
    explanation: "Neil Armstrong stepped onto the Moon on July 20, 1969.",
    quick: true,
  },
  {
    id: "soc-g1-29",
    subject: "social",
    grade: "1",
    standard: "1.H.1.1",
    skill: "People who made a difference",
    prompt: "The Wright brothers built the first successful powered...",
    choices: ["Airplane", "Car", "Train", "Boat"],
    answer: 0,
    explanation: "In 1903, Orville and Wilbur Wright flew their airplane in Kitty Hawk, North Carolina.",
    quick: true,
  },
  {
    id: "soc-g1-30",
    subject: "social",
    grade: "1",
    standard: "1.H.1.1",
    skill: "People who made a difference",
    prompt: "In 1955, Rosa Parks bravely refused to give up her seat on a...",
    choices: ["Bus", "Train", "Plane", "Boat"],
    answer: 0,
    explanation: "Rosa Parks was arrested for not giving her seat to a white man. Her courage helped start a bus boycott for equal rights.",
    quick: true,
  },
  {
    id: "soc-g1-31",
    subject: "social",
    grade: "1",
    standard: "1.H.1.1",
    skill: "People who made a difference",
    prompt: "In 1960, six-year-old Ruby Bridges was the first Black student at her new...",
    choices: ["School", "Store", "Bank", "Farm"],
    answer: 0,
    explanation: "Ruby Bridges bravely walked into an all-white school in New Orleans. She helped schools become open to all children.",
    quick: true,
  },
  {
    id: "soc-g1-32",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "Today many people send quick messages by...",
    choices: ["Phone", "Pigeon", "Wagon", "Candle"],
    answer: 0,
    explanation: "Long ago people sent letters that took days. Today phones send messages in seconds.",
    quick: true,
  },
  {
    id: "soc-g1-33",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Timelines",
    prompt: "On most timelines, the earliest event is on the...",
    choices: ["Left", "Right", "Top", "Middle"],
    answer: 0,
    explanation: "Timelines are read from left to right, so the earliest event is on the left.",
    quick: true,
  },
  {
    id: "soc-g1-34",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Timelines",
    passage:
      "Mia's timeline: 2018 – Mia was born. 2022 – Mia learned to ride a bike. 2024 – Mia started first grade.",
    prompt: "What happened right after Mia learned to ride a bike?",
    choices: ["She started first grade", "She was born", "She learned to walk", "She finished high school"],
    answer: 0,
    explanation: "After 2022 comes 2024, when Mia started first grade.",
  },
  {
    id: "soc-g1-35",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1.1",
    skill: "Shaping communities",
    prompt: "Volunteers who clean up a park are helping their...",
    choices: ["Community", "Bank account", "Video game", "Bedroom"],
    answer: 0,
    explanation: "Volunteers give their time to help others. Cleaning a park helps the whole community.",
    quick: true,
  },
  {
    id: "soc-g1-36",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1.1",
    skill: "Community helpers",
    prompt: "Firefighters help the community by...",
    choices: ["Fighting fires", "Selling shoes", "Teaching math", "Baking bread"],
    answer: 0,
    explanation: "Firefighters put out fires and rescue people. They are community helpers.",
    quick: true,
  },
  {
    id: "soc-g1-37",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1.2",
    skill: "Making laws",
    prompt: "Who makes the laws for a town?",
    choices: ["Town council", "Teachers", "Kids", "Doctors"],
    answer: 0,
    explanation: "A town council, often led by the mayor, votes on the town's laws.",
    quick: true,
  },
  {
    id: "soc-g1-38",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1.2",
    skill: "Making rules",
    prompt: "A class votes on a rule. The choice with the most votes...",
    choices: ["Wins", "Loses", "Is erased", "Is a tie"],
    answer: 0,
    explanation: "When a group votes, the choice with the most votes usually wins. This is called majority rule.",
    quick: true,
  },
  {
    id: "soc-g1-39",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Laws",
    prompt: "Seat belt laws help keep people...",
    choices: ["Safe", "Hungry", "Sleepy", "Loud"],
    answer: 0,
    explanation: "Many laws are made to keep people safe, like wearing seat belts in cars.",
    quick: true,
  },
  {
    id: "soc-g1-40",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1.2",
    skill: "Making rules",
    passage:
      "Room 4 has a class fish. Many students want to feed it, and they argue about whose turn it is. The teacher asks the class to make a fair rule.",
    prompt: "Which rule is most fair?",
    choices: ["Take turns using a job chart", "The tallest student always feeds it", "Nobody ever feeds the fish", "Only the teacher's friend feeds it"],
    answer: 0,
    explanation: "A fair rule treats everyone the same. A job chart gives each student a turn.",
  },
  {
    id: "soc-g1-41",
    subject: "social",
    grade: "1",
    standard: "1.E.1.1",
    skill: "Scarcity",
    prompt: "There are 10 kids and only 5 swings. This is an example of...",
    choices: ["Scarcity", "Saving", "Voting", "Trade"],
    answer: 0,
    explanation: "Scarcity means there is not enough for everyone. The kids must take turns or choose.",
    quick: true,
  },
  {
    id: "soc-g1-42",
    subject: "social",
    grade: "1",
    standard: "1.E.1.2",
    skill: "Supply and demand",
    prompt: "Many people want a toy, but the store has only a few. The price will likely...",
    choices: ["Go up", "Go down", "Disappear", "Be free"],
    answer: 0,
    explanation: "When lots of people want something and there is little of it, the price usually goes up.",
    quick: true,
  },
  {
    id: "soc-g1-43",
    subject: "social",
    grade: "1",
    standard: "1.E.1.2",
    skill: "Supply and demand",
    prompt: "Stores have lots of strawberries in summer. Prices are likely...",
    choices: ["Lower", "Higher", "Free", "Gone"],
    answer: 0,
    explanation: "When there is a lot of something, sellers often lower the price so people will buy it.",
    quick: true,
  },
  {
    id: "soc-g1-44",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Producers",
    prompt: "A person who makes goods is a...",
    choices: ["Producer", "Consumer", "Voter", "Mayor"],
    answer: 0,
    explanation: "Producers make goods or give services. Consumers buy and use them.",
    quick: true,
  },
  {
    id: "soc-g1-45",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Saving",
    prompt: "A jar where you save coins is a...",
    choices: ["Piggy bank", "Toolbox", "Lunchbox", "Mailbox"],
    answer: 0,
    explanation: "A piggy bank holds money you are saving for later.",
    quick: true,
  },
  {
    id: "soc-g1-46",
    subject: "social",
    grade: "1",
    standard: "1.B.1.1",
    skill: "Traditions",
    prompt: "Many families celebrate Lunar New Year with gifts of money in red...",
    choices: ["Envelopes", "Pumpkins", "Stockings", "Baskets"],
    answer: 0,
    explanation: "In many Asian cultures, red envelopes with money are given for good luck at Lunar New Year.",
    quick: true,
  },
  {
    id: "soc-g1-47",
    subject: "social",
    grade: "1",
    standard: "1.B.1.1",
    skill: "Traditions",
    prompt: "Kwanzaa is a holiday that celebrates African American...",
    choices: ["Culture", "Sports", "Weather", "Inventions"],
    answer: 0,
    explanation: "Kwanzaa, held from December 26 to January 1, honors African heritage in African American culture.",
    quick: true,
  },
  {
    id: "soc-g1-48",
    subject: "social",
    grade: "1",
    standard: "1.B.1",
    skill: "Traditions",
    passage:
      "Sofia's family speaks Spanish at home and makes tamales at Christmas. Amir's family speaks Arabic and shares a big meal to celebrate Eid.",
    prompt: "What do both families have?",
    choices: ["Traditions they share as a family", "The same language", "The same holiday", "The same food"],
    answer: 0,
    explanation: "Both families have traditions, even though their languages, foods and holidays are different.",
  },
];

export default questions;
