import type { Question } from "../../types";
// Grade 4 social studies — NC Standard Course of Study for Social Studies (adopted 2021). North Carolina history: American Indians in NC (4.H.1.1), changing roles (4.H.1.2),
// revolution, reform and resistance (4.H.1.3), Roanoke and the Wright brothers (4.H.1); NC geography and movement (4.G.1, 4.G.1.2); state leaders and government (4.C&G.1.1, 4.C&G.1);
// scarcity and NC industries (4.E.1.1, 4.E.1); NC traditions and art (4.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g4-01",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    prompt: "Which group lived in NC long before Europeans arrived?",
    choices: ["Tuscarora", "Pilgrims", "Vikings", "Spanish"],
    answer: 0,
    explanation: "The Tuscarora, Cherokee, Catawba and other American Indian nations lived in NC for thousands of years before Europeans came.",
    quick: true,
  },
  {
    id: "soc-g4-02",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    passage:
      "In 1838, the U.S. Army forced most Cherokee people to leave their homes in the Southeast and walk west on the Trail of Tears. Some Cherokee hid in the North Carolina mountains or had legal claims to stay. Later they were able to keep land there.",
    prompt: "Why is there still a Cherokee nation in western NC today?",
    choices: ["Some Cherokee stayed in the mountains and kept land there", "The Army never came to NC", "The Cherokee moved there in 1900", "Settlers gave the whole state back"],
    answer: 0,
    explanation: "Some Cherokee avoided removal. Their descendants are the Eastern Band of Cherokee Indians, based at Qualla Boundary.",
  },
  {
    id: "soc-g4-03",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "The English colony that vanished from Roanoke Island is called the...",
    choices: ["Lost Colony", "Jamestown", "Plymouth", "New Bern"],
    answer: 0,
    explanation: "The 1587 Roanoke colony disappeared by 1590. No one knows for sure what happened.",
    quick: true,
  },
  {
    id: "soc-g4-04",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "The first English child born in the Americas was...",
    choices: ["Virginia Dare", "Pocahontas", "Betsy Ross", "Dolley Madison"],
    answer: 0,
    explanation: "Virginia Dare was born on Roanoke Island in 1587, in the Lost Colony.",
    quick: true,
  },
  {
    id: "soc-g4-05",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Revolution in NC",
    prompt: "The Halifax Resolves (April 12, 1776) were an early official call for...",
    choices: ["Independence", "Lower taxes", "A new king", "More soldiers"],
    answer: 0,
    explanation: "NC's Halifax Resolves were the first official action by a colony calling for independence from Britain. The date is on NC's flag.",
    quick: true,
  },
  {
    id: "soc-g4-06",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Civil rights in NC",
    prompt: "In 1960, four students held a sit-in at a Greensboro lunch counter to protest...",
    choices: ["Segregation", "High prices", "School hours", "New roads"],
    answer: 0,
    explanation: "The Greensboro Four sat at a whites-only counter at Woolworth's. Their peaceful protest spread to many cities.",
    quick: true,
  },
  {
    id: "soc-g4-07",
    subject: "social",
    grade: "4",
    standard: "4.H.1.2",
    skill: "Changing roles",
    prompt: "During World War II, many NC women took new jobs in...",
    choices: ["Shipyards", "Space", "Video games", "Computers"],
    answer: 0,
    explanation: "With many men in the military, women built ships in Wilmington and worked in factories. Women's roles changed.",
    quick: true,
  },
  {
    id: "soc-g4-08",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Wright brothers",
    prompt: "The Wright brothers made the first powered airplane flight in 1903 near...",
    choices: ["Kitty Hawk", "Raleigh", "Asheville", "Charlotte"],
    answer: 0,
    explanation: "On December 17, 1903, Orville and Wilbur Wright flew at Kill Devil Hills near Kitty Hawk.",
    quick: true,
  },
  {
    id: "soc-g4-09",
    subject: "social",
    grade: "4",
    standard: "4.G.1.2",
    skill: "Movement in NC",
    passage:
      "In 1856, the North Carolina Railroad was finished. It ran from Goldsboro through Raleigh and Greensboro to Charlotte. Before this, Piedmont farmers hauled crops for days by wagon on muddy roads.",
    prompt: "How did the railroad most likely change towns along its route?",
    choices: ["They grew as trade became easier", "They shrank because no one traveled", "Nothing changed", "Farmers stopped growing crops"],
    answer: 0,
    explanation: "Railroads moved crops and goods faster and cheaper. Towns along the line grew into trading centers.",
  },
  {
    id: "soc-g4-10",
    subject: "social",
    grade: "4",
    standard: "4.G.1",
    skill: "NC coast",
    prompt: "Many shipwrecks off NC's coast earned it the name Graveyard of the...",
    choices: ["Atlantic", "Pacific", "Piedmont", "Rivers"],
    answer: 0,
    explanation: "Shallow shoals and storms near Cape Hatteras sank many ships, so the area is called the Graveyard of the Atlantic.",
    quick: true,
  },
  {
    id: "soc-g4-11",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.1",
    skill: "State leaders",
    prompt: "Who leads NC's executive branch?",
    choices: ["Governor", "Lt. Governor", "Mayor", "Chief Justice"],
    answer: 0,
    explanation: "The governor is elected by NC voters to lead the executive branch and carry out state laws.",
    quick: true,
  },
  {
    id: "soc-g4-12",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1",
    skill: "State government",
    prompt: "NC's General Assembly has a House of Representatives and a...",
    choices: ["Senate", "Court", "Cabinet", "Council"],
    answer: 0,
    explanation: "The General Assembly is NC's legislative branch. It has two houses: the Senate and the House.",
    quick: true,
  },
  {
    id: "soc-g4-13",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1",
    skill: "State government",
    prompt: "North Carolina's state capital is...",
    choices: ["Raleigh", "Charlotte", "Durham", "Greensboro"],
    answer: 0,
    explanation: "Raleigh was founded in 1792 to be NC's capital. The General Assembly meets there.",
    quick: true,
  },
  {
    id: "soc-g4-14",
    subject: "social",
    grade: "4",
    standard: "4.E.1.1",
    skill: "Scarcity",
    passage:
      "During a long summer drought in eastern North Carolina, the rivers ran low. Farmers had to choose which fields to water, and some crops dried up.",
    prompt: "What is the best example of scarcity in this story?",
    choices: ["There is not enough water for all the crops", "The farmers have too much corn", "Prices of seeds went down", "The town built a new school"],
    answer: 0,
    explanation: "Scarcity means limited resources. With little water, farmers must decide which fields to water first.",
  },
  {
    id: "soc-g4-15",
    subject: "social",
    grade: "4",
    standard: "4.E.1",
    skill: "NC economy",
    prompt: "For many years, NC's most valuable cash crop was...",
    choices: ["Tobacco", "Coffee", "Rice", "Oranges"],
    answer: 0,
    explanation: "Tobacco was NC's leading cash crop for much of its history. Today NC grows many crops and raises hogs and poultry.",
    quick: true,
  },
  {
    id: "soc-g4-16",
    subject: "social",
    grade: "4",
    standard: "4.E.1",
    skill: "NC economy",
    prompt: "Furniture making grew in NC's Piedmont because of plentiful...",
    choices: ["Hardwood trees", "Gold", "Oil", "Coal"],
    answer: 0,
    explanation: "Forests of hardwood made High Point and nearby towns centers of furniture making.",
    quick: true,
  },
  {
    id: "soc-g4-17",
    subject: "social",
    grade: "4",
    standard: "4.B.1.1",
    skill: "NC traditions",
    prompt: "Bluegrass and old-time music are traditions of NC's...",
    choices: ["Mountains", "Outer Banks", "Sandhills", "Coastal Plain"],
    answer: 0,
    explanation: "Mountain communities kept old-time fiddle and banjo music alive, and bluegrass grew from it.",
    quick: true,
  },
  {
    id: "soc-g4-18",
    subject: "social",
    grade: "4",
    standard: "4.B.1.1",
    skill: "NC traditions",
    prompt: "Seagrove, NC, is famous for which traditional art?",
    choices: ["Pottery", "Glassmaking", "Painting", "Weaving"],
    answer: 0,
    explanation: "Potters have worked in Seagrove for over 200 years using local clay.",
    quick: true,
  },
];

export default questions;
