import type { Question } from "../../types";

// Grade 7 ELA — NC Standard Course of Study for ELA (2017). RL.7.1, RL.7.2, RL.7.3, RL.7.4, RL.7.5, RL.7.6, RI.7.2, RI.7.3, RI.7.6, RI.7.8, W.7.1, L.7.1, L.7.2, L.7.3, L.7.4, L.7.5
const questions: Question[] = [
  {
    id: "ela-g7-01",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Phrases and clauses",
    prompt: "Which is a dependent clause?",
    choices: ["when it rained", "the dog barked", "I ran home", "she smiled"],
    answer: 0,
    explanation: "A dependent clause has a subject and verb but can't stand alone. 'When it rained' needs more.",
    quick: true,
  },
  {
    id: "ela-g7-02",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Sentence types",
    prompt: "'I ran, and she walked.' What type of sentence is this?",
    choices: ["compound", "simple", "complex", "fragment"],
    answer: 0,
    explanation: "Two independent clauses joined by a comma and 'and' make a compound sentence.",
    quick: true,
  },
  {
    id: "ela-g7-03",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Sentence types",
    prompt: "'Although it was late, we kept reading.' What type of sentence is this?",
    choices: ["complex", "simple", "compound", "run-on"],
    answer: 0,
    explanation: "A dependent clause (Although it was late) plus an independent clause makes a complex sentence.",
    quick: true,
  },
  {
    id: "ela-g7-04",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Phrases and clauses",
    prompt: "Which is a phrase, not a clause?",
    choices: ["in the morning", "we ate lunch", "she laughed", "if he calls"],
    answer: 0,
    explanation: "A phrase has no subject-verb pair. 'In the morning' is a prepositional phrase.",
    quick: true,
  },
  {
    id: "ela-g7-05",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root bene (as in benefit) means...",
    choices: ["good", "bad", "war", "ten"],
    answer: 0,
    explanation: "Bene means good or well. A benefit is something good.",
    quick: true,
  },
  {
    id: "ela-g7-06",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Prefixes",
    prompt: "The prefix anti- (as in antifreeze) means...",
    choices: ["against", "before", "many", "after"],
    answer: 0,
    explanation: "Anti- means against. Antifreeze works against freezing.",
    quick: true,
  },
  {
    id: "ela-g7-07",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Allusion",
    prompt: "Calling a strong person 'a Hercules' is an example of...",
    choices: ["allusion", "simile", "pun", "oxymoron"],
    answer: 0,
    explanation: "An allusion refers to a well-known story or figure, here the hero of Greek myth.",
    quick: true,
  },
  {
    id: "ela-g7-08",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Connotation",
    prompt: "Which word describes confidence in a positive way?",
    choices: ["self-assured", "arrogant", "cocky", "smug"],
    answer: 0,
    explanation: "Arrogant, cocky, and smug all suggest too much pride. Self-assured is positive.",
    quick: true,
  },
  {
    id: "ela-g7-09",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Analogies",
    prompt: "Author is to novel as composer is to...",
    choices: ["symphony", "piano", "singer", "book"],
    answer: 0,
    explanation: "This is a creator-to-creation analogy: an author writes a novel; a composer writes a symphony.",
    quick: true,
  },
  {
    id: "ela-g7-10",
    subject: "ela",
    grade: "7",
    standard: "RL.7.4",
    skill: "Sound devices",
    prompt: "'Seven silly snakes slid south' is an example of...",
    choices: ["alliteration", "rhyme", "metaphor", "irony"],
    answer: 0,
    explanation: "Alliteration repeats the same beginning consonant sound in nearby words.",
    quick: true,
  },
  {
    id: "ela-g7-11",
    subject: "ela",
    grade: "7",
    standard: "RL.7.6",
    skill: "Point of view",
    prompt: "When characters see the same event differently, they have different...",
    choices: ["points of view", "settings", "plots", "authors"],
    answer: 0,
    explanation: "Point of view is how a character sees and feels about events.",
    quick: true,
  },
  {
    id: "ela-g7-12",
    subject: "ela",
    grade: "7",
    standard: "W.7.1",
    skill: "Argument writing",
    prompt: "In an argument, an opposing viewpoint is called a...",
    choices: ["counterclaim", "thesis", "reason", "conclusion"],
    answer: 0,
    explanation: "A counterclaim is the other side's position. Strong arguments acknowledge and answer it.",
    quick: true,
  },
  {
    id: "ela-g7-13",
    subject: "ela",
    grade: "7",
    standard: "W.7.1",
    skill: "Transitions",
    prompt: "Which transition signals a contrast?",
    choices: ["however", "also", "first", "for example"],
    answer: 0,
    explanation: "However signals a turn to a different or opposite idea.",
    quick: true,
  },
  {
    id: "ela-g7-14",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Misplaced modifiers",
    prompt: "Which sentence has a misplaced modifier?",
    choices: ["I saw a deer driving to school.", "Driving to school, I saw a deer.", "I saw a deer while driving to school.", "While I drove to school, I saw a deer."],
    answer: 0,
    explanation: "In the first sentence, 'driving to school' sits next to deer, so it sounds like the deer is driving.",
  },
  {
    id: "ela-g7-15",
    subject: "ela",
    grade: "7",
    standard: "RL.7.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "Every year, Eli's grandfather planted an oak sapling, though he knew he would never sit in its shade. 'Why bother?' Eli asked. His grandfather smiled and pointed to the tall oaks around their farm. 'Someone planted these for me.'",
    choices: ["We should give to the future, as others gave to us.", "Oak trees grow very fast.", "Farming is too difficult.", "Grandparents know everything."],
    answer: 0,
    explanation: "The grandfather plants trees for people after him because someone did the same for him.",
  },
  {
    id: "ela-g7-16",
    subject: "ela",
    grade: "7",
    standard: "RI.7.8",
    skill: "Evaluating arguments",
    prompt: "What is the biggest weakness in this argument?",
    passage: "Our school should ban homework on weekends. My friend said she was tired on Monday because of homework. Also, a famous athlete once said rest is important. Therefore, weekend homework clearly harms all students.",
    choices: ["Weak evidence leads to a broad conclusion.", "It does not state a claim.", "It uses too many statistics.", "It is written in first person."],
    answer: 0,
    explanation: "One friend's experience and a vague quote can't prove homework 'clearly harms all students.'",
  },
  {
    id: "ela-g7-17",
    subject: "ela",
    grade: "7",
    standard: "RL.7.6",
    skill: "Point of view",
    prompt: "How do the characters' points of view differ?",
    passage: "To Carla, the storm was an adventure. She pressed her face to the window, counting lightning flashes. Her little brother, Tomas, hid under a blanket, sure that each thunderclap meant the roof would fall.",
    choices: ["Carla is excited; Tomas is afraid.", "Both are afraid.", "Carla is afraid; Tomas is excited.", "Both are bored."],
    answer: 0,
    explanation: "Carla counts lightning like an adventure, while Tomas hides, sure the roof will fall.",
  },
  {
    id: "ela-g7-18",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Context clues",
    prompt: "What does impasse most likely mean?",
    passage: "The negotiations reached an impasse; neither side would give up anything, and after six hours, both teams left the room without an agreement.",
    choices: ["a point with no progress", "a quick victory", "a friendly lunch", "a new rule"],
    answer: 0,
    explanation: "Neither side gave anything and they left without agreement, so an impasse is a deadlock.",
  },
  {
    id: "ela-g7-19",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Greek roots",
    prompt: "The Greek root psych (as in psychology) means...",
    choices: ["mind", "body", "life", "fear"],
    answer: 0,
    explanation: "Psych means mind. Psychology is the study of the mind.",
    quick: true,
  },
  {
    id: "ela-g7-20",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Latin roots",
    prompt: "The Latin root cred (as in credible) means...",
    choices: ["believe", "give", "break", "speak"],
    answer: 0,
    explanation: "Cred means believe. A credible source is one you can believe.",
    quick: true,
  },
  {
    id: "ela-g7-21",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Latin prefixes",
    prompt: "The prefix circum- (as in circumference) means...",
    choices: ["around", "across", "half", "under"],
    answer: 0,
    explanation: "Circum- means around. The circumference is the distance around a circle.",
    quick: true,
  },
  {
    id: "ela-g7-22",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Greek roots",
    prompt: "The Greek root path (as in sympathy) means...",
    choices: ["feeling", "road", "sound", "light"],
    answer: 0,
    explanation: "Path means feeling. Sympathy is feeling with someone.",
    quick: true,
  },
  {
    id: "ela-g7-23",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Suffixes",
    prompt: "The suffix -ous (as in courageous) means...",
    choices: ["full of", "without", "able to", "one who"],
    answer: 0,
    explanation: "-ous means full of. Courageous means full of courage.",
    quick: true,
  },
  {
    id: "ela-g7-24",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Connotation",
    prompt: "Which word for young has the most negative connotation?",
    choices: ["childish", "youthful", "childlike", "young"],
    answer: 0,
    explanation: "Childish suggests immature behavior. Youthful and childlike sound fresh or innocent.",
    quick: true,
  },
  {
    id: "ela-g7-25",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Metaphors",
    prompt: "'Time is a thief.' This is an example of a...",
    choices: ["metaphor", "simile", "pun", "hyperbole"],
    answer: 0,
    explanation: "It compares time to a thief without like or as, so it is a metaphor.",
    quick: true,
  },
  {
    id: "ela-g7-26",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Idioms",
    prompt: "'Bite the bullet' means to...",
    choices: ["endure it", "eat quickly", "start a fight", "give up"],
    answer: 0,
    explanation: "To bite the bullet is to face something hard or painful bravely.",
    quick: true,
  },
  {
    id: "ela-g7-27",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Phrases",
    prompt: "In 'The girl with red boots laughed,' 'with red boots' is what kind of phrase?",
    choices: ["prepositional", "infinitive", "gerund", "verb"],
    answer: 0,
    explanation: "It begins with the preposition with, so it is a prepositional phrase.",
    quick: true,
  },
  {
    id: "ela-g7-28",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Noun clauses",
    prompt: "In 'I know that she won,' the clause 'that she won' acts as a...",
    choices: ["noun", "adjective", "adverb", "verb"],
    answer: 0,
    explanation: "The clause answers 'I know what?' It is the object, so it works as a noun.",
    quick: true,
  },
  {
    id: "ela-g7-29",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Participles",
    prompt: "'Running late, Jo grabbed her keys.' 'Running late' is a...",
    choices: ["participle", "gerund", "infinitive", "clause"],
    answer: 0,
    explanation: "Running late describes Jo, so it is a participial phrase, not a gerund.",
    quick: true,
  },
  {
    id: "ela-g7-30",
    subject: "ela",
    grade: "7",
    standard: "L.7.2",
    skill: "Coordinate adjectives",
    prompt: "Which phrase punctuates coordinate adjectives correctly?",
    choices: ["long, hot day", "long hot, day", "long, hot, day", "long hot day,"],
    answer: 0,
    explanation: "Put a comma between adjectives that each describe the noun equally.",
    quick: true,
  },
  {
    id: "ela-g7-31",
    subject: "ela",
    grade: "7",
    standard: "L.7.2",
    skill: "Colons",
    prompt: "'Bring three things ___ a pen, paper, and a snack.' Which mark fits?",
    choices: ["colon", "semicolon", "comma", "apostrophe"],
    answer: 0,
    explanation: "A colon introduces a list after a complete sentence.",
    quick: true,
  },
  {
    id: "ela-g7-32",
    subject: "ela",
    grade: "7",
    standard: "L.7.3",
    skill: "Concise writing",
    prompt: "Which is the most concise way to say 'at this point in time'?",
    choices: ["now", "presently now", "in this time", "at this moment"],
    answer: 0,
    explanation: "Now says the same thing in one word.",
    quick: true,
  },
  {
    id: "ela-g7-33",
    subject: "ela",
    grade: "7",
    standard: "RL.7.4",
    skill: "Assonance",
    prompt: "Repeated vowel sounds in nearby words, like lake and fade, are called...",
    choices: ["assonance", "alliteration", "consonance", "onomatopoeia"],
    answer: 0,
    explanation: "Assonance repeats vowel sounds. Alliteration repeats beginning consonant sounds.",
    quick: true,
  },
  {
    id: "ela-g7-34",
    subject: "ela",
    grade: "7",
    standard: "RL.7.5",
    skill: "Poetic forms",
    prompt: "A poem with no set rhyme or meter is written in...",
    choices: ["free verse", "a sonnet", "a haiku", "a limerick"],
    answer: 0,
    explanation: "Free verse follows the natural rhythms of speech instead of a fixed pattern.",
    quick: true,
  },
  {
    id: "ela-g7-35",
    subject: "ela",
    grade: "7",
    standard: "RL.7.5",
    skill: "Drama terms",
    prompt: "A remark to the audience that other characters can't hear is an...",
    choices: ["aside", "monologue", "epilogue", "cue"],
    answer: 0,
    explanation: "An aside lets a character share private thoughts with the audience.",
    quick: true,
  },
  {
    id: "ela-g7-36",
    subject: "ela",
    grade: "7",
    standard: "RI.7.8",
    skill: "Sufficient evidence",
    prompt: "When an argument has too few examples, its evidence is...",
    choices: ["insufficient", "relevant", "credible", "biased"],
    answer: 0,
    explanation: "Insufficient means not enough. Strong claims need enough evidence.",
    quick: true,
  },
  {
    id: "ela-g7-37",
    subject: "ela",
    grade: "7",
    standard: "RI.7.6",
    skill: "Author's purpose",
    prompt: "An author who wants to change readers' minds is writing to...",
    choices: ["persuade", "inform", "entertain", "describe"],
    answer: 0,
    explanation: "Writing meant to change minds is persuasive.",
    quick: true,
  },
  {
    id: "ela-g7-38",
    subject: "ela",
    grade: "7",
    standard: "RL.7.6",
    skill: "Point of view",
    prompt: "A narrator who reports only actions and words, never thoughts, is...",
    choices: ["objective", "omniscient", "first person", "unreliable"],
    answer: 0,
    explanation: "An objective narrator acts like a camera, showing only what can be seen and heard.",
    quick: true,
  },
  {
    id: "ela-g7-39",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Sentence types",
    prompt: "'When it rained, we ran inside, and Sam laughed.' What type of sentence is this?",
    choices: ["compound-complex", "complex", "compound", "simple"],
    answer: 0,
    explanation: "It has two independent clauses and one dependent clause (When it rained).",
  },
  {
    id: "ela-g7-40",
    subject: "ela",
    grade: "7",
    standard: "RL.7.1",
    skill: "Making inferences",
    prompt: "What can you infer about the letter?",
    passage: "Grandma's hands trembled as she unfolded the faded letter. She read it twice, then pressed it to her chest and stared out the window at the empty road.",
    choices: ["It has strong personal meaning for her.", "It is a bill.", "It is from a stranger.", "It made her angry."],
    answer: 0,
    explanation: "Pressing it to her chest and staring at the road show it means a lot to her.",
  },
  {
    id: "ela-g7-41",
    subject: "ela",
    grade: "7",
    standard: "RL.7.3",
    skill: "Setting and character",
    prompt: "How does the setting shape Lio?",
    passage: "Living on the island, where the ferry came only twice a week, Lio learned to fix everything himself: bikes, fishing nets, even the generator.",
    choices: ["Isolation makes him self-reliant.", "It makes him lazy.", "It makes him leave the island.", "It makes him fear the ocean."],
    answer: 0,
    explanation: "With help far away, Lio learned to fix everything himself.",
  },
  {
    id: "ela-g7-42",
    subject: "ela",
    grade: "7",
    standard: "RL.7.4",
    skill: "Sound and meaning",
    prompt: "What effect do the repeated s and w sounds create?",
    passage: "The waves wash, whisper, and withdraw,\nSoft as a secret, slow as a sigh.",
    choices: ["a calm, hushing mood", "a loud, angry mood", "a fast, exciting pace", "a confusing mood"],
    answer: 0,
    explanation: "Soft s and w sounds imitate gentle waves and whispers.",
  },
  {
    id: "ela-g7-43",
    subject: "ela",
    grade: "7",
    standard: "RI.7.2",
    skill: "Central idea",
    prompt: "Which statement best states the central idea?",
    passage: "Coral reefs cover less than 1 percent of the ocean floor, yet they shelter about a quarter of all ocean species. Rising water temperatures cause coral bleaching, which can kill reefs and the creatures that depend on them.",
    choices: ["Reefs are vital habitats threatened by warming.", "Reefs cover much of the ocean floor.", "Bleaching makes coral pretty.", "Fish avoid coral reefs."],
    answer: 0,
    explanation: "The passage explains why reefs matter and how warming endangers them.",
  },
  {
    id: "ela-g7-44",
    subject: "ela",
    grade: "7",
    standard: "RI.7.3",
    skill: "Events and ideas",
    prompt: "According to the text, how did the railroad affect Millbrook?",
    passage: "After the railroad reached Millbrook in 1880, farmers could ship their crops to distant cities. The town's population tripled within ten years.",
    choices: ["It helped the town grow.", "It ruined the farms.", "It caused people to leave.", "Nothing changed."],
    answer: 0,
    explanation: "Farmers could ship crops far away, and the population tripled.",
  },
  {
    id: "ela-g7-45",
    subject: "ela",
    grade: "7",
    standard: "RI.7.6",
    skill: "Responding to opponents",
    prompt: "How does the author respond to opponents?",
    passage: "Some argue that cell phones distract students. While this can be true, phones also give students instant access to research tools, calculators, and dictionaries. Schools should teach responsible use rather than ban phones.",
    choices: ["Grants their point, then argues against a ban.", "Ignores them completely.", "Agrees phones should be banned.", "Insults them."],
    answer: 0,
    explanation: "The author admits phones can distract, then explains why teaching beats banning.",
  },
  {
    id: "ela-g7-46",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Context clues",
    prompt: "What does ambiguous mean?",
    passage: "The mayor's plan was so ambiguous that half the council thought it raised taxes and the other half thought it cut them.",
    choices: ["unclear", "popular", "expensive", "brief"],
    answer: 0,
    explanation: "Half thought one thing and half thought the opposite, so the plan was unclear.",
  },
  {
    id: "ela-g7-47",
    subject: "ela",
    grade: "7",
    standard: "RL.7.5",
    skill: "Poem structure",
    prompt: "How does the last line change the poem?",
    passage: "Thunder cracks; the windows shake.\nWind howls; the old oak bends and breaks.\nThen silence, and sun on every lake.",
    choices: ["It shifts from chaos to peace.", "It adds more thunder.", "It introduces a new character.", "It repeats the first line."],
    answer: 0,
    explanation: "After two lines of storm, the final line brings silence and sunshine.",
  },
  {
    id: "ela-g7-48",
    subject: "ela",
    grade: "7",
    standard: "RI.7.8",
    skill: "Evaluating evidence",
    prompt: "What is the main flaw in this argument?",
    passage: "Energy drinks improve test scores. I drank one before my last quiz and got an A.",
    choices: ["It relies on one personal example.", "It cites too many studies.", "It uses expert opinion.", "It defines its terms."],
    answer: 0,
    explanation: "One quiz is not enough evidence to prove a claim about everyone.",
  },
];

export default questions;
