import type { Question } from "../../types";
// Grade 11 science — NC Standard Course of Study for Science (2023), Chemistry (PS.Chm). Atomic models, nuclear
// chemistry and electron arrangement (PS.Chm.1); the periodic table, valence electrons and periodic trends (PS.Chm.2);
// ionic and covalent bonding, molecular shape and intermolecular forces (PS.Chm.3); energy in reactions, conservation
// of mass, reaction types, moles and stoichiometry (PS.Chm.4); reaction rates and equilibrium (PS.Chm.5); solutions,
// molarity and acids and bases (PS.Chm.6). Gas-law items are tagged PS.Chm.5 pending confirmation (see NOTES.md).
const questions: Question[] = [
  {
    id: "sci-g11-01",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1",
    skill: "Atomic structure",
    prompt: "Isotopes of the same element differ in their number of...",
    choices: ["Neutrons", "Protons", "Electrons", "Elements"],
    answer: 0,
    explanation: "Isotopes have the same number of protons (so the same element) but different numbers of neutrons, so different masses.",
    quick: true,
  },
  {
    id: "sci-g11-02",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Nuclear decay",
    prompt: "An alpha particle is the same as the nucleus of which element?",
    choices: ["Helium", "Hydrogen", "Carbon", "Uranium"],
    answer: 0,
    explanation: "An alpha particle is 2 protons and 2 neutrons, a helium-4 nucleus. Alpha decay lowers the atomic number by 2.",
    quick: true,
  },
  {
    id: "sci-g11-03",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Half-life",
    passage: "A lab has an 80 g sample of a radioactive isotope with a half-life of 5 days.",
    prompt: "How much of the original isotope remains after 15 days?",
    choices: ["10 g", "20 g", "40 g", "0 g"],
    answer: 0,
    explanation: "15 days is 3 half-lives: 80 → 40 → 20 → 10 g. Each half-life cuts the amount in half; it never drops straight to zero.",
  },
  {
    id: "sci-g11-04",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1",
    skill: "Atomic structure",
    prompt: "An element's atomic number equals its number of...",
    choices: ["Protons", "Neutrons", "Shells", "Isotopes"],
    answer: 0,
    explanation: "The atomic number is the proton count, which defines the element. The mass number is protons plus neutrons.",
    quick: true,
  },
  {
    id: "sci-g11-05",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Moving left to right across a period, atomic radius generally...",
    choices: ["Decreases", "Increases", "Stays same", "Doubles"],
    answer: 0,
    explanation: "More protons in the same energy level pull electrons in more tightly, so atoms get smaller across a period.",
    quick: true,
  },
  {
    id: "sci-g11-06",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Which element has the highest electronegativity?",
    choices: ["Fluorine", "Cesium", "Sodium", "Iron"],
    answer: 0,
    explanation: "Electronegativity increases up and to the right on the periodic table, making fluorine the highest.",
    quick: true,
  },
  {
    id: "sci-g11-07",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Group 1 metals are very reactive because they easily do what to one electron?",
    choices: ["Lose it", "Gain it", "Share it", "Split it"],
    answer: 0,
    explanation: "Alkali metals have one valence electron with low ionization energy, so they give it up easily to form +1 ions.",
    quick: true,
  },
  {
    id: "sci-g11-08",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.1",
    skill: "Chemical bonding",
    prompt: "Sodium chloride (NaCl) is held together by which bonds?",
    choices: ["Ionic", "Covalent", "Metallic", "Hydrogen"],
    answer: 0,
    explanation: "Na gives an electron to Cl, forming Na⁺ and Cl⁻ ions that attract each other in an ionic lattice.",
    quick: true,
  },
  {
    id: "sci-g11-09",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.1",
    skill: "Chemical bonding",
    prompt: "Two nonmetal atoms sharing pairs of electrons form which bond?",
    choices: ["Covalent", "Ionic", "Metallic", "Nuclear"],
    answer: 0,
    explanation: "Covalent bonds form when atoms share electrons, typically between nonmetals, as in H₂O and CO₂.",
    quick: true,
  },
  {
    id: "sci-g11-10",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Molecular shape",
    prompt: "What is the molecular shape of a water molecule?",
    choices: ["Bent", "Linear", "Octahedral", "Square"],
    answer: 0,
    explanation: "Oxygen's two lone pairs push the two O–H bonds together into a bent shape (about 104.5°), making water polar.",
    quick: true,
  },
  {
    id: "sci-g11-11",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.1",
    skill: "Bonding and properties",
    passage: "Melting points: sodium chloride (NaCl) 801°C; table sugar (C₁₂H₂₂O₁₁) about 186°C; paraffin wax about 60°C.",
    prompt: "Why does sodium chloride have by far the highest melting point?",
    choices: [
      "Strong attractions between ions in a lattice must be overcome",
      "Its molecules are the largest of the three",
      "It contains the most covalent bonds",
      "Sodium is a metal, and all metals melt above 800°C",
    ],
    answer: 0,
    explanation: "Melting NaCl means pulling apart oppositely charged ions held in a lattice. Sugar and wax only need weaker forces between molecules overcome.",
  },
  {
    id: "sci-g11-12",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.2",
    skill: "Balancing equations",
    prompt: "Balance: _H₂ + O₂ → 2H₂O. What coefficient goes before H₂?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "2H₂O has 4 H atoms, so you need 2H₂. Balanced equations show atoms are conserved.",
    quick: true,
  },
  {
    id: "sci-g11-13",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.3",
    skill: "The mole",
    prompt: "How many moles are in 36 g of water (molar mass 18 g/mol)?",
    choices: ["2 mol", "0.5 mol", "18 mol", "648 mol"],
    answer: 0,
    explanation: "moles = mass ÷ molar mass = 36 g ÷ 18 g/mol = 2 mol.",
    quick: true,
  },
  {
    id: "sci-g11-14",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.2",
    skill: "Reaction types",
    prompt: "A + B → AB is which type of reaction?",
    choices: ["Synthesis", "Decomposition", "Combustion", "Replacement"],
    answer: 0,
    explanation: "In synthesis, simpler substances combine into one product. Decomposition is the reverse: AB → A + B.",
    quick: true,
  },
  {
    id: "sci-g11-15",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.4",
    skill: "Limiting reactant",
    passage: "Reaction: 2H₂ + O₂ → 2H₂O. A container holds 4 mol of H₂ and 1 mol of O₂, and the reaction runs to completion.",
    prompt: "Which reactant is limiting, and how much water forms?",
    choices: ["O₂; 2 mol H₂O", "H₂; 4 mol H₂O", "O₂; 1 mol H₂O", "H₂; 2 mol H₂O"],
    answer: 0,
    explanation: "1 mol O₂ needs only 2 mol H₂, so O₂ runs out first. 1 mol O₂ makes 2 mol H₂O, and 2 mol H₂ is left over.",
  },
  {
    id: "sci-g11-16",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5",
    skill: "Gas laws",
    prompt: "At constant temperature, doubling the pressure on a gas makes its volume...",
    choices: ["Halve", "Double", "Stay the same", "Quadruple"],
    answer: 0,
    explanation: "Boyle's law: P₁V₁ = P₂V₂. Pressure and volume are inversely related, so doubling P halves V.",
    quick: true,
  },
  {
    id: "sci-g11-17",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.3",
    skill: "Acids and bases",
    prompt: "A solution with a pH of 3 is...",
    choices: ["Acidic", "Basic", "Neutral", "Salty"],
    answer: 0,
    explanation: "pH below 7 is acidic, 7 is neutral, and above 7 is basic. Each pH step is a tenfold change in H⁺ concentration.",
    quick: true,
  },
  {
    id: "sci-g11-18",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.2",
    skill: "Solutions",
    prompt: "Molarity is moles of solute per...",
    choices: ["L of solution", "kg of solvent", "g of solute", "mL of water"],
    answer: 0,
    explanation: "Molarity (M) = mol solute ÷ liters of solution. Moles per kilogram of solvent is molality, a different unit.",
    quick: true,
  },
  {
    id: "sci-g11-19",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.1",
    skill: "Atomic models",
    prompt: "Rutherford's gold foil experiment showed that atoms have a...",
    choices: ["Small nucleus", "Spread charge", "No empty space", "No electrons"],
    answer: 0,
    explanation: "Most alpha particles passed through, but a few bounced back, so the positive charge and mass are packed into a tiny nucleus.",
    quick: true,
  },
  {
    id: "sci-g11-20",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.1",
    skill: "Atomic models",
    prompt: "Who proposed that electrons orbit in fixed energy levels?",
    choices: ["Bohr", "Dalton", "Thomson", "Democritus"],
    answer: 0,
    explanation: "Niels Bohr's model placed electrons in specific energy levels around the nucleus.",
    quick: true,
  },
  {
    id: "sci-g11-21",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Nuclear chemistry",
    prompt: "Beta decay emits which particle?",
    choices: ["Electron", "Helium nucleus", "Proton", "Photon only"],
    answer: 0,
    explanation: "In beta decay, a neutron changes into a proton and a fast electron (beta particle) is emitted.",
    quick: true,
  },
  {
    id: "sci-g11-22",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.2",
    skill: "Nuclear chemistry",
    prompt: "Splitting a heavy nucleus into smaller nuclei is...",
    choices: ["Fission", "Fusion", "Alpha decay", "Ionization"],
    answer: 0,
    explanation: "Nuclear power plants use fission of uranium-235 to release energy.",
    quick: true,
  },
  {
    id: "sci-g11-23",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.3",
    skill: "Electron arrangement",
    prompt: "How many electrons can the first energy level hold?",
    choices: ["2", "8", "18", "32"],
    answer: 0,
    explanation: "The n = 1 level has one s orbital, which holds 2 electrons.",
    quick: true,
  },
  {
    id: "sci-g11-24",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.1.3",
    skill: "Electron arrangement",
    prompt: "What is the electron configuration of oxygen (8 electrons)?",
    choices: ["1s² 2s² 2p⁴", "1s² 2s² 2p⁶", "1s² 2s⁴ 2p²", "1s² 2p⁶"],
    answer: 0,
    explanation: "Fill 1s (2), then 2s (2), then put the remaining 4 electrons in 2p.",
    quick: true,
  },
  {
    id: "sci-g11-25",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.1",
    skill: "Valence electrons",
    prompt: "Electrons in an atom's outermost energy level are called...",
    choices: ["Valence", "Core", "Nuclear", "Isotopic"],
    answer: 0,
    explanation: "Valence electrons are in the outer shell and take part in bonding.",
    quick: true,
  },
  {
    id: "sci-g11-26",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.1",
    skill: "Valence electrons",
    prompt: "How many valence electrons does chlorine have?",
    choices: ["7", "1", "8", "17"],
    answer: 0,
    explanation: "Chlorine is in Group 17, so it has 7 valence electrons and tends to gain 1.",
    quick: true,
  },
  {
    id: "sci-g11-27",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.1",
    skill: "Valence electrons",
    prompt: "Which element is a halogen?",
    choices: ["Bromine", "Neon", "Sodium", "Calcium"],
    answer: 0,
    explanation: "Halogens are Group 17: fluorine, chlorine, bromine and iodine.",
    quick: true,
  },
  {
    id: "sci-g11-28",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.2.2",
    skill: "Periodic trends",
    prompt: "Going down a group, ionization energy generally...",
    choices: ["Decreases", "Increases", "Stays same", "Doubles"],
    answer: 0,
    explanation: "Outer electrons are farther from the nucleus and more shielded, so they are easier to remove.",
    quick: true,
  },
  {
    id: "sci-g11-29",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.1",
    skill: "Ionic and covalent bonds",
    prompt: "What is the formula of the compound formed by Mg²⁺ and Cl⁻?",
    choices: ["MgCl₂", "MgCl", "Mg₂Cl", "Mg₂Cl₃"],
    answer: 0,
    explanation: "Two Cl⁻ ions balance one Mg²⁺ ion, so the formula is MgCl₂.",
    quick: true,
  },
  {
    id: "sci-g11-30",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.1",
    skill: "Ionic and covalent bonds",
    prompt: "Which compound is held together by covalent bonds?",
    choices: ["CO₂", "NaCl", "KBr", "MgO"],
    answer: 0,
    explanation: "CO₂ is made of two nonmetals sharing electrons. The others are metal-nonmetal ionic compounds.",
    quick: true,
  },
  {
    id: "sci-g11-31",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3.2",
    skill: "Intermolecular forces",
    prompt: "Water's unusually high boiling point is due to...",
    choices: ["Hydrogen bonds", "Ionic bonds", "Metal bonds", "Nuclear force"],
    answer: 0,
    explanation: "Hydrogen bonds between water molecules take extra energy to break, raising the boiling point.",
    quick: true,
  },
  {
    id: "sci-g11-32",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.3",
    skill: "Molecular shape",
    prompt: "What is the shape of a carbon dioxide (CO₂) molecule?",
    choices: ["Linear", "Bent", "Tetrahedral", "Trigonal"],
    answer: 0,
    explanation: "Carbon has two double bonds and no lone pairs, so the oxygens sit 180° apart in a straight line.",
    quick: true,
  },
  {
    id: "sci-g11-33",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.1",
    skill: "Energy in reactions",
    prompt: "A reaction that releases heat to its surroundings is...",
    choices: ["Exothermic", "Endothermic", "Neutral", "Nuclear"],
    answer: 0,
    explanation: "Exothermic reactions give off energy, so the surroundings get warmer.",
    quick: true,
  },
  {
    id: "sci-g11-34",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.1",
    skill: "Energy in reactions",
    prompt: "A cold pack feels cold after squeezing. The process is...",
    choices: ["Endothermic", "Exothermic", "Combustion", "Fusion"],
    answer: 0,
    explanation: "An endothermic process absorbs heat from its surroundings, including your hand.",
    quick: true,
  },
  {
    id: "sci-g11-35",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.2",
    skill: "Reaction types",
    prompt: "CH₄ + 2O₂ → CO₂ + 2H₂O is which reaction type?",
    choices: ["Combustion", "Synthesis", "Decomposition", "Replacement"],
    answer: 0,
    explanation: "A fuel reacting with oxygen to make CO₂ and water is combustion.",
    quick: true,
  },
  {
    id: "sci-g11-36",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.3",
    skill: "Moles and composition",
    prompt: "What is the molar mass of CO₂? (C = 12, O = 16)",
    choices: ["44 g/mol", "28 g/mol", "32 g/mol", "60 g/mol"],
    answer: 0,
    explanation: "12 + 2(16) = 44 g/mol.",
    quick: true,
  },
  {
    id: "sci-g11-37",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5.1",
    skill: "Reaction rates",
    prompt: "Powdered sugar reacts faster than a sugar cube because it has more...",
    choices: ["Surface area", "Mass", "Volume", "Density"],
    answer: 0,
    explanation: "Smaller pieces expose more particles to collisions, so the reaction rate increases.",
    quick: true,
  },
  {
    id: "sci-g11-38",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5.2",
    skill: "Equilibrium",
    prompt: "Adding more reactant to a system at equilibrium shifts it toward...",
    choices: ["Products", "Reactants", "Neither side", "Solids only"],
    answer: 0,
    explanation: "Le Chatelier's principle: the system shifts to use up the added reactant, making more product.",
    quick: true,
  },
  {
    id: "sci-g11-39",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.1",
    skill: "Solutions",
    prompt: "In salt water, the water is the...",
    choices: ["Solvent", "Solute", "Precipitate", "Catalyst"],
    answer: 0,
    explanation: "The solvent does the dissolving. The salt is the solute.",
    quick: true,
  },
  {
    id: "sci-g11-40",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.2",
    skill: "Molarity",
    prompt: "1 L of 2 M solution is diluted to 4 L. What is the new molarity?",
    choices: ["0.5 M", "8 M", "2 M", "1 M"],
    answer: 0,
    explanation: "M₁V₁ = M₂V₂: (2 M)(1 L) = M₂(4 L), so M₂ = 0.5 M.",
    quick: true,
  },
  {
    id: "sci-g11-41",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.3",
    skill: "Acids and bases",
    prompt: "pH 3 has how many times more H⁺ than pH 5?",
    choices: ["100", "2", "10", "1000"],
    answer: 0,
    explanation: "Each pH unit is a factor of 10. Two units apart means 10 × 10 = 100 times.",
    quick: true,
  },
  {
    id: "sci-g11-42",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5",
    skill: "Gas laws",
    prompt: "At constant pressure, heating a gas makes its volume...",
    choices: ["Increase", "Decrease", "Stay the same", "Drop to zero"],
    answer: 0,
    explanation: "Charles's law: volume is proportional to Kelvin temperature when pressure is constant.",
    quick: true,
  },
  {
    id: "sci-g11-43",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5.1",
    skill: "Reaction rates",
    passage:
      "Equal masses of marble chips were added to the same acid. At 20°C the fizzing stopped after 60 s. At 40°C it stopped after 25 s.",
    prompt: "What best explains the faster reaction at 40°C?",
    choices: [
      "Particles collide more often and with more energy",
      "The acid became more concentrated",
      "The marble melted at 40°C",
      "Heating added more marble",
    ],
    answer: 0,
    explanation: "Collision theory: higher temperature means faster particles, more frequent collisions, and more collisions with enough energy to react.",
  },
  {
    id: "sci-g11-44",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.4",
    skill: "Stoichiometry",
    passage:
      "2H₂ + O₂ → 2H₂O. Molar mass of H₂O = 18 g/mol.",
    prompt: "How many grams of water form from 2 mol of H₂ with excess O₂?",
    choices: ["36 g", "18 g", "72 g", "9 g"],
    answer: 0,
    explanation: "The 2:2 ratio gives 2 mol H₂O. 2 mol × 18 g/mol = 36 g.",
  },
  {
    id: "sci-g11-45",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.5.2",
    skill: "Equilibrium",
    passage:
      "N₂(g) + 3H₂(g) ⇌ 2NH₃(g) + heat",
    prompt: "The system is cooled. Which way does the equilibrium shift?",
    choices: ["Toward NH₃", "Toward N₂ and H₂", "No shift", "The reaction stops"],
    answer: 0,
    explanation: "The forward reaction releases heat. Removing heat favors the forward, heat-producing direction, making more NH₃.",
  },
  {
    id: "sci-g11-46",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.4.1",
    skill: "Energy in reactions",
    passage:
      "On an energy diagram, the reactants are at 50 kJ, the peak (activated complex) is at 90 kJ, and the products are at 20 kJ.",
    prompt: "What are ΔH and the reaction type?",
    choices: ["−30 kJ; exothermic", "+30 kJ; endothermic", "+40 kJ; endothermic", "−70 kJ; exothermic"],
    answer: 0,
    explanation: "ΔH = products − reactants = 20 − 50 = −30 kJ. Products have less energy, so energy was released.",
  },
  {
    id: "sci-g11-47",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.1",
    skill: "Solutions",
    passage:
      "Solubility of KNO₃ in 100 g of water: 32 g at 20°C and 110 g at 60°C. A saturated solution in 100 g of water at 60°C is cooled to 20°C.",
    prompt: "About how much KNO₃ crystallizes out?",
    choices: ["78 g", "32 g", "110 g", "142 g"],
    answer: 0,
    explanation: "At 20°C only 32 g stays dissolved, so 110 − 32 = 78 g comes out as crystals.",
  },
  {
    id: "sci-g11-48",
    subject: "science",
    grade: "11",
    standard: "PS.Chm.6.2",
    skill: "Titration",
    prompt: "What volume of 0.050 M NaOH neutralizes 25 mL of 0.10 M HCl?",
    choices: ["50 mL", "25 mL", "12.5 mL", "100 mL"],
    answer: 0,
    explanation: "Moles HCl = 0.10 × 0.025 = 0.0025 mol. NaOH reacts 1:1, so V = 0.0025 ÷ 0.050 = 0.050 L = 50 mL.",
    quick: true,
  },
];
export default questions;
