import type { Question } from "../../types";
// Grade 4 science — NC Standard Course of Study for Science (2023). Magnetic and electric forces (PS.4.1), energy,
// circuits, conductors and insulators (PS.4.2), light and reflection (PS.4.3), day/night and moon phases (ESS.4.1),
// minerals, rocks and changes to Earth's surface (ESS.4.2), adaptations and behaviors (LS.4.1), and fossils (LS.4.2).
const questions: Question[] = [
  {
    id: "sci-g4-01",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.1",
    skill: "Magnets",
    prompt: "A magnet will attract which object?",
    choices: ["Iron nail", "Plastic cup", "Wooden spoon", "Rubber band"],
    answer: 0,
    explanation: "Magnets attract things made of iron (and a few other metals). Plastic, wood and rubber are not attracted.",
    quick: true,
  },
  {
    id: "sci-g4-02",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.1",
    skill: "Magnets",
    prompt: "Two north poles of magnets are held close. They will...",
    choices: ["Repel", "Attract", "Stick", "Melt"],
    answer: 0,
    explanation: "Like poles (north-north or south-south) push apart. Opposite poles pull together.",
    quick: true,
  },
  {
    id: "sci-g4-03",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.2",
    skill: "Static electricity",
    prompt: "A balloon rubbed on hair sticks to a wall. What causes this?",
    choices: ["Static charge", "Glue", "Magnetism", "Gravity"],
    answer: 0,
    explanation: "Rubbing moves electric charges onto the balloon. Charged objects can pull on other objects without touching.",
    quick: true,
  },
  {
    id: "sci-g4-04",
    subject: "science",
    grade: "4",
    standard: "LS.4.2.2",
    skill: "Fossils",
    prompt: "Fish fossils are found high on a mountain. The area was probably once...",
    choices: ["Underwater", "A desert", "Covered in ice", "A city"],
    answer: 0,
    explanation: "Fish live in water, so their fossils tell us that place was once covered by water. Fossils give clues about past environments.",
    quick: true,
  },
  {
    id: "sci-g4-05",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Conductors and insulators",
    prompt: "Which is a good conductor of electricity?",
    choices: ["Copper wire", "Rubber", "Plastic", "Wood"],
    answer: 0,
    explanation: "Metals like copper let electricity flow easily. Rubber and plastic are insulators, so they cover wires.",
    quick: true,
  },
  {
    id: "sci-g4-06",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Energy transfer",
    prompt: "A lamp changes electrical energy mostly into...",
    choices: ["Light and heat", "Motion only", "Sound only", "Food energy"],
    answer: 0,
    explanation: "A light bulb turns electrical energy into light. Some of the energy always becomes heat, too.",
    quick: true,
  },
  {
    id: "sci-g4-07",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Conductors and insulators",
    prompt: "Pot handles often have plastic grips. Plastic is a good heat...",
    choices: ["Insulator", "Conductor", "Magnet", "Mirror"],
    answer: 0,
    explanation: "Insulators slow the flow of heat, so a plastic grip keeps your hand from getting burned.",
    quick: true,
  },
  {
    id: "sci-g4-08",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Circuits",
    passage:
      "Ava built a circuit with a battery, wires, a switch and a bulb. When the switch is closed, the bulb lights. When she opens the switch, the bulb goes dark right away.",
    prompt: "Why does the bulb go out when the switch is opened?",
    choices: [
      "The path for electricity is broken",
      "The battery is suddenly used up",
      "The bulb got too hot",
      "The wires stopped being metal",
    ],
    answer: 0,
    explanation: "Electricity needs a complete, closed loop. Opening the switch makes a gap, so current stops flowing.",
  },
  {
    id: "sci-g4-09",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.1",
    skill: "Light and reflection",
    prompt: "Light hits a mirror and bounces off. This is called...",
    choices: ["Reflection", "Absorption", "Refraction", "A shadow"],
    answer: 0,
    explanation: "Reflection is light bouncing off a surface. Smooth, shiny surfaces like mirrors reflect light best.",
    quick: true,
  },
  {
    id: "sci-g4-10",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.1",
    skill: "Light and reflection",
    prompt: "Light hits a flat mirror at 30° from straight-on. At what angle does it bounce off?",
    choices: ["30°", "60°", "90°", "0°"],
    answer: 0,
    explanation: "A mirror reflects light at the same angle it came in, just on the other side of the straight-on line.",
    quick: true,
  },
  {
    id: "sci-g4-11",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.1",
    skill: "Day and night",
    prompt: "What causes day and night?",
    choices: ["Earth spinning", "Sun circling", "Clouds", "Moon blocking"],
    answer: 0,
    explanation: "Earth rotates on its axis. The side facing the sun has day, and the side facing away has night.",
    quick: true,
  },
  {
    id: "sci-g4-12",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.1",
    skill: "Day and night",
    prompt: "About how long does Earth take to spin around once?",
    choices: ["About 24 hours", "One week", "One month", "One year"],
    answer: 0,
    explanation: "One full rotation takes about 24 hours, which is one day. A trip around the sun takes one year.",
    quick: true,
  },
  {
    id: "sci-g4-13",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1",
    skill: "Moon phases",
    prompt: "Why does the moon seem to change shape during a month?",
    choices: [
      "We see different amounts of its sunlit half as it orbits Earth",
      "Earth's shadow covers a different part each night",
      "Clouds block part of the moon",
      "The moon grows and shrinks in size",
    ],
    answer: 0,
    explanation: "The sun always lights half the moon. As the moon orbits Earth, we see more or less of that lit half. Earth's shadow only matters during an eclipse.",
  },
  {
    id: "sci-g4-14",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.1",
    skill: "Minerals",
    prompt: "A streak test shows a mineral's...",
    choices: ["Powder color", "Hardness", "Weight", "Shape"],
    answer: 0,
    explanation: "Rubbing a mineral on a streak plate leaves powder. The powder's color can differ from the outside color and helps identify it.",
    quick: true,
  },
  {
    id: "sci-g4-15",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.2",
    skill: "Rocks",
    prompt: "Rock formed when lava cools and hardens is...",
    choices: ["Igneous", "Sedimentary", "Metamorphic", "A fossil"],
    answer: 0,
    explanation: "Igneous rock forms from melted rock (magma or lava) that cools. Sedimentary rock forms from layers of sediment.",
    quick: true,
  },
  {
    id: "sci-g4-16",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.3",
    skill: "Changes to Earth's surface",
    prompt: "Moving water carrying soil and rock away is called...",
    choices: ["Erosion", "Melting", "Freezing", "Deposition"],
    answer: 0,
    explanation: "Erosion moves weathered bits of rock and soil to new places. Deposition is when they are dropped off.",
    quick: true,
  },
  {
    id: "sci-g4-17",
    subject: "science",
    grade: "4",
    standard: "LS.4.1",
    skill: "Adaptations",
    prompt: "Thick fur and fat help a polar bear...",
    choices: ["Stay warm", "Hide in woods", "Eat plants", "Climb trees"],
    answer: 0,
    explanation: "These adaptations hold in body heat so polar bears can survive in the freezing Arctic.",
    quick: true,
  },
  {
    id: "sci-g4-18",
    subject: "science",
    grade: "4",
    standard: "LS.4.1",
    skill: "Behaviors",
    prompt: "Birds flying south for the winter is an example of...",
    choices: ["Migration", "Hibernation", "Camouflage", "Erosion"],
    answer: 0,
    explanation: "Migration is moving to a new place when seasons change, often to find food and warmth.",
    quick: true,
  },
];
export default questions;
