import type { Question } from "../../types";

// Grade 4 ELA — NC Standard Course of Study for ELA (2017). RL.4.1, RL.4.2, RL.4.3, RL.4.4, RL.4.5, RL.4.6, RI.4.1, RI.4.2, RI.4.3, RI.4.4, RI.4.5, RI.4.6, RI.4.8, RF.4.4, L.4.1, L.4.2, L.4.3, L.4.4, L.4.5
const questions: Question[] = [
  {
    id: "ela-g4-01",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root graph (as in autograph) means...",
    choices: ["write", "see", "hear", "carry"],
    answer: 0,
    explanation: "Graph means write. An autograph is a name you write yourself.",
    quick: true,
  },
  {
    id: "ela-g4-02",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root tele (as in telephone) means...",
    choices: ["far", "sound", "near", "light"],
    answer: 0,
    explanation: "Tele means far. A telephone carries sound from far away.",
    quick: true,
  },
  {
    id: "ela-g4-03",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root port (as in transport) means...",
    choices: ["carry", "look", "build", "break"],
    answer: 0,
    explanation: "Port means carry. To transport something is to carry it across.",
    quick: true,
  },
  {
    id: "ela-g4-04",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Similes and metaphors",
    prompt: "Which phrase is a simile?",
    choices: ["like a rocket", "a red rocket", "the rocket", "rockets fly"],
    answer: 0,
    explanation: "A simile compares two things using like or as.",
    quick: true,
  },
  {
    id: "ela-g4-05",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Similes and metaphors",
    prompt: "'The classroom was a zoo.' This is a...",
    choices: ["metaphor", "simile", "rhyme", "fact"],
    answer: 0,
    explanation: "A metaphor compares without like or as: the room is called a zoo because it's wild.",
    quick: true,
  },
  {
    id: "ela-g4-06",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Idioms",
    prompt: "What does 'break the ice' mean?",
    choices: ["start talking", "smash a glass", "feel cold", "skate fast"],
    answer: 0,
    explanation: "To break the ice means to help people relax and start talking.",
    quick: true,
  },
  {
    id: "ela-g4-07",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Antonyms",
    prompt: "Which word is an antonym of ancient?",
    choices: ["modern", "old", "antique", "huge"],
    answer: 0,
    explanation: "Antonyms are opposites. Ancient means very old; modern means new.",
    quick: true,
  },
  {
    id: "ela-g4-08",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Relative pronouns",
    prompt: "The boy ___ won the race is my cousin. Which word fits?",
    choices: ["who", "which", "what", "whom"],
    answer: 0,
    explanation: "Use who for a person doing the action. Which is for things.",
    quick: true,
  },
  {
    id: "ela-g4-09",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Progressive verb tense",
    prompt: "Which verb is in the present progressive tense?",
    choices: ["is running", "ran", "runs", "will run"],
    answer: 0,
    explanation: "The present progressive (is + -ing) shows an action happening right now.",
    quick: true,
  },
  {
    id: "ela-g4-10",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Confused words",
    prompt: "___ going to the game tonight. Which word fits?",
    choices: ["They're", "Their", "There", "Thier"],
    answer: 0,
    explanation: "They're is short for they are. Their shows ownership; there is a place.",
    quick: true,
  },
  {
    id: "ela-g4-11",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Prepositional phrases",
    prompt: "Which is a prepositional phrase?",
    choices: ["under the bed", "the red bed", "very sleepy", "and then"],
    answer: 0,
    explanation: "A prepositional phrase starts with a preposition, like under, and ends with a noun.",
    quick: true,
  },
  {
    id: "ela-g4-12",
    subject: "ela",
    grade: "4",
    standard: "RL.4.6",
    skill: "Point of view",
    prompt: "A narrator using he, she, and they tells the story in...",
    choices: ["third person", "first person", "second person", "dialogue"],
    answer: 0,
    explanation: "A third-person narrator is outside the story and uses he, she, and they.",
    quick: true,
  },
  {
    id: "ela-g4-13",
    subject: "ela",
    grade: "4",
    standard: "RL.4.5",
    skill: "Drama",
    prompt: "The parts that a play is divided into are called...",
    choices: ["scenes", "stanzas", "chapters", "verses"],
    answer: 0,
    explanation: "Plays are divided into acts and scenes. Poems have stanzas; novels have chapters.",
    quick: true,
  },
  {
    id: "ela-g4-14",
    subject: "ela",
    grade: "4",
    standard: "RI.4.5",
    skill: "Text structure",
    prompt: "A text telling what happened first, next, and last is...",
    choices: ["chronological", "comparison", "cause/effect", "description"],
    answer: 0,
    explanation: "Chronological structure tells events in time order.",
    quick: true,
  },
  {
    id: "ela-g4-15",
    subject: "ela",
    grade: "4",
    standard: "RL.4.2",
    skill: "Theme",
    prompt: "What is the theme of this story?",
    passage: "Rosa practiced piano for weeks, but at the recital her fingers shook and she missed three notes. Afterward, her teacher said, 'You kept playing when it was hard. That takes courage.' Rosa realized that finishing mattered more than being perfect.",
    choices: ["Finishing matters more than being perfect.", "Music is hard to learn.", "Teachers are always right.", "Recitals should be canceled."],
    answer: 0,
    explanation: "Rosa's realization at the end points to the theme: finishing with courage matters more than perfection.",
  },
  {
    id: "ela-g4-16",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Context clues",
    prompt: "What does frugal most likely mean?",
    passage: "Grandpa is so frugal that he reuses wrapping paper, fixes his own shoes, and never buys anything that is not on sale.",
    choices: ["careful with money", "very generous", "often angry", "good at sports"],
    answer: 0,
    explanation: "Reusing paper, fixing shoes, and buying only on sale are clues that frugal means careful with money.",
  },
  {
    id: "ela-g4-17",
    subject: "ela",
    grade: "4",
    standard: "RI.4.2",
    skill: "Main idea",
    prompt: "What is the main idea of this text?",
    passage: "Sea turtles face many dangers. Plastic bags in the ocean look like jellyfish, so turtles may eat them. Bright lights on beaches confuse baby turtles and lead them away from the sea. People can help by picking up trash and turning off beach lights at night.",
    choices: ["Sea turtles face dangers people can reduce.", "Turtles like to eat jellyfish.", "Beaches are too bright at night.", "Plastic bags are useful."],
    answer: 0,
    explanation: "The text names dangers and then explains how people can help. That is the main idea.",
  },
  {
    id: "ela-g4-18",
    subject: "ela",
    grade: "4",
    standard: "RL.4.1",
    skill: "Making inferences",
    prompt: "How does Jamal most likely feel?",
    passage: "Jamal stared at the clock. He tapped his pencil, then checked the door again. When the bell finally rang, he grabbed his bag and raced to the bus to see his grandmother, who was visiting from Ghana.",
    choices: ["eager", "bored", "angry", "sleepy"],
    answer: 0,
    explanation: "Watching the clock and racing to the bus are clues that Jamal is eager to see his grandmother.",
  },
  {
    id: "ela-g4-19",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Latin roots",
    prompt: "The Latin root spect (as in inspect) means...",
    choices: ["look", "carry", "write", "hear"],
    answer: 0,
    explanation: "Spect means look. To inspect is to look at closely.",
    quick: true,
  },
  {
    id: "ela-g4-20",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Prefixes",
    prompt: "What does the prefix sub- mean in submarine?",
    choices: ["under", "over", "across", "again"],
    answer: 0,
    explanation: "Sub- means under. A submarine travels under the sea.",
    quick: true,
  },
  {
    id: "ela-g4-21",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Prefixes",
    prompt: "What does the prefix inter- mean in international?",
    choices: ["between", "inside", "before", "against"],
    answer: 0,
    explanation: "Inter- means between. International means between nations.",
    quick: true,
  },
  {
    id: "ela-g4-22",
    subject: "ela",
    grade: "4",
    standard: "RF.4.4",
    skill: "Suffixes",
    prompt: "Which suffix turns kind into a noun?",
    choices: ["-ness", "-ly", "-er", "-est"],
    answer: 0,
    explanation: "Kind + -ness = kindness, a noun. Kindly and kinder are not nouns.",
    quick: true,
  },
  {
    id: "ela-g4-23",
    subject: "ela",
    grade: "4",
    standard: "RF.4.4",
    skill: "Syllables",
    prompt: "How many syllables are in information?",
    choices: ["4", "3", "5", "2"],
    answer: 0,
    explanation: "In-for-ma-tion has four syllables.",
    quick: true,
  },
  {
    id: "ela-g4-24",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Synonyms",
    prompt: "Which word is a synonym for brave?",
    choices: ["courageous", "fearful", "timid", "careless"],
    answer: 0,
    explanation: "Courageous means brave. Fearful and timid are antonyms.",
    quick: true,
  },
  {
    id: "ela-g4-25",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Idioms",
    prompt: "What does 'hit the books' mean?",
    choices: ["study hard", "punch books", "drop books", "buy books"],
    answer: 0,
    explanation: "'Hit the books' is an idiom that means to study.",
    quick: true,
  },
  {
    id: "ela-g4-26",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Adages and proverbs",
    prompt: "'Practice makes perfect' means you get better by...",
    choices: ["repeating it", "giving up", "being lucky", "watching TV"],
    answer: 0,
    explanation: "This adage means doing something again and again helps you improve.",
    quick: true,
  },
  {
    id: "ela-g4-27",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Metaphors",
    prompt: "'Dad is a bear before breakfast.' What does this mean?",
    choices: ["He's grumpy.", "He's furry.", "He's huge.", "He's strong."],
    answer: 0,
    explanation: "The metaphor compares Dad to a cranky bear: he is grumpy before he eats.",
    quick: true,
  },
  {
    id: "ela-g4-28",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Modal verbs",
    prompt: "You ___ wear a seatbelt; it's the law. Which word fits?",
    choices: ["must", "might", "could", "may"],
    answer: 0,
    explanation: "Must shows something is required. Might and could only show it is possible.",
    quick: true,
  },
  {
    id: "ela-g4-29",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Relative adverbs",
    prompt: "That's the park ___ we had the picnic. Which word fits?",
    choices: ["where", "when", "why", "who"],
    answer: 0,
    explanation: "Where points to a place, like a park.",
    quick: true,
  },
  {
    id: "ela-g4-30",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Order of adjectives",
    prompt: "Which phrase puts the adjectives in the right order?",
    choices: ["small red ball", "red small ball", "ball small red", "red ball small"],
    answer: 0,
    explanation: "Size words usually come before color words: small red ball.",
    quick: true,
  },
  {
    id: "ela-g4-31",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Sentence fragments",
    prompt: "Which is a sentence fragment?",
    choices: ["Under the bed.", "I ran.", "We left early.", "Stop!"],
    answer: 0,
    explanation: "'Under the bed' has no subject or verb. 'Stop!' is a command, so it is complete.",
    quick: true,
  },
  {
    id: "ela-g4-32",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Confused words",
    prompt: "The dog wagged ___ tail. Which word fits?",
    choices: ["its", "it's", "its'", "it is"],
    answer: 0,
    explanation: "Its shows belonging. It's means it is.",
    quick: true,
  },
  {
    id: "ela-g4-33",
    subject: "ela",
    grade: "4",
    standard: "L.4.2",
    skill: "Commas in compound sentences",
    prompt: "Where should the comma go? 'I was tired so I went to bed.'",
    choices: ["after tired", "after I", "after went", "after so"],
    answer: 0,
    explanation: "Put a comma before the joining word so: I was tired, so I went to bed.",
    quick: true,
  },
  {
    id: "ela-g4-34",
    subject: "ela",
    grade: "4",
    standard: "L.4.2",
    skill: "Titles",
    prompt: "When typing, a book title should be in...",
    choices: ["italics", "all capitals", "parentheses", "bold font"],
    answer: 0,
    explanation: "Typed book titles go in italics. When handwriting, you underline them.",
    quick: true,
  },
  {
    id: "ela-g4-35",
    subject: "ela",
    grade: "4",
    standard: "L.4.3",
    skill: "Precise words",
    prompt: "Which verb shows best that the speaker was upset? 'Stop that!' she ___.",
    choices: ["snapped", "said", "told", "went"],
    answer: 0,
    explanation: "Snapped shows she spoke sharply and was upset. Said is plain.",
    quick: true,
  },
  {
    id: "ela-g4-36",
    subject: "ela",
    grade: "4",
    standard: "RL.4.5",
    skill: "Poetry and prose",
    prompt: "Poems are made of lines and stanzas. Stories in prose are made of...",
    choices: ["paragraphs", "verses", "scenes", "rhymes"],
    answer: 0,
    explanation: "Prose is ordinary writing organized into sentences and paragraphs.",
    quick: true,
  },
  {
    id: "ela-g4-37",
    subject: "ela",
    grade: "4",
    standard: "RL.4.5",
    skill: "Drama",
    prompt: "In a play, the words characters speak to each other are...",
    choices: ["dialogue", "stanzas", "chapters", "captions"],
    answer: 0,
    explanation: "Dialogue is what characters say. In a play, the story is told mostly through dialogue.",
    quick: true,
  },
  {
    id: "ela-g4-38",
    subject: "ela",
    grade: "4",
    standard: "RI.4.6",
    skill: "Firsthand accounts",
    prompt: "A diary written by someone who was there is a ___ account.",
    choices: ["firsthand", "secondhand", "fictional", "retold"],
    answer: 0,
    explanation: "A firsthand account comes from someone who saw or lived the event.",
    quick: true,
  },
  {
    id: "ela-g4-39",
    subject: "ela",
    grade: "4",
    standard: "RL.4.3",
    skill: "Describing characters",
    prompt: "Which word best describes Tomás?",
    passage: "Tomás always shared his lunch with the new kid, Dev, even though it meant Tomás went home hungry. When Dev asked why, Tomás shrugged. 'You'd do the same.'",
    choices: ["generous", "greedy", "shy", "bossy"],
    answer: 0,
    explanation: "Tomás shares his lunch even when it leaves him hungry, so he is generous.",
  },
  {
    id: "ela-g4-40",
    subject: "ela",
    grade: "4",
    standard: "RL.4.4",
    skill: "Allusions",
    prompt: "What does 'a Herculean effort' mean?",
    passage: "When Rina finished every one of her chores before breakfast, her mom laughed and called it a Herculean effort.",
    choices: ["a huge, hard effort", "a lazy try", "a quick nap", "a messy job"],
    answer: 0,
    explanation: "Hercules was a hero of Greek myths known for his great strength and hard tasks.",
  },
  {
    id: "ela-g4-41",
    subject: "ela",
    grade: "4",
    standard: "RL.4.2",
    skill: "Summarizing",
    prompt: "Which is the best summary?",
    passage: "Lena's lemonade stand sold nothing all morning. Instead of quitting, she asked a neighbor for advice, moved the stand near the park, and added ice. By afternoon, the pitcher was empty.",
    choices: ["Lena changed her plan and sold all her lemonade.", "Lena likes ice in her lemonade.", "The park is a busy place.", "Lena quit her lemonade stand."],
    answer: 0,
    explanation: "A good summary tells the main events: Lena did not quit, changed her plan, and succeeded.",
  },
  {
    id: "ela-g4-42",
    subject: "ela",
    grade: "4",
    standard: "RL.4.6",
    skill: "Point of view",
    prompt: "From which point of view is this told?",
    passage: "I couldn't believe it! The coach picked me to start. My hands shook as I laced up my cleats.",
    choices: ["first person", "second person", "third person", "no narrator"],
    answer: 0,
    explanation: "The narrator uses I, me, and my, so it is first person.",
  },
  {
    id: "ela-g4-43",
    subject: "ela",
    grade: "4",
    standard: "RI.4.1",
    skill: "Making inferences",
    prompt: "What can you infer about a desert fox's ears?",
    passage: "Desert foxes have huge ears. The ears release heat from their bodies, helping them stay cool in the scorching sand.",
    choices: ["They help it survive heat.", "They are used for digging.", "They keep it warm.", "They help it swim."],
    answer: 0,
    explanation: "The ears let out heat, which keeps the fox cool in the hot desert.",
  },
  {
    id: "ela-g4-44",
    subject: "ela",
    grade: "4",
    standard: "RI.4.3",
    skill: "Explaining a procedure",
    prompt: "What step comes right after rubbing the needle?",
    passage: "To make a simple compass, rub a needle with a magnet 20 times in one direction. Then float the needle on a leaf in a bowl of water. The needle will turn to point north.",
    choices: ["Float it on a leaf in water.", "Point it north.", "Rub it the other way.", "Bury it in sand."],
    answer: 0,
    explanation: "After rubbing the needle with the magnet, you float it on a leaf in water.",
  },
  {
    id: "ela-g4-45",
    subject: "ela",
    grade: "4",
    standard: "RI.4.5",
    skill: "Text structure",
    prompt: "Which text structure does this passage use?",
    passage: "Many schools throw away tons of food. To fix this, one school started a 'share table' where students leave unopened snacks for others to take.",
    choices: ["problem and solution", "compare and contrast", "time order", "description"],
    answer: 0,
    explanation: "The passage names a problem (wasted food) and a solution (a share table).",
  },
  {
    id: "ela-g4-46",
    subject: "ela",
    grade: "4",
    standard: "RI.4.8",
    skill: "Reasons and evidence",
    prompt: "Which evidence supports the author's point?",
    passage: "Recess helps students learn. A study found that students who had recess paid better attention in class. Teachers also reported fewer behavior problems.",
    choices: ["Students with recess paid better attention.", "Recess is fun.", "Some schools are big.", "Lunch comes after recess."],
    answer: 0,
    explanation: "The study about attention is evidence that recess helps students learn.",
  },
  {
    id: "ela-g4-47",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Context clues",
    prompt: "What does famished mean?",
    passage: "The hikers were famished after the long climb, so they ate every sandwich in minutes.",
    choices: ["very hungry", "very tired", "lost", "cheerful"],
    answer: 0,
    explanation: "They ate every sandwich in minutes, a clue that famished means very hungry.",
  },
  {
    id: "ela-g4-48",
    subject: "ela",
    grade: "4",
    standard: "RI.4.4",
    skill: "Science words",
    prompt: "What does erosion mean?",
    passage: "Erosion slowly wears away rock and soil. Wind, water, and ice can all carry bits of land away over many years.",
    choices: ["wearing away of land", "building of mountains", "melting of ice", "growth of plants"],
    answer: 0,
    explanation: "The text says erosion slowly wears away rock and soil.",
  },
];

export default questions;
