import type { Question } from "../../types";

// Grade 8 ELA — NC Standard Course of Study for ELA (2017). RL.8.1, RL.8.2, RL.8.3, RL.8.4, RL.8.5, RL.8.6, RL.8.9, RI.8.2, RI.8.5, RI.8.6, RI.8.8, RI.8.9, W.8.1, L.8.1, L.8.2, L.8.4, L.8.5
const questions: Question[] = [
  {
    id: "ela-g8-01",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "In 'Swimming is fun,' the word swimming is a...",
    choices: ["gerund", "participle", "infinitive", "adverb"],
    answer: 0,
    explanation: "A gerund is an -ing verb used as a noun. Here swimming is the subject.",
    quick: true,
  },
  {
    id: "ela-g8-02",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "Which phrase is an infinitive?",
    choices: ["to explore", "exploring", "explored", "explores"],
    answer: 0,
    explanation: "An infinitive is to + the base form of a verb: to explore.",
    quick: true,
  },
  {
    id: "ela-g8-03",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "In 'The broken vase lay on the floor,' broken is a...",
    choices: ["participle", "gerund", "infinitive", "noun"],
    answer: 0,
    explanation: "A participle is a verb form used as an adjective. Broken describes the vase.",
    quick: true,
  },
  {
    id: "ela-g8-04",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Active and passive voice",
    prompt: "Which verb phrase is in the passive voice?",
    choices: ["was thrown", "threw", "is throwing", "will throw"],
    answer: 0,
    explanation: "Passive voice uses a form of be + past participle, so the subject receives the action.",
    quick: true,
  },
  {
    id: "ela-g8-05",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verb mood",
    prompt: "'If I were you, I would study.' The verb were is in which mood?",
    choices: ["subjunctive", "indicative", "imperative", "interrogative"],
    answer: 0,
    explanation: "The subjunctive mood expresses wishes or situations contrary to fact.",
    quick: true,
  },
  {
    id: "ela-g8-06",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verb mood",
    prompt: "'Close the door, please.' Which mood is this?",
    choices: ["imperative", "indicative", "subjunctive", "conditional"],
    answer: 0,
    explanation: "The imperative mood gives commands or requests.",
    quick: true,
  },
  {
    id: "ela-g8-07",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root phon (as in symphony) means...",
    choices: ["sound", "light", "love", "fear"],
    answer: 0,
    explanation: "Phon means sound, as in telephone, phonics, and symphony.",
    quick: true,
  },
  {
    id: "ela-g8-08",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Verbal irony",
    prompt: "Saying 'What lovely weather!' during a storm is...",
    choices: ["verbal irony", "a simile", "hyperbole", "a pun"],
    answer: 0,
    explanation: "Verbal irony is saying the opposite of what you mean.",
    quick: true,
  },
  {
    id: "ela-g8-09",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Puns",
    prompt: "'I used to be a banker, but I lost interest.' This is a...",
    choices: ["pun", "simile", "metaphor", "paradox"],
    answer: 0,
    explanation: "A pun plays on two meanings of a word: interest as money and as attention.",
    quick: true,
  },
  {
    id: "ela-g8-10",
    subject: "ela",
    grade: "8",
    standard: "RL.8.6",
    skill: "Dramatic irony",
    prompt: "When the audience knows something a character doesn't, it is...",
    choices: ["dramatic irony", "verbal irony", "a flashback", "foreshadowing"],
    answer: 0,
    explanation: "Dramatic irony creates suspense or humor because readers know more than the characters.",
    quick: true,
  },
  {
    id: "ela-g8-11",
    subject: "ela",
    grade: "8",
    standard: "RL.8.5",
    skill: "Text structure",
    prompt: "A scene that jumps back to an earlier time is a...",
    choices: ["flashback", "foreshadowing", "climax", "resolution"],
    answer: 0,
    explanation: "A flashback interrupts the plot to show something from the past.",
    quick: true,
  },
  {
    id: "ela-g8-12",
    subject: "ela",
    grade: "8",
    standard: "W.8.1",
    skill: "Argument writing",
    prompt: "Evidence in an argument should be relevant and...",
    choices: ["credible", "emotional", "lengthy", "funny"],
    answer: 0,
    explanation: "Strong evidence is relevant to the claim and comes from credible, trustworthy sources.",
    quick: true,
  },
  {
    id: "ela-g8-13",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Connotation",
    prompt: "Which word has the most negative connotation?",
    choices: ["scheme", "plan", "strategy", "idea"],
    answer: 0,
    explanation: "Scheme suggests a sneaky or dishonest plan.",
    quick: true,
  },
  {
    id: "ela-g8-14",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Active and passive voice",
    prompt: "Which sentence is written in the active voice?",
    choices: ["The chef prepared the meal.", "The meal was prepared by the chef.", "The meal was being prepared.", "The meal had been prepared by noon."],
    answer: 0,
    explanation: "In active voice, the subject (the chef) does the action.",
  },
  {
    id: "ela-g8-15",
    subject: "ela",
    grade: "8",
    standard: "RL.8.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "For months, Dev told everyone he had built the robot himself, though his older sister had done most of the wiring. At the science fair, a judge asked him to explain the circuit. Dev stared at the wires, his face burning, and finally said, 'Actually, my sister should answer that.'",
    choices: ["Taking credit you didn't earn can backfire.", "Science fairs are unfair.", "Older siblings are smarter.", "Robots are hard to build."],
    answer: 0,
    explanation: "Dev's embarrassment when he can't explain the circuit shows the cost of taking false credit.",
  },
  {
    id: "ela-g8-16",
    subject: "ela",
    grade: "8",
    standard: "RI.8.8",
    skill: "Relevant evidence",
    prompt: "Which sentence is irrelevant to the author's claim?",
    passage: "Our city should add bike lanes downtown. Cities with protected lanes have seen traffic injuries drop. Bike lanes also reduce car emissions. My uncle rides a very expensive bike. More people bike to work when lanes feel safe.",
    choices: ["My uncle rides a very expensive bike.", "Protected lanes cut traffic injuries.", "Bike lanes reduce car emissions.", "More people bike when lanes feel safe."],
    answer: 0,
    explanation: "The uncle's expensive bike says nothing about whether the city needs bike lanes.",
  },
  {
    id: "ela-g8-17",
    subject: "ela",
    grade: "8",
    standard: "RL.8.6",
    skill: "Dramatic irony",
    prompt: "What effect does the reader's knowledge create?",
    passage: "The detective smiled at the butler and thanked him for the tea. He lifted the cup to his lips. Readers already know, from Chapter 2, that the butler stirred sleeping powder into the pot.",
    choices: ["suspense, since readers see a danger he can't", "humor, since the butler is clumsy", "sadness, since the detective leaves", "confusion about the setting"],
    answer: 0,
    explanation: "Because readers know about the sleeping powder and the detective doesn't, dramatic irony builds suspense.",
  },
  {
    id: "ela-g8-18",
    subject: "ela",
    grade: "8",
    standard: "RI.8.6",
    skill: "Conflicting viewpoints",
    prompt: "How does the author respond to the opposing view?",
    passage: "Some argue that video games waste time. However, research shows certain games improve problem-solving and hand-eye coordination. While moderation matters, dismissing all games ignores their real benefits.",
    choices: ["Acknowledges it, then counters with research", "Ignores it completely", "Agrees with it fully", "Insults people who hold it"],
    answer: 0,
    explanation: "The author admits some people disagree, then uses research to answer them.",
  },
  {
    id: "ela-g8-19",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Latin roots",
    prompt: "The Latin root ject (as in eject) means...",
    choices: ["throw", "pull", "speak", "turn"],
    answer: 0,
    explanation: "Ject means throw. To eject is to throw out.",
    quick: true,
  },
  {
    id: "ela-g8-20",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Latin roots",
    prompt: "The Latin root voc (as in vocal) means...",
    choices: ["voice", "see", "turn", "live"],
    answer: 0,
    explanation: "Voc means voice or call, as in vocal and vocabulary.",
    quick: true,
  },
  {
    id: "ela-g8-21",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Greek prefixes",
    prompt: "The prefix mono- (as in monologue) means...",
    choices: ["one", "many", "half", "all"],
    answer: 0,
    explanation: "Mono- means one. A monologue is one person speaking.",
    quick: true,
  },
  {
    id: "ela-g8-22",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Latin roots",
    prompt: "The Latin root duc/duct (as in conduct) means...",
    choices: ["lead", "break", "hold", "push"],
    answer: 0,
    explanation: "Duc and duct mean lead. A conductor leads an orchestra.",
    quick: true,
  },
  {
    id: "ela-g8-23",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Analogies",
    prompt: "Benevolent is to kind as hostile is to...",
    choices: ["unfriendly", "generous", "peaceful", "calm"],
    answer: 0,
    explanation: "Benevolent means kind, so the matching synonym for hostile is unfriendly.",
    quick: true,
  },
  {
    id: "ela-g8-24",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Connotation",
    prompt: "Which word for smell has the most positive connotation?",
    choices: ["fragrance", "stench", "odor", "reek"],
    answer: 0,
    explanation: "Fragrance suggests a pleasant smell. Stench and reek are unpleasant.",
    quick: true,
  },
  {
    id: "ela-g8-25",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Oxymoron",
    prompt: "'Parting is such sweet sorrow' pairs opposites. This is an...",
    choices: ["oxymoron", "simile", "idiom", "allusion"],
    answer: 0,
    explanation: "Sweet sorrow joins two opposite ideas, which makes it an oxymoron.",
    quick: true,
  },
  {
    id: "ela-g8-26",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Irony",
    prompt: "A fire station burning down is an example of what type of irony?",
    choices: ["situational", "verbal", "dramatic", "no irony"],
    answer: 0,
    explanation: "Situational irony is when the opposite of what you expect happens.",
    quick: true,
  },
  {
    id: "ela-g8-27",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Transitive verbs",
    prompt: "In 'She kicked the ball,' kicked is a(n) ___ verb.",
    choices: ["transitive", "intransitive", "linking", "helping"],
    answer: 0,
    explanation: "A transitive verb takes a direct object; the ball is what she kicked.",
    quick: true,
  },
  {
    id: "ela-g8-28",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Conditional mood",
    prompt: "If it ___, we would cancel the picnic. Which verb fits?",
    choices: ["rained", "rains", "rain", "will rain"],
    answer: 0,
    explanation: "The conditional 'would cancel' pairs with the past form: If it rained.",
    quick: true,
  },
  {
    id: "ela-g8-29",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Direct objects",
    prompt: "In 'Mom gave me a book,' what is the direct object?",
    choices: ["book", "me", "Mom", "gave"],
    answer: 0,
    explanation: "The book is what Mom gave, so it is the direct object; me is the indirect object.",
    quick: true,
  },
  {
    id: "ela-g8-30",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Subject-verb agreement",
    prompt: "Neither Ana nor her sisters ___ ready. Which fits?",
    choices: ["are", "is", "be", "was"],
    answer: 0,
    explanation: "With neither/nor, the verb agrees with the nearer subject: sisters are.",
    quick: true,
  },
  {
    id: "ela-g8-31",
    subject: "ela",
    grade: "8",
    standard: "L.8.2",
    skill: "Dashes",
    prompt: "Which mark shows a sudden break in thought?",
    choices: ["dash", "colon", "semicolon", "period"],
    answer: 0,
    explanation: "A dash signals a sudden break or interruption.",
    quick: true,
  },
  {
    id: "ela-g8-32",
    subject: "ela",
    grade: "8",
    standard: "L.8.2",
    skill: "Ellipses",
    prompt: "In the dialogue 'I... I don't know,' the ellipsis shows...",
    choices: ["a pause", "a list", "a question", "a title"],
    answer: 0,
    explanation: "An ellipsis in speech can show a pause or hesitation.",
    quick: true,
  },
  {
    id: "ela-g8-33",
    subject: "ela",
    grade: "8",
    standard: "L.8.2",
    skill: "Spelling",
    prompt: "Which word is spelled correctly?",
    choices: ["necessary", "neccessary", "necesary", "neccesary"],
    answer: 0,
    explanation: "Necessary has one c and two s's.",
    quick: true,
  },
  {
    id: "ela-g8-34",
    subject: "ela",
    grade: "8",
    standard: "RL.8.5",
    skill: "Story structure",
    prompt: "A story told inside another story is a ___ narrative.",
    choices: ["frame", "flash", "parallel", "linear"],
    answer: 0,
    explanation: "A frame narrative wraps one story inside another.",
    quick: true,
  },
  {
    id: "ela-g8-35",
    subject: "ela",
    grade: "8",
    standard: "RL.8.9",
    skill: "Myths in modern fiction",
    prompt: "A modern hero's journey to the underworld most likely draws on a...",
    choices: ["myth", "sonnet", "memoir", "news report"],
    answer: 0,
    explanation: "Journeys to the underworld are patterns from ancient myths.",
    quick: true,
  },
  {
    id: "ela-g8-36",
    subject: "ela",
    grade: "8",
    standard: "RI.8.8",
    skill: "Weak evidence",
    prompt: "'Studies show...' with no study named is a sign of...",
    choices: ["weak evidence", "strong logic", "a counterclaim", "a thesis"],
    answer: 0,
    explanation: "Vague references to studies cannot be checked, so the evidence is weak.",
    quick: true,
  },
  {
    id: "ela-g8-37",
    subject: "ela",
    grade: "8",
    standard: "W.8.1",
    skill: "Transitions",
    prompt: "Which transition introduces a counterclaim?",
    choices: ["admittedly", "therefore", "for instance", "finally"],
    answer: 0,
    explanation: "Admittedly signals that the writer is granting a point to the other side.",
    quick: true,
  },
  {
    id: "ela-g8-38",
    subject: "ela",
    grade: "8",
    standard: "RL.8.4",
    skill: "Analogies",
    prompt: "Comparing the heart to a pump to explain how it works is an...",
    choices: ["analogy", "allusion", "idiom", "irony"],
    answer: 0,
    explanation: "An analogy explains something by comparing it to something familiar.",
    quick: true,
  },
  {
    id: "ela-g8-39",
    subject: "ela",
    grade: "8",
    standard: "RL.8.1",
    skill: "Strongest evidence",
    prompt: "Which detail most strongly shows Devon is nervous?",
    passage: "Devon told everyone he wasn't nervous about the audition. Yet he rehearsed his monologue nineteen times, chewed his pencil to splinters, and checked the clock every two minutes.",
    choices: ["He chewed his pencil to splinters.", "He said he wasn't nervous.", "He had a monologue.", "There was an audition."],
    answer: 0,
    explanation: "Chewing a pencil to splinters is a strong physical sign of nerves.",
  },
  {
    id: "ela-g8-40",
    subject: "ela",
    grade: "8",
    standard: "RL.8.3",
    skill: "Dialogue and plot",
    prompt: "How does this dialogue move the plot forward?",
    passage: "'You took the money,' Elena said quietly. Her brother froze, the envelope still in his hand. 'I was going to put it back,' he whispered.",
    choices: ["It reveals guilt and creates conflict.", "It describes the setting.", "It resolves the conflict.", "It starts a flashback."],
    answer: 0,
    explanation: "Elena's accusation and her brother's reply reveal what he did and create tension.",
  },
  {
    id: "ela-g8-41",
    subject: "ela",
    grade: "8",
    standard: "RL.8.2",
    skill: "Theme",
    prompt: "Which theme develops in this passage?",
    passage: "At first, Mae mocked the old librarian's strict rules. But when a flood ruined the town's records, the librarian's carefully kept copies saved them. Mae began volunteering every Saturday.",
    choices: ["Respect grows when we understand others.", "Libraries are boring.", "Floods destroy towns.", "Rules should be broken."],
    answer: 0,
    explanation: "Mae mocks the librarian until she sees why the rules mattered, then she joins in.",
  },
  {
    id: "ela-g8-42",
    subject: "ela",
    grade: "8",
    standard: "RL.8.4",
    skill: "Tone",
    prompt: "What tone do the quotation marks around 'luxury' create?",
    passage: "The 'luxury' hotel offered a lumpy mattress, a faucet that coughed brown water, and a view of the dumpster.",
    choices: ["sarcastic", "admiring", "neutral", "fearful"],
    answer: 0,
    explanation: "The quotation marks show the hotel was not luxurious at all.",
  },
  {
    id: "ela-g8-43",
    subject: "ela",
    grade: "8",
    standard: "RI.8.2",
    skill: "Central idea",
    prompt: "What central idea does the passage develop?",
    passage: "In the 1840s, doctors rarely washed their hands between patients. When Ignaz Semmelweis required handwashing in his clinic, deaths dropped sharply. Yet many doctors ignored his findings for decades.",
    choices: ["Good evidence can be ignored if it challenges habits.", "Handwashing does not matter.", "Clinics in the 1800s were spotless.", "Doctors always accept new ideas."],
    answer: 0,
    explanation: "Semmelweis had strong results, yet many doctors refused to change for years.",
  },
  {
    id: "ela-g8-44",
    subject: "ela",
    grade: "8",
    standard: "RI.8.5",
    skill: "Paragraph structure",
    prompt: "What is the role of the first sentence?",
    passage: "Many people believe bats are blind. In fact, all bats can see, and some see quite well. Many bats also use echolocation, bouncing sounds off objects to find their way in the dark.",
    choices: ["It states a myth the paragraph corrects.", "It gives the main evidence.", "It concludes the argument.", "It defines echolocation."],
    answer: 0,
    explanation: "The paragraph opens with a common belief and then shows it is false.",
  },
  {
    id: "ela-g8-45",
    subject: "ela",
    grade: "8",
    standard: "RI.8.6",
    skill: "Presenting viewpoints",
    prompt: "How does the author present the issue?",
    passage: "Supporters say the new highway will cut commute times. Residents of Elm Street, however, point out that it would split their neighborhood in two and close the local park.",
    choices: ["By showing two conflicting viewpoints.", "By arguing only for the highway.", "By telling a funny story.", "By listing park rules."],
    answer: 0,
    explanation: "The author gives the supporters' view and the residents' view.",
  },
  {
    id: "ela-g8-46",
    subject: "ela",
    grade: "8",
    standard: "RI.8.8",
    skill: "Faulty reasoning",
    prompt: "Which flaw appears in this argument?",
    passage: "We must ban skateboards downtown. Last month a skater nearly hit a woman. If we don't act, someone will be hurt, then killed, and soon no one will feel safe outside.",
    choices: ["slippery slope", "strong statistics", "expert testimony", "a fair concession"],
    answer: 0,
    explanation: "It claims one event will lead to worse and worse results without proof.",
  },
  {
    id: "ela-g8-47",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Context clues",
    prompt: "What does gregarious mean?",
    passage: "Unlike his gregarious sister, who loved parties, Theo preferred quiet evenings alone with a book.",
    choices: ["sociable", "shy", "studious", "tired"],
    answer: 0,
    explanation: "Unlike Theo, who likes quiet, his sister loves parties, so gregarious means sociable.",
  },
  {
    id: "ela-g8-48",
    subject: "ela",
    grade: "8",
    standard: "RI.8.9",
    skill: "Conflicting information",
    prompt: "What should a careful reader do?",
    passage: "Text A: The museum reported 50,000 visitors last year.\nText B: A city report says the museum had 35,000 visitors last year.",
    choices: ["Check how each source counted.", "Believe the bigger number.", "Ignore both sources.", "Average the two numbers."],
    answer: 0,
    explanation: "When sources disagree, look at how each one got its information.",
  },
];

export default questions;
