import type { Question } from "../../types";
// Grade 4 science — NC Standard Course of Study for Science (2023). Magnets and static electricity (PS.4.1); forms of
// energy, simple circuits, and conductors and insulators (PS.4.2); reflection, refraction and absorption of light
// (PS.4.3); Earth's rotation and the phases of the moon (ESS.4.1); minerals, rocks, weathering, erosion and deposition
// (ESS.4.2); external structures, senses and variation that help animals and plants survive (LS.4.1); fossils as
// evidence of past life and environments (LS.4.2).
const questions: Question[] = [
  {
    id: "sci-g4-01",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.1",
    skill: "Magnets",
    prompt: "A magnet will attract which object?",
    choices: ["Iron nail", "Plastic cup", "Wooden spoon", "Rubber band"],
    answer: 0,
    explanation: "Magnets attract things made of iron (and a few other metals). Plastic, wood and rubber are not attracted.",
    quick: true,
  },
  {
    id: "sci-g4-02",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.1",
    skill: "Magnets",
    prompt: "Two north poles of magnets are held close. They will...",
    choices: ["Repel", "Attract", "Stick", "Melt"],
    answer: 0,
    explanation: "Like poles (north-north or south-south) push apart. Opposite poles pull together.",
    quick: true,
  },
  {
    id: "sci-g4-03",
    subject: "science",
    grade: "4",
    standard: "PS.4.1.2",
    skill: "Static electricity",
    prompt: "A balloon rubbed on hair sticks to a wall. What causes this?",
    choices: ["Static charge", "Glue", "Magnetism", "Gravity"],
    answer: 0,
    explanation: "Rubbing moves electric charges onto the balloon. Charged objects can pull on other objects without touching.",
    quick: true,
  },
  {
    id: "sci-g4-04",
    subject: "science",
    grade: "4",
    standard: "LS.4.2.2",
    skill: "Fossils",
    prompt: "Fish fossils are found high on a mountain. The area was probably once...",
    choices: ["Underwater", "A desert", "Covered in ice", "A city"],
    answer: 0,
    explanation: "Fish live in water, so their fossils tell us that place was once covered by water. Fossils give clues about past environments.",
    quick: true,
  },
  {
    id: "sci-g4-05",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Conductors and insulators",
    prompt: "Which is a good conductor of electricity?",
    choices: ["Copper wire", "Rubber", "Plastic", "Wood"],
    answer: 0,
    explanation: "Metals like copper let electricity flow easily. Rubber and plastic are insulators, so they cover wires.",
    quick: true,
  },
  {
    id: "sci-g4-06",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Energy transfer",
    prompt: "A lamp changes electrical energy mostly into...",
    choices: ["Light and heat", "Motion only", "Sound only", "Food energy"],
    answer: 0,
    explanation: "A light bulb turns electrical energy into light. Some of the energy always becomes heat, too.",
    quick: true,
  },
  {
    id: "sci-g4-07",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Conductors and insulators",
    prompt: "Pot handles often have plastic grips. Plastic is a good heat...",
    choices: ["Insulator", "Conductor", "Magnet", "Mirror"],
    answer: 0,
    explanation: "Insulators slow the flow of heat, so a plastic grip keeps your hand from getting burned.",
    quick: true,
  },
  {
    id: "sci-g4-08",
    subject: "science",
    grade: "4",
    standard: "PS.4.2",
    skill: "Circuits",
    passage:
      "Ava built a circuit with a battery, wires, a switch and a bulb. When the switch is closed, the bulb lights. When she opens the switch, the bulb goes dark right away.",
    prompt: "Why does the bulb go out when the switch is opened?",
    choices: [
      "The path for electricity is broken",
      "The battery is suddenly used up",
      "The bulb got too hot",
      "The wires stopped being metal",
    ],
    answer: 0,
    explanation: "Electricity needs a complete, closed loop. Opening the switch makes a gap, so current stops flowing.",
  },
  {
    id: "sci-g4-09",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.1",
    skill: "Light and reflection",
    prompt: "Light hits a mirror and bounces off. This is called...",
    choices: ["Reflection", "Absorption", "Refraction", "A shadow"],
    answer: 0,
    explanation: "Reflection is light bouncing off a surface. Smooth, shiny surfaces like mirrors reflect light best.",
    quick: true,
  },
  {
    id: "sci-g4-10",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.1",
    skill: "Light and reflection",
    prompt: "Light hits a flat mirror at 30° from straight-on. At what angle does it bounce off?",
    choices: ["30°", "60°", "90°", "0°"],
    answer: 0,
    explanation: "A mirror reflects light at the same angle it came in, just on the other side of the straight-on line.",
    quick: true,
  },
  {
    id: "sci-g4-11",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.1",
    skill: "Day and night",
    prompt: "What causes day and night?",
    choices: ["Earth spinning", "Sun circling", "Clouds", "Moon blocking"],
    answer: 0,
    explanation: "Earth rotates on its axis. The side facing the sun has day, and the side facing away has night.",
    quick: true,
  },
  {
    id: "sci-g4-12",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.1",
    skill: "Day and night",
    prompt: "About how long does Earth take to spin around once?",
    choices: ["About 24 hours", "One week", "One month", "One year"],
    answer: 0,
    explanation: "One full rotation takes about 24 hours, which is one day. A trip around the sun takes one year.",
    quick: true,
  },
  {
    id: "sci-g4-13",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1",
    skill: "Moon phases",
    prompt: "Why does the moon seem to change shape during a month?",
    choices: [
      "We see different amounts of its sunlit half as it orbits Earth",
      "Earth's shadow covers a different part each night",
      "Clouds block part of the moon",
      "The moon grows and shrinks in size",
    ],
    answer: 0,
    explanation: "The sun always lights half the moon. As the moon orbits Earth, we see more or less of that lit half. Earth's shadow only matters during an eclipse.",
  },
  {
    id: "sci-g4-14",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.1",
    skill: "Minerals",
    prompt: "A streak test shows a mineral's...",
    choices: ["Powder color", "Hardness", "Weight", "Shape"],
    answer: 0,
    explanation: "Rubbing a mineral on a streak plate leaves powder. The powder's color can differ from the outside color and helps identify it.",
    quick: true,
  },
  {
    id: "sci-g4-15",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.2",
    skill: "Rocks",
    prompt: "Rock formed when lava cools and hardens is...",
    choices: ["Igneous", "Sedimentary", "Metamorphic", "A fossil"],
    answer: 0,
    explanation: "Igneous rock forms from melted rock (magma or lava) that cools. Sedimentary rock forms from layers of sediment.",
    quick: true,
  },
  {
    id: "sci-g4-16",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.3",
    skill: "Changes to Earth's surface",
    prompt: "Moving water carrying soil and rock away is called...",
    choices: ["Erosion", "Melting", "Freezing", "Deposition"],
    answer: 0,
    explanation: "Erosion moves weathered bits of rock and soil to new places. Deposition is when they are dropped off.",
    quick: true,
  },
  {
    id: "sci-g4-17",
    subject: "science",
    grade: "4",
    standard: "LS.4.1",
    skill: "Adaptations",
    prompt: "Thick fur and fat help a polar bear...",
    choices: ["Stay warm", "Hide in woods", "Eat plants", "Climb trees"],
    answer: 0,
    explanation: "These adaptations hold in body heat so polar bears can survive in the freezing Arctic.",
    quick: true,
  },
  {
    id: "sci-g4-18",
    subject: "science",
    grade: "4",
    standard: "LS.4.1",
    skill: "Behaviors",
    prompt: "Birds flying south for the winter is an example of...",
    choices: ["Migration", "Hibernation", "Camouflage", "Erosion"],
    answer: 0,
    explanation: "Migration is moving to a new place when seasons change, often to find food and warmth.",
    quick: true,
  },
  {
    id: "sci-g4-19",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.1",
    skill: "Forms of energy",
    prompt: "A drum makes a loud boom. Sound is a form of...",
    choices: ["Energy", "Matter", "Gravity", "Magnetism"],
    answer: 0,
    explanation: "Sound is a form of energy. Light, heat and electricity are other forms.",
    quick: true,
  },
  {
    id: "sci-g4-20",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.1",
    skill: "Forms of energy",
    prompt: "A space heater mainly gives off which energy?",
    choices: ["Heat", "Sound", "Magnetic", "Chemical"],
    answer: 0,
    explanation: "A heater changes electrical energy into heat energy that warms the room.",
    quick: true,
  },
  {
    id: "sci-g4-21",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.1",
    skill: "Forms of energy",
    prompt: "A solar toy car moves in sunlight. Light energy became...",
    choices: ["Motion", "Sound", "Gravity", "Magnetism"],
    answer: 0,
    explanation: "The solar panel turns light into electricity, and the motor turns that into motion.",
    quick: true,
  },
  {
    id: "sci-g4-22",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.2",
    skill: "Simple circuits",
    prompt: "Which part of a simple circuit supplies the energy?",
    choices: ["Battery", "Wire", "Switch", "Bulb"],
    answer: 0,
    explanation: "The battery is the energy source. Wires carry the electricity, and the bulb uses it.",
    quick: true,
  },
  {
    id: "sci-g4-23",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.2",
    skill: "Simple circuits",
    prompt: "A bulb lights only when its circuit is...",
    choices: ["Closed", "Open", "Unplugged", "Missing a wire"],
    answer: 0,
    explanation: "Electricity flows only through a closed, complete loop.",
    quick: true,
  },
  {
    id: "sci-g4-24",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.2",
    skill: "Simple circuits",
    prompt: "In a series circuit, one bulb burns out. The other bulbs...",
    choices: ["Go out", "Get brighter", "Stay lit", "Change color"],
    answer: 0,
    explanation: "A series circuit has only one path. One broken bulb breaks the loop, so all the bulbs go out.",
    quick: true,
  },
  {
    id: "sci-g4-25",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.2",
    skill: "Simple circuits",
    prompt: "In a parallel circuit, one bulb burns out. The others...",
    choices: ["Stay lit", "Go out", "Flicker off", "Melt"],
    answer: 0,
    explanation: "A parallel circuit has more than one path, so electricity still reaches the other bulbs.",
    quick: true,
  },
  {
    id: "sci-g4-26",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.3",
    skill: "Conductors and insulators",
    prompt: "Which material is an electrical insulator?",
    choices: ["Rubber", "Copper", "Aluminum foil", "Iron nail"],
    answer: 0,
    explanation: "Rubber does not let electricity flow easily, so it is an insulator. Metals are conductors.",
    quick: true,
  },
  {
    id: "sci-g4-27",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.3",
    skill: "Conductors and insulators",
    prompt: "Wires are coated in plastic because plastic...",
    choices: ["Insulates", "Conducts", "Is magnetic", "Glows"],
    answer: 0,
    explanation: "Plastic is an insulator. The coating keeps electricity inside the wire and protects us from shocks.",
    quick: true,
  },
  {
    id: "sci-g4-28",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.2",
    skill: "Refraction and absorption",
    prompt: "A straw in water looks bent. This bending of light is...",
    choices: ["Refraction", "Reflection", "Absorption", "Vibration"],
    answer: 0,
    explanation: "Light bends when it passes from water into air. This bending is called refraction.",
    quick: true,
  },
  {
    id: "sci-g4-29",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.2",
    skill: "Refraction and absorption",
    prompt: "A black shirt gets hot in the sun because it...",
    choices: ["Absorbs light", "Reflects light", "Bends light", "Makes light"],
    answer: 0,
    explanation: "Dark colors absorb most of the light that hits them, and that energy turns into heat.",
    quick: true,
  },
  {
    id: "sci-g4-30",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.2",
    skill: "Refraction and absorption",
    prompt: "Sunlight passes through a prism and splits into...",
    choices: ["Colors", "Shadows", "Sound", "Sparks"],
    answer: 0,
    explanation: "A prism bends each color of light a different amount, spreading white light into a rainbow.",
    quick: true,
  },
  {
    id: "sci-g4-31",
    subject: "science",
    grade: "4",
    standard: "PS.4.3.1",
    skill: "Reflection",
    prompt: "Which surface reflects light the best?",
    choices: ["Mirror", "Black cloth", "Brick", "Tree bark"],
    answer: 0,
    explanation: "Smooth, shiny surfaces like mirrors bounce back most of the light that hits them.",
    quick: true,
  },
  {
    id: "sci-g4-32",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.2",
    skill: "Moon phases",
    prompt: "Which phase comes right after a new moon?",
    choices: ["Crescent", "Full moon", "Gibbous", "Third quarter"],
    answer: 0,
    explanation: "After the new moon, a thin waxing crescent appears. Then come first quarter, gibbous and full.",
    quick: true,
  },
  {
    id: "sci-g4-33",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.2",
    skill: "Moon phases",
    prompt: "About how long does one full cycle of moon phases take?",
    choices: ["About 29 days", "About 7 days", "About 365 days", "About 1 day"],
    answer: 0,
    explanation: "The moon goes from new moon to new moon in about 29½ days.",
    quick: true,
  },
  {
    id: "sci-g4-34",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.2",
    skill: "Moon phases",
    prompt: "When the moon is waxing, the lit part we see is...",
    choices: ["Growing", "Shrinking", "Staying same", "Turning red"],
    answer: 0,
    explanation: "Waxing means growing. Waning means shrinking.",
    quick: true,
  },
  {
    id: "sci-g4-35",
    subject: "science",
    grade: "4",
    standard: "ESS.4.1.1",
    skill: "Earth's rotation",
    prompt: "The sun seems to rise in the east because Earth spins toward the...",
    choices: ["East", "West", "North", "South"],
    answer: 0,
    explanation: "Earth spins from west to east. As we turn toward the east, the sun comes into view there.",
    quick: true,
  },
  {
    id: "sci-g4-36",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.1",
    skill: "Structures for survival",
    prompt: "A hawk's sharp talons help it...",
    choices: ["Catch prey", "Swim", "Stay warm", "Hear well"],
    answer: 0,
    explanation: "Talons are sharp, curved claws that let a hawk grab and hold its prey.",
    quick: true,
  },
  {
    id: "sci-g4-37",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.1",
    skill: "Structures for survival",
    prompt: "A porcupine's quills are used mainly for...",
    choices: ["Defense", "Swimming", "Eating", "Hearing"],
    answer: 0,
    explanation: "Sharp quills protect a porcupine from predators.",
    quick: true,
  },
  {
    id: "sci-g4-38",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.1",
    skill: "Structures for survival",
    prompt: "Big, wide leaves help plants on a shady forest floor catch more...",
    choices: ["Sunlight", "Snow", "Sand", "Insects"],
    answer: 0,
    explanation: "Little light reaches the forest floor. Wide leaves gather as much sunlight as possible.",
    quick: true,
  },
  {
    id: "sci-g4-39",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.2",
    skill: "Senses and responses",
    prompt: "A bat finds insects in the dark by using...",
    choices: ["Echoes", "Light", "Taste", "Magnets"],
    answer: 0,
    explanation: "Bats make high sounds and listen for the echoes. This is called echolocation.",
    quick: true,
  },
  {
    id: "sci-g4-40",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.2",
    skill: "Senses and responses",
    prompt: "A snake flicks its tongue to...",
    choices: ["Smell", "Drink", "Hear", "See"],
    answer: 0,
    explanation: "A snake's tongue picks up scent particles from the air so it can smell prey.",
    quick: true,
  },
  {
    id: "sci-g4-41",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.2",
    skill: "Senses and responses",
    prompt: "Messages from your senses travel to your brain through...",
    choices: ["Nerves", "Bones", "Blood", "Hair"],
    answer: 0,
    explanation: "Nerves carry signals from your eyes, ears, skin, nose and tongue to your brain.",
    quick: true,
  },
  {
    id: "sci-g4-42",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.1",
    skill: "Minerals",
    prompt: "How a mineral shines in light is called its...",
    choices: ["Luster", "Streak", "Hardness", "Mass"],
    answer: 0,
    explanation: "Luster describes shine, like metallic, glassy or dull.",
    quick: true,
  },
  {
    id: "sci-g4-43",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.3",
    skill: "Changes to Earth's surface",
    prompt: "Which is a fast change to Earth's surface?",
    choices: ["Earthquake", "Weathering", "Rain erosion", "Glacier moving"],
    answer: 0,
    explanation: "Earthquakes, landslides and volcanoes change the land quickly. Weathering and erosion are slow.",
    quick: true,
  },
  {
    id: "sci-g4-44",
    subject: "science",
    grade: "4",
    standard: "ESS.4.2.3",
    skill: "Changes to Earth's surface",
    prompt: "A river drops sand at its mouth and builds a delta. This is...",
    choices: ["Deposition", "Erosion", "Weathering", "Melting"],
    answer: 0,
    explanation: "Deposition is when moving water, wind or ice drops the sediment it was carrying.",
    quick: true,
  },
  {
    id: "sci-g4-45",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.2",
    skill: "Simple circuits",
    passage:
      "Leah connects one wire from the top of a battery to a bulb. She does not connect any wire from the bulb back to the bottom of the battery.",
    prompt: "Why doesn't the bulb light?",
    choices: [
      "The circuit is not a complete loop",
      "The battery has too much energy",
      "Bulbs need two batteries to light",
      "The wires are too short",
    ],
    answer: 0,
    explanation: "Electricity needs a closed path from one end of the battery, through the bulb, and back to the other end.",
  },
  {
    id: "sci-g4-46",
    subject: "science",
    grade: "4",
    standard: "PS.4.2.3",
    skill: "Conductors and insulators",
    passage:
      "Rami tested objects in a circuit. The bulb lit with a steel nail and a metal spoon. It did not light with a rubber eraser or a wooden craft stick.",
    prompt: "Which objects are conductors?",
    choices: ["Nail and spoon", "Eraser and nail", "Spoon and eraser", "Craft stick and spoon"],
    answer: 0,
    explanation: "The bulb lit only with the metal nail and metal spoon. Metals are good conductors of electricity.",
  },
  {
    id: "sci-g4-47",
    subject: "science",
    grade: "4",
    standard: "LS.4.1.3",
    skill: "Variation and survival",
    passage:
      "In a forest, most tree bark turned dark from soot. Some moths are light and some are dark. Birds eat the moths they can see.",
    prompt: "What will most likely happen over many years?",
    choices: ["More moths will be dark", "More moths will be light", "All moths will leave", "Moths will turn white"],
    answer: 0,
    explanation: "Dark moths are harder for birds to spot on dark bark, so more of them survive and have young.",
  },
  {
    id: "sci-g4-48",
    subject: "science",
    grade: "4",
    standard: "LS.4.2",
    skill: "Fossil evidence",
    passage:
      "Scientists found fossils of fern plants in rocks in Antarctica, which is now covered in ice.",
    prompt: "What do the fossils suggest about Antarctica long ago?",
    choices: ["It was much warmer", "It was always icy", "It was a deep ocean", "It had no plants"],
    answer: 0,
    explanation: "Ferns need warm, wet places. Fern fossils show Antarctica once had a warmer climate.",
  },
];
export default questions;
