import type { Question } from "../../types";
// Grade 11 social studies — NC Standard Course of Study for Social Studies (adopted 2021). American History (1763 to present): Revolution, expansion, Civil War and
// Reconstruction, world wars, Cold War, civil rights and recent history (AH.H.1.1, AH.H.1); rights, amendments and court rulings (AH.C&G.1.1, AH.C&G.1); capitalism, labor and
// the Depression (AH.E.1.1, AH.E.1); migration and settlement (AH.G.1.1, AH.G.1); American identity (AH.B.1.1, AH.B.1.2, AH.B.1).
const questions: Question[] = [
  {
    id: "soc-g11-01",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Road to revolution",
    prompt: "Colonists protested the 1765 Stamp Act with 'no taxation without...'",
    choices: ["Representation", "Permission", "Money", "A king"],
    answer: 0,
    explanation: "Colonists had no members in Parliament, so they said Parliament had no right to tax them.",
    quick: true,
  },
  {
    id: "soc-g11-02",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Expansion",
    prompt: "The United States bought the Louisiana Territory in 1803 from...",
    choices: ["France", "Spain", "Britain", "Mexico"],
    answer: 0,
    explanation: "Jefferson bought it from Napoleon's France, doubling the size of the country.",
    quick: true,
  },
  {
    id: "soc-g11-03",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Expansion",
    prompt: "Manifest Destiny was the belief the U.S. should expand...",
    choices: ["To the Pacific", "Into Europe", "Into Africa", "Into Asia"],
    answer: 0,
    explanation: "The idea encouraged westward expansion, often at the expense of American Indians and Mexico.",
    quick: true,
  },
  {
    id: "soc-g11-04",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Reform",
    prompt: "The 1848 Seneca Falls Convention focused on...",
    choices: ["Women's rights", "Railroads", "Gold", "Tariffs"],
    answer: 0,
    explanation: "Elizabeth Cady Stanton and others issued the Declaration of Sentiments demanding equal rights for women.",
    quick: true,
  },
  {
    id: "soc-g11-05",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Reconstruction",
    prompt: "Which amendment (1868) granted citizenship and equal protection?",
    choices: ["14th", "13th", "15th", "19th"],
    answer: 0,
    explanation: "The 14th Amendment made formerly enslaved people citizens and promised equal protection of the laws.",
    quick: true,
  },
  {
    id: "soc-g11-06",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Segregation",
    prompt: "Plessy v. Ferguson (1896) upheld which policy?",
    choices: ["Segregation", "Integration", "Busing", "Suffrage"],
    answer: 0,
    explanation: "The Court approved 'separate but equal' facilities, allowing Jim Crow segregation.",
    quick: true,
  },
  {
    id: "soc-g11-07",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Civil rights",
    prompt: "Brown v. Board of Education (1954) overturned the ruling in...",
    choices: ["Plessy", "Marbury", "Miranda", "Dred Scott"],
    answer: 0,
    explanation: "Brown ruled that separate schools are inherently unequal, reversing Plessy v. Ferguson.",
    quick: true,
  },
  {
    id: "soc-g11-08",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Industrialization",
    prompt: "In the late 1800s, most new immigrants settled in...",
    choices: ["Cities", "Deserts", "Plantations", "Mountains"],
    answer: 0,
    explanation: "Factory jobs drew immigrants to growing cities like New York and Chicago.",
    quick: true,
  },
  {
    id: "soc-g11-09",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "World War I",
    prompt: "The United States entered World War I in...",
    choices: ["1917", "1914", "1941", "1898"],
    answer: 0,
    explanation: "The war began in 1914. The U.S. joined in April 1917.",
    quick: true,
  },
  {
    id: "soc-g11-10",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Great Depression",
    prompt: "Franklin Roosevelt's programs to fight the Depression were called the...",
    choices: ["New Deal", "Fair Deal", "Square Deal", "Great Society"],
    answer: 0,
    explanation: "The New Deal created jobs programs, Social Security and banking reforms.",
    quick: true,
  },
  {
    id: "soc-g11-11",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "World War II",
    prompt: "The U.S. entered World War II after the attack on...",
    choices: ["Pearl Harbor", "Midway", "Normandy", "Iwo Jima"],
    answer: 0,
    explanation: "Japan attacked Pearl Harbor, Hawaii, on December 7, 1941.",
    quick: true,
  },
  {
    id: "soc-g11-12",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Cold War",
    prompt: "The 1962 Cuban Missile Crisis was a standoff between the U.S. and the...",
    choices: ["Soviet Union", "United Kingdom", "Vietnam", "Canada"],
    answer: 0,
    explanation: "Soviet missiles in Cuba brought the superpowers close to nuclear war until a deal was reached.",
    quick: true,
  },
  {
    id: "soc-g11-13",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Civil rights",
    prompt: "The Voting Rights Act became law in...",
    choices: ["1965", "1954", "1920", "1870"],
    answer: 0,
    explanation: "The 1965 act banned literacy tests and other barriers that blocked Black citizens from voting.",
    quick: true,
  },
  {
    id: "soc-g11-14",
    subject: "social",
    grade: "11",
    standard: "AH.B.1.1",
    skill: "American identity",
    prompt: "The idea that the U.S. has a unique mission or character is American...",
    choices: ["Exceptionalism", "Federalism", "Nativism", "Isolationism"],
    answer: 0,
    explanation: "Americans have debated this idea from the colonial era to today.",
    quick: true,
  },
  {
    id: "soc-g11-15",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Recent history",
    prompt: "After the September 11, 2001 attacks, the U.S. led a war in...",
    choices: ["Afghanistan", "Vietnam", "Korea", "Mexico"],
    answer: 0,
    explanation: "U.S. forces entered Afghanistan in October 2001 and withdrew in 2021.",
    quick: true,
  },
  {
    id: "soc-g11-16",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil War",
    passage:
      "On January 1, 1863, President Lincoln declared that all enslaved people 'within any State or designated part of a State, the people whereof shall then be in rebellion against the United States, shall be then, thenceforward, and forever free.'",
    prompt: "What was a limit of the Emancipation Proclamation?",
    choices: ["It applied only to areas in rebellion", "It freed no one at all", "It applied only to the North", "It ended slavery everywhere at once"],
    answer: 0,
    explanation: "It did not cover border states loyal to the Union. The 13th Amendment (1865) ended slavery nationwide.",
  },
  {
    id: "soc-g11-17",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil rights",
    passage:
      "On February 1, 1960, four Black students from NC A&T sat at a whites-only lunch counter in Greensboro. Within about two months, sit-ins had spread to more than 50 cities in 13 states.",
    prompt: "What does this passage show about the sit-in movement?",
    choices: ["Nonviolent protest spread quickly", "The protest failed right away", "Only adults took part", "It started in the North"],
    answer: 0,
    explanation: "The Greensboro Four inspired students across the South to use sit-ins.",
  },
  {
    id: "soc-g11-18",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Progressive Era",
    passage:
      "In 1906, Upton Sinclair's novel The Jungle described filthy conditions in Chicago meatpacking plants, where spoiled meat and waste were packaged for sale.",
    prompt: "Which government action most directly followed this book?",
    choices: ["Meat Inspection Act", "Homestead Act", "Interstate highways", "19th Amendment"],
    answer: 0,
    explanation: "Public outrage led Congress to pass the Meat Inspection Act and Pure Food and Drug Act in 1906.",
  },
  {
    id: "soc-g11-19",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Road to revolution",
    prompt: "The 1773 Boston Tea Party protested a British law about...",
    choices: ["Tea", "Stamps", "Sugar", "Paper"],
    answer: 0,
    explanation: "Colonists dumped British East India Company tea into Boston Harbor to protest the Tea Act.",
    quick: true,
  },
  {
    id: "soc-g11-20",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Foreign policy",
    prompt: "Which 1823 policy warned Europe not to colonize the Americas further?",
    choices: ["Monroe Doctrine", "Open Door", "Containment", "Good Neighbor"],
    answer: 0,
    explanation: "President Monroe said the Western Hemisphere was closed to new European colonies.",
  },
  {
    id: "soc-g11-21",
    subject: "social",
    grade: "11",
    standard: "AH.H.1.1",
    skill: "Indian removal",
    prompt: "The Indian Removal Act was signed in 1830 by President...",
    choices: ["Jackson", "Jefferson", "Lincoln", "Polk"],
    answer: 0,
    explanation: "Andrew Jackson's policy forced the Cherokee, Creek, Choctaw, Chickasaw and Seminole west.",
    quick: true,
  },
  {
    id: "soc-g11-22",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Expansion",
    prompt: "The 1848 treaty ending the Mexican-American War gave the U.S....",
    choices: ["California", "Florida", "Alaska", "Louisiana"],
    answer: 0,
    explanation: "In the Treaty of Guadalupe Hidalgo, Mexico gave up California and much of the Southwest.",
    quick: true,
  },
  {
    id: "soc-g11-23",
    subject: "social",
    grade: "11",
    standard: "AH.H.1.1",
    skill: "Civil War",
    prompt: "The first shots of the Civil War were fired in 1861 at Fort...",
    choices: ["Sumter", "McHenry", "Fisher", "Ticonderoga"],
    answer: 0,
    explanation: "Confederates fired on Fort Sumter in Charleston Harbor on April 12, 1861.",
    quick: true,
  },
  {
    id: "soc-g11-24",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil War",
    prompt: "Lincoln's Gettysburg Address described a nation 'conceived in...'",
    choices: ["Liberty", "War", "Faith", "Wealth"],
    answer: 0,
    explanation: "'Conceived in Liberty, and dedicated to the proposition that all men are created equal.'",
    quick: true,
  },
  {
    id: "soc-g11-25",
    subject: "social",
    grade: "11",
    standard: "AH.H.1.1",
    skill: "Reconstruction",
    prompt: "Reconstruction ended after the Compromise of...",
    choices: ["1877", "1850", "1820", "1865"],
    answer: 0,
    explanation: "Federal troops left the South, and Southern states soon passed Jim Crow laws.",
    quick: true,
  },
  {
    id: "soc-g11-26",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Imperialism",
    prompt: "The Spanish-American War of 1898 gave the U.S. control of...",
    choices: ["Puerto Rico", "Alaska", "Texas", "Oregon"],
    answer: 0,
    explanation: "The U.S. gained Puerto Rico, Guam and the Philippines from Spain.",
    quick: true,
  },
  {
    id: "soc-g11-27",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Cold War",
    prompt: "The 1948–49 Berlin Airlift supplied West Berlin after the Soviets...",
    choices: ["Blocked access", "Built a dam", "Surrendered", "Joined NATO"],
    answer: 0,
    explanation: "When the Soviets blocked roads and railways, U.S. and British planes flew in food and fuel.",
    quick: true,
  },
  {
    id: "soc-g11-28",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Vietnam War",
    prompt: "U.S. combat troops left Vietnam in...",
    choices: ["1973", "1965", "1954", "1991"],
    answer: 0,
    explanation: "The last U.S. combat troops left in 1973. South Vietnam fell in 1975.",
    quick: true,
  },
  {
    id: "soc-g11-29",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Watergate",
    prompt: "The Watergate scandal led President Nixon to...",
    choices: ["Resign", "Run again", "Veto Congress", "Declare war"],
    answer: 0,
    explanation: "Nixon resigned in August 1974, the only President to do so.",
    quick: true,
  },
  {
    id: "soc-g11-30",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Recent history",
    prompt: "The 1991 Persian Gulf War pushed Iraqi forces out of...",
    choices: ["Kuwait", "Iran", "Egypt", "Israel"],
    answer: 0,
    explanation: "A U.S.-led coalition freed Kuwait, which Iraq had invaded in 1990.",
    quick: true,
  },
  {
    id: "soc-g11-31",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Recent history",
    prompt: "In 2008, Barack Obama became the first African American elected...",
    choices: ["President", "Senator", "Governor", "Mayor"],
    answer: 0,
    explanation: "Obama served two terms as President, from 2009 to 2017.",
    quick: true,
  },
  {
    id: "soc-g11-32",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil rights",
    prompt: "The Montgomery Bus Boycott (1955–56) began after the arrest of...",
    choices: ["Rosa Parks", "Ruby Bridges", "Ella Baker", "Diane Nash"],
    answer: 0,
    explanation: "The boycott lasted 381 days and ended with bus segregation ruled unconstitutional.",
    quick: true,
  },
  {
    id: "soc-g11-33",
    subject: "social",
    grade: "11",
    standard: "AH.G.1.1",
    skill: "Migration",
    prompt: "The Dust Bowl of the 1930s drove many farm families from Oklahoma to...",
    choices: ["California", "Maine", "Florida", "Alaska"],
    answer: 0,
    explanation: "Drought and dust storms ruined Plains farms, and many 'Okies' sought work in California.",
    quick: true,
  },
  {
    id: "soc-g11-34",
    subject: "social",
    grade: "11",
    standard: "AH.G.1.1",
    skill: "Immigration",
    prompt: "The Immigration Act of 1924 used quotas to sharply limit immigration from...",
    choices: ["Southern and Eastern Europe", "Northern and Western Europe", "Canada", "Mexico"],
    answer: 0,
    explanation: "Quotas favored Northern and Western Europeans and barred most Asians. The 1965 act ended the national-origins quotas.",
  },
  {
    id: "soc-g11-35",
    subject: "social",
    grade: "11",
    standard: "AH.G.1.1",
    skill: "Great Migration",
    passage:
      "Between about 1910 and 1970, roughly six million Black Southerners moved to cities in the North, Midwest and West.",
    prompt: "Which pair of factors best explains this migration?",
    choices: ["Jim Crow laws in the South and factory jobs elsewhere", "Free land in the South and droughts in the North", "Gold rushes and new railroads", "Wars in Europe and cheap farmland in Mississippi"],
    answer: 0,
    explanation: "Segregation and violence pushed people out of the South, and jobs pulled them to other cities.",
  },
  {
    id: "soc-g11-36",
    subject: "social",
    grade: "11",
    standard: "AH.G.1",
    skill: "Western settlement",
    prompt: "Which 1862 law offered settlers 160 acres of western land?",
    choices: ["Homestead Act", "Dawes Act", "Morrill Act", "Stamp Act"],
    answer: 0,
    explanation: "Settlers who farmed the land for five years could own it. The Morrill Act funded land-grant colleges.",
    quick: true,
  },
  {
    id: "soc-g11-37",
    subject: "social",
    grade: "11",
    standard: "AH.E.1.1",
    skill: "Industrialization",
    prompt: "Rockefeller's Standard Oil was an example of a...",
    choices: ["Monopoly", "Union", "Co-op", "Charity"],
    answer: 0,
    explanation: "Standard Oil controlled about 90% of U.S. oil refining before it was broken up in 1911.",
    quick: true,
  },
  {
    id: "soc-g11-38",
    subject: "social",
    grade: "11",
    standard: "AH.E.1.1",
    skill: "Regulation",
    prompt: "Which 1890 law was the first federal law against monopolies?",
    choices: ["Sherman Act", "Clayton Act", "Wagner Act", "Taft-Hartley"],
    answer: 0,
    explanation: "The Sherman Antitrust Act banned trusts that restrained trade. The Clayton Act came in 1914.",
    quick: true,
  },
  {
    id: "soc-g11-39",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Labor",
    prompt: "Workers formed ___ to bargain together for better pay and conditions.",
    choices: ["Unions", "Trusts", "Tariffs", "Cartels"],
    answer: 0,
    explanation: "Labor unions like the AFL used collective bargaining and strikes.",
    quick: true,
  },
  {
    id: "soc-g11-40",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "New Deal",
    prompt: "The Wagner Act (1935) protected workers' right to...",
    choices: ["Unionize", "Vote", "Pay no tax", "Retire at 50"],
    answer: 0,
    explanation: "The act created the National Labor Relations Board to protect union organizing.",
    quick: true,
  },
  {
    id: "soc-g11-41",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Great Depression",
    passage:
      "U.S. unemployment rate (estimates): 1929 – 3%. 1933 – 25%. 1937 – 14%. 1938 – 19%. 1941 – 10%.",
    prompt: "What does the chart show?",
    choices: ["Unemployment peaked in 1933 and then fell unevenly", "Unemployment rose every year from 1929 to 1941", "Unemployment was highest in 1941", "The Depression ended in 1930"],
    answer: 0,
    explanation: "Unemployment soared to about 25%, improved under the New Deal, rose again in 1938 and fell as war production grew.",
  },
  {
    id: "soc-g11-42",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1.1",
    skill: "Rights of the accused",
    prompt: "In Miranda v. Arizona (1966), the Court ruled police must tell suspects their...",
    choices: ["Rights", "Bail", "Sentence", "Verdict"],
    answer: 0,
    explanation: "Police must tell suspects they have the right to remain silent and to have a lawyer.",
    quick: true,
  },
  {
    id: "soc-g11-43",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1.1",
    skill: "Civil rights",
    prompt: "The Civil Rights Act of 1964 banned discrimination in public places and in...",
    choices: ["Employment", "Taxes", "Farming", "Sports"],
    answer: 0,
    explanation: "Title VII of the act banned job discrimination based on race, color, religion, sex or national origin.",
    quick: true,
  },
  {
    id: "soc-g11-44",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1.1",
    skill: "Citizenship",
    prompt: "Congress granted citizenship to all American Indians born in the U.S. in...",
    choices: ["1924", "1830", "1868", "1965"],
    answer: 0,
    explanation: "The Indian Citizenship Act of 1924 made all Native Americans born in the U.S. citizens.",
    quick: true,
  },
  {
    id: "soc-g11-45",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "World War II",
    prompt: "In 1988, Congress apologized and paid reparations to Japanese Americans who had been...",
    choices: ["Interned", "Drafted", "Elected", "Knighted"],
    answer: 0,
    explanation: "About 120,000 Japanese Americans were forced into camps during WWII. The Civil Liberties Act of 1988 apologized.",
    quick: true,
  },
  {
    id: "soc-g11-46",
    subject: "social",
    grade: "11",
    standard: "AH.B.1.2",
    skill: "Perspectives on identity",
    passage:
      "Frederick Douglass, speaking in Rochester, New York, July 5, 1852: 'This Fourth of July is yours, not mine. You may rejoice, I must mourn.'",
    prompt: "What is Douglass's main point?",
    choices: ["The nation's celebration of liberty excluded enslaved people", "He disliked holiday fireworks", "Independence Day should be moved", "Slavery had already ended"],
    answer: 0,
    explanation: "Douglass pointed out that the promise of liberty did not yet apply to millions of enslaved Americans.",
  },
  {
    id: "soc-g11-47",
    subject: "social",
    grade: "11",
    standard: "AH.B.1.1",
    skill: "American identity",
    passage:
      "President John F. Kennedy's inaugural address, January 20, 1961: 'And so, my fellow Americans: ask not what your country can do for you – ask what you can do for your country.'",
    prompt: "What value does Kennedy appeal to?",
    choices: ["Civic duty and public service", "Isolation from world affairs", "Personal wealth", "Lower taxes"],
    answer: 0,
    explanation: "Kennedy asked Americans to serve their country, and programs like the Peace Corps followed.",
  },
  {
    id: "soc-g11-48",
    subject: "social",
    grade: "11",
    standard: "AH.B.1",
    skill: "Culture",
    prompt: "The 1920s flowering of Black art, music and writing in New York was the ___ Renaissance.",
    choices: ["Harlem", "Brooklyn", "Boston", "Chicago"],
    answer: 0,
    explanation: "Writers like Langston Hughes and Zora Neale Hurston and musicians like Duke Ellington made Harlem a cultural center.",
    quick: true,
  },
];

export default questions;
