import type { Question } from "../../types";
// Grade 12 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Economics and Personal Finance: economic systems, supply and demand, inflation,
// the Fed (EPF.E.1, EPF.E.1.1); income and education (EPF.IE.1, EPF.IE.1.1); budgeting, credit and interest (EPF.MM.1); investing (EPF.FP.1, EPF.FP.1.1); consumer decisions (EPF.CC.1, EPF.CC.1.1).
const questions: Question[] = [
  {
    id: "soc-g12-01",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.1",
    skill: "Economic systems",
    prompt: "An economy where customs decide what to produce is...",
    choices: ["Traditional", "Command", "Market", "Mixed"],
    answer: 0,
    explanation: "In a traditional economy, people produce what their ancestors did.",
    quick: true,
  },
  {
    id: "soc-g12-02",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1.1",
    skill: "Economic systems",
    prompt: "Most economies, including the U.S., are...",
    choices: ["Mixed", "Pure command", "Traditional", "Pure market"],
    answer: 0,
    explanation: "The U.S. mixes free markets with some government rules and services.",
    quick: true,
  },
  {
    id: "soc-g12-03",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "Supply and demand",
    prompt: "When a price rises, quantity demanded usually...",
    choices: ["Falls", "Rises", "Stays same", "Doubles"],
    answer: 0,
    explanation: "The law of demand: higher prices mean people buy less.",
    quick: true,
  },
  {
    id: "soc-g12-04",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "Opportunity cost",
    prompt: "The value of the next-best option you give up is the opportunity...",
    choices: ["Cost", "Profit", "Market", "Budget"],
    answer: 0,
    explanation: "Every choice has an opportunity cost, the value of what you did not choose.",
    quick: true,
  },
  {
    id: "soc-g12-05",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "Inflation",
    prompt: "A general rise in prices over time is...",
    choices: ["Inflation", "Deflation", "Recession", "Interest"],
    answer: 0,
    explanation: "Inflation means each dollar buys less than before.",
    quick: true,
  },
  {
    id: "soc-g12-06",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "Monetary policy",
    prompt: "The Federal Reserve is the U.S....",
    choices: ["Central bank", "Tax agency", "Stock market", "Trade court"],
    answer: 0,
    explanation: "The Fed manages the money supply and sets key interest rates.",
    quick: true,
  },
  {
    id: "soc-g12-07",
    subject: "social",
    grade: "12",
    standard: "EPF.E.1",
    skill: "GDP",
    prompt: "GDP measures a country's total...",
    choices: ["Output", "Debt", "Savings", "Population"],
    answer: 0,
    explanation: "Gross domestic product is the value of all final goods and services made in a country in a year.",
    quick: true,
  },
  {
    id: "soc-g12-08",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1.1",
    skill: "Education and income",
    prompt: "On average, more education is linked to higher...",
    choices: ["Earnings", "Prices", "Rent", "Inflation"],
    answer: 0,
    explanation: "Workers with more education or training tend to earn more and face less unemployment.",
    quick: true,
  },
  {
    id: "soc-g12-09",
    subject: "social",
    grade: "12",
    standard: "EPF.IE.1",
    skill: "Paychecks",
    prompt: "Paycheck money withheld for Social Security and Medicare is called...",
    choices: ["FICA", "Interest", "Tips", "Dividends"],
    answer: 0,
    explanation: "FICA taxes fund Social Security and Medicare.",
    quick: true,
  },
  {
    id: "soc-g12-10",
    subject: "social",
    grade: "12",
    standard: "EPF.MM.1",
    skill: "Budgeting",
    prompt: "A plan for spending and saving money is a...",
    choices: ["Budget", "Loan", "Tax", "Bond"],
    answer: 0,
    explanation: "A budget compares income and expenses so you can reach goals.",
    quick: true,
  },
  {
    id: "soc-g12-11",
    subject: "social",
    grade: "12",
    standard: "EPF.MM.1",
    skill: "Credit",
    prompt: "A credit score mainly shows how well you...",
    choices: ["Repay debts", "Earn money", "Invest", "Spend cash"],
    answer: 0,
    explanation: "Lenders use credit scores to judge how likely you are to pay back a loan.",
    quick: true,
  },
  {
    id: "soc-g12-12",
    subject: "social",
    grade: "12",
    standard: "EPF.MM.1",
    skill: "Interest",
    prompt: "Interest earned on both principal and past interest is...",
    choices: ["Compound", "Simple", "Fixed", "Flat"],
    answer: 0,
    explanation: "Compound interest grows faster over time because interest earns interest.",
    quick: true,
  },
  {
    id: "soc-g12-13",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Investing",
    prompt: "Spreading money across many investments is called...",
    choices: ["Diversifying", "Borrowing", "Budgeting", "Leasing"],
    answer: 0,
    explanation: "Diversifying lowers risk because one bad investment hurts less.",
    quick: true,
  },
  {
    id: "soc-g12-14",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1.1",
    skill: "Risk and return",
    prompt: "Which usually has the highest long-term risk and return?",
    choices: ["Stocks", "Savings acct", "CDs", "Gov't bonds"],
    answer: 0,
    explanation: "Stocks rise and fall more, but historically they have earned more over long periods.",
    quick: true,
  },
  {
    id: "soc-g12-15",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1.1",
    skill: "Advertising",
    prompt: "An ad where a famous athlete praises a product uses...",
    choices: ["An endorsement", "A warranty", "A rebate", "A recall"],
    answer: 0,
    explanation: "Endorsements try to persuade consumers by linking a product to someone they admire.",
    quick: true,
  },
  {
    id: "soc-g12-16",
    subject: "social",
    grade: "12",
    standard: "EPF.CC.1",
    skill: "Consumer protection",
    prompt: "A phishing email tries to...",
    choices: ["Steal info", "Save money", "Pay taxes", "Send refunds"],
    answer: 0,
    explanation: "Phishing messages pretend to be trusted companies to trick you into sharing passwords or account numbers.",
    quick: true,
  },
  {
    id: "soc-g12-17",
    subject: "social",
    grade: "12",
    standard: "EPF.MM.1",
    skill: "Budgeting",
    passage:
      "Kia's take-home pay is $2,400 a month. She follows the 50/30/20 rule: 50% for needs, 30% for wants and 20% for savings and paying down debt.",
    prompt: "Using the 50/30/20 rule, how much should Kia save each month?",
    choices: ["$480", "$720", "$1,200", "$240"],
    answer: 0,
    explanation: "20% of $2,400 is $480. Needs get $1,200 and wants get $720.",
  },
  {
    id: "soc-g12-18",
    subject: "social",
    grade: "12",
    standard: "EPF.FP.1",
    skill: "Compound interest",
    passage:
      "Sam deposits $1,000 in a savings account that pays 5% interest, compounded once a year. He makes no other deposits or withdrawals.",
    prompt: "How much will be in the account after 2 years?",
    choices: ["$1,102.50", "$1,100.00", "$1,050.00", "$1,200.00"],
    answer: 0,
    explanation: "Year 1: $1,000 × 1.05 = $1,050. Year 2: $1,050 × 1.05 = $1,102.50.",
  },
];

export default questions;
