import type { Question } from "../../types";
// Grade 2 social studies — NC Standard Course of Study for Social Studies (adopted 2021). America as part of the world: people and holidays in U.S. history (2.H.1);
// continents, oceans and the 50 states (2.G.1); democracy, voting and the Constitution (2.C&G.1); scarcity, consumers and income (2.E.1); culture and immigration (2.B.1).
const questions: Question[] = [
  {
    id: "soc-g2-01",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "How many continents are there?",
    choices: ["7", "5", "3", "10"],
    answer: 0,
    explanation: "The seven continents are Africa, Antarctica, Asia, Australia, Europe, North America and South America.",
    quick: true,
  },
  {
    id: "soc-g2-02",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "The United States is on which continent?",
    choices: ["North America", "South America", "Europe", "Africa"],
    answer: 0,
    explanation: "The United States is in North America, along with Canada and Mexico.",
    quick: true,
  },
  {
    id: "soc-g2-03",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "Which ocean touches North Carolina?",
    choices: ["Atlantic", "Pacific", "Arctic", "Indian"],
    answer: 0,
    explanation: "The Atlantic Ocean is on the East Coast. The Pacific is on the West Coast.",
    quick: true,
  },
  {
    id: "soc-g2-04",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "States",
    prompt: "How many states does the U.S. have?",
    choices: ["50", "13", "48", "100"],
    answer: 0,
    explanation: "The United States has 50 states. North Carolina is one of them.",
    quick: true,
  },
  {
    id: "soc-g2-05",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "The first U.S. President was George...",
    choices: ["Washington", "Lincoln", "Jefferson", "Adams"],
    answer: 0,
    explanation: "George Washington became the first President in 1789.",
    quick: true,
  },
  {
    id: "soc-g2-06",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "Who led many enslaved people to freedom?",
    choices: ["Harriet Tubman", "Betsy Ross", "Amelia Earhart", "Paul Revere"],
    answer: 0,
    explanation: "Harriet Tubman escaped slavery and then guided others to freedom on the Underground Railroad.",
    quick: true,
  },
  {
    id: "soc-g2-07",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "Martin Luther King Jr. worked for...",
    choices: ["Equal rights", "Space travel", "Faster cars", "New sports"],
    answer: 0,
    explanation: "Dr. King led peaceful protests so all people would be treated fairly.",
    quick: true,
  },
  {
    id: "soc-g2-08",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "Holidays and symbols",
    prompt: "July 4th is ___ Day.",
    choices: ["Independence", "Thanksgiving", "Labor", "Earth"],
    answer: 0,
    explanation: "On July 4, 1776, the Declaration of Independence was adopted. We celebrate America's birthday.",
    quick: true,
  },
  {
    id: "soc-g2-09",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "Holidays and symbols",
    prompt: "The Statue of Liberty stands for...",
    choices: ["Freedom", "Money", "Weather", "Sports"],
    answer: 0,
    explanation: "The Statue of Liberty is a symbol of freedom. It welcomed many people coming to America.",
    quick: true,
  },
  {
    id: "soc-g2-10",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1",
    skill: "Democracy",
    prompt: "In a democracy, people choose leaders by...",
    choices: ["Voting", "Guessing", "Fighting", "Shouting"],
    answer: 0,
    explanation: "In a democracy, citizens vote to choose their leaders.",
    quick: true,
  },
  {
    id: "soc-g2-11",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1",
    skill: "Democracy",
    prompt: "The leader of our country is the...",
    choices: ["President", "Mayor", "Governor", "Principal"],
    answer: 0,
    explanation: "The President leads the United States. A governor leads a state, and a mayor leads a city.",
    quick: true,
  },
  {
    id: "soc-g2-12",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1",
    skill: "Democracy",
    prompt: "The Constitution is the plan for our country's...",
    choices: ["Government", "Recess", "Weather", "Sports"],
    answer: 0,
    explanation: "The U.S. Constitution sets up our government and protects people's rights.",
    quick: true,
  },
  {
    id: "soc-g2-13",
    subject: "social",
    grade: "2",
    standard: "2.E.1.1",
    skill: "Scarcity",
    prompt: "When there is not enough of something, it is...",
    choices: ["Scarce", "Free", "Extra", "Heavy"],
    answer: 0,
    explanation: "Scarcity means there is not enough for everyone, so people must make choices.",
    quick: true,
  },
  {
    id: "soc-g2-14",
    subject: "social",
    grade: "2",
    standard: "2.E.1",
    skill: "Producers and consumers",
    prompt: "People who buy and use goods are...",
    choices: ["Consumers", "Producers", "Voters", "Mayors"],
    answer: 0,
    explanation: "Consumers buy and use goods and services. Producers make them.",
    quick: true,
  },
  {
    id: "soc-g2-15",
    subject: "social",
    grade: "2",
    standard: "2.E.1",
    skill: "Producers and consumers",
    prompt: "Money you earn from a job is...",
    choices: ["Income", "Scarcity", "A tax", "A loan"],
    answer: 0,
    explanation: "Income is money people earn by working.",
    quick: true,
  },
  {
    id: "soc-g2-16",
    subject: "social",
    grade: "2",
    standard: "2.E.1.1",
    skill: "Scarcity",
    prompt: "You have $1. You want juice and a cookie. Each costs $1. You must...",
    choices: ["Choose one", "Get both", "Get neither", "Pay $5"],
    answer: 0,
    explanation: "When money is scarce, you have to choose. Picking one means giving up the other.",
    quick: true,
  },
  {
    id: "soc-g2-17",
    subject: "social",
    grade: "2",
    standard: "2.B.1",
    skill: "Culture",
    prompt: "A group's food, music and language are its...",
    choices: ["Culture", "Weather", "Money", "Border"],
    answer: 0,
    explanation: "Culture is a group's way of life, like its food, music, language and holidays.",
    quick: true,
  },
  {
    id: "soc-g2-18",
    subject: "social",
    grade: "2",
    standard: "2.B.1",
    skill: "Immigration",
    prompt: "Many people moved to America from other...",
    choices: ["Countries", "Planets", "Oceans", "Moons"],
    answer: 0,
    explanation: "Immigrants come from other countries. They bring their cultures with them.",
    quick: true,
  },
];

export default questions;
