import type { Question } from "../../types";
// Grade 3 social studies — NC Standard Course of Study for Social Studies (adopted 2021). "Our Community and State": location, climate and NC regions, movement of goods
// (3.G.1.1, 3.G.1.2, 3.G.1.3, 3.G.1); local history and primary sources (3.H.1.1, 3.H.1); state and local government and leaders, citizenship (3.C&G.1.1, 3.C&G.1.2, 3.C&G.1);
// entrepreneurship, natural resources and NC products (3.E.1.1, 3.E.1.2, 3.E.1); community traditions and cultures (3.B.1.1, 3.B.1.2).
const questions: Question[] = [
  {
    id: "soc-g3-01",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "Which NC region has the highest land?",
    choices: ["Mountains", "Piedmont", "Coastal Plain", "Outer Banks"],
    answer: 0,
    explanation: "North Carolina has three regions. The Mountains in the west are the highest, with Mount Mitchell.",
    quick: true,
  },
  {
    id: "soc-g3-02",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "Raleigh, our state capital, is in which region?",
    choices: ["Piedmont", "Mountains", "Coastal Plain", "Outer Banks"],
    answer: 0,
    explanation: "The Piedmont is the middle region of NC, with rolling hills and big cities like Raleigh and Charlotte.",
    quick: true,
  },
  {
    id: "soc-g3-03",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "NC's long chain of barrier islands is the...",
    choices: ["Outer Banks", "Blue Ridge", "Piedmont", "Sandhills"],
    answer: 0,
    explanation: "The Outer Banks are thin islands along NC's coast in the Coastal Plain.",
    quick: true,
  },
  {
    id: "soc-g3-04",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    prompt: "Rivers helped early NC towns grow because boats could...",
    choices: ["Move goods", "Make rain", "Grow crops", "Stop wind"],
    answer: 0,
    explanation: "Geography affects movement. Rivers were early highways for carrying goods and people.",
    quick: true,
  },
  {
    id: "soc-g3-05",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    prompt: "Highways and railroads mostly help a community with...",
    choices: ["Trade", "Weather", "Recess", "Holidays"],
    answer: 0,
    explanation: "Roads and railroads move goods and people, which helps communities trade.",
    quick: true,
  },
  {
    id: "soc-g3-06",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "Map skills",
    passage:
      "A map of North Carolina has a scale that says: 1 inch = 10 miles. On the map, Pine Town and Oak City are 3 inches apart.",
    prompt: "What is the distance from Pine Town to Oak City?",
    choices: ["30 miles", "3 miles", "13 miles", "300 miles"],
    answer: 0,
    explanation: "Each inch stands for 10 miles, so 3 inches equals 3 × 10 = 30 miles.",
  },
  {
    id: "soc-g3-07",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Local history",
    prompt: "Two American Indian nations in NC today are the Lumbee and the...",
    choices: ["Cherokee", "Aztec", "Inca", "Maya"],
    answer: 0,
    explanation: "The Lumbee and the Eastern Band of Cherokee Indians are two of the American Indian tribes in NC.",
    quick: true,
  },
  {
    id: "soc-g3-08",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Timelines",
    prompt: "Our town began in 1850. Its school opened in 1900. Which came first?",
    choices: ["The town", "The school", "Same year", "Can't tell"],
    answer: 0,
    explanation: "1850 is earlier than 1900, so the town came first.",
    quick: true,
  },
  {
    id: "soc-g3-09",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Primary sources",
    prompt: "Which is a primary source about your town's past?",
    choices: ["An old photo", "A textbook", "A cartoon", "A video game"],
    answer: 0,
    explanation: "A primary source was made at the time, like a photo or letter. A textbook is written later.",
    quick: true,
  },
  {
    id: "soc-g3-10",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.2",
    skill: "Local government",
    prompt: "The leader of a city government is the...",
    choices: ["Mayor", "Governor", "President", "Judge"],
    answer: 0,
    explanation: "A mayor leads a city. A governor leads a state, and the President leads the nation.",
    quick: true,
  },
  {
    id: "soc-g3-11",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.2",
    skill: "State government",
    prompt: "The leader of North Carolina's government is the...",
    choices: ["Governor", "Mayor", "President", "Principal"],
    answer: 0,
    explanation: "The governor is the elected leader of North Carolina's executive branch.",
    quick: true,
  },
  {
    id: "soc-g3-12",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "Taxes",
    prompt: "Local taxes help pay for...",
    choices: ["Public schools", "Your toys", "Vacations", "Birthday cake"],
    answer: 0,
    explanation: "Taxes pay for public services like schools, parks, police and fire stations.",
    quick: true,
  },
  {
    id: "soc-g3-13",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "Citizenship",
    prompt: "A responsible citizen in a community...",
    choices: ["Follows laws", "Litters", "Ignores rules", "Wastes water"],
    answer: 0,
    explanation: "Responsible citizens follow laws, help others and take care of the community.",
    quick: true,
  },
  {
    id: "soc-g3-14",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "NC products",
    prompt: "Farmers in NC's Coastal Plain grow a lot of...",
    choices: ["Sweet potatoes", "Coffee", "Bananas", "Pineapples"],
    answer: 0,
    explanation: "North Carolina grows more sweet potatoes than any other state, mostly in the east.",
    quick: true,
  },
  {
    id: "soc-g3-15",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "Specialization",
    prompt: "A bakery that only makes bread is...",
    choices: ["Specializing", "Saving", "Voting", "Borrowing"],
    answer: 0,
    explanation: "Specialization means focusing on making one kind of good or service.",
    quick: true,
  },
  {
    id: "soc-g3-16",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "Opportunity cost",
    passage:
      "Maya has $5. She wants a book and a kite, and each costs $5. She thinks about it and buys the book.",
    prompt: "What is Maya's opportunity cost?",
    choices: ["The kite", "The book", "The $5", "The store"],
    answer: 0,
    explanation: "Opportunity cost is the next-best choice you give up. Maya gave up the kite.",
  },
  {
    id: "soc-g3-17",
    subject: "social",
    grade: "3",
    standard: "3.B.1.1",
    skill: "Traditions",
    prompt: "Festivals, foods and songs passed down in a community are...",
    choices: ["Traditions", "Laws", "Landforms", "Taxes"],
    answer: 0,
    explanation: "Traditions are customs passed from older people to younger people. They help give a community its culture.",
    quick: true,
  },
  {
    id: "soc-g3-18",
    subject: "social",
    grade: "3",
    standard: "3.B.1.1",
    skill: "Traditions",
    prompt: "A powwow is a celebration held by...",
    choices: ["Native nations", "City councils", "Sports teams", "Banks"],
    answer: 0,
    explanation: "Powwows bring American Indian people together for dancing, drumming, food and honoring traditions.",
    quick: true,
  },
  {
    id: "soc-g3-19",
    subject: "social",
    grade: "3",
    standard: "3.G.1.1",
    skill: "NC location",
    prompt: "The highest mountain east of the Mississippi River, in NC, is Mount...",
    choices: ["Mitchell", "Everest", "Rushmore", "Washington"],
    answer: 0,
    explanation: "Mount Mitchell, in Yancey County, is 6,684 feet tall, the highest peak in the eastern United States.",
    quick: true,
  },
  {
    id: "soc-g3-20",
    subject: "social",
    grade: "3",
    standard: "3.G.1.1",
    skill: "NC location",
    prompt: "Which state is North Carolina's neighbor to the north?",
    choices: ["Virginia", "Georgia", "Florida", "Alabama"],
    answer: 0,
    explanation: "Virginia is north of NC. Tennessee is west, and South Carolina and Georgia are south.",
    quick: true,
  },
  {
    id: "soc-g3-21",
    subject: "social",
    grade: "3",
    standard: "3.G.1.1",
    skill: "NC location",
    prompt: "Which state borders NC on the west?",
    choices: ["Tennessee", "Virginia", "Kentucky", "Texas"],
    answer: 0,
    explanation: "Tennessee lies west of NC, across the Great Smoky Mountains.",
    quick: true,
  },
  {
    id: "soc-g3-22",
    subject: "social",
    grade: "3",
    standard: "3.G.1.1",
    skill: "NC regions",
    prompt: "Asheville is a city in which NC region?",
    choices: ["Mountains", "Piedmont", "Coastal Plain", "Outer Banks"],
    answer: 0,
    explanation: "Asheville sits in the Blue Ridge Mountains of western NC.",
    quick: true,
  },
  {
    id: "soc-g3-23",
    subject: "social",
    grade: "3",
    standard: "3.G.1.2",
    skill: "Climate",
    prompt: "Why do NC's mountain towns get more snow than towns on the coast?",
    choices: ["Higher land", "Saltwater", "More beaches", "Flat land"],
    answer: 0,
    explanation: "Higher places are colder. NC's mountains get more snow than the warm, low coast.",
    quick: true,
  },
  {
    id: "soc-g3-24",
    subject: "social",
    grade: "3",
    standard: "3.G.1.2",
    skill: "Climate",
    prompt: "People on NC's Outer Banks must be most ready for...",
    choices: ["Hurricanes", "Blizzards", "Earthquakes", "Volcanoes"],
    answer: 0,
    explanation: "Hurricanes form over warm ocean water and often hit NC's coast in late summer and fall.",
    quick: true,
  },
  {
    id: "soc-g3-25",
    subject: "social",
    grade: "3",
    standard: "3.G.1.2",
    skill: "Physical characteristics",
    prompt: "The Coastal Plain's flat land and rich soil are good for...",
    choices: ["Farming", "Skiing", "Rock climbing", "Glaciers"],
    answer: 0,
    explanation: "Flat land and good soil make eastern NC a big farming area.",
    quick: true,
  },
  {
    id: "soc-g3-26",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    prompt: "The Port of Wilmington helps NC ship goods by...",
    choices: ["Sea", "Air", "Pipeline", "Bicycle"],
    answer: 0,
    explanation: "Ships at the Port of Wilmington carry goods to and from places around the world.",
    quick: true,
  },
  {
    id: "soc-g3-27",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of ideas",
    prompt: "The internet lets ideas move from place to place...",
    choices: ["Quickly", "Slowly", "Never", "Only by mail"],
    answer: 0,
    explanation: "Ideas once traveled by letter or by people. Now the internet spreads them in seconds.",
    quick: true,
  },
  {
    id: "soc-g3-28",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    passage:
      "Map of a town: Highway 1 runs north and south through the middle of town. The river runs east and west along the south edge. The new factory is where Highway 1 crosses the river.",
    prompt: "Why might the factory be built there?",
    choices: ["It can ship goods by road and river", "It is far from every road", "It is the coldest spot", "The river makes it hard to reach"],
    answer: 0,
    explanation: "Factories are often built where roads, rivers or railroads meet so goods can move easily.",
  },
  {
    id: "soc-g3-29",
    subject: "social",
    grade: "3",
    standard: "3.H.1.1",
    skill: "Local history",
    prompt: "Which American Indian tribe, based in Robeson County, is the largest in NC?",
    choices: ["Lumbee", "Cherokee", "Haliwa-Saponi", "Catawba"],
    answer: 0,
    explanation: "The Lumbee Tribe is centered in Robeson County and is the largest tribe in North Carolina.",
    quick: true,
  },
  {
    id: "soc-g3-30",
    subject: "social",
    grade: "3",
    standard: "3.H.1.1",
    skill: "Local history",
    prompt: "Civil rights leader Ella Baker grew up in which state?",
    choices: ["North Carolina", "Alaska", "Maine", "Hawaii"],
    answer: 0,
    explanation: "Ella Baker grew up in Littleton, NC, studied at Shaw University in Raleigh and helped young people lead the civil rights movement.",
    quick: true,
  },
  {
    id: "soc-g3-31",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Learning about the past",
    prompt: "A place that keeps old objects so people can learn about the past is a...",
    choices: ["Museum", "Gas station", "Gym", "Mall"],
    answer: 0,
    explanation: "Museums collect and show objects like tools, clothes and photos from long ago.",
    quick: true,
  },
  {
    id: "soc-g3-32",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Primary sources",
    prompt: "A person who saw an event happen and tells about it is an...",
    choices: ["Eyewitness", "Editor", "Actor", "Inventor"],
    answer: 0,
    explanation: "An eyewitness saw the event. Their account is a primary source.",
    quick: true,
  },
  {
    id: "soc-g3-33",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Timelines",
    prompt: "How many years are in a decade?",
    choices: ["10", "100", "12", "1,000"],
    answer: 0,
    explanation: "A decade is 10 years. A century is 100 years.",
    quick: true,
  },
  {
    id: "soc-g3-34",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Primary sources",
    passage:
      "Imagine a letter written by a girl in 1918: 'Dear Aunt May, School is closed because so many people are sick with the flu. Mother makes us wear masks when we go to the store.'",
    prompt: "What can we learn from this letter?",
    choices: ["Sickness changed daily life in 1918", "Schools never closed long ago", "Masks were first made in 2020", "The girl liked being sick"],
    answer: 0,
    explanation: "In 1918 a flu pandemic closed many schools, and some towns asked people to wear masks.",
  },
  {
    id: "soc-g3-35",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.1",
    skill: "State government",
    prompt: "Laws for a whole state are made by the state...",
    choices: ["Legislature", "Mayor", "School board", "Fire chief"],
    answer: 0,
    explanation: "A state legislature makes state laws. NC's legislature is called the General Assembly.",
    quick: true,
  },
  {
    id: "soc-g3-36",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.1",
    skill: "Local government",
    prompt: "A city council makes rules for a...",
    choices: ["City", "State", "Country", "Planet"],
    answer: 0,
    explanation: "A city council is the law-making group for a city or town.",
    quick: true,
  },
  {
    id: "soc-g3-37",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.1",
    skill: "Local government",
    prompt: "North Carolina is divided into how many counties?",
    choices: ["100", "50", "13", "200"],
    answer: 0,
    explanation: "NC has 100 counties. Each county has its own local government.",
    quick: true,
  },
  {
    id: "soc-g3-38",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.2",
    skill: "Leaders",
    prompt: "An NC county's top elected law officer is the...",
    choices: ["Sheriff", "Mayor", "Governor", "Senator"],
    answer: 0,
    explanation: "Each NC county elects a sheriff to enforce laws and run the county jail.",
    quick: true,
  },
  {
    id: "soc-g3-39",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.2",
    skill: "Leaders",
    prompt: "Which leader signs or vetoes bills for NC?",
    choices: ["Governor", "Mayor", "Sheriff", "Judge"],
    answer: 0,
    explanation: "The governor can sign a bill into law or veto it.",
    quick: true,
  },
  {
    id: "soc-g3-40",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1.2",
    skill: "Local government",
    passage:
      "Our town wants a new park. The town council votes to spend money on it. The mayor signs the plan. Workers from the parks department build the park.",
    prompt: "Who voted to spend the money?",
    choices: ["The town council", "The mayor", "The parks department", "The governor"],
    answer: 0,
    explanation: "The town council decides how to spend town money. Other leaders carry out the plan.",
  },
  {
    id: "soc-g3-41",
    subject: "social",
    grade: "3",
    standard: "3.E.1.1",
    skill: "Entrepreneurship",
    prompt: "A person who starts a new business is an...",
    choices: ["Entrepreneur", "Employee", "Consumer", "Voter"],
    answer: 0,
    explanation: "Entrepreneurs take a risk to start businesses. Their businesses can make jobs for others.",
    quick: true,
  },
  {
    id: "soc-g3-42",
    subject: "social",
    grade: "3",
    standard: "3.E.1.1",
    skill: "Entrepreneurship",
    prompt: "How can a new bakery help a town?",
    choices: ["Creates jobs", "Floods roads", "Ends school", "Closes parks"],
    answer: 0,
    explanation: "New businesses hire workers and sell goods, which helps the local economy.",
    quick: true,
  },
  {
    id: "soc-g3-43",
    subject: "social",
    grade: "3",
    standard: "3.E.1.2",
    skill: "Natural resources",
    prompt: "Which product comes from NC's coastal waters?",
    choices: ["Shrimp", "Apples", "Fraser firs", "Cotton"],
    answer: 0,
    explanation: "Fishing boats on NC's coast catch shrimp, crabs and fish.",
    quick: true,
  },
  {
    id: "soc-g3-44",
    subject: "social",
    grade: "3",
    standard: "3.E.1.2",
    skill: "Natural resources",
    prompt: "NC's mountains are famous for growing which holiday trees?",
    choices: ["Fraser firs", "Palm trees", "Orange trees", "Cactus"],
    answer: 0,
    explanation: "The cool mountain climate is perfect for Fraser fir Christmas trees.",
    quick: true,
  },
  {
    id: "soc-g3-45",
    subject: "social",
    grade: "3",
    standard: "3.E.1.2",
    skill: "NC products",
    passage:
      "Chart – North Carolina's rank among U.S. states: Sweet potatoes: 1st. Tobacco: 1st. Christmas trees: 2nd.",
    prompt: "NC is second in the nation for which product?",
    choices: ["Christmas trees", "Sweet potatoes", "Tobacco", "Cotton"],
    answer: 0,
    explanation: "The chart shows NC ranks second for Christmas trees (Oregon is first).",
  },
  {
    id: "soc-g3-46",
    subject: "social",
    grade: "3",
    standard: "3.B.1.1",
    skill: "Traditions",
    prompt: "The Lumbee Homecoming festival is held each summer in...",
    choices: ["Pembroke", "Boone", "Asheville", "Raleigh"],
    answer: 0,
    explanation: "Lumbee Homecoming in Pembroke brings people together for a powwow, music, food and a parade.",
    quick: true,
  },
  {
    id: "soc-g3-47",
    subject: "social",
    grade: "3",
    standard: "3.B.1.2",
    skill: "Cultures",
    prompt: "Why do groups in a community have different holidays?",
    choices: ["Cultures differ", "The weather", "Laws say so", "Maps differ"],
    answer: 0,
    explanation: "Groups have different beliefs and traditions, so they celebrate different holidays.",
  },
  {
    id: "soc-g3-48",
    subject: "social",
    grade: "3",
    standard: "3.B.1.2",
    skill: "Cultures",
    passage:
      "At a school culture night, Kai's family shares Hmong embroidery, Priya's family shares Indian dance and Jose's family shares Mexican food.",
    prompt: "What is the best conclusion?",
    choices: ["The community includes many cultures", "Everyone has the same traditions", "Only food is part of culture", "Culture night shows one culture"],
    answer: 0,
    explanation: "Different families shared different traditions, so the community has many cultures.",
  },
];

export default questions;
