import type { Question } from "../../types";
// Grade 5 social studies — NC Standard Course of Study for Social Studies (adopted 2021). The United States: regions, migration and technology (5.G.1.1–5.G.1.4);
// three branches and checks and balances (5.C&G.1.1–1.2); rights and civic participation (5.C&G.2.1–2.2); identity and the arts (5.B.1.1); revolution, conflict, innovators,
// primary sources (5.H.1.1, 5.H.1.3–1.5); economic growth and decline, budgeting and borrowing (5.E.1.1, 5.E.1.3, 5.E.2.2, 5.E.2).
const questions: Question[] = [
  {
    id: "soc-g5-01",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "Which U.S. region is known for farms growing corn and wheat?",
    choices: ["Midwest", "Northeast", "Southwest", "West Coast"],
    answer: 0,
    explanation: "The flat land and rich soil of the Midwest make it a leading region for corn and wheat.",
    quick: true,
  },
  {
    id: "soc-g5-02",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "Which river did early farmers use to ship crops to New Orleans?",
    choices: ["Mississippi", "Hudson", "Colorado", "Rio Grande"],
    answer: 0,
    explanation: "The Mississippi River flows south to New Orleans, so farmers floated crops downriver to market.",
    quick: true,
  },
  {
    id: "soc-g5-03",
    subject: "social",
    grade: "5",
    standard: "5.G.1.2",
    skill: "Forced migration",
    prompt: "The Trail of Tears was the forced removal of...",
    choices: ["The Cherokee", "Pilgrims", "Gold miners", "Irish workers"],
    answer: 0,
    explanation: "In 1838–39 the U.S. forced thousands of Cherokee west to Indian Territory. Thousands died on the way.",
    quick: true,
  },
  {
    id: "soc-g5-04",
    subject: "social",
    grade: "5",
    standard: "5.G.1.3",
    skill: "Technology and geography",
    prompt: "What was completed in 1869 to link the East and West by rail?",
    choices: ["Railroad", "Interstate", "Airport", "Canal"],
    answer: 0,
    explanation: "The transcontinental railroad cut a months-long trip to about a week.",
    quick: true,
  },
  {
    id: "soc-g5-05",
    subject: "social",
    grade: "5",
    standard: "5.G.1.4",
    skill: "Immigration",
    prompt: "Millions of immigrants in the early 1900s first arrived at...",
    choices: ["Ellis Island", "Hawaii", "Alaska", "Pikes Peak"],
    answer: 0,
    explanation: "Ellis Island in New York Harbor processed about 12 million immigrants from 1892 to 1954.",
    quick: true,
  },
  {
    id: "soc-g5-06",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "Which branch makes federal laws?",
    choices: ["Congress", "President", "Supreme Court", "Governor"],
    answer: 0,
    explanation: "Congress is the legislative branch. It writes and passes laws.",
    quick: true,
  },
  {
    id: "soc-g5-07",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "Which branch decides if laws follow the Constitution?",
    choices: ["Judicial", "Legislative", "Executive", "Military"],
    answer: 0,
    explanation: "The judicial branch, led by the Supreme Court, interprets laws.",
    quick: true,
  },
  {
    id: "soc-g5-08",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.2",
    skill: "Checks and balances",
    prompt: "Checks and balances stop one branch from having...",
    choices: ["Too much power", "A budget", "Any members", "A building"],
    answer: 0,
    explanation: "Each branch can limit the others, so no one branch becomes too powerful.",
    quick: true,
  },
  {
    id: "soc-g5-09",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.1",
    skill: "Voting rights",
    prompt: "The 19th Amendment (1920) gave the right to vote to...",
    choices: ["Women", "18-year-olds", "Landowners", "Soldiers"],
    answer: 0,
    explanation: "After years of advocacy by suffragists, the 19th Amendment protected women's right to vote.",
    quick: true,
  },
  {
    id: "soc-g5-10",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.2",
    skill: "Bill of Rights",
    prompt: "Freedom of speech is protected by the...",
    choices: ["1st Amendment", "2nd Amendment", "10th Amendment", "19th Amendment"],
    answer: 0,
    explanation: "The 1st Amendment protects freedom of speech, religion, press, assembly and petition.",
    quick: true,
  },
  {
    id: "soc-g5-11",
    subject: "social",
    grade: "5",
    standard: "5.H.1.3",
    skill: "American Revolution",
    prompt: "The American Revolution was a fight for independence from...",
    choices: ["Great Britain", "France", "Spain", "Mexico"],
    answer: 0,
    explanation: "The 13 colonies declared independence from Great Britain in 1776 and won the war in 1783.",
    quick: true,
  },
  {
    id: "soc-g5-12",
    subject: "social",
    grade: "5",
    standard: "5.H.1.4",
    skill: "Major conflicts",
    prompt: "The U.S. Civil War was fought from...",
    choices: ["1861–1865", "1776–1783", "1812–1815", "1917–1918"],
    answer: 0,
    explanation: "The Civil War between the Union and the Confederacy lasted from 1861 to 1865.",
    quick: true,
  },
  {
    id: "soc-g5-13",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    prompt: "George Washington Carver found hundreds of uses for...",
    choices: ["Peanuts", "Oil", "Steel", "Rubber"],
    answer: 0,
    explanation: "Carver, a Black scientist, taught Southern farmers to rotate cotton with peanuts to restore worn-out soil.",
    quick: true,
  },
  {
    id: "soc-g5-14",
    subject: "social",
    grade: "5",
    standard: "5.B.1.1",
    skill: "American arts",
    prompt: "Jazz music first grew in which city?",
    choices: ["New Orleans", "Boston", "Seattle", "Denver"],
    answer: 0,
    explanation: "Jazz was created by African American musicians in New Orleans in the early 1900s.",
    quick: true,
  },
  {
    id: "soc-g5-15",
    subject: "social",
    grade: "5",
    standard: "5.E.1.3",
    skill: "Division of labor",
    prompt: "Henry Ford's moving assembly line made cars...",
    choices: ["Cheaper", "Slower", "Rarer", "Heavier"],
    answer: 0,
    explanation: "Each worker did one step, so cars were built faster and cost less.",
    quick: true,
  },
  {
    id: "soc-g5-16",
    subject: "social",
    grade: "5",
    standard: "5.E.1.1",
    skill: "Economic decline",
    prompt: "The Great Depression began after the stock market crash of...",
    choices: ["1929", "1941", "1865", "1776"],
    answer: 0,
    explanation: "The 1929 crash helped start the Great Depression, a time of high unemployment.",
    quick: true,
  },
  {
    id: "soc-g5-17",
    subject: "social",
    grade: "5",
    standard: "5.E.2.2",
    skill: "Budgeting",
    passage:
      "Jada earns $20 a week walking dogs. Her budget says to save 25% of what she earns and spend the rest.",
    prompt: "How much will Jada save each week?",
    choices: ["$5", "$15", "$20", "$25"],
    answer: 0,
    explanation: "25% is one quarter. One quarter of $20 is $5.",
  },
  {
    id: "soc-g5-18",
    subject: "social",
    grade: "5",
    standard: "5.H.1.5",
    skill: "Primary sources",
    passage:
      "A student is researching the American Revolution (1775–1783) and finds four sources in the library.",
    prompt: "Which of these is a primary source about the Revolution?",
    choices: ["A letter written by a soldier in 1777", "A 2020 website about the war", "A textbook chapter from 1990", "A movie made in 2000"],
    answer: 0,
    explanation: "A primary source was created by someone who lived through the event. The others were made much later.",
  },
  {
    id: "soc-g5-19",
    subject: "social",
    grade: "5",
    standard: "5.H.1.3",
    skill: "American Revolution",
    prompt: "The first shots of the Revolution were fired in 1775 at Lexington and...",
    choices: ["Concord", "Yorktown", "Saratoga", "Trenton"],
    answer: 0,
    explanation: "Fighting at Lexington and Concord, Massachusetts, on April 19, 1775, began the war.",
    quick: true,
  },
  {
    id: "soc-g5-20",
    subject: "social",
    grade: "5",
    standard: "5.H.1.3",
    skill: "American Revolution",
    prompt: "The British army surrendered at Yorktown in...",
    choices: ["1781", "1776", "1812", "1865"],
    answer: 0,
    explanation: "Washington and his French allies trapped Cornwallis at Yorktown in October 1781. The peace treaty followed in 1783.",
    quick: true,
  },
  {
    id: "soc-g5-21",
    subject: "social",
    grade: "5",
    standard: "5.H.1.3",
    skill: "American Revolution",
    prompt: "Who wrote most of the Declaration of Independence?",
    choices: ["Jefferson", "Washington", "Franklin", "Hamilton"],
    answer: 0,
    explanation: "Thomas Jefferson wrote the first draft. Franklin, Adams and Congress made changes.",
    quick: true,
  },
  {
    id: "soc-g5-22",
    subject: "social",
    grade: "5",
    standard: "5.H.1.4",
    skill: "Major conflicts",
    prompt: "The War of 1812 was fought between the United States and...",
    choices: ["Great Britain", "France", "Spain", "Mexico"],
    answer: 0,
    explanation: "The U.S. fought Britain over trade, sailors' rights and land from 1812 to 1815.",
    quick: true,
  },
  {
    id: "soc-g5-23",
    subject: "social",
    grade: "5",
    standard: "5.H.1.4",
    skill: "Major conflicts",
    prompt: "In 1865, Lee surrendered to Grant at...",
    choices: ["Appomattox", "Gettysburg", "Yorktown", "Fort Sumter"],
    answer: 0,
    explanation: "Lee's surrender at Appomattox Court House, Virginia, on April 9, 1865, led to the end of the Civil War.",
    quick: true,
  },
  {
    id: "soc-g5-24",
    subject: "social",
    grade: "5",
    standard: "5.H.1.4",
    skill: "Major conflicts",
    prompt: "Which war did the U.S. enter after the 1941 attack on Pearl Harbor?",
    choices: ["World War II", "World War I", "Civil War", "Korean War"],
    answer: 0,
    explanation: "Japan attacked Pearl Harbor on December 7, 1941, and the U.S. entered World War II.",
    quick: true,
  },
  {
    id: "soc-g5-25",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    prompt: "Alexander Graham ___ received a patent for the telephone in 1876.",
    choices: ["Bell", "Edison", "Ford", "Morse"],
    answer: 0,
    explanation: "Bell's telephone carried voices over wires. Samuel Morse had invented the telegraph code earlier.",
    quick: true,
  },
  {
    id: "soc-g5-26",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    prompt: "Thomas Edison is famous for developing a long-lasting...",
    choices: ["Light bulb", "Airplane", "Telephone", "Car"],
    answer: 0,
    explanation: "Edison's team made a practical electric light bulb in 1879 and built power systems to light cities.",
    quick: true,
  },
  {
    id: "soc-g5-27",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    prompt: "Amelia ___ was the first woman to fly solo across the Atlantic.",
    choices: ["Earhart", "Ride", "Tubman", "Keller"],
    answer: 0,
    explanation: "Amelia Earhart flew alone across the Atlantic in 1932. Sally Ride later became the first American woman in space.",
    quick: true,
  },
  {
    id: "soc-g5-28",
    subject: "social",
    grade: "5",
    standard: "5.H.1.1",
    skill: "Innovators",
    passage:
      "Katherine Johnson was a Black mathematician at NASA. In 1962, before John Glenn orbited Earth, he asked that she check the electronic computer's numbers for his flight by hand.",
    prompt: "What does this show about Johnson?",
    choices: ["Astronauts trusted her careful math", "She was the first astronaut", "She built the first computer", "She was in charge of NASA"],
    answer: 0,
    explanation: "Katherine Johnson's calculations helped NASA send astronauts safely into orbit and to the Moon.",
  },
  {
    id: "soc-g5-29",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "Which U.S. region includes Arizona and New Mexico?",
    choices: ["Southwest", "Northeast", "Midwest", "Southeast"],
    answer: 0,
    explanation: "The Southwest has deserts, canyons and a strong mix of American Indian, Mexican and Anglo cultures.",
    quick: true,
  },
  {
    id: "soc-g5-30",
    subject: "social",
    grade: "5",
    standard: "5.G.1.1",
    skill: "U.S. regions",
    prompt: "The long, old mountain range in the eastern U.S. is the...",
    choices: ["Appalachians", "Rockies", "Andes", "Alps"],
    answer: 0,
    explanation: "The Appalachian Mountains run from Alabama to Canada, including NC's Blue Ridge and Great Smokies.",
    quick: true,
  },
  {
    id: "soc-g5-31",
    subject: "social",
    grade: "5",
    standard: "5.G.1.2",
    skill: "Westward movement",
    prompt: "Pioneers traveled west in covered wagons on the ___ Trail.",
    choices: ["Oregon", "Silk", "Appalachian", "Freedom"],
    answer: 0,
    explanation: "About 400,000 people used the Oregon Trail between the 1840s and 1860s.",
    quick: true,
  },
  {
    id: "soc-g5-32",
    subject: "social",
    grade: "5",
    standard: "5.G.1.2",
    skill: "Westward movement",
    prompt: "The 1849 rush of people to California began with the discovery of...",
    choices: ["Gold", "Oil", "Silver", "Coal"],
    answer: 0,
    explanation: "Gold found at Sutter's Mill in 1848 drew the 'forty-niners' to California.",
    quick: true,
  },
  {
    id: "soc-g5-33",
    subject: "social",
    grade: "5",
    standard: "5.G.1.2",
    skill: "Push and pull factors",
    passage:
      "In the 1840s, a plant disease destroyed Ireland's potato crops, and about a million people died of hunger and disease. More than a million Irish people sailed to American cities, where they could find work.",
    prompt: "Which is a push factor in this passage?",
    choices: ["The potato crop failure in Ireland", "Jobs in American cities", "Ships sailing to America", "Family members already in America"],
    answer: 0,
    explanation: "A push factor drives people away from home. The famine pushed people out of Ireland.",
  },
  {
    id: "soc-g5-34",
    subject: "social",
    grade: "5",
    standard: "5.G.1.3",
    skill: "Technology and movement",
    prompt: "The Erie Canal (1825) linked the Great Lakes to the...",
    choices: ["Hudson River", "Mississippi", "Gulf of Mexico", "Pacific"],
    answer: 0,
    explanation: "The canal connected Lake Erie to the Hudson River, so goods could float to New York City.",
    quick: true,
  },
  {
    id: "soc-g5-35",
    subject: "social",
    grade: "5",
    standard: "5.G.1.3",
    skill: "Technology and change",
    prompt: "Eli Whitney's 1793 cotton gin made it faster to...",
    choices: ["Remove seeds", "Plant seeds", "Sew shirts", "Dye cloth"],
    answer: 0,
    explanation: "The gin pulled seeds from cotton. Cotton farming grew, and sadly slavery spread with it.",
    quick: true,
  },
  {
    id: "soc-g5-36",
    subject: "social",
    grade: "5",
    standard: "5.G.1.3",
    skill: "Technology and movement",
    prompt: "The interstate highway system began in 1956 under President...",
    choices: ["Eisenhower", "Lincoln", "Washington", "Jefferson"],
    answer: 0,
    explanation: "Eisenhower signed the law that built thousands of miles of interstate highways.",
    quick: true,
  },
  {
    id: "soc-g5-37",
    subject: "social",
    grade: "5",
    standard: "5.G.1.4",
    skill: "Immigration",
    prompt: "Angel Island in San Francisco Bay processed many immigrants from...",
    choices: ["Asia", "Europe", "Canada", "Africa"],
    answer: 0,
    explanation: "From 1910 to 1940, Angel Island handled many immigrants from China, Japan and other Pacific nations.",
    quick: true,
  },
  {
    id: "soc-g5-38",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "The head of the executive branch is the...",
    choices: ["President", "Speaker", "Chief Justice", "Senator"],
    answer: 0,
    explanation: "The President leads the executive branch, which carries out laws.",
    quick: true,
  },
  {
    id: "soc-g5-39",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.1",
    skill: "Three branches",
    prompt: "Congress is made up of the Senate and the...",
    choices: ["House", "Cabinet", "Court", "Army"],
    answer: 0,
    explanation: "Congress has two parts: the Senate and the House of Representatives.",
    quick: true,
  },
  {
    id: "soc-g5-40",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.2",
    skill: "Checks and balances",
    prompt: "The President picks Supreme Court justices, but who must approve them?",
    choices: ["The Senate", "The House", "Governors", "Voters"],
    answer: 0,
    explanation: "The Senate confirms judges. This check keeps the President from choosing alone.",
    quick: true,
  },
  {
    id: "soc-g5-41",
    subject: "social",
    grade: "5",
    standard: "5.C&G.1.2",
    skill: "Checks and balances",
    passage:
      "Congress passes a bill. The President vetoes it. Then two-thirds of the House and two-thirds of the Senate vote to pass it again.",
    prompt: "What happens to the bill?",
    choices: ["It becomes law", "It is thrown out", "The Supreme Court must sign it", "The President must approve it again"],
    answer: 0,
    explanation: "A two-thirds vote in both houses overrides a veto. This is a check on the President.",
  },
  {
    id: "soc-g5-42",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.1",
    skill: "Voting rights",
    prompt: "The 15th Amendment (1870) said voting rights can't be denied because of...",
    choices: ["Race", "Age", "Income", "Height"],
    answer: 0,
    explanation: "The 15th Amendment protected the votes of Black men. Later, unfair laws blocked many of them until the 1960s.",
    quick: true,
  },
  {
    id: "soc-g5-43",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.2",
    skill: "Bill of Rights",
    prompt: "Which amendment protects the right to a speedy, public trial?",
    choices: ["6th Amendment", "1st Amendment", "2nd Amendment", "10th Amendment"],
    answer: 0,
    explanation: "The 6th Amendment protects the rights of people accused of crimes, including a jury trial and a lawyer.",
    quick: true,
  },
  {
    id: "soc-g5-44",
    subject: "social",
    grade: "5",
    standard: "5.C&G.2.1",
    skill: "Civic participation",
    prompt: "A written request to government signed by many people is a...",
    choices: ["Petition", "Veto", "Treaty", "Tax"],
    answer: 0,
    explanation: "The 1st Amendment protects the right to petition the government.",
    quick: true,
  },
  {
    id: "soc-g5-45",
    subject: "social",
    grade: "5",
    standard: "5.B.1.1",
    skill: "American arts",
    prompt: "Langston ___ was a leading poet of the Harlem Renaissance.",
    choices: ["Hughes", "Twain", "Frost", "Poe"],
    answer: 0,
    explanation: "Langston Hughes wrote poems about African American life, like 'I, Too.'",
    quick: true,
  },
  {
    id: "soc-g5-46",
    subject: "social",
    grade: "5",
    standard: "5.E.1.1",
    skill: "Economic decline",
    prompt: "A time when the economy shrinks and many people lose jobs is a...",
    choices: ["Recession", "Boom", "Holiday", "Census"],
    answer: 0,
    explanation: "In a recession, businesses sell less and many workers lose jobs. A very long, deep one is a depression.",
    quick: true,
  },
  {
    id: "soc-g5-47",
    subject: "social",
    grade: "5",
    standard: "5.E.2.2",
    skill: "Budgeting",
    passage:
      "Leo earns $30 a month doing chores. He spends $12 on snacks and $8 on a game. He saves the rest.",
    prompt: "How much does Leo save each month?",
    choices: ["$10", "$20", "$18", "$12"],
    answer: 0,
    explanation: "$30 − $12 − $8 = $10 left to save.",
  },
  {
    id: "soc-g5-48",
    subject: "social",
    grade: "5",
    standard: "5.E.2",
    skill: "Borrowing",
    prompt: "Money you borrow and must pay back, usually with interest, is a...",
    choices: ["Loan", "Gift", "Tax", "Allowance"],
    answer: 0,
    explanation: "A loan must be paid back. Interest is the extra cost of borrowing.",
    quick: true,
  },
];

export default questions;
