import type { Question } from "../../types";
// Grade 1 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Self, family and community: past and present, timelines (1.H.1);
// map keys, directions, landforms and water (1.G.1); laws, leaders and voting (1.C&G.1); goods, services, saving and trade (1.E.1); traditions and languages (1.B.1).
const questions: Question[] = [
  {
    id: "soc-g1-01",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map skills",
    prompt: "The part of a map that explains its symbols is the...",
    choices: ["Map key", "Title", "Compass", "Border"],
    answer: 0,
    explanation: "The map key (legend) tells what each symbol on the map means.",
    quick: true,
  },
  {
    id: "soc-g1-02",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map skills",
    prompt: "A compass rose on a map shows...",
    choices: ["Directions", "Weather", "Time", "Money"],
    answer: 0,
    explanation: "A compass rose shows north, south, east and west.",
    quick: true,
  },
  {
    id: "soc-g1-03",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Map skills",
    prompt: "Which direction is opposite of north?",
    choices: ["South", "East", "West", "Up"],
    answer: 0,
    explanation: "North and south are opposites. East and west are opposites too.",
    quick: true,
  },
  {
    id: "soc-g1-04",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Landforms and water",
    prompt: "A very tall, rocky landform is a...",
    choices: ["Mountain", "Lake", "Valley", "Plain"],
    answer: 0,
    explanation: "Mountains are the highest landforms. North Carolina has mountains in the west.",
    quick: true,
  },
  {
    id: "soc-g1-05",
    subject: "social",
    grade: "1",
    standard: "1.G.1",
    skill: "Landforms and water",
    prompt: "Which is a body of water?",
    choices: ["Ocean", "Hill", "Desert", "Forest"],
    answer: 0,
    explanation: "Oceans, lakes and rivers are bodies of water.",
    quick: true,
  },
  {
    id: "soc-g1-06",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "A timeline shows events in...",
    choices: ["Order", "Color", "Size", "Secret"],
    answer: 0,
    explanation: "A timeline puts events in the order they happened, from first to last.",
    quick: true,
  },
  {
    id: "soc-g1-07",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "Before cars, many people traveled by...",
    choices: ["Horse", "Airplane", "Rocket", "Subway"],
    answer: 0,
    explanation: "Long ago, people rode horses or used wagons. Transportation has changed over time.",
    quick: true,
  },
  {
    id: "soc-g1-08",
    subject: "social",
    grade: "1",
    standard: "1.H.1",
    skill: "Past and present",
    prompt: "A photo taken 100 years ago shows the...",
    choices: ["Past", "Future", "Present", "Next week"],
    answer: 0,
    explanation: "Old photos show us what life was like in the past.",
    quick: true,
  },
  {
    id: "soc-g1-09",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Laws and leaders",
    prompt: "Laws are rules made for a...",
    choices: ["Community", "Toy box", "Board game", "Recess"],
    answer: 0,
    explanation: "Laws are rules for everyone in a community, state or country.",
    quick: true,
  },
  {
    id: "soc-g1-10",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Laws and leaders",
    prompt: "Who leads a town or city?",
    choices: ["A mayor", "A coach", "A doctor", "A chef"],
    answer: 0,
    explanation: "A mayor is a leader of a town or city government.",
    quick: true,
  },
  {
    id: "soc-g1-11",
    subject: "social",
    grade: "1",
    standard: "1.C&G.1",
    skill: "Voting",
    prompt: "Voting is a way to...",
    choices: ["Make a choice", "Get a snack", "Take a nap", "Build a road"],
    answer: 0,
    explanation: "When we vote, each person gets to help make a group choice.",
    quick: true,
  },
  {
    id: "soc-g1-12",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Goods and services",
    prompt: "Something you can buy and hold is a...",
    choices: ["Good", "Service", "Law", "Map"],
    answer: 0,
    explanation: "Goods are things you can touch, like apples and shoes.",
    quick: true,
  },
  {
    id: "soc-g1-13",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Goods and services",
    prompt: "A haircut is a...",
    choices: ["Service", "Good", "Need", "Tax"],
    answer: 0,
    explanation: "A service is work someone does for you, like cutting hair.",
    quick: true,
  },
  {
    id: "soc-g1-14",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Saving",
    prompt: "Keeping money to use later is...",
    choices: ["Saving", "Spending", "Borrowing", "Losing"],
    answer: 0,
    explanation: "When you save, you keep money now so you can use it later.",
    quick: true,
  },
  {
    id: "soc-g1-15",
    subject: "social",
    grade: "1",
    standard: "1.E.1",
    skill: "Trade",
    prompt: "You give a sticker and get a pencil. This is a...",
    choices: ["Trade", "Tax", "Vote", "Map"],
    answer: 0,
    explanation: "A trade is when people swap things with each other.",
    quick: true,
  },
  {
    id: "soc-g1-16",
    subject: "social",
    grade: "1",
    standard: "1.B.1",
    skill: "Traditions",
    prompt: "Special ways a family celebrates are...",
    choices: ["Traditions", "Laws", "Maps", "Jobs"],
    answer: 0,
    explanation: "Traditions are customs passed down in families and communities.",
    quick: true,
  },
  {
    id: "soc-g1-17",
    subject: "social",
    grade: "1",
    standard: "1.B.1",
    skill: "Traditions",
    prompt: "Diwali, Hanukkah and Christmas all use...",
    choices: ["Lights", "Snowballs", "Kites", "Masks"],
    answer: 0,
    explanation: "Diwali is a festival of lights, Hanukkah candles are lit on a menorah, and many people use lights at Christmas.",
    quick: true,
  },
  {
    id: "soc-g1-18",
    subject: "social",
    grade: "1",
    standard: "1.B.1",
    skill: "Languages",
    prompt: "People around the world speak many...",
    choices: ["Languages", "Maps", "Moons", "Rules"],
    answer: 0,
    explanation: "People speak many languages, like English, Spanish, Cherokee and Chinese.",
    quick: true,
  },
];

export default questions;
