import type { Question } from "../../types";
// Grade 6 social studies — NC Standard Course of Study for Social Studies (adopted 2021). World history and geography, Paleolithic era to 1400 CE: early humans, writing and
// empires (6.H.1); migration, settlement and river valleys (6.G.1.1, 6.G.1); forms of government and law codes (6.C&G.1.1, 6.C&G.1); trade routes and the economics of empires
// (6.E.1.1, 6.E.1.2, 6.E.1); religions and belief systems (6.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g6-01",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Early farming",
    prompt: "When people began farming, many started to...",
    choices: ["Build villages", "Hunt mammoths", "Use no tools", "Move daily"],
    answer: 0,
    explanation: "Farming meant people could stay in one place, so they built permanent villages.",
    quick: true,
  },
  {
    id: "soc-g6-02",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    prompt: "Ancient Egypt grew along which river?",
    choices: ["Nile", "Amazon", "Tigris", "Yangtze"],
    answer: 0,
    explanation: "The Nile gave Egyptians water, rich soil and a path for boats.",
    quick: true,
  },
  {
    id: "soc-g6-03",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    prompt: "Mesopotamia lay between the Tigris and...",
    choices: ["Euphrates", "Nile", "Indus", "Huang He"],
    answer: 0,
    explanation: "Mesopotamia means 'land between rivers': the Tigris and Euphrates.",
    quick: true,
  },
  {
    id: "soc-g6-04",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Writing",
    prompt: "Cuneiform, one of the first writing systems, came from...",
    choices: ["Sumer", "Rome", "China", "The Maya"],
    answer: 0,
    explanation: "Sumerians pressed wedge-shaped marks into clay tablets over 5,000 years ago.",
    quick: true,
  },
  {
    id: "soc-g6-05",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Law codes",
    prompt: "Hammurabi's Code is famous as an early written set of...",
    choices: ["Laws", "Recipes", "Songs", "Maps"],
    answer: 0,
    explanation: "Babylon's King Hammurabi had about 282 laws carved in stone so people could know the rules.",
    quick: true,
  },
  {
    id: "soc-g6-06",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Democracy",
    prompt: "Ancient Athens is known as the birthplace of...",
    choices: ["Democracy", "Monarchy", "Feudalism", "Communism"],
    answer: 0,
    explanation: "In Athens, male citizens voted directly on laws, an early form of democracy.",
    quick: true,
  },
  {
    id: "soc-g6-07",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Roman Republic",
    prompt: "In the Roman Republic, citizens elected two leaders each year called...",
    choices: ["Consuls", "Pharaohs", "Emperors", "Shoguns"],
    answer: 0,
    explanation: "Two consuls ran the Roman Republic for one-year terms, so no single person held power too long.",
    quick: true,
  },
  {
    id: "soc-g6-08",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade routes",
    prompt: "The Silk Road was a network of trade routes linking China and...",
    choices: ["Europe", "Australia", "The Americas", "Antarctica"],
    answer: 0,
    explanation: "Silk, spices and ideas moved between China, Central Asia, the Middle East and Europe.",
    quick: true,
  },
  {
    id: "soc-g6-09",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade routes",
    prompt: "West African empires like Mali grew rich trading gold and...",
    choices: ["Salt", "Oil", "Coffee", "Tea"],
    answer: 0,
    explanation: "Gold from the south was traded for salt from the Sahara.",
    quick: true,
  },
  {
    id: "soc-g6-10",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "African empires",
    prompt: "Mansa Musa was a famously wealthy ruler of...",
    choices: ["Mali", "Rome", "China", "Persia"],
    answer: 0,
    explanation: "Mansa Musa ruled Mali in the 1300s. His pilgrimage to Mecca showed off Mali's wealth.",
    quick: true,
  },
  {
    id: "soc-g6-11",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Which religion began in ancient India?",
    choices: ["Hinduism", "Islam", "Judaism", "Christianity"],
    answer: 0,
    explanation: "Hinduism developed in South Asia. Buddhism also began in India.",
    quick: true,
  },
  {
    id: "soc-g6-12",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Whose teachings about respect and family shaped ancient China?",
    choices: ["Confucius", "Socrates", "Homer", "Julius Caesar"],
    answer: 0,
    explanation: "Confucius taught respect for elders, family duty and good government.",
    quick: true,
  },
  {
    id: "soc-g6-13",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "Americas",
    prompt: "The Maya civilization was centered in present-day Mexico and...",
    choices: ["Guatemala", "Peru", "Egypt", "China"],
    answer: 0,
    explanation: "Maya cities rose in southern Mexico and Central America, including Guatemala.",
    quick: true,
  },
  {
    id: "soc-g6-14",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Empires",
    prompt: "China's Great Wall was built mainly to keep out...",
    choices: ["Invaders", "Floods", "Tourists", "Earthquakes"],
    answer: 0,
    explanation: "Chinese dynasties built and rebuilt walls to protect against raids from the north.",
    quick: true,
  },
  {
    id: "soc-g6-15",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Empires",
    prompt: "Which empire built aqueducts and the Colosseum?",
    choices: ["Roman", "Persian", "Inca", "Mongol"],
    answer: 0,
    explanation: "Roman engineers built aqueducts, roads and the Colosseum.",
    quick: true,
  },
  {
    id: "soc-g6-16",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Timelines (BCE/CE)",
    passage:
      "Timeline cards: Great Pyramid of Giza built (about 2500 BCE). Roman Republic founded (509 BCE). Qin dynasty unifies China (221 BCE). Western Roman Empire falls (476 CE).",
    prompt: "Which event happened first?",
    choices: ["Pyramids of Giza built", "Qin unifies China", "Roman Republic founded", "Rome falls in the west"],
    answer: 0,
    explanation: "BCE years count down toward year 1, so 2500 BCE is the earliest of these dates.",
  },
  {
    id: "soc-g6-17",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    passage:
      "Each summer the Nile River flooded. When the water went down, it left a layer of dark, wet mud on the land nearby. Beyond this strip, the land was dry desert.",
    prompt: "Why did most Egyptians farm close to the Nile?",
    choices: ["Floods left rich soil for crops", "The desert soil was better", "Rivers kept enemies away", "Kings ordered them to"],
    answer: 0,
    explanation: "The Nile's yearly flood spread fertile silt, making farming possible in a desert land.",
  },
  {
    id: "soc-g6-18",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade and ideas",
    passage:
      "Buddhism began in India. Monks and merchants traveling the Silk Road carried its teachings. By about 100 CE, Buddhist temples were being built in China.",
    prompt: "What does this show about trade routes?",
    choices: ["They spread ideas as well as goods", "They only moved silk", "They stopped the spread of religion", "They were used only by soldiers"],
    answer: 0,
    explanation: "Merchants carried beliefs, art and inventions along with goods.",
  },
  {
    id: "soc-g6-19",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Early humans",
    prompt: "The Old Stone Age, when people hunted, gathered and used stone tools, is the...",
    choices: ["Paleolithic", "Industrial", "Renaissance", "Medieval"],
    answer: 0,
    explanation: "Paleolithic means 'old stone.' It lasted until people began farming about 12,000 years ago.",
    quick: true,
  },
  {
    id: "soc-g6-20",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Early humans",
    prompt: "Scientists find that modern humans first lived in...",
    choices: ["Africa", "Australia", "Antarctica", "Iceland"],
    answer: 0,
    explanation: "Fossils show modern humans lived in Africa first and later spread to other continents.",
    quick: true,
  },
  {
    id: "soc-g6-21",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Ancient Egypt",
    prompt: "The rulers of ancient Egypt were called...",
    choices: ["Pharaohs", "Consuls", "Shoguns", "Czars"],
    answer: 0,
    explanation: "Pharaohs ruled Egypt for about 3,000 years and were seen as god-kings.",
    quick: true,
  },
  {
    id: "soc-g6-22",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Writing",
    prompt: "The ancient Egyptian writing system that used pictures is...",
    choices: ["Hieroglyphics", "Cuneiform", "Latin", "Sanskrit"],
    answer: 0,
    explanation: "Hieroglyphs were carved on temples and written on papyrus.",
    quick: true,
  },
  {
    id: "soc-g6-23",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Empires",
    prompt: "The Byzantine Empire was ruled from the city of...",
    choices: ["Constantinople", "Rome", "Athens", "Baghdad"],
    answer: 0,
    explanation: "Constantinople (today's Istanbul) was the capital of the eastern Roman, or Byzantine, Empire.",
    quick: true,
  },
  {
    id: "soc-g6-24",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Americas",
    prompt: "The Olmec of ancient Mexico are known for carving giant stone...",
    choices: ["Heads", "Ships", "Coins", "Bridges"],
    answer: 0,
    explanation: "The Olmec, one of the first civilizations in Mesoamerica, carved huge stone heads.",
    quick: true,
  },
  {
    id: "soc-g6-25",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Inventions",
    prompt: "Paper was first invented in ancient...",
    choices: ["China", "Rome", "Egypt", "Greece"],
    answer: 0,
    explanation: "Paper was made in China about 2,000 years ago. Egyptians wrote on papyrus, which is different.",
    quick: true,
  },
  {
    id: "soc-g6-26",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Medieval Europe",
    prompt: "Under feudalism, lords gave knights land in exchange for...",
    choices: ["Loyalty", "Gold", "Ships", "Spices"],
    answer: 0,
    explanation: "Knights promised loyalty and military service. In return they received land.",
    quick: true,
  },
  {
    id: "soc-g6-27",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Law codes",
    passage:
      "From Hammurabi's Code (about 1754 BCE): 'If a man put out the eye of another man, his eye shall be put out.'",
    prompt: "What idea of justice does this law show?",
    choices: ["Punishment should match the crime", "All crimes get the same fine", "Judges may decide anything", "Only kings can be punished"],
    answer: 0,
    explanation: "This law is an example of 'an eye for an eye': the punishment equals the harm.",
  },
  {
    id: "soc-g6-28",
    subject: "social",
    grade: "6",
    standard: "6.G.1.1",
    skill: "Settlement",
    prompt: "Early farming villages first appeared in the Fertile...",
    choices: ["Crescent", "Valley", "Plain", "Delta"],
    answer: 0,
    explanation: "The Fertile Crescent, a curve of good land in Southwest Asia, had some of the first farms.",
    quick: true,
  },
  {
    id: "soc-g6-29",
    subject: "social",
    grade: "6",
    standard: "6.G.1.1",
    skill: "River valleys",
    prompt: "Ancient India's first cities grew along the ___ River.",
    choices: ["Indus", "Nile", "Tiber", "Amazon"],
    answer: 0,
    explanation: "Cities like Harappa and Mohenjo-daro grew along the Indus River in present-day Pakistan.",
    quick: true,
  },
  {
    id: "soc-g6-30",
    subject: "social",
    grade: "6",
    standard: "6.G.1.1",
    skill: "River valleys",
    prompt: "Early Chinese civilization grew along the Huang He, or...",
    choices: ["Yellow River", "Blue Nile", "Red River", "Amazon"],
    answer: 0,
    explanation: "The Huang He carries yellow silt that made farmland rich.",
    quick: true,
  },
  {
    id: "soc-g6-31",
    subject: "social",
    grade: "6",
    standard: "6.G.1.1",
    skill: "Physical geography",
    prompt: "Mountains and seas split ancient Greece into separate...",
    choices: ["City-states", "Deserts", "Empires", "Provinces"],
    answer: 0,
    explanation: "Rugged land made travel hard, so Greeks formed independent city-states like Athens and Sparta.",
    quick: true,
  },
  {
    id: "soc-g6-32",
    subject: "social",
    grade: "6",
    standard: "6.G.1.1",
    skill: "Migration",
    prompt: "Polynesian sailors used stars and waves to settle islands across the...",
    choices: ["Pacific", "Atlantic", "Arctic", "Indian Ocean"],
    answer: 0,
    explanation: "Polynesians sailed great distances to settle islands from Hawaii to New Zealand.",
    quick: true,
  },
  {
    id: "soc-g6-33",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "Physical geography",
    prompt: "Rome was built on the ___ River in Italy.",
    choices: ["Tiber", "Nile", "Seine", "Danube"],
    answer: 0,
    explanation: "Rome grew on hills next to the Tiber River.",
    quick: true,
  },
  {
    id: "soc-g6-34",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "Trade and location",
    passage:
      "Map description: The Sahara Desert stretches across North Africa. South of it are grasslands and the Niger River. The cities of Timbuktu and Gao grew near the river at the southern edge of the desert.",
    prompt: "Why did Timbuktu become a trading center?",
    choices: ["Desert caravans met river trade there", "It was on the Mediterranean coast", "It was in the middle of a rainforest", "It had no water nearby"],
    answer: 0,
    explanation: "Timbuktu sat where Sahara caravan routes met the Niger River, so goods changed hands there.",
  },
  {
    id: "soc-g6-35",
    subject: "social",
    grade: "6",
    standard: "6.E.1.2",
    skill: "Rise and fall of empires",
    prompt: "When late Roman emperors put less silver in coins, prices rose. This is...",
    choices: ["Inflation", "Deflation", "Barter", "Tariffs"],
    answer: 0,
    explanation: "Coins with less silver were worth less, so prices rose. Money troubles helped weaken Rome.",
    quick: true,
  },
  {
    id: "soc-g6-36",
    subject: "social",
    grade: "6",
    standard: "6.E.1",
    skill: "Trade",
    prompt: "Trading goods directly without money is called...",
    choices: ["Barter", "Banking", "Taxing", "Lending"],
    answer: 0,
    explanation: "Before coins, people often bartered, like trading grain for pottery.",
    quick: true,
  },
  {
    id: "soc-g6-37",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade and ideas",
    prompt: "Phoenician traders spread an early ___ around the Mediterranean.",
    choices: ["Alphabet", "Calendar", "Pyramid", "Compass"],
    answer: 0,
    explanation: "The Phoenician alphabet influenced the Greek and Latin alphabets we use today.",
    quick: true,
  },
  {
    id: "soc-g6-38",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade routes",
    prompt: "Seasonal monsoon winds helped sailors trade across the ___ Ocean.",
    choices: ["Indian", "Arctic", "Atlantic", "Southern"],
    answer: 0,
    explanation: "Monsoon winds change direction with the seasons, carrying ships between Africa, Arabia and India.",
    quick: true,
  },
  {
    id: "soc-g6-39",
    subject: "social",
    grade: "6",
    standard: "6.E.1.2",
    skill: "African empires",
    prompt: "Great Zimbabwe, a powerful city in southern Africa, was built of...",
    choices: ["Stone", "Ice", "Glass", "Steel"],
    answer: 0,
    explanation: "Its stone walls were built without mortar. The city grew rich trading gold and ivory.",
    quick: true,
  },
  {
    id: "soc-g6-40",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1.1",
    skill: "Forms of government",
    prompt: "Government by one ruler who inherits power is a...",
    choices: ["Monarchy", "Democracy", "Republic", "Oligarchy"],
    answer: 0,
    explanation: "In a monarchy, a king or queen rules, and power passes down in the family.",
    quick: true,
  },
  {
    id: "soc-g6-41",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1.1",
    skill: "Forms of government",
    prompt: "Government by a small group of powerful people is an...",
    choices: ["Oligarchy", "Monarchy", "Democracy", "Anarchy"],
    answer: 0,
    explanation: "Oligarchy means 'rule by a few.'",
    quick: true,
  },
  {
    id: "soc-g6-42",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1.1",
    skill: "Forms of government",
    prompt: "In ancient Egypt, the pharaoh was seen as both king and...",
    choices: ["A god", "A farmer", "A merchant", "A soldier"],
    answer: 0,
    explanation: "Government and religion were joined. Egyptians believed the pharaoh was divine.",
    quick: true,
  },
  {
    id: "soc-g6-43",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Roman law",
    prompt: "Rome's early laws, posted in public, were the Twelve...",
    choices: ["Tables", "Codes", "Rules", "Scrolls"],
    answer: 0,
    explanation: "The Twelve Tables (about 450 BCE) let Roman citizens see the laws.",
    quick: true,
  },
  {
    id: "soc-g6-44",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Athenian democracy",
    prompt: "Who could vote in ancient Athens?",
    choices: ["Free adult men who were citizens", "All adults living in Athens", "Women and enslaved people", "Only the king"],
    answer: 0,
    explanation: "Athens was a democracy for citizen men only. Women, enslaved people and foreigners could not vote.",
  },
  {
    id: "soc-g6-45",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Buddhism was founded by Siddhartha Gautama, known as the...",
    choices: ["Buddha", "Pharaoh", "Caesar", "Khan"],
    answer: 0,
    explanation: "Buddha means 'awakened one.' Buddhism began in India and spread across Asia.",
    quick: true,
  },
  {
    id: "soc-g6-46",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Judaism is monotheistic, which means believing in...",
    choices: ["One God", "Many gods", "No gods", "Nature spirits"],
    answer: 0,
    explanation: "Judaism taught belief in one God. Christianity and Islam are also monotheistic.",
    quick: true,
  },
  {
    id: "soc-g6-47",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Islam began in the 600s CE on the ___ Peninsula.",
    choices: ["Arabian", "Iberian", "Korean", "Italian"],
    answer: 0,
    explanation: "Islam began in Mecca with the Prophet Muhammad and spread quickly.",
    quick: true,
  },
  {
    id: "soc-g6-48",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    passage:
      "Confucius was asked for one word to guide a whole life. He answered: 'What you do not want done to yourself, do not do to others.' (from the Analects; Confucius lived about 551–479 BCE)",
    prompt: "Which idea does this teaching express?",
    choices: ["Treat others as you want to be treated", "Obey rulers no matter what", "Wealth matters most", "Avoid other people"],
    answer: 0,
    explanation: "Confucius taught kindness and respect. Similar 'golden rules' appear in many religions.",
  },
];

export default questions;
