import type { Question } from "../../types";
// Grade 7 social studies — NC Standard Course of Study for Social Studies (adopted 2021). Modern world, 1400 to present: turning points (7.H.1.1) and 20th-century conflicts (7.H.1);
// revolutions and changing governments (7.C&G.1.1, 7.C&G.1); Columbian Exchange and markets (7.E.1); globalization and cities (7.G.1); elements of culture (7.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g7-01",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Turning points",
    prompt: "Movable-type printing in Europe was developed around 1440 by...",
    choices: ["Gutenberg", "Columbus", "Napoleon", "Galileo"],
    answer: 0,
    explanation: "Gutenberg's press made books faster and cheaper, spreading ideas widely.",
    quick: true,
  },
  {
    id: "soc-g7-02",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Turning points",
    prompt: "Columbus's 1492 voyage began lasting contact between Europe and...",
    choices: ["The Americas", "China", "Australia", "Antarctica"],
    answer: 0,
    explanation: "After 1492, contact between Europe, Africa and the Americas changed life on every continent.",
    quick: true,
  },
  {
    id: "soc-g7-03",
    subject: "social",
    grade: "7",
    standard: "7.E.1",
    skill: "Columbian Exchange",
    prompt: "Which crop went from the Americas to Europe in the Columbian Exchange?",
    choices: ["Potatoes", "Wheat", "Sugarcane", "Rice"],
    answer: 0,
    explanation: "Potatoes, corn and tomatoes came from the Americas. Wheat, sugarcane and rice went the other way.",
    quick: true,
  },
  {
    id: "soc-g7-04",
    subject: "social",
    grade: "7",
    standard: "7.H.1.1",
    skill: "Industrial Revolution",
    prompt: "The Industrial Revolution began in the 1700s in...",
    choices: ["Great Britain", "Japan", "Brazil", "Egypt"],
    answer: 0,
    explanation: "Coal, iron, capital and inventions like the steam engine helped Britain industrialize first.",
    quick: true,
  },
  {
    id: "soc-g7-05",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "The French Revolution began in...",
    choices: ["1789", "1492", "1917", "1945"],
    answer: 0,
    explanation: "In 1789 French people rose against the king's absolute power and demanded rights.",
    quick: true,
  },
  {
    id: "soc-g7-06",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Revolutions",
    prompt: "The 1917 Russian Revolution led to a government run by...",
    choices: ["Communists", "Pharaohs", "Samurai", "Vikings"],
    answer: 0,
    explanation: "The Bolsheviks, led by Lenin, took power and later formed the Soviet Union.",
    quick: true,
  },
  {
    id: "soc-g7-07",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "World War I began in...",
    choices: ["1914", "1939", "1861", "1776"],
    answer: 0,
    explanation: "World War I lasted from 1914 to 1918.",
    quick: true,
  },
  {
    id: "soc-g7-08",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "World War II ended in...",
    choices: ["1945", "1918", "1965", "1939"],
    answer: 0,
    explanation: "World War II lasted from 1939 to 1945.",
    quick: true,
  },
  {
    id: "soc-g7-09",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "World wars",
    prompt: "Nazi Germany's murder of about six million Jews is called the...",
    choices: ["Holocaust", "Cold War", "Crusades", "Renaissance"],
    answer: 0,
    explanation: "The Holocaust was the state-sponsored murder of six million Jews and millions of others by Nazi Germany.",
    quick: true,
  },
  {
    id: "soc-g7-10",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1",
    skill: "Changing governments",
    prompt: "Nelson Mandela became South Africa's president in 1994 after the end of...",
    choices: ["Apartheid", "The Crusades", "World War I", "Renaissance"],
    answer: 0,
    explanation: "Apartheid was a system of racial segregation. Mandela became the first president elected in a fully democratic vote.",
    quick: true,
  },
  {
    id: "soc-g7-11",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1",
    skill: "International cooperation",
    prompt: "Which group formed in 1945 to promote world peace?",
    choices: ["United Nations", "NASA", "FIFA", "The Olympics"],
    answer: 0,
    explanation: "The United Nations was founded after World War II to prevent future wars.",
    quick: true,
  },
  {
    id: "soc-g7-12",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Cold War",
    prompt: "The Cold War was a rivalry between the U.S. and the...",
    choices: ["Soviet Union", "United Kingdom", "Mexico", "Canada"],
    answer: 0,
    explanation: "From about 1947 to 1991, the U.S. and Soviet Union competed without fighting a direct war.",
    quick: true,
  },
  {
    id: "soc-g7-13",
    subject: "social",
    grade: "7",
    standard: "7.H.1",
    skill: "Cold War",
    prompt: "The Berlin Wall fell in...",
    choices: ["1989", "1945", "1961", "2001"],
    answer: 0,
    explanation: "The wall went up in 1961 and fell in 1989. Germany reunified in 1990.",
    quick: true,
  },
  {
    id: "soc-g7-14",
    subject: "social",
    grade: "7",
    standard: "7.E.1",
    skill: "Market economies",
    prompt: "In a market economy, prices are mostly set by...",
    choices: ["Supply/demand", "One ruler", "A lottery", "The weather"],
    answer: 0,
    explanation: "Buyers and sellers, through supply and demand, set most prices in a market economy.",
    quick: true,
  },
  {
    id: "soc-g7-15",
    subject: "social",
    grade: "7",
    standard: "7.B.1.1",
    skill: "Culture",
    prompt: "Which is an element of culture?",
    choices: ["Language", "Latitude", "Elevation", "Rainfall"],
    answer: 0,
    explanation: "Culture includes language, religion, food, arts and customs. Latitude and rainfall are physical geography.",
    quick: true,
  },
  {
    id: "soc-g7-16",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Globalization",
    prompt: "Globalization means countries are becoming more...",
    choices: ["Connected", "Isolated", "Frozen", "Empty"],
    answer: 0,
    explanation: "Trade, travel and the internet link people and economies around the world.",
    quick: true,
  },
  {
    id: "soc-g7-17",
    subject: "social",
    grade: "7",
    standard: "7.C&G.1.1",
    skill: "Nonviolent resistance",
    passage:
      "In 1930, Mohandas Gandhi and his followers walked about 240 miles to the sea to make their own salt, breaking a British law that taxed salt. Thousands were later arrested, and they did not fight back.",
    prompt: "Which method does this passage describe?",
    choices: ["Nonviolent protest", "Armed revolt", "Trade embargo", "Royal decree"],
    answer: 0,
    explanation: "Gandhi led the Salt March to resist British rule without violence.",
  },
  {
    id: "soc-g7-18",
    subject: "social",
    grade: "7",
    standard: "7.G.1",
    skill: "Urbanization",
    passage:
      "Manchester, England, had about 25,000 people in the 1770s. After cotton mills opened, it grew to over 300,000 by the 1850s.",
    prompt: "What best explains the change in Manchester's population?",
    choices: ["People moved from farms to work in factories", "Farming became more popular", "People left cities for the countryside", "A war destroyed nearby towns"],
    answer: 0,
    explanation: "The Industrial Revolution drew workers to factory cities, a trend called urbanization.",
  },
];

export default questions;
