import type { Question } from "../../types";
// Kindergarten social studies — NC Standard Course of Study for Social Studies (adopted 2021). "The World Around Us": change over time (K.H.1),
// maps, globes and location words (K.G.1), rules, citizens and symbols (K.C&G.1), needs, wants, money and jobs (K.E.1), families and culture (K.B.1).
const questions: Question[] = [
  {
    id: "soc-gK-01",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "What do we use to find places?",
    choices: ["A map", "A spoon", "A clock", "A bed"],
    answer: 0,
    explanation: "A map is a drawing of a place seen from above. It helps us find where things are.",
    quick: true,
  },
  {
    id: "soc-gK-02",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "A globe is a round model of...",
    choices: ["Earth", "The moon", "The sun", "A ball game"],
    answer: 0,
    explanation: "A globe is shaped like a ball, just like Earth. It shows land and water.",
    quick: true,
  },
  {
    id: "soc-gK-03",
    subject: "social",
    grade: "K",
    standard: "K.G.1.1",
    skill: "Maps and globes",
    prompt: "On a map, blue often shows...",
    choices: ["Water", "Roads", "Trees", "Houses"],
    answer: 0,
    explanation: "Map makers usually color oceans, lakes and rivers blue.",
    quick: true,
  },
  {
    id: "soc-gK-04",
    subject: "social",
    grade: "K",
    standard: "K.G.1",
    skill: "Location words",
    prompt: "The cat is inside the box. The cat is ___ the box.",
    choices: ["In", "On top of", "Under", "Next to"],
    answer: 0,
    explanation: "Inside means in. Words like in, on, under and next to tell where things are.",
    quick: true,
  },
  {
    id: "soc-gK-05",
    subject: "social",
    grade: "K",
    standard: "K.H.1",
    skill: "Past and present",
    prompt: "You were a baby. Now you are big! This shows...",
    choices: ["Change", "Weather", "Money", "A map"],
    answer: 0,
    explanation: "People change over time. You grow and learn new things every year.",
    quick: true,
  },
  {
    id: "soc-gK-06",
    subject: "social",
    grade: "K",
    standard: "K.H.1",
    skill: "Past and present",
    prompt: "Yesterday is in the...",
    choices: ["Past", "Future", "Present", "Weekend"],
    answer: 0,
    explanation: "The past is time that already happened. Yesterday is in the past.",
    quick: true,
  },
  {
    id: "soc-gK-07",
    subject: "social",
    grade: "K",
    standard: "K.H.1",
    skill: "Past and present",
    prompt: "Long ago, people read by candlelight. Today we use...",
    choices: ["Lamps", "Rocks", "Fireflies", "Snow"],
    answer: 0,
    explanation: "Life changes over time. Now we have electric lamps to help us see at night.",
    quick: true,
  },
  {
    id: "soc-gK-08",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Rules",
    prompt: "Why do we have rules?",
    choices: ["To stay safe", "To be loud", "To get lost", "To be mean"],
    answer: 0,
    explanation: "Rules keep us safe and help everyone get along.",
    quick: true,
  },
  {
    id: "soc-gK-09",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Rules",
    prompt: "Who helps make rules at school?",
    choices: ["The principal", "A puppy", "The bus", "A tree"],
    answer: 0,
    explanation: "The principal and teachers help make school rules.",
    quick: true,
  },
  {
    id: "soc-gK-10",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Good citizens",
    prompt: "A good citizen...",
    choices: ["Shares", "Pushes", "Litters", "Grabs toys"],
    answer: 0,
    explanation: "Good citizens are kind, share, and help others.",
    quick: true,
  },
  {
    id: "soc-gK-11",
    subject: "social",
    grade: "K",
    standard: "K.C&G.1",
    skill: "Symbols",
    prompt: "Which color is on the U.S. flag?",
    choices: ["Blue", "Green", "Purple", "Orange"],
    answer: 0,
    explanation: "The U.S. flag is red, white and blue. It has 50 stars and 13 stripes.",
    quick: true,
  },
  {
    id: "soc-gK-12",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Needs and wants",
    prompt: "Which is a need?",
    choices: ["Food", "A toy car", "A game", "Candy"],
    answer: 0,
    explanation: "Needs are things we must have to live, like food, water and a home.",
    quick: true,
  },
  {
    id: "soc-gK-13",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Needs and wants",
    prompt: "Which is a want?",
    choices: ["A toy", "Water", "Food", "Air"],
    answer: 0,
    explanation: "A want is nice to have, but we can live without it.",
    quick: true,
  },
  {
    id: "soc-gK-14",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Money",
    prompt: "We use money to...",
    choices: ["Buy things", "Grow hair", "Make rain", "Sleep"],
    answer: 0,
    explanation: "People trade money for the things they need and want.",
    quick: true,
  },
  {
    id: "soc-gK-15",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "Who helps sick people get well?",
    choices: ["A doctor", "A chef", "A pilot", "A farmer"],
    answer: 0,
    explanation: "Doctors and nurses are workers who help people stay healthy.",
    quick: true,
  },
  {
    id: "soc-gK-16",
    subject: "social",
    grade: "K",
    standard: "K.E.1",
    skill: "Jobs",
    prompt: "Who grows food for us to eat?",
    choices: ["A farmer", "A firefighter", "A mail carrier", "A dentist"],
    answer: 0,
    explanation: "Farmers grow fruits, vegetables and grains. Many North Carolina farmers grow sweet potatoes.",
    quick: true,
  },
  {
    id: "soc-gK-17",
    subject: "social",
    grade: "K",
    standard: "K.B.1",
    skill: "Families",
    prompt: "Which is a way families celebrate?",
    choices: ["A party", "A fire drill", "Homework", "A bath"],
    answer: 0,
    explanation: "Families celebrate special days in many ways, like parties, meals and songs.",
    quick: true,
  },
  {
    id: "soc-gK-18",
    subject: "social",
    grade: "K",
    standard: "K.B.1",
    skill: "Families",
    prompt: "Friends like different foods. Is that okay?",
    choices: ["Yes", "No", "Only on Monday", "Never"],
    answer: 0,
    explanation: "People are different in many ways, and that is okay. We can learn from each other.",
    quick: true,
  },
];

export default questions;
