import type { Question } from "../../types";
// Grade 2 social studies — NC Standard Course of Study for Social Studies (adopted 2021). America as part of the world: contributions of diverse Americans and key events
// (2.H.1.1, 2.H.1.2, 2.H.1); absolute and relative location, environment and settlement, continents and oceans (2.G.1.1, 2.G.1.2, 2.G.1); democracy, freedom and
// equality (2.C&G.1.1, 2.C&G.1.2, 2.C&G.1); scarcity, resources and production, consumers (2.E.1.1, 2.E.1.2, 2.E.1); culture and immigration (2.B.1.1, 2.B.1).
const questions: Question[] = [
  {
    id: "soc-g2-01",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "How many continents are there?",
    choices: ["7", "5", "3", "10"],
    answer: 0,
    explanation: "The seven continents are Africa, Antarctica, Asia, Australia, Europe, North America and South America.",
    quick: true,
  },
  {
    id: "soc-g2-02",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "The United States is on which continent?",
    choices: ["North America", "South America", "Europe", "Africa"],
    answer: 0,
    explanation: "The United States is in North America, along with Canada and Mexico.",
    quick: true,
  },
  {
    id: "soc-g2-03",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "Continents and oceans",
    prompt: "Which ocean touches North Carolina?",
    choices: ["Atlantic", "Pacific", "Arctic", "Indian"],
    answer: 0,
    explanation: "The Atlantic Ocean is on the East Coast. The Pacific is on the West Coast.",
    quick: true,
  },
  {
    id: "soc-g2-04",
    subject: "social",
    grade: "2",
    standard: "2.G.1",
    skill: "States",
    prompt: "How many states does the U.S. have?",
    choices: ["50", "13", "48", "100"],
    answer: 0,
    explanation: "The United States has 50 states. North Carolina is one of them.",
    quick: true,
  },
  {
    id: "soc-g2-05",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "The first U.S. President was George...",
    choices: ["Washington", "Lincoln", "Jefferson", "Adams"],
    answer: 0,
    explanation: "George Washington became the first President in 1789.",
    quick: true,
  },
  {
    id: "soc-g2-06",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "Who led many enslaved people to freedom?",
    choices: ["Harriet Tubman", "Betsy Ross", "Amelia Earhart", "Paul Revere"],
    answer: 0,
    explanation: "Harriet Tubman escaped slavery and then guided others to freedom on the Underground Railroad.",
    quick: true,
  },
  {
    id: "soc-g2-07",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "American leaders",
    prompt: "Martin Luther King Jr. worked for...",
    choices: ["Equal rights", "Space travel", "Faster cars", "New sports"],
    answer: 0,
    explanation: "Dr. King led peaceful protests so all people would be treated fairly.",
    quick: true,
  },
  {
    id: "soc-g2-08",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "Holidays and symbols",
    prompt: "July 4th is ___ Day.",
    choices: ["Independence", "Thanksgiving", "Labor", "Earth"],
    answer: 0,
    explanation: "On July 4, 1776, the Declaration of Independence was adopted. We celebrate America's birthday.",
    quick: true,
  },
  {
    id: "soc-g2-09",
    subject: "social",
    grade: "2",
    standard: "2.H.1",
    skill: "Holidays and symbols",
    prompt: "The Statue of Liberty stands for...",
    choices: ["Freedom", "Money", "Weather", "Sports"],
    answer: 0,
    explanation: "The Statue of Liberty is a symbol of freedom. It welcomed many people coming to America.",
    quick: true,
  },
  {
    id: "soc-g2-10",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.1",
    skill: "Democracy",
    prompt: "In a democracy, people choose leaders by...",
    choices: ["Voting", "Guessing", "Fighting", "Shouting"],
    answer: 0,
    explanation: "In a democracy, citizens vote to choose their leaders.",
    quick: true,
  },
  {
    id: "soc-g2-11",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1",
    skill: "Democracy",
    prompt: "The leader of our country is the...",
    choices: ["President", "Mayor", "Governor", "Principal"],
    answer: 0,
    explanation: "The President leads the United States. A governor leads a state, and a mayor leads a city.",
    quick: true,
  },
  {
    id: "soc-g2-12",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1",
    skill: "Democracy",
    prompt: "The Constitution is the plan for our country's...",
    choices: ["Government", "Recess", "Weather", "Sports"],
    answer: 0,
    explanation: "The U.S. Constitution sets up our government and protects people's rights.",
    quick: true,
  },
  {
    id: "soc-g2-13",
    subject: "social",
    grade: "2",
    standard: "2.E.1.1",
    skill: "Scarcity",
    prompt: "When there is not enough of something, it is...",
    choices: ["Scarce", "Free", "Extra", "Heavy"],
    answer: 0,
    explanation: "Scarcity means there is not enough for everyone, so people must make choices.",
    quick: true,
  },
  {
    id: "soc-g2-14",
    subject: "social",
    grade: "2",
    standard: "2.E.1",
    skill: "Producers and consumers",
    prompt: "People who buy and use goods are...",
    choices: ["Consumers", "Producers", "Voters", "Mayors"],
    answer: 0,
    explanation: "Consumers buy and use goods and services. Producers make them.",
    quick: true,
  },
  {
    id: "soc-g2-15",
    subject: "social",
    grade: "2",
    standard: "2.E.1",
    skill: "Producers and consumers",
    prompt: "Money you earn from a job is...",
    choices: ["Income", "Scarcity", "A tax", "A loan"],
    answer: 0,
    explanation: "Income is money people earn by working.",
    quick: true,
  },
  {
    id: "soc-g2-16",
    subject: "social",
    grade: "2",
    standard: "2.E.1.1",
    skill: "Scarcity",
    prompt: "You have $1. You want juice and a cookie. Each costs $1. You must...",
    choices: ["Choose one", "Get both", "Get neither", "Pay $5"],
    answer: 0,
    explanation: "When money is scarce, you have to choose. Picking one means giving up the other.",
    quick: true,
  },
  {
    id: "soc-g2-17",
    subject: "social",
    grade: "2",
    standard: "2.B.1.1",
    skill: "Culture",
    prompt: "A group's food, music and language are its...",
    choices: ["Culture", "Weather", "Money", "Border"],
    answer: 0,
    explanation: "Culture is a group's way of life, like its food, music, language and holidays.",
    quick: true,
  },
  {
    id: "soc-g2-18",
    subject: "social",
    grade: "2",
    standard: "2.B.1",
    skill: "Immigration",
    prompt: "Many people moved to America from other...",
    choices: ["Countries", "Planets", "Oceans", "Moons"],
    answer: 0,
    explanation: "Immigrants come from other countries. They bring their cultures with them.",
    quick: true,
  },
  {
    id: "soc-g2-19",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "Sacagawea helped Lewis and Clark explore the American...",
    choices: ["West", "Arctic", "Moon", "Ocean floor"],
    answer: 0,
    explanation: "Sacagawea, a Shoshone woman, guided and translated for the Lewis and Clark expedition (1804–1806).",
    quick: true,
  },
  {
    id: "soc-g2-20",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "In 1947, Jackie Robinson became the first Black player in modern Major League...",
    choices: ["Baseball", "Football", "Soccer", "Hockey"],
    answer: 0,
    explanation: "Jackie Robinson joined the Brooklyn Dodgers and opened the door for Black players in the major leagues.",
    quick: true,
  },
  {
    id: "soc-g2-21",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "Cesar Chavez worked for fair treatment of...",
    choices: ["Farmworkers", "Astronauts", "Bankers", "Kings"],
    answer: 0,
    explanation: "Cesar Chavez and Dolores Huerta organized farmworkers to win better pay and safer working conditions.",
    quick: true,
  },
  {
    id: "soc-g2-22",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "Susan B. Anthony worked for women's right to...",
    choices: ["Vote", "Drive", "Fly", "Sing"],
    answer: 0,
    explanation: "Susan B. Anthony spent her life working so women could vote. The 19th Amendment passed in 1920.",
    quick: true,
  },
  {
    id: "soc-g2-23",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "Sequoyah created a writing system for the...",
    choices: ["Cherokee", "Lumbee", "Aztec", "Inca"],
    answer: 0,
    explanation: "Sequoyah finished his Cherokee syllabary in 1821, and soon many Cherokee people could read and write.",
    quick: true,
  },
  {
    id: "soc-g2-24",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American leaders",
    prompt: "Abraham Lincoln was President during the...",
    choices: ["Civil War", "Revolution", "Moon landing", "World War II"],
    answer: 0,
    explanation: "Lincoln led the country during the Civil War (1861–1865) and worked to end slavery.",
    quick: true,
  },
  {
    id: "soc-g2-25",
    subject: "social",
    grade: "2",
    standard: "2.H.1.1",
    skill: "American contributors",
    prompt: "Clara Barton founded the American...",
    choices: ["Red Cross", "Navy", "Post Office", "Girl Scouts"],
    answer: 0,
    explanation: "Clara Barton nursed soldiers in the Civil War and founded the American Red Cross in 1881.",
    quick: true,
  },
  {
    id: "soc-g2-26",
    subject: "social",
    grade: "2",
    standard: "2.H.1.2",
    skill: "Historical events",
    prompt: "In 1969, American astronauts were the first people to land on the...",
    choices: ["Moon", "Mars", "Sun", "Venus"],
    answer: 0,
    explanation: "Apollo 11 landed on the Moon on July 20, 1969.",
    quick: true,
  },
  {
    id: "soc-g2-27",
    subject: "social",
    grade: "2",
    standard: "2.H.1.2",
    skill: "Historical events",
    prompt: "Which 1776 document said the 13 colonies were free from Britain?",
    choices: ["Declaration", "Bill of Rights", "Constitution", "Magna Carta"],
    answer: 0,
    explanation: "The Declaration of Independence was adopted on July 4, 1776.",
    quick: true,
  },
  {
    id: "soc-g2-28",
    subject: "social",
    grade: "2",
    standard: "2.H.1.2",
    skill: "Historical events",
    prompt: "The first 13 states began as 13 British...",
    choices: ["Colonies", "Countries", "Cities", "Islands"],
    answer: 0,
    explanation: "A colony is ruled by another country. The 13 colonies became the first 13 states.",
    quick: true,
  },
  {
    id: "soc-g2-29",
    subject: "social",
    grade: "2",
    standard: "2.H.1.2",
    skill: "Timelines",
    passage:
      "Timeline: 1776 – Declaration of Independence adopted. 1861 – Civil War begins. 1920 – Women win the right to vote. 1969 – People first walk on the Moon.",
    prompt: "Which event on this timeline happened second?",
    choices: ["The Civil War began", "Women won the vote", "People walked on the Moon", "The Declaration was adopted"],
    answer: 0,
    explanation: "1861 comes after 1776 and before 1920, so the start of the Civil War is second.",
  },
  {
    id: "soc-g2-30",
    subject: "social",
    grade: "2",
    standard: "2.G.1.1",
    skill: "Location",
    prompt: "The capital of the United States is...",
    choices: ["Washington, DC", "New York City", "Raleigh", "Philadelphia"],
    answer: 0,
    explanation: "Washington, DC, has been the U.S. capital since 1800. Raleigh is North Carolina's capital.",
    quick: true,
  },
  {
    id: "soc-g2-31",
    subject: "social",
    grade: "2",
    standard: "2.G.1.1",
    skill: "Location",
    prompt: "Which country is north of the United States?",
    choices: ["Canada", "Mexico", "Brazil", "Cuba"],
    answer: 0,
    explanation: "Canada is north of the United States and Mexico is south of it.",
    quick: true,
  },
  {
    id: "soc-g2-32",
    subject: "social",
    grade: "2",
    standard: "2.G.1.1",
    skill: "Absolute and relative location",
    prompt: "Your home address is an example of ___ location.",
    choices: ["Absolute", "Relative", "Lost", "Secret"],
    answer: 0,
    explanation: "Absolute location is an exact spot, like a street address.",
    quick: true,
  },
  {
    id: "soc-g2-33",
    subject: "social",
    grade: "2",
    standard: "2.G.1.1",
    skill: "Absolute and relative location",
    prompt: "'The store is next to the library' describes ___ location.",
    choices: ["Relative", "Absolute", "Exact", "Global"],
    answer: 0,
    explanation: "Relative location tells where a place is compared to another place.",
    quick: true,
  },
  {
    id: "soc-g2-34",
    subject: "social",
    grade: "2",
    standard: "2.G.1.1",
    skill: "Location",
    prompt: "North Carolina is in which part of the United States?",
    choices: ["Southeast", "Northwest", "Southwest", "Midwest"],
    answer: 0,
    explanation: "North Carolina is on the Atlantic coast in the southeastern United States.",
    quick: true,
  },
  {
    id: "soc-g2-35",
    subject: "social",
    grade: "2",
    standard: "2.G.1.2",
    skill: "Environment and settlement",
    prompt: "Early towns were often built near rivers because rivers gave...",
    choices: ["Fresh water", "Mountains", "Sand dunes", "Volcanoes"],
    answer: 0,
    explanation: "Rivers gave people fresh water, fish and a way to travel and trade.",
    quick: true,
  },
  {
    id: "soc-g2-36",
    subject: "social",
    grade: "2",
    standard: "2.G.1.2",
    skill: "Environment and settlement",
    prompt: "The flat, grassy Great Plains became a good place for...",
    choices: ["Farms", "Ski slopes", "Seaports", "Glaciers"],
    answer: 0,
    explanation: "Flat land and rich soil made the Great Plains a great place to grow wheat and raise cattle.",
    quick: true,
  },
  {
    id: "soc-g2-37",
    subject: "social",
    grade: "2",
    standard: "2.G.1.2",
    skill: "Environment and settlement",
    passage:
      "Settlers are choosing a spot for a new town. Place A is next to a river with rich soil and trees. Place B is on a rocky hilltop far from water. Place C is in a dry desert. Place D is a tiny island with no fresh water.",
    prompt: "Which place would most likely grow into a town?",
    choices: ["Place A", "Place B", "Place C", "Place D"],
    answer: 0,
    explanation: "Place A has water, good soil and trees for building, so people could live and farm there.",
  },
  {
    id: "soc-g2-38",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.1",
    skill: "Democracy",
    prompt: "When the choice with the most votes wins, it is called majority...",
    choices: ["Rule", "Power", "Money", "Party"],
    answer: 0,
    explanation: "Majority rule means the choice with more than half the votes wins. It is a key idea of democracy.",
    quick: true,
  },
  {
    id: "soc-g2-39",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.1",
    skill: "Democracy",
    prompt: "Who makes the laws for the whole United States?",
    choices: ["Congress", "The mayor", "Teachers", "The governor"],
    answer: 0,
    explanation: "Congress makes national laws. Mayors and governors lead cities and states.",
    quick: true,
  },
  {
    id: "soc-g2-40",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.1",
    skill: "Democracy",
    prompt: "Americans vote for President every ___ years.",
    choices: ["4", "2", "6", "10"],
    answer: 0,
    explanation: "Presidential elections happen every four years.",
    quick: true,
  },
  {
    id: "soc-g2-41",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.2",
    skill: "Freedom and equality",
    prompt: "The Bill of Rights protects people's...",
    choices: ["Freedoms", "Toys", "Houses", "Pets"],
    answer: 0,
    explanation: "The Bill of Rights lists freedoms, like freedom of speech and religion, that the government must protect.",
    quick: true,
  },
  {
    id: "soc-g2-42",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.2",
    skill: "Freedom and equality",
    prompt: "Equality under the law means everyone is treated...",
    choices: ["Fairly", "Unfairly", "Rudely", "Secretly"],
    answer: 0,
    explanation: "Equality means the same laws and rights apply to everyone.",
    quick: true,
  },
  {
    id: "soc-g2-43",
    subject: "social",
    grade: "2",
    standard: "2.C&G.1.2",
    skill: "Freedom and equality",
    passage:
      "In one town, some families go to a church, some go to a mosque, some go to a synagogue, and some do not go to any place of worship. The government lets each family choose.",
    prompt: "Which freedom does this show?",
    choices: ["Freedom of religion", "Freedom of the press", "Right to vote", "Right to a jury"],
    answer: 0,
    explanation: "The First Amendment lets people choose how to worship, or not to worship at all.",
  },
  {
    id: "soc-g2-44",
    subject: "social",
    grade: "2",
    standard: "2.E.1.2",
    skill: "Resources",
    prompt: "Wood, water and soil are ___ resources.",
    choices: ["Natural", "Human", "Capital", "Fake"],
    answer: 0,
    explanation: "Natural resources come from nature. People use them to make goods.",
    quick: true,
  },
  {
    id: "soc-g2-45",
    subject: "social",
    grade: "2",
    standard: "2.E.1.2",
    skill: "Resources",
    prompt: "A tractor that a farmer uses is a ___ resource.",
    choices: ["Capital", "Natural", "Human", "Free"],
    answer: 0,
    explanation: "Capital resources are tools and machines people use to make goods.",
    quick: true,
  },
  {
    id: "soc-g2-46",
    subject: "social",
    grade: "2",
    standard: "2.E.1.2",
    skill: "Resources",
    prompt: "A baker's skill and hard work are ___ resources.",
    choices: ["Human", "Natural", "Capital", "Weather"],
    answer: 0,
    explanation: "Human resources are the people who do the work and the skills they bring.",
    quick: true,
  },
  {
    id: "soc-g2-47",
    subject: "social",
    grade: "2",
    standard: "2.E.1.2",
    skill: "Resources and production",
    passage:
      "A freeze in spring hurt the apple trees at a big orchard. This fall the orchard has only half as many apples as last year.",
    prompt: "What will most likely happen?",
    choices: ["Apples will be scarce and may cost more", "Apples will be free", "There will be more apples than ever", "People will stop eating food"],
    answer: 0,
    explanation: "When fewer apples are grown, there are not enough for everyone, so prices often go up.",
  },
  {
    id: "soc-g2-48",
    subject: "social",
    grade: "2",
    standard: "2.B.1.1",
    skill: "Culture",
    prompt: "Cinco de Mayo is a celebration from which country's culture?",
    choices: ["Mexico", "Japan", "Ireland", "India"],
    answer: 0,
    explanation: "Cinco de Mayo remembers a Mexican victory in 1862. Many Mexican Americans celebrate it with music and food.",
    quick: true,
  },
];

export default questions;
