import type { Question } from "../../types";
// Grade 4 social studies — NC Standard Course of Study for Social Studies (adopted 2021). North Carolina history: American Indians in NC (4.H.1.1), changing roles (4.H.1.2),
// revolution, reform and resistance (4.H.1.3), NC in major conflicts (4.H.1.4), Roanoke and the Wright brothers (4.H.1); NC regions, movement and human-environment
// interaction (4.G.1.1, 4.G.1.2, 4.G.1.3, 4.G.1); state leaders, groups in government, NC Constitution rights (4.C&G.1.1–1.3, 4.C&G.1); scarcity, industries and factors
// of production (4.E.1.1–1.3, 4.E.1); NC traditions, art and cultural groups (4.B.1.1, 4.B.1.2).
const questions: Question[] = [
  {
    id: "soc-g4-01",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    prompt: "Which group lived in NC long before Europeans arrived?",
    choices: ["Tuscarora", "Pilgrims", "Vikings", "Spanish"],
    answer: 0,
    explanation: "The Tuscarora, Cherokee, Catawba and other American Indian nations lived in NC for thousands of years before Europeans came.",
    quick: true,
  },
  {
    id: "soc-g4-02",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    passage:
      "In 1838, the U.S. Army forced most Cherokee people to leave their homes in the Southeast and walk west on the Trail of Tears. Some Cherokee hid in the North Carolina mountains or had legal claims to stay. Later they were able to keep land there.",
    prompt: "Why is there still a Cherokee nation in western NC today?",
    choices: ["Some Cherokee stayed in the mountains and kept land there", "The Army never came to NC", "The Cherokee moved there in 1900", "Settlers gave the whole state back"],
    answer: 0,
    explanation: "Some Cherokee avoided removal. Their descendants are the Eastern Band of Cherokee Indians, based at Qualla Boundary.",
  },
  {
    id: "soc-g4-03",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "The English colony that vanished from Roanoke Island is called the...",
    choices: ["Lost Colony", "Jamestown", "Plymouth", "New Bern"],
    answer: 0,
    explanation: "The 1587 Roanoke colony disappeared by 1590. No one knows for sure what happened.",
    quick: true,
  },
  {
    id: "soc-g4-04",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "The first English child born in the Americas was...",
    choices: ["Virginia Dare", "Pocahontas", "Betsy Ross", "Dolley Madison"],
    answer: 0,
    explanation: "Virginia Dare was born on Roanoke Island in 1587, in the Lost Colony.",
    quick: true,
  },
  {
    id: "soc-g4-05",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Revolution in NC",
    prompt: "The Halifax Resolves (April 12, 1776) were an early official call for...",
    choices: ["Independence", "Lower taxes", "A new king", "More soldiers"],
    answer: 0,
    explanation: "NC's Halifax Resolves were the first official action by a colony calling for independence from Britain. The date is on NC's flag.",
    quick: true,
  },
  {
    id: "soc-g4-06",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Civil rights in NC",
    prompt: "In 1960, four students held a sit-in at a Greensboro lunch counter to protest...",
    choices: ["Segregation", "High prices", "School hours", "New roads"],
    answer: 0,
    explanation: "The Greensboro Four sat at a whites-only counter at Woolworth's. Their peaceful protest spread to many cities.",
    quick: true,
  },
  {
    id: "soc-g4-07",
    subject: "social",
    grade: "4",
    standard: "4.H.1.2",
    skill: "Changing roles",
    prompt: "During World War II, many NC women took new jobs in...",
    choices: ["Shipyards", "Space", "Video games", "Computers"],
    answer: 0,
    explanation: "With many men in the military, women built ships in Wilmington and worked in factories. Women's roles changed.",
    quick: true,
  },
  {
    id: "soc-g4-08",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Wright brothers",
    prompt: "The Wright brothers made the first powered airplane flight in 1903 near...",
    choices: ["Kitty Hawk", "Raleigh", "Asheville", "Charlotte"],
    answer: 0,
    explanation: "On December 17, 1903, Orville and Wilbur Wright flew at Kill Devil Hills near Kitty Hawk.",
    quick: true,
  },
  {
    id: "soc-g4-09",
    subject: "social",
    grade: "4",
    standard: "4.G.1.2",
    skill: "Movement in NC",
    passage:
      "In 1856, the North Carolina Railroad was finished. It ran from Goldsboro through Raleigh and Greensboro to Charlotte. Before this, Piedmont farmers hauled crops for days by wagon on muddy roads.",
    prompt: "How did the railroad most likely change towns along its route?",
    choices: ["They grew as trade became easier", "They shrank because no one traveled", "Nothing changed", "Farmers stopped growing crops"],
    answer: 0,
    explanation: "Railroads moved crops and goods faster and cheaper. Towns along the line grew into trading centers.",
  },
  {
    id: "soc-g4-10",
    subject: "social",
    grade: "4",
    standard: "4.G.1",
    skill: "NC coast",
    prompt: "Many shipwrecks off NC's coast earned it the name Graveyard of the...",
    choices: ["Atlantic", "Pacific", "Piedmont", "Rivers"],
    answer: 0,
    explanation: "Shallow shoals and storms near Cape Hatteras sank many ships, so the area is called the Graveyard of the Atlantic.",
    quick: true,
  },
  {
    id: "soc-g4-11",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.1",
    skill: "State leaders",
    prompt: "Who leads NC's executive branch?",
    choices: ["Governor", "Lt. Governor", "Mayor", "Chief Justice"],
    answer: 0,
    explanation: "The governor is elected by NC voters to lead the executive branch and carry out state laws.",
    quick: true,
  },
  {
    id: "soc-g4-12",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1",
    skill: "State government",
    prompt: "NC's General Assembly has a House of Representatives and a...",
    choices: ["Senate", "Court", "Cabinet", "Council"],
    answer: 0,
    explanation: "The General Assembly is NC's legislative branch. It has two houses: the Senate and the House.",
    quick: true,
  },
  {
    id: "soc-g4-13",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1",
    skill: "State government",
    prompt: "North Carolina's state capital is...",
    choices: ["Raleigh", "Charlotte", "Durham", "Greensboro"],
    answer: 0,
    explanation: "Raleigh was founded in 1792 to be NC's capital. The General Assembly meets there.",
    quick: true,
  },
  {
    id: "soc-g4-14",
    subject: "social",
    grade: "4",
    standard: "4.E.1.1",
    skill: "Scarcity",
    passage:
      "During a long summer drought in eastern North Carolina, the rivers ran low. Farmers had to choose which fields to water, and some crops dried up.",
    prompt: "What is the best example of scarcity in this story?",
    choices: ["There is not enough water for all the crops", "The farmers have too much corn", "Prices of seeds went down", "The town built a new school"],
    answer: 0,
    explanation: "Scarcity means limited resources. With little water, farmers must decide which fields to water first.",
  },
  {
    id: "soc-g4-15",
    subject: "social",
    grade: "4",
    standard: "4.E.1",
    skill: "NC economy",
    prompt: "For many years, NC's most valuable cash crop was...",
    choices: ["Tobacco", "Coffee", "Rice", "Oranges"],
    answer: 0,
    explanation: "Tobacco was NC's leading cash crop for much of its history. Today NC grows many crops and raises hogs and poultry.",
    quick: true,
  },
  {
    id: "soc-g4-16",
    subject: "social",
    grade: "4",
    standard: "4.E.1",
    skill: "NC economy",
    prompt: "Furniture making grew in NC's Piedmont because of plentiful...",
    choices: ["Hardwood trees", "Gold", "Oil", "Coal"],
    answer: 0,
    explanation: "Forests of hardwood made High Point and nearby towns centers of furniture making.",
    quick: true,
  },
  {
    id: "soc-g4-17",
    subject: "social",
    grade: "4",
    standard: "4.B.1.1",
    skill: "NC traditions",
    prompt: "Bluegrass and old-time music are traditions of NC's...",
    choices: ["Mountains", "Outer Banks", "Sandhills", "Coastal Plain"],
    answer: 0,
    explanation: "Mountain communities kept old-time fiddle and banjo music alive, and bluegrass grew from it.",
    quick: true,
  },
  {
    id: "soc-g4-18",
    subject: "social",
    grade: "4",
    standard: "4.B.1.1",
    skill: "NC traditions",
    prompt: "Seagrove, NC, is famous for which traditional art?",
    choices: ["Pottery", "Glassmaking", "Painting", "Weaving"],
    answer: 0,
    explanation: "Potters have worked in Seagrove for over 200 years using local clay.",
    quick: true,
  },
  {
    id: "soc-g4-19",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    passage:
      "At Town Creek Indian Mound in Montgomery County, archaeologists found pottery, tools and the remains of a town with a large earthen mound. American Indians lived there roughly 700 to 900 years ago.",
    prompt: "What do these discoveries show?",
    choices: ["American Indians built towns in NC long before Europeans came", "Europeans built the mound", "No one lived in NC before 1585", "The mound was built in the 1900s"],
    answer: 0,
    explanation: "Town Creek shows that American Indian peoples had towns, farms and ceremonies in NC centuries before Europeans arrived.",
  },
  {
    id: "soc-g4-20",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    prompt: "The Tuscarora War (1711–1715) was fought between the Tuscarora and...",
    choices: ["Colonists", "The Spanish", "The French", "The Dutch"],
    answer: 0,
    explanation: "The Tuscarora fought colonists who were taking their land. After the war, many Tuscarora moved north to New York.",
    quick: true,
  },
  {
    id: "soc-g4-21",
    subject: "social",
    grade: "4",
    standard: "4.H.1.1",
    skill: "American Indians in NC",
    prompt: "The Eastern Band of Cherokee's land in western NC is the Qualla...",
    choices: ["Boundary", "Mountain", "Village", "River"],
    answer: 0,
    explanation: "The Qualla Boundary is land held by the Eastern Band of Cherokee Indians near Cherokee, NC.",
    quick: true,
  },
  {
    id: "soc-g4-22",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "Sir Walter Raleigh sent English colonists to...",
    choices: ["Roanoke Island", "Plymouth", "Bermuda", "Cuba"],
    answer: 0,
    explanation: "Raleigh sponsored voyages to Roanoke Island in the 1580s. NC's capital is named for him.",
    quick: true,
  },
  {
    id: "soc-g4-23",
    subject: "social",
    grade: "4",
    standard: "4.H.1",
    skill: "Roanoke",
    prompt: "The word carved at the empty Roanoke colony in 1590 was...",
    choices: ["Croatoan", "Jamestown", "Help", "Virginia"],
    answer: 0,
    explanation: "John White found 'CROATOAN' carved on a post. It was the name of a nearby island and its people.",
    quick: true,
  },
  {
    id: "soc-g4-24",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Revolution in NC",
    prompt: "In 1774, women in Edenton signed a pledge to stop buying British...",
    choices: ["Tea", "Guns", "Ships", "Horses"],
    answer: 0,
    explanation: "The Edenton Tea Party was one of the first political actions by women in the colonies.",
    quick: true,
  },
  {
    id: "soc-g4-25",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Revolution in NC",
    prompt: "The 1776 Battle of Moores Creek Bridge was a win for NC's...",
    choices: ["Patriots", "Loyalists", "British", "French"],
    answer: 0,
    explanation: "Patriots defeated Loyalists at Moores Creek Bridge in February 1776, which kept NC out of British control.",
    quick: true,
  },
  {
    id: "soc-g4-26",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Resistance",
    prompt: "Harriet Jacobs escaped slavery in Edenton, NC, and later wrote a...",
    choices: ["Book", "Song", "Law", "Map"],
    answer: 0,
    explanation: "Her 1861 book, Incidents in the Life of a Slave Girl, told the truth about slavery.",
    quick: true,
  },
  {
    id: "soc-g4-27",
    subject: "social",
    grade: "4",
    standard: "4.H.1.3",
    skill: "Resistance",
    prompt: "David Walker, born in Wilmington, wrote a famous Appeal against...",
    choices: ["Slavery", "Taxes", "Railroads", "Schools"],
    answer: 0,
    explanation: "David Walker's Appeal (1829) called on enslaved people and the nation to resist slavery.",
    quick: true,
  },
  {
    id: "soc-g4-28",
    subject: "social",
    grade: "4",
    standard: "4.H.1.4",
    skill: "NC in the Civil War",
    prompt: "During the Civil War, which NC port did blockade runners use most?",
    choices: ["Wilmington", "Asheville", "Raleigh", "Charlotte"],
    answer: 0,
    explanation: "Ships slipped past the Union blockade into Wilmington, protected by Fort Fisher, until 1865.",
    quick: true,
  },
  {
    id: "soc-g4-29",
    subject: "social",
    grade: "4",
    standard: "4.H.1.4",
    skill: "NC in the Civil War",
    prompt: "The Civil War's largest troop surrender was in 1865 at Bennett Place near...",
    choices: ["Durham", "Boone", "Wilmington", "New Bern"],
    answer: 0,
    explanation: "General Johnston surrendered about 89,000 Confederate soldiers to General Sherman at Bennett Place.",
    quick: true,
  },
  {
    id: "soc-g4-30",
    subject: "social",
    grade: "4",
    standard: "4.H.1.2",
    skill: "Changing roles",
    prompt: "In the early 1900s, many NC women and children worked in textile...",
    choices: ["Mills", "Mines", "Ships", "Labs"],
    answer: 0,
    explanation: "Cotton mills in the Piedmont hired whole families, often for long hours and low pay.",
    quick: true,
  },
  {
    id: "soc-g4-31",
    subject: "social",
    grade: "4",
    standard: "4.H.1.2",
    skill: "Changing roles",
    prompt: "During the Great Migration, many Black North Carolinians moved north for...",
    choices: ["Better jobs", "Gold", "Warmer weather", "Beaches"],
    answer: 0,
    explanation: "From about 1910 to 1970, many Black families left the South to escape Jim Crow laws and find better jobs.",
    quick: true,
  },
  {
    id: "soc-g4-32",
    subject: "social",
    grade: "4",
    standard: "4.G.1.1",
    skill: "NC regions",
    prompt: "Which NC region lies between the Coastal Plain and the Mountains?",
    choices: ["Piedmont", "Outer Banks", "Tidewater", "Blue Ridge"],
    answer: 0,
    explanation: "The Piedmont is NC's middle region. Its name means 'foot of the mountain.'",
    quick: true,
  },
  {
    id: "soc-g4-33",
    subject: "social",
    grade: "4",
    standard: "4.G.1.1",
    skill: "NC regions",
    prompt: "At the Fall Line, rivers drop from the Piedmont down to the...",
    choices: ["Coastal Plain", "Mountains", "Blue Ridge", "Outer Banks"],
    answer: 0,
    explanation: "Waterfalls and rapids at the Fall Line powered early mills.",
    quick: true,
  },
  {
    id: "soc-g4-34",
    subject: "social",
    grade: "4",
    standard: "4.G.1.1",
    skill: "NC regions",
    prompt: "Pamlico Sound lies between NC's mainland and the...",
    choices: ["Outer Banks", "Blue Ridge", "Piedmont", "Sandhills"],
    answer: 0,
    explanation: "Pamlico Sound is a large, shallow body of water behind the Outer Banks.",
    quick: true,
  },
  {
    id: "soc-g4-35",
    subject: "social",
    grade: "4",
    standard: "4.G.1.3",
    skill: "Modifying the environment",
    prompt: "Building Fontana Dam in the 1940s made a lake and...",
    choices: ["Electricity", "Gold", "Snow", "Oil"],
    answer: 0,
    explanation: "Fontana Dam was built in 1942–1944 to make electricity during World War II.",
    quick: true,
  },
  {
    id: "soc-g4-36",
    subject: "social",
    grade: "4",
    standard: "4.G.1.2",
    skill: "Movement in NC",
    passage:
      "Interstate 40 runs east to west from Wilmington through Raleigh, Greensboro and Winston-Salem to Asheville. Interstate 85 runs from Charlotte northeast through Greensboro toward Virginia.",
    prompt: "Which city is on both interstates?",
    choices: ["Greensboro", "Wilmington", "Asheville", "Charlotte"],
    answer: 0,
    explanation: "Greensboro is on I-40 and I-85, which is one reason it grew as a transportation center.",
  },
  {
    id: "soc-g4-37",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.1",
    skill: "State leaders",
    prompt: "How long is the NC governor's term?",
    choices: ["4 years", "2 years", "6 years", "Life"],
    answer: 0,
    explanation: "NC's governor serves a four-year term and can serve two terms in a row.",
    quick: true,
  },
  {
    id: "soc-g4-38",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.1",
    skill: "State leaders",
    prompt: "Who presides over the NC Senate?",
    choices: ["Lt. Governor", "Governor", "Chief Justice", "Mayor"],
    answer: 0,
    explanation: "The lieutenant governor is the president of the NC Senate.",
    quick: true,
  },
  {
    id: "soc-g4-39",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.3",
    skill: "NC Constitution",
    prompt: "The NC Constitution says people have a right to the privilege of...",
    choices: ["Education", "A job", "A house", "A car"],
    answer: 0,
    explanation: "Article I says the people have a right to education, and the state must guard and maintain it.",
    quick: true,
  },
  {
    id: "soc-g4-40",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.3",
    skill: "Rights and responsibilities",
    prompt: "Which is a responsibility of NC citizens, not just a right?",
    choices: ["Obeying laws", "Free speech", "Worship freely", "Own property"],
    answer: 0,
    explanation: "Rights are freedoms we have. Responsibilities, like obeying laws, are things we should do.",
    quick: true,
  },
  {
    id: "soc-g4-41",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.2",
    skill: "Groups in government",
    passage:
      "In 1968, Henry Frye became the first Black person elected to the NC General Assembly in the 1900s. In 2001, he became the first Black Chief Justice of the NC Supreme Court.",
    prompt: "How did Henry Frye influence state government?",
    choices: ["He served as a lawmaker and as the state's top judge", "He was NC's first governor", "He founded the city of Raleigh", "He wrote the U.S. Constitution"],
    answer: 0,
    explanation: "Henry Frye helped make NC government more representative as a lawmaker and later as Chief Justice.",
  },
  {
    id: "soc-g4-42",
    subject: "social",
    grade: "4",
    standard: "4.C&G.1.2",
    skill: "Groups in government",
    prompt: "The Eastern Band of Cherokee elects a principal chief and a tribal...",
    choices: ["Council", "King", "Pharaoh", "Emperor"],
    answer: 0,
    explanation: "The Eastern Band governs itself with an elected principal chief and Tribal Council.",
    quick: true,
  },
  {
    id: "soc-g4-43",
    subject: "social",
    grade: "4",
    standard: "4.E.1.2",
    skill: "NC industries",
    prompt: "Why did many NC textile mills close in the late 1900s?",
    choices: ["Companies moved work to countries with lower costs", "Cotton disappeared from the world", "People stopped wearing clothes", "Storms destroyed every mill"],
    answer: 0,
    explanation: "Cheaper labor overseas and new trade rules led many textile companies to close NC mills.",
  },
  {
    id: "soc-g4-44",
    subject: "social",
    grade: "4",
    standard: "4.E.1.2",
    skill: "NC industries",
    prompt: "Which industry grew around the Research Triangle in the late 1900s?",
    choices: ["Technology", "Fur trading", "Whaling", "Gold mining"],
    answer: 0,
    explanation: "Universities and Research Triangle Park drew technology and medical research companies.",
    quick: true,
  },
  {
    id: "soc-g4-45",
    subject: "social",
    grade: "4",
    standard: "4.E.1.2",
    skill: "NC industries",
    prompt: "The first U.S. gold rush began in 1799 in...",
    choices: ["North Carolina", "California", "Alaska", "Colorado"],
    answer: 0,
    explanation: "Conrad Reed found a gold nugget on his family's Cabarrus County farm, starting America's first gold rush.",
    quick: true,
  },
  {
    id: "soc-g4-46",
    subject: "social",
    grade: "4",
    standard: "4.E.1.3",
    skill: "Factors of production",
    prompt: "Land, workers, tools and business owners are the factors of...",
    choices: ["Production", "Weather", "Voting", "History"],
    answer: 0,
    explanation: "Land, labor, capital and entrepreneurs are the four factors of production.",
    quick: true,
  },
  {
    id: "soc-g4-47",
    subject: "social",
    grade: "4",
    standard: "4.B.1.2",
    skill: "Cultural groups",
    prompt: "In 1766, Moravians founded Salem, NC. Moravians were a ___ group.",
    choices: ["Religious", "Sports", "Military", "Pirate"],
    answer: 0,
    explanation: "The Moravians were a Protestant church group known for music, crafts and schools.",
    quick: true,
  },
  {
    id: "soc-g4-48",
    subject: "social",
    grade: "4",
    standard: "4.B.1.2",
    skill: "Cultural groups",
    prompt: "Scottish Highlanders settled mostly along which NC river?",
    choices: ["Cape Fear", "Yadkin", "French Broad", "Catawba"],
    answer: 0,
    explanation: "Many Highland Scots settled along the upper Cape Fear River near present-day Fayetteville.",
    quick: true,
  },
];

export default questions;
