import type { Question } from "../../types";
// Grade 9 social studies — NC Standard Course of Study for Social Studies (adopted 2021). World History (1200 CE to present): Mongols, plague, revolutions, imperialism,
// world wars and the Cold War (WH.H.1); Renaissance and Reformation (WH.B.1); government, rights and revolution (WH.C&G.1); trade and industry (WH.E.1); movement and borders (WH.G.1).
const questions: Question[] = [
  {
    id: "soc-g9-01",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Mongol Empire",
    prompt: "The Mongol Empire was founded in the early 1200s by...",
    choices: ["Genghis Khan", "Kublai Khan", "Suleiman", "Akbar"],
    answer: 0,
    explanation: "Genghis Khan united the Mongols in 1206. His grandson Kublai Khan later ruled China.",
    quick: true,
  },
  {
    id: "soc-g9-02",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Trade networks",
    prompt: "Mongol rule made travel safer along the...",
    choices: ["Silk Road", "Erie Canal", "Suez Canal", "Panama Canal"],
    answer: 0,
    explanation: "The 'Pax Mongolica' protected merchants, so trade and ideas flowed across Eurasia.",
    quick: true,
  },
  {
    id: "soc-g9-03",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Black Death",
    prompt: "The Black Death swept across Europe in the...",
    choices: ["1340s", "1540s", "1740s", "1940s"],
    answer: 0,
    explanation: "The plague killed perhaps a third of Europe's people between 1347 and 1351.",
    quick: true,
  },
  {
    id: "soc-g9-04",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Renaissance",
    prompt: "The Renaissance began in the city-states of...",
    choices: ["Italy", "Sweden", "Russia", "Portugal"],
    answer: 0,
    explanation: "Wealthy Italian cities like Florence funded artists and scholars who revived classical learning.",
    quick: true,
  },
  {
    id: "soc-g9-05",
    subject: "social",
    grade: "9",
    standard: "WH.B.1",
    skill: "Reformation",
    prompt: "Martin Luther's 95 Theses (1517) sparked the...",
    choices: ["Reformation", "Renaissance", "Crusades", "Enlightenment"],
    answer: 0,
    explanation: "Luther challenged Church practices, leading to Protestant churches.",
    quick: true,
  },
  {
    id: "soc-g9-06",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Enlightenment",
    prompt: "John Locke argued people have natural rights to life, liberty and...",
    choices: ["Property", "Taxes", "Kings", "Land grants"],
    answer: 0,
    explanation: "Locke's ideas about natural rights influenced the Declaration of Independence.",
    quick: true,
  },
  {
    id: "soc-g9-07",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Mercantilism",
    prompt: "Under mercantilism, colonies mainly served to enrich their...",
    choices: ["Home country", "Neighbors", "Native rulers", "Pirates"],
    answer: 0,
    explanation: "Mercantilism said colonies should supply raw materials and buy goods from the ruling country.",
    quick: true,
  },
  {
    id: "soc-g9-08",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Atlantic slave trade",
    prompt: "The Atlantic slave trade forcibly carried millions of Africans to...",
    choices: ["The Americas", "Australia", "Siberia", "Japan"],
    answer: 0,
    explanation: "About 12.5 million Africans were forced onto ships to the Americas from the 1500s to the 1800s.",
    quick: true,
  },
  {
    id: "soc-g9-09",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Revolutions",
    prompt: "A leader of the Haitian Revolution (1791–1804) was...",
    choices: ["Toussaint", "Bolívar", "Napoleon", "Garibaldi"],
    answer: 0,
    explanation: "Toussaint L'Ouverture helped lead the revolt of enslaved people that created independent Haiti.",
    quick: true,
  },
  {
    id: "soc-g9-10",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Industrial Revolution",
    prompt: "Early Industrial Revolution factories were powered by water and...",
    choices: ["Steam", "Electricity", "Oil", "Solar"],
    answer: 0,
    explanation: "Water wheels and then coal-fired steam engines powered the first factories.",
    quick: true,
  },
  {
    id: "soc-g9-11",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Imperialism",
    prompt: "The 1884–85 Berlin Conference set rules for dividing Africa among...",
    choices: ["Europeans", "Africans", "Americans", "Chinese"],
    answer: 0,
    explanation: "European powers claimed African land without African input, drawing many of today's borders.",
    quick: true,
  },
  {
    id: "soc-g9-12",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Independence movements",
    prompt: "Gandhi led India's nonviolent movement for independence from...",
    choices: ["Britain", "France", "Japan", "Portugal"],
    answer: 0,
    explanation: "India gained independence from Britain in 1947.",
    quick: true,
  },
  {
    id: "soc-g9-13",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Human rights",
    prompt: "The Universal Declaration of Human Rights (1948) was adopted by the...",
    choices: ["United Nations", "NATO", "EU", "Warsaw Pact"],
    answer: 0,
    explanation: "The UN General Assembly adopted it after World War II.",
    quick: true,
  },
  {
    id: "soc-g9-14",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Cold War",
    prompt: "The Cold War ended as the Soviet Union dissolved in...",
    choices: ["1991", "1945", "1962", "1975"],
    answer: 0,
    explanation: "The USSR broke into 15 countries in December 1991.",
    quick: true,
  },
  {
    id: "soc-g9-15",
    subject: "social",
    grade: "9",
    standard: "WH.G.1",
    skill: "Trade routes",
    prompt: "Which 1869 canal shortened the sea route from Europe to Asia?",
    choices: ["Suez Canal", "Panama Canal", "Erie Canal", "Grand Canal"],
    answer: 0,
    explanation: "The Suez Canal links the Mediterranean and Red Seas, so ships no longer had to sail around Africa.",
    quick: true,
  },
  {
    id: "soc-g9-16",
    subject: "social",
    grade: "9",
    standard: "WH.C&G.1",
    skill: "Rule of law",
    passage:
      "In 1215, English barons forced King John to accept Magna Carta. It said the king could not take free men's property or jail them without lawful judgment, and he could not raise certain taxes without the barons' consent.",
    prompt: "What principle does this event best show?",
    choices: ["Rulers must obey the law too", "Kings have unlimited power", "Barons should rule England", "Taxes are always illegal"],
    answer: 0,
    explanation: "Magna Carta is an early example of limiting a ruler's power by law.",
  },
  {
    id: "soc-g9-17",
    subject: "social",
    grade: "9",
    standard: "WH.H.1",
    skill: "Columbian Exchange",
    passage:
      "Historians estimate that central Mexico's Indigenous population fell by up to 90 percent in the century after Spanish arrival in 1519. Epidemics of smallpox, measles and other illnesses swept through towns.",
    prompt: "What best explains the population decline?",
    choices: ["Diseases like smallpox from Europe", "Moving to Europe", "A long drought only", "Better farming"],
    answer: 0,
    explanation: "Indigenous peoples had no immunity to Old World diseases, which caused catastrophic death.",
  },
  {
    id: "soc-g9-18",
    subject: "social",
    grade: "9",
    standard: "WH.E.1",
    skill: "Industrial Revolution",
    passage:
      "A British parliament report from 1832 recorded a mill worker saying she began work at age 6, worked from 5 a.m. to 9 p.m., and was beaten when she fell behind.",
    prompt: "Which conclusion is best supported by the source?",
    choices: ["Factory work was long and dangerous for children", "Children rarely worked in factories", "Factories paid children very high wages", "Laws stopped child labor by 1800"],
    answer: 0,
    explanation: "Testimony like this led Britain to pass Factory Acts limiting child labor, starting in 1833.",
  },
];

export default questions;
