import type { Question } from "../../types";

// Grade 3 ELA — NC Standard Course of Study for ELA (2017). L.3.1, L.3.2, L.3.4 (context clues, affixes), L.3.5 (nonliteral), RL.3.2, RL.3.3, RL.3.5, RL.3.6, RI.3.2, RI.3.5, RI.3.8
const questions: Question[] = [
  {
    id: "ela-g3-01",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does the prefix re- mean in reread?",
    choices: ["again", "not", "before", "under"],
    answer: 0,
    explanation: "Re- means again, so reread means read again.",
    quick: true,
  },
  {
    id: "ela-g3-02",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does careless mean?",
    choices: ["without care", "full of care", "cares again", "before care"],
    answer: 0,
    explanation: "The suffix -less means without, so careless means without care.",
    quick: true,
  },
  {
    id: "ela-g3-03",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does helpful mean?",
    choices: ["full of help", "without help", "help again", "not help"],
    answer: 0,
    explanation: "The suffix -ful means full of, so helpful means full of help.",
    quick: true,
  },
  {
    id: "ela-g3-04",
    subject: "ela",
    grade: "3",
    standard: "L.3.5",
    skill: "Literal and nonliteral",
    prompt: "What does 'It's raining cats and dogs' mean?",
    choices: ["It's pouring", "Pets are out", "It's sunny", "It's snowing"],
    answer: 0,
    explanation: "This is an idiom. It means it is raining very hard, not that animals are falling.",
    quick: true,
  },
  {
    id: "ela-g3-05",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Comparatives",
    prompt: "My dog is ___ than your dog. Which word fits?",
    choices: ["bigger", "biggest", "more big", "big"],
    answer: 0,
    explanation: "Use -er to compare two things: bigger. Use -est for three or more.",
    quick: true,
  },
  {
    id: "ela-g3-06",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Irregular verbs",
    prompt: "What is the past tense of bring?",
    choices: ["brought", "bringed", "brang", "brung"],
    answer: 0,
    explanation: "Bring is irregular: today I bring, yesterday I brought.",
    quick: true,
  },
  {
    id: "ela-g3-07",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Subject-verb agreement",
    prompt: "Which sentence is correct?",
    choices: ["She runs fast.", "She run fast.", "She running.", "She are fast."],
    answer: 0,
    explanation: "A singular subject like she needs a verb with -s: She runs.",
    quick: true,
  },
  {
    id: "ela-g3-08",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Abstract nouns",
    prompt: "Which is an abstract noun (a feeling or idea)?",
    choices: ["bravery", "table", "river", "pencil"],
    answer: 0,
    explanation: "You cannot touch bravery. It is an idea, so it is an abstract noun.",
    quick: true,
  },
  {
    id: "ela-g3-09",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Possessives",
    prompt: "How do you show a toy belongs to more than one girl?",
    choices: ["girls' toy", "girl's toy", "girls toy", "girls's toy"],
    answer: 0,
    explanation: "For a plural noun ending in s, add only an apostrophe: girls'.",
    quick: true,
  },
  {
    id: "ela-g3-10",
    subject: "ela",
    grade: "3",
    standard: "RL.3.5",
    skill: "Parts of a poem",
    prompt: "What do we call a group of lines in a poem?",
    choices: ["stanza", "chapter", "scene", "paragraph"],
    answer: 0,
    explanation: "Poems are built from stanzas, like stories are built from paragraphs.",
    quick: true,
  },
  {
    id: "ela-g3-11",
    subject: "ela",
    grade: "3",
    standard: "RL.3.6",
    skill: "Point of view",
    prompt: "A story told with I and me is told in...",
    choices: ["first person", "third person", "second person", "the reader's"],
    answer: 0,
    explanation: "When the narrator says I and me, the story is in first person.",
    quick: true,
  },
  {
    id: "ela-g3-12",
    subject: "ela",
    grade: "3",
    standard: "RI.3.5",
    skill: "Text features",
    prompt: "Which feature tells what a section of text is about?",
    choices: ["heading", "caption", "index", "glossary"],
    answer: 0,
    explanation: "A heading is a title for a section. It tells what that part is about.",
    quick: true,
  },
  {
    id: "ela-g3-13",
    subject: "ela",
    grade: "3",
    standard: "RI.3.5",
    skill: "Text features",
    prompt: "Where would you look to find which page is about volcanoes?",
    choices: ["index", "glossary", "title", "caption"],
    answer: 0,
    explanation: "An index lists topics in ABC order with their page numbers.",
    quick: true,
  },
  {
    id: "ela-g3-14",
    subject: "ela",
    grade: "3",
    standard: "RL.3.2",
    skill: "Central message",
    prompt: "The big idea a fable wants you to learn is its...",
    choices: ["lesson", "setting", "title", "character"],
    answer: 0,
    explanation: "A fable's lesson, or moral, is its central message.",
    quick: true,
  },
  {
    id: "ela-g3-15",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Context clues",
    prompt: "What does fragile most likely mean?",
    passage: "The old bridge was fragile. When Leo stepped on the first board, it cracked, and a piece fell into the creek below. He decided to walk the long way around.",
    choices: ["easily broken", "very long", "brand new", "painted brightly"],
    answer: 0,
    explanation: "The board cracked and fell, which is a clue that fragile means easily broken.",
  },
  {
    id: "ela-g3-16",
    subject: "ela",
    grade: "3",
    standard: "RI.3.2",
    skill: "Main idea",
    prompt: "What is the main idea of this text?",
    passage: "Honeybees work as a team. Some bees gather nectar from flowers. Others guard the hive from enemies. Young bees clean the cells and feed the babies. Every bee has a job that helps the whole hive survive.",
    choices: ["Honeybees work together in jobs.", "Bees gather nectar.", "Bees have enemies.", "Hives are made of wax."],
    answer: 0,
    explanation: "Each detail names a job, and the last sentence sums up the main idea.",
  },
  {
    id: "ela-g3-17",
    subject: "ela",
    grade: "3",
    standard: "RL.3.3",
    skill: "Character traits",
    prompt: "Which word best describes Marcus?",
    passage: "When the new girl, Ana, sat alone at lunch, Marcus picked up his tray and sat beside her. He asked her about her old school and shared his cookies. By the end of lunch, Ana was laughing.",
    choices: ["kind", "shy", "bossy", "sleepy"],
    answer: 0,
    explanation: "Marcus sits with Ana and shares his cookies. His actions show he is kind.",
  },
  {
    id: "ela-g3-18",
    subject: "ela",
    grade: "3",
    standard: "RI.3.8",
    skill: "Cause and effect",
    prompt: "Why did the frogs move to the creek?",
    passage: "Last spring, it did not rain for six weeks. The pond behind the farm got smaller and smaller. The frogs that lived there moved to the creek, where there was still water.",
    choices: ["The pond was drying up.", "The creek was too cold.", "A farmer chased them.", "They wanted to eat fish."],
    answer: 0,
    explanation: "No rain made the pond shrink (cause), so the frogs moved (effect).",
  },
];

export default questions;
