import type { Question } from "../../types";

// Grade K ELA — NC Standard Course of Study for ELA (2017). RL.K.2, RL.K.3, RL.K.5, RL.K.6, RI.K.2, RI.K.5, RF.K.1, RF.K.3, RF.K.4, L.K.1, L.K.2, L.K.4, L.K.5
const questions: Question[] = [
  {
    id: "ela-gK-01",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with cat?",
    choices: ["hat", "dog", "cup", "sun"],
    answer: 0,
    explanation: "Cat and hat both end with the -at sound, so they rhyme.",
    quick: true,
  },
  {
    id: "ela-gK-02",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with bug?",
    choices: ["rug", "bed", "cap", "fox"],
    answer: 0,
    explanation: "Bug and rug both end with -ug. Rhyming words sound the same at the end.",
    quick: true,
  },
  {
    id: "ela-gK-03",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with pig?",
    choices: ["wig", "pan", "top", "sit"],
    answer: 0,
    explanation: "Pig and wig both end with -ig, so they rhyme.",
    quick: true,
  },
  {
    id: "ela-gK-04",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Beginning sounds",
    prompt: "Which word starts with the same sound as ball?",
    choices: ["bat", "cat", "sun", "map"],
    answer: 0,
    explanation: "Ball and bat both start with the /b/ sound.",
    quick: true,
  },
  {
    id: "ela-gK-05",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Beginning sounds",
    prompt: "Which word starts with the /s/ sound?",
    choices: ["sock", "fish", "moon", "tree"],
    answer: 0,
    explanation: "Sock starts with /s/, like snake and sun.",
    quick: true,
  },
  {
    id: "ela-gK-06",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Syllables",
    prompt: "Clap it out! How many syllables are in rabbit?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "Rab-bit has two claps, so it has two syllables.",
    quick: true,
  },
  {
    id: "ela-gK-07",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Ending sounds",
    prompt: "Which word ends with the /t/ sound?",
    choices: ["hat", "dog", "bus", "cup"],
    answer: 0,
    explanation: "Hat ends with /t/. Say it slowly: h-a-t.",
    quick: true,
  },
  {
    id: "ela-gK-08",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Middle sounds",
    prompt: "What is the middle sound in sun?",
    choices: ["/u/", "/s/", "/n/", "/a/"],
    answer: 0,
    explanation: "Sun is s-u-n. The sound in the middle is the short u, /u/.",
    quick: true,
  },
  {
    id: "ela-gK-09",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Letter sounds",
    prompt: "Which letter makes the first sound in fan?",
    choices: ["F", "V", "P", "T"],
    answer: 0,
    explanation: "Fan starts with /f/, and the letter F makes that sound.",
    quick: true,
  },
  {
    id: "ela-gK-10",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Sight words",
    prompt: "Which word says 'the'?",
    choices: ["the", "then", "they", "tea"],
    answer: 0,
    explanation: "T-h-e spells the. It is a sight word we see in almost every book.",
    quick: true,
  },
  {
    id: "ela-gK-11",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Short vowels",
    prompt: "Change the a in cat to u. What new word do you get?",
    choices: ["cut", "cot", "kit", "cap"],
    answer: 0,
    explanation: "C-a-t becomes c-u-t. Changing the middle vowel makes a new word.",
    quick: true,
  },
  {
    id: "ela-gK-12",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Print concepts",
    prompt: "Which way do we read words in English?",
    choices: ["Left to right", "Right to left", "Bottom to top", "Any way"],
    answer: 0,
    explanation: "In English we read from left to right, then go down to the next line.",
    quick: true,
  },
  {
    id: "ela-gK-13",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Print concepts",
    prompt: "What goes between words in a sentence?",
    choices: ["Spaces", "Pictures", "Numbers", "Colors"],
    answer: 0,
    explanation: "Spaces show where one word ends and the next word begins.",
    quick: true,
  },
  {
    id: "ela-gK-14",
    subject: "ela",
    grade: "K",
    standard: "L.K.1",
    skill: "Plurals",
    prompt: "Which word means more than one dog?",
    choices: ["dogs", "dog", "dug", "dig"],
    answer: 0,
    explanation: "Adding -s to dog makes dogs, which means more than one.",
    quick: true,
  },
  {
    id: "ela-gK-15",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Opposites",
    prompt: "What is the opposite of hot?",
    choices: ["cold", "warm", "big", "fast"],
    answer: 0,
    explanation: "Cold is the opposite of hot. Warm is only a little bit hot.",
    quick: true,
  },
  {
    id: "ela-gK-16",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Sorting words",
    prompt: "Which one is a fruit?",
    choices: ["apple", "carrot", "bread", "milk"],
    answer: 0,
    explanation: "An apple is a fruit. A carrot is a vegetable.",
    quick: true,
  },
  {
    id: "ela-gK-17",
    subject: "ela",
    grade: "K",
    standard: "RL.K.3",
    skill: "Story elements",
    prompt: "Where and when a story happens is called the...",
    choices: ["setting", "character", "title", "author"],
    answer: 0,
    explanation: "The setting tells where and when a story takes place.",
    quick: true,
  },
  {
    id: "ela-gK-18",
    subject: "ela",
    grade: "K",
    standard: "RL.K.6",
    skill: "Author and illustrator",
    prompt: "Who writes the words in a book?",
    choices: ["author", "illustrator", "reader", "teacher"],
    answer: 0,
    explanation: "The author writes the words. The illustrator draws the pictures.",
    quick: true,
  },
  {
    id: "ela-gK-19",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with man?",
    choices: ["fan", "mop", "sit", "bed"],
    answer: 0,
    explanation: "Man and fan both end with the -an sound, so they rhyme.",
    quick: true,
  },
  {
    id: "ela-gK-20",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Syllables",
    prompt: "Clap it out! How many syllables are in butterfly?",
    choices: ["3", "2", "4", "1"],
    answer: 0,
    explanation: "But-ter-fly has three claps, so it has three syllables.",
    quick: true,
  },
  {
    id: "ela-gK-21",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Onset and rime",
    prompt: "Put together /m/ and -op. What word do you get?",
    choices: ["mop", "top", "map", "hop"],
    answer: 0,
    explanation: "The /m/ sound plus -op makes mop.",
    quick: true,
  },
  {
    id: "ela-gK-22",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Blending syllables",
    prompt: "Put these parts together: pan... cake. What word is it?",
    choices: ["pancake", "cupcake", "panda", "teacake"],
    answer: 0,
    explanation: "Pan and cake go together to make pancake.",
    quick: true,
  },
  {
    id: "ela-gK-23",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Beginning sounds",
    prompt: "Which word starts with the same sound as moon?",
    choices: ["milk", "nose", "sun", "ball"],
    answer: 0,
    explanation: "Moon and milk both start with the /m/ sound.",
    quick: true,
  },
  {
    id: "ela-gK-24",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Ending sounds",
    prompt: "Which word ends with the same sound as bus?",
    choices: ["yes", "bun", "cup", "bat"],
    answer: 0,
    explanation: "Bus and yes both end with the /s/ sound.",
    quick: true,
  },
  {
    id: "ela-gK-25",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Middle sounds",
    prompt: "What is the middle sound in pig?",
    choices: ["/i/", "/p/", "/g/", "/e/"],
    answer: 0,
    explanation: "Pig is p-i-g. The sound in the middle is the short i, /i/.",
    quick: true,
  },
  {
    id: "ela-gK-26",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Changing sounds",
    prompt: "Say mat. Change /m/ to /s/. What word is it now?",
    choices: ["sat", "mad", "sit", "fat"],
    answer: 0,
    explanation: "When /m/ becomes /s/, mat turns into sat.",
    quick: true,
  },
  {
    id: "ela-gK-27",
    subject: "ela",
    grade: "K",
    standard: "RF.K.3",
    skill: "Adding sounds",
    prompt: "Say at. Add /h/ to the start. What word is it now?",
    choices: ["hat", "cat", "ham", "ant"],
    answer: 0,
    explanation: "Putting /h/ in front of at makes hat.",
    quick: true,
  },
  {
    id: "ela-gK-28",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Letter sounds",
    prompt: "Which letter makes the /d/ sound, like in dog?",
    choices: ["D", "B", "P", "T"],
    answer: 0,
    explanation: "The letter D makes the /d/ sound you hear at the start of dog.",
    quick: true,
  },
  {
    id: "ela-gK-29",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Letter sounds",
    prompt: "Which word starts with the letter M?",
    choices: ["mitten", "nest", "wagon", "apple"],
    answer: 0,
    explanation: "Mitten starts with /m/, the sound the letter M makes.",
    quick: true,
  },
  {
    id: "ela-gK-30",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Short vowels",
    prompt: "Which word has the short a sound, like in apple?",
    choices: ["bag", "bug", "big", "bed"],
    answer: 0,
    explanation: "Bag has the short a sound, /a/, just like apple.",
    quick: true,
  },
  {
    id: "ela-gK-31",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Long vowels",
    prompt: "Which word has the long o sound, like in boat?",
    choices: ["rope", "rock", "rub", "rip"],
    answer: 0,
    explanation: "In rope, the o says its name, just like in boat.",
    quick: true,
  },
  {
    id: "ela-gK-32",
    subject: "ela",
    grade: "K",
    standard: "RF.K.4",
    skill: "Sight words",
    prompt: "Which word says 'is'?",
    choices: ["is", "it", "in", "if"],
    answer: 0,
    explanation: "I-s spells is. It is a sight word we see in lots of books.",
    quick: true,
  },
  {
    id: "ela-gK-33",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Upper- and lowercase",
    prompt: "Which is the uppercase (big) letter for b?",
    choices: ["B", "D", "P", "R"],
    answer: 0,
    explanation: "Big B and little b are the same letter.",
    quick: true,
  },
  {
    id: "ela-gK-34",
    subject: "ela",
    grade: "K",
    standard: "RF.K.1",
    skill: "Counting words",
    prompt: "How many words are in 'I see a cat'?",
    choices: ["4", "3", "5", "2"],
    answer: 0,
    explanation: "I - see - a - cat. Count them: four words.",
    quick: true,
  },
  {
    id: "ela-gK-35",
    subject: "ela",
    grade: "K",
    standard: "L.K.1",
    skill: "Plurals",
    prompt: "Which word means more than one box?",
    choices: ["boxes", "box", "fox", "socks"],
    answer: 0,
    explanation: "We add -es to box to make boxes, which means more than one.",
    quick: true,
  },
  {
    id: "ela-gK-36",
    subject: "ela",
    grade: "K",
    standard: "L.K.1",
    skill: "Question words",
    prompt: "Which question word asks about a place?",
    choices: ["Where", "Who", "When", "What"],
    answer: 0,
    explanation: "Where asks about a place, like 'Where is my hat?'",
    quick: true,
  },
  {
    id: "ela-gK-37",
    subject: "ela",
    grade: "K",
    standard: "L.K.2",
    skill: "Capital I",
    prompt: "When you write the word I by itself, it is always a...",
    choices: ["capital letter", "small letter", "number", "period"],
    answer: 0,
    explanation: "The word I is always a capital letter, even in the middle of a sentence.",
    quick: true,
  },
  {
    id: "ela-gK-38",
    subject: "ela",
    grade: "K",
    standard: "L.K.2",
    skill: "End marks",
    prompt: "What mark goes at the end of a telling sentence?",
    choices: ["period", "question mark", "comma", "dash"],
    answer: 0,
    explanation: "A telling sentence ends with a period.",
    quick: true,
  },
  {
    id: "ela-gK-39",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Opposites",
    prompt: "What is the opposite of up?",
    choices: ["down", "top", "over", "in"],
    answer: 0,
    explanation: "Down is the opposite of up.",
    quick: true,
  },
  {
    id: "ela-gK-40",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Sorting words",
    prompt: "Which one is an animal?",
    choices: ["horse", "chair", "apple", "shoe"],
    answer: 0,
    explanation: "A horse is an animal. A chair, an apple, and a shoe are things.",
    quick: true,
  },
  {
    id: "ela-gK-41",
    subject: "ela",
    grade: "K",
    standard: "L.K.5",
    skill: "Shades of meaning",
    prompt: "Which is the fastest way to move?",
    choices: ["run", "walk", "tiptoe", "crawl"],
    answer: 0,
    explanation: "Running is faster than walking, tiptoeing, or crawling.",
    quick: true,
  },
  {
    id: "ela-gK-42",
    subject: "ela",
    grade: "K",
    standard: "L.K.4",
    skill: "Word meanings",
    prompt: "A puppy is a baby...",
    choices: ["dog", "cat", "cow", "duck"],
    answer: 0,
    explanation: "A puppy grows up to be a dog.",
    quick: true,
  },
  {
    id: "ela-gK-43",
    subject: "ela",
    grade: "K",
    standard: "RI.K.5",
    skill: "Parts of a book",
    prompt: "The outside of a book that you see first is the...",
    choices: ["front cover", "back cover", "title page", "last page"],
    answer: 0,
    explanation: "The front cover is on the outside. It shows the title and often a picture.",
    quick: true,
  },
  {
    id: "ela-gK-44",
    subject: "ela",
    grade: "K",
    standard: "RL.K.5",
    skill: "Types of texts",
    prompt: "Which kind of text often has lines that rhyme?",
    choices: ["poem", "recipe", "map", "list"],
    answer: 0,
    explanation: "Poems often have rhyming words at the ends of lines.",
    quick: true,
  },
  {
    id: "ela-gK-45",
    subject: "ela",
    grade: "K",
    standard: "RL.K.3",
    skill: "Characters",
    prompt: "Who found the ball?",
    passage: "Max the puppy dug a hole in the yard. He found an old red ball. Max ran to show his friend Lily.",
    choices: ["Max", "Lily", "Mom", "a cat"],
    answer: 0,
    explanation: "The story says Max dug a hole and found the ball.",
  },
  {
    id: "ela-gK-46",
    subject: "ela",
    grade: "K",
    standard: "RL.K.3",
    skill: "Setting",
    prompt: "Where does this story happen?",
    passage: "Ana and her dad built a sand castle by the water. Then a big wave washed it away!",
    choices: ["at the beach", "at school", "at a park", "at home"],
    answer: 0,
    explanation: "The sand, the water, and the wave tell us they are at the beach.",
  },
  {
    id: "ela-gK-47",
    subject: "ela",
    grade: "K",
    standard: "RL.K.2",
    skill: "Retelling",
    prompt: "What happened last?",
    passage: "First, Ben planted a seed. Next, he watered it. Last, a tall sunflower grew.",
    choices: ["A sunflower grew.", "Ben planted a seed.", "Ben watered it.", "Ben picked a rose."],
    answer: 0,
    explanation: "The word last tells us the sunflower growing came at the end.",
  },
  {
    id: "ela-gK-48",
    subject: "ela",
    grade: "K",
    standard: "RI.K.2",
    skill: "Main topic",
    prompt: "What is this mostly about?",
    passage: "Frogs can jump far. Frogs can swim. Frogs catch bugs with their long, sticky tongues.",
    choices: ["frogs", "bugs", "swimming", "ponds"],
    answer: 0,
    explanation: "Every sentence tells something about frogs.",
  },
];

export default questions;
