import type { Question } from "../../types";
// Grade 6 social studies — NC Standard Course of Study for Social Studies (adopted 2021). World history and geography, Paleolithic era to 1400 CE: early farming, writing and
// empires (6.H.1); river valleys and regions (6.G.1); law codes, democracy and republics (6.C&G.1); trade routes (6.E.1.1); religions and belief systems (6.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g6-01",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Early farming",
    prompt: "When people began farming, many started to...",
    choices: ["Build villages", "Hunt mammoths", "Use no tools", "Move daily"],
    answer: 0,
    explanation: "Farming meant people could stay in one place, so they built permanent villages.",
    quick: true,
  },
  {
    id: "soc-g6-02",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    prompt: "Ancient Egypt grew along which river?",
    choices: ["Nile", "Amazon", "Tigris", "Yangtze"],
    answer: 0,
    explanation: "The Nile gave Egyptians water, rich soil and a path for boats.",
    quick: true,
  },
  {
    id: "soc-g6-03",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    prompt: "Mesopotamia lay between the Tigris and...",
    choices: ["Euphrates", "Nile", "Indus", "Huang He"],
    answer: 0,
    explanation: "Mesopotamia means 'land between rivers': the Tigris and Euphrates.",
    quick: true,
  },
  {
    id: "soc-g6-04",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Writing",
    prompt: "Cuneiform, one of the first writing systems, came from...",
    choices: ["Sumer", "Rome", "China", "The Maya"],
    answer: 0,
    explanation: "Sumerians pressed wedge-shaped marks into clay tablets over 5,000 years ago.",
    quick: true,
  },
  {
    id: "soc-g6-05",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Law codes",
    prompt: "Hammurabi's Code is famous as an early written set of...",
    choices: ["Laws", "Recipes", "Songs", "Maps"],
    answer: 0,
    explanation: "Babylon's King Hammurabi had about 282 laws carved in stone so people could know the rules.",
    quick: true,
  },
  {
    id: "soc-g6-06",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Democracy",
    prompt: "Ancient Athens is known as the birthplace of...",
    choices: ["Democracy", "Monarchy", "Feudalism", "Communism"],
    answer: 0,
    explanation: "In Athens, male citizens voted directly on laws, an early form of democracy.",
    quick: true,
  },
  {
    id: "soc-g6-07",
    subject: "social",
    grade: "6",
    standard: "6.C&G.1",
    skill: "Roman Republic",
    prompt: "In the Roman Republic, citizens elected two leaders each year called...",
    choices: ["Consuls", "Pharaohs", "Emperors", "Shoguns"],
    answer: 0,
    explanation: "Two consuls ran the Roman Republic for one-year terms, so no single person held power too long.",
    quick: true,
  },
  {
    id: "soc-g6-08",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade routes",
    prompt: "The Silk Road was a network of trade routes linking China and...",
    choices: ["Europe", "Australia", "The Americas", "Antarctica"],
    answer: 0,
    explanation: "Silk, spices and ideas moved between China, Central Asia, the Middle East and Europe.",
    quick: true,
  },
  {
    id: "soc-g6-09",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade routes",
    prompt: "West African empires like Mali grew rich trading gold and...",
    choices: ["Salt", "Oil", "Coffee", "Tea"],
    answer: 0,
    explanation: "Gold from the south was traded for salt from the Sahara.",
    quick: true,
  },
  {
    id: "soc-g6-10",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "African empires",
    prompt: "Mansa Musa was a famously wealthy ruler of...",
    choices: ["Mali", "Rome", "China", "Persia"],
    answer: 0,
    explanation: "Mansa Musa ruled Mali in the 1300s. His pilgrimage to Mecca showed off Mali's wealth.",
    quick: true,
  },
  {
    id: "soc-g6-11",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Which religion began in ancient India?",
    choices: ["Hinduism", "Islam", "Judaism", "Christianity"],
    answer: 0,
    explanation: "Hinduism developed in South Asia. Buddhism also began in India.",
    quick: true,
  },
  {
    id: "soc-g6-12",
    subject: "social",
    grade: "6",
    standard: "6.B.1.1",
    skill: "Belief systems",
    prompt: "Whose teachings about respect and family shaped ancient China?",
    choices: ["Confucius", "Socrates", "Homer", "Julius Caesar"],
    answer: 0,
    explanation: "Confucius taught respect for elders, family duty and good government.",
    quick: true,
  },
  {
    id: "soc-g6-13",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "Americas",
    prompt: "The Maya civilization was centered in present-day Mexico and...",
    choices: ["Guatemala", "Peru", "Egypt", "China"],
    answer: 0,
    explanation: "Maya cities rose in southern Mexico and Central America, including Guatemala.",
    quick: true,
  },
  {
    id: "soc-g6-14",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Empires",
    prompt: "China's Great Wall was built mainly to keep out...",
    choices: ["Invaders", "Floods", "Tourists", "Earthquakes"],
    answer: 0,
    explanation: "Chinese dynasties built and rebuilt walls to protect against raids from the north.",
    quick: true,
  },
  {
    id: "soc-g6-15",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Empires",
    prompt: "Which empire built aqueducts and the Colosseum?",
    choices: ["Roman", "Persian", "Inca", "Mongol"],
    answer: 0,
    explanation: "Roman engineers built aqueducts, roads and the Colosseum.",
    quick: true,
  },
  {
    id: "soc-g6-16",
    subject: "social",
    grade: "6",
    standard: "6.H.1",
    skill: "Timelines (BCE/CE)",
    passage:
      "Timeline cards: Great Pyramid of Giza built (about 2500 BCE). Roman Republic founded (509 BCE). Qin dynasty unifies China (221 BCE). Western Roman Empire falls (476 CE).",
    prompt: "Which event happened first?",
    choices: ["Pyramids of Giza built", "Qin unifies China", "Roman Republic founded", "Rome falls in the west"],
    answer: 0,
    explanation: "BCE years count down toward year 1, so 2500 BCE is the earliest of these dates.",
  },
  {
    id: "soc-g6-17",
    subject: "social",
    grade: "6",
    standard: "6.G.1",
    skill: "River valleys",
    passage:
      "Each summer the Nile River flooded. When the water went down, it left a layer of dark, wet mud on the land nearby. Beyond this strip, the land was dry desert.",
    prompt: "Why did most Egyptians farm close to the Nile?",
    choices: ["Floods left rich soil for crops", "The desert soil was better", "Rivers kept enemies away", "Kings ordered them to"],
    answer: 0,
    explanation: "The Nile's yearly flood spread fertile silt, making farming possible in a desert land.",
  },
  {
    id: "soc-g6-18",
    subject: "social",
    grade: "6",
    standard: "6.E.1.1",
    skill: "Trade and ideas",
    passage:
      "Buddhism began in India. Monks and merchants traveling the Silk Road carried its teachings. By about 100 CE, Buddhist temples were being built in China.",
    prompt: "What does this show about trade routes?",
    choices: ["They spread ideas as well as goods", "They only moved silk", "They stopped the spread of religion", "They were used only by soldiers"],
    answer: 0,
    explanation: "Merchants carried beliefs, art and inventions along with goods.",
  },
];

export default questions;
