import type { Question } from "../../types";
// Grade 8 social studies — NC Standard Course of Study for Social Studies (adopted 2021). North Carolina and United States history: conflict and cooperation from the Regulators
// to civil rights (8.H.1); location and movement (8.G.1.1); democratic principles and the Constitution (8.C&G.1); farming and industry after the Civil War (8.E.1).
const questions: Question[] = [
  {
    id: "soc-g8-01",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Regulators",
    prompt: "NC's Regulator Movement was backcountry farmers protesting...",
    choices: ["Unfair fees", "Free schools", "Railroads", "Low prices"],
    answer: 0,
    explanation: "Regulators protested corrupt officials, high fees and taxes. Governor Tryon defeated them at Alamance in 1771.",
    quick: true,
  },
  {
    id: "soc-g8-02",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Revolution in NC",
    prompt: "The 1781 Battle of Guilford Courthouse weakened the army of...",
    choices: ["Cornwallis", "Washington", "Lee", "Sherman"],
    answer: 0,
    explanation: "British General Cornwallis won the field but lost many men, helping lead to his surrender at Yorktown.",
    quick: true,
  },
  {
    id: "soc-g8-03",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Ratification",
    prompt: "NC delayed ratifying the Constitution until Congress proposed a...",
    choices: ["Bill of Rights", "King", "New capital", "Navy"],
    answer: 0,
    explanation: "NC refused to ratify the Constitution in 1788, then ratified it in November 1789 after amendments protecting rights were proposed.",
    quick: true,
  },
  {
    id: "soc-g8-04",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Constitution",
    prompt: "The first three words of the U.S. Constitution are...",
    choices: ["We the People", "All men are", "Four score and", "In God We"],
    answer: 0,
    explanation: "'We the People' shows that power comes from the people.",
    quick: true,
  },
  {
    id: "soc-g8-05",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Federalism",
    prompt: "Dividing power between national and state governments is...",
    choices: ["Federalism", "Monarchy", "Anarchy", "Tyranny"],
    answer: 0,
    explanation: "Under federalism, both national and state governments have their own powers.",
    quick: true,
  },
  {
    id: "soc-g8-06",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Sectional conflict",
    prompt: "The Missouri Compromise (1820) tried to settle disputes over...",
    choices: ["Slavery", "Tea", "Railroads", "Gold"],
    answer: 0,
    explanation: "The compromise admitted Missouri as a slave state and Maine as a free state, but tensions kept growing.",
    quick: true,
  },
  {
    id: "soc-g8-07",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil War",
    prompt: "North Carolina left the Union in May 1861 to join the...",
    choices: ["Confederacy", "British", "Mexico", "Union Army"],
    answer: 0,
    explanation: "NC seceded on May 20, 1861, after President Lincoln called for troops.",
    quick: true,
  },
  {
    id: "soc-g8-08",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Reconstruction",
    prompt: "The 13th Amendment (1865)...",
    choices: ["Ended slavery", "Women's vote", "Free speech", "Income tax"],
    answer: 0,
    explanation: "The 13th Amendment abolished slavery throughout the United States.",
    quick: true,
  },
  {
    id: "soc-g8-09",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Wilmington 1898",
    prompt: "In 1898, white supremacist mobs in Wilmington violently overthrew the city's...",
    choices: ["Government", "Governor", "King", "Railroad"],
    answer: 0,
    explanation: "The Wilmington coup forced out an elected, biracial city government and killed many Black residents. It helped bring Jim Crow laws and the loss of Black voting rights across NC.",
    quick: true,
  },
  {
    id: "soc-g8-10",
    subject: "social",
    grade: "8",
    standard: "8.E.1",
    skill: "Sharecropping",
    prompt: "After the Civil War, many landless NC farmers worked as...",
    choices: ["Sharecroppers", "Pilots", "Miners", "Sailors"],
    answer: 0,
    explanation: "Sharecroppers farmed someone else's land and paid with part of the crop, which often kept them in debt.",
    quick: true,
  },
  {
    id: "soc-g8-11",
    subject: "social",
    grade: "8",
    standard: "8.E.1",
    skill: "Industrialization",
    prompt: "In the late 1800s, NC's Piedmont grew with mills making textiles and...",
    choices: ["Cigarettes", "Cars", "Airplanes", "Computers"],
    answer: 0,
    explanation: "Textile mills and tobacco factories, like those of the Duke and Reynolds families, grew in the Piedmont.",
    quick: true,
  },
  {
    id: "soc-g8-12",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Modern NC",
    prompt: "Research Triangle Park (1959) is near Raleigh, Durham and...",
    choices: ["Chapel Hill", "Asheville", "Wilmington", "Boone"],
    answer: 0,
    explanation: "The park is anchored by NC State, Duke and UNC-Chapel Hill, and it drew research jobs to NC.",
    quick: true,
  },
  {
    id: "soc-g8-13",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Civil rights",
    prompt: "The 1960 student sit-ins led to what group being formed at Shaw University?",
    choices: ["SNCC", "NAACP", "UN", "NATO"],
    answer: 0,
    explanation: "Ella Baker helped students form the Student Nonviolent Coordinating Committee in Raleigh in April 1960.",
    quick: true,
  },
  {
    id: "soc-g8-14",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Location",
    prompt: "Why did NC develop few big seaports?",
    choices: ["Shallow inlets", "No rivers", "Too cold", "No trees"],
    answer: 0,
    explanation: "Barrier islands, shifting sandbars and shallow inlets made it hard for big ships to reach NC harbors.",
    quick: true,
  },
  {
    id: "soc-g8-15",
    subject: "social",
    grade: "8",
    standard: "8.C&G.1",
    skill: "Desegregation",
    prompt: "Swann v. Charlotte-Mecklenburg (1971) upheld using busing to...",
    choices: ["Desegregate", "Build roads", "Raise taxes", "End elections"],
    answer: 0,
    explanation: "The Supreme Court ruled that busing could be used to integrate schools.",
    quick: true,
  },
  {
    id: "soc-g8-16",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Revolution in NC",
    passage:
      "On April 12, 1776, North Carolina's Provincial Congress met in Halifax. It told NC's delegates to the Continental Congress to vote with the other colonies for declaring independence from Britain.",
    prompt: "What principle do the Halifax Resolves show?",
    choices: ["Colonists had a right to independence", "The king should rule forever", "NC wanted to leave the other colonies", "Taxes should be raised"],
    answer: 0,
    explanation: "The Resolves supported independence, showing NC's move from protest to revolution.",
  },
  {
    id: "soc-g8-17",
    subject: "social",
    grade: "8",
    standard: "8.G.1.1",
    skill: "Migration",
    passage:
      "From about 1910 to 1970, millions of Black Southerners, including many North Carolinians, moved to cities like New York, Philadelphia and Washington, D.C. This is called the Great Migration.",
    prompt: "Which was a push factor for these migrants?",
    choices: ["Jim Crow laws and few good jobs", "Cold winters in the North", "Free land in the West", "A gold rush in NC"],
    answer: 0,
    explanation: "Push factors drive people away from a place. Segregation, violence and low farm wages pushed people to leave.",
  },
  {
    id: "soc-g8-18",
    subject: "social",
    grade: "8",
    standard: "8.H.1",
    skill: "Timelines",
    passage:
      "Timeline: 1789 NC ratifies the U.S. Constitution. 1795 UNC admits its first students. 1861 NC leaves the Union. 1903 The Wright brothers fly at Kitty Hawk.",
    prompt: "Which event happened first?",
    choices: ["NC ratifies Constitution", "UNC admits students", "NC leaves the Union", "Wright brothers fly"],
    answer: 0,
    explanation: "NC ratified the Constitution in 1789, six years before UNC, the first public university in the U.S. to admit students, opened in 1795.",
  },
];

export default questions;
