import type { Question } from "../../types";
// Grade 3 social studies — NC Standard Course of Study for Social Studies (adopted 2021). "Our Community and State": NC regions, map scale and movement of goods (3.G.1, 3.G.1.3);
// local history and primary sources (3.H.1); local and state government, citizenship (3.C&G.1); NC products, specialization, opportunity cost (3.E.1); community traditions (3.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g3-01",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "Which NC region has the highest land?",
    choices: ["Mountains", "Piedmont", "Coastal Plain", "Outer Banks"],
    answer: 0,
    explanation: "North Carolina has three regions. The Mountains in the west are the highest, with Mount Mitchell.",
    quick: true,
  },
  {
    id: "soc-g3-02",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "Raleigh, our state capital, is in which region?",
    choices: ["Piedmont", "Mountains", "Coastal Plain", "Outer Banks"],
    answer: 0,
    explanation: "The Piedmont is the middle region of NC, with rolling hills and big cities like Raleigh and Charlotte.",
    quick: true,
  },
  {
    id: "soc-g3-03",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "NC regions",
    prompt: "NC's long chain of barrier islands is the...",
    choices: ["Outer Banks", "Blue Ridge", "Piedmont", "Sandhills"],
    answer: 0,
    explanation: "The Outer Banks are thin islands along NC's coast in the Coastal Plain.",
    quick: true,
  },
  {
    id: "soc-g3-04",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    prompt: "Rivers helped early NC towns grow because boats could...",
    choices: ["Move goods", "Make rain", "Grow crops", "Stop wind"],
    answer: 0,
    explanation: "Geography affects movement. Rivers were early highways for carrying goods and people.",
    quick: true,
  },
  {
    id: "soc-g3-05",
    subject: "social",
    grade: "3",
    standard: "3.G.1.3",
    skill: "Movement of goods",
    prompt: "Highways and railroads mostly help a community with...",
    choices: ["Trade", "Weather", "Recess", "Holidays"],
    answer: 0,
    explanation: "Roads and railroads move goods and people, which helps communities trade.",
    quick: true,
  },
  {
    id: "soc-g3-06",
    subject: "social",
    grade: "3",
    standard: "3.G.1",
    skill: "Map skills",
    passage:
      "A map of North Carolina has a scale that says: 1 inch = 10 miles. On the map, Pine Town and Oak City are 3 inches apart.",
    prompt: "What is the distance from Pine Town to Oak City?",
    choices: ["30 miles", "3 miles", "13 miles", "300 miles"],
    answer: 0,
    explanation: "Each inch stands for 10 miles, so 3 inches equals 3 × 10 = 30 miles.",
  },
  {
    id: "soc-g3-07",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Local history",
    prompt: "Two American Indian nations in NC today are the Lumbee and the...",
    choices: ["Cherokee", "Aztec", "Inca", "Maya"],
    answer: 0,
    explanation: "The Lumbee and the Eastern Band of Cherokee Indians are two of the American Indian tribes in NC.",
    quick: true,
  },
  {
    id: "soc-g3-08",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Timelines",
    prompt: "Our town began in 1850. Its school opened in 1900. Which came first?",
    choices: ["The town", "The school", "Same year", "Can't tell"],
    answer: 0,
    explanation: "1850 is earlier than 1900, so the town came first.",
    quick: true,
  },
  {
    id: "soc-g3-09",
    subject: "social",
    grade: "3",
    standard: "3.H.1",
    skill: "Primary sources",
    prompt: "Which is a primary source about your town's past?",
    choices: ["An old photo", "A textbook", "A cartoon", "A video game"],
    answer: 0,
    explanation: "A primary source was made at the time, like a photo or letter. A textbook is written later.",
    quick: true,
  },
  {
    id: "soc-g3-10",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "Local government",
    prompt: "The leader of a city government is the...",
    choices: ["Mayor", "Governor", "President", "Judge"],
    answer: 0,
    explanation: "A mayor leads a city. A governor leads a state, and the President leads the nation.",
    quick: true,
  },
  {
    id: "soc-g3-11",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "State government",
    prompt: "The leader of North Carolina's government is the...",
    choices: ["Governor", "Mayor", "President", "Principal"],
    answer: 0,
    explanation: "The governor is the elected leader of North Carolina's executive branch.",
    quick: true,
  },
  {
    id: "soc-g3-12",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "Taxes",
    prompt: "Local taxes help pay for...",
    choices: ["Public schools", "Your toys", "Vacations", "Birthday cake"],
    answer: 0,
    explanation: "Taxes pay for public services like schools, parks, police and fire stations.",
    quick: true,
  },
  {
    id: "soc-g3-13",
    subject: "social",
    grade: "3",
    standard: "3.C&G.1",
    skill: "Citizenship",
    prompt: "A responsible citizen in a community...",
    choices: ["Follows laws", "Litters", "Ignores rules", "Wastes water"],
    answer: 0,
    explanation: "Responsible citizens follow laws, help others and take care of the community.",
    quick: true,
  },
  {
    id: "soc-g3-14",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "NC products",
    prompt: "Farmers in NC's Coastal Plain grow a lot of...",
    choices: ["Sweet potatoes", "Coffee", "Bananas", "Pineapples"],
    answer: 0,
    explanation: "North Carolina grows more sweet potatoes than any other state, mostly in the east.",
    quick: true,
  },
  {
    id: "soc-g3-15",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "Specialization",
    prompt: "A bakery that only makes bread is...",
    choices: ["Specializing", "Saving", "Voting", "Borrowing"],
    answer: 0,
    explanation: "Specialization means focusing on making one kind of good or service.",
    quick: true,
  },
  {
    id: "soc-g3-16",
    subject: "social",
    grade: "3",
    standard: "3.E.1",
    skill: "Opportunity cost",
    passage:
      "Maya has $5. She wants a book and a kite, and each costs $5. She thinks about it and buys the book.",
    prompt: "What is Maya's opportunity cost?",
    choices: ["The kite", "The book", "The $5", "The store"],
    answer: 0,
    explanation: "Opportunity cost is the next-best choice you give up. Maya gave up the kite.",
  },
  {
    id: "soc-g3-17",
    subject: "social",
    grade: "3",
    standard: "3.B.1.1",
    skill: "Traditions",
    prompt: "Festivals, foods and songs passed down in a community are...",
    choices: ["Traditions", "Laws", "Landforms", "Taxes"],
    answer: 0,
    explanation: "Traditions are customs passed from older people to younger people. They help give a community its culture.",
    quick: true,
  },
  {
    id: "soc-g3-18",
    subject: "social",
    grade: "3",
    standard: "3.B.1.1",
    skill: "Traditions",
    prompt: "A powwow is a celebration held by...",
    choices: ["Native nations", "City councils", "Sports teams", "Banks"],
    answer: 0,
    explanation: "Powwows bring American Indian people together for dancing, drumming, food and honoring traditions.",
    quick: true,
  },
];

export default questions;
