import type { Question } from "../../types";
// Grade 8 science — NC Standard Course of Study for Science (2023). Elements, compounds and mixtures, atomic structure,
// the periodic table, and physical vs. chemical changes (PS.8.1); energy resources (PS.8.2); rock layers, fossils and
// Earth's history (ESS.8.1); the hydrosphere, ocean currents and water quality (ESS.8.2); pathogens and the spread,
// treatment and prevention of disease (LS.8.1); populations, food webs and relationships in ecosystems (LS.8.2);
// evidence for evolution and natural selection (LS.8.3).
const questions: Question[] = [
  {
    id: "sci-g8-01",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Atomic structure",
    prompt: "Which positively charged particles are found in an atom's nucleus?",
    choices: ["Protons", "Electrons", "Neutrons", "Photons"],
    answer: 0,
    explanation: "Protons (+) and neutrons (no charge) are in the nucleus. Electrons (−) move around outside it.",
    quick: true,
  },
  {
    id: "sci-g8-02",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Elements, compounds, mixtures",
    prompt: "Water (H₂O) is best classified as a...",
    choices: ["Compound", "Element", "Mixture", "Single atom"],
    answer: 0,
    explanation: "A compound is two or more elements chemically bonded in a fixed ratio. Water is always 2 hydrogen atoms to 1 oxygen.",
    quick: true,
  },
  {
    id: "sci-g8-03",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Chemical changes",
    prompt: "Which is evidence that a chemical change happened?",
    choices: ["A gas forms", "Ice melts", "Paper is torn", "Salt dissolves"],
    answer: 0,
    explanation: "Unexpected gas, color change, light, or a new solid can show new substances formed. Melting, tearing and dissolving are physical changes.",
    quick: true,
  },
  {
    id: "sci-g8-04",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Conservation of mass",
    passage:
      "In a sealed flask, 10 g of substance A reacts completely with 5 g of substance B. A new solid and a gas are produced, and nothing leaves the flask.",
    prompt: "What is the total mass of the products?",
    choices: ["15 g", "10 g", "5 g", "Less than 15 g, because gas weighs nothing"],
    answer: 0,
    explanation: "In a closed system, atoms are rearranged but not created or destroyed, so mass is conserved: 10 g + 5 g = 15 g.",
  },
  {
    id: "sci-g8-05",
    subject: "science",
    grade: "8",
    standard: "PS.8.1",
    skill: "Periodic table",
    prompt: "Elements in the same column (group) of the periodic table have similar...",
    choices: ["Properties", "Masses", "Names", "Discoverers"],
    answer: 0,
    explanation: "Elements in a group have the same number of outer electrons, so they react in similar ways.",
    quick: true,
  },
  {
    id: "sci-g8-06",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Evidence of evolution",
    prompt: "Bat wings and human arms have similar bones. This is evidence of...",
    choices: ["Evolution", "Erosion", "Metamorphism", "Digestion"],
    answer: 0,
    explanation: "Similar (homologous) structures suggest bats and humans share a common ancestor.",
    quick: true,
  },
  {
    id: "sci-g8-07",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Which energy resource is renewable?",
    choices: ["Wind", "Coal", "Natural gas", "Oil"],
    answer: 0,
    explanation: "Wind is replaced naturally and will not run out. Coal, oil and natural gas are fossil fuels that take millions of years to form.",
    quick: true,
  },
  {
    id: "sci-g8-08",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Burning coal releases which greenhouse gas?",
    choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    answer: 0,
    explanation: "Coal is mostly carbon. Burning it combines carbon with oxygen, making carbon dioxide, which traps heat.",
    quick: true,
  },
  {
    id: "sci-g8-09",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Rock layers",
    prompt: "In undisturbed rock layers, where is the oldest layer?",
    choices: ["Bottom", "Top", "Middle", "Surface"],
    answer: 0,
    explanation: "This is the law of superposition: layers are deposited on top of older ones, so the oldest is at the bottom.",
    quick: true,
  },
  {
    id: "sci-g8-10",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Relative dating",
    passage:
      "A cliff shows three flat rock layers: A on top, B in the middle, C on the bottom. A band of igneous rock (an intrusion) cuts through layers C and B but stops at the bottom of layer A.",
    prompt: "What is the correct order of events, oldest to youngest?",
    choices: ["C, B, intrusion, A", "A, B, C, intrusion", "Intrusion, C, B, A", "C, intrusion, B, A"],
    answer: 0,
    explanation: "C and B formed first. The intrusion must be younger than the layers it cuts, and older than layer A, which covers it.",
  },
  {
    id: "sci-g8-11",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Fossils",
    prompt: "Fossils used to date rock layers because they lived briefly but widely are...",
    choices: ["Index fossils", "Trace fossils", "Casts", "Molds"],
    answer: 0,
    explanation: "Index fossils come from species that lived for a short time over a wide area, so they pinpoint a layer's age.",
    quick: true,
  },
  {
    id: "sci-g8-12",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere",
    prompt: "Most of Earth's water is...",
    choices: ["Salt water", "Glacier ice", "Groundwater", "River water"],
    answer: 0,
    explanation: "About 97% of Earth's water is salty ocean water. Only a small part is fresh water we can use.",
    quick: true,
  },
  {
    id: "sci-g8-13",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere",
    prompt: "An estuary forms where a river meets...",
    choices: ["The ocean", "A mountain", "A glacier", "A desert"],
    answer: 0,
    explanation: "Estuaries, like the Albemarle-Pamlico Sound, mix fresh river water with salty ocean water.",
    quick: true,
  },
  {
    id: "sci-g8-14",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Water quality",
    passage:
      "Dissolved oxygen (DO) measured in a stream: at 10°C, 11 mg/L; at 20°C, 9 mg/L; at 30°C, 7.5 mg/L. Many fish become stressed below about 5 mg/L.",
    prompt: "Which conclusion is best supported by these data?",
    choices: [
      "Warmer water holds less oxygen, which can stress fish",
      "Warmer water holds more oxygen, which helps fish",
      "Temperature has no effect on dissolved oxygen",
      "Fish need warmer water to get enough oxygen",
    ],
    answer: 0,
    explanation: "As temperature rose, DO fell. Warm water holds less dissolved gas, so hot summers or warm runoff can harm aquatic life.",
  },
  {
    id: "sci-g8-15",
    subject: "science",
    grade: "8",
    standard: "LS.8.1",
    skill: "Microbes and disease",
    prompt: "Antibiotics can treat illnesses caused by...",
    choices: ["Bacteria", "Viruses", "The flu", "A cold"],
    answer: 0,
    explanation: "Antibiotics kill bacteria. Colds and flu are caused by viruses, so antibiotics do not help them.",
    quick: true,
  },
  {
    id: "sci-g8-16",
    subject: "science",
    grade: "8",
    standard: "LS.8.1",
    skill: "Microbes and disease",
    prompt: "What does a vaccine help the body do?",
    choices: ["Build immunity", "Digest food", "Grow taller", "Make vitamins"],
    answer: 0,
    explanation: "A vaccine trains the immune system to recognize a germ, so the body can fight it quickly later.",
    quick: true,
  },
  {
    id: "sci-g8-17",
    subject: "science",
    grade: "8",
    standard: "LS.8.2",
    skill: "Energy flow in ecosystems",
    prompt: "About how much energy passes from one level of a food chain to the next?",
    choices: ["10%", "50%", "90%", "100%"],
    answer: 0,
    explanation: "Only about 10% is passed on. Most energy is used for life processes or lost as heat.",
    quick: true,
  },
  {
    id: "sci-g8-18",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Natural selection",
    passage:
      "Before the 1800s, most peppered moths in England were light-colored and blended in with pale tree bark. Factory soot then darkened the trees. Within decades, most moths in those areas were dark.",
    prompt: "What best explains the change?",
    choices: [
      "Dark moths were eaten less on dark bark, survived and passed on the trait",
      "Light moths turned dark to hide from birds",
      "Soot dyed the light moths' wings dark",
      "Moths chose to become dark because they needed to",
    ],
    answer: 0,
    explanation: "Natural selection: variation already existed, and the trait that improved survival became more common over generations. Individuals do not change on purpose.",
  },
  {
    id: "sci-g8-19",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.1",
    skill: "Elements, compounds, mixtures",
    prompt: "Salt water is best classified as a...",
    choices: ["Mixture", "Element", "Compound", "Pure atom"],
    answer: 0,
    explanation: "Salt and water are mixed but not chemically bonded, and they can be separated by evaporation.",
    quick: true,
  },
  {
    id: "sci-g8-20",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.1",
    skill: "Elements, compounds, mixtures",
    prompt: "Which substance is an element?",
    choices: ["Gold (Au)", "Water (H₂O)", "Salt (NaCl)", "Air"],
    answer: 0,
    explanation: "An element is made of only one kind of atom. Gold contains only gold atoms.",
    quick: true,
  },
  {
    id: "sci-g8-21",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.1",
    skill: "Elements, compounds, mixtures",
    prompt: "Which can be separated by physical means, like filtering?",
    choices: ["Mixture", "Compound", "Element", "Atom"],
    answer: 0,
    explanation: "The parts of a mixture keep their own properties, so they can be separated physically.",
    quick: true,
  },
  {
    id: "sci-g8-22",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.2",
    skill: "Atomic structure",
    prompt: "Which particle has a negative charge?",
    choices: ["Electron", "Proton", "Neutron", "Nucleus"],
    answer: 0,
    explanation: "Electrons are negative, protons are positive and neutrons have no charge.",
    quick: true,
  },
  {
    id: "sci-g8-23",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.2",
    skill: "Atomic structure",
    prompt: "Most of an atom's mass is found in its...",
    choices: ["Nucleus", "Electron cloud", "Outer shell", "Empty space"],
    answer: 0,
    explanation: "Protons and neutrons in the nucleus are about 1,800 times heavier than electrons.",
    quick: true,
  },
  {
    id: "sci-g8-24",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.2",
    skill: "Atomic structure",
    prompt: "Which particle has no electric charge?",
    choices: ["Neutron", "Proton", "Electron", "Ion"],
    answer: 0,
    explanation: "Neutrons are neutral. They sit in the nucleus with the protons.",
    quick: true,
  },
  {
    id: "sci-g8-25",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.3",
    skill: "Periodic table",
    prompt: "Elements on the far right of the periodic table are...",
    choices: ["Noble gases", "Alkali metals", "Metalloids", "Transition metals"],
    answer: 0,
    explanation: "Group 18, the noble gases, are on the far right. They rarely react with other elements.",
  },
  {
    id: "sci-g8-26",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.3",
    skill: "Periodic table",
    prompt: "Most elements on the left side of the periodic table are...",
    choices: ["Metals", "Nonmetals", "Noble gases", "Halogens"],
    answer: 0,
    explanation: "Metals fill the left and middle of the table. Nonmetals are on the right.",
    quick: true,
  },
  {
    id: "sci-g8-27",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.3",
    skill: "Periodic table",
    prompt: "Shiny, conducts heat, can be hammered flat. This element is a...",
    choices: ["Metal", "Nonmetal", "Noble gas", "Halogen"],
    answer: 0,
    explanation: "Luster, conductivity and malleability are properties of metals.",
    quick: true,
  },
  {
    id: "sci-g8-28",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.4",
    skill: "Physical and chemical changes",
    prompt: "Which is a physical change?",
    choices: ["Ice melting", "Iron rusting", "Wood burning", "Milk souring"],
    answer: 0,
    explanation: "Melting changes only the state. Rusting, burning and souring make new substances.",
    quick: true,
  },
  {
    id: "sci-g8-29",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.4",
    skill: "Physical and chemical changes",
    prompt: "Two clear liquids mix and form a cloudy solid. This solid is a...",
    choices: ["Precipitate", "Solvent", "Element", "Mixture"],
    answer: 0,
    explanation: "A solid that forms when solutions are mixed is a precipitate, a sign of a chemical change.",
    quick: true,
  },
  {
    id: "sci-g8-30",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Which energy source comes from heat inside Earth?",
    choices: ["Geothermal", "Solar", "Wind", "Coal"],
    answer: 0,
    explanation: "Geothermal energy uses heat from deep underground to make steam and electricity.",
    quick: true,
  },
  {
    id: "sci-g8-31",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Nuclear power plants get energy by...",
    choices: ["Splitting atoms", "Burning coal", "Using wind", "Heating oil"],
    answer: 0,
    explanation: "Nuclear plants use fission, splitting uranium atoms, to release heat that makes steam.",
  },
  {
    id: "sci-g8-32",
    subject: "science",
    grade: "8",
    standard: "PS.8.2",
    skill: "Energy resources",
    prompt: "Fossil fuels formed from...",
    choices: ["Ancient life", "Volcanic ash", "Sea salt", "Moon rocks"],
    answer: 0,
    explanation: "Coal, oil and natural gas formed from plants and tiny organisms buried millions of years ago.",
    quick: true,
  },
  {
    id: "sci-g8-33",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Earth's history",
    prompt: "A crack in rock where the rock has moved is a...",
    choices: ["Fault", "Fossil", "Mineral", "Crater"],
    answer: 0,
    explanation: "A fault is a break where rock layers have slid past each other.",
    quick: true,
  },
  {
    id: "sci-g8-34",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Earth's history",
    prompt: "Seashell fossils in mountain rock show the area was once...",
    choices: ["Under the sea", "A desert", "Glacier ice", "Grassland"],
    answer: 0,
    explanation: "Shells come from sea animals, so the rock formed on an ancient seafloor that was later lifted up.",
    quick: true,
  },
  {
    id: "sci-g8-35",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Earth's history",
    prompt: "Which rock type most often contains fossils?",
    choices: ["Sedimentary", "Igneous", "Metamorphic", "Magma"],
    answer: 0,
    explanation: "Fossils form when organisms are buried in layers of sediment that harden into rock.",
    quick: true,
  },
  {
    id: "sci-g8-36",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere and ocean currents",
    prompt: "Deep ocean currents are driven mainly by differences in...",
    choices: ["Temperature, salt", "Wind only", "Moon phase", "Fish"],
    answer: 0,
    explanation: "Cold, salty water is dense and sinks, driving deep currents around the globe.",
  },
  {
    id: "sci-g8-37",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Hydrosphere and ocean currents",
    prompt: "Surface ocean currents are driven mainly by...",
    choices: ["Wind", "Earthquakes", "Fish", "Moonlight"],
    answer: 0,
    explanation: "Steady winds push the top layer of the ocean, creating surface currents like the Gulf Stream.",
    quick: true,
  },
  {
    id: "sci-g8-38",
    subject: "science",
    grade: "8",
    standard: "ESS.8.2",
    skill: "Water quality",
    prompt: "Which measurement shows how cloudy water is?",
    choices: ["Turbidity", "pH", "Salinity", "Temperature"],
    answer: 0,
    explanation: "Turbidity measures how much sediment or particles make water cloudy.",
    quick: true,
  },
  {
    id: "sci-g8-39",
    subject: "science",
    grade: "8",
    standard: "LS.8.1.1",
    skill: "Pathogens and disease",
    prompt: "Which type of pathogen is not a living cell?",
    choices: ["Virus", "Bacterium", "Fungus", "Parasite"],
    answer: 0,
    explanation: "Viruses are not cells. They can only reproduce inside a host's cells.",
    quick: true,
  },
  {
    id: "sci-g8-40",
    subject: "science",
    grade: "8",
    standard: "LS.8.1.1",
    skill: "Pathogens and disease",
    prompt: "Athlete's foot is caused by a...",
    choices: ["Fungus", "Virus", "Bacterium", "Vitamin"],
    answer: 0,
    explanation: "Athlete's foot is a fungal infection, so it is treated with antifungal medicine.",
    quick: true,
  },
  {
    id: "sci-g8-41",
    subject: "science",
    grade: "8",
    standard: "LS.8.1.2",
    skill: "Epidemics and pandemics",
    prompt: "A disease spreading across many countries at once is a...",
    choices: ["Pandemic", "Epidemic", "Vaccine", "Antibody"],
    answer: 0,
    explanation: "An epidemic is a big outbreak in one area. A pandemic spreads worldwide.",
    quick: true,
  },
  {
    id: "sci-g8-42",
    subject: "science",
    grade: "8",
    standard: "LS.8.2",
    skill: "Ecosystem relationships",
    prompt: "Bees get nectar and flowers get pollinated. This is...",
    choices: ["Mutualism", "Parasitism", "Predation", "Competition"],
    answer: 0,
    explanation: "In mutualism, both species benefit.",
    quick: true,
  },
  {
    id: "sci-g8-43",
    subject: "science",
    grade: "8",
    standard: "LS.8.2",
    skill: "Ecosystem relationships",
    prompt: "A tick feeds on a dog's blood. This relationship is...",
    choices: ["Parasitism", "Mutualism", "Commensalism", "Predation"],
    answer: 0,
    explanation: "The tick benefits and the dog is harmed, which is parasitism.",
    quick: true,
  },
  {
    id: "sci-g8-44",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Evidence for evolution",
    prompt: "Whale skeletons have tiny hip bones. These are...",
    choices: ["Vestigial", "Analogous", "Fossils", "Igneous"],
    answer: 0,
    explanation: "Vestigial structures are leftover parts that no longer have their original use, a clue to ancestry.",
    quick: true,
  },
  {
    id: "sci-g8-45",
    subject: "science",
    grade: "8",
    standard: "LS.8.2.1",
    skill: "Population changes",
    passage:
      "On a plateau, wolves were removed in 1910. Deer: 1910: 4,000. 1920: 30,000. 1930: 80,000. 1940: 10,000. Plants were badly overgrazed by 1930.",
    prompt: "Why did the deer population drop after 1930?",
    choices: ["Food ran out", "Wolves increased", "Deer moved to cities", "Hunting rose"],
    answer: 0,
    explanation: "With no predators, the deer outgrew their food supply, and many starved.",
  },
  {
    id: "sci-g8-46",
    subject: "science",
    grade: "8",
    standard: "ESS.8.1",
    skill: "Earth's history",
    passage:
      "A cliff shows layers 1 (bottom) to 4 (top). Between layers 2 and 3 is a wavy surface where rock was eroded away before layer 3 was deposited.",
    prompt: "What does the wavy surface represent?",
    choices: [
      "A gap in the rock record",
      "The oldest rock in the cliff",
      "A fault that formed last",
      "A layer made of fossils",
    ],
    answer: 0,
    explanation: "An erosion surface (unconformity) shows that rock was worn away before new layers formed, so part of Earth's history is missing there.",
  },
  {
    id: "sci-g8-47",
    subject: "science",
    grade: "8",
    standard: "PS.8.1.1",
    skill: "Elements, compounds, mixtures",
    passage:
      "Box A: single atoms, all of one kind. Box B: identical molecules, each made of two different atoms bonded together. Box C: two different kinds of molecules mixed but not bonded.",
    prompt: "Which box shows a mixture?",
    choices: ["Box C", "Box A", "Box B", "Boxes A and B"],
    answer: 0,
    explanation: "Box C holds two different substances that are not bonded together, so it is a mixture. A is an element and B is a compound.",
  },
  {
    id: "sci-g8-48",
    subject: "science",
    grade: "8",
    standard: "LS.8.3",
    skill: "Evidence for evolution",
    passage:
      "Fossils of horse ancestors, from oldest to youngest rock layers, show four toes, then three toes, then one hoof, while body size slowly increased.",
    prompt: "What do these fossils best show?",
    choices: [
      "Horses changed gradually over time",
      "Horses have always looked the same",
      "Horses are related to fish",
      "Fossils cannot show change",
    ],
    answer: 0,
    explanation: "The fossil series shows small changes building up over millions of years, which is evidence of evolution.",
  },
];
export default questions;
