import type { Question } from "../../types";

// Grade 10 ELA — NC Standard Course of Study for ELA (2017). English II (9-10 band): RL.9-10.4, RL.9-10.5, RL.9-10.6, RL.9-10.9, RI.9-10.5, RI.9-10.6, RI.9-10.8, L.9-10.1, L.9-10.2, L.9-10.4, L.9-10.5
const questions: Question[] = [
  {
    id: "ela-g10-01",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "Twisting an opponent's argument so it's easy to attack is a...",
    choices: ["straw man", "red herring", "ad hominem", "slippery slope"],
    answer: 0,
    explanation: "A straw man replaces the real argument with a weaker version that is easy to knock down.",
    quick: true,
  },
  {
    id: "ela-g10-02",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'Either we ban all cars or the planet is doomed' is a...",
    choices: ["false dilemma", "straw man", "red herring", "ad hominem"],
    answer: 0,
    explanation: "A false dilemma pretends there are only two options when more exist.",
    quick: true,
  },
  {
    id: "ela-g10-03",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'If we allow one late pass, soon no one will be on time' is a...",
    choices: ["slippery slope", "bandwagon", "ethos", "false dilemma"],
    answer: 0,
    explanation: "A slippery slope claims one small step will lead to extreme results without proof.",
    quick: true,
  },
  {
    id: "ela-g10-04",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal using facts, data, and reasoning is...",
    choices: ["logos", "pathos", "ethos", "mythos"],
    answer: 0,
    explanation: "Logos appeals to logic with evidence and clear reasoning.",
    quick: true,
  },
  {
    id: "ela-g10-05",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Conjunctions and clauses",
    prompt: "Which word is a subordinating conjunction?",
    choices: ["although", "and", "but", "or"],
    answer: 0,
    explanation: "Although begins a dependent clause. And, but, and or are coordinating conjunctions.",
    quick: true,
  },
  {
    id: "ela-g10-06",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.2",
    skill: "Colons",
    prompt: "Which mark introduces a list after a complete sentence?",
    choices: ["colon", "semicolon", "comma", "hyphen"],
    answer: 0,
    explanation: "A colon follows an independent clause to introduce a list, quote, or explanation.",
    quick: true,
  },
  {
    id: "ela-g10-07",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Word forms",
    prompt: "Which word is the noun form of analyze?",
    choices: ["analysis", "analytic", "analytical", "analyzed"],
    answer: 0,
    explanation: "Analysis is the noun. Analytic and analytical are adjectives; analyzed is a verb.",
    quick: true,
  },
  {
    id: "ela-g10-08",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Greek and Latin roots",
    prompt: "The root bell (as in belligerent) means...",
    choices: ["war", "beauty", "noise", "peace"],
    answer: 0,
    explanation: "Latin bellum means war, so a belligerent person is hostile or ready to fight.",
    quick: true,
  },
  {
    id: "ela-g10-09",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Narrative structure",
    prompt: "Hints about what will happen later in a story are...",
    choices: ["foreshadowing", "flashback", "epilogue", "exposition"],
    answer: 0,
    explanation: "Foreshadowing plants clues that build tension and expectation.",
    quick: true,
  },
  {
    id: "ela-g10-10",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.9",
    skill: "Allusion",
    prompt: "A reference to a well-known myth, text, or event is an...",
    choices: ["allusion", "illusion", "elegy", "idiom"],
    answer: 0,
    explanation: "An allusion borrows meaning from something the reader already knows. An illusion is a false image.",
    quick: true,
  },
  {
    id: "ela-g10-11",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.5",
    skill: "Nuance in word meaning",
    prompt: "Which word means stubborn in the most negative way?",
    choices: ["pigheaded", "determined", "persistent", "steadfast"],
    answer: 0,
    explanation: "Determined, persistent, and steadfast sound admirable; pigheaded is an insult.",
    quick: true,
  },
  {
    id: "ela-g10-12",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.4",
    skill: "Mood",
    prompt: "The feeling a text creates in the reader is its...",
    choices: ["mood", "tone", "theme", "voice"],
    answer: 0,
    explanation: "Mood is the reader's emotional atmosphere; tone is the author's attitude.",
    quick: true,
  },
  {
    id: "ela-g10-13",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.9",
    skill: "Archetypes",
    prompt: "The hero's journey is an example of an...",
    choices: ["archetype", "oxymoron", "epigraph", "anecdote"],
    answer: 0,
    explanation: "An archetype is a pattern, like the hero's journey, that appears across many cultures' stories.",
    quick: true,
  },
  {
    id: "ela-g10-14",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Phrases and clauses",
    prompt: "In 'The novel that won the prize was written in Lagos,' what is 'that won the prize'?",
    choices: ["an adjective clause modifying novel", "an adverb clause modifying written", "a noun clause used as the subject", "a prepositional phrase"],
    answer: 0,
    explanation: "The clause has a subject and verb and describes which novel, so it is an adjective (relative) clause.",
  },
  {
    id: "ela-g10-15",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.6",
    skill: "Cultural perspective",
    prompt: "What does this passage mainly reveal?",
    passage: "In my grandmother's village, a guest is never asked whether they are hungry; a plate simply appears. When my roommate asked if I wanted a snack, I said no out of politeness, and then waited, stomach growling, for the plate that never came.",
    choices: ["How cultural norms shape everyday moments", "That the roommate was rude", "That the narrator dislikes the food", "That the grandmother is a chef"],
    answer: 0,
    explanation: "The misunderstanding comes from different cultural expectations about offering food.",
  },
  {
    id: "ela-g10-16",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.5",
    skill: "Text structure",
    prompt: "How is this paragraph structured?",
    passage: "Many assume the Great Wall of China was built all at once. In fact, it is a series of walls constructed over many centuries by different dynasties, each adding, rebuilding, or abandoning sections.",
    choices: ["It states a misconception, then corrects it.", "It lists events in time order.", "It compares two different walls.", "It describes a problem and a solution."],
    answer: 0,
    explanation: "'Many assume' introduces a common belief; 'In fact' corrects it.",
  },
  {
    id: "ela-g10-17",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Pacing",
    prompt: "What effect do the short sentences and fragments create?",
    passage: "The clock ticked. Mara's hand hovered over the button. One second. Two. Her breath caught. Three.",
    choices: ["tension", "calm reflection", "humor", "confusion about the setting"],
    answer: 0,
    explanation: "Short, clipped sentences slow time down second by second and build suspense.",
  },
  {
    id: "ela-g10-18",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does trepidation most likely mean?",
    passage: "Despite the team's initial trepidation about the steep climb, they reached the summit with confidence and laughter.",
    choices: ["fear or worry", "excitement", "exhaustion", "disbelief"],
    answer: 0,
    explanation: "'Despite' signals a contrast with 'confidence,' so trepidation means fear or worry.",
  },
];

export default questions;
