import type { Question } from "../../types";

// Grade 11 ELA — NC Standard Course of Study for ELA (2017). English III (11-12 band): RL.11-12.4, RL.11-12.5, RL.11-12.6, RI.11-12.6, RI.11-12.8, L.11-12.2, L.11-12.3, L.11-12.4, L.11-12.5, W.11-12.1
const questions: Question[] = [
  {
    id: "ela-g11-01",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Satire",
    prompt: "A work that mocks human foolishness to push for change is...",
    choices: ["satire", "elegy", "epic", "ode"],
    answer: 0,
    explanation: "Satire uses humor, irony, and exaggeration to criticize and encourage reform.",
    quick: true,
  },
  {
    id: "ela-g11-02",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Understatement",
    prompt: "Calling a hurricane 'a bit of wind' is...",
    choices: ["understatement", "hyperbole", "alliteration", "allusion"],
    answer: 0,
    explanation: "Understatement makes something seem much smaller than it is, often for irony.",
    quick: true,
  },
  {
    id: "ela-g11-03",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'The more you learn, the less you know' is a...",
    choices: ["paradox", "simile", "euphemism", "pun"],
    answer: 0,
    explanation: "A paradox seems self-contradictory but reveals a deeper truth.",
    quick: true,
  },
  {
    id: "ela-g11-04",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'The White House announced a new plan' uses...",
    choices: ["metonymy", "simile", "apostrophe", "hyperbole"],
    answer: 0,
    explanation: "Metonymy names something closely associated (the building) to mean the thing itself (the administration).",
    quick: true,
  },
  {
    id: "ela-g11-05",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Rhetorical devices",
    prompt: "A question asked for effect, not for an answer, is...",
    choices: ["rhetorical", "literal", "factual", "open-ended"],
    answer: 0,
    explanation: "A rhetorical question makes a point or engages the audience rather than seeking a reply.",
    quick: true,
  },
  {
    id: "ela-g11-06",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.4",
    skill: "Diction",
    prompt: "An author's specific word choice is called...",
    choices: ["diction", "syntax", "tone", "imagery"],
    answer: 0,
    explanation: "Diction is word choice. Syntax is how words are arranged.",
    quick: true,
  },
  {
    id: "ela-g11-07",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.3",
    skill: "Syntax",
    prompt: "The arrangement of words and phrases in a sentence is...",
    choices: ["syntax", "diction", "tone", "semantics"],
    answer: 0,
    explanation: "Syntax covers sentence order, length, and structure.",
    quick: true,
  },
  {
    id: "ela-g11-08",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root loqu (as in eloquent) means...",
    choices: ["speak", "write", "light", "lose"],
    answer: 0,
    explanation: "Loqu means speak, as in eloquent, loquacious, and soliloquy.",
    quick: true,
  },
  {
    id: "ela-g11-09",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Greek and Latin roots",
    prompt: "The prefix omni- (as in omnipotent) means...",
    choices: ["all", "none", "some", "power"],
    answer: 0,
    explanation: "Omni- means all, so omnipotent means all-powerful.",
    quick: true,
  },
  {
    id: "ela-g11-10",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.5",
    skill: "Drama",
    prompt: "A long speech by a character alone on stage is a...",
    choices: ["soliloquy", "dialogue", "aside", "epilogue"],
    answer: 0,
    explanation: "In a soliloquy, a character speaks thoughts aloud alone. An aside is a brief remark to the audience.",
    quick: true,
  },
  {
    id: "ela-g11-11",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Hyphens",
    prompt: "Which compound adjective is hyphenated correctly?",
    choices: ["up-to-date app", "up to-date app", "up-to date app", "uptodate app"],
    answer: 0,
    explanation: "Hyphenate all the words of a compound adjective that comes before a noun.",
    quick: true,
  },
  {
    id: "ela-g11-12",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.8",
    skill: "Reasoning",
    prompt: "Reasoning from a general principle to a specific case is...",
    choices: ["deductive", "inductive", "circular", "anecdotal"],
    answer: 0,
    explanation: "Deductive reasoning moves from general to specific; inductive moves from specific cases to a general rule.",
    quick: true,
  },
  {
    id: "ela-g11-13",
    subject: "ela",
    grade: "11",
    standard: "W.11-12.1",
    skill: "Argument writing",
    prompt: "An argument's central, debatable claim is its...",
    choices: ["thesis", "anecdote", "hook", "citation"],
    answer: 0,
    explanation: "The thesis states the precise claim the whole argument supports.",
    quick: true,
  },
  {
    id: "ela-g11-14",
    subject: "ela",
    grade: "11",
    standard: "RL.11-12.6",
    skill: "Irony",
    prompt: "What type of irony is in this passage?",
    passage: "The fire station burned down last night. The firefighters, who had been out rescuing a cat from a tree, returned to find their own building in ashes.",
    choices: ["situational irony", "verbal irony", "dramatic irony", "no irony"],
    answer: 0,
    explanation: "Situational irony is when the outcome is the opposite of what we expect: firefighters lose their own station to fire.",
  },
  {
    id: "ela-g11-15",
    subject: "ela",
    grade: "11",
    standard: "RI.11-12.6",
    skill: "Rhetorical devices",
    prompt: "Which device appears in 'We did not choose the storm, but we can choose how we weather it'?",
    passage: "We did not choose the storm, but we can choose how we weather it. Let us not ask whether the task is easy; let us ask whether it is right. And if it is right, let us begin, today, together, without delay.",
    choices: ["antithesis", "understatement", "onomatopoeia", "euphemism"],
    answer: 0,
    explanation: "Antithesis sets contrasting ideas side by side in parallel form for emphasis.",
  },
  {
    id: "ela-g11-16",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.3",
    skill: "Syntax and style",
    prompt: "What is the effect of the short sentence followed by a long one?",
    passage: "She ran. She ran past the mill, past the church, past the last lit window of the town, until the road dissolved into dark fields and the only sound was her own breathing.",
    choices: ["The long sentence mirrors her run stretching on.", "It shows that she stopped running.", "It creates a humorous tone.", "It introduces a new character."],
    answer: 0,
    explanation: "The long, flowing sentence carries the reader forward just as the road carries her into the distance.",
  },
  {
    id: "ela-g11-17",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.2",
    skill: "Comma splices",
    prompt: "Which sentence avoids a comma splice?",
    choices: ["The results were clear; the plan had worked.", "The results were clear, the plan had worked.", "The results were clear the plan had worked.", "The results, were clear the plan had worked."],
    answer: 0,
    explanation: "A semicolon can correctly join two independent clauses; a comma alone cannot.",
  },
  {
    id: "ela-g11-18",
    subject: "ela",
    grade: "11",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does specious most likely mean?",
    passage: "The lawyer's argument was specious: it sounded convincing at first, but under careful examination, its logic fell apart.",
    choices: ["seeming true but actually false", "completely honest", "overly long", "difficult to hear"],
    answer: 0,
    explanation: "The argument sounded convincing but fell apart, so specious means misleadingly plausible.",
  },
];

export default questions;
