import type { Question } from "../../types";

// Grade 12 ELA — NC Standard Course of Study for ELA (2017). English IV (11-12 band): RL.11-12.2, RL.11-12.4, RL.11-12.5, RL.11-12.6, RI.11-12.6, RI.11-12.8, L.11-12.1, L.11-12.4, L.11-12.5, W.11-12.1
const questions: Question[] = [
  {
    id: "ela-g12-01",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'All hands on deck' uses a part to stand for the whole. This is...",
    choices: ["synecdoche", "simile", "litotes", "euphemism"],
    answer: 0,
    explanation: "Synecdoche uses a part (hands) to represent the whole (sailors).",
    quick: true,
  },
  {
    id: "ela-g12-02",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "Speaking directly to an absent person or thing, as in 'O Moon!', is...",
    choices: ["apostrophe", "allusion", "ellipsis", "anaphora"],
    answer: 0,
    explanation: "As a figure of speech, apostrophe addresses someone absent or something not human.",
    quick: true,
  },
  {
    id: "ela-g12-03",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Tragedy",
    prompt: "A tragic hero's fatal flaw or error is called...",
    choices: ["hamartia", "catharsis", "denouement", "epiphany"],
    answer: 0,
    explanation: "Hamartia is the flaw or mistake that leads to the tragic hero's downfall.",
    quick: true,
  },
  {
    id: "ela-g12-04",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Tragedy",
    prompt: "The emotional release an audience feels after a tragedy is...",
    choices: ["catharsis", "hamartia", "exposition", "peripeteia"],
    answer: 0,
    explanation: "Aristotle called this purging of pity and fear catharsis.",
    quick: true,
  },
  {
    id: "ela-g12-05",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Poetic forms",
    prompt: "A 14-line poem written in iambic pentameter is a...",
    choices: ["sonnet", "haiku", "limerick", "ballad"],
    answer: 0,
    explanation: "Sonnets have 14 lines, usually in iambic pentameter, with set rhyme schemes.",
    quick: true,
  },
  {
    id: "ela-g12-06",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.5",
    skill: "Poetic forms",
    prompt: "Unrhymed lines written in iambic pentameter are called...",
    choices: ["blank verse", "free verse", "a sonnet", "a couplet"],
    answer: 0,
    explanation: "Blank verse has regular meter but no rhyme. Free verse has neither.",
    quick: true,
  },
  {
    id: "ela-g12-07",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.6",
    skill: "Narrator reliability",
    prompt: "A narrator whose account can't be fully trusted is...",
    choices: ["unreliable", "omniscient", "objective", "second-person"],
    answer: 0,
    explanation: "An unreliable narrator's bias, lies, or limits make readers question the story.",
    quick: true,
  },
  {
    id: "ela-g12-08",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Word origins",
    prompt: "The study of a word's origin and history is...",
    choices: ["etymology", "entomology", "syntax", "phonics"],
    answer: 0,
    explanation: "Etymology traces word histories. Entomology is the study of insects.",
    quick: true,
  },
  {
    id: "ela-g12-09",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Who and whom",
    prompt: "To ___ should I address the letter? Which word fits?",
    choices: ["whom", "who", "whose", "who's"],
    answer: 0,
    explanation: "Use whom as the object of a preposition: to whom.",
    quick: true,
  },
  {
    id: "ela-g12-10",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Subjunctive mood",
    prompt: "The board insisted that he ___ on time. Which verb fits?",
    choices: ["be", "is", "was", "being"],
    answer: 0,
    explanation: "After verbs like insist or demand, formal English uses the subjunctive base form: be.",
    quick: true,
  },
  {
    id: "ela-g12-11",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.8",
    skill: "Reasoning",
    prompt: "An argument that assumes its conclusion in its premise is...",
    choices: ["circular", "deductive", "inductive", "analogical"],
    answer: 0,
    explanation: "Circular reasoning, also called begging the question, goes around in a loop instead of proving anything.",
    quick: true,
  },
  {
    id: "ela-g12-12",
    subject: "ela",
    grade: "12",
    standard: "W.11-12.1",
    skill: "Argument writing",
    prompt: "Admitting the other side has a valid point is called a...",
    choices: ["concession", "thesis", "claim", "hook"],
    answer: 0,
    explanation: "A concession grants part of the opposing view, which builds credibility before a rebuttal.",
    quick: true,
  },
  {
    id: "ela-g12-13",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.5",
    skill: "Figures of speech",
    prompt: "'He's not unkind' is an example of...",
    choices: ["litotes", "hyperbole", "simile", "oxymoron"],
    answer: 0,
    explanation: "Litotes is understatement by denying the opposite: 'not unkind' means kind.",
    quick: true,
  },
  {
    id: "ela-g12-14",
    subject: "ela",
    grade: "12",
    standard: "RI.11-12.6",
    skill: "Satire and purpose",
    prompt: "What is the author's likely purpose?",
    passage: "Clearly, the best way to reduce library noise is to remove all the books. Without books, there will be nothing to discuss, and silence will finally reign.",
    choices: ["To satirize a foolish solution by exaggerating it", "To seriously propose removing books", "To describe a library's history", "To praise librarians"],
    answer: 0,
    explanation: "The absurd 'solution' is exaggerated on purpose to mock simple-minded fixes.",
  },
  {
    id: "ela-g12-15",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "The old clockmaker repaired every clock in the village but let his own stand still. 'Time,' he told his apprentice, 'is for other people.' When he died, the apprentice wound it for the first time, and its chime filled the empty shop.",
    choices: ["A life spent only serving others can go unlived.", "Clocks are difficult to repair.", "Apprentices should not touch tools.", "Villages depend on accurate time."],
    answer: 0,
    explanation: "The clockmaker kept everyone's time but his own; his clock chimes only after his death.",
  },
  {
    id: "ela-g12-16",
    subject: "ela",
    grade: "12",
    standard: "RL.11-12.4",
    skill: "Connotation",
    prompt: "What does the word loomed suggest about the mansion?",
    passage: "The mansion did not merely stand on the hill; it loomed, casting its long, cold shadow over the cottages below.",
    choices: ["a threatening, overpowering presence", "a warm and welcoming shelter", "a crumbling ruin", "a hidden location"],
    answer: 0,
    explanation: "Loomed connotes something large and menacing, reinforced by the 'long, cold shadow.'",
  },
  {
    id: "ela-g12-17",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.1",
    skill: "Dangling modifiers",
    prompt: "Which revision fixes 'Having finished the essay, the TV was turned on'?",
    choices: ["Having finished the essay, Lena turned on the TV.", "Having finished the essay, the TV was on.", "The TV, having finished the essay, was on.", "Having finished, the essay turned on the TV."],
    answer: 0,
    explanation: "The opening phrase must describe the person who finished the essay, so Lena must follow it.",
  },
  {
    id: "ela-g12-18",
    subject: "ela",
    grade: "12",
    standard: "L.11-12.4",
    skill: "Context clues",
    prompt: "What does loquacious most likely mean?",
    passage: "Though he was usually loquacious, holding forth for hours at dinner parties, Arthur fell silent when the letter arrived.",
    choices: ["talkative", "quiet", "generous", "forgetful"],
    answer: 0,
    explanation: "'Holding forth for hours' is a clue that loquacious means very talkative.",
  },
];

export default questions;
