import type { Question } from "../../types";

// Grade 2 ELA — NC Standard Course of Study for ELA (2017). RF.2.4 phonics (long/short vowels, vowel teams, two-syllable words), RL.2.2, RL.2.3, RI.2.2, RI.2.5, RI.2.6, L.2.1, L.2.2, L.2.4, L.2.5
const questions: Question[] = [
  {
    id: "ela-g2-01",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Long and short vowels",
    prompt: "Which word has a long o sound?",
    choices: ["boat", "hot", "top", "mop"],
    answer: 0,
    explanation: "In boat, the oa team makes the long o sound. Hot, top, and mop have short o.",
    quick: true,
  },
  {
    id: "ela-g2-02",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Long and short vowels",
    prompt: "Which word has a short i sound?",
    choices: ["fish", "kite", "pie", "tree"],
    answer: 0,
    explanation: "Fish has the short i sound, /i/. Kite and pie have long i.",
    quick: true,
  },
  {
    id: "ela-g2-03",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Vowel teams",
    prompt: "Which word has the same vowel sound as rain?",
    choices: ["play", "ran", "rip", "road"],
    answer: 0,
    explanation: "Rain (ai) and play (ay) both have the long a sound.",
    quick: true,
  },
  {
    id: "ela-g2-04",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Syllables",
    prompt: "How do you split rabbit into syllables?",
    choices: ["rab-bit", "ra-bbit", "rabb-it", "r-abbit"],
    answer: 0,
    explanation: "When two consonants are in the middle, split between them: rab-bit.",
    quick: true,
  },
  {
    id: "ela-g2-05",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular plurals",
    prompt: "What is the plural of mouse?",
    choices: ["mice", "mouses", "mousies", "meese"],
    answer: 0,
    explanation: "Mouse has a special plural: one mouse, two mice.",
    quick: true,
  },
  {
    id: "ela-g2-06",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular verbs",
    prompt: "Yesterday I ___ to the park. Which word fits?",
    choices: ["went", "goed", "go", "going"],
    answer: 0,
    explanation: "Went is the past tense of go. We never say goed.",
    quick: true,
  },
  {
    id: "ela-g2-07",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Collective nouns",
    prompt: "Which word names a group of fish?",
    choices: ["school", "herd", "flock", "pack"],
    answer: 0,
    explanation: "A group of fish is a school. A flock is birds and a herd is cows.",
    quick: true,
  },
  {
    id: "ela-g2-08",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Adjectives",
    prompt: "Which word is an adjective in 'The fluffy cat slept on the rug'?",
    choices: ["fluffy", "cat", "slept", "rug"],
    answer: 0,
    explanation: "Fluffy describes the cat, so it is an adjective.",
    quick: true,
  },
  {
    id: "ela-g2-09",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Contractions",
    prompt: "What is the contraction for do not?",
    choices: ["don't", "dont'", "do'nt", "dont"],
    answer: 0,
    explanation: "The apostrophe takes the place of the missing o: do not becomes don't.",
    quick: true,
  },
  {
    id: "ela-g2-10",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Possessives",
    prompt: "Which shows that the ball belongs to Ben?",
    choices: ["Ben's ball", "Bens ball", "Bens' ball", "Ben ball"],
    answer: 0,
    explanation: "Add an apostrophe and s to show something belongs to one person: Ben's.",
    quick: true,
  },
  {
    id: "ela-g2-11",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Prefixes",
    prompt: "What does unhappy mean?",
    choices: ["not happy", "very happy", "happy again", "happy before"],
    answer: 0,
    explanation: "The prefix un- means not, so unhappy means not happy.",
    quick: true,
  },
  {
    id: "ela-g2-12",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Compound words",
    prompt: "Which is a compound word?",
    choices: ["sunflower", "flower", "sunny", "flowers"],
    answer: 0,
    explanation: "Sunflower is made of two words put together: sun + flower.",
    quick: true,
  },
  {
    id: "ela-g2-13",
    subject: "ela",
    grade: "2",
    standard: "L.2.5",
    skill: "Shades of meaning",
    prompt: "Which word is the strongest way to say hot?",
    choices: ["scorching", "warm", "cool", "mild"],
    answer: 0,
    explanation: "Scorching means very, very hot. Warm is only a little hot.",
    quick: true,
  },
  {
    id: "ela-g2-14",
    subject: "ela",
    grade: "2",
    standard: "RL.2.2",
    skill: "Lesson of a story",
    prompt: "The lesson a fable teaches is called the...",
    choices: ["moral", "setting", "title", "rhyme"],
    answer: 0,
    explanation: "The moral is the lesson the story wants you to learn.",
    quick: true,
  },
  {
    id: "ela-g2-15",
    subject: "ela",
    grade: "2",
    standard: "RI.2.5",
    skill: "Text features",
    prompt: "What helps you find the meaning of a bold word in a book?",
    choices: ["glossary", "cover", "title page", "author name"],
    answer: 0,
    explanation: "A glossary is a small dictionary in the back of a book.",
    quick: true,
  },
  {
    id: "ela-g2-16",
    subject: "ela",
    grade: "2",
    standard: "RI.2.6",
    skill: "Author's purpose",
    prompt: "A book about how bees make honey is mostly meant to...",
    choices: ["inform", "entertain", "persuade", "rhyme"],
    answer: 0,
    explanation: "Books that teach facts are written to inform the reader.",
    quick: true,
  },
  {
    id: "ela-g2-17",
    subject: "ela",
    grade: "2",
    standard: "RL.2.3",
    skill: "Character response",
    prompt: "How did Mia respond when she tripped?",
    passage: "Mia wanted to win the class race. She practiced running every day after school. On race day, she tripped at the start. Mia got up, brushed off her knees, and kept running. She came in third, and she was proud she did not quit.",
    choices: ["She got up and kept running.", "She cried and went home.", "She asked to start over.", "She stopped the race."],
    answer: 0,
    explanation: "The story says Mia got up, brushed off her knees, and kept running.",
  },
  {
    id: "ela-g2-18",
    subject: "ela",
    grade: "2",
    standard: "RI.2.2",
    skill: "Main topic",
    prompt: "What is the main topic of this text?",
    passage: "Octopuses are clever sea animals. They can change color to hide from enemies. They can squeeze through tiny holes because they have no bones. Some octopuses even carry shells to use as shelters.",
    choices: ["How octopuses are clever", "What octopuses eat", "How to catch fish", "Where sharks live"],
    answer: 0,
    explanation: "Every sentence tells a clever thing octopuses can do.",
  },
];

export default questions;
