import type { Question } from "../../types";

// Grade 3 ELA — NC Standard Course of Study for ELA (2017). RL.3.1, RL.3.2, RL.3.3, RL.3.4, RL.3.5, RL.3.6, RI.3.1, RI.3.2, RI.3.3, RI.3.4, RI.3.5, RI.3.8, RI.3.9, RF.3.4, L.3.1, L.3.2, L.3.3, L.3.4, L.3.5
const questions: Question[] = [
  {
    id: "ela-g3-01",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does the prefix re- mean in reread?",
    choices: ["again", "not", "before", "under"],
    answer: 0,
    explanation: "Re- means again, so reread means read again.",
    quick: true,
  },
  {
    id: "ela-g3-02",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does careless mean?",
    choices: ["without care", "full of care", "cares again", "before care"],
    answer: 0,
    explanation: "The suffix -less means without, so careless means without care.",
    quick: true,
  },
  {
    id: "ela-g3-03",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes and suffixes",
    prompt: "What does helpful mean?",
    choices: ["full of help", "without help", "help again", "not help"],
    answer: 0,
    explanation: "The suffix -ful means full of, so helpful means full of help.",
    quick: true,
  },
  {
    id: "ela-g3-04",
    subject: "ela",
    grade: "3",
    standard: "L.3.5",
    skill: "Literal and nonliteral",
    prompt: "What does 'It's raining cats and dogs' mean?",
    choices: ["It's pouring", "Pets are out", "It's sunny", "It's snowing"],
    answer: 0,
    explanation: "This is an idiom. It means it is raining very hard, not that animals are falling.",
    quick: true,
  },
  {
    id: "ela-g3-05",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Comparatives",
    prompt: "My dog is ___ than your dog. Which word fits?",
    choices: ["bigger", "biggest", "more big", "big"],
    answer: 0,
    explanation: "Use -er to compare two things: bigger. Use -est for three or more.",
    quick: true,
  },
  {
    id: "ela-g3-06",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Irregular verbs",
    prompt: "What is the past tense of bring?",
    choices: ["brought", "bringed", "brang", "brung"],
    answer: 0,
    explanation: "Bring is irregular: today I bring, yesterday I brought.",
    quick: true,
  },
  {
    id: "ela-g3-07",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Subject-verb agreement",
    prompt: "Which sentence is correct?",
    choices: ["She runs fast.", "She run fast.", "She running.", "She are fast."],
    answer: 0,
    explanation: "A singular subject like she needs a verb with -s: She runs.",
    quick: true,
  },
  {
    id: "ela-g3-08",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Abstract nouns",
    prompt: "Which is an abstract noun (a feeling or idea)?",
    choices: ["bravery", "table", "river", "pencil"],
    answer: 0,
    explanation: "You cannot touch bravery. It is an idea, so it is an abstract noun.",
    quick: true,
  },
  {
    id: "ela-g3-09",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Possessives",
    prompt: "How do you show a toy belongs to more than one girl?",
    choices: ["girls' toy", "girl's toy", "girls toy", "girls's toy"],
    answer: 0,
    explanation: "For a plural noun ending in s, add only an apostrophe: girls'.",
    quick: true,
  },
  {
    id: "ela-g3-10",
    subject: "ela",
    grade: "3",
    standard: "RL.3.5",
    skill: "Parts of a poem",
    prompt: "What do we call a group of lines in a poem?",
    choices: ["stanza", "chapter", "scene", "paragraph"],
    answer: 0,
    explanation: "Poems are built from stanzas, like stories are built from paragraphs.",
    quick: true,
  },
  {
    id: "ela-g3-11",
    subject: "ela",
    grade: "3",
    standard: "RL.3.6",
    skill: "Point of view",
    prompt: "A story told with I and me is told in...",
    choices: ["first person", "third person", "second person", "the reader's"],
    answer: 0,
    explanation: "When the narrator says I and me, the story is in first person.",
    quick: true,
  },
  {
    id: "ela-g3-12",
    subject: "ela",
    grade: "3",
    standard: "RI.3.5",
    skill: "Text features",
    prompt: "Which feature tells what a section of text is about?",
    choices: ["heading", "caption", "index", "glossary"],
    answer: 0,
    explanation: "A heading is a title for a section. It tells what that part is about.",
    quick: true,
  },
  {
    id: "ela-g3-13",
    subject: "ela",
    grade: "3",
    standard: "RI.3.5",
    skill: "Text features",
    prompt: "Where would you look to find which page is about volcanoes?",
    choices: ["index", "glossary", "title", "caption"],
    answer: 0,
    explanation: "An index lists topics in ABC order with their page numbers.",
    quick: true,
  },
  {
    id: "ela-g3-14",
    subject: "ela",
    grade: "3",
    standard: "RL.3.2",
    skill: "Central message",
    prompt: "The big idea a fable wants you to learn is its...",
    choices: ["lesson", "setting", "title", "character"],
    answer: 0,
    explanation: "A fable's lesson, or moral, is its central message.",
    quick: true,
  },
  {
    id: "ela-g3-15",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Context clues",
    prompt: "What does fragile most likely mean?",
    passage: "The old bridge was fragile. When Leo stepped on the first board, it cracked, and a piece fell into the creek below. He decided to walk the long way around.",
    choices: ["easily broken", "very long", "brand new", "painted brightly"],
    answer: 0,
    explanation: "The board cracked and fell, which is a clue that fragile means easily broken.",
  },
  {
    id: "ela-g3-16",
    subject: "ela",
    grade: "3",
    standard: "RI.3.2",
    skill: "Main idea",
    prompt: "What is the main idea of this text?",
    passage: "Honeybees work as a team. Some bees gather nectar from flowers. Others guard the hive from enemies. Young bees clean the cells and feed the babies. Every bee has a job that helps the whole hive survive.",
    choices: ["Honeybees work together in jobs.", "Bees gather nectar.", "Bees have enemies.", "Hives are made of wax."],
    answer: 0,
    explanation: "Each detail names a job, and the last sentence sums up the main idea.",
  },
  {
    id: "ela-g3-17",
    subject: "ela",
    grade: "3",
    standard: "RL.3.3",
    skill: "Character traits",
    prompt: "Which word best describes Marcus?",
    passage: "When the new girl, Ana, sat alone at lunch, Marcus picked up his tray and sat beside her. He asked her about her old school and shared his cookies. By the end of lunch, Ana was laughing.",
    choices: ["kind", "shy", "bossy", "sleepy"],
    answer: 0,
    explanation: "Marcus sits with Ana and shares his cookies. His actions show he is kind.",
  },
  {
    id: "ela-g3-18",
    subject: "ela",
    grade: "3",
    standard: "RI.3.8",
    skill: "Cause and effect",
    prompt: "Why did the frogs move to the creek?",
    passage: "Last spring, it did not rain for six weeks. The pond behind the farm got smaller and smaller. The frogs that lived there moved to the creek, where there was still water.",
    choices: ["The pond was drying up.", "The creek was too cold.", "A farmer chased them.", "They wanted to eat fish."],
    answer: 0,
    explanation: "No rain made the pond shrink (cause), so the frogs moved (effect).",
  },
  {
    id: "ela-g3-19",
    subject: "ela",
    grade: "3",
    standard: "RF.3.4",
    skill: "Prefixes",
    prompt: "What does the prefix dis- mean in disagree?",
    choices: ["not", "again", "before", "very"],
    answer: 0,
    explanation: "Dis- means not, so disagree means not agree.",
    quick: true,
  },
  {
    id: "ela-g3-20",
    subject: "ela",
    grade: "3",
    standard: "RF.3.4",
    skill: "Suffixes",
    prompt: "What does washable mean?",
    choices: ["can be washed", "was washed", "not washed", "washing now"],
    answer: 0,
    explanation: "The suffix -able means can be, so washable means it can be washed.",
    quick: true,
  },
  {
    id: "ela-g3-21",
    subject: "ela",
    grade: "3",
    standard: "RF.3.4",
    skill: "Syllables",
    prompt: "How many syllables are in fantastic?",
    choices: ["3", "2", "4", "5"],
    answer: 0,
    explanation: "Fan-tas-tic has three syllables.",
    quick: true,
  },
  {
    id: "ela-g3-22",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Spelling",
    prompt: "Which word is spelled correctly?",
    choices: ["because", "becuz", "becaus", "beacuse"],
    answer: 0,
    explanation: "Because is spelled b-e-c-a-u-s-e.",
    quick: true,
  },
  {
    id: "ela-g3-23",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Irregular verbs",
    prompt: "What is the past tense of swim?",
    choices: ["swam", "swimmed", "swum", "swimed"],
    answer: 0,
    explanation: "Today I swim; yesterday I swam. Swum needs a helper, as in 'have swum.'",
    quick: true,
  },
  {
    id: "ela-g3-24",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Comparative adverbs",
    prompt: "Mia ran ___ than Leo. Which word fits?",
    choices: ["faster", "fastest", "more fast", "fastly"],
    answer: 0,
    explanation: "Use faster to compare two people. Fastest compares three or more.",
    quick: true,
  },
  {
    id: "ela-g3-25",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Conjunctions",
    prompt: "We stayed inside ___ it was storming. Which word fits?",
    choices: ["because", "but", "or", "unless"],
    answer: 0,
    explanation: "Because tells why we stayed inside.",
    quick: true,
  },
  {
    id: "ela-g3-26",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Homophones",
    prompt: "I can't ___ for my party! Which word fits?",
    choices: ["wait", "weight", "wate", "whait"],
    answer: 0,
    explanation: "Wait means to stay until something happens. Weight is how heavy something is.",
    quick: true,
  },
  {
    id: "ela-g3-27",
    subject: "ela",
    grade: "3",
    standard: "L.3.1",
    skill: "Adverbs",
    prompt: "In 'She sang loudly,' what part of speech is loudly?",
    choices: ["adverb", "adjective", "noun", "verb"],
    answer: 0,
    explanation: "Loudly tells how she sang, so it is an adverb.",
    quick: true,
  },
  {
    id: "ela-g3-28",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Capitalizing titles",
    prompt: "Which book title is capitalized correctly?",
    choices: ["The Big Race", "The big race", "the Big Race", "The big Race"],
    answer: 0,
    explanation: "Capitalize the first word and the important words in a title.",
    quick: true,
  },
  {
    id: "ela-g3-29",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Commas in addresses",
    prompt: "Which city and state are written correctly?",
    choices: ["Durham, NC", "Durham NC,", "Durham, nc", "durham, NC"],
    answer: 0,
    explanation: "Put a comma between the city and the state, and capitalize both.",
    quick: true,
  },
  {
    id: "ela-g3-30",
    subject: "ela",
    grade: "3",
    standard: "L.3.2",
    skill: "Possessives",
    prompt: "Which shows the bone that belongs to one dog?",
    choices: ["dog's bone", "dogs bone", "dogs' bone", "dog bone's"],
    answer: 0,
    explanation: "For one owner, add an apostrophe and s: dog's.",
    quick: true,
  },
  {
    id: "ela-g3-31",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Prefixes",
    prompt: "What does the prefix pre- mean in preview?",
    choices: ["before", "after", "again", "not"],
    answer: 0,
    explanation: "Pre- means before. A preview is a look before something comes out.",
    quick: true,
  },
  {
    id: "ela-g3-32",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Suffixes",
    prompt: "A person who teaches is a teacher. A person who farms is a...",
    choices: ["farmer", "farming", "farmed", "farmable"],
    answer: 0,
    explanation: "The suffix -er can mean a person who does something.",
    quick: true,
  },
  {
    id: "ela-g3-33",
    subject: "ela",
    grade: "3",
    standard: "L.3.5",
    skill: "Literal and nonliteral",
    prompt: "What does 'I'm all ears' mean?",
    choices: ["I'm listening", "My ears hurt", "I'm tired", "I'm hungry"],
    answer: 0,
    explanation: "'I'm all ears' is a saying that means you are listening closely.",
    quick: true,
  },
  {
    id: "ela-g3-34",
    subject: "ela",
    grade: "3",
    standard: "L.3.5",
    skill: "Degrees of certainty",
    prompt: "Which word shows you are MOST sure?",
    choices: ["definitely", "maybe", "probably", "possibly"],
    answer: 0,
    explanation: "Definitely means for sure. Maybe and possibly show you are not sure.",
    quick: true,
  },
  {
    id: "ela-g3-35",
    subject: "ela",
    grade: "3",
    standard: "L.3.5",
    skill: "Shades of meaning",
    prompt: "Which word means the most upset?",
    choices: ["furious", "annoyed", "bothered", "calm"],
    answer: 0,
    explanation: "Furious means very, very angry. Annoyed and bothered are only a little upset.",
    quick: true,
  },
  {
    id: "ela-g3-36",
    subject: "ela",
    grade: "3",
    standard: "L.3.3",
    skill: "Word choice",
    prompt: "Which verb paints the clearest picture? The horse ___ across the field.",
    choices: ["galloped", "went", "moved", "got"],
    answer: 0,
    explanation: "Galloped shows exactly how the horse moved.",
    quick: true,
  },
  {
    id: "ela-g3-37",
    subject: "ela",
    grade: "3",
    standard: "RL.3.5",
    skill: "Parts of a play",
    prompt: "A part of a play that happens in one place and time is a...",
    choices: ["scene", "chapter", "stanza", "verse"],
    answer: 0,
    explanation: "Plays are split into scenes. Books have chapters, and poems have stanzas.",
    quick: true,
  },
  {
    id: "ela-g3-38",
    subject: "ela",
    grade: "3",
    standard: "RI.3.5",
    skill: "Text features",
    prompt: "Which feature lists important words and their meanings?",
    choices: ["glossary", "index", "title", "caption"],
    answer: 0,
    explanation: "A glossary, near the back of a book, tells what key words mean.",
    quick: true,
  },
  {
    id: "ela-g3-39",
    subject: "ela",
    grade: "3",
    standard: "RL.3.1",
    skill: "Answering with the text",
    prompt: "Why did Ava pick a button each visit?",
    passage: "Grandpa Joe kept a jar of buttons on his workbench. Every time Ava visited, she picked one button, and he told her the story of the coat or shirt it came from.",
    choices: ["To hear its story.", "To sew a new coat.", "To sell the buttons.", "To fill a new jar."],
    answer: 0,
    explanation: "The text says Grandpa told her the story of where each button came from.",
  },
  {
    id: "ela-g3-40",
    subject: "ela",
    grade: "3",
    standard: "RL.3.2",
    skill: "Central message",
    prompt: "What is the central message?",
    passage: "Hare laughed at Snail for being slow. 'Let's see who reaches the river first,' said Snail. Hare raced ahead but stopped to brag to every animal he met. Snail never stopped moving, and he got there first.",
    choices: ["Steady effort beats bragging.", "Snails are fast.", "Rivers are far away.", "Never race a friend."],
    answer: 0,
    explanation: "Hare kept stopping to brag, while Snail never stopped moving and won.",
  },
  {
    id: "ela-g3-41",
    subject: "ela",
    grade: "3",
    standard: "RL.3.3",
    skill: "Character actions",
    prompt: "How did Keisha's action cause the problem?",
    passage: "Keisha forgot to close the gate. While she watched TV, the goats wandered into Mrs. Lee's garden and ate every tomato.",
    choices: ["The open gate let the goats out.", "She fed the goats tomatoes.", "She took the goats for a walk.", "She planted the garden."],
    answer: 0,
    explanation: "Keisha forgot to close the gate, so the goats got out and ate the tomatoes.",
  },
  {
    id: "ela-g3-42",
    subject: "ela",
    grade: "3",
    standard: "RL.3.4",
    skill: "Word meaning",
    prompt: "What does pounced mean?",
    passage: "The kitten crept toward the ball of yarn, then pounced, landing on it with all four paws.",
    choices: ["jumped suddenly onto", "slept on", "ran away from", "looked at"],
    answer: 0,
    explanation: "The kitten crept up, then landed on the yarn with all four paws. It jumped on it suddenly.",
  },
  {
    id: "ela-g3-43",
    subject: "ela",
    grade: "3",
    standard: "RI.3.3",
    skill: "Cause and effect",
    prompt: "What caused the road to flood?",
    passage: "Heavy rain fell for three days. The creek rose over its banks, and water flooded the road. The town closed the road until the water went down.",
    choices: ["The creek rose from heavy rain.", "The town closed the road.", "A pipe broke.", "Snow melted."],
    answer: 0,
    explanation: "Three days of rain made the creek rise over its banks and onto the road.",
  },
  {
    id: "ela-g3-44",
    subject: "ela",
    grade: "3",
    standard: "RI.3.4",
    skill: "Science words",
    prompt: "What is photosynthesis?",
    passage: "Plants make their own food through photosynthesis. They use sunlight, water, and air to make sugar.",
    choices: ["how plants make food", "how plants grow roots", "how seeds travel", "how leaves fall"],
    answer: 0,
    explanation: "The text says plants make their own food through photosynthesis.",
  },
  {
    id: "ela-g3-45",
    subject: "ela",
    grade: "3",
    standard: "RI.3.9",
    skill: "Comparing texts",
    prompt: "What do both texts tell about?",
    passage: "Text A: Sea turtles lay their eggs on sandy beaches at night.\nText B: Baby sea turtles hatch and crawl toward the bright ocean.",
    choices: ["sea turtles", "fish", "the moon", "sandcastles"],
    answer: 0,
    explanation: "Both texts give facts about sea turtles.",
  },
  {
    id: "ela-g3-46",
    subject: "ela",
    grade: "3",
    standard: "RI.3.1",
    skill: "Key details",
    prompt: "How did riders move the first bicycles?",
    passage: "The first bicycles had no pedals. Riders sat on the seat and pushed along the ground with their feet. Later, pedals were added to the front wheel.",
    choices: ["They pushed with their feet.", "They used pedals.", "They used a motor.", "A horse pulled them."],
    answer: 0,
    explanation: "The text says the first bicycles had no pedals, so riders pushed with their feet.",
  },
  {
    id: "ela-g3-47",
    subject: "ela",
    grade: "3",
    standard: "RL.3.6",
    skill: "Narrator's point of view",
    prompt: "How does the narrator feel about camping?",
    passage: "I hate camping. The tent is lumpy, the bugs bite, and there's no TV. Still, the stars tonight are kind of amazing.",
    choices: ["Mostly dislikes it but likes the stars.", "Loves every part of it.", "Has never been camping.", "Is afraid of the stars."],
    answer: 0,
    explanation: "The narrator complains about the tent and bugs but says the stars are amazing.",
  },
  {
    id: "ela-g3-48",
    subject: "ela",
    grade: "3",
    standard: "L.3.4",
    skill: "Context clues",
    prompt: "What does timid mean?",
    passage: "Our dog is very timid. He hides under the bed whenever the doorbell rings.",
    choices: ["shy and easily scared", "loud", "hungry", "playful"],
    answer: 0,
    explanation: "Hiding under the bed when the doorbell rings is a clue that timid means shy and easily scared.",
  },
];

export default questions;
