import type { Question } from "../../types";

// Grade 4 ELA — NC Standard Course of Study for ELA (2017). L.4.1, L.4.4 (Greek/Latin roots, context), L.4.5 (simile, metaphor, idioms, antonyms), RL.4.1, RL.4.2, RL.4.5, RL.4.6, RI.4.2, RI.4.5
const questions: Question[] = [
  {
    id: "ela-g4-01",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root graph (as in autograph) means...",
    choices: ["write", "see", "hear", "carry"],
    answer: 0,
    explanation: "Graph means write. An autograph is a name you write yourself.",
    quick: true,
  },
  {
    id: "ela-g4-02",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root tele (as in telephone) means...",
    choices: ["far", "sound", "near", "light"],
    answer: 0,
    explanation: "Tele means far. A telephone carries sound from far away.",
    quick: true,
  },
  {
    id: "ela-g4-03",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root port (as in transport) means...",
    choices: ["carry", "look", "build", "break"],
    answer: 0,
    explanation: "Port means carry. To transport something is to carry it across.",
    quick: true,
  },
  {
    id: "ela-g4-04",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Similes and metaphors",
    prompt: "Which phrase is a simile?",
    choices: ["like a rocket", "a red rocket", "the rocket", "rockets fly"],
    answer: 0,
    explanation: "A simile compares two things using like or as.",
    quick: true,
  },
  {
    id: "ela-g4-05",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Similes and metaphors",
    prompt: "'The classroom was a zoo.' This is a...",
    choices: ["metaphor", "simile", "rhyme", "fact"],
    answer: 0,
    explanation: "A metaphor compares without like or as: the room is called a zoo because it's wild.",
    quick: true,
  },
  {
    id: "ela-g4-06",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Idioms",
    prompt: "What does 'break the ice' mean?",
    choices: ["start talking", "smash a glass", "feel cold", "skate fast"],
    answer: 0,
    explanation: "To break the ice means to help people relax and start talking.",
    quick: true,
  },
  {
    id: "ela-g4-07",
    subject: "ela",
    grade: "4",
    standard: "L.4.5",
    skill: "Antonyms",
    prompt: "Which word is an antonym of ancient?",
    choices: ["modern", "old", "antique", "huge"],
    answer: 0,
    explanation: "Antonyms are opposites. Ancient means very old; modern means new.",
    quick: true,
  },
  {
    id: "ela-g4-08",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Relative pronouns",
    prompt: "The boy ___ won the race is my cousin. Which word fits?",
    choices: ["who", "which", "what", "whom"],
    answer: 0,
    explanation: "Use who for a person doing the action. Which is for things.",
    quick: true,
  },
  {
    id: "ela-g4-09",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Progressive verb tense",
    prompt: "Which verb is in the present progressive tense?",
    choices: ["is running", "ran", "runs", "will run"],
    answer: 0,
    explanation: "The present progressive (is + -ing) shows an action happening right now.",
    quick: true,
  },
  {
    id: "ela-g4-10",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Confused words",
    prompt: "___ going to the game tonight. Which word fits?",
    choices: ["They're", "Their", "There", "Thier"],
    answer: 0,
    explanation: "They're is short for they are. Their shows ownership; there is a place.",
    quick: true,
  },
  {
    id: "ela-g4-11",
    subject: "ela",
    grade: "4",
    standard: "L.4.1",
    skill: "Prepositional phrases",
    prompt: "Which is a prepositional phrase?",
    choices: ["under the bed", "the red bed", "very sleepy", "and then"],
    answer: 0,
    explanation: "A prepositional phrase starts with a preposition, like under, and ends with a noun.",
    quick: true,
  },
  {
    id: "ela-g4-12",
    subject: "ela",
    grade: "4",
    standard: "RL.4.6",
    skill: "Point of view",
    prompt: "A narrator using he, she, and they tells the story in...",
    choices: ["third person", "first person", "second person", "dialogue"],
    answer: 0,
    explanation: "A third-person narrator is outside the story and uses he, she, and they.",
    quick: true,
  },
  {
    id: "ela-g4-13",
    subject: "ela",
    grade: "4",
    standard: "RL.4.5",
    skill: "Drama",
    prompt: "The parts that a play is divided into are called...",
    choices: ["scenes", "stanzas", "chapters", "verses"],
    answer: 0,
    explanation: "Plays are divided into acts and scenes. Poems have stanzas; novels have chapters.",
    quick: true,
  },
  {
    id: "ela-g4-14",
    subject: "ela",
    grade: "4",
    standard: "RI.4.5",
    skill: "Text structure",
    prompt: "A text telling what happened first, next, and last is...",
    choices: ["chronological", "comparison", "cause/effect", "description"],
    answer: 0,
    explanation: "Chronological structure tells events in time order.",
    quick: true,
  },
  {
    id: "ela-g4-15",
    subject: "ela",
    grade: "4",
    standard: "RL.4.2",
    skill: "Theme",
    prompt: "What is the theme of this story?",
    passage: "Rosa practiced piano for weeks, but at the recital her fingers shook and she missed three notes. Afterward, her teacher said, 'You kept playing when it was hard. That takes courage.' Rosa realized that finishing mattered more than being perfect.",
    choices: ["Finishing matters more than being perfect.", "Music is hard to learn.", "Teachers are always right.", "Recitals should be canceled."],
    answer: 0,
    explanation: "Rosa's realization at the end points to the theme: finishing with courage matters more than perfection.",
  },
  {
    id: "ela-g4-16",
    subject: "ela",
    grade: "4",
    standard: "L.4.4",
    skill: "Context clues",
    prompt: "What does frugal most likely mean?",
    passage: "Grandpa is so frugal that he reuses wrapping paper, fixes his own shoes, and never buys anything that is not on sale.",
    choices: ["careful with money", "very generous", "often angry", "good at sports"],
    answer: 0,
    explanation: "Reusing paper, fixing shoes, and buying only on sale are clues that frugal means careful with money.",
  },
  {
    id: "ela-g4-17",
    subject: "ela",
    grade: "4",
    standard: "RI.4.2",
    skill: "Main idea",
    prompt: "What is the main idea of this text?",
    passage: "Sea turtles face many dangers. Plastic bags in the ocean look like jellyfish, so turtles may eat them. Bright lights on beaches confuse baby turtles and lead them away from the sea. People can help by picking up trash and turning off beach lights at night.",
    choices: ["Sea turtles face dangers people can reduce.", "Turtles like to eat jellyfish.", "Beaches are too bright at night.", "Plastic bags are useful."],
    answer: 0,
    explanation: "The text names dangers and then explains how people can help. That is the main idea.",
  },
  {
    id: "ela-g4-18",
    subject: "ela",
    grade: "4",
    standard: "RL.4.1",
    skill: "Making inferences",
    prompt: "How does Jamal most likely feel?",
    passage: "Jamal stared at the clock. He tapped his pencil, then checked the door again. When the bell finally rang, he grabbed his bag and raced to the bus to see his grandmother, who was visiting from Ghana.",
    choices: ["eager", "bored", "angry", "sleepy"],
    answer: 0,
    explanation: "Watching the clock and racing to the bus are clues that Jamal is eager to see his grandmother.",
  },
];

export default questions;
