import type { Question } from "../../types";

// Grade 6 ELA — NC Standard Course of Study for ELA (2017). L.6.1 (pronoun case, intensive, vague pronouns), L.6.4 roots, L.6.5 (figurative, connotation, analogies), RL.6.2, RL.6.3, RL.6.4, RL.6.6, RI.6.5, RI.6.6, RI.6.8, W.6.1
const questions: Question[] = [
  {
    id: "ela-g6-01",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun case",
    prompt: "Maya and ___ went to the store. Which pronoun fits?",
    choices: ["I", "me", "myself", "mine"],
    answer: 0,
    explanation: "Use the subject pronoun I. Test it alone: I went to the store.",
    quick: true,
  },
  {
    id: "ela-g6-02",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Pronoun case",
    prompt: "The coach gave the award to Jordan and ___.",
    choices: ["me", "I", "myself", "mine"],
    answer: 0,
    explanation: "After a preposition like to, use the object pronoun me: gave it to me.",
    quick: true,
  },
  {
    id: "ela-g6-03",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Intensive pronouns",
    prompt: "In 'I built the shed myself,' what kind of pronoun is myself?",
    choices: ["intensive", "possessive", "objective", "relative"],
    answer: 0,
    explanation: "An intensive pronoun adds emphasis. The sentence still works without it.",
    quick: true,
  },
  {
    id: "ela-g6-04",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root chron (as in chronological) means...",
    choices: ["time", "color", "sound", "city"],
    answer: 0,
    explanation: "Chron means time. Chronological order is time order.",
    quick: true,
  },
  {
    id: "ela-g6-05",
    subject: "ela",
    grade: "6",
    standard: "L.6.4",
    skill: "Greek and Latin roots",
    prompt: "The root geo (as in geology) means...",
    choices: ["earth", "life", "star", "water"],
    answer: 0,
    explanation: "Geo means earth. Geology is the study of Earth's rocks and layers.",
    quick: true,
  },
  {
    id: "ela-g6-06",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "Which word has the most positive connotation?",
    choices: ["thrifty", "cheap", "stingy", "miserly"],
    answer: 0,
    explanation: "All four mean careful with money, but thrifty sounds wise while the others sound negative.",
    quick: true,
  },
  {
    id: "ela-g6-07",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Connotation",
    prompt: "Which is a negative way to describe a curious person?",
    choices: ["nosy", "inquisitive", "interested", "eager"],
    answer: 0,
    explanation: "Nosy suggests poking into things that aren't your business, a negative connotation.",
    quick: true,
  },
  {
    id: "ela-g6-08",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Analogies",
    prompt: "Finger is to hand as toe is to...",
    choices: ["foot", "leg", "shoe", "nail"],
    answer: 0,
    explanation: "This is a part-to-whole analogy: a finger is part of a hand; a toe is part of a foot.",
    quick: true,
  },
  {
    id: "ela-g6-09",
    subject: "ela",
    grade: "6",
    standard: "L.6.5",
    skill: "Figurative language",
    prompt: "'Her words were daggers.' The metaphor suggests her words were...",
    choices: ["hurtful", "funny", "shiny", "quiet"],
    answer: 0,
    explanation: "Daggers cut, so the metaphor means her words hurt.",
    quick: true,
  },
  {
    id: "ela-g6-10",
    subject: "ela",
    grade: "6",
    standard: "RL.6.6",
    skill: "Point of view",
    prompt: "A narrator who is a character and uses I tells the story in...",
    choices: ["first person", "third person", "omniscient", "second person"],
    answer: 0,
    explanation: "When a character tells the story using I, it is first-person point of view.",
    quick: true,
  },
  {
    id: "ela-g6-11",
    subject: "ela",
    grade: "6",
    standard: "RI.6.5",
    skill: "Text structure",
    prompt: "Which structure best fits a text on why dinosaurs died out?",
    choices: ["cause/effect", "chronology", "comparison", "description"],
    answer: 0,
    explanation: "Explaining why something happened is cause-and-effect structure.",
    quick: true,
  },
  {
    id: "ela-g6-12",
    subject: "ela",
    grade: "6",
    standard: "W.6.1",
    skill: "Argument writing",
    prompt: "In an argument, the writer's main position is the...",
    choices: ["claim", "evidence", "hook", "summary"],
    answer: 0,
    explanation: "The claim is the position the writer argues. Evidence and reasons support it.",
    quick: true,
  },
  {
    id: "ela-g6-13",
    subject: "ela",
    grade: "6",
    standard: "RL.6.2",
    skill: "Theme",
    prompt: "A story's theme is best described as its...",
    choices: ["life lesson", "setting", "main event", "title"],
    answer: 0,
    explanation: "A theme is a message about life that the story develops, not a single event.",
    quick: true,
  },
  {
    id: "ela-g6-14",
    subject: "ela",
    grade: "6",
    standard: "RL.6.4",
    skill: "Mood and word choice",
    prompt: "Which word best describes the mood of this passage?",
    passage: "The house sat at the end of the lane, its windows dark and cracked. Wind moaned through the gaps in the boards, and a single shutter banged, again and again, like someone knocking to get in.",
    choices: ["eerie", "cheerful", "peaceful", "silly"],
    answer: 0,
    explanation: "Words like dark, cracked, moaned, and knocking create an eerie, spooky mood.",
  },
  {
    id: "ela-g6-15",
    subject: "ela",
    grade: "6",
    standard: "RI.6.8",
    skill: "Claims and evidence",
    prompt: "Which statement is an opinion with no evidence to support it?",
    passage: "Schools should start later in the morning. Studies of teenagers show that their sleep cycles shift, making it hard to fall asleep early. One district that moved its start time to 8:30 reported better attendance and higher grades. Besides, everyone enjoys sleeping in.",
    choices: ["Everyone enjoys sleeping in.", "Teen sleep cycles shift later.", "Attendance improved in one district.", "Grades rose in one district."],
    answer: 0,
    explanation: "The other statements come from studies or reports. 'Everyone enjoys sleeping in' is an unsupported opinion.",
  },
  {
    id: "ela-g6-16",
    subject: "ela",
    grade: "6",
    standard: "L.6.1",
    skill: "Vague pronouns",
    prompt: "Which sentence has a vague (unclear) pronoun?",
    choices: ["When Ana met Lily, she was nervous.", "Ana was nervous about meeting Lily.", "The dog wagged its tail at Ana.", "Marcus lost his hat at the park."],
    answer: 0,
    explanation: "In the first sentence, she could mean Ana or Lily, so the pronoun is vague.",
  },
  {
    id: "ela-g6-17",
    subject: "ela",
    grade: "6",
    standard: "RL.6.3",
    skill: "Character response",
    prompt: "What does Priya's response reveal about her?",
    passage: "Priya had rehearsed her speech for student council all week. The morning of the election, she discovered her note cards were missing. With minutes to go, she took a breath, walked to the podium, and spoke from memory about the ideas she truly cared about.",
    choices: ["She stays calm under pressure.", "She is careless and forgetful.", "She dislikes public speaking.", "She wants to quit the election."],
    answer: 0,
    explanation: "Instead of panicking, Priya breathes and speaks from memory, showing she is calm and resourceful.",
  },
  {
    id: "ela-g6-18",
    subject: "ela",
    grade: "6",
    standard: "RI.6.6",
    skill: "Author's purpose",
    prompt: "What is the author's main purpose?",
    passage: "Plastic straws might seem harmless, but millions end up in oceans each year, where they can injure sea animals. Switching to paper or metal straws is an easy change that every restaurant should make today.",
    choices: ["to persuade", "to entertain", "to explain how straws are made", "to tell a story"],
    answer: 0,
    explanation: "The words 'every restaurant should' show the author is trying to persuade.",
  },
];

export default questions;
