import type { Question } from "../../types";

// Grade 7 ELA — NC Standard Course of Study for ELA (2017). L.7.1 (phrases, clauses, sentence types, misplaced modifiers), L.7.4 roots/affixes/context, L.7.5 (allusion, connotation, analogies), RL.7.2, RL.7.4, RL.7.6, RI.7.8, W.7.1
const questions: Question[] = [
  {
    id: "ela-g7-01",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Phrases and clauses",
    prompt: "Which is a dependent clause?",
    choices: ["when it rained", "the dog barked", "I ran home", "she smiled"],
    answer: 0,
    explanation: "A dependent clause has a subject and verb but can't stand alone. 'When it rained' needs more.",
    quick: true,
  },
  {
    id: "ela-g7-02",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Sentence types",
    prompt: "'I ran, and she walked.' What type of sentence is this?",
    choices: ["compound", "simple", "complex", "fragment"],
    answer: 0,
    explanation: "Two independent clauses joined by a comma and 'and' make a compound sentence.",
    quick: true,
  },
  {
    id: "ela-g7-03",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Sentence types",
    prompt: "'Although it was late, we kept reading.' What type of sentence is this?",
    choices: ["complex", "simple", "compound", "run-on"],
    answer: 0,
    explanation: "A dependent clause (Although it was late) plus an independent clause makes a complex sentence.",
    quick: true,
  },
  {
    id: "ela-g7-04",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Phrases and clauses",
    prompt: "Which is a phrase, not a clause?",
    choices: ["in the morning", "we ate lunch", "she laughed", "if he calls"],
    answer: 0,
    explanation: "A phrase has no subject-verb pair. 'In the morning' is a prepositional phrase.",
    quick: true,
  },
  {
    id: "ela-g7-05",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root bene (as in benefit) means...",
    choices: ["good", "bad", "war", "ten"],
    answer: 0,
    explanation: "Bene means good or well. A benefit is something good.",
    quick: true,
  },
  {
    id: "ela-g7-06",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Prefixes",
    prompt: "The prefix anti- (as in antifreeze) means...",
    choices: ["against", "before", "many", "after"],
    answer: 0,
    explanation: "Anti- means against. Antifreeze works against freezing.",
    quick: true,
  },
  {
    id: "ela-g7-07",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Allusion",
    prompt: "Calling a strong person 'a Hercules' is an example of...",
    choices: ["allusion", "simile", "pun", "oxymoron"],
    answer: 0,
    explanation: "An allusion refers to a well-known story or figure, here the hero of Greek myth.",
    quick: true,
  },
  {
    id: "ela-g7-08",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Connotation",
    prompt: "Which word describes confidence in a positive way?",
    choices: ["self-assured", "arrogant", "cocky", "smug"],
    answer: 0,
    explanation: "Arrogant, cocky, and smug all suggest too much pride. Self-assured is positive.",
    quick: true,
  },
  {
    id: "ela-g7-09",
    subject: "ela",
    grade: "7",
    standard: "L.7.5",
    skill: "Analogies",
    prompt: "Author is to novel as composer is to...",
    choices: ["symphony", "piano", "singer", "book"],
    answer: 0,
    explanation: "This is a creator-to-creation analogy: an author writes a novel; a composer writes a symphony.",
    quick: true,
  },
  {
    id: "ela-g7-10",
    subject: "ela",
    grade: "7",
    standard: "RL.7.4",
    skill: "Sound devices",
    prompt: "'Seven silly snakes slid south' is an example of...",
    choices: ["alliteration", "rhyme", "metaphor", "irony"],
    answer: 0,
    explanation: "Alliteration repeats the same beginning consonant sound in nearby words.",
    quick: true,
  },
  {
    id: "ela-g7-11",
    subject: "ela",
    grade: "7",
    standard: "RL.7.6",
    skill: "Point of view",
    prompt: "When characters see the same event differently, they have different...",
    choices: ["points of view", "settings", "plots", "authors"],
    answer: 0,
    explanation: "Point of view is how a character sees and feels about events.",
    quick: true,
  },
  {
    id: "ela-g7-12",
    subject: "ela",
    grade: "7",
    standard: "W.7.1",
    skill: "Argument writing",
    prompt: "In an argument, an opposing viewpoint is called a...",
    choices: ["counterclaim", "thesis", "reason", "conclusion"],
    answer: 0,
    explanation: "A counterclaim is the other side's position. Strong arguments acknowledge and answer it.",
    quick: true,
  },
  {
    id: "ela-g7-13",
    subject: "ela",
    grade: "7",
    standard: "W.7.1",
    skill: "Transitions",
    prompt: "Which transition signals a contrast?",
    choices: ["however", "also", "first", "for example"],
    answer: 0,
    explanation: "However signals a turn to a different or opposite idea.",
    quick: true,
  },
  {
    id: "ela-g7-14",
    subject: "ela",
    grade: "7",
    standard: "L.7.1",
    skill: "Misplaced modifiers",
    prompt: "Which sentence has a misplaced modifier?",
    choices: ["I saw a deer driving to school.", "Driving to school, I saw a deer.", "I saw a deer while driving to school.", "While I drove to school, I saw a deer."],
    answer: 0,
    explanation: "In the first sentence, 'driving to school' sits next to deer, so it sounds like the deer is driving.",
  },
  {
    id: "ela-g7-15",
    subject: "ela",
    grade: "7",
    standard: "RL.7.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "Every year, Eli's grandfather planted an oak sapling, though he knew he would never sit in its shade. 'Why bother?' Eli asked. His grandfather smiled and pointed to the tall oaks around their farm. 'Someone planted these for me.'",
    choices: ["We should give to the future, as others gave to us.", "Oak trees grow very fast.", "Farming is too difficult.", "Grandparents know everything."],
    answer: 0,
    explanation: "The grandfather plants trees for people after him because someone did the same for him.",
  },
  {
    id: "ela-g7-16",
    subject: "ela",
    grade: "7",
    standard: "RI.7.8",
    skill: "Evaluating arguments",
    prompt: "What is the biggest weakness in this argument?",
    passage: "Our school should ban homework on weekends. My friend said she was tired on Monday because of homework. Also, a famous athlete once said rest is important. Therefore, weekend homework clearly harms all students.",
    choices: ["Weak evidence leads to a broad conclusion.", "It does not state a claim.", "It uses too many statistics.", "It is written in first person."],
    answer: 0,
    explanation: "One friend's experience and a vague quote can't prove homework 'clearly harms all students.'",
  },
  {
    id: "ela-g7-17",
    subject: "ela",
    grade: "7",
    standard: "RL.7.6",
    skill: "Point of view",
    prompt: "How do the characters' points of view differ?",
    passage: "To Carla, the storm was an adventure. She pressed her face to the window, counting lightning flashes. Her little brother, Tomas, hid under a blanket, sure that each thunderclap meant the roof would fall.",
    choices: ["Carla is excited; Tomas is afraid.", "Both are afraid.", "Carla is afraid; Tomas is excited.", "Both are bored."],
    answer: 0,
    explanation: "Carla counts lightning like an adventure, while Tomas hides, sure the roof will fall.",
  },
  {
    id: "ela-g7-18",
    subject: "ela",
    grade: "7",
    standard: "L.7.4",
    skill: "Context clues",
    prompt: "What does impasse most likely mean?",
    passage: "The negotiations reached an impasse; neither side would give up anything, and after six hours, both teams left the room without an agreement.",
    choices: ["a point with no progress", "a quick victory", "a friendly lunch", "a new rule"],
    answer: 0,
    explanation: "Neither side gave anything and they left without agreement, so an impasse is a deadlock.",
  },
];

export default questions;
