import type { Question } from "../../types";

// Grade 9 ELA — NC Standard Course of Study for ELA (2017). English I (9-10 band): RL.9-10.1, RL.9-10.2, RL.9-10.3, RL.9-10.4, RL.9-10.5, RL.9-10.6, RI.9-10.2, RI.9-10.6, RI.9-10.8, RI.9-10.9, W.9-10.1, L.9-10.1, L.9-10.2, L.9-10.3, L.9-10.4, L.9-10.5
const questions: Question[] = [
  {
    id: "ela-g9-01",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal to the speaker's credibility is...",
    choices: ["ethos", "pathos", "logos", "kairos"],
    answer: 0,
    explanation: "Ethos builds trust in the speaker's character or expertise.",
    quick: true,
  },
  {
    id: "ela-g9-02",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal to the audience's emotions is...",
    choices: ["pathos", "ethos", "logos", "syntax"],
    answer: 0,
    explanation: "Pathos moves the audience through feelings like pity, fear, or hope.",
    quick: true,
  },
  {
    id: "ela-g9-03",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "Attacking the person instead of the argument is...",
    choices: ["ad hominem", "straw man", "bandwagon", "red herring"],
    answer: 0,
    explanation: "Ad hominem (Latin for 'to the person') targets the speaker, not the reasoning.",
    quick: true,
  },
  {
    id: "ela-g9-04",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'Everyone is buying it, so you should too' is...",
    choices: ["bandwagon", "ad hominem", "straw man", "false cause"],
    answer: 0,
    explanation: "The bandwagon fallacy claims something is right because it is popular.",
    quick: true,
  },
  {
    id: "ela-g9-05",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Figures of speech",
    prompt: "Which phrase is an oxymoron?",
    choices: ["jumbo shrimp", "bright sun", "cold ice", "big house"],
    answer: 0,
    explanation: "An oxymoron pairs contradictory words: jumbo (huge) and shrimp (tiny).",
    quick: true,
  },
  {
    id: "ela-g9-06",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Figures of speech",
    prompt: "Saying 'passed away' instead of 'died' is a...",
    choices: ["euphemism", "hyperbole", "paradox", "cliché"],
    answer: 0,
    explanation: "A euphemism is a gentler word used in place of a harsh or unpleasant one.",
    quick: true,
  },
  {
    id: "ela-g9-07",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Greek and Latin roots",
    prompt: "The root mal (as in malfunction) means...",
    choices: ["bad", "many", "small", "sea"],
    answer: 0,
    explanation: "Mal means bad or badly, as in malfunction and malnourished.",
    quick: true,
  },
  {
    id: "ela-g9-08",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.2",
    skill: "Semicolons",
    prompt: "A semicolon can join two closely related...",
    choices: ["main clauses", "adjectives", "prepositions", "articles"],
    answer: 0,
    explanation: "A semicolon links two independent (main) clauses without a conjunction.",
    quick: true,
  },
  {
    id: "ela-g9-09",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.3",
    skill: "Character",
    prompt: "A character who contrasts with the main character is a...",
    choices: ["foil", "protagonist", "narrator", "mentor"],
    answer: 0,
    explanation: "A foil highlights the protagonist's traits through contrast.",
    quick: true,
  },
  {
    id: "ela-g9-10",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.5",
    skill: "Narrative structure",
    prompt: "A story that opens in the middle of the action begins...",
    choices: ["in medias res", "in exposition", "at resolution", "at denouement"],
    answer: 0,
    explanation: "In medias res is Latin for 'in the middle of things.'",
    quick: true,
  },
  {
    id: "ela-g9-11",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Tone",
    prompt: "A writer's attitude toward the subject is the...",
    choices: ["tone", "mood", "theme", "plot"],
    answer: 0,
    explanation: "Tone is the writer's attitude; mood is the feeling the reader gets.",
    quick: true,
  },
  {
    id: "ela-g9-12",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Parallel structure",
    prompt: "I like hiking, swimming, and ___. Which keeps it parallel?",
    choices: ["biking", "to bike", "I bike", "go biking"],
    answer: 0,
    explanation: "Parallel structure keeps items in the same form: hiking, swimming, biking.",
    quick: true,
  },
  {
    id: "ela-g9-13",
    subject: "ela",
    grade: "9",
    standard: "W.9-10.1",
    skill: "Argument writing",
    prompt: "The part of an argument that answers the other side is the...",
    choices: ["rebuttal", "thesis", "hook", "anecdote"],
    answer: 0,
    explanation: "A rebuttal responds to a counterclaim and explains why it falls short.",
    quick: true,
  },
  {
    id: "ela-g9-14",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Parallel structure",
    prompt: "Which sentence uses parallel structure correctly?",
    choices: ["She wanted to travel, to learn, and to grow.", "She wanted to travel, learning, and to grow.", "She wanted travel, to learn, and growing.", "She wanted to travel, learn, and growing."],
    answer: 0,
    explanation: "All three items use the same infinitive form: to travel, to learn, to grow.",
  },
  {
    id: "ela-g9-15",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Tone and diction",
    prompt: "Which word best describes the tone?",
    passage: "The committee's report, all forty glossy pages of it, concluded, after much deliberation and an expensive catered lunch, that the broken stoplight on Main Street was, in fact, broken.",
    choices: ["sarcastic", "admiring", "fearful", "nostalgic"],
    answer: 0,
    explanation: "Stating that a broken light was 'in fact, broken' after a costly report mocks the committee.",
  },
  {
    id: "ela-g9-16",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical devices",
    prompt: "Which device appears in 'We have walked... We have watched...'?",
    passage: "Fellow students, we have walked past that empty lot for years. We have watched weeds grow where a garden could bloom. We can wait for someone else to act, or we can pick up the shovels ourselves.",
    choices: ["anaphora", "understatement", "oxymoron", "allusion"],
    answer: 0,
    explanation: "Anaphora repeats the same words at the start of clauses to build rhythm and emphasis.",
  },
  {
    id: "ela-g9-17",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "Nora spent the summer tracking the migration of monarchs, measuring every wing. By August she had filled three notebooks with data but had never once simply watched a butterfly land. On the last day, she set her pencil down, and one settled on her open palm.",
    choices: ["We must sometimes stop measuring life to live it.", "Science is a waste of time.", "Butterflies are fragile.", "Summer is too short for goals."],
    answer: 0,
    explanation: "Nora finally experiences the butterfly only when she sets down her pencil.",
  },
  {
    id: "ela-g9-18",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does laconic most likely mean?",
    passage: "The senator's speech was so laconic, just three sentences, that reporters wondered whether she had anything more to say.",
    choices: ["using very few words", "angry", "extremely long", "humorous"],
    answer: 0,
    explanation: "A speech of just three sentences is a clue that laconic means brief or using few words.",
  },
  {
    id: "ela-g9-19",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Latin roots",
    prompt: "The Latin root ambul (as in ambulance) means...",
    choices: ["walk", "sick", "carry", "fast"],
    answer: 0,
    explanation: "Ambul means walk or move, as in ambulatory.",
    quick: true,
  },
  {
    id: "ela-g9-20",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Greek roots",
    prompt: "The Greek root anthrop (as in anthropology) means...",
    choices: ["human", "animal", "ancient", "earth"],
    answer: 0,
    explanation: "Anthrop means human. Anthropology is the study of humans.",
    quick: true,
  },
  {
    id: "ela-g9-21",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Latin prefixes",
    prompt: "The prefix contra- (as in contradict) means...",
    choices: ["against", "with", "together", "after"],
    answer: 0,
    explanation: "Contra- means against. To contradict is to speak against.",
    quick: true,
  },
  {
    id: "ela-g9-22",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Word forms",
    prompt: "Which word is the adverb form of deceive?",
    choices: ["deceptively", "deception", "deceptive", "deceit"],
    answer: 0,
    explanation: "The -ly ending makes deceptively an adverb. Deception and deceit are nouns.",
    quick: true,
  },
  {
    id: "ela-g9-23",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Latin roots",
    prompt: "The Latin root ver (as in verify) means...",
    choices: ["truth", "green", "turn", "speak"],
    answer: 0,
    explanation: "Ver means truth. To verify is to confirm something is true.",
    quick: true,
  },
  {
    id: "ela-g9-24",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Nuance",
    prompt: "Which word suggests the most extreme fear?",
    choices: ["terror", "unease", "worry", "concern"],
    answer: 0,
    explanation: "Terror is intense, overwhelming fear. The others are milder.",
    quick: true,
  },
  {
    id: "ela-g9-25",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Metonymy",
    prompt: "'The pen is mightier than the sword' uses pen and sword as...",
    choices: ["metonymy", "simile", "hyperbole", "oxymoron"],
    answer: 0,
    explanation: "Pen stands for writing and sword for force, which is metonymy.",
    quick: true,
  },
  {
    id: "ela-g9-26",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Extended metaphor",
    prompt: "A comparison of unlike things developed over many lines is an extended...",
    choices: ["metaphor", "simile", "allusion", "irony"],
    answer: 0,
    explanation: "An extended metaphor carries one comparison through a passage or poem.",
    quick: true,
  },
  {
    id: "ela-g9-27",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Clauses",
    prompt: "In 'Because it rained, we stayed in,' what kind of clause is 'Because it rained'?",
    choices: ["adverb", "noun", "adjective", "independent"],
    answer: 0,
    explanation: "It tells why we stayed in, so it is a dependent adverb clause.",
    quick: true,
  },
  {
    id: "ela-g9-28",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Appositives",
    prompt: "In 'My aunt, a pilot, flies daily,' 'a pilot' is a(n)...",
    choices: ["appositive", "gerund", "infinitive", "participle"],
    answer: 0,
    explanation: "An appositive renames the noun next to it: my aunt = a pilot.",
    quick: true,
  },
  {
    id: "ela-g9-29",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.2",
    skill: "Semicolons",
    prompt: "'I studied ___ however, I failed.' Which mark fits?",
    choices: ["semicolon", "comma", "colon", "dash"],
    answer: 0,
    explanation: "Use a semicolon before a conjunctive adverb like however that joins two clauses.",
    quick: true,
  },
  {
    id: "ela-g9-30",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.2",
    skill: "Spelling",
    prompt: "Which word is spelled correctly?",
    choices: ["accommodate", "acommodate", "accomodate", "acomodate"],
    answer: 0,
    explanation: "Accommodate has two c's and two m's.",
    quick: true,
  },
  {
    id: "ela-g9-31",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.3",
    skill: "Style manuals",
    prompt: "MLA style is mainly used for writing in...",
    choices: ["humanities", "psychology", "chemistry", "engineering"],
    answer: 0,
    explanation: "MLA is used in English and the humanities. Psychology usually uses APA.",
    quick: true,
  },
  {
    id: "ela-g9-32",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.3",
    skill: "Character types",
    prompt: "A character who changes significantly over a story is...",
    choices: ["dynamic", "static", "flat", "stock"],
    answer: 0,
    explanation: "A dynamic character grows or changes. A static character stays the same.",
    quick: true,
  },
  {
    id: "ela-g9-33",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.5",
    skill: "Structure",
    prompt: "Events told out of time order use a ___ structure.",
    choices: ["nonlinear", "linear", "chronological", "sequential"],
    answer: 0,
    explanation: "A nonlinear structure jumps around in time, often to build tension.",
    quick: true,
  },
  {
    id: "ela-g9-34",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Connotation",
    prompt: "The feelings and ideas a word suggests beyond its definition are its...",
    choices: ["connotations", "denotations", "etymologies", "syntax"],
    answer: 0,
    explanation: "Connotations are a word's associations. Denotation is the dictionary meaning.",
    quick: true,
  },
  {
    id: "ela-g9-35",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.6",
    skill: "Point of view",
    prompt: "A narrator who addresses the reader as 'you' is using...",
    choices: ["second person", "first person", "third limited", "omniscient"],
    answer: 0,
    explanation: "Second-person narration speaks directly to 'you.'",
    quick: true,
  },
  {
    id: "ela-g9-36",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Faulty appeals",
    prompt: "Citing a dentist about video game quality is a faulty appeal to...",
    choices: ["authority", "emotion", "statistics", "analogy"],
    answer: 0,
    explanation: "A dentist is not an expert on video games, so this is a false appeal to authority.",
    quick: true,
  },
  {
    id: "ela-g9-37",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "False cause",
    prompt: "'I wore my lucky socks and we won, so the socks caused it' is...",
    choices: ["false cause", "bandwagon", "straw man", "ad hominem"],
    answer: 0,
    explanation: "False cause assumes that because one thing came first, it caused the second.",
    quick: true,
  },
  {
    id: "ela-g9-38",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.9",
    skill: "Seminal documents",
    prompt: "The Declaration of Independence was mainly written by...",
    choices: ["Jefferson", "Washington", "Lincoln", "Franklin"],
    answer: 0,
    explanation: "Thomas Jefferson drafted the Declaration in 1776. Franklin and others helped edit it.",
    quick: true,
  },
  {
    id: "ela-g9-39",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.1",
    skill: "Inference",
    prompt: "What does Rafael's behavior suggest?",
    passage: "The invitation sat on Rafael's desk for a week, unopened. Each morning he moved it a little farther from his laptop, until finally it slid behind the radiator.",
    choices: ["He is avoiding the event.", "He lost the invitation by accident.", "He is excited to go.", "He doesn't own a laptop."],
    answer: 0,
    explanation: "Leaving it unopened and pushing it farther away each day shows avoidance.",
  },
  {
    id: "ela-g9-40",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.3",
    skill: "Character motivation",
    prompt: "What motivates Nia's constant volunteering?",
    passage: "Nia volunteered for every committee, organized every fundraiser, and never said no. Only her journal knew her fear: that if she stopped, no one would notice her at all.",
    choices: ["fear of being overlooked", "a love of fundraising", "pressure from her parents", "a desire for money"],
    answer: 0,
    explanation: "Her journal reveals her fear that no one would notice her if she stopped.",
  },
  {
    id: "ela-g9-41",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.5",
    skill: "Foreshadowing",
    prompt: "What role does the crack most likely play in the story?",
    passage: "On the morning of the voyage, Elias noticed a hairline crack in the ship's hull. The captain waved it off. 'She's survived worse,' he said, and the crew went on loading the cargo.",
    choices: ["It foreshadows trouble at sea.", "It resolves the conflict.", "It flashes back to the past.", "It ends the story."],
    answer: 0,
    explanation: "A dismissed warning sign early on hints that something will go wrong later.",
  },
  {
    id: "ela-g9-42",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Tone",
    prompt: "What is the narrator's attitude toward the diner?",
    passage: "The diner is gone now, but I can still hear the bell over the door and smell coffee and pancakes on the Saturday mornings when Dad let me spin on the red stools.",
    choices: ["nostalgic", "bitter", "mocking", "indifferent"],
    answer: 0,
    explanation: "The narrator fondly remembers the bell, the smells, and Saturdays with Dad.",
  },
  {
    id: "ela-g9-43",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.2",
    skill: "Theme",
    prompt: "Which theme does the passage suggest?",
    passage: "For thirty years, the lighthouse keeper logged every passing ship. When automation made his job unnecessary, he kept logging them anyway, from his kitchen window in town.",
    choices: ["Purpose and identity can outlast a job.", "Technology is always good.", "Ships are dangerous.", "Retirement is restful."],
    answer: 0,
    explanation: "He keeps logging ships after the job ends because it is part of who he is.",
  },
  {
    id: "ela-g9-44",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.2",
    skill: "Central idea",
    prompt: "What is the central idea?",
    passage: "The printing press did more than make books cheaper. By spreading identical texts across Europe, it helped standardize spelling, sped the exchange of scientific ideas, and fueled religious and political debate.",
    choices: ["The printing press had effects far beyond cheaper books.", "Books became more expensive.", "Printers invented spelling.", "Europe had no debates before printing."],
    answer: 0,
    explanation: "The passage lists wide effects: standard spelling, faster science, and public debate.",
  },
  {
    id: "ela-g9-45",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical technique",
    prompt: "What technique does the author mainly use?",
    passage: "Ask yourself: would you drink from a cup that a thousand strangers had used? Then why do we accept unwashed, shared gym equipment?",
    choices: ["an analogy posed as a question", "a statistic", "an expert quotation", "a personal story"],
    answer: 0,
    explanation: "The author compares shared gym equipment to a shared cup and asks the reader a question.",
  },
  {
    id: "ela-g9-46",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Hasty generalization",
    prompt: "Which fallacy does this reasoning contain?",
    passage: "I met two rude tourists from Ohio, so people from Ohio must be rude.",
    choices: ["hasty generalization", "appeal to tradition", "red herring", "circular reasoning"],
    answer: 0,
    explanation: "Judging a whole state from two people is a conclusion drawn from too little evidence.",
  },
  {
    id: "ela-g9-47",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does grandiloquent mean?",
    passage: "The senator's speech was full of grandiloquent phrases, such as 'a glorious tapestry of national destiny,' but it contained few concrete proposals.",
    choices: ["pompous and overblown", "short and plain", "angry", "humble"],
    answer: 0,
    explanation: "The fancy phrase and lack of concrete ideas show grandiloquent means showy and overblown.",
  },
  {
    id: "ela-g9-48",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.2",
    skill: "Semicolons",
    prompt: "Which sentence uses a semicolon correctly?",
    choices: ["The game was over; the fans went home.", "The game was over; and the fans went home.", "The game; was over, the fans went home.", "Because the game was over; the fans went home."],
    answer: 0,
    explanation: "A semicolon joins two independent clauses without a conjunction.",
  },
];

export default questions;
