import type { Question } from "../../types";

// Grade 9 ELA — NC Standard Course of Study for ELA (2017). English I (9-10 band): RL.9-10.2, RL.9-10.3, RL.9-10.4, RL.9-10.5, RI.9-10.6, RI.9-10.8, L.9-10.1, L.9-10.2, L.9-10.4, L.9-10.5, W.9-10.1
const questions: Question[] = [
  {
    id: "ela-g9-01",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal to the speaker's credibility is...",
    choices: ["ethos", "pathos", "logos", "kairos"],
    answer: 0,
    explanation: "Ethos builds trust in the speaker's character or expertise.",
    quick: true,
  },
  {
    id: "ela-g9-02",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal to the audience's emotions is...",
    choices: ["pathos", "ethos", "logos", "syntax"],
    answer: 0,
    explanation: "Pathos moves the audience through feelings like pity, fear, or hope.",
    quick: true,
  },
  {
    id: "ela-g9-03",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "Attacking the person instead of the argument is...",
    choices: ["ad hominem", "straw man", "bandwagon", "red herring"],
    answer: 0,
    explanation: "Ad hominem (Latin for 'to the person') targets the speaker, not the reasoning.",
    quick: true,
  },
  {
    id: "ela-g9-04",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'Everyone is buying it, so you should too' is...",
    choices: ["bandwagon", "ad hominem", "straw man", "false cause"],
    answer: 0,
    explanation: "The bandwagon fallacy claims something is right because it is popular.",
    quick: true,
  },
  {
    id: "ela-g9-05",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Figures of speech",
    prompt: "Which phrase is an oxymoron?",
    choices: ["jumbo shrimp", "bright sun", "cold ice", "big house"],
    answer: 0,
    explanation: "An oxymoron pairs contradictory words: jumbo (huge) and shrimp (tiny).",
    quick: true,
  },
  {
    id: "ela-g9-06",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.5",
    skill: "Figures of speech",
    prompt: "Saying 'passed away' instead of 'died' is a...",
    choices: ["euphemism", "hyperbole", "paradox", "cliché"],
    answer: 0,
    explanation: "A euphemism is a gentler word used in place of a harsh or unpleasant one.",
    quick: true,
  },
  {
    id: "ela-g9-07",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Greek and Latin roots",
    prompt: "The root mal (as in malfunction) means...",
    choices: ["bad", "many", "small", "sea"],
    answer: 0,
    explanation: "Mal means bad or badly, as in malfunction and malnourished.",
    quick: true,
  },
  {
    id: "ela-g9-08",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.2",
    skill: "Semicolons",
    prompt: "A semicolon can join two closely related...",
    choices: ["main clauses", "adjectives", "prepositions", "articles"],
    answer: 0,
    explanation: "A semicolon links two independent (main) clauses without a conjunction.",
    quick: true,
  },
  {
    id: "ela-g9-09",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.3",
    skill: "Character",
    prompt: "A character who contrasts with the main character is a...",
    choices: ["foil", "protagonist", "narrator", "mentor"],
    answer: 0,
    explanation: "A foil highlights the protagonist's traits through contrast.",
    quick: true,
  },
  {
    id: "ela-g9-10",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.5",
    skill: "Narrative structure",
    prompt: "A story that opens in the middle of the action begins...",
    choices: ["in medias res", "in exposition", "at resolution", "at denouement"],
    answer: 0,
    explanation: "In medias res is Latin for 'in the middle of things.'",
    quick: true,
  },
  {
    id: "ela-g9-11",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Tone",
    prompt: "A writer's attitude toward the subject is the...",
    choices: ["tone", "mood", "theme", "plot"],
    answer: 0,
    explanation: "Tone is the writer's attitude; mood is the feeling the reader gets.",
    quick: true,
  },
  {
    id: "ela-g9-12",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Parallel structure",
    prompt: "I like hiking, swimming, and ___. Which keeps it parallel?",
    choices: ["biking", "to bike", "I bike", "go biking"],
    answer: 0,
    explanation: "Parallel structure keeps items in the same form: hiking, swimming, biking.",
    quick: true,
  },
  {
    id: "ela-g9-13",
    subject: "ela",
    grade: "9",
    standard: "W.9-10.1",
    skill: "Argument writing",
    prompt: "The part of an argument that answers the other side is the...",
    choices: ["rebuttal", "thesis", "hook", "anecdote"],
    answer: 0,
    explanation: "A rebuttal responds to a counterclaim and explains why it falls short.",
    quick: true,
  },
  {
    id: "ela-g9-14",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.1",
    skill: "Parallel structure",
    prompt: "Which sentence uses parallel structure correctly?",
    choices: ["She wanted to travel, to learn, and to grow.", "She wanted to travel, learning, and to grow.", "She wanted travel, to learn, and growing.", "She wanted to travel, learn, and growing."],
    answer: 0,
    explanation: "All three items use the same infinitive form: to travel, to learn, to grow.",
  },
  {
    id: "ela-g9-15",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.4",
    skill: "Tone and diction",
    prompt: "Which word best describes the tone?",
    passage: "The committee's report, all forty glossy pages of it, concluded, after much deliberation and an expensive catered lunch, that the broken stoplight on Main Street was, in fact, broken.",
    choices: ["sarcastic", "admiring", "fearful", "nostalgic"],
    answer: 0,
    explanation: "Stating that a broken light was 'in fact, broken' after a costly report mocks the committee.",
  },
  {
    id: "ela-g9-16",
    subject: "ela",
    grade: "9",
    standard: "RI.9-10.6",
    skill: "Rhetorical devices",
    prompt: "Which device appears in 'We have walked... We have watched...'?",
    passage: "Fellow students, we have walked past that empty lot for years. We have watched weeds grow where a garden could bloom. We can wait for someone else to act, or we can pick up the shovels ourselves.",
    choices: ["anaphora", "understatement", "oxymoron", "allusion"],
    answer: 0,
    explanation: "Anaphora repeats the same words at the start of clauses to build rhythm and emphasis.",
  },
  {
    id: "ela-g9-17",
    subject: "ela",
    grade: "9",
    standard: "RL.9-10.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "Nora spent the summer tracking the migration of monarchs, measuring every wing. By August she had filled three notebooks with data but had never once simply watched a butterfly land. On the last day, she set her pencil down, and one settled on her open palm.",
    choices: ["We must sometimes stop measuring life to live it.", "Science is a waste of time.", "Butterflies are fragile.", "Summer is too short for goals."],
    answer: 0,
    explanation: "Nora finally experiences the butterfly only when she sets down her pencil.",
  },
  {
    id: "ela-g9-18",
    subject: "ela",
    grade: "9",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does laconic most likely mean?",
    passage: "The senator's speech was so laconic, just three sentences, that reporters wondered whether she had anything more to say.",
    choices: ["using very few words", "angry", "extremely long", "humorous"],
    answer: 0,
    explanation: "A speech of just three sentences is a clue that laconic means brief or using few words.",
  },
];

export default questions;
