/*
 * Science sequences, K-12 (NC Standard Course of Study for Science, 2023).
 * K-2 stacks have 3 slabs, 3-5 have 4, 6-12 have 4 or 5. Each has exactly one correct order.
 * Cycles (seasons, water, moon) say where to start, so only one order fits.
 */
import type { Grade } from "../kit/types";
import type { Sequence } from "./types";

type Extra = Partial<Pick<Sequence, "passage" | "notes" | "say">>;

function S(id: string, grades: Grade[], standard: string, skill: string, title: string, ends: [string, string], steps: string[], explain: string, extra: Extra = {}): Sequence {
  return { id, subject: "science", grades, standard, skill, title, ends, steps, explain, ...extra };
}
const FL: [string, string] = ["FIRST", "LAST"];

export const SCIENCE: Sequence[] = [
  /* ---------------- K-2 (3 slabs, big labels) ---------------- */
  S("sci-k-01", ["K", "1"], "ESS.K.1.2", "Seasons", "THE SEASONS", FL, ["WINTER", "SPRING", "SUMMER"],
    "After cold winter comes spring, when plants start to grow. Then comes hot summer.", { passage: "Start in WINTER. Which season comes next, and next?" }),
  S("sci-k-02", ["K", "1"], "ESS.K.1.2", "Seasons", "THE SEASONS", FL, ["SUMMER", "FALL", "WINTER"],
    "Hot summer turns into fall, when leaves change color and drop. Then comes cold winter.", { passage: "Start in SUMMER. Which season comes next, and next?" }),
  S("sci-k-03", ["K"], "ESS.K.1.1", "Weather", "A RAINY DAY", FL, ["CLOUDS", "RAIN", "PUDDLES"],
    "Gray clouds roll in first. Rain falls from the clouds, and then puddles form on the ground.", { passage: "What happens first on a rainy day?" }),
  S("sci-k-04", ["K"], "LS.K.1.1", "Living things grow", "A PLANT GROWS", FL, ["SEED", "SPROUT", "FLOWER"],
    "A plant starts as a seed. It sprouts, grows bigger, and then it can bloom into a flower."),
  S("sci-k-05", ["K"], "LS.K.1.1", "Living things grow", "PEOPLE GROW UP", FL, ["BABY", "CHILD", "ADULT"],
    "People are living things, and living things grow. A baby grows into a child, and a child grows into an adult."),
  S("sci-k-06", ["K"], "PS.K.2.2", "Pushes and pulls", "KICK A BALL", FL, ["KICK", "ROLLS", "STOPS"],
    "A kick is a push that starts the ball moving. It rolls across the grass until rubbing on the ground slows it and it stops."),
  S("sci-1-01", ["1", "2"], "ESS.1.1", "The sun in the sky", "THE SUN IN ONE DAY", FL, ["SUNRISE", "NOON", "SUNSET"],
    "The sun rises in the morning, is high in the sky at noon, and sets in the evening.", { passage: "Follow the sun from morning to evening." }),
  S("sci-1-02", ["1"], "LS.1.1", "Plants grow", "A BEAN SPROUTS", FL, ["SEED", "ROOT", "LEAVES"],
    "A bean seed sends a root down into the soil first. Then a shoot grows up and opens its leaves to the sun."),
  S("sci-1-03", ["1"], "LS.1.2", "Animal homes and young", "A BIRD FAMILY", FL, ["NEST", "EGGS", "CHICKS"],
    "The parent birds build a nest first. Then eggs are laid in it, and later the chicks hatch."),
  S("sci-1-04", ["1"], "ESS.1.1", "Day and night sky", "DAY TO NIGHT", FL, ["MORNING", "EVENING", "NIGHT"],
    "Morning comes first, when the sun comes up. Evening comes as the sun goes down, and then it is dark night.", { passage: "Start in the MORNING." }),
  S("sci-2-01", ["2"], "LS.2.1", "Animal life cycles", "FROG LIFE CYCLE", FL, ["EGG", "TADPOLE", "FROG"],
    "A frog starts as an egg in the water. A tadpole hatches, grows legs, loses its tail and becomes a frog."),
  S("sci-2-02", ["2"], "LS.2.1", "Animal life cycles", "BUTTERFLY LIFE CYCLE", FL, ["LARVA", "CHRYSALIS", "BUTTERFLY"],
    "The larva (the caterpillar) eats and grows, then makes a chrysalis. Inside, it changes into a butterfly.",
    { passage: "A caterpillar is called a LARVA. Start with the larva." }),
  S("sci-2-03", ["2"], "LS.2.1", "Animal life cycles", "CHICKEN LIFE CYCLE", FL, ["EGG", "CHICK", "HEN"],
    "A hen lays an egg. A fluffy chick hatches from it and grows up into a hen."),
  S("sci-2-04", ["2"], "PS.2.1.1", "Heating and cooling", "HEATING WATER", FL, ["ICE", "WATER", "STEAM"],
    "Heat melts solid ice into liquid water. More heat makes the water boil into steam.", { passage: "Start with ice and keep heating it." }),
  S("sci-2-05", ["2"], "PS.2.1.2", "Heating and cooling", "MAKING AN ICE POP", FL, ["JUICE", "SLUSH", "ICE POP"],
    "Liquid juice goes in the freezer. As it cools it turns slushy, and then it freezes solid into an ice pop."),
  S("sci-2-06", ["2"], "ESS.2.1", "Weather", "A THUNDERSTORM", FL, ["CLOUDS", "FLASH", "THUNDER"],
    "Storm clouds build up first. You see the lightning flash, then you hear the thunder, because light travels faster than sound."),

  /* ---------------- 3-5 (4 slabs) ---------------- */
  S("sci-3-01", ["3"], "LS.3.2.2", "Seed-plant life cycle", "SEED PLANT LIFE CYCLE", FL, ["SEED", "SEEDLING", "FLOWER", "FRUIT"],
    "A seed sprouts into a seedling, grows into a plant that flowers, and the flower becomes a fruit holding new seeds."),
  S("sci-3-02", ["3"], "LS.3.2.2", "Seed-plant life cycle", "FROM FLOWER TO SEEDS", FL, ["FLOWER OPENS", "POLLINATED", "FRUIT GROWS", "SEEDS SPREAD"],
    "A flower opens and is pollinated, often by insects. The fertilized flower grows into a fruit, and its seeds are spread to grow new plants."),
  S("sci-3-03", ["3"], "PS.3.1.3", "Heating changes matter", "HEATING ICE", FL, ["SOLID ICE", "LIQUID WATER", "BOILING", "WATER VAPOR"],
    "Heating melts solid ice into liquid water. More heat makes the water boil, and it becomes a gas: water vapor."),
  S("sci-3-04", ["3"], "ESS.3.1.1", "The solar system", "INNER PLANETS", ["NEAREST SUN", "FARTHEST"], ["MERCURY", "VENUS", "EARTH", "MARS"],
    "The four rocky inner planets, from the sun outward, are Mercury, Venus, Earth and Mars."),
  S("sci-3-05", ["3"], "ESS.3.1.1", "The solar system", "OUTER PLANETS", ["NEAREST SUN", "FARTHEST"], ["JUPITER", "SATURN", "URANUS", "NEPTUNE"],
    "The four giant outer planets, from the sun outward, are Jupiter, Saturn, Uranus and Neptune."),
  S("sci-3-06", ["3"], "LS.3.1.1", "Bones and muscles", "HOW YOUR ARM BENDS", FL, ["BRAIN SIGNAL", "MUSCLE PULLS", "BONE MOVES", "ARM BENDS"],
    "Your brain sends a signal along nerves. The muscle contracts and pulls on the bone, which moves at the elbow joint, so your arm bends."),
  S("sci-4-01", ["4"], "ESS.4.1", "Moon phases", "MOON PHASES", FL, ["NEW MOON", "1ST QUARTER", "FULL MOON", "3RD QUARTER"],
    "Over about a month the moon goes from new moon to first quarter to full moon to third quarter, then back to new.",
    { passage: "Start at the NEW MOON and follow one month." }),
  S("sci-4-02", ["4"], "ESS.4.1", "Earth's rotation", "ONE TURN OF EARTH", FL, ["SUNRISE", "NOON", "SUNSET", "MIDNIGHT"],
    "As Earth spins once in 24 hours, your side turns toward the sun (sunrise), faces it most directly (noon), turns away (sunset) and is farthest from facing it (midnight).",
    { passage: "Start at sunrise and follow one full spin of Earth." }),
  S("sci-4-03", ["4"], "ESS.4.2.3", "Weathering", "WEATHERING A ROCK", ["BIGGEST", "SMALLEST"], ["BOULDER", "ROCKS", "PEBBLES", "SAND"],
    "Weathering breaks a boulder into rocks, rocks into pebbles, and pebbles into tiny grains of sand."),
  S("sci-4-04", ["4"], "LS.4.2.2", "Fossils", "HOW A FOSSIL FORMS", FL, ["ANIMAL DIES", "BURIED", "ROCK FORMS", "FOSSIL FOUND"],
    "An animal dies and is quickly buried by mud or sand. Over time the layers harden into rock around it, and much later the fossil is uncovered and found."),
  S("sci-4-05", ["4"], "PS.4.2", "Energy transfer", "ENERGY IN A FLASHLIGHT", FL, ["BATTERY", "WIRE", "BULB", "LIGHT"],
    "Stored energy in the battery moves through the wire as electricity to the bulb, which changes it into light."),
  S("sci-5-01", ["5"], "ESS.5.1.4", "The water cycle", "A WATER DROP'S TRIP", FL, ["EVAPORATES", "CONDENSES", "RAINS DOWN", "COLLECTS"],
    "The sun heats water so it evaporates. The vapor cools and condenses into clouds, falls as precipitation, and collects in oceans, lakes and ground water.",
    { passage: "Start when the sun warms the ocean." }),
  S("sci-5-02", ["5"], "LS.5.2", "Food chains", "A FOOD CHAIN", ["ENERGY STARTS", "TOP"], ["SUN", "GRASS", "RABBIT", "FOX"],
    "Energy flows from the sun to grass (a producer), to the rabbit that eats the grass, to the fox that eats the rabbit."),
  S("sci-5-03", ["5"], "LS.5.2.1", "Food chains", "A FOREST FOOD CHAIN", ["PRODUCER", "TOP"], ["LEAVES", "CATERPILLAR", "SONGBIRD", "HAWK"],
    "Leaves are the producer. A caterpillar eats the leaves, a songbird eats the caterpillar, and a hawk eats the songbird."),
  S("sci-5-04", ["5"], "LS.5.1.1", "Body organization", "BODY ORGANIZATION", ["SMALLEST", "LARGEST"], ["CELL", "TISSUE", "ORGAN", "ORGAN SYSTEM"],
    "Cells group into tissues, tissues form organs, and organs work together as organ systems."),
  S("sci-5-05", ["5"], "LS.5.1", "Digestive system", "PATH OF FOOD", FL, ["MOUTH", "ESOPHAGUS", "STOMACH", "INTESTINES"],
    "Food is chewed in the mouth, pushed down the esophagus, mashed in the stomach, and absorbed in the intestines."),
  S("sci-5-06", ["5"], "ESS.5.1", "Clouds and weather", "HOW A CLOUD FORMS", FL, ["AIR RISES", "AIR COOLS", "DROPS FORM", "CLOUD GROWS"],
    "Warm, moist air rises and cools. The water vapor condenses into tiny droplets, and billions of droplets make a growing cloud."),

  /* ---------------- 6-8 (4-5 slabs) ---------------- */
  S("sci-6-01", ["6"], "PS.6.1.2", "Phase changes", "ADDING HEAT TO ICE", FL, ["SOLID", "MELTING", "LIQUID", "BOILING", "GAS"],
    "Adding thermal energy speeds up the particles: the solid melts into a liquid, and the liquid boils into a gas."),
  S("sci-6-02", ["6"], "ESS.6.1", "Seasons", "A YEAR OF SEASONS (NORTH)", FL, ["MAR EQUINOX", "LONGEST DAY", "SEP EQUINOX", "SHORTEST DAY"],
    "In the Northern Hemisphere the March equinox starts spring, the June solstice is the longest day, the September equinox starts fall, and the December solstice is the shortest day.",
    { passage: "Start at the March equinox in the Northern Hemisphere." }),
  S("sci-6-03", ["6"], "PS.6.3", "Electromagnetic waves", "EM WAVES BY WAVELENGTH", ["LONGEST", "SHORTEST"], ["RADIO", "MICROWAVE", "INFRARED", "VISIBLE", "ULTRAVIOLET"],
    "Radio waves are the longest, then microwaves, infrared, visible light and ultraviolet. Shorter waves carry more energy."),
  S("sci-6-04", ["6"], "ESS.6.2", "Weathering, erosion and deposition", "FROM MOUNTAIN TO NEW ROCK", FL, ["WEATHERING", "EROSION", "DEPOSITION", "COMPACTION"],
    "Weathering breaks rock apart, erosion carries the pieces away, deposition drops them in layers, and compaction presses the layers into new rock."),
  S("sci-6-05", ["6"], "LS.6.2", "Ecosystem change", "AFTER A FOREST FIRE", FL, ["BURNED LAND", "GRASSES", "SHRUBS", "YOUNG TREES", "FOREST"],
    "In succession after a fire, grasses grow first, then shrubs, then young trees, until a forest returns."),
  S("sci-6-06", ["6", "7", "8"], "SEP.3", "Investigations", "SCIENTIFIC INVESTIGATION", FL, ["QUESTION", "HYPOTHESIS", "EXPERIMENT", "ANALYZE DATA", "CONCLUSION"],
    "Ask a question, make a testable hypothesis, run an experiment, analyze the data, and draw a conclusion."),
  S("sci-7-01", ["7"], "ESS.7.1", "Layers of the atmosphere", "LAYERS OF THE ATMOSPHERE", ["GROUND", "SPACE"], ["TROPOSPHERE", "STRATOSPHERE", "MESOSPHERE", "THERMOSPHERE", "EXOSPHERE"],
    "From the ground up: troposphere (weather), stratosphere (ozone layer), mesosphere, thermosphere, and the exosphere at the edge of space."),
  S("sci-7-02", ["7"], "LS.7.1", "Levels of organization", "LEVELS OF ORGANIZATION", ["SIMPLEST", "MOST COMPLEX"], ["CELL", "TISSUE", "ORGAN", "ORGAN SYSTEM", "ORGANISM"],
    "Cells form tissues, tissues form organs, organs form organ systems, and organ systems make up the whole organism."),
  S("sci-7-03", ["7"], "LS.7.1", "Circulatory system", "PATH OF BLOOD", FL, ["RIGHT HEART", "LUNGS", "LEFT HEART", "BODY"],
    "Blood low in oxygen enters the right side of the heart, is pumped to the lungs to pick up oxygen, returns to the left side, and is pumped out to the body.",
    { passage: "Blood low in oxygen has just come back from the body. Where does it go next?" }),
  S("sci-7-04", ["7"], "ESS.7.1", "Weather", "A THUNDERSTORM FORMS", FL, ["AIR RISES", "AIR COOLS", "DROPS FORM", "CLOUD GROWS", "RAIN FALLS"],
    "Warm, moist air rises and cools; water vapor condenses into droplets; the cloud grows tall; and when the drops get heavy enough, rain falls."),
  S("sci-8-01", ["8"], "PS.8.1", "Structure of matter", "SMALLEST TO LARGEST", ["SMALLEST", "LARGEST"], ["QUARK", "PROTON", "NUCLEUS", "ATOM", "MOLECULE"],
    "Quarks make up protons; protons (with neutrons) make up the nucleus; the nucleus is the center of an atom; and atoms bond into molecules."),
  S("sci-8-02", ["8"], "ESS.8.1", "Rock layers and relative age", "ROCK LAYERS: OLDEST FIRST", ["OLDEST", "YOUNGEST"], ["LIMESTONE", "SHALE", "SANDSTONE", "DIKE"],
    "Superposition: lower layers formed first, so limestone is oldest, then shale, then sandstone. Cross-cutting: the dike cuts all three, so it is younger than all of them.",
    { passage: "A canyon wall shows sandstone on top, shale in the middle and limestone at the bottom. A dark igneous dike cuts through all three layers." }),
  S("sci-8-03", ["8"], "LS.8.3", "Evidence of evolution", "FIRST APPEARANCE IN FOSSILS", ["OLDEST", "NEWEST"], ["BACTERIA", "FISH", "DINOSAURS", "HUMANS"],
    "The fossil record shows single-celled life like bacteria first (over 3 billion years ago), then fish, then dinosaurs, and humans only very recently."),
  S("sci-8-04", ["8"], "LS.8.1", "Vaccines and immunity", "HOW A VACCINE PROTECTS", FL, ["VACCINE SHOT", "ANTIBODIES", "VIRUS ENTERS", "FAST DEFENSE"],
    "A vaccine trains the immune system to make antibodies and memory cells. Later, if the real virus enters, the body fights it off quickly."),

  /* ---------------- 9-12 (4-5 slabs) ---------------- */
  S("sci-9-01", ["9"], "ESS.EES.2.2", "The rock cycle", "ONE PATH THROUGH THE ROCK CYCLE", FL, ["MAGMA", "IGNEOUS ROCK", "SEDIMENT", "SEDIMENTARY", "METAMORPHIC"],
    "Magma cools into igneous rock; weathering breaks it into sediment; compaction and cementation make sedimentary rock; heat and pressure change it into metamorphic rock.",
    { passage: "Magma cools into rock. Wind and rain break that rock into bits. The bits are pressed and cemented. Deep burial heats and squeezes the rock." }),
  S("sci-9-02", ["9"], "ESS.EES.1", "Stars", "LIFE OF A SUN-LIKE STAR", FL, ["NEBULA", "PROTOSTAR", "MAIN SEQ.", "RED GIANT", "WHITE DWARF"],
    "A cloud of gas (nebula) collapses into a protostar, which fuses hydrogen for billions of years on the main sequence, swells into a red giant, and ends as a white dwarf."),
  S("sci-9-03", ["9"], "ESS.EES.2", "Earth's layers", "EARTH'S LAYERS, SURFACE DOWN", ["SURFACE", "CENTER"], ["CRUST", "MANTLE", "OUTER CORE", "INNER CORE"],
    "From the surface down: the thin rocky crust, the thick mantle, the liquid outer core and the solid inner core."),
  S("sci-9-04", ["9"], "ESS.EES.1", "Scale of the universe", "SIZES IN SPACE", ["SMALLEST", "LARGEST"], ["MOON", "EARTH", "SUN", "SOLAR SYSTEM", "MILKY WAY"],
    "The moon is smaller than Earth, Earth is tiny next to the sun, the sun is one part of the solar system, and the solar system is one of billions in the Milky Way."),
  S("sci-9-05", ["9"], "ESS.EES.2", "Plate tectonics", "LIFE OF OCEAN CRUST", FL, ["MAGMA RISES", "NEW CRUST", "SPREADS", "SUBDUCTS"],
    "At a mid-ocean ridge magma rises and cools into new crust, which spreads away from the ridge and finally sinks (subducts) at a trench.",
    { passage: "Follow one piece of ocean floor from the ridge to the trench." }),
  S("sci-10-01", ["10"], "LS.Bio.1", "Cell cycle", "THE CELL CYCLE", FL, ["INTERPHASE", "PROPHASE", "METAPHASE", "ANAPHASE", "TELOPHASE"],
    "The cell copies its DNA in interphase; chromosomes condense (prophase), line up in the middle (metaphase), pull apart (anaphase), and two nuclei form (telophase)."),
  S("sci-10-02", ["10"], "LS.Bio.5", "Protein synthesis", "FROM DNA TO PROTEIN", FL, ["DNA", "TRANSCRIBE", "mRNA", "TRANSLATE", "PROTEIN"],
    "In transcription a gene in DNA is copied into mRNA; in translation a ribosome reads the mRNA codons to build a protein.",
    { say: ["DNA", "transcription", "messenger RNA", "translation", "protein"] }),
  S("sci-10-03", ["10"], "LS.Bio.4", "Levels of ecology", "LEVELS OF ECOLOGY", ["SMALLEST", "LARGEST"], ["ORGANISM", "POPULATION", "COMMUNITY", "ECOSYSTEM", "BIOSPHERE"],
    "One organism; a population of one species; a community of many species; an ecosystem adds the nonliving parts; the biosphere is all life on Earth."),
  S("sci-10-04", ["10"], "LS.Bio.3", "Cellular respiration", "CELLULAR RESPIRATION", FL, ["GLUCOSE", "GLYCOLYSIS", "KREBS CYCLE", "ELEC CHAIN"],
    "Glucose is split in glycolysis, the pieces are broken down in the Krebs cycle, and the electron transport chain makes most of the ATP.",
    { say: ["glucose", "glycolysis", "Krebs cycle", "electron transport chain"] }),
  S("sci-10-05", ["10"], "LS.Bio.6", "Classification", "CLASSIFICATION LEVELS", ["BROADEST", "NARROWEST"], ["DOMAIN", "KINGDOM", "PHYLUM", "CLASS", "ORDER"],
    "Classification goes from broad to narrow: domain, kingdom, phylum, class, order (then family, genus, species)."),
  S("sci-11-01", ["11"], "PS.Chm.1", "Atomic models", "ATOMIC MODELS IN HISTORY", ["EARLIEST", "LATEST"], ["DALTON", "THOMSON", "RUTHERFORD", "BOHR", "SCHRODINGER"],
    "Dalton's solid atom (1803), Thomson's plum pudding (1904), Rutherford's nucleus (1911), Bohr's energy levels (1913), Schrödinger's electron cloud (1926).",
    { say: ["Dalton", "Thomson", "Rutherford", "Bohr", "Schrödinger"] }),
  S("sci-11-02", ["11"], "PS.Chm.1", "Electron configuration", "ELECTRON FILLING ORDER", FL, ["1s", "2s", "2p", "3s", "3p"],
    "Electrons fill the lowest energy orbitals first: 1s, 2s, 2p, 3s, 3p (the Aufbau principle).", { say: ["1 s", "2 s", "2 p", "3 s", "3 p"] }),
  S("sci-11-03", ["11"], "PS.Chm.4", "Stoichiometry", "GRAMS OF A TO GRAMS OF B", FL, ["GRAMS A", "MOLES A", "MOLES B", "GRAMS B"],
    "Divide by A's molar mass to get moles of A, use the mole ratio from the balanced equation to get moles of B, then multiply by B's molar mass.",
    { passage: "You know the mass of reactant A. Find the mass of product B." }),
  S("sci-11-04", ["11"], "PS.Chm.2.2", "Periodic trends", "ATOMIC RADIUS, PERIOD 3", ["LARGEST", "SMALLEST"], ["SODIUM", "MAGNESIUM", "ALUMINUM", "SILICON", "PHOSPHORUS"],
    "Across a period, more protons pull the electrons closer, so atomic radius shrinks from sodium to phosphorus."),
  S("sci-12-01", ["12"], "PS.Phy.7", "Electromagnetic spectrum", "EM SPECTRUM BY FREQUENCY", ["LOWEST", "HIGHEST"], ["INFRARED", "VISIBLE", "ULTRAVIOLET", "X-RAY", "GAMMA RAY"],
    "Frequency (and photon energy) increases from infrared to visible, ultraviolet, X-rays and gamma rays."),
  S("sci-12-02", ["12"], "PS.Phy.7", "Light and color", "COLORS BY WAVELENGTH", ["LONGEST", "SHORTEST"], ["RED", "ORANGE", "YELLOW", "GREEN", "BLUE"],
    "Red light has the longest wavelength (about 700 nm), then orange, yellow, green and blue (about 470 nm)."),
  S("sci-12-03", ["12"], "PS.Phy.6", "Energy transformations", "ENERGY AT A DAM", FL, ["HIGH WATER", "FALLING", "TURBINE", "GENERATOR", "ELECTRICITY"],
    "Water held high has gravitational potential energy; falling turns it into kinetic energy; it spins a turbine, which turns a generator that makes electricity."),
  S("sci-12-04", ["12"], "PS.Phy.1", "Motion", "BALL THROWN STRAIGHT UP", FL, ["LEAVES HAND", "SLOWING", "STOPS AT TOP", "SPEEDS DOWN", "CAUGHT"],
    "Gravity slows the ball on the way up until it stops for an instant at the top, then speeds it up on the way back down to your hand."),
];
