import type { Question } from "../../types";

// Grade 1 ELA — NC Standard Course of Study for ELA (2017). RL.1.1, RL.1.2, RL.1.3, RL.1.5, RL.1.6, RI.1.2, RI.1.5, RI.1.8, RF.1.1, RF.1.3, RF.1.4, RF.1.5, L.1.1, L.1.2, L.1.4, L.1.5
const questions: Question[] = [
  {
    id: "ela-g1-01",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Long and short vowels",
    prompt: "Which word has a long a sound?",
    choices: ["cake", "cat", "cap", "can"],
    answer: 0,
    explanation: "In cake, the a says its name. Cat, cap, and can have the short a sound.",
    quick: true,
  },
  {
    id: "ela-g1-02",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Blending sounds",
    prompt: "Blend /sh/ /i/ /p/. What word is it?",
    choices: ["ship", "chip", "sip", "shop"],
    answer: 0,
    explanation: "Put the sounds together: sh-i-p makes ship.",
    quick: true,
  },
  {
    id: "ela-g1-03",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Segmenting sounds",
    prompt: "How many sounds are in frog?",
    choices: ["4", "3", "5", "2"],
    answer: 0,
    explanation: "Frog has four sounds: /f/ /r/ /o/ /g/.",
    quick: true,
  },
  {
    id: "ela-g1-04",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with light?",
    choices: ["night", "lit", "lip", "late"],
    answer: 0,
    explanation: "Light and night both end with the -ight sound.",
    quick: true,
  },
  {
    id: "ela-g1-05",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Digraphs",
    prompt: "Which word begins with ch?",
    choices: ["chin", "shin", "thin", "win"],
    answer: 0,
    explanation: "Chin starts with ch, two letters that make one sound: /ch/.",
    quick: true,
  },
  {
    id: "ela-g1-06",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Silent e",
    prompt: "Add an e to the end of kit. What word do you get?",
    choices: ["kite", "kitty", "kits", "kid"],
    answer: 0,
    explanation: "A silent e at the end makes the i say its name: kit becomes kite.",
    quick: true,
  },
  {
    id: "ela-g1-07",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Vowel teams",
    prompt: "Which word has the long e sound spelled ee?",
    choices: ["tree", "bread", "boat", "rain"],
    answer: 0,
    explanation: "In tree, the two e's team up to say the long e sound.",
    quick: true,
  },
  {
    id: "ela-g1-08",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Syllables",
    prompt: "How many syllables are in sunset?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "Sun-set has two parts, so it has two syllables.",
    quick: true,
  },
  {
    id: "ela-g1-09",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Word endings",
    prompt: "Which word means the jumping already happened?",
    choices: ["jumped", "jumps", "jumping", "jump"],
    answer: 0,
    explanation: "The ending -ed tells us something already happened.",
    quick: true,
  },
  {
    id: "ela-g1-10",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Sight words",
    prompt: "Which word is spelled correctly?",
    choices: ["said", "sed", "siad", "sayd"],
    answer: 0,
    explanation: "Said is a tricky sight word. It is spelled s-a-i-d.",
    quick: true,
  },
  {
    id: "ela-g1-11",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Nouns",
    prompt: "Which word is a noun (a person, place, or thing)?",
    choices: ["school", "run", "happy", "quickly"],
    answer: 0,
    explanation: "A school is a place, so it is a noun.",
    quick: true,
  },
  {
    id: "ela-g1-12",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Verbs",
    prompt: "Which word is an action word (a verb)?",
    choices: ["hop", "cup", "red", "soft"],
    answer: 0,
    explanation: "Hop is something you can do, so it is a verb.",
    quick: true,
  },
  {
    id: "ela-g1-13",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "End marks",
    prompt: "Which mark goes at the end of a question?",
    choices: ["?", ".", "!", ","],
    answer: 0,
    explanation: "A question mark (?) ends a sentence that asks something.",
    quick: true,
  },
  {
    id: "ela-g1-14",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "Capital letters",
    prompt: "Which word should always start with a capital letter?",
    choices: ["Monday", "apple", "dog", "city"],
    answer: 0,
    explanation: "Names of days, like Monday, always begin with a capital letter.",
    quick: true,
  },
  {
    id: "ela-g1-15",
    subject: "ela",
    grade: "1",
    standard: "L.1.5",
    skill: "Sorting words",
    prompt: "Which word does not belong: red, blue, green, dog?",
    choices: ["dog", "red", "blue", "green"],
    answer: 0,
    explanation: "Red, blue, and green are colors. A dog is an animal.",
    quick: true,
  },
  {
    id: "ela-g1-16",
    subject: "ela",
    grade: "1",
    standard: "RI.1.5",
    skill: "Text features",
    prompt: "What are the words under a picture that tell about it?",
    choices: ["caption", "title", "author", "glossary"],
    answer: 0,
    explanation: "A caption is a short label that explains a picture or photo.",
    quick: true,
  },
  {
    id: "ela-g1-17",
    subject: "ela",
    grade: "1",
    standard: "RL.1.5",
    skill: "Fiction and nonfiction",
    prompt: "A book that tells a made-up story is called...",
    choices: ["fiction", "nonfiction", "a glossary", "a label"],
    answer: 0,
    explanation: "Fiction tells made-up stories. Nonfiction gives true information.",
    quick: true,
  },
  {
    id: "ela-g1-18",
    subject: "ela",
    grade: "1",
    standard: "RL.1.1",
    skill: "Key details",
    prompt: "Where did Sam find his kite?",
    passage: "Sam lost his red kite in the wind. He looked in the yard and by the pond. At last he saw it stuck in the big oak tree. His dad got a ladder and helped him get it down. Sam hugged his kite and smiled.",
    choices: ["In a tree", "By the pond", "In the yard", "Under his bed"],
    answer: 0,
    explanation: "The story says Sam saw his kite stuck in the big oak tree.",
  },
  {
    id: "ela-g1-19",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Long and short vowels",
    prompt: "Which word has a short o sound, like in hot?",
    choices: ["mop", "rope", "boat", "cute"],
    answer: 0,
    explanation: "Mop has the short o sound, /o/, like hot. Rope and boat have a long o.",
    quick: true,
  },
  {
    id: "ela-g1-20",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Long and short vowels",
    prompt: "Which word has a long i sound?",
    choices: ["bike", "bit", "big", "fin"],
    answer: 0,
    explanation: "In bike, the i says its name. Bit, big, and fin have a short i.",
    quick: true,
  },
  {
    id: "ela-g1-21",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Blending sounds",
    prompt: "Blend /s/ /t/ /o/ /p/. What word is it?",
    choices: ["stop", "spot", "top", "step"],
    answer: 0,
    explanation: "Put the sounds together in order: s-t-o-p makes stop.",
    quick: true,
  },
  {
    id: "ela-g1-22",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Ending sounds",
    prompt: "What is the last sound in duck?",
    choices: ["/k/", "/d/", "/u/", "/t/"],
    answer: 0,
    explanation: "Duck ends with /k/. The letters ck make that sound.",
    quick: true,
  },
  {
    id: "ela-g1-23",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Digraphs",
    prompt: "Which word ends with the /th/ sound?",
    choices: ["bath", "bat", "bash", "back"],
    answer: 0,
    explanation: "Bath ends with th, two letters that make one sound.",
    quick: true,
  },
  {
    id: "ela-g1-24",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Digraphs",
    prompt: "Which word starts with the /sh/ sound?",
    choices: ["shell", "chip", "sell", "chess"],
    answer: 0,
    explanation: "Shell starts with sh. Chip and chess start with ch.",
    quick: true,
  },
  {
    id: "ela-g1-25",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Silent e",
    prompt: "Which word has a silent e at the end?",
    choices: ["home", "hop", "hot", "him"],
    answer: 0,
    explanation: "Home ends in a silent e that makes the o say its name.",
    quick: true,
  },
  {
    id: "ela-g1-26",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Vowel teams",
    prompt: "Which word has the long a sound spelled ai?",
    choices: ["paint", "pant", "pat", "pet"],
    answer: 0,
    explanation: "In paint, the letters a and i team up to say the long a sound.",
    quick: true,
  },
  {
    id: "ela-g1-27",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Vowel teams",
    prompt: "Which word has the long o sound spelled oa?",
    choices: ["coat", "cot", "cut", "cat"],
    answer: 0,
    explanation: "In coat, o and a team up to say the long o sound.",
    quick: true,
  },
  {
    id: "ela-g1-28",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Syllables",
    prompt: "How many syllables are in elephant?",
    choices: ["3", "2", "4", "1"],
    answer: 0,
    explanation: "El-e-phant has three parts, and each part has a vowel sound.",
    quick: true,
  },
  {
    id: "ela-g1-29",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Word endings",
    prompt: "Which word means more than one wish?",
    choices: ["wishes", "wished", "wishing", "wish"],
    answer: 0,
    explanation: "We add -es to wish to make wishes.",
    quick: true,
  },
  {
    id: "ela-g1-30",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Word endings",
    prompt: "Sam is ___ ball right now. Which word fits?",
    choices: ["playing", "played", "play", "plays"],
    answer: 0,
    explanation: "The -ing ending shows something is happening right now.",
    quick: true,
  },
  {
    id: "ela-g1-31",
    subject: "ela",
    grade: "1",
    standard: "RF.1.5",
    skill: "Using context",
    prompt: "Which word makes sense? The dog wagged its ___.",
    choices: ["tail", "tall", "tell", "toll"],
    answer: 0,
    explanation: "Dogs wag their tails, so tail makes sense in the sentence.",
    quick: true,
  },
  {
    id: "ela-g1-32",
    subject: "ela",
    grade: "1",
    standard: "RF.1.1",
    skill: "Print features",
    prompt: "What does every sentence start with?",
    choices: ["capital letter", "period", "number", "comma"],
    answer: 0,
    explanation: "Every sentence starts with a capital letter and ends with an end mark.",
    quick: true,
  },
  {
    id: "ela-g1-33",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Adjectives",
    prompt: "Which word describes something (an adjective)?",
    choices: ["soft", "jump", "desk", "sing"],
    answer: 0,
    explanation: "Soft tells what something feels like, so it is an adjective.",
    quick: true,
  },
  {
    id: "ela-g1-34",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Pronouns",
    prompt: "Tom and I went home. Which word can take the place of Tom and I?",
    choices: ["We", "They", "He", "Us"],
    answer: 0,
    explanation: "We means me and someone else: We went home.",
    quick: true,
  },
  {
    id: "ela-g1-35",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Past tense",
    prompt: "Yesterday we ___ a cake. Which word fits?",
    choices: ["baked", "bake", "bakes", "baking"],
    answer: 0,
    explanation: "Yesterday means it already happened, so we use baked.",
    quick: true,
  },
  {
    id: "ela-g1-36",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Proper nouns",
    prompt: "Which is a proper noun (a special name)?",
    choices: ["Texas", "city", "river", "girl"],
    answer: 0,
    explanation: "Texas is the name of a special place, so it is a proper noun.",
    quick: true,
  },
  {
    id: "ela-g1-37",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "Commas in dates",
    prompt: "Which date has the comma in the right place?",
    choices: ["May 4, 2026", "May, 4 2026", "May 4 2026,", "May 4 20,26"],
    answer: 0,
    explanation: "The comma goes between the day and the year: May 4, 2026.",
    quick: true,
  },
  {
    id: "ela-g1-38",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "End marks",
    prompt: "Which mark ends a sentence that shows strong feeling?",
    choices: ["!", "?", ".", ","],
    answer: 0,
    explanation: "An exclamation mark (!) shows strong feeling, like 'We won!'",
    quick: true,
  },
  {
    id: "ela-g1-39",
    subject: "ela",
    grade: "1",
    standard: "L.1.5",
    skill: "Categories",
    prompt: "A robin, a crow, and an owl are all...",
    choices: ["birds", "bugs", "fish", "pets"],
    answer: 0,
    explanation: "Robins, crows, and owls all have feathers and wings. They are birds.",
    quick: true,
  },
  {
    id: "ela-g1-40",
    subject: "ela",
    grade: "1",
    standard: "L.1.5",
    skill: "Shades of meaning",
    prompt: "Which word means to look at something for a long time?",
    choices: ["stare", "glance", "peek", "blink"],
    answer: 0,
    explanation: "To stare is to look for a long time. A glance or a peek is quick.",
    quick: true,
  },
  {
    id: "ela-g1-41",
    subject: "ela",
    grade: "1",
    standard: "L.1.5",
    skill: "Defining words",
    prompt: "A tiger is a big cat with...",
    choices: ["stripes", "feathers", "wings", "scales"],
    answer: 0,
    explanation: "Tigers are big cats with striped fur.",
    quick: true,
  },
  {
    id: "ela-g1-42",
    subject: "ela",
    grade: "1",
    standard: "L.1.4",
    skill: "Multiple-meaning words",
    prompt: "In 'I can bat the ball,' what does bat mean?",
    choices: ["to hit", "an animal", "to sleep", "to throw"],
    answer: 0,
    explanation: "Bat can mean a flying animal, but here it means to hit the ball.",
    quick: true,
  },
  {
    id: "ela-g1-43",
    subject: "ela",
    grade: "1",
    standard: "RL.1.1",
    skill: "Key details",
    prompt: "What did Rosa put in the muffins?",
    passage: "Rosa wanted to bake muffins. She mixed flour, eggs, and blueberries. The muffins smelled so good that her brother came running.",
    choices: ["blueberries", "apples", "nuts", "carrots"],
    answer: 0,
    explanation: "The story says Rosa mixed in blueberries.",
  },
  {
    id: "ela-g1-44",
    subject: "ela",
    grade: "1",
    standard: "RL.1.3",
    skill: "Character feelings",
    prompt: "How did Leo feel?",
    passage: "Leo lost his first tooth at lunch. He held it up and grinned. 'Look!' he shouted to his friends.",
    choices: ["excited", "sad", "scared", "sleepy"],
    answer: 0,
    explanation: "Leo grinned and shouted 'Look!' Those clues show he was excited.",
  },
  {
    id: "ela-g1-45",
    subject: "ela",
    grade: "1",
    standard: "RL.1.6",
    skill: "Who is telling",
    prompt: "Who is telling this story?",
    passage: "I am a little seed. The rain gives me a drink. The sun keeps me warm. Soon I will be a flower!",
    choices: ["a seed", "the sun", "the rain", "a girl"],
    answer: 0,
    explanation: "The words 'I am a little seed' tell us the seed is talking.",
  },
  {
    id: "ela-g1-46",
    subject: "ela",
    grade: "1",
    standard: "RI.1.2",
    skill: "Main topic",
    prompt: "What is the main topic?",
    passage: "Bats sleep in the day. At night, they fly out to find food. Many bats eat bugs. Some bats eat fruit.",
    choices: ["bats", "bugs", "fruit", "night"],
    answer: 0,
    explanation: "Every sentence tells something about bats.",
  },
  {
    id: "ela-g1-47",
    subject: "ela",
    grade: "1",
    standard: "RI.1.8",
    skill: "Author's reasons",
    prompt: "What reason does the author give for wearing a helmet?",
    passage: "Wear a helmet when you ride a bike. A helmet keeps your head safe if you fall.",
    choices: ["It keeps your head safe.", "It looks cool.", "It keeps you warm.", "It makes you fast."],
    answer: 0,
    explanation: "The author says a helmet keeps your head safe if you fall.",
  },
  {
    id: "ela-g1-48",
    subject: "ela",
    grade: "1",
    standard: "RL.1.2",
    skill: "Lesson",
    prompt: "What is the lesson of this story?",
    passage: "Two goats met on a narrow bridge. Neither would step back, so they both fell into the river. The next day, one goat let the other cross first, and both stayed dry.",
    choices: ["Taking turns helps everyone.", "Goats can swim.", "Bridges are fun.", "Always go first."],
    answer: 0,
    explanation: "When one goat let the other go first, both stayed dry. Taking turns helped them both.",
  },
];

export default questions;
