import type { Question } from "../../types";

// Grade 10 ELA — NC Standard Course of Study for ELA (2017). English II (9-10 band): RL.9-10.1, RL.9-10.2, RL.9-10.3, RL.9-10.4, RL.9-10.5, RL.9-10.6, RL.9-10.9, RI.9-10.2, RI.9-10.3, RI.9-10.4, RI.9-10.5, RI.9-10.6, RI.9-10.8, RI.9-10.9, L.9-10.1, L.9-10.2, L.9-10.4, L.9-10.5
const questions: Question[] = [
  {
    id: "ela-g10-01",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "Twisting an opponent's argument so it's easy to attack is a...",
    choices: ["straw man", "red herring", "ad hominem", "slippery slope"],
    answer: 0,
    explanation: "A straw man replaces the real argument with a weaker version that is easy to knock down.",
    quick: true,
  },
  {
    id: "ela-g10-02",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'Either we ban all cars or the planet is doomed' is a...",
    choices: ["false dilemma", "straw man", "red herring", "ad hominem"],
    answer: 0,
    explanation: "A false dilemma pretends there are only two options when more exist.",
    quick: true,
  },
  {
    id: "ela-g10-03",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Logical fallacies",
    prompt: "'If we allow one late pass, soon no one will be on time' is a...",
    choices: ["slippery slope", "bandwagon", "ethos", "false dilemma"],
    answer: 0,
    explanation: "A slippery slope claims one small step will lead to extreme results without proof.",
    quick: true,
  },
  {
    id: "ela-g10-04",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "An appeal using facts, data, and reasoning is...",
    choices: ["logos", "pathos", "ethos", "mythos"],
    answer: 0,
    explanation: "Logos appeals to logic with evidence and clear reasoning.",
    quick: true,
  },
  {
    id: "ela-g10-05",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Conjunctions and clauses",
    prompt: "Which word is a subordinating conjunction?",
    choices: ["although", "and", "but", "or"],
    answer: 0,
    explanation: "Although begins a dependent clause. And, but, and or are coordinating conjunctions.",
    quick: true,
  },
  {
    id: "ela-g10-06",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.2",
    skill: "Colons",
    prompt: "Which mark introduces a list after a complete sentence?",
    choices: ["colon", "semicolon", "comma", "hyphen"],
    answer: 0,
    explanation: "A colon follows an independent clause to introduce a list, quote, or explanation.",
    quick: true,
  },
  {
    id: "ela-g10-07",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Word forms",
    prompt: "Which word is the noun form of analyze?",
    choices: ["analysis", "analytic", "analytical", "analyzed"],
    answer: 0,
    explanation: "Analysis is the noun. Analytic and analytical are adjectives; analyzed is a verb.",
    quick: true,
  },
  {
    id: "ela-g10-08",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Greek and Latin roots",
    prompt: "The root bell (as in belligerent) means...",
    choices: ["war", "beauty", "noise", "peace"],
    answer: 0,
    explanation: "Latin bellum means war, so a belligerent person is hostile or ready to fight.",
    quick: true,
  },
  {
    id: "ela-g10-09",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Narrative structure",
    prompt: "Hints about what will happen later in a story are...",
    choices: ["foreshadowing", "flashback", "epilogue", "exposition"],
    answer: 0,
    explanation: "Foreshadowing plants clues that build tension and expectation.",
    quick: true,
  },
  {
    id: "ela-g10-10",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.9",
    skill: "Allusion",
    prompt: "A reference to a well-known myth, text, or event is an...",
    choices: ["allusion", "illusion", "elegy", "idiom"],
    answer: 0,
    explanation: "An allusion borrows meaning from something the reader already knows. An illusion is a false image.",
    quick: true,
  },
  {
    id: "ela-g10-11",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.5",
    skill: "Nuance in word meaning",
    prompt: "Which word means stubborn in the most negative way?",
    choices: ["pigheaded", "determined", "persistent", "steadfast"],
    answer: 0,
    explanation: "Determined, persistent, and steadfast sound admirable; pigheaded is an insult.",
    quick: true,
  },
  {
    id: "ela-g10-12",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.4",
    skill: "Mood",
    prompt: "The feeling a text creates in the reader is its...",
    choices: ["mood", "tone", "theme", "voice"],
    answer: 0,
    explanation: "Mood is the reader's emotional atmosphere; tone is the author's attitude.",
    quick: true,
  },
  {
    id: "ela-g10-13",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.9",
    skill: "Archetypes",
    prompt: "The hero's journey is an example of an...",
    choices: ["archetype", "oxymoron", "epigraph", "anecdote"],
    answer: 0,
    explanation: "An archetype is a pattern, like the hero's journey, that appears across many cultures' stories.",
    quick: true,
  },
  {
    id: "ela-g10-14",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Phrases and clauses",
    prompt: "In 'The novel that won the prize was written in Lagos,' what is 'that won the prize'?",
    choices: ["an adjective clause modifying novel", "an adverb clause modifying written", "a noun clause used as the subject", "a prepositional phrase"],
    answer: 0,
    explanation: "The clause has a subject and verb and describes which novel, so it is an adjective (relative) clause.",
  },
  {
    id: "ela-g10-15",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.6",
    skill: "Cultural perspective",
    prompt: "What does this passage mainly reveal?",
    passage: "In my grandmother's village, a guest is never asked whether they are hungry; a plate simply appears. When my roommate asked if I wanted a snack, I said no out of politeness, and then waited, stomach growling, for the plate that never came.",
    choices: ["How cultural norms shape everyday moments", "That the roommate was rude", "That the narrator dislikes the food", "That the grandmother is a chef"],
    answer: 0,
    explanation: "The misunderstanding comes from different cultural expectations about offering food.",
  },
  {
    id: "ela-g10-16",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.5",
    skill: "Text structure",
    prompt: "How is this paragraph structured?",
    passage: "Many assume the Great Wall of China was built all at once. In fact, it is a series of walls constructed over many centuries by different dynasties, each adding, rebuilding, or abandoning sections.",
    choices: ["It states a misconception, then corrects it.", "It lists events in time order.", "It compares two different walls.", "It describes a problem and a solution."],
    answer: 0,
    explanation: "'Many assume' introduces a common belief; 'In fact' corrects it.",
  },
  {
    id: "ela-g10-17",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Pacing",
    prompt: "What effect do the short sentences and fragments create?",
    passage: "The clock ticked. Mara's hand hovered over the button. One second. Two. Her breath caught. Three.",
    choices: ["tension", "calm reflection", "humor", "confusion about the setting"],
    answer: 0,
    explanation: "Short, clipped sentences slow time down second by second and build suspense.",
  },
  {
    id: "ela-g10-18",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does trepidation most likely mean?",
    passage: "Despite the team's initial trepidation about the steep climb, they reached the summit with confidence and laughter.",
    choices: ["fear or worry", "excitement", "exhaustion", "disbelief"],
    answer: 0,
    explanation: "'Despite' signals a contrast with 'confidence,' so trepidation means fear or worry.",
  },
  {
    id: "ela-g10-19",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Latin roots",
    prompt: "The Latin root jud (as in judicial) means...",
    choices: ["judge", "power", "people", "write"],
    answer: 0,
    explanation: "Jud means judge, as in judicial and judgment.",
    quick: true,
  },
  {
    id: "ela-g10-20",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Greek roots",
    prompt: "The Greek root dem (as in democracy) means...",
    choices: ["people", "rule", "city", "law"],
    answer: 0,
    explanation: "Dem means people. Democracy is rule by the people.",
    quick: true,
  },
  {
    id: "ela-g10-21",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Greek prefixes",
    prompt: "The prefix hyper- (as in hyperactive) means...",
    choices: ["over", "under", "beside", "against"],
    answer: 0,
    explanation: "Hyper- means over or beyond. Hypo- means under.",
    quick: true,
  },
  {
    id: "ela-g10-22",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Latin roots",
    prompt: "The Latin root pac (as in pacify) means...",
    choices: ["peace", "pack", "father", "step"],
    answer: 0,
    explanation: "Pac means peace. To pacify is to calm or make peaceful.",
    quick: true,
  },
  {
    id: "ela-g10-23",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Suffixes",
    prompt: "Adding -ify to solid makes a word meaning...",
    choices: ["to make solid", "very solid", "not solid", "a solid one"],
    answer: 0,
    explanation: "The suffix -ify means to make, so solidify means to make solid.",
    quick: true,
  },
  {
    id: "ela-g10-24",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.5",
    skill: "Nuance",
    prompt: "Which word suggests someone is too sure of themselves?",
    choices: ["arrogant", "confident", "assured", "poised"],
    answer: 0,
    explanation: "Arrogant has a negative connotation. The others suggest healthy self-belief.",
    quick: true,
  },
  {
    id: "ela-g10-25",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.5",
    skill: "Chiasmus",
    prompt: "'Ask not what your country can do for you...' reverses phrases. This is...",
    choices: ["chiasmus", "anaphora", "simile", "litotes"],
    answer: 0,
    explanation: "Chiasmus repeats ideas in reverse order for emphasis, as in Kennedy's famous line.",
    quick: true,
  },
  {
    id: "ela-g10-26",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.5",
    skill: "Connotation",
    prompt: "Which word for old is the most respectful?",
    choices: ["venerable", "decrepit", "ancient", "worn-out"],
    answer: 0,
    explanation: "Venerable means old and deserving respect. Decrepit means weak and broken down.",
    quick: true,
  },
  {
    id: "ela-g10-27",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Noun clauses",
    prompt: "In 'Whoever wins gets a prize,' 'Whoever wins' is a(n) ___ clause.",
    choices: ["noun", "adverb", "adjective", "independent"],
    answer: 0,
    explanation: "The clause is the subject of the sentence, so it is a noun clause.",
    quick: true,
  },
  {
    id: "ela-g10-28",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Absolute phrases",
    prompt: "'Her hands trembling, she opened the letter.' 'Her hands trembling' is a(n)...",
    choices: ["absolute", "appositive", "gerund", "infinitive"],
    answer: 0,
    explanation: "An absolute phrase has a noun plus a participle and modifies the whole sentence.",
    quick: true,
  },
  {
    id: "ela-g10-29",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.2",
    skill: "Colons",
    prompt: "'She had one goal ___ to win.' Which mark fits best?",
    choices: ["colon", "semicolon", "apostrophe", "quotation mark"],
    answer: 0,
    explanation: "A colon introduces an explanation after a complete sentence.",
    quick: true,
  },
  {
    id: "ela-g10-30",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.2",
    skill: "Spelling",
    prompt: "Which spelling is correct?",
    choices: ["conscientious", "consientious", "conscientous", "consciencious"],
    answer: 0,
    explanation: "Conscientious comes from conscience, so it keeps the sc and the ti.",
    quick: true,
  },
  {
    id: "ela-g10-31",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.3",
    skill: "Character types",
    prompt: "A character who exists mainly as a familiar type is a ___ character.",
    choices: ["stock", "round", "dynamic", "foil"],
    answer: 0,
    explanation: "Stock characters, like the mad scientist, are recognizable types.",
    quick: true,
  },
  {
    id: "ela-g10-32",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Poetic structure",
    prompt: "A pause in the middle of a line of poetry is a...",
    choices: ["caesura", "couplet", "refrain", "stanza"],
    answer: 0,
    explanation: "A caesura is a break within a line, often marked by punctuation.",
    quick: true,
  },
  {
    id: "ela-g10-33",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.5",
    skill: "Enjambment",
    prompt: "When a sentence runs past a line break without pausing, it's...",
    choices: ["enjambment", "caesura", "a refrain", "rhyme"],
    answer: 0,
    explanation: "Enjambment carries a thought from one line into the next.",
    quick: true,
  },
  {
    id: "ela-g10-34",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.4",
    skill: "Imagery",
    prompt: "Language that appeals to the five senses is called...",
    choices: ["imagery", "diction", "syntax", "irony"],
    answer: 0,
    explanation: "Imagery helps readers see, hear, smell, taste, and feel the scene.",
    quick: true,
  },
  {
    id: "ela-g10-35",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.6",
    skill: "Point of view",
    prompt: "A narrator who knows only one character's thoughts is...",
    choices: ["third limited", "omniscient", "objective", "second person"],
    answer: 0,
    explanation: "Third-person limited stays inside one character's mind.",
    quick: true,
  },
  {
    id: "ela-g10-36",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.8",
    skill: "Red herring",
    prompt: "Changing the subject to distract from the real issue is a...",
    choices: ["red herring", "straw man", "bandwagon", "false dilemma"],
    answer: 0,
    explanation: "A red herring leads the audience away from the actual argument.",
    quick: true,
  },
  {
    id: "ela-g10-37",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.6",
    skill: "Rhetorical appeals",
    prompt: "Fitting an argument to the right moment or occasion is...",
    choices: ["kairos", "ethos", "logos", "pathos"],
    answer: 0,
    explanation: "Kairos is the Greek idea of the timely, opportune moment to speak.",
    quick: true,
  },
  {
    id: "ela-g10-38",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.9",
    skill: "Seminal documents",
    prompt: "'Four score and seven years ago' opens Lincoln's ___ Address.",
    choices: ["Gettysburg", "Farewell", "Inaugural", "Cooper Union"],
    answer: 0,
    explanation: "Lincoln opened the Gettysburg Address (1863) with these words.",
    quick: true,
  },
  {
    id: "ela-g10-39",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.1",
    skill: "Textual evidence",
    prompt: "What does this detail most strongly suggest?",
    passage: "Mrs. Okafor smiled warmly at the new neighbors. Then, once the door closed, she drew every curtain in the house and checked the lock twice.",
    choices: ["She distrusts the new neighbors.", "She is rude to everyone.", "She is going to bed.", "She is eager to meet them."],
    answer: 0,
    explanation: "Her warm smile hides worry: she shuts every curtain and checks the lock twice.",
  },
  {
    id: "ela-g10-40",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.2",
    skill: "Theme and symbol",
    prompt: "What theme does the rosebush help develop?",
    passage: "Every spring, Lena's grandmother replanted the same rosebush, though deer ate it every summer. 'Why bother?' Lena asked. 'Because spring comes anyway,' her grandmother said.",
    choices: ["Hope and persistence despite loss.", "Deer are garden pests.", "Gardening wastes time.", "Spring is the best season."],
    answer: 0,
    explanation: "The grandmother keeps replanting because she trusts spring will come again.",
  },
  {
    id: "ela-g10-41",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.3",
    skill: "Character interaction",
    prompt: "What does Theo's response reveal?",
    passage: "When Jonah confessed to breaking the trophy, his rival Theo, who had been blamed for it, said nothing. Then he quietly withdrew his complaint to the principal.",
    choices: ["a capacity for forgiveness", "a desire for revenge", "indifference to fairness", "fear of Jonah"],
    answer: 0,
    explanation: "Theo was wrongly blamed, yet he quietly drops his complaint instead of seeking payback.",
  },
  {
    id: "ela-g10-42",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.4",
    skill: "Mood and diction",
    prompt: "What mood does the diction create?",
    passage: "The hallway smelled of bleach and old fear. Every door was shut, every chair bolted down, every clock ten minutes slow.",
    choices: ["oppressive and uneasy", "joyful", "peaceful", "humorous"],
    answer: 0,
    explanation: "Bleach, 'old fear,' bolted chairs, and wrong clocks create a tense, trapped feeling.",
  },
  {
    id: "ela-g10-43",
    subject: "ela",
    grade: "10",
    standard: "RL.9-10.9",
    skill: "Source material",
    prompt: "This plot most clearly draws on which classical work?",
    passage: "In the novel, a teenage girl defies the city council to give a proper burial to her brother, who has been declared a traitor.",
    choices: ["Antigone", "The Odyssey", "Beowulf", "Hamlet"],
    answer: 0,
    explanation: "In Sophocles' Antigone, a young woman defies the ruler to bury her brother.",
  },
  {
    id: "ela-g10-44",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.2",
    skill: "Central idea",
    prompt: "What is the central idea?",
    passage: "Although electric cars produce no tailpipe emissions, their environmental benefit depends heavily on how the electricity is generated. In regions powered mostly by coal, the advantage shrinks considerably.",
    choices: ["Electric cars' benefits depend on the power source.", "Electric cars pollute more than gas cars.", "Coal is a clean fuel.", "Electric cars have tailpipes."],
    answer: 0,
    explanation: "The passage says the benefit shrinks where electricity comes from coal.",
  },
  {
    id: "ela-g10-45",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.3",
    skill: "Cause and effect",
    prompt: "How does the author organize these events?",
    passage: "When the factory closed, hundreds lost their jobs. With fewer customers, the diner and the hardware store shut down. Young families moved away, and the elementary school merged with the next town's.",
    choices: ["as a chain of causes and effects", "as a comparison", "from newest to oldest", "by order of importance"],
    answer: 0,
    explanation: "Each event leads to the next: the factory closing sets off the rest.",
  },
  {
    id: "ela-g10-46",
    subject: "ela",
    grade: "10",
    standard: "RI.9-10.4",
    skill: "Word choice",
    prompt: "What does this phrase reveal about the company?",
    passage: "The company described the layoffs of 300 workers as a 'workforce realignment.'",
    choices: ["It softens bad news with vague words.", "It speaks bluntly.", "It celebrates growth.", "It is joking."],
    answer: 0,
    explanation: "'Workforce realignment' is a vague euphemism for firing people.",
  },
  {
    id: "ela-g10-47",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.4",
    skill: "Context clues",
    prompt: "What does meticulous mean?",
    passage: "The scientist was meticulous, recording every measurement to the hundredth of a gram and double-checking each calculation.",
    choices: ["extremely careful", "careless", "creative", "impatient"],
    answer: 0,
    explanation: "Recording to the hundredth of a gram and double-checking shows extreme care.",
  },
  {
    id: "ela-g10-48",
    subject: "ela",
    grade: "10",
    standard: "L.9-10.1",
    skill: "Subject-verb agreement",
    prompt: "Which sentence has correct subject-verb agreement?",
    choices: ["Each of the players has a locker.", "Each of the players have a locker.", "Each of the players are given a locker.", "Each of the players were given a locker."],
    answer: 0,
    explanation: "Each is singular, so it takes the singular verb has.",
  },
];

export default questions;
