import type { Question } from "../../types";

// Grade 2 ELA — NC Standard Course of Study for ELA (2017). RL.2.1, RL.2.2, RL.2.3, RL.2.4, RL.2.5, RL.2.6, RI.2.2, RI.2.3, RI.2.4, RI.2.5, RI.2.6, RI.2.8, RF.2.4, RF.2.5, L.2.1, L.2.2, L.2.3, L.2.4, L.2.5
const questions: Question[] = [
  {
    id: "ela-g2-01",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Long and short vowels",
    prompt: "Which word has a long o sound?",
    choices: ["boat", "hot", "top", "mop"],
    answer: 0,
    explanation: "In boat, the oa team makes the long o sound. Hot, top, and mop have short o.",
    quick: true,
  },
  {
    id: "ela-g2-02",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Long and short vowels",
    prompt: "Which word has a short i sound?",
    choices: ["fish", "kite", "pie", "tree"],
    answer: 0,
    explanation: "Fish has the short i sound, /i/. Kite and pie have long i.",
    quick: true,
  },
  {
    id: "ela-g2-03",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Vowel teams",
    prompt: "Which word has the same vowel sound as rain?",
    choices: ["play", "ran", "rip", "road"],
    answer: 0,
    explanation: "Rain (ai) and play (ay) both have the long a sound.",
    quick: true,
  },
  {
    id: "ela-g2-04",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Syllables",
    prompt: "How do you split rabbit into syllables?",
    choices: ["rab-bit", "ra-bbit", "rabb-it", "r-abbit"],
    answer: 0,
    explanation: "When two consonants are in the middle, split between them: rab-bit.",
    quick: true,
  },
  {
    id: "ela-g2-05",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular plurals",
    prompt: "What is the plural of mouse?",
    choices: ["mice", "mouses", "mousies", "meese"],
    answer: 0,
    explanation: "Mouse has a special plural: one mouse, two mice.",
    quick: true,
  },
  {
    id: "ela-g2-06",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular verbs",
    prompt: "Yesterday I ___ to the park. Which word fits?",
    choices: ["went", "goed", "go", "going"],
    answer: 0,
    explanation: "Went is the past tense of go. We never say goed.",
    quick: true,
  },
  {
    id: "ela-g2-07",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Collective nouns",
    prompt: "Which word names a group of fish?",
    choices: ["school", "herd", "flock", "pack"],
    answer: 0,
    explanation: "A group of fish is a school. A flock is birds and a herd is cows.",
    quick: true,
  },
  {
    id: "ela-g2-08",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Adjectives",
    prompt: "Which word is an adjective in 'The fluffy cat slept on the rug'?",
    choices: ["fluffy", "cat", "slept", "rug"],
    answer: 0,
    explanation: "Fluffy describes the cat, so it is an adjective.",
    quick: true,
  },
  {
    id: "ela-g2-09",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Contractions",
    prompt: "What is the contraction for do not?",
    choices: ["don't", "dont'", "do'nt", "dont"],
    answer: 0,
    explanation: "The apostrophe takes the place of the missing o: do not becomes don't.",
    quick: true,
  },
  {
    id: "ela-g2-10",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Possessives",
    prompt: "Which shows that the ball belongs to Ben?",
    choices: ["Ben's ball", "Bens ball", "Bens' ball", "Ben ball"],
    answer: 0,
    explanation: "Add an apostrophe and s to show something belongs to one person: Ben's.",
    quick: true,
  },
  {
    id: "ela-g2-11",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Prefixes",
    prompt: "What does unhappy mean?",
    choices: ["not happy", "very happy", "happy again", "happy before"],
    answer: 0,
    explanation: "The prefix un- means not, so unhappy means not happy.",
    quick: true,
  },
  {
    id: "ela-g2-12",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Compound words",
    prompt: "Which is a compound word?",
    choices: ["sunflower", "flower", "sunny", "flowers"],
    answer: 0,
    explanation: "Sunflower is made of two words put together: sun + flower.",
    quick: true,
  },
  {
    id: "ela-g2-13",
    subject: "ela",
    grade: "2",
    standard: "L.2.5",
    skill: "Shades of meaning",
    prompt: "Which word is the strongest way to say hot?",
    choices: ["scorching", "warm", "cool", "mild"],
    answer: 0,
    explanation: "Scorching means very, very hot. Warm is only a little hot.",
    quick: true,
  },
  {
    id: "ela-g2-14",
    subject: "ela",
    grade: "2",
    standard: "RL.2.2",
    skill: "Lesson of a story",
    prompt: "The lesson a fable teaches is called the...",
    choices: ["moral", "setting", "title", "rhyme"],
    answer: 0,
    explanation: "The moral is the lesson the story wants you to learn.",
    quick: true,
  },
  {
    id: "ela-g2-15",
    subject: "ela",
    grade: "2",
    standard: "RI.2.5",
    skill: "Text features",
    prompt: "What helps you find the meaning of a bold word in a book?",
    choices: ["glossary", "cover", "title page", "author name"],
    answer: 0,
    explanation: "A glossary is a small dictionary in the back of a book.",
    quick: true,
  },
  {
    id: "ela-g2-16",
    subject: "ela",
    grade: "2",
    standard: "RI.2.6",
    skill: "Author's purpose",
    prompt: "A book about how bees make honey is mostly meant to...",
    choices: ["inform", "entertain", "persuade", "rhyme"],
    answer: 0,
    explanation: "Books that teach facts are written to inform the reader.",
    quick: true,
  },
  {
    id: "ela-g2-17",
    subject: "ela",
    grade: "2",
    standard: "RL.2.3",
    skill: "Character response",
    prompt: "How did Mia respond when she tripped?",
    passage: "Mia wanted to win the class race. She practiced running every day after school. On race day, she tripped at the start. Mia got up, brushed off her knees, and kept running. She came in third, and she was proud she did not quit.",
    choices: ["She got up and kept running.", "She cried and went home.", "She asked to start over.", "She stopped the race."],
    answer: 0,
    explanation: "The story says Mia got up, brushed off her knees, and kept running.",
  },
  {
    id: "ela-g2-18",
    subject: "ela",
    grade: "2",
    standard: "RI.2.2",
    skill: "Main topic",
    prompt: "What is the main topic of this text?",
    passage: "Octopuses are clever sea animals. They can change color to hide from enemies. They can squeeze through tiny holes because they have no bones. Some octopuses even carry shells to use as shelters.",
    choices: ["How octopuses are clever", "What octopuses eat", "How to catch fish", "Where sharks live"],
    answer: 0,
    explanation: "Every sentence tells a clever thing octopuses can do.",
  },
  {
    id: "ela-g2-19",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Vowel teams",
    prompt: "Which word has the same vowel sound as boat?",
    choices: ["snow", "cow", "shut", "cot"],
    answer: 0,
    explanation: "In snow, ow says the long o sound, just like oa in boat. In cow, ow says /ou/.",
    quick: true,
  },
  {
    id: "ela-g2-20",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Vowel teams",
    prompt: "Which word has the same vowel sound as moon?",
    choices: ["blue", "book", "mop", "moan"],
    answer: 0,
    explanation: "Blue and moon share the /oo/ sound. Book has a different oo sound.",
    quick: true,
  },
  {
    id: "ela-g2-21",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "R-controlled vowels",
    prompt: "Which word has the same vowel sound as car?",
    choices: ["star", "care", "cat", "core"],
    answer: 0,
    explanation: "Car and star both have the /ar/ sound.",
    quick: true,
  },
  {
    id: "ela-g2-22",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Two-syllable words",
    prompt: "Which word has two syllables and a long a sound?",
    choices: ["baby", "apple", "cat", "basket"],
    answer: 0,
    explanation: "Ba-by has two syllables, and the a says its name.",
    quick: true,
  },
  {
    id: "ela-g2-23",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Prefixes",
    prompt: "Which word means 'not safe'?",
    choices: ["unsafe", "safely", "saved", "safer"],
    answer: 0,
    explanation: "The prefix un- means not, so unsafe means not safe.",
    quick: true,
  },
  {
    id: "ela-g2-24",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Suffixes",
    prompt: "Which word means 'full of joy'?",
    choices: ["joyful", "joyless", "enjoyed", "joys"],
    answer: 0,
    explanation: "The suffix -ful means full of. Joyless means without joy.",
    quick: true,
  },
  {
    id: "ela-g2-25",
    subject: "ela",
    grade: "2",
    standard: "RF.2.4",
    skill: "Tricky spellings",
    prompt: "Which word has the same vowel sound as head?",
    choices: ["bed", "bead", "heat", "hide"],
    answer: 0,
    explanation: "In head, ea makes the short e sound, just like in bed.",
    quick: true,
  },
  {
    id: "ela-g2-26",
    subject: "ela",
    grade: "2",
    standard: "RF.2.5",
    skill: "Using context",
    prompt: "Which word makes sense? The bird built a ___ in the tree.",
    choices: ["nest", "net", "next", "neat"],
    answer: 0,
    explanation: "Birds build nests, so nest makes sense.",
    quick: true,
  },
  {
    id: "ela-g2-27",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular plurals",
    prompt: "What is the plural of foot?",
    choices: ["feet", "foots", "feets", "footes"],
    answer: 0,
    explanation: "Foot is irregular. One foot, two feet.",
    quick: true,
  },
  {
    id: "ela-g2-28",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Irregular verbs",
    prompt: "Today I see. Yesterday I ___.",
    choices: ["saw", "seed", "seen", "sawed"],
    answer: 0,
    explanation: "See is irregular. The past tense is saw.",
    quick: true,
  },
  {
    id: "ela-g2-29",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Reflexive pronouns",
    prompt: "He made the sandwich all by ___.",
    choices: ["himself", "hisself", "herself", "itself"],
    answer: 0,
    explanation: "Himself goes with he. Hisself is not a real word.",
    quick: true,
  },
  {
    id: "ela-g2-30",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Adverbs",
    prompt: "The turtle walked ___. Which word fits?",
    choices: ["slowly", "slow", "slowest", "slowness"],
    answer: 0,
    explanation: "Slowly is an adverb. It tells how the turtle walked.",
    quick: true,
  },
  {
    id: "ela-g2-31",
    subject: "ela",
    grade: "2",
    standard: "L.2.1",
    skill: "Conjunctions",
    prompt: "I wanted to play, ___ it was raining. Which word fits?",
    choices: ["but", "and", "so", "or"],
    answer: 0,
    explanation: "But joins two ideas that are different: I wanted to play, but it rained.",
    quick: true,
  },
  {
    id: "ela-g2-32",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Capitalizing holidays",
    prompt: "Which holiday is written correctly?",
    choices: ["New Year's Day", "new year's day", "New year's day", "new Year's day"],
    answer: 0,
    explanation: "Every important word in a holiday name starts with a capital letter.",
    quick: true,
  },
  {
    id: "ela-g2-33",
    subject: "ela",
    grade: "2",
    standard: "L.2.2",
    skill: "Capitalizing places",
    prompt: "Which place name is capitalized correctly?",
    choices: ["Lake Erie", "lake erie", "Lake erie", "lake Erie"],
    answer: 0,
    explanation: "Names of places, like Lake Erie, start each word with a capital letter.",
    quick: true,
  },
  {
    id: "ela-g2-34",
    subject: "ela",
    grade: "2",
    standard: "L.2.3",
    skill: "Formal and informal",
    prompt: "Which is the more formal way to greet a principal?",
    choices: ["Good morning.", "Hey there!", "Yo!", "What's up?"],
    answer: 0,
    explanation: "Good morning is polite and formal. The others are for friends.",
    quick: true,
  },
  {
    id: "ela-g2-35",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Compound words",
    prompt: "What does the compound word birdhouse mean?",
    choices: ["home for birds", "bird food", "a bird song", "a big house"],
    answer: 0,
    explanation: "Bird + house = a house, or home, for birds.",
    quick: true,
  },
  {
    id: "ela-g2-36",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Prefixes",
    prompt: "What does preheat mean?",
    choices: ["heat before", "heat again", "not heat", "heat a lot"],
    answer: 0,
    explanation: "The prefix pre- means before. You preheat an oven before you bake.",
    quick: true,
  },
  {
    id: "ela-g2-37",
    subject: "ela",
    grade: "2",
    standard: "L.2.4",
    skill: "Multiple-meaning words",
    prompt: "In 'Please ring the bell,' what does ring mean?",
    choices: ["make a sound", "jewelry", "a circle", "a boxing area"],
    answer: 0,
    explanation: "Ring can mean jewelry, but here it means to make the bell sound.",
    quick: true,
  },
  {
    id: "ela-g2-38",
    subject: "ela",
    grade: "2",
    standard: "L.2.5",
    skill: "Shades of meaning",
    prompt: "Which word means the very biggest?",
    choices: ["enormous", "big", "large", "tiny"],
    answer: 0,
    explanation: "Enormous means much bigger than just big or large.",
    quick: true,
  },
  {
    id: "ela-g2-39",
    subject: "ela",
    grade: "2",
    standard: "L.2.5",
    skill: "Shades of meaning",
    prompt: "Which word means to throw gently?",
    choices: ["toss", "hurl", "fling", "slam"],
    answer: 0,
    explanation: "To toss is to throw softly. Hurl and fling mean to throw hard.",
    quick: true,
  },
  {
    id: "ela-g2-40",
    subject: "ela",
    grade: "2",
    standard: "RL.2.5",
    skill: "Story structure",
    prompt: "The part of a story where the problem gets solved is usually the...",
    choices: ["ending", "beginning", "title", "setting"],
    answer: 0,
    explanation: "Stories often solve the problem near the end.",
    quick: true,
  },
  {
    id: "ela-g2-41",
    subject: "ela",
    grade: "2",
    standard: "RL.2.1",
    skill: "Asking why",
    prompt: "Why did Jada bake cookies?",
    passage: "Jada's kite got stuck in a tall tree. Her neighbor, Mr. Ortiz, brought a long ladder and climbed up to get it. Jada baked him cookies to say thank you.",
    choices: ["to thank Mr. Ortiz", "to sell them", "for her birthday", "to feed the birds"],
    answer: 0,
    explanation: "Jada baked cookies to say thank you for getting her kite.",
  },
  {
    id: "ela-g2-42",
    subject: "ela",
    grade: "2",
    standard: "RL.2.2",
    skill: "Lesson",
    prompt: "What is the lesson of this story?",
    passage: "A squirrel spent all fall playing while his sister gathered nuts. When snow came, he had nothing to eat. His sister shared, and the next fall he gathered nuts too.",
    choices: ["Plan ahead for later.", "Snow is cold.", "Squirrels like to play.", "Never share food."],
    answer: 0,
    explanation: "The squirrel had no food because he did not plan ahead. The next year he did.",
  },
  {
    id: "ela-g2-43",
    subject: "ela",
    grade: "2",
    standard: "RL.2.3",
    skill: "Responding to challenges",
    prompt: "How did Omar respond to feeling nervous?",
    passage: "On the day of the spelling bee, Omar's throat felt tight. He took three deep breaths, remembered how hard he had practiced, and stepped up to the microphone.",
    choices: ["He calmed down and tried.", "He ran home.", "He refused to spell.", "He laughed at others."],
    answer: 0,
    explanation: "Omar took deep breaths, remembered his practice, and stepped up anyway.",
  },
  {
    id: "ela-g2-44",
    subject: "ela",
    grade: "2",
    standard: "RL.2.6",
    skill: "Points of view",
    prompt: "How do Duck and Cat feel differently about rain?",
    passage: "'I love rainy days!' said Duck, splashing in a puddle. 'Not me,' grumbled Cat from under the porch. 'Rain ruins everything.'",
    choices: ["Duck likes it; Cat does not.", "Both love rain.", "Both hate rain.", "Cat likes it; Duck does not."],
    answer: 0,
    explanation: "Duck splashes and says 'I love rainy days!' Cat grumbles that rain ruins everything.",
  },
  {
    id: "ela-g2-45",
    subject: "ela",
    grade: "2",
    standard: "RI.2.3",
    skill: "Order of events",
    prompt: "What happens right after the caterpillar makes a chrysalis?",
    passage: "When a caterpillar is fully grown, it makes a hard case called a chrysalis. Inside, its body changes. After about two weeks, a butterfly comes out.",
    choices: ["Its body changes inside.", "A butterfly lays eggs.", "It eats leaves.", "It flies away."],
    answer: 0,
    explanation: "The text says that inside the chrysalis, the caterpillar's body changes.",
  },
  {
    id: "ela-g2-46",
    subject: "ela",
    grade: "2",
    standard: "RI.2.8",
    skill: "Author's reasons",
    prompt: "Which is a reason the author gives?",
    passage: "Our class should plant a garden. A garden would teach us how food grows. It would also give birds and bees a place to visit.",
    choices: ["A garden teaches how food grows.", "Gardens are easy.", "Bees are scary.", "Our class is too big."],
    answer: 0,
    explanation: "The author says a garden would teach us how food grows.",
  },
  {
    id: "ela-g2-47",
    subject: "ela",
    grade: "2",
    standard: "RI.2.4",
    skill: "Word meaning",
    prompt: "What does hibernate mean?",
    passage: "Some animals hibernate in winter. They find a safe den and sleep deeply until spring, living on fat stored in their bodies.",
    choices: ["sleep through winter", "hunt for food", "build a nest", "fly south"],
    answer: 0,
    explanation: "The text says the animals sleep deeply until spring.",
  },
  {
    id: "ela-g2-48",
    subject: "ela",
    grade: "2",
    standard: "RL.2.4",
    skill: "Rhythm and sound",
    prompt: "Which words in the first line copy the sound of rain?",
    passage: "Pitter, patter, on the pane,\nTap, tap, tapping goes the rain.",
    choices: ["pitter, patter", "on the pane", "goes the", "the rain"],
    answer: 0,
    explanation: "Pitter and patter sound like raindrops tapping on a window.",
  },
];

export default questions;
