import type { Question } from "../../types";

// Grade 8 ELA — NC Standard Course of Study for ELA (2017). L.8.1 (verbals, active/passive voice, verb mood), L.8.4 roots, L.8.5 (verbal irony, puns, connotation), RL.8.2, RL.8.5, RL.8.6, RI.8.6, RI.8.8, W.8.1
const questions: Question[] = [
  {
    id: "ela-g8-01",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "In 'Swimming is fun,' the word swimming is a...",
    choices: ["gerund", "participle", "infinitive", "adverb"],
    answer: 0,
    explanation: "A gerund is an -ing verb used as a noun. Here swimming is the subject.",
    quick: true,
  },
  {
    id: "ela-g8-02",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "Which phrase is an infinitive?",
    choices: ["to explore", "exploring", "explored", "explores"],
    answer: 0,
    explanation: "An infinitive is to + the base form of a verb: to explore.",
    quick: true,
  },
  {
    id: "ela-g8-03",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verbals",
    prompt: "In 'The broken vase lay on the floor,' broken is a...",
    choices: ["participle", "gerund", "infinitive", "noun"],
    answer: 0,
    explanation: "A participle is a verb form used as an adjective. Broken describes the vase.",
    quick: true,
  },
  {
    id: "ela-g8-04",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Active and passive voice",
    prompt: "Which verb phrase is in the passive voice?",
    choices: ["was thrown", "threw", "is throwing", "will throw"],
    answer: 0,
    explanation: "Passive voice uses a form of be + past participle, so the subject receives the action.",
    quick: true,
  },
  {
    id: "ela-g8-05",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verb mood",
    prompt: "'If I were you, I would study.' The verb were is in which mood?",
    choices: ["subjunctive", "indicative", "imperative", "interrogative"],
    answer: 0,
    explanation: "The subjunctive mood expresses wishes or situations contrary to fact.",
    quick: true,
  },
  {
    id: "ela-g8-06",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Verb mood",
    prompt: "'Close the door, please.' Which mood is this?",
    choices: ["imperative", "indicative", "subjunctive", "conditional"],
    answer: 0,
    explanation: "The imperative mood gives commands or requests.",
    quick: true,
  },
  {
    id: "ela-g8-07",
    subject: "ela",
    grade: "8",
    standard: "L.8.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root phon (as in symphony) means...",
    choices: ["sound", "light", "love", "fear"],
    answer: 0,
    explanation: "Phon means sound, as in telephone, phonics, and symphony.",
    quick: true,
  },
  {
    id: "ela-g8-08",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Verbal irony",
    prompt: "Saying 'What lovely weather!' during a storm is...",
    choices: ["verbal irony", "a simile", "hyperbole", "a pun"],
    answer: 0,
    explanation: "Verbal irony is saying the opposite of what you mean.",
    quick: true,
  },
  {
    id: "ela-g8-09",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Puns",
    prompt: "'I used to be a banker, but I lost interest.' This is a...",
    choices: ["pun", "simile", "metaphor", "paradox"],
    answer: 0,
    explanation: "A pun plays on two meanings of a word: interest as money and as attention.",
    quick: true,
  },
  {
    id: "ela-g8-10",
    subject: "ela",
    grade: "8",
    standard: "RL.8.6",
    skill: "Dramatic irony",
    prompt: "When the audience knows something a character doesn't, it is...",
    choices: ["dramatic irony", "verbal irony", "a flashback", "foreshadowing"],
    answer: 0,
    explanation: "Dramatic irony creates suspense or humor because readers know more than the characters.",
    quick: true,
  },
  {
    id: "ela-g8-11",
    subject: "ela",
    grade: "8",
    standard: "RL.8.5",
    skill: "Text structure",
    prompt: "A scene that jumps back to an earlier time is a...",
    choices: ["flashback", "foreshadowing", "climax", "resolution"],
    answer: 0,
    explanation: "A flashback interrupts the plot to show something from the past.",
    quick: true,
  },
  {
    id: "ela-g8-12",
    subject: "ela",
    grade: "8",
    standard: "W.8.1",
    skill: "Argument writing",
    prompt: "Evidence in an argument should be relevant and...",
    choices: ["credible", "emotional", "lengthy", "funny"],
    answer: 0,
    explanation: "Strong evidence is relevant to the claim and comes from credible, trustworthy sources.",
    quick: true,
  },
  {
    id: "ela-g8-13",
    subject: "ela",
    grade: "8",
    standard: "L.8.5",
    skill: "Connotation",
    prompt: "Which word has the most negative connotation?",
    choices: ["scheme", "plan", "strategy", "idea"],
    answer: 0,
    explanation: "Scheme suggests a sneaky or dishonest plan.",
    quick: true,
  },
  {
    id: "ela-g8-14",
    subject: "ela",
    grade: "8",
    standard: "L.8.1",
    skill: "Active and passive voice",
    prompt: "Which sentence is written in the active voice?",
    choices: ["The chef prepared the meal.", "The meal was prepared by the chef.", "The meal was being prepared.", "The meal had been prepared by noon."],
    answer: 0,
    explanation: "In active voice, the subject (the chef) does the action.",
  },
  {
    id: "ela-g8-15",
    subject: "ela",
    grade: "8",
    standard: "RL.8.2",
    skill: "Theme",
    prompt: "Which theme best fits this passage?",
    passage: "For months, Dev told everyone he had built the robot himself, though his older sister had done most of the wiring. At the science fair, a judge asked him to explain the circuit. Dev stared at the wires, his face burning, and finally said, 'Actually, my sister should answer that.'",
    choices: ["Taking credit you didn't earn can backfire.", "Science fairs are unfair.", "Older siblings are smarter.", "Robots are hard to build."],
    answer: 0,
    explanation: "Dev's embarrassment when he can't explain the circuit shows the cost of taking false credit.",
  },
  {
    id: "ela-g8-16",
    subject: "ela",
    grade: "8",
    standard: "RI.8.8",
    skill: "Relevant evidence",
    prompt: "Which sentence is irrelevant to the author's claim?",
    passage: "Our city should add bike lanes downtown. Cities with protected lanes have seen traffic injuries drop. Bike lanes also reduce car emissions. My uncle rides a very expensive bike. More people bike to work when lanes feel safe.",
    choices: ["My uncle rides a very expensive bike.", "Protected lanes cut traffic injuries.", "Bike lanes reduce car emissions.", "More people bike when lanes feel safe."],
    answer: 0,
    explanation: "The uncle's expensive bike says nothing about whether the city needs bike lanes.",
  },
  {
    id: "ela-g8-17",
    subject: "ela",
    grade: "8",
    standard: "RL.8.6",
    skill: "Dramatic irony",
    prompt: "What effect does the reader's knowledge create?",
    passage: "The detective smiled at the butler and thanked him for the tea. He lifted the cup to his lips. Readers already know, from Chapter 2, that the butler stirred sleeping powder into the pot.",
    choices: ["suspense, since readers see a danger he can't", "humor, since the butler is clumsy", "sadness, since the detective leaves", "confusion about the setting"],
    answer: 0,
    explanation: "Because readers know about the sleeping powder and the detective doesn't, dramatic irony builds suspense.",
  },
  {
    id: "ela-g8-18",
    subject: "ela",
    grade: "8",
    standard: "RI.8.6",
    skill: "Conflicting viewpoints",
    prompt: "How does the author respond to the opposing view?",
    passage: "Some argue that video games waste time. However, research shows certain games improve problem-solving and hand-eye coordination. While moderation matters, dismissing all games ignores their real benefits.",
    choices: ["Acknowledges it, then counters with research", "Ignores it completely", "Agrees with it fully", "Insults people who hold it"],
    answer: 0,
    explanation: "The author admits some people disagree, then uses research to answer them.",
  },
];

export default questions;
