import type { Question } from "../../types";

// Grade 5 ELA — NC Standard Course of Study for ELA (2017). L.5.1, L.5.2, L.5.4 (roots, affixes, context), L.5.5 (personification, hyperbole, adages, homographs), RL.5.2, RL.5.4, RL.5.6, RI.5.5, RI.5.8
const questions: Question[] = [
  {
    id: "ela-g5-01",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root aud (as in audience) means...",
    choices: ["hear", "see", "speak", "walk"],
    answer: 0,
    explanation: "Aud means hear. An audience is a group that listens.",
    quick: true,
  },
  {
    id: "ela-g5-02",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root bio (as in biology) means...",
    choices: ["life", "earth", "water", "book"],
    answer: 0,
    explanation: "Bio means life. Biology is the study of living things.",
    quick: true,
  },
  {
    id: "ela-g5-03",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Prefixes",
    prompt: "The prefix mis- in misspell means...",
    choices: ["wrongly", "again", "before", "not yet"],
    answer: 0,
    explanation: "Mis- means wrongly or badly, so misspell means spell wrongly.",
    quick: true,
  },
  {
    id: "ela-g5-04",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Personification",
    prompt: "'The wind whispered through the trees.' What is given a human action?",
    choices: ["the wind", "the trees", "a person", "a whisper"],
    answer: 0,
    explanation: "Only people whisper. Giving the wind a human action is personification.",
    quick: true,
  },
  {
    id: "ela-g5-05",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Hyperbole",
    prompt: "'I've told you a million times!' This is an example of...",
    choices: ["hyperbole", "simile", "alliteration", "onomatopoeia"],
    answer: 0,
    explanation: "Hyperbole is a big exaggeration used for effect.",
    quick: true,
  },
  {
    id: "ela-g5-06",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Adages and proverbs",
    prompt: "What does 'Don't count your chickens before they hatch' mean?",
    choices: ["Don't assume", "Count slowly", "Raise chickens", "Eat breakfast"],
    answer: 0,
    explanation: "This proverb warns not to count on something good before it actually happens.",
    quick: true,
  },
  {
    id: "ela-g5-07",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Homographs",
    prompt: "In 'The bat flew out of the cave,' what is a bat?",
    choices: ["an animal", "a club", "a wink", "a game"],
    answer: 0,
    explanation: "Bat is a homograph. Flying out of a cave tells us it is the animal.",
    quick: true,
  },
  {
    id: "ela-g5-08",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Interjections",
    prompt: "Which word is an interjection?",
    choices: ["Wow", "quickly", "table", "because"],
    answer: 0,
    explanation: "An interjection shows sudden feeling, like Wow! or Oops!",
    quick: true,
  },
  {
    id: "ela-g5-09",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Correlative conjunctions",
    prompt: "___ Sam ___ Kim will go. Which pair fits?",
    choices: ["Either / or", "Neither / or", "Both / or", "Not / nor"],
    answer: 0,
    explanation: "Correlative conjunctions come in pairs: either/or, neither/nor, both/and.",
    quick: true,
  },
  {
    id: "ela-g5-10",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Perfect verb tenses",
    prompt: "Which verb is in the present perfect tense?",
    choices: ["has eaten", "ate", "will eat", "is eating"],
    answer: 0,
    explanation: "Present perfect uses has or have plus a past participle: has eaten.",
    quick: true,
  },
  {
    id: "ela-g5-11",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Verb tense shifts",
    prompt: "She opened the box and ___ a puppy. Which verb fits?",
    choices: ["found", "finds", "will find", "is finding"],
    answer: 0,
    explanation: "Opened is past tense, so found keeps the tense the same.",
    quick: true,
  },
  {
    id: "ela-g5-12",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Commas",
    prompt: "Which sentence uses a comma correctly?",
    choices: ["Yes, I can go.", "Yes I, can go.", "Yes I can, go.", "Yes I can go,"],
    answer: 0,
    explanation: "Use a comma after yes or no at the start of a sentence.",
    quick: true,
  },
  {
    id: "ela-g5-13",
    subject: "ela",
    grade: "5",
    standard: "RL.5.6",
    skill: "Narrator's point of view",
    prompt: "A narrator who knows every character's thoughts is...",
    choices: ["omniscient", "limited", "first person", "a character"],
    answer: 0,
    explanation: "An omniscient narrator is all-knowing and can share every character's thoughts.",
    quick: true,
  },
  {
    id: "ela-g5-14",
    subject: "ela",
    grade: "5",
    standard: "RI.5.5",
    skill: "Text structure",
    prompt: "A text on how frogs and toads are alike and different uses...",
    choices: ["comparison", "chronology", "cause/effect", "description"],
    answer: 0,
    explanation: "Telling how things are alike and different is compare-and-contrast structure.",
    quick: true,
  },
  {
    id: "ela-g5-15",
    subject: "ela",
    grade: "5",
    standard: "RL.5.2",
    skill: "Theme",
    prompt: "What is the theme of this story?",
    passage: "Every morning, Ms. Park's garden had fewer tomatoes. Her neighbor Leon admitted he had been taking them for his little sisters because his family could not afford groceries. Instead of scolding him, Ms. Park handed him a basket. 'From now on,' she said, 'just ask, and we'll pick them together.'",
    choices: ["Kindness can turn a wrong into friendship.", "Stealing is always punished.", "Gardens are hard work.", "Tomatoes grow best in summer."],
    answer: 0,
    explanation: "Ms. Park answers Leon's mistake with kindness, which points to the theme.",
  },
  {
    id: "ela-g5-16",
    subject: "ela",
    grade: "5",
    standard: "RL.5.4",
    skill: "Figurative language",
    prompt: "What does 'The classroom was a beehive' suggest?",
    passage: "The classroom was a beehive the morning of the field trip. Kids buzzed from desk to desk, and even Mr. Ortiz couldn't stop smiling.",
    choices: ["It was busy and full of activity.", "Bees were in the room.", "The room was very quiet.", "Kids were afraid of stings."],
    answer: 0,
    explanation: "The metaphor compares busy kids to buzzing bees. The next sentence, with kids buzzing around, supports it.",
  },
  {
    id: "ela-g5-17",
    subject: "ela",
    grade: "5",
    standard: "RI.5.8",
    skill: "Reasons and evidence",
    prompt: "Which evidence best supports that a skate park is safer?",
    passage: "Our town should build a skate park. Right now, skaters use the library steps, which damages them and blocks visitors. A skate park would give kids a safe place to exercise. Nearby towns that built parks saw fewer skating injuries.",
    choices: ["Nearby towns saw fewer injuries.", "Skaters use the library steps.", "Kids like to exercise.", "The town has a library."],
    answer: 0,
    explanation: "Fewer injuries in towns with parks is evidence that directly supports the safety reason.",
  },
  {
    id: "ela-g5-18",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Context clues",
    prompt: "What does parched most likely mean?",
    passage: "After hiking all day in the hot sun without enough water, the campers were parched. They gulped down every drop at the stream.",
    choices: ["very thirsty", "very cold", "lost", "excited"],
    answer: 0,
    explanation: "Hiking in the sun without water and gulping every drop are clues that parched means very thirsty.",
  },
];

export default questions;
