/*
 * 12x12 picture-clue icons as character grids (pure data, so the tests can check every clue has
 * one). Special ids: "person:<job>" (a helper in uniform), "say:<WORD>" (a speech bubble with a
 * sound word) and "arrow:<N|E|S|W>" (a compass arrow).
 */

export const PAL: Record<string, string> = {
  K: "#05060f",
  W: "#ffffff",
  R: "#e3262f",
  r: "#8a1218",
  Y: "#ffd23f",
  O: "#ff8a2a",
  B: "#2456e8",
  b: "#6ea0ff",
  G: "#3cb043",
  g: "#1f6b2a",
  N: "#8a5a2b",
  n: "#d8a060",
  P: "#ff9ac8",
  S: "#f0c090",
  s: "#a8aec0",
  D: "#555a6a",
  C: "#7ff3ff",
  V: "#8a4ad8",
  E: "#2a2f45",
};

export const ICONS: Record<string, string[]> = {
  volcano: [
    ".....RO.....",
    "....O.RO....",
    ".....RR.....",
    "....NRRN....",
    "...NNORNN...",
    "...NNNRNN...",
    "..NNNNNNNN..",
    "..NNNNNNNNN.",
    ".NNNNnNNNNN.",
    ".NNnNNNNnNNN",
    "NNNNNNNNNNNN",
    "gggggggggggg",
  ],
  oil: [
    ".....K......",
    "....KDK.....",
    "....K.K.....",
    "...KD.DK....",
    "...K...K....",
    "..KDKKKDK...",
    "..K.....K...",
    ".KD.....DK..",
    ".K.......K..",
    "KKKKKKKKKKK.",
    "N..KKKKK...N",
    "NNNNNNNNNNNN",
  ],
  // ---- town things ----
  bus: [
    "............",
    ".YYYYYYYYYY.",
    ".YbbYbbYbbY.",
    ".YbbYbbYbbY.",
    ".YYYYYYYYYY.",
    ".YKKKKKKKKY.",
    ".YYYYYYYYYY.",
    ".YYYYYYYYYY.",
    "..KK....KK..",
    "..KK....KK..",
    "............",
    "............",
  ],
  book: [
    "............",
    ".RRRRRRRRR..",
    ".RWWWWWWWWR.",
    ".RWKKKKKKWR.",
    ".RWWWWWWWWR.",
    ".RWKKKKKWWR.",
    ".RWWWWWWWWR.",
    ".RWKKKKKKWR.",
    ".RWWWWWWWWR.",
    ".RRRRRRRRRR.",
    "..rrrrrrrrr.",
    "............",
  ],
  firetruck: [
    "............",
    "....ssssss..",
    "...s....s...",
    ".RRRRRRRbbR.",
    ".RRRRRRRbbR.",
    ".RWWRRRRRRR.",
    ".RRRRRRRRRR.",
    ".RYYRRRRYYR.",
    "..KK....KK..",
    "..KK....KK..",
    "............",
    "............",
  ],
  slide: [
    "............",
    ".B..........",
    ".BB.........",
    ".BYY........",
    ".B.YY.......",
    ".BB.YY......",
    ".B...YY.....",
    ".BB...YY....",
    ".B.....YY...",
    ".B......YYY.",
    ".GGGGGGGGGG.",
    "............",
  ],
  bread: [
    "............",
    "............",
    "...nnnnnn...",
    "..nNnNnNnn..",
    ".nnnnnnnnnn.",
    ".nNNNNNNNNn.",
    ".nNNNNNNNNn.",
    ".nNNNNNNNNn.",
    ".nnnnnnnnnn.",
    "............",
    "............",
    "............",
  ],
  letter: [
    "............",
    "............",
    ".WWWWWWWWWW.",
    ".WKWWWWWWKW.",
    ".WWKWWWWKWW.",
    ".WWWKWWKWRW.",
    ".WWWWKKWWWW.",
    ".WWWWWWWWWW.",
    ".WWWWWWWWWW.",
    ".WWWWWWWWWW.",
    "............",
    "............",
  ],
  cart: [
    "............",
    "KK..........",
    ".K..........",
    ".KsssssssK..",
    ".KsRsGsYsK..",
    ".KsssssssK..",
    "..KsssssK...",
    "..KKKKKKK...",
    "...K...K....",
    "..KK..KK....",
    "............",
    "............",
  ],
  tractor: [
    "............",
    "......KKK...",
    "......K.K...",
    "...GGGGGG...",
    "...GGGGGG...",
    ".GGGGGGGGG..",
    ".GGGGGGGGG..",
    ".KKK...KKKK.",
    "KKYKK.KKYYKK",
    ".KKK..KKYYKK",
    "......KKKKK.",
    "............",
  ],
  policecar: [
    "............",
    ".....bR.....",
    "...BBBBBB...",
    "..BbbBbbBB..",
    ".BBBBBBBBBB.",
    ".BWWWWWWWWB.",
    ".BBBBBBBBBB.",
    "..KK....KK..",
    "..KK....KK..",
    "............",
    "............",
    "............",
  ],
  bandage: [
    "............",
    "............",
    "..........P.",
    "........PPP.",
    "......PPnPP.",
    "....PPnnnP..",
    "..PPnnnPP...",
    ".PPnnPP.....",
    ".PPPP.......",
    "..P.........",
    "............",
    "............",
  ],
  // ---- borrowed items ----
  bell: [
    ".....YY.....",
    "....YYYY....",
    "...YYYYYY...",
    "...YYWYYY...",
    "..YYWYYYYY..",
    "..YYYYYYYY..",
    "..YYYYYYYY..",
    ".YYYYYYYYYY.",
    "YYYYYYYYYYYY",
    ".....KK.....",
    "............",
    "............",
  ],
  cake: [
    ".....R......",
    ".....Y......",
    ".....W......",
    "..PPPPPPPP..",
    "..PWPWPWPP..",
    "..nnnnnnnn..",
    ".PPPPPPPPPP.",
    ".PWPWPWPWPP.",
    ".nnnnnnnnnn.",
    ".nnnnnnnnnn.",
    "ssssssssssss",
    "............",
  ],
  kite: [
    ".....R......",
    "....RRR.....",
    "...RRYRR....",
    "..RRRYRRR...",
    ".RYYYYYYYR..",
    "..RRRYRRR...",
    "...RRYRR....",
    "....RRR.....",
    ".....K......",
    "......K.Y...",
    ".......K.B..",
    "........K...",
  ],
  pumpkin: [
    ".....g......",
    ".....gg.....",
    "..OOOOOOOO..",
    ".OOrOOOrOOO.",
    "OOOrOOOrOOOO",
    "OOOrOOOrOOOO",
    "OOOrOOOrOOOO",
    "OOOrOOOrOOOO",
    ".OOrOOOrOOO.",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
  teddy: [
    ".NN......NN.",
    "NnNN....NNnN",
    ".NNNNNNNNNN.",
    "..NNNNNNNN..",
    "..NKNNNNKN..",
    "..NNNnnNNN..",
    "...NNKKNN...",
    "..NNNNNNNN..",
    ".NNnnnnnnNN.",
    ".NNnnnnnnNN.",
    "..NN....NN..",
    "............",
  ],
  mailbag: [
    "............",
    "...NNNNNN...",
    "..N......N..",
    ".N........N.",
    ".BBBBBBBBBB.",
    ".BBBBBBBBBB.",
    ".BBWWWWWWBB.",
    ".BBWBBBBWBB.",
    ".BBWWWWWWBB.",
    ".BBBBBBBBBB.",
    "............",
    "............",
  ],
  recipe: [
    "............",
    "..WWWWWWWW..",
    "..WRRRRRRW..",
    "..WWWWWWWW..",
    "..WKKKKWWW..",
    "..WWWWWWWW..",
    "..WKKKKKKW..",
    "..WWWWWWWW..",
    "..WKKKWnnW..",
    "..WWWWnnnW..",
    "..WWWWWWWW..",
    "............",
  ],
  globe: [
    "....bbbb....",
    "...bWbbbb...",
    "..bWbbbbbb..",
    "..bbWbbbbb..",
    "..bbbbbbbb..",
    "...bbbbbb...",
    "....bbbb....",
    ".....NN.....",
    "...NNNNNN...",
    "..NNNNNNNN..",
    "............",
    "............",
  ],
  hat: [
    ".....Y......",
    ".....P......",
    "....PPP.....",
    "....PYP.....",
    "...PPPPP....",
    "...PYPYP....",
    "..PPPPPPP...",
    "..PYPPPYP...",
    ".PPPPPPPPP..",
    "YYYYYYYYYYY.",
    "............",
    "............",
  ],
  lamp: [
    "............",
    "....KKKK....",
    "...KYYYYK...",
    "..KYYWYYYK..",
    "..KYWYYYYK..",
    "..KYYYYYYK..",
    "...KYYYYK...",
    "....KYYK....",
    "....ssss....",
    "...ssssss...",
    "............",
    "............",
  ],
  star: [
    ".....YY.....",
    ".....YY.....",
    "....YYYY....",
    "YYYYYYYYYYYY",
    ".YYYYYYYYYY.",
    "..YYYYYYYY..",
    "...YYYYYY...",
    "..YYYYYYYY..",
    "..YYY..YYY..",
    ".YY......YY.",
    "............",
    "............",
  ],
  flag: [
    ".K..........",
    ".KBBBRRRRRR.",
    ".KBWBRRRRRR.",
    ".KBBBWWWWWW.",
    ".KBBBWWWWWW.",
    ".KBBBRRRRRR.",
    ".KBBBRRRRRR.",
    ".K..........",
    ".K..........",
    ".K..........",
    ".K..........",
    "NNN.........",
  ],
  gnome: [
    ".....R......",
    "....RRR.....",
    "....RRR.....",
    "...RRRRR....",
    "...SSKSS....",
    "...SSSSS....",
    "..WWWWWWW...",
    "..WWWWWWW...",
    "...BBBBB....",
    "...BBBBB....",
    "..ss...ss...",
    "............",
  ],
  map: [
    "............",
    ".nnnNnnnNnn.",
    ".nGGNnbbNnn.",
    ".nGGNbbbNGn.",
    ".nnnNbbnNGn.",
    ".nRnNnnnNnn.",
    ".nnnNnGGNnn.",
    ".nnnNnGGNnn.",
    ".nnnNnnnNnn.",
    "............",
    "............",
    "............",
  ],
  apple: [
    ".....N......",
    ".....N.GG...",
    "....NGGG....",
    "..RRRRRRRR..",
    ".RRWRRRRRRR.",
    ".RWRRRRRRRR.",
    ".RRRRRRRRRR.",
    ".RRRRRRRRRR.",
    "..RRRRRRRR..",
    "...RR..RR...",
    "............",
    "............",
  ],
  plank: [
    "............",
    "............",
    "............",
    "NNNNNNNNNNNN",
    "nnnnNnnnnnnn",
    "nnnnnnnnNnnn",
    "nKnnnnnnnnKn",
    "NNNNNNNNNNNN",
    "............",
    "............",
    "............",
    "............",
  ],
  spyglass: [
    "............",
    "..........K.",
    ".........KYK",
    "........KYYK",
    ".......YYYK.",
    "......YYYK..",
    ".....NNNK...",
    "....NNNK....",
    "...NNNK.....",
    "..NNNK......",
    ".NNK........",
    "............",
  ],
  plant: [
    "............",
    "..G.....G...",
    ".GrG...GrG..",
    ".GrG...GrG..",
    "..GG.G.GG...",
    "....GGG.....",
    ".....G......",
    "..NNNNNNN...",
    "..NNNNNNN...",
    "...NNNNN....",
    "...NNNNN....",
    "............",
  ],
  nugget: [
    "............",
    "............",
    "....YYYY....",
    "..YYWYYYO...",
    ".YYWYYYYYO..",
    ".YYYYYYYYYO.",
    "YYYYYOYYYYO.",
    ".YYYYYYYYO..",
    "..OOYYYOO...",
    "....OOO.....",
    "............",
    "............",
  ],
  torch: [
    ".....Y......",
    "....YOY.....",
    "....YORY....",
    "...YORRY....",
    "....YYY.....",
    "...GGGGG....",
    "....GGG.....",
    "....GGG.....",
    "....GGG.....",
    "....GGG.....",
    "....GGG.....",
    "............",
  ],
  trumpet: [
    "............",
    "............",
    "..........YY",
    ".........YYY",
    "YYYYYYYYYYYY",
    "Y..YYY...YYY",
    "YYYYYYYYYYYY",
    "...Y.Y.Y.YYY",
    "..........YY",
    "............",
    "............",
    "............",
  ],
  compass: [
    "....ssss....",
    "..ssWWWWss..",
    ".sWWWRWWWWs.",
    ".sWWWRWWWWs.",
    "sWWWRRRWWWWs",
    "sWWWWKWWWWWs",
    "sWWWWBWWWWWs",
    ".sWWWBWWWWs.",
    ".sWWWBWWWWs.",
    "..ssWWWWss..",
    "....ssss....",
    "............",
  ],
  bolt: [
    "............",
    "...YYYYYY...",
    "...YKYYKY...",
    "...YYYYYY...",
    ".....YY.....",
    ".....YO.....",
    ".....YY.....",
    ".....YO.....",
    ".....YY.....",
    ".....YO.....",
    ".....YY.....",
    "............",
  ],
  sail: [
    ".....K......",
    ".....KW.....",
    ".....KWW....",
    ".....KWWW...",
    ".....KWWWW..",
    ".....KWWWWW.",
    ".....KWWWWW.",
    ".....K......",
    ".NNNNNNNNNN.",
    "..NNNNNNNN..",
    "..bbbbbbbb..",
    "............",
  ],
  // ---- world & map pictures ----
  land: [
    "bbbbbbbbbbbb",
    "bbbGGGbbbbbb",
    "bbGGGGGGbbbb",
    "bGGGgGGGGbbb",
    "bGGGGGGGGGbb",
    "bbGGGGGgGGbb",
    "bbbGGGGGGGbb",
    "bbbbGGGGGbbb",
    "bbbbbGGGbbbb",
    "bbbbbbGbbbbb",
    "bbbbbbbbbbbb",
    "bbbbbbbbbbbb",
  ],
  wave: [
    "............",
    "............",
    "..bb....bb..",
    ".bWbb..bWbb.",
    "bb..bbbb..bb",
    "BBBBBBBBBBBB",
    "BBbbBBBBbbBB",
    "BBBBBBBBBBBB",
    "BBBBbbBBBBBB",
    "BBBBBBBBBBBB",
    "............",
    "............",
  ],
  beach: [
    "...YY.......",
    "..YYYY......",
    "...YY.......",
    "............",
    "........G...",
    ".......GGG..",
    "........N...",
    "bbbbbb..N...",
    "BBbbbbbnNnn.",
    "BBBBbbnnnnnn",
    "BBBBBnnnnnnn",
    "............",
  ],
  between: [
    "............",
    "GGG......GG.",
    "GGGG....GGG.",
    "GGG.bbbb.GG.",
    "GG.bbbbbb...",
    "GG.bbbbbb.GG",
    "G..bbbbbb.GG",
    "....bbbb....",
    "............",
    "............",
    "............",
    "............",
  ],
  ring: [
    "...bbbbbb...",
    ".bbbbbbbbbb.",
    "bbbWWWWWWbbb",
    "bbWWWWWWWWbb",
    "bbWWWWWWWWbb",
    "bbWWWWWWWWbb",
    "bbbWWWWWWbbb",
    ".bbbbbbbbbb.",
    "...bbbbbb...",
    "............",
    "............",
    "............",
  ],
  home: [
    ".....RR.....",
    "....RRRR....",
    "...RRRRRR...",
    "..RRRRRRRR..",
    ".RRRRRRRRRR.",
    "..nnnnnnnn..",
    "..nbbnnbbn..",
    "..nbbnnbbn..",
    "..nnnNNnnn..",
    "..nnnNNnnn..",
    "GGGGGGGGGGGG",
    "............",
  ],
  river: [
    "GGGGGGGGGGGG",
    "GGGbbGGGGGGG",
    "GGGGbbGGGGGG",
    "GGGGbbbGGGGG",
    "GGGGGbbbGGGG",
    "GGGGGGbbbGGG",
    "GGGGGbbbGGGG",
    "GGGGbbbGGGGG",
    "GGGbbbGGGGGG",
    "GGbbbGGGGGGG",
    "GbbbGGGGGGGG",
    "GGGGGGGGGGGG",
  ],
  bison: [
    "............",
    ".NN.........",
    "NNNN.NNN....",
    "NKNNNNNNNNN.",
    "NNNNNNNNNNNN",
    ".NNNNnnnnnnN",
    "..NNnnnnnnnn",
    "...nnnnnnnnn",
    "...n.n...n.n",
    "...n.n...n.n",
    "............",
    "............",
  ],
  llama: [
    "..WW........",
    "..WWW.......",
    "..WKW.......",
    "..WWW.......",
    "..WWW.......",
    "..WWW.......",
    "..WWWWWWWW..",
    "..WWWWWWWWW.",
    "...WWWWWWW..",
    "...W.W..W.W.",
    "...W.W..W.W.",
    "............",
  ],
  eiffel: [
    ".....K......",
    ".....K......",
    "....KDK.....",
    "....KDK.....",
    "...KDDDK....",
    "...KDKDK....",
    "..KKKKKKK...",
    "..KD...DK...",
    ".KD.....DK..",
    "KKKKKKKKKKK.",
    "KD.......DK.",
    "............",
  ],
  pyramid: [
    "............",
    ".....Y......",
    "....YYn.....",
    "...YYYnn....",
    "...YYYnn....",
    "..YYYYnnn...",
    ".YYYYYnnnn..",
    ".YYYYYnnnn..",
    "YYYYYYnnnnn.",
    "nnnnnnnnnnnn",
    "............",
    "............",
  ],
  desert: [
    "..YYY.......",
    ".YYYYY......",
    "..YYY.......",
    "............",
    "........G...",
    "........G.G.",
    "......G.GGG.",
    "......GGG...",
    "....nnnnGnn.",
    "..nnnnnnnnnn",
    "nnnnnnnnnnnn",
    "............",
  ],
  panda: [
    ".KK......KK.",
    "KKKWWWWWWKKK",
    ".KWWWWWWWWK.",
    ".WKKWWWWKKW.",
    ".WKWWWWWWKW.",
    ".WWWWKKWWWW.",
    "..WWWWWWWW..",
    ".KKWWWWWWKK.",
    "KKKWWWWWWKKK",
    ".KKWWWWWWKK.",
    "..KK....KK..",
    "............",
  ],
  wall: [
    "............",
    "........s.s.",
    "......s.sss.",
    "....s.sssss.",
    "..s.sssssDs.",
    "s.sssssDsss.",
    "sssssDsss...",
    "sssDsss.....",
    "sDsss.....GG",
    "sss.....GGGG",
    "GGGGGGGGGGGG",
    "............",
  ],
  kangaroo: [
    "...NN.......",
    "..NNN.......",
    ".NKNN.......",
    "NNNNN.......",
    "..NNNN......",
    "..NNNNN.....",
    "..NNnNNN....",
    "...NnNNN....",
    "...NNNNNN...",
    "....NN..NNN.",
    "...NNN....NN",
    "............",
  ],
  penguin: [
    "....KKKK....",
    "...KKKKKK...",
    "...KWKKWK...",
    "...KKOOKK...",
    "..KKWWWWKK..",
    ".KKWWWWWWKK.",
    ".KKWWWWWWKK.",
    "..KWWWWWWK..",
    "..KWWWWWWK..",
    "...KWWWWK...",
    "...OO..OO...",
    "............",
  ],
  polarbear: [
    "............",
    ".WW.........",
    "WWWW........",
    "WKWWWWWWWWW.",
    "WWWWWWWWWWWW",
    "KWWWWWWWWWWW",
    ".WWWWWWWWWWW",
    "..WW.WW.WW.W",
    "..WW.WW.WW.W",
    "bbbbbbbbbbbb",
    "............",
    "............",
  ],
  snow: [
    ".....W......",
    "..W..W..W...",
    "...W.W.W....",
    "....WWW.....",
    "WWWWWCWWWWW.",
    "....WWW.....",
    "...W.W.W....",
    "..W..W..W...",
    ".....W......",
    "............",
    "............",
    "............",
  ],
  storm: [
    "...ssss.....",
    ".ssssssss...",
    "sssDsssssss.",
    "ssssssDssss.",
    ".sssssssss..",
    "....YY......",
    "...YY..b....",
    "..YYYY...b..",
    "....YY.b....",
    "...YY....b..",
    "..Y...b.....",
    "............",
  ],
  island: [
    "............",
    "............",
    "........G...",
    ".......GGG..",
    "........N...",
    "bbbbbbbbNbbb",
    "bbbnnnnnnnnb",
    "bbbbbbbbbbbb",
    "BBBBBBBBBBBB",
    "BBbbBBBBbbBB",
    "BBBBBBBBBBBB",
    "............",
  ],
  mountain: [
    "............",
    ".....W......",
    "....WWs.....",
    "...WsWss....",
    "...ssssD....",
    "..sssssDD...",
    "..ssssDDD.s.",
    ".sssssDDDsss",
    ".ssssDDDDsss",
    "sssssDDDDDss",
    "GGGGGGGGGGGG",
    "............",
  ],
  city: [
    "......bb....",
    "......bb....",
    "...BB.bbb...",
    "...BBbbbb...",
    "...BBbYbb.BB",
    ".BBBBbbbb.BB",
    ".BYBBbYbbBBB",
    ".BBBBbbbbBYB",
    ".BYBBbbbbBBB",
    ".BBBBbYbbBBB",
    "DDDDDDDDDDDD",
    "............",
  ],
  ship: [
    "............",
    ".....R......",
    ".....RR.....",
    "...sssss....",
    "...sWsWs....",
    ".RRRRRRRRRR.",
    ".RRRRRRRRRR.",
    "..rrrrrrrr..",
    "bbbbbbbbbbbb",
    "BBbbBBBBbbBB",
    "............",
    "............",
  ],
  plane: [
    "............",
    "............",
    "..nnnnnnnn..",
    "...K....K...",
    "...K.KK.K...",
    "..nnnnnnnn..",
    ".....KK.....",
    "............",
    "............",
    "............",
    "............",
    "............",
  ],
  lighthouse: [
    "....YYY.....",
    "...KKKKK....",
    "....WWW.....",
    "....KKK.....",
    "....WWW.....",
    "...KKKKK....",
    "...WWWWW....",
    "...KKKKK....",
    "..WWWWWWW...",
    "..KKKKKKK...",
    "nnnnnnnnnnnn",
    "............",
  ],
  tree: [
    ".....g......",
    "....ggg.....",
    "...gGggg....",
    "....ggg.....",
    "...gggGg....",
    "..ggGgggg...",
    "...ggggg....",
    "..ggggGggg..",
    ".gggggggggg.",
    ".....N......",
    ".....N......",
    "............",
  ],
  // ---- landmark marks (drawn big in scenes) ----
  mansion: [
    "............",
    ".s..ssss..s.",
    ".s.ssssss.s.",
    "ssssssssssss",
    "sbsbsbsbsbss",
    "ssssssssssss",
    "sbsbsNNsbsbs",
    "ssssNNNNssss",
    "ssssNNNNssss",
    "GGGGGGGGGGGG",
    "............",
    "............",
  ],
  bridge: [
    "............",
    "K..........K",
    "KK........KK",
    "K.K......K.K",
    "K..KK..KK..K",
    "K....KK....K",
    "NNNNNNNNNNNN",
    "K..........K",
    "K..........K",
    "............",
    "............",
    "............",
  ],
  spire: [
    "............",
    "....ss......",
    "...sssD.....",
    "...ssDD.....",
    "...ssDD.....",
    "...sssD.....",
    "...ssDD.....",
    "..sssDDD....",
    "..sssDDD....",
    ".ssssDDDD...",
    "GGGGGGGGGGGG",
    "............",
  ],
  museum: [
    ".....nn.....",
    "...nnnnnn...",
    ".nnnnnnnnnn.",
    "nnnnnnnnnnnn",
    ".n.n.n.n.n..",
    ".n.n.n.n.n..",
    ".n.n.n.n.n..",
    ".n.n.n.n.n..",
    "nnnnnnnnnnnn",
    "nnnnnnnnnnnn",
    "............",
    "............",
  ],
  gem: [
    "............",
    "...GGGGGG...",
    "..GGWGGGGG..",
    ".GGWGGGGGGg.",
    ".GGGGGGGGgg.",
    "..GGGGGGgg..",
    "...GGGGgg...",
    "....GGgg....",
    ".....Gg.....",
    "............",
    "............",
    "............",
  ],
  gold: [
    "............",
    "............",
    "....YYYY....",
    "..YYWYYYO...",
    ".YYWYYYYYO..",
    ".YYYYYYYYYO.",
    "YYYYYOYYYYO.",
    ".YYYYYYYYO..",
    "..OOYYYOO...",
    "....OOO.....",
    "............",
    "............",
  ],
  counter: [
    "............",
    "RRRRRRRRRRRR",
    "WWWWWWWWWWWW",
    "............",
    "..sss..sss..",
    "..sRs..sRs..",
    "...s....s...",
    "nnnnnnnnnnnn",
    "nNNNNNNNNNNn",
    "nNNNNNNNNNNn",
    "............",
    "............",
  ],
  dome: [
    ".....YY.....",
    "....ssss....",
    "...ssssss...",
    "..ssssssss..",
    "..ssssssss..",
    ".ssssssssss.",
    ".s.s.s.s.s..",
    ".s.s.s.s.s..",
    ".s.s.s.s.s..",
    "ssssssssssss",
    "............",
    "............",
  ],
  boat: [
    "............",
    ".....K......",
    ".....KW.....",
    ".....KWW....",
    ".....KWWW...",
    ".....KWWWW..",
    ".....K......",
    ".NNNNNNNNN..",
    "..NNNNNNN...",
    "bbbbbbbbbbbb",
    "............",
    "............",
  ],
  pirate: [
    "............",
    "...KKKKKK...",
    "..KKKKKKKK..",
    ".KKKKWKKKKK.",
    "KKKKWWWKKKKK",
    "KKKKKWKKKKKK",
    "KKKKKKKKKKKK",
    ".KKKKKKKKKK.",
    "............",
    "............",
    "............",
    "............",
  ],
  needle: [
    ".....K......",
    ".....s......",
    "...sssss....",
    "..sssssss...",
    "...sssss....",
    ".....s......",
    "....s.s.....",
    "....s.s.....",
    "...s...s....",
    "...s...s....",
    "..s.....s...",
    "............",
  ],
  gate: [
    "............",
    ".R........R.",
    ".R........R.",
    "RRR......RRR",
    ".RRR....RRR.",
    ".R..RRRR..R.",
    "RRRRRRRRRRRR",
    ".R........R.",
    ".R........R.",
    "bbbbbbbbbbbb",
    "............",
    "............",
  ],
  cactus: [
    ".....G......",
    "....GGG.....",
    "....GGG.....",
    ".G..GGG.....",
    ".G..GGG..G..",
    ".GGGGGG..G..",
    "....GGGGGG..",
    "....GGG.....",
    "....GGG.....",
    "....GGG.....",
    "nnnnnnnnnnnn",
    "............",
  ],
  bat: [
    "............",
    "............",
    "K....KK....K",
    "KK..KKKK..KK",
    "KKKKKKKKKKKK",
    ".KKKKRRKKKK.",
    "..KK.KK.KK..",
    "...K....K...",
    "............",
    "............",
    "............",
    "............",
  ],
  faces: [
    "............",
    "..ssssssss..",
    ".ssKsKsKsKs.",
    ".ssssssssss.",
    ".ssDsDsDsDs.",
    ".ssssssssss.",
    "sssssssssss.",
    "ssssssssssss",
    "ssssssssssss",
    "GGGGGGGGGGGG",
    "............",
    "............",
  ],
  arch: [
    "....ssss....",
    "...s....s...",
    "..s......s..",
    "..s......s..",
    ".s........s.",
    ".s........s.",
    ".s........s.",
    "s..........s",
    "s..........s",
    "GGGGGGGGGGGG",
    "............",
    "............",
  ],
  horn: [
    "............",
    "..........YY",
    ".........YYY",
    "YYYYYYYYYYYY",
    "Y..YYY...YYY",
    "YYYYYYYYYYYY",
    "...Y.Y.Y.YYY",
    "..........YY",
    "............",
    "............",
    "............",
    "............",
  ],
  guitar: [
    "...........K",
    "..........K.",
    ".........N..",
    "........N...",
    "..OOO..N....",
    ".OOOOON.....",
    "OOOKOOOO....",
    "OOOOOOOO....",
    ".OOOOOOO....",
    "..OOOOO.....",
    "............",
    "............",
  ],
  gator: [
    "............",
    "............",
    "............",
    "..g.g.g.....",
    "GGGGGGGGGG..",
    "GKGGGGGGGGGG",
    "WGWGGGGGGGGG",
    "GGGG.GG.GG..",
    "bbbbbbbbbbbb",
    "............",
    "............",
    "............",
  ],
  liberty: [
    "..Y.........",
    "..O.........",
    "..G..GGG....",
    "..G.GGGGG...",
    "..GGGGGG....",
    "....GGGG....",
    "....GGGG....",
    "...GGGGGG...",
    "...GGGGGG...",
    "..ssssssss..",
    "..ssssssss..",
    "............",
  ],
  geyser: [
    ".....W......",
    "....WbW.....",
    "...WbbbW....",
    "....bbb.....",
    "....WbW.....",
    ".....b......",
    ".....W......",
    "....WbW.....",
    "..nnnbnnn...",
    ".nnnnnnnnn..",
    "............",
    "............",
  ],
  whale: [
    "............",
    "....b.b.....",
    ".....b......",
    "...BBBBBB...",
    ".BBBBBBBBBB.",
    "BBKBBBBBBBBB",
    "BWWWWWWWBBBB",
    ".WWWWWWBB.BB",
    "...........B",
    "bbbbbbbbbbbb",
    "............",
    "............",
  ],
  bigben: [
    ".....Y......",
    "....nnn.....",
    "....nnn.....",
    "...nWWWn....",
    "...nWKWn....",
    "...nWWWn....",
    "...nnnnn....",
    "...nNnNn....",
    "...nnnnn....",
    "...nNnNn....",
    "..nnnnnnn...",
    "............",
  ],
  fuji: [
    "............",
    "............",
    ".....WW.....",
    "....WWWW....",
    "...WWbbWW...",
    "...bbbbbb...",
    "..bbbbbbbb..",
    ".bbbbbbbbbb.",
    "bbbbbbbbbbbb",
    "GGGGGGGGGGGG",
    "............",
    "............",
  ],
  opera: [
    "............",
    "...W........",
    "...WW...W...",
    "..WWW..WW...",
    "..WWWW.WWW..",
    ".WWWWWWWWWW.",
    ".WWWWWWWWWWW",
    "nnnnnnnnnnnn",
    "bbbbbbbbbbbb",
    "............",
    "............",
    "............",
  ],
};

/** Uniform colors for "person:<job>" icons: hat, shirt, extra detail. */
export const JOBS: Record<string, { hat: string | null; shirt: string; prop: string }> = {
  teacher: { hat: null, shirt: "G", prop: "apple" },
  librarian: { hat: null, shirt: "V", prop: "book" },
  firefighter: { hat: "R", shirt: "Y", prop: "hose" },
  parkworker: { hat: "g", shirt: "G", prop: "rake" },
  baker: { hat: "W", shirt: "W", prop: "bread" },
  mail: { hat: "B", shirt: "b", prop: "bag" },
  cashier: { hat: null, shirt: "R", prop: "none" },
  farmer: { hat: "n", shirt: "B", prop: "none" },
  police: { hat: "B", shirt: "B", prop: "badge" },
  doctor: { hat: null, shirt: "W", prop: "scope" },
};

const PERSON = [
  "....hhhh....",
  "...hhhhhh...",
  "....SSSS....",
  "....SKSK....",
  "....SSSS....",
  "...cccccc...",
  "..cccccccc..",
  "..cSccccSc..",
  "....cccc....",
  "....EEEE....",
  "....E..E....",
  "...EE..EE...",
];

/**
 * Pixel flags, described by a spec so near-miss flags (Italy / Mexico / Ireland) stay distinct:
 *  "flag:v:GWR"      vertical stripes        "flag:h:KRY"     horizontal stripes
 *  "flag:v:GWR:N"    stripes + a centre emblem color
 *  "flag:disc:WR"    field + centre disc     "flag:diamond:GYB" field + diamond + centre disc
 *  "flag:star:RY"    field + a star in the top-left corner
 * Letters are PAL colors. The flag is 10x9 inside a black frame.
 */
export function flagGrid(spec: string): string[] | null {
  const [kind, cols, emblem] = spec.split(":");
  if (!cols || ![...cols].every((c) => c in PAL) || (emblem && !(emblem in PAL))) return null;
  if (!["v", "h", "disc", "diamond", "star"].includes(kind)) return null;
  const rows: string[] = [];
  for (let y = 0; y < 12; y++) {
    let row = "";
    for (let x = 0; x < 12; x++) {
      if (y < 1 || y > 11 || x > 11) {
        row += ".";
        continue;
      }
      if (y === 1 || y === 11 || x === 0 || x === 11) {
        row += "K";
        continue;
      }
      const ix = x - 1; // 0..9
      const iy = y - 2; // 0..8
      const dx = ix - 4.5;
      const dy = iy - 4;
      let c: string;
      if (kind === "v") c = cols[Math.floor((ix * cols.length) / 10)];
      else if (kind === "h") c = cols[Math.floor((iy * cols.length) / 9)];
      else if (kind === "disc") c = dx * dx + dy * dy <= 6.5 ? cols[1] : cols[0];
      else if (kind === "diamond") c = dx * dx + dy * dy <= 2.5 && cols[2] ? cols[2] : Math.abs(dx) / 4.6 + Math.abs(dy) / 3.6 <= 1 ? cols[1] : cols[0];
      else c = (ix === 2 && iy >= 1 && iy <= 3) || (iy === 2 && ix >= 1 && ix <= 3) ? cols[1] : cols[0];
      if (emblem && Math.abs(dx) <= 1 && Math.abs(dy) <= 1) c = emblem;
      row += c;
    }
    rows.push(row);
  }
  return rows;
}

/** Rows + colors for any icon id (including the special person/say/arrow ids). Null if unknown. */
export function iconGrid(id: string): { rows: string[]; colors: Record<string, string> } | null {
  if (id.startsWith("flag:")) {
    const rows = flagGrid(id.slice(5));
    return rows ? { rows, colors: PAL } : null;
  }
  if (id.startsWith("person:")) {
    const job = JOBS[id.slice(7)];
    if (!job) return null;
    const rows = PERSON.map((r) => r.replace(/h/g, job.hat ? "h" : "N"));
    const colors = { ...PAL, h: PAL[job.hat ?? "N"], c: PAL[job.shirt] };
    return { rows, colors };
  }
  if (id.startsWith("say:") || id.startsWith("arrow:")) return null; // drawn by the renderer
  const rows = ICONS[id];
  return rows ? { rows, colors: PAL } : null;
}

/** True when an icon id can be drawn. */
export function iconExists(id: string): boolean {
  if (id.startsWith("say:")) return id.length > 4 && id.length <= 12;
  if (id.startsWith("arrow:")) return ["N", "E", "S", "W"].includes(id.slice(6));
  return iconGrid(id) !== null;
}
