import type { Question } from "../../types";
// Grade 1 science — NC Standard Course of Study for Science (2023). Pushes and pulls, with and without contact, and
// how the size of a force changes motion (PS.1.1); the day and night sky and the moon's changing shape (ESS.1.1);
// properties of Earth materials and soils (ESS.1.2); needs of plants and animals, plant parts, and how needs are met in
// different environments (LS.1.1); animal needs and shelter (LS.1.2).
const questions: Question[] = [
  {
    id: "sci-g1-01",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "What makes a wagon start to move?",
    choices: ["A push or pull", "Nothing", "A sound", "Its color"],
    answer: 0,
    explanation: "Things start moving when something pushes or pulls them. A wagon will not move by itself.",
    quick: true,
  },
  {
    id: "sci-g1-02",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Gravity",
    prompt: "What pulls things down to the ground?",
    choices: ["Gravity", "Wind", "Light", "Sound"],
    answer: 0,
    explanation: "Gravity is a pull that brings things down toward the ground. That is why a dropped apple falls.",
    quick: true,
  },
  {
    id: "sci-g1-03",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "A ball rolls slowest on which ground?",
    choices: ["Thick grass", "Smooth floor", "Ice", "A slide"],
    answer: 0,
    explanation: "Thick grass rubs against the ball and slows it down. Smooth things like ice let it roll easily.",
    quick: true,
  },
  {
    id: "sci-g1-04",
    subject: "science",
    grade: "1",
    standard: "PS.1.1",
    skill: "Pushes and pulls",
    prompt: "Which push makes a toy car go the farthest?",
    choices: ["A strong push", "A soft push", "A tiny tap", "No push"],
    answer: 0,
    explanation: "A strong push gives the car more motion, so it goes farther than after a soft push.",
    quick: true,
  },
  {
    id: "sci-g1-05",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "What do we see in the sky in the daytime?",
    choices: ["The sun", "Many stars", "A dark sky", "Fireflies"],
    answer: 0,
    explanation: "In the daytime we see the sun. At night the sky is dark and we can see the moon and stars.",
    quick: true,
  },
  {
    id: "sci-g1-06",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Where does the sun seem to come up in the morning?",
    choices: ["East", "West", "North", "South"],
    answer: 0,
    explanation: "The sun seems to rise in the east and set in the west. It looks like it moves across the sky.",
    quick: true,
  },
  {
    id: "sci-g1-07",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Why can't we see stars in the day?",
    choices: ["Sun too bright", "They go away", "They fall down", "They turn off"],
    answer: 0,
    explanation: "The stars are still there in the day. The sun is so bright that we cannot see them.",
    quick: true,
  },
  {
    id: "sci-g1-08",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1",
    skill: "Day and night sky",
    prompt: "Over a month, the moon's shape seems to...",
    choices: ["Change", "Stay the same", "Turn square", "Turn red"],
    answer: 0,
    explanation: "The moon looks like it changes shape. Sometimes it is a thin sliver and sometimes it is full and round.",
    quick: true,
  },
  {
    id: "sci-g1-09",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Which Earth material can you pour?",
    choices: ["Water", "A boulder", "A mountain", "A big rock"],
    answer: 0,
    explanation: "Water is a liquid, so you can pour it. Rocks and boulders are solid and keep their shape.",
    quick: true,
  },
  {
    id: "sci-g1-10",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Most plants grow best in which Earth material?",
    choices: ["Soil", "Bare rock", "Plastic", "Pavement"],
    answer: 0,
    explanation: "Soil holds water and has bits of old plants that help new plants grow.",
    quick: true,
  },
  {
    id: "sci-g1-11",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Tiny pieces of broken rock are called...",
    choices: ["Sand", "Water", "Air", "Clouds"],
    answer: 0,
    explanation: "Sand is made of tiny bits of rock. Over a long time, big rocks break into smaller pieces.",
    quick: true,
  },
  {
    id: "sci-g1-12",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "How can we sort a pile of rocks?",
    choices: ["By size, color", "By their smell", "By their names", "By their mood"],
    answer: 0,
    explanation: "We can sort rocks by what we see and feel, like size, color and how rough or smooth they are.",
    quick: true,
  },
  {
    id: "sci-g1-13",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "What plants need",
    prompt: "What do plants need to grow?",
    choices: ["Sunlight", "Candy", "Darkness", "Toys"],
    answer: 0,
    explanation: "Plants need sunlight, water and air to grow. They use sunlight to make their own food.",
    quick: true,
  },
  {
    id: "sci-g1-14",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "Plant parts",
    prompt: "Which part of a plant takes in water?",
    choices: ["Roots", "Flower", "Fruit", "Seed"],
    answer: 0,
    explanation: "Roots grow in the soil and soak up water for the plant. They also hold the plant in place.",
    quick: true,
  },
  {
    id: "sci-g1-15",
    subject: "science",
    grade: "1",
    standard: "LS.1.1",
    skill: "Plants and animals help each other",
    prompt: "How do bees help flowers?",
    choices: ["Carry pollen", "Eat leaves", "Dig roots", "Break stems"],
    answer: 0,
    explanation: "Bees carry pollen from flower to flower. This helps the plants make seeds.",
    quick: true,
  },
  {
    id: "sci-g1-16",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "Where does a fish live?",
    choices: ["Water", "A tree", "Desert sand", "A nest"],
    answer: 0,
    explanation: "Fish live in water. They use gills to get air from the water.",
    quick: true,
  },
  {
    id: "sci-g1-17",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "What do many birds use to build nests?",
    choices: ["Twigs, grass", "Glass", "Metal", "Ice cubes"],
    answer: 0,
    explanation: "Birds gather twigs, grass and leaves from around them to build nests.",
    quick: true,
  },
  {
    id: "sci-g1-18",
    subject: "science",
    grade: "1",
    standard: "LS.1.2",
    skill: "Animal needs and homes",
    prompt: "Why does a rabbit need a hiding place?",
    choices: ["To stay safe", "To get taller", "To turn green", "To eat rocks"],
    answer: 0,
    explanation: "Animals need shelter to stay safe from danger and bad weather.",
    quick: true,
  },
  {
    id: "sci-g1-19",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Which plant part holds the plant up tall?",
    choices: ["Stem", "Root", "Petal", "Seed"],
    answer: 0,
    explanation: "The stem holds the plant up so its leaves can reach the light.",
    quick: true,
  },
  {
    id: "sci-g1-20",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Which part of a plant makes food from sunlight?",
    choices: ["Leaf", "Root", "Seed", "Flower"],
    answer: 0,
    explanation: "Leaves use sunlight, air and water to make food for the plant.",
    quick: true,
  },
  {
    id: "sci-g1-21",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Which plant part makes seeds?",
    choices: ["Flower", "Root", "Stem", "Leaf"],
    answer: 0,
    explanation: "Flowers make seeds. The seeds can grow into new plants.",
    quick: true,
  },
  {
    id: "sci-g1-22",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "A new plant can grow from a...",
    choices: ["Seed", "Pebble", "Raindrop", "Shadow"],
    answer: 0,
    explanation: "A seed has a tiny plant inside. With water and warmth, it grows into a new plant.",
    quick: true,
  },
  {
    id: "sci-g1-23",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Which part keeps a plant from blowing away?",
    choices: ["Roots", "Petals", "Leaves", "Flowers"],
    answer: 0,
    explanation: "Roots grow down into the soil and hold the plant in place.",
    quick: true,
  },
  {
    id: "sci-g1-24",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "An apple is the part of the plant that holds the...",
    choices: ["Seeds", "Roots", "Soil", "Bees"],
    answer: 0,
    explanation: "A fruit, like an apple, holds and protects the plant's seeds.",
    quick: true,
  },
  {
    id: "sci-g1-25",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Water moves up from the roots through the...",
    choices: ["Stem", "Petals", "Fruit", "Air"],
    answer: 0,
    explanation: "The stem works like a straw. It carries water from the roots up to the leaves.",
    quick: true,
  },
  {
    id: "sci-g1-26",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    prompt: "Which plant part grows under the soil?",
    choices: ["Roots", "Flower", "Leaves", "Fruit"],
    answer: 0,
    explanation: "Roots grow under the ground. Flowers, leaves and most fruits grow above it.",
    quick: true,
  },
  {
    id: "sci-g1-27",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant needs",
    prompt: "A plant kept in a dark closet will...",
    choices: ["Get weak", "Grow better", "Turn blue", "Grow fruit"],
    answer: 0,
    explanation: "Plants need light to make food. Without light, a plant turns pale and weak.",
    quick: true,
  },
  {
    id: "sci-g1-28",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Animal needs",
    prompt: "All animals need food, water, air and...",
    choices: ["Shelter", "Toys", "Money", "Shoes"],
    answer: 0,
    explanation: "Animals need food, water, air and a safe place to live, called shelter.",
    quick: true,
  },
  {
    id: "sci-g1-29",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.2",
    skill: "Needs in different places",
    prompt: "A cactus lives in the dry desert. Its thick stem stores...",
    choices: ["Water", "Snow", "Sand", "Rocks"],
    answer: 0,
    explanation: "A cactus stores water in its thick stem, so it can live where it rarely rains.",
    quick: true,
  },
  {
    id: "sci-g1-30",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.2",
    skill: "Needs in different places",
    prompt: "Where can a frog find the water it needs?",
    choices: ["A pond", "A desert", "A cave", "A rock"],
    answer: 0,
    explanation: "Frogs live near ponds and streams, where there is plenty of water.",
    quick: true,
  },
  {
    id: "sci-g1-31",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.2",
    skill: "Needs in different places",
    prompt: "In winter, how do squirrels get food?",
    choices: ["Stored nuts", "Fresh fruit", "Snow", "Flowers"],
    answer: 0,
    explanation: "Squirrels bury nuts in the fall. In winter, when food is hard to find, they dig them up.",
    quick: true,
  },
  {
    id: "sci-g1-32",
    subject: "science",
    grade: "1",
    standard: "PS.1.1.1",
    skill: "Pushes and pulls",
    prompt: "Does a magnet have to touch a paper clip to pull it?",
    choices: ["No", "Yes, always", "Only if wet", "Only at night"],
    answer: 0,
    explanation: "A magnet can pull a paper clip from a little way off, without touching it.",
    quick: true,
  },
  {
    id: "sci-g1-33",
    subject: "science",
    grade: "1",
    standard: "PS.1.1.2",
    skill: "Size of a force",
    prompt: "Which takes a bigger push to move?",
    choices: ["Full wagon", "Empty wagon", "A feather", "A paper cup"],
    answer: 0,
    explanation: "Heavier things need a bigger push to start moving. A full wagon is heavy.",
    quick: true,
  },
  {
    id: "sci-g1-34",
    subject: "science",
    grade: "1",
    standard: "PS.1.1.2",
    skill: "Size of a force",
    prompt: "You push a swing softly, then hard. The hard push makes it go...",
    choices: ["Higher", "Lower", "Not at all", "Backward"],
    answer: 0,
    explanation: "A bigger push gives the swing more motion, so it swings higher.",
    quick: true,
  },
  {
    id: "sci-g1-35",
    subject: "science",
    grade: "1",
    standard: "PS.1.1.1",
    skill: "Pushes and pulls",
    prompt: "A rolling ball hits a wall and stops. What stopped it?",
    choices: ["The wall", "The air", "The sun", "Its color"],
    answer: 0,
    explanation: "The wall pushed back on the ball. That push changed its motion and stopped it.",
    quick: true,
  },
  {
    id: "sci-g1-36",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.1",
    skill: "Day and night sky",
    prompt: "Which can you see in the sky at night?",
    choices: ["Stars", "The sun", "Rainbows", "Blue sky"],
    answer: 0,
    explanation: "At night the sky is dark, so we can see stars. The sun is up in the daytime.",
    quick: true,
  },
  {
    id: "sci-g1-37",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.1",
    skill: "Day and night sky",
    prompt: "In the evening, the sun seems to go down in the...",
    choices: ["West", "East", "North", "South"],
    answer: 0,
    explanation: "The sun seems to rise in the east and set in the west.",
    quick: true,
  },
  {
    id: "sci-g1-38",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.1",
    skill: "Day and night sky",
    prompt: "Can you sometimes see the moon in the daytime?",
    choices: ["Yes", "No, never", "Only in winter", "Only in July"],
    answer: 0,
    explanation: "Yes. The moon is often in the sky during the day, too.",
    quick: true,
  },
  {
    id: "sci-g1-39",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.2",
    skill: "Moon patterns",
    prompt: "When the moon looks like a whole circle, it is a...",
    choices: ["Full moon", "New moon", "Half moon", "Crescent"],
    answer: 0,
    explanation: "A full moon looks like a bright, round circle.",
    quick: true,
  },
  {
    id: "sci-g1-40",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.2",
    skill: "Moon patterns",
    prompt: "Where does moonlight really come from?",
    choices: ["The sun", "The moon", "Stars", "Streetlights"],
    answer: 0,
    explanation: "The moon does not make its own light. It shines because sunlight bounces off it.",
    quick: true,
  },
  {
    id: "sci-g1-41",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.2",
    skill: "Soil",
    prompt: "Worms help soil by digging...",
    choices: ["Air tunnels", "Rocks", "Plastic", "Snow"],
    answer: 0,
    explanation: "Worm tunnels let air and water into the soil, which helps roots grow.",
    quick: true,
  },
  {
    id: "sci-g1-42",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.2",
    skill: "Soil",
    prompt: "Water drains through which soil the fastest?",
    choices: ["Sand", "Clay", "Mud", "Silt"],
    answer: 0,
    explanation: "Sand has big grains with big spaces between them, so water runs through it fast.",
    quick: true,
  },
  {
    id: "sci-g1-43",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.1",
    skill: "Earth materials",
    prompt: "Which one is a mineral we put on food?",
    choices: ["Salt", "Sugar", "Pepper", "Flour"],
    answer: 0,
    explanation: "Salt is a mineral that comes from the Earth. Sugar, pepper and flour come from plants.",
    quick: true,
  },
  {
    id: "sci-g1-44",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant needs",
    passage:
      "Ava planted two bean seeds. She gave Plant A water and sunlight. She gave Plant B sunlight but no water.",
    prompt: "What will most likely happen to Plant B?",
    choices: [
      "It will wilt and dry up",
      "It will grow taller than Plant A",
      "It will make more flowers",
      "It will turn back into a seed",
    ],
    answer: 0,
    explanation: "Plants need water to live and grow. Without water, Plant B will wilt and dry up.",
  },
  {
    id: "sci-g1-45",
    subject: "science",
    grade: "1",
    standard: "ESS.1.1.2",
    skill: "Moon patterns",
    passage:
      "Jay drew the moon each night. Night 1: a thin crescent. Night 4: a half moon. Night 8: almost full.",
    prompt: "What will the moon look like a few nights later?",
    choices: ["Full and round", "A thin crescent", "Gone for good", "Square"],
    answer: 0,
    explanation: "Each night Jay saw more of the moon lit up. The pattern keeps going until the moon is full.",
  },
  {
    id: "sci-g1-46",
    subject: "science",
    grade: "1",
    standard: "PS.1.1.2",
    skill: "Size of a force",
    passage:
      "Mia and Leo push a box from opposite sides. They push with the same strength.",
    prompt: "What happens to the box?",
    choices: ["It does not move", "It slides toward Mia", "It slides toward Leo", "It jumps up"],
    answer: 0,
    explanation: "The two pushes are the same size and go opposite ways, so they cancel out. The box stays still.",
  },
  {
    id: "sci-g1-47",
    subject: "science",
    grade: "1",
    standard: "ESS.1.2.2",
    skill: "Soil",
    passage:
      "Kim poured one cup of water on sandy soil and one cup on clay soil. Much more water dripped out of the sandy soil.",
    prompt: "Which soil kept more of the water?",
    choices: ["Clay soil", "Sandy soil", "They kept the same", "Neither kept any"],
    answer: 0,
    explanation: "Less water dripped out of the clay soil, so the clay held on to more water.",
  },
  {
    id: "sci-g1-48",
    subject: "science",
    grade: "1",
    standard: "LS.1.1.1",
    skill: "Plant parts",
    passage:
      "Lucy put a white flower in a cup of water with blue food coloring. The next day, the edges of the petals were blue.",
    prompt: "How did the blue water get to the petals?",
    choices: [
      "It moved up the stem",
      "It soaked in through the petals",
      "It fell from the air",
      "The flower made blue paint",
    ],
    answer: 0,
    explanation: "The stem carries water up from the bottom of the plant to the flower. The blue color rode along with the water.",
  },
];
export default questions;
