import type { Question } from "../../types";
// Grade 10 science — NC Standard Course of Study for Science (2023), Biology (LS.Bio). Macromolecules, enzymes,
// organelles, prokaryotes vs. eukaryotes, and protein synthesis (LS.Bio.1); cell division, differentiation and cancer
// (LS.Bio.2); homeostasis and membrane transport, photosynthesis, and cellular respiration (LS.Bio.3); energy flow and
// cycling of matter (LS.Bio.4); populations, carrying capacity and human impact (LS.Bio.5); meiosis and genetic
// variation (LS.Bio.6); inheritance patterns (LS.Bio.7); DNA analysis and biotechnology (LS.Bio.8); natural selection
// and evidence for evolution (LS.Bio.9).
const questions: Question[] = [
  {
    id: "sci-g10-01",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.3",
    skill: "Organelles",
    prompt: "Which organelle produces most of a cell's ATP?",
    choices: ["Mitochondrion", "Ribosome", "Golgi body", "Nucleus"],
    answer: 0,
    explanation: "Mitochondria carry out aerobic cellular respiration, releasing energy from glucose as ATP.",
    quick: true,
  },
  {
    id: "sci-g10-02",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.3",
    skill: "Organelles",
    prompt: "Proteins are assembled from amino acids at the...",
    choices: ["Ribosome", "Lysosome", "Vacuole", "Cell wall"],
    answer: 0,
    explanation: "Ribosomes read mRNA and link amino acids into proteins. Lysosomes break molecules down.",
    quick: true,
  },
  {
    id: "sci-g10-03",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.4",
    skill: "Prokaryotes and eukaryotes",
    prompt: "Which cells lack a nucleus and membrane-bound organelles?",
    choices: ["Prokaryotes", "Plant cells", "Animal cells", "Fungal cells"],
    answer: 0,
    explanation: "Prokaryotes (bacteria and archaea) keep their DNA in the cytoplasm. Plant, animal and fungal cells are eukaryotic.",
    quick: true,
  },
  {
    id: "sci-g10-04",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.3",
    skill: "Plant and animal cells",
    prompt: "Plant cells have which structure that animal cells lack?",
    choices: ["Cell wall", "Ribosomes", "Cell membrane", "Mitochondria"],
    answer: 0,
    explanation: "Plant cells have cell walls and chloroplasts. Both plant and animal cells have ribosomes, membranes and mitochondria.",
    quick: true,
  },
  {
    id: "sci-g10-05",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.1",
    skill: "Cell transport",
    prompt: "A red blood cell placed in very salty water shrinks. Water left it by...",
    choices: ["Osmosis", "Endocytosis", "Mitosis", "Translation"],
    answer: 0,
    explanation: "Osmosis is water diffusing across a membrane toward the side with more dissolved solute, here the salty outside.",
    quick: true,
  },
  {
    id: "sci-g10-06",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.1",
    skill: "Homeostasis",
    passage:
      "After a meal, blood glucose rises. The pancreas releases insulin, which signals body cells to take in glucose. Blood glucose falls back to normal, and insulin release slows.",
    prompt: "This process is an example of...",
    choices: [
      "Negative feedback maintaining homeostasis",
      "Positive feedback increasing the change",
      "Active transport of insulin into cells",
      "A mutation in the pancreas",
    ],
    answer: 0,
    explanation: "Negative feedback reverses a change to return the body to a set point. Positive feedback would push glucose even further from normal.",
  },
  {
    id: "sci-g10-07",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.1",
    skill: "Cell transport",
    prompt: "Moving molecules against their concentration gradient requires...",
    choices: ["Energy (ATP)", "No energy", "Osmosis", "Diffusion"],
    answer: 0,
    explanation: "Active transport uses ATP and protein pumps to move substances from low to high concentration.",
    quick: true,
  },
  {
    id: "sci-g10-08",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "Photosynthesis uses CO₂ and water and releases which gas?",
    choices: ["Oxygen", "Nitrogen", "Methane", "Hydrogen"],
    answer: 0,
    explanation: "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. The oxygen comes from splitting water.",
    quick: true,
  },
  {
    id: "sci-g10-09",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.3",
    skill: "Cellular respiration",
    prompt: "Cellular respiration releases the energy stored in...",
    choices: ["Glucose", "Oxygen", "Water", "Carbon dioxide"],
    answer: 0,
    explanation: "Cells break down glucose (with oxygen, in aerobic respiration) to make ATP, releasing CO₂ and water.",
    quick: true,
  },
  {
    id: "sci-g10-10",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5.1",
    skill: "Population growth",
    passage:
      "Deer were introduced to an island with no predators. Population counts: 1990: 100; 1995: 400; 2000: 900; 2005: 950; 2010: 920; 2015: 940.",
    prompt: "What is the best estimate of the island's carrying capacity for deer?",
    choices: ["About 930", "About 100", "About 400", "There is no limit"],
    answer: 0,
    explanation: "The population grew quickly, then leveled off and hovered around 920–950. That plateau shows the carrying capacity set by limited food and space.",
  },
  {
    id: "sci-g10-11",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.4.2",
    skill: "Matter cycles",
    prompt: "Plants turning CO₂ from the air into sugars is part of which cycle?",
    choices: ["Carbon", "Nitrogen", "Rock", "Phosphorus"],
    answer: 0,
    explanation: "Photosynthesis moves carbon from the atmosphere into living things. Respiration and decomposition return it.",
    quick: true,
  },
  {
    id: "sci-g10-12",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.5",
    skill: "DNA structure",
    prompt: "In DNA, adenine (A) always pairs with...",
    choices: ["Thymine (T)", "Guanine (G)", "Cytosine (C)", "Uracil (U)"],
    answer: 0,
    explanation: "DNA base pairs are A–T and G–C. Uracil replaces thymine only in RNA.",
    quick: true,
  },
  {
    id: "sci-g10-13",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.5",
    skill: "Protein synthesis",
    prompt: "A codon, which codes for one amino acid, is a group of how many bases?",
    choices: ["Three", "Two", "Four", "Twenty"],
    answer: 0,
    explanation: "Each three-base mRNA codon specifies one amino acid (or a stop signal).",
    quick: true,
  },
  {
    id: "sci-g10-14",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.7.1",
    skill: "Genetic crosses",
    prompt: "Two carriers (Aa × Aa) have offspring. What fraction show the recessive trait?",
    choices: ["1/4", "1/2", "3/4", "0"],
    answer: 0,
    explanation: "The cross gives AA, Aa, Aa, aa. Only aa (1 of 4) shows the recessive trait.",
    quick: true,
  },
  {
    id: "sci-g10-15",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.7.1",
    skill: "Inheritance patterns",
    passage:
      "A red-flowered snapdragon (RR) is crossed with a white-flowered snapdragon (WW). Every offspring has pink flowers (RW).",
    prompt: "Which inheritance pattern explains the pink flowers?",
    choices: ["Incomplete dominance", "Codominance", "Complete dominance", "Sex-linked inheritance"],
    answer: 0,
    explanation: "In incomplete dominance, the heterozygote shows a blend. In codominance, both traits would show separately, like red and white patches.",
  },
  {
    id: "sci-g10-16",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.9.1",
    skill: "Natural selection",
    passage:
      "A patient stops taking an antibiotic after a few days. A few bacteria that happened to have a resistance gene survive. They multiply, and the new infection does not respond to the same antibiotic.",
    prompt: "What best explains why the bacteria population is now resistant?",
    choices: [
      "The antibiotic selected for bacteria that already had resistance",
      "The antibiotic caused each bacterium to become resistant",
      "The bacteria learned to avoid the antibiotic",
      "The patient's body became resistant to the antibiotic",
    ],
    answer: 0,
    explanation: "Natural selection acts on existing variation: resistant bacteria survive and reproduce, so their trait becomes common.",
  },
  {
    id: "sci-g10-17",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.9.2",
    skill: "Evidence of evolution",
    prompt: "Structures with the same origin but different functions are...",
    choices: ["Homologous", "Analogous", "Vestigial", "Identical"],
    answer: 0,
    explanation: "Homologous structures, like a whale flipper and a human arm, point to a common ancestor. Analogous ones share function, not origin.",
    quick: true,
  },
  {
    id: "sci-g10-18",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.9.2",
    skill: "Evidence of evolution",
    prompt: "Which data best show how closely two species are related?",
    choices: ["DNA sequences", "Body size", "Diet", "Habitat"],
    answer: 0,
    explanation: "The more similar two species' DNA or protein sequences, the more recently they shared a common ancestor.",
    quick: true,
  },
  {
    id: "sci-g10-19",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.1",
    skill: "Macromolecules",
    prompt: "Enzymes are which type of macromolecule?",
    choices: ["Proteins", "Lipids", "Carbohydrates", "Nucleic acids"],
    answer: 0,
    explanation: "Almost all enzymes are proteins, built from chains of amino acids folded into specific shapes.",
    quick: true,
  },
  {
    id: "sci-g10-20",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.1",
    skill: "Macromolecules",
    prompt: "Which macromolecule is the body's main source of quick energy?",
    choices: ["Carbohydrates", "Proteins", "Nucleic acids", "Lipids"],
    answer: 0,
    explanation: "Carbohydrates like glucose are broken down quickly for energy. Lipids store energy long term.",
    quick: true,
  },
  {
    id: "sci-g10-21",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.2",
    skill: "Enzymes",
    prompt: "Enzymes speed up reactions by lowering the...",
    choices: ["Activation energy", "Temperature", "pH of the cell", "Amount of product"],
    answer: 0,
    explanation: "Enzymes lower the activation energy, the energy needed to start a reaction, without being used up.",
  },
  {
    id: "sci-g10-22",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.2",
    skill: "Enzymes",
    prompt: "High heat changes an enzyme's shape so it stops working. This is...",
    choices: ["Denaturation", "Mutation", "Diffusion", "Replication"],
    answer: 0,
    explanation: "A denatured enzyme loses the shape of its active site, so substrates no longer fit.",
    quick: true,
  },
  {
    id: "sci-g10-23",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.3",
    skill: "Organelles",
    prompt: "Which organelle modifies and packages proteins for shipping?",
    choices: ["Golgi body", "Nucleus", "Lysosome", "Chloroplast"],
    answer: 0,
    explanation: "The Golgi apparatus sorts, modifies and packages proteins into vesicles.",
    quick: true,
  },
  {
    id: "sci-g10-24",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.5",
    skill: "Protein synthesis",
    prompt: "Transcription copies a gene from DNA into...",
    choices: ["mRNA", "Protein", "Lipid", "Glucose"],
    answer: 0,
    explanation: "In transcription, a gene's DNA code is copied into messenger RNA, which carries it to a ribosome.",
    quick: true,
  },
  {
    id: "sci-g10-25",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.5",
    skill: "Protein synthesis",
    prompt: "In RNA, which base replaces thymine?",
    choices: ["Uracil", "Adenine", "Guanine", "Cytosine"],
    answer: 0,
    explanation: "RNA uses uracil (U) instead of thymine (T), so A pairs with U.",
    quick: true,
  },
  {
    id: "sci-g10-26",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2.1",
    skill: "Cell division",
    prompt: "Mitosis produces two daughter cells that are...",
    choices: ["Identical", "Haploid", "Gametes", "Mutants"],
    answer: 0,
    explanation: "Mitosis makes two genetically identical cells for growth and repair.",
    quick: true,
  },
  {
    id: "sci-g10-27",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2.1",
    skill: "Cell division",
    prompt: "In which phase do chromosomes line up in the middle of the cell?",
    choices: ["Metaphase", "Prophase", "Anaphase", "Telophase"],
    answer: 0,
    explanation: "In metaphase, chromosomes line up along the cell's equator before they are pulled apart.",
    quick: true,
  },
  {
    id: "sci-g10-28",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2.2",
    skill: "Differentiation and cancer",
    prompt: "Cell division that is no longer controlled can lead to...",
    choices: ["Cancer", "Immunity", "Osmosis", "Meiosis"],
    answer: 0,
    explanation: "When genes that regulate the cell cycle are damaged, cells divide out of control and can form tumors.",
    quick: true,
  },
  {
    id: "sci-g10-29",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.1",
    skill: "Homeostasis",
    prompt: "Sweating to cool off on a hot day is an example of...",
    choices: ["Homeostasis", "Photosynthesis", "Mutation", "Evolution"],
    answer: 0,
    explanation: "Homeostasis keeps internal conditions, like body temperature, stable.",
    quick: true,
  },
  {
    id: "sci-g10-30",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.1",
    skill: "Homeostasis",
    prompt: "During exercise, blood CO₂ rises. Your breathing rate...",
    choices: ["Increases", "Decreases", "Stops", "Stays same"],
    answer: 0,
    explanation: "Sensors detect the extra CO₂, and the brain speeds up breathing to remove it. This feedback keeps blood chemistry stable.",
    quick: true,
  },
  {
    id: "sci-g10-31",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "The light reactions of photosynthesis happen in the...",
    choices: ["Thylakoids", "Stroma", "Mitochondria", "Nucleus"],
    answer: 0,
    explanation: "Chlorophyll in the thylakoid membranes captures light to make ATP and NADPH.",
    quick: true,
  },
  {
    id: "sci-g10-32",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "In which part of the chloroplast does the Calvin cycle occur?",
    choices: ["Stroma", "Thylakoid", "Cytoplasm", "Cell wall"],
    answer: 0,
    explanation: "The Calvin cycle uses ATP, NADPH and CO₂ to build sugar in the stroma, the fluid around the thylakoids.",
    quick: true,
  },
  {
    id: "sci-g10-33",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "The O₂ released by photosynthesis comes from splitting...",
    choices: ["Water", "Glucose", "CO₂", "ATP"],
    answer: 0,
    explanation: "In the light reactions, water molecules are split. Their oxygen atoms are released as O₂.",
    quick: true,
  },
  {
    id: "sci-g10-34",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "Light reactions supply ATP and which carrier to the Calvin cycle?",
    choices: ["NADPH", "Glucose", "CO₂", "DNA"],
    answer: 0,
    explanation: "ATP and NADPH carry energy and electrons from the light reactions to the Calvin cycle.",
    quick: true,
  },
  {
    id: "sci-g10-35",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.3",
    skill: "Cellular respiration",
    prompt: "Without oxygen, yeast make ATP by...",
    choices: ["Fermentation", "Photosynthesis", "Krebs cycle", "Osmosis"],
    answer: 0,
    explanation: "Yeast use alcoholic fermentation, making ethanol and CO₂ and a small amount of ATP.",
    quick: true,
  },
  {
    id: "sci-g10-36",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.4.2",
    skill: "Energy flow",
    prompt: "In an energy pyramid, which level has the most energy?",
    choices: ["Producers", "Top predators", "Herbivores", "Carnivores"],
    answer: 0,
    explanation: "Producers sit at the base. Only about 10% of energy passes to each higher level.",
    quick: true,
  },
  {
    id: "sci-g10-37",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5.1",
    skill: "Population interactions",
    prompt: "Over time, predator and prey populations usually...",
    choices: ["Cycle together", "Never change", "Both vanish", "Grow forever"],
    answer: 0,
    explanation: "More prey feeds more predators. Then prey decline, and predators follow, in repeating cycles.",
    quick: true,
  },
  {
    id: "sci-g10-38",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.6.1",
    skill: "Meiosis",
    prompt: "Human egg and sperm cells each have how many chromosomes?",
    choices: ["23", "46", "92", "12"],
    answer: 0,
    explanation: "Meiosis halves the chromosome number, so gametes have 23. Fertilization restores 46.",
    quick: true,
  },
  {
    id: "sci-g10-39",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.6.2",
    skill: "Genetic variation",
    prompt: "Crossing over during meiosis increases...",
    choices: ["Variation", "Cell size", "ATP output", "Cell count"],
    answer: 0,
    explanation: "Crossing over swaps DNA between paired chromosomes, making new combinations of alleles.",
    quick: true,
  },
  {
    id: "sci-g10-40",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.7.1",
    skill: "Inheritance patterns",
    prompt: "Type AB blood shows both A and B traits. This pattern is...",
    choices: ["Codominance", "Incomplete", "Sex-linked", "Polygenic"],
    answer: 0,
    explanation: "In codominance, both alleles are fully expressed. Type AB blood has both A and B markers.",
    quick: true,
  },
  {
    id: "sci-g10-41",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.7.2",
    skill: "Polygenic traits",
    prompt: "Human height, controlled by many genes, is a...",
    choices: ["Polygenic", "Sex-linked", "Codominant", "Single-gene"],
    answer: 0,
    explanation: "Polygenic traits are shaped by several genes, giving a wide, continuous range of phenotypes.",
    quick: true,
  },
  {
    id: "sci-g10-42",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.8.2",
    skill: "Biotechnology",
    prompt: "Bt corn makes its own insecticide because it carries a...",
    choices: ["Bacterial gene", "Virus coat", "Extra leaf", "Fungus"],
    answer: 0,
    explanation: "Scientists inserted a gene from the bacterium Bacillus thuringiensis, making the corn genetically modified.",
    quick: true,
  },
  {
    id: "sci-g10-43",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.9.1",
    skill: "Natural selection",
    prompt: "Two populations split by a new mountain range may become...",
    choices: ["New species", "Identical", "One species", "Prokaryotes"],
    answer: 0,
    explanation: "Geographic isolation stops gene flow. Over time, the groups can evolve into separate species.",
    quick: true,
  },
  {
    id: "sci-g10-44",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1.5",
    skill: "Protein synthesis",
    passage:
      "DNA template strand: TAC GGA",
    prompt: "Which mRNA sequence is transcribed from this DNA template?",
    choices: ["AUG CCU", "ATG CCT", "TAC GGA", "UAC GGA"],
    answer: 0,
    explanation: "Pair each DNA base with its RNA partner: T→A, A→U, C→G, G→C. TAC GGA becomes AUG CCU.",
  },
  {
    id: "sci-g10-45",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2.2",
    skill: "Differentiation and cancer",
    prompt: "Nerve and muscle cells in one person have the same DNA. Why are they different?",
    choices: [
      "They express different genes",
      "They have different DNA",
      "They lost some chromosomes",
      "They came from different parents",
    ],
    answer: 0,
    explanation: "Every body cell has the same genes, but each cell type turns on (expresses) a different set of them.",
  },
  {
    id: "sci-g10-46",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    passage:
      "Chlorophyll absorbs about 80% of blue light, 70% of red light, and only about 10% of green light.",
    prompt: "Which color of light would give the slowest photosynthesis?",
    choices: ["Green", "Blue", "Red", "White"],
    answer: 0,
    explanation: "Chlorophyll absorbs little green light, so green light provides the least energy for photosynthesis.",
  },
  {
    id: "sci-g10-47",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3.2",
    skill: "Photosynthesis",
    prompt: "Which equation correctly summarizes photosynthesis?",
    choices: [
      "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂",
      "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O",
      "6O₂ + 6H₂O → C₆H₁₂O₆ + 6CO₂",
      "6CO₂ + C₆H₁₂O₆ → 6H₂O + 6O₂",
    ],
    answer: 0,
    explanation: "Carbon dioxide and water, powered by light, become glucose and oxygen. The reverse is cellular respiration.",
  },
  {
    id: "sci-g10-48",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5.2",
    skill: "Human impact",
    prompt: "How does kudzu mainly harm NC forests?",
    choices: [
      "It shades out native plants",
      "It feeds native deer",
      "It cools forest streams",
      "It eats forest insects",
    ],
    answer: 0,
    explanation: "Kudzu is an invasive vine that grows over trees and blocks their sunlight, killing native plants.",
  },
];
export default questions;
