import type { Question } from "../../types";
// Grade K science — NC Standard Course of Study for Science (2023). Sorting objects by physical properties and
// materials (PS.K.1); position words, pushes, pulls and ways things move (PS.K.2); daily and seasonal weather and
// weather patterns (ESS.K.1); how weather changes the land around us (ESS.K.2); living vs. nonliving and how animals use
// their body parts (LS.K.1); how animals and plants of the same kind are alike and different (LS.K.2).
const questions: Question[] = [
  {
    id: "sci-gK-01",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one feels soft?",
    choices: ["Pillow", "Rock", "Spoon", "Brick"],
    answer: 0,
    explanation: "A pillow is soft. Rocks, spoons and bricks are hard. How a thing feels is one of its properties.",
    quick: true,
  },
  {
    id: "sci-gK-02",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one is the heaviest?",
    choices: ["Bowling ball", "Feather", "Leaf", "Balloon"],
    answer: 0,
    explanation: "A bowling ball is very heavy. A feather, a leaf and a balloon are light. Weight is a property we can feel.",
    quick: true,
  },
  {
    id: "sci-gK-03",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one can bend and stretch?",
    choices: ["Rubber band", "Rock", "Brick", "Wood block"],
    answer: 0,
    explanation: "A rubber band is flexible, so it can bend and stretch. Rocks, bricks and wood blocks are stiff.",
    quick: true,
  },
  {
    id: "sci-gK-04",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "What are most windows made of?",
    choices: ["Glass", "Paper", "Cloth", "Clay"],
    answer: 0,
    explanation: "Windows are made of glass because you can see through it and it keeps rain out.",
    quick: true,
  },
  {
    id: "sci-gK-05",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "Which is best for making a warm coat?",
    choices: ["Cloth", "Paper", "Glass", "Rock"],
    answer: 0,
    explanation: "Cloth is soft, bends easily and keeps you warm. That is why coats are made of cloth.",
    quick: true,
  },
  {
    id: "sci-gK-06",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "A push moves a thing which way?",
    choices: ["Away from you", "Toward you", "Up only", "Nowhere"],
    answer: 0,
    explanation: "A push moves a thing away from you. A pull moves a thing toward you.",
    quick: true,
  },
  {
    id: "sci-gK-07",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "To open a drawer, you give it a...",
    choices: ["Pull", "Push", "Kick", "Hug"],
    answer: 0,
    explanation: "You pull a drawer toward you to open it. You push it away to close it.",
    quick: true,
  },
  {
    id: "sci-gK-08",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "What happens when you drop a ball?",
    choices: ["It falls down", "It floats up", "It stays put", "It melts"],
    answer: 0,
    explanation: "When you let go of a ball, it falls down to the ground. Things fall when they are dropped.",
    quick: true,
  },
  {
    id: "sci-gK-09",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "A harder kick makes a ball go...",
    choices: ["Farther", "Less far", "Nowhere", "Backward"],
    answer: 0,
    explanation: "A bigger push makes a ball go faster and farther. A soft kick makes it go only a little way.",
    quick: true,
  },
  {
    id: "sci-gK-10",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "How does a swing move?",
    choices: ["Back and forth", "Zigzag", "In a circle", "It can't move"],
    answer: 0,
    explanation: "A swing moves back and forth. Other things move straight, zigzag, or round and round.",
    quick: true,
  },
  {
    id: "sci-gK-11",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "What should you wear on a snowy day?",
    choices: ["Warm coat", "Swimsuit", "Sandals", "Shorts"],
    answer: 0,
    explanation: "Snowy days are cold, so a warm coat keeps you cozy. We change what we wear when the weather changes.",
    quick: true,
  },
  {
    id: "sci-gK-12",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "What falls from clouds on a rainy day?",
    choices: ["Water drops", "Sand", "Leaves", "Rocks"],
    answer: 0,
    explanation: "Rain is drops of water falling from clouds. Rain makes puddles and helps plants grow.",
    quick: true,
  },
  {
    id: "sci-gK-13",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.2",
    skill: "Seasons",
    prompt: "Which season is the coldest?",
    choices: ["Winter", "Summer", "Spring", "Fall"],
    answer: 0,
    explanation: "Winter is the coldest season. Summer is the hottest. The weather changes through the year.",
    quick: true,
  },
  {
    id: "sci-gK-14",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.2",
    skill: "Weather",
    prompt: "What tool tells how hot or cold it is?",
    choices: ["Thermometer", "Ruler", "Clock", "Spoon"],
    answer: 0,
    explanation: "A thermometer measures temperature, which tells how hot or cold it is.",
    quick: true,
  },
  {
    id: "sci-gK-15",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.1",
    skill: "Living and nonliving",
    prompt: "Which one is alive?",
    choices: ["Dog", "Rock", "Chair", "Ball"],
    answer: 0,
    explanation: "A dog is alive. It eats, drinks, grows and moves on its own. Rocks, chairs and balls do not.",
    quick: true,
  },
  {
    id: "sci-gK-16",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.1",
    skill: "Living and nonliving",
    prompt: "What do all living things need?",
    choices: ["Water", "Toys", "TV", "Shoes"],
    answer: 0,
    explanation: "Every living thing needs water. Plants, animals and people all need water to live.",
    quick: true,
  },
  {
    id: "sci-gK-17",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.1",
    skill: "Animals alike and different",
    prompt: "What do a robin and a crow both have?",
    choices: ["Feathers", "Fur", "Scales", "Fins"],
    answer: 0,
    explanation: "Robins and crows are both birds, and all birds have feathers.",
    quick: true,
  },
  {
    id: "sci-gK-18",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.1",
    skill: "Animals alike and different",
    prompt: "Two dogs can look different. What can be different?",
    choices: ["Fur color", "Being a dog", "Having a nose", "Needing food"],
    answer: 0,
    explanation: "Dogs can have different fur colors and sizes, but they are all dogs with noses who need food.",
    quick: true,
  },
  {
    id: "sci-gK-19",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.1",
    skill: "Position words",
    prompt: "A bird sits on top of a house. Where is the bird?",
    choices: ["Above it", "Under it", "Inside it", "Behind it"],
    answer: 0,
    explanation: "On top of the house means the bird is above it. Position words tell where things are.",
    quick: true,
  },
  {
    id: "sci-gK-20",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.1",
    skill: "Position words",
    prompt: "Which word means the opposite of above?",
    choices: ["Below", "Over", "On top", "High"],
    answer: 0,
    explanation: "Above means higher than something. Below means lower than something.",
    quick: true,
  },
  {
    id: "sci-gK-21",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.1",
    skill: "Position words",
    prompt: "Sam stands between Ana and Lee. Who is in the middle?",
    choices: ["Sam", "Ana", "Lee", "Nobody"],
    answer: 0,
    explanation: "Between means in the middle. Sam is in the middle, with Ana on one side and Lee on the other.",
    quick: true,
  },
  {
    id: "sci-gK-22",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.1",
    skill: "Position words",
    prompt: "Mia is first in line. Ben is behind Mia. Who is in front?",
    choices: ["Mia", "Ben", "The teacher", "No one"],
    answer: 0,
    explanation: "Ben is behind Mia, so Mia is in front of Ben.",
    quick: true,
  },
  {
    id: "sci-gK-23",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.1",
    skill: "Position words",
    prompt: "A book is beside the lamp. Where is the book?",
    choices: ["Next to it", "On top of it", "Under it", "Inside it"],
    answer: 0,
    explanation: "Beside means next to. The book is right next to the lamp.",
    quick: true,
  },
  {
    id: "sci-gK-24",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one is round?",
    choices: ["Ball", "Book", "Box", "Door"],
    answer: 0,
    explanation: "A ball is round. Books, boxes and doors have flat sides and corners. Shape is a property.",
    quick: true,
  },
  {
    id: "sci-gK-25",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one sinks in water?",
    choices: ["Rock", "Cork", "Leaf", "Feather"],
    answer: 0,
    explanation: "A rock sinks to the bottom. A cork, a leaf and a feather float on top of the water.",
    quick: true,
  },
  {
    id: "sci-gK-26",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.1",
    skill: "Sorting by properties",
    prompt: "Which one feels rough?",
    choices: ["Sandpaper", "Silk", "Glass", "Ice"],
    answer: 0,
    explanation: "Sandpaper feels rough and scratchy. Silk, glass and ice feel smooth.",
    quick: true,
  },
  {
    id: "sci-gK-27",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "Which one is made of wood?",
    choices: ["Pencil", "Coin", "Window", "Sock"],
    answer: 0,
    explanation: "Most pencils are made of wood. Coins are metal, windows are glass and socks are cloth.",
    quick: true,
  },
  {
    id: "sci-gK-28",
    subject: "science",
    grade: "K",
    standard: "PS.K.1.2",
    skill: "Materials and their uses",
    prompt: "Rain boots are made of rubber to...",
    choices: ["Keep feet dry", "Look shiny", "Make noise", "Smell nice"],
    answer: 0,
    explanation: "Water cannot get through rubber, so rubber boots keep your feet dry.",
    quick: true,
  },
  {
    id: "sci-gK-29",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "How does a merry-go-round move?",
    choices: ["In a circle", "Zigzag", "Straight", "Up only"],
    answer: 0,
    explanation: "A merry-go-round goes round and round in a circle.",
    quick: true,
  },
  {
    id: "sci-gK-30",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "Which one moves the fastest?",
    choices: ["Race car", "Snail", "Turtle", "Worm"],
    answer: 0,
    explanation: "A race car is very fast. Snails, turtles and worms move slowly.",
    quick: true,
  },
  {
    id: "sci-gK-31",
    subject: "science",
    grade: "K",
    standard: "PS.K.2.2",
    skill: "Ways things move",
    prompt: "A rabbit runs left, then right, then left. It moves in a...",
    choices: ["Zigzag", "Circle", "Straight line", "Back and forth"],
    answer: 0,
    explanation: "Turning one way and then the other way makes a zigzag path.",
    quick: true,
  },
  {
    id: "sci-gK-32",
    subject: "science",
    grade: "K",
    standard: "PS.K.2",
    skill: "Pushes and pulls",
    prompt: "Kicking a ball is a...",
    choices: ["Push", "Pull", "Sound", "Color"],
    answer: 0,
    explanation: "Your foot pushes the ball away from you. A kick is a push.",
    quick: true,
  },
  {
    id: "sci-gK-33",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "What do people use on a rainy day?",
    choices: ["Umbrella", "Sunglasses", "Sled", "Fan"],
    answer: 0,
    explanation: "An umbrella keeps the rain off you. We use different things for different weather.",
    quick: true,
  },
  {
    id: "sci-gK-34",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "When the wind blows, leaves on a tree...",
    choices: ["Move", "Melt", "Freeze", "Sing"],
    answer: 0,
    explanation: "Wind is moving air. It pushes leaves so they wave and move.",
    quick: true,
  },
  {
    id: "sci-gK-35",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    prompt: "The sun shines on the ground. The ground gets...",
    choices: ["Warm", "Wet", "Snowy", "Dark"],
    answer: 0,
    explanation: "Sunlight warms the land, air and water.",
    quick: true,
  },
  {
    id: "sci-gK-36",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.3",
    skill: "Seasons",
    prompt: "In which season do many leaves fall off trees?",
    choices: ["Fall", "Spring", "Summer", "Morning"],
    answer: 0,
    explanation: "In fall, many leaves change color and drop. That is why the season is called fall.",
    quick: true,
  },
  {
    id: "sci-gK-37",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.3",
    skill: "Seasons",
    prompt: "Which season comes after winter?",
    choices: ["Spring", "Summer", "Fall", "Night"],
    answer: 0,
    explanation: "The seasons go winter, spring, summer, fall, and then winter again.",
    quick: true,
  },
  {
    id: "sci-gK-38",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.3",
    skill: "Seasons",
    prompt: "In summer, the weather is usually...",
    choices: ["Hot", "Snowy", "Icy", "Freezing"],
    answer: 0,
    explanation: "Summer is the hottest season. Winter is the coldest.",
    quick: true,
  },
  {
    id: "sci-gK-39",
    subject: "science",
    grade: "K",
    standard: "ESS.K.2.1",
    skill: "Weather changes the land",
    prompt: "After a big rain, the ground has...",
    choices: ["Puddles", "Snowmen", "Dry dust", "Sand piles"],
    answer: 0,
    explanation: "Rain water collects in low spots and makes puddles.",
    quick: true,
  },
  {
    id: "sci-gK-40",
    subject: "science",
    grade: "K",
    standard: "ESS.K.2.1",
    skill: "Weather changes the land",
    prompt: "Strong wind can knock down...",
    choices: ["Tree branches", "Mountains", "The moon", "Rivers"],
    answer: 0,
    explanation: "Very strong wind can break branches and blow them down.",
    quick: true,
  },
  {
    id: "sci-gK-41",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.2",
    skill: "Animal body parts",
    prompt: "What does a turtle use to stay safe?",
    choices: ["Its shell", "Its tail", "Its eyes", "Its claws"],
    answer: 0,
    explanation: "A turtle can pull into its hard shell to hide from danger.",
    quick: true,
  },
  {
    id: "sci-gK-42",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.2",
    skill: "Animal body parts",
    prompt: "A giraffe's long neck helps it...",
    choices: ["Reach leaves", "Swim fast", "Dig holes", "Fly high"],
    answer: 0,
    explanation: "A long neck lets a giraffe eat leaves high up in tall trees.",
    quick: true,
  },
  {
    id: "sci-gK-43",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.2",
    skill: "Animal body parts",
    prompt: "What helps a bird fly?",
    choices: ["Wings", "Beak", "Feet", "Eyes"],
    answer: 0,
    explanation: "Birds flap their wings to fly through the air.",
    quick: true,
  },
  {
    id: "sci-gK-44",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.2",
    skill: "Animal body parts",
    prompt: "What does a duck use to paddle in water?",
    choices: ["Webbed feet", "Its beak", "Its eyes", "Its tail"],
    answer: 0,
    explanation: "Ducks have webbed feet that push water like paddles.",
    quick: true,
  },
  {
    id: "sci-gK-45",
    subject: "science",
    grade: "K",
    standard: "LS.K.1.1",
    skill: "Living and nonliving",
    prompt: "Which one is nonliving?",
    choices: ["Toy car", "Tree", "Bird", "Frog"],
    answer: 0,
    explanation: "A toy car does not eat, drink, grow or make babies, so it is nonliving. Trees, birds and frogs are alive.",
    quick: true,
  },
  {
    id: "sci-gK-46",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.2",
    skill: "Plants alike and different",
    prompt: "Two apple trees are alike. Both grow...",
    choices: ["Apples", "Oranges", "Pinecones", "Acorns"],
    answer: 0,
    explanation: "Plants of the same kind make the same kind of fruit. Apple trees grow apples.",
    quick: true,
  },
  {
    id: "sci-gK-47",
    subject: "science",
    grade: "K",
    standard: "ESS.K.1.1",
    skill: "Weather",
    passage:
      "Lily made a weather chart. Monday: sunny. Tuesday: rainy. Wednesday: sunny. Thursday: sunny.",
    prompt: "Which weather did Lily see the most?",
    choices: ["Sunny", "Rainy", "Snowy", "Windy"],
    answer: 0,
    explanation: "Lily saw sunny weather on 3 days and rainy weather on only 1 day.",
  },
  {
    id: "sci-gK-48",
    subject: "science",
    grade: "K",
    standard: "LS.K.2.2",
    skill: "Plants alike and different",
    passage:
      "Two sunflowers grow in a garden. Both have yellow petals and green leaves. One is as tall as a door. One is as tall as a chair.",
    prompt: "How are the two sunflowers different?",
    choices: ["One is taller", "Only one is a plant", "Only one has leaves", "Only one needs water"],
    answer: 0,
    explanation: "Both are sunflowers with leaves that need water. Plants of the same kind can still be different sizes.",
  },
];
export default questions;
