import type { Question } from "../../types";

// Grade 5 ELA — NC Standard Course of Study for ELA (2017). RL.5.1, RL.5.2, RL.5.3, RL.5.4, RL.5.5, RL.5.6, RI.5.2, RI.5.3, RI.5.5, RI.5.8, RF.5.4, L.5.1, L.5.2, L.5.3, L.5.4, L.5.5
const questions: Question[] = [
  {
    id: "ela-g5-01",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Greek and Latin roots",
    prompt: "The Latin root aud (as in audience) means...",
    choices: ["hear", "see", "speak", "walk"],
    answer: 0,
    explanation: "Aud means hear. An audience is a group that listens.",
    quick: true,
  },
  {
    id: "ela-g5-02",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Greek and Latin roots",
    prompt: "The Greek root bio (as in biology) means...",
    choices: ["life", "earth", "water", "book"],
    answer: 0,
    explanation: "Bio means life. Biology is the study of living things.",
    quick: true,
  },
  {
    id: "ela-g5-03",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Prefixes",
    prompt: "The prefix mis- in misspell means...",
    choices: ["wrongly", "again", "before", "not yet"],
    answer: 0,
    explanation: "Mis- means wrongly or badly, so misspell means spell wrongly.",
    quick: true,
  },
  {
    id: "ela-g5-04",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Personification",
    prompt: "'The wind whispered through the trees.' What is given a human action?",
    choices: ["the wind", "the trees", "a person", "a whisper"],
    answer: 0,
    explanation: "Only people whisper. Giving the wind a human action is personification.",
    quick: true,
  },
  {
    id: "ela-g5-05",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Hyperbole",
    prompt: "'I've told you a million times!' This is an example of...",
    choices: ["hyperbole", "simile", "alliteration", "onomatopoeia"],
    answer: 0,
    explanation: "Hyperbole is a big exaggeration used for effect.",
    quick: true,
  },
  {
    id: "ela-g5-06",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Adages and proverbs",
    prompt: "What does 'Don't count your chickens before they hatch' mean?",
    choices: ["Don't assume", "Count slowly", "Raise chickens", "Eat breakfast"],
    answer: 0,
    explanation: "This proverb warns not to count on something good before it actually happens.",
    quick: true,
  },
  {
    id: "ela-g5-07",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Homographs",
    prompt: "In 'The bat flew out of the cave,' what is a bat?",
    choices: ["an animal", "a club", "a wink", "a game"],
    answer: 0,
    explanation: "Bat is a homograph. Flying out of a cave tells us it is the animal.",
    quick: true,
  },
  {
    id: "ela-g5-08",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Interjections",
    prompt: "Which word is an interjection?",
    choices: ["Wow", "quickly", "table", "because"],
    answer: 0,
    explanation: "An interjection shows sudden feeling, like Wow! or Oops!",
    quick: true,
  },
  {
    id: "ela-g5-09",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Correlative conjunctions",
    prompt: "___ Sam ___ Kim will go. Which pair fits?",
    choices: ["Either / or", "Neither / or", "Both / or", "Not / nor"],
    answer: 0,
    explanation: "Correlative conjunctions come in pairs: either/or, neither/nor, both/and.",
    quick: true,
  },
  {
    id: "ela-g5-10",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Perfect verb tenses",
    prompt: "Which verb is in the present perfect tense?",
    choices: ["has eaten", "ate", "will eat", "is eating"],
    answer: 0,
    explanation: "Present perfect uses has or have plus a past participle: has eaten.",
    quick: true,
  },
  {
    id: "ela-g5-11",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Verb tense shifts",
    prompt: "She opened the box and ___ a puppy. Which verb fits?",
    choices: ["found", "finds", "will find", "is finding"],
    answer: 0,
    explanation: "Opened is past tense, so found keeps the tense the same.",
    quick: true,
  },
  {
    id: "ela-g5-12",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Commas",
    prompt: "Which sentence uses a comma correctly?",
    choices: ["Yes, I can go.", "Yes I, can go.", "Yes I can, go.", "Yes I can go,"],
    answer: 0,
    explanation: "Use a comma after yes or no at the start of a sentence.",
    quick: true,
  },
  {
    id: "ela-g5-13",
    subject: "ela",
    grade: "5",
    standard: "RL.5.6",
    skill: "Narrator's point of view",
    prompt: "A narrator who knows every character's thoughts is...",
    choices: ["omniscient", "limited", "first person", "a character"],
    answer: 0,
    explanation: "An omniscient narrator is all-knowing and can share every character's thoughts.",
    quick: true,
  },
  {
    id: "ela-g5-14",
    subject: "ela",
    grade: "5",
    standard: "RI.5.5",
    skill: "Text structure",
    prompt: "A text on how frogs and toads are alike and different uses...",
    choices: ["comparison", "chronology", "cause/effect", "description"],
    answer: 0,
    explanation: "Telling how things are alike and different is compare-and-contrast structure.",
    quick: true,
  },
  {
    id: "ela-g5-15",
    subject: "ela",
    grade: "5",
    standard: "RL.5.2",
    skill: "Theme",
    prompt: "What is the theme of this story?",
    passage: "Every morning, Ms. Park's garden had fewer tomatoes. Her neighbor Leon admitted he had been taking them for his little sisters because his family could not afford groceries. Instead of scolding him, Ms. Park handed him a basket. 'From now on,' she said, 'just ask, and we'll pick them together.'",
    choices: ["Kindness can turn a wrong into friendship.", "Stealing is always punished.", "Gardens are hard work.", "Tomatoes grow best in summer."],
    answer: 0,
    explanation: "Ms. Park answers Leon's mistake with kindness, which points to the theme.",
  },
  {
    id: "ela-g5-16",
    subject: "ela",
    grade: "5",
    standard: "RL.5.4",
    skill: "Figurative language",
    prompt: "What does 'The classroom was a beehive' suggest?",
    passage: "The classroom was a beehive the morning of the field trip. Kids buzzed from desk to desk, and even Mr. Ortiz couldn't stop smiling.",
    choices: ["It was busy and full of activity.", "Bees were in the room.", "The room was very quiet.", "Kids were afraid of stings."],
    answer: 0,
    explanation: "The metaphor compares busy kids to buzzing bees. The next sentence, with kids buzzing around, supports it.",
  },
  {
    id: "ela-g5-17",
    subject: "ela",
    grade: "5",
    standard: "RI.5.8",
    skill: "Reasons and evidence",
    prompt: "Which evidence best supports that a skate park is safer?",
    passage: "Our town should build a skate park. Right now, skaters use the library steps, which damages them and blocks visitors. A skate park would give kids a safe place to exercise. Nearby towns that built parks saw fewer skating injuries.",
    choices: ["Nearby towns saw fewer injuries.", "Skaters use the library steps.", "Kids like to exercise.", "The town has a library."],
    answer: 0,
    explanation: "Fewer injuries in towns with parks is evidence that directly supports the safety reason.",
  },
  {
    id: "ela-g5-18",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Context clues",
    prompt: "What does parched most likely mean?",
    passage: "After hiking all day in the hot sun without enough water, the campers were parched. They gulped down every drop at the stream.",
    choices: ["very thirsty", "very cold", "lost", "excited"],
    answer: 0,
    explanation: "Hiking in the sun without water and gulping every drop are clues that parched means very thirsty.",
  },
  {
    id: "ela-g5-19",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Latin roots",
    prompt: "The Latin root rupt (as in erupt) means...",
    choices: ["break", "build", "carry", "see"],
    answer: 0,
    explanation: "Rupt means break. When a volcano erupts, it breaks out.",
    quick: true,
  },
  {
    id: "ela-g5-20",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Greek roots",
    prompt: "The Greek root therm (as in thermometer) means...",
    choices: ["heat", "measure", "water", "light"],
    answer: 0,
    explanation: "Therm means heat. A thermometer measures heat.",
    quick: true,
  },
  {
    id: "ela-g5-21",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Latin roots",
    prompt: "The Latin root struct (as in construct) means...",
    choices: ["build", "break", "write", "pull"],
    answer: 0,
    explanation: "Struct means build. A structure is something built.",
    quick: true,
  },
  {
    id: "ela-g5-22",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Prefixes",
    prompt: "What does the prefix trans- mean in transport?",
    choices: ["across", "under", "before", "against"],
    answer: 0,
    explanation: "Trans- means across. To transport is to carry across.",
    quick: true,
  },
  {
    id: "ela-g5-23",
    subject: "ela",
    grade: "5",
    standard: "RF.5.4",
    skill: "Suffixes",
    prompt: "Which suffix turns enjoy into a noun?",
    choices: ["-ment", "-ly", "-ful", "-ed"],
    answer: 0,
    explanation: "Enjoy + -ment = enjoyment, a noun.",
    quick: true,
  },
  {
    id: "ela-g5-24",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Idioms",
    prompt: "What does 'under the weather' mean?",
    choices: ["feeling sick", "outside", "wet", "very happy"],
    answer: 0,
    explanation: "'Under the weather' is an idiom that means feeling ill.",
    quick: true,
  },
  {
    id: "ela-g5-25",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Adages",
    prompt: "'Actions speak louder than words' means people are judged by...",
    choices: ["what they do", "what they say", "how loud", "their looks"],
    answer: 0,
    explanation: "This adage means what you do shows more than what you say.",
    quick: true,
  },
  {
    id: "ela-g5-26",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Figurative language",
    prompt: "'The news was music to my ears.' The news was...",
    choices: ["welcome", "noisy", "a song", "confusing"],
    answer: 0,
    explanation: "'Music to my ears' means something pleasant to hear.",
    quick: true,
  },
  {
    id: "ela-g5-27",
    subject: "ela",
    grade: "5",
    standard: "L.5.5",
    skill: "Similes",
    prompt: "'He was as quiet as a mouse.' What does this mean?",
    choices: ["very quiet", "very small", "scared", "hungry"],
    answer: 0,
    explanation: "The simile compares him to a mouse to show he made almost no sound.",
    quick: true,
  },
  {
    id: "ela-g5-28",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Correlative conjunctions",
    prompt: "You can have ___ pizza or pasta. Which word fits?",
    choices: ["either", "neither", "both", "whether"],
    answer: 0,
    explanation: "Either goes with or. Neither goes with nor, and both goes with and.",
    quick: true,
  },
  {
    id: "ela-g5-29",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Perfect tenses",
    prompt: "By the time we arrived, the movie ___ started.",
    choices: ["had", "has", "have", "will have"],
    answer: 0,
    explanation: "Had started (past perfect) shows the movie began before we arrived.",
    quick: true,
  },
  {
    id: "ela-g5-30",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Progressive tenses",
    prompt: "Which verb is in the past progressive tense?",
    choices: ["was running", "ran", "has run", "runs"],
    answer: 0,
    explanation: "Past progressive uses was or were plus an -ing verb.",
    quick: true,
  },
  {
    id: "ela-g5-31",
    subject: "ela",
    grade: "5",
    standard: "L.5.1",
    skill: "Clauses",
    prompt: "Which is an independent clause?",
    choices: ["the sun set", "after lunch", "because I ran", "if it snows"],
    answer: 0,
    explanation: "An independent clause has a subject and verb and can stand alone.",
    quick: true,
  },
  {
    id: "ela-g5-32",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Commas with yes and no",
    prompt: "Where does the comma go in 'Yes I can help'?",
    choices: ["after Yes", "after I", "after can", "after help"],
    answer: 0,
    explanation: "Use a comma to set off yes or no: Yes, I can help.",
    quick: true,
  },
  {
    id: "ela-g5-33",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Direct address",
    prompt: "Which uses a comma for direct address correctly?",
    choices: ["Ben, sit down.", "Ben sit, down.", "Ben sit down,", "Ben sit. down,"],
    answer: 0,
    explanation: "When you speak to someone by name, set the name off with a comma.",
    quick: true,
  },
  {
    id: "ela-g5-34",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Titles",
    prompt: "The title of a short story should be in...",
    choices: ["quote marks", "italics", "all caps", "parentheses"],
    answer: 0,
    explanation: "Short works, like stories and poems, go in quotation marks. Books go in italics.",
    quick: true,
  },
  {
    id: "ela-g5-35",
    subject: "ela",
    grade: "5",
    standard: "L.5.2",
    skill: "Tag questions",
    prompt: "Where does the comma go? 'It's cold today isn't it?'",
    choices: ["after today", "after It's", "after cold", "after isn't"],
    answer: 0,
    explanation: "Use a comma before a tag question: It's cold today, isn't it?",
    quick: true,
  },
  {
    id: "ela-g5-36",
    subject: "ela",
    grade: "5",
    standard: "L.5.3",
    skill: "Varieties of English",
    prompt: "Saying y'all instead of you all is an example of...",
    choices: ["dialect", "a simile", "formal English", "a typo"],
    answer: 0,
    explanation: "A dialect is the way people in a certain place or group speak.",
    quick: true,
  },
  {
    id: "ela-g5-37",
    subject: "ela",
    grade: "5",
    standard: "RL.5.6",
    skill: "Speaker",
    prompt: "The voice that speaks in a poem is called the...",
    choices: ["speaker", "author", "reader", "editor"],
    answer: 0,
    explanation: "The speaker is the voice in a poem. It is not always the poet.",
    quick: true,
  },
  {
    id: "ela-g5-38",
    subject: "ela",
    grade: "5",
    standard: "RI.5.5",
    skill: "Text structure",
    prompt: "A text explaining why the Titanic sank mostly uses...",
    choices: ["cause/effect", "comparison", "sequence", "description"],
    answer: 0,
    explanation: "Explaining why something happened is cause and effect.",
    quick: true,
  },
  {
    id: "ela-g5-39",
    subject: "ela",
    grade: "5",
    standard: "RL.5.1",
    skill: "Quoting the text",
    prompt: "Which quote best shows Nadia is nervous?",
    passage: "Nadia peeked at the math test, then quickly turned it over. Her stomach flipped. She had studied fractions all week, but now every number looked like a stranger.",
    choices: ["\"Her stomach flipped.\"", "\"She had studied fractions all week\"", "\"Nadia peeked at the math test\"", "\"turned it over\""],
    answer: 0,
    explanation: "A flipping stomach is a sign of nerves, so that quote shows it best.",
  },
  {
    id: "ela-g5-40",
    subject: "ela",
    grade: "5",
    standard: "RL.5.2",
    skill: "Theme",
    prompt: "Which theme fits this story?",
    passage: "When the storm knocked down the community garden's fence, the neighbors argued over whose fault it was. Then old Mr. Kim picked up a hammer. One by one, the others joined him, and by sunset the fence stood again.",
    choices: ["Working together solves problems.", "Storms are dangerous.", "Fences are hard to build.", "Neighbors always argue."],
    answer: 0,
    explanation: "The neighbors stopped arguing, worked together, and fixed the fence.",
  },
  {
    id: "ela-g5-41",
    subject: "ela",
    grade: "5",
    standard: "RL.5.3",
    skill: "Comparing characters",
    prompt: "How are Ari and Eli different?",
    passage: "Twins Ari and Eli each won a bag of candy at the fair. Ari hid his bag under his bed. Eli opened his right away and shared it with their little sister.",
    choices: ["Ari keeps things; Eli shares.", "Eli keeps things; Ari shares.", "Both hide their candy.", "Neither likes candy."],
    answer: 0,
    explanation: "Ari hides his candy, while Eli shares his with their sister.",
  },
  {
    id: "ela-g5-42",
    subject: "ela",
    grade: "5",
    standard: "RL.5.4",
    skill: "Figurative language",
    prompt: "What does the personification suggest about the car?",
    passage: "The old car coughed and wheezed up the hill, finally collapsing in the driveway.",
    choices: ["It is old and barely working.", "It has a cold.", "It is brand new.", "It is very fast."],
    answer: 0,
    explanation: "Coughing, wheezing, and collapsing make the car sound worn out.",
  },
  {
    id: "ela-g5-43",
    subject: "ela",
    grade: "5",
    standard: "RI.5.2",
    skill: "Main ideas",
    prompt: "Which two main ideas does the text present?",
    passage: "Honeybees pollinate many crops we eat, such as apples and almonds. They also make honey and beeswax. Sadly, bee populations are shrinking because of disease and pesticides.",
    choices: ["Bees are useful, and they are in danger.", "Bees sting and are scary.", "Apples are better than almonds.", "Honey is sweet and sticky."],
    answer: 0,
    explanation: "The text tells how bees help us and why their numbers are shrinking.",
  },
  {
    id: "ela-g5-44",
    subject: "ela",
    grade: "5",
    standard: "RI.5.3",
    skill: "Relationships",
    prompt: "How did the beavers affect other living things?",
    passage: "Because the beavers built a dam, the stream backed up into a pond. Ducks and frogs moved in, and new plants grew along the edge.",
    choices: ["Their dam made a pond for others.", "They chased the ducks away.", "They ate all the plants.", "They dried up the stream."],
    answer: 0,
    explanation: "The beavers' dam made a pond, and ducks, frogs, and plants moved in.",
  },
  {
    id: "ela-g5-45",
    subject: "ela",
    grade: "5",
    standard: "RI.5.8",
    skill: "Reasons and evidence",
    prompt: "Which point does the fact about other cities support?",
    passage: "Our town should build a bike lane on Main Street. Last year, there were 12 bike accidents there. Cities with bike lanes report far fewer crashes.",
    choices: ["Bike lanes can make streets safer.", "Main Street is long.", "Bikes are cheap.", "Cities like bikes."],
    answer: 0,
    explanation: "Fewer crashes in cities with bike lanes supports the idea that bike lanes improve safety.",
  },
  {
    id: "ela-g5-46",
    subject: "ela",
    grade: "5",
    standard: "L.5.4",
    skill: "Context clues",
    prompt: "What does reluctant mean?",
    passage: "Mia was reluctant to jump into the cold lake. She stood on the dock for ten minutes, dipping one toe in and pulling it back.",
    choices: ["unwilling", "excited", "unable", "angry"],
    answer: 0,
    explanation: "Standing on the dock and pulling her toe back shows Mia did not want to jump in.",
  },
  {
    id: "ela-g5-47",
    subject: "ela",
    grade: "5",
    standard: "RL.5.6",
    skill: "Narrator's point of view",
    prompt: "How does the narrator's view of the new girl change?",
    passage: "From where I sat, the new girl seemed stuck-up. She never ate lunch with anyone. Then I found out she read under the tree because she didn't know anyone yet.",
    choices: ["from judging her to understanding her", "from liking her to disliking her", "from ignoring her to fearing her", "It never changes."],
    answer: 0,
    explanation: "At first the narrator thinks she is stuck-up, then learns she is just new.",
  },
  {
    id: "ela-g5-48",
    subject: "ela",
    grade: "5",
    standard: "RL.5.5",
    skill: "Poem structure",
    prompt: "How do the stanzas build the poem?",
    passage: "The seed sleeps in the cold, dark ground.\n\nSpring rain taps; a green shoot is found.\n\nSummer sun: a sunflower, tall and proud.",
    choices: ["Each shows a later stage of growth.", "Each describes a different flower.", "They repeat the same idea.", "They list kinds of weather."],
    answer: 0,
    explanation: "The stanzas move from seed, to shoot, to full-grown sunflower.",
  },
];

export default questions;
