import type { Question } from "../../types";
// Grade 10 science — NC Standard Course of Study for Science (2023), Biology (LS.Bio). Cell structure and function
// (LS.Bio.1); transport and homeostasis (LS.Bio.2); photosynthesis and cellular respiration (LS.Bio.3); ecosystems and
// populations (LS.Bio.4); DNA and heredity (LS.Bio.5); evolution (LS.Bio.6).
const questions: Question[] = [
  {
    id: "sci-g10-01",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1",
    skill: "Organelles",
    prompt: "Which organelle produces most of a cell's ATP?",
    choices: ["Mitochondrion", "Ribosome", "Golgi body", "Nucleus"],
    answer: 0,
    explanation: "Mitochondria carry out aerobic cellular respiration, releasing energy from glucose as ATP.",
    quick: true,
  },
  {
    id: "sci-g10-02",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1",
    skill: "Organelles",
    prompt: "Proteins are assembled from amino acids at the...",
    choices: ["Ribosome", "Lysosome", "Vacuole", "Cell wall"],
    answer: 0,
    explanation: "Ribosomes read mRNA and link amino acids into proteins. Lysosomes break molecules down.",
    quick: true,
  },
  {
    id: "sci-g10-03",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1",
    skill: "Prokaryotes and eukaryotes",
    prompt: "Which cells lack a nucleus and membrane-bound organelles?",
    choices: ["Prokaryotes", "Plant cells", "Animal cells", "Fungal cells"],
    answer: 0,
    explanation: "Prokaryotes (bacteria and archaea) keep their DNA in the cytoplasm. Plant, animal and fungal cells are eukaryotic.",
    quick: true,
  },
  {
    id: "sci-g10-04",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.1",
    skill: "Plant and animal cells",
    prompt: "Plant cells have which structure that animal cells lack?",
    choices: ["Cell wall", "Ribosomes", "Cell membrane", "Mitochondria"],
    answer: 0,
    explanation: "Plant cells have cell walls and chloroplasts. Both plant and animal cells have ribosomes, membranes and mitochondria.",
    quick: true,
  },
  {
    id: "sci-g10-05",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2",
    skill: "Cell transport",
    prompt: "A red blood cell placed in very salty water shrinks. Water left it by...",
    choices: ["Osmosis", "Endocytosis", "Mitosis", "Translation"],
    answer: 0,
    explanation: "Osmosis is water diffusing across a membrane toward the side with more dissolved solute, here the salty outside.",
    quick: true,
  },
  {
    id: "sci-g10-06",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2",
    skill: "Homeostasis",
    passage:
      "After a meal, blood glucose rises. The pancreas releases insulin, which signals body cells to take in glucose. Blood glucose falls back to normal, and insulin release slows.",
    prompt: "This process is an example of...",
    choices: [
      "Negative feedback maintaining homeostasis",
      "Positive feedback increasing the change",
      "Active transport of insulin into cells",
      "A mutation in the pancreas",
    ],
    answer: 0,
    explanation: "Negative feedback reverses a change to return the body to a set point. Positive feedback would push glucose even further from normal.",
  },
  {
    id: "sci-g10-07",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.2",
    skill: "Cell transport",
    prompt: "Moving molecules against their concentration gradient requires...",
    choices: ["Energy (ATP)", "No energy", "Osmosis", "Diffusion"],
    answer: 0,
    explanation: "Active transport uses ATP and protein pumps to move substances from low to high concentration.",
    quick: true,
  },
  {
    id: "sci-g10-08",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3",
    skill: "Photosynthesis",
    prompt: "Photosynthesis uses CO₂ and water and releases which gas?",
    choices: ["Oxygen", "Nitrogen", "Methane", "Hydrogen"],
    answer: 0,
    explanation: "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. The oxygen comes from splitting water.",
    quick: true,
  },
  {
    id: "sci-g10-09",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.3",
    skill: "Cellular respiration",
    prompt: "Cellular respiration releases the energy stored in...",
    choices: ["Glucose", "Oxygen", "Water", "Carbon dioxide"],
    answer: 0,
    explanation: "Cells break down glucose (with oxygen, in aerobic respiration) to make ATP, releasing CO₂ and water.",
    quick: true,
  },
  {
    id: "sci-g10-10",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.4",
    skill: "Population growth",
    passage:
      "Deer were introduced to an island with no predators. Population counts: 1990: 100; 1995: 400; 2000: 900; 2005: 950; 2010: 920; 2015: 940.",
    prompt: "What is the best estimate of the island's carrying capacity for deer?",
    choices: ["About 930", "About 100", "About 400", "There is no limit"],
    answer: 0,
    explanation: "The population grew quickly, then leveled off and hovered around 920–950. That plateau shows the carrying capacity set by limited food and space.",
  },
  {
    id: "sci-g10-11",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.4",
    skill: "Matter cycles",
    prompt: "Plants turning CO₂ from the air into sugars is part of which cycle?",
    choices: ["Carbon", "Nitrogen", "Rock", "Phosphorus"],
    answer: 0,
    explanation: "Photosynthesis moves carbon from the atmosphere into living things. Respiration and decomposition return it.",
    quick: true,
  },
  {
    id: "sci-g10-12",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5",
    skill: "DNA structure",
    prompt: "In DNA, adenine (A) always pairs with...",
    choices: ["Thymine (T)", "Guanine (G)", "Cytosine (C)", "Uracil (U)"],
    answer: 0,
    explanation: "DNA base pairs are A–T and G–C. Uracil replaces thymine only in RNA.",
    quick: true,
  },
  {
    id: "sci-g10-13",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5",
    skill: "Protein synthesis",
    prompt: "A codon, which codes for one amino acid, is a group of how many bases?",
    choices: ["Three", "Two", "Four", "Twenty"],
    answer: 0,
    explanation: "Each three-base mRNA codon specifies one amino acid (or a stop signal).",
    quick: true,
  },
  {
    id: "sci-g10-14",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5",
    skill: "Genetic crosses",
    prompt: "Two carriers (Aa × Aa) have offspring. What fraction show the recessive trait?",
    choices: ["1/4", "1/2", "3/4", "0"],
    answer: 0,
    explanation: "The cross gives AA, Aa, Aa, aa. Only aa (1 of 4) shows the recessive trait.",
    quick: true,
  },
  {
    id: "sci-g10-15",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.5",
    skill: "Inheritance patterns",
    passage:
      "A red-flowered snapdragon (RR) is crossed with a white-flowered snapdragon (WW). Every offspring has pink flowers (RW).",
    prompt: "Which inheritance pattern explains the pink flowers?",
    choices: ["Incomplete dominance", "Codominance", "Complete dominance", "Sex-linked inheritance"],
    answer: 0,
    explanation: "In incomplete dominance, the heterozygote shows a blend. In codominance, both traits would show separately, like red and white patches.",
  },
  {
    id: "sci-g10-16",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.6",
    skill: "Natural selection",
    passage:
      "A patient stops taking an antibiotic after a few days. A few bacteria that happened to have a resistance gene survive. They multiply, and the new infection does not respond to the same antibiotic.",
    prompt: "What best explains why the bacteria population is now resistant?",
    choices: [
      "The antibiotic selected for bacteria that already had resistance",
      "The antibiotic caused each bacterium to become resistant",
      "The bacteria learned to avoid the antibiotic",
      "The patient's body became resistant to the antibiotic",
    ],
    answer: 0,
    explanation: "Natural selection acts on existing variation: resistant bacteria survive and reproduce, so their trait becomes common.",
  },
  {
    id: "sci-g10-17",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.6",
    skill: "Evidence of evolution",
    prompt: "Structures with the same origin but different functions are...",
    choices: ["Homologous", "Analogous", "Vestigial", "Identical"],
    answer: 0,
    explanation: "Homologous structures, like a whale flipper and a human arm, point to a common ancestor. Analogous ones share function, not origin.",
    quick: true,
  },
  {
    id: "sci-g10-18",
    subject: "science",
    grade: "10",
    standard: "LS.Bio.6",
    skill: "Evidence of evolution",
    prompt: "Which data best show how closely two species are related?",
    choices: ["DNA sequences", "Body size", "Diet", "Habitat"],
    answer: 0,
    explanation: "The more similar two species' DNA or protein sequences, the more recently they shared a common ancestor.",
    quick: true,
  },
];
export default questions;
