import type { Question } from "../../types";
// Grade 11 social studies — NC Standard Course of Study for Social Studies (adopted 2021). American History (1763 to present): Revolution, expansion, Civil War and
// Reconstruction, industry, world wars, civil rights, Cold War and 9/11 (AH.H.1); rights and amendments (AH.C&G.1); economic change (AH.E.1); American identity (AH.B.1.1).
const questions: Question[] = [
  {
    id: "soc-g11-01",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Road to revolution",
    prompt: "Colonists protested the 1765 Stamp Act with 'no taxation without...'",
    choices: ["Representation", "Permission", "Money", "A king"],
    answer: 0,
    explanation: "Colonists had no members in Parliament, so they said Parliament had no right to tax them.",
    quick: true,
  },
  {
    id: "soc-g11-02",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Expansion",
    prompt: "The United States bought the Louisiana Territory in 1803 from...",
    choices: ["France", "Spain", "Britain", "Mexico"],
    answer: 0,
    explanation: "Jefferson bought it from Napoleon's France, doubling the size of the country.",
    quick: true,
  },
  {
    id: "soc-g11-03",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Expansion",
    prompt: "Manifest Destiny was the belief the U.S. should expand...",
    choices: ["To the Pacific", "Into Europe", "Into Africa", "Into Asia"],
    answer: 0,
    explanation: "The idea encouraged westward expansion, often at the expense of American Indians and Mexico.",
    quick: true,
  },
  {
    id: "soc-g11-04",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Reform",
    prompt: "The 1848 Seneca Falls Convention focused on...",
    choices: ["Women's rights", "Railroads", "Gold", "Tariffs"],
    answer: 0,
    explanation: "Elizabeth Cady Stanton and others issued the Declaration of Sentiments demanding equal rights for women.",
    quick: true,
  },
  {
    id: "soc-g11-05",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Reconstruction",
    prompt: "Which amendment (1868) granted citizenship and equal protection?",
    choices: ["14th", "13th", "15th", "19th"],
    answer: 0,
    explanation: "The 14th Amendment made formerly enslaved people citizens and promised equal protection of the laws.",
    quick: true,
  },
  {
    id: "soc-g11-06",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Segregation",
    prompt: "Plessy v. Ferguson (1896) upheld which policy?",
    choices: ["Segregation", "Integration", "Busing", "Suffrage"],
    answer: 0,
    explanation: "The Court approved 'separate but equal' facilities, allowing Jim Crow segregation.",
    quick: true,
  },
  {
    id: "soc-g11-07",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Civil rights",
    prompt: "Brown v. Board of Education (1954) overturned the ruling in...",
    choices: ["Plessy", "Marbury", "Miranda", "Dred Scott"],
    answer: 0,
    explanation: "Brown ruled that separate schools are inherently unequal, reversing Plessy v. Ferguson.",
    quick: true,
  },
  {
    id: "soc-g11-08",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Industrialization",
    prompt: "In the late 1800s, most new immigrants settled in...",
    choices: ["Cities", "Deserts", "Plantations", "Mountains"],
    answer: 0,
    explanation: "Factory jobs drew immigrants to growing cities like New York and Chicago.",
    quick: true,
  },
  {
    id: "soc-g11-09",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "World War I",
    prompt: "The United States entered World War I in...",
    choices: ["1917", "1914", "1941", "1898"],
    answer: 0,
    explanation: "The war began in 1914. The U.S. joined in April 1917.",
    quick: true,
  },
  {
    id: "soc-g11-10",
    subject: "social",
    grade: "11",
    standard: "AH.E.1",
    skill: "Great Depression",
    prompt: "Franklin Roosevelt's programs to fight the Depression were called the...",
    choices: ["New Deal", "Fair Deal", "Square Deal", "Great Society"],
    answer: 0,
    explanation: "The New Deal created jobs programs, Social Security and banking reforms.",
    quick: true,
  },
  {
    id: "soc-g11-11",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "World War II",
    prompt: "The U.S. entered World War II after the attack on...",
    choices: ["Pearl Harbor", "Midway", "Normandy", "Iwo Jima"],
    answer: 0,
    explanation: "Japan attacked Pearl Harbor, Hawaii, on December 7, 1941.",
    quick: true,
  },
  {
    id: "soc-g11-12",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Cold War",
    prompt: "The 1962 Cuban Missile Crisis was a standoff between the U.S. and the...",
    choices: ["Soviet Union", "United Kingdom", "Vietnam", "Canada"],
    answer: 0,
    explanation: "Soviet missiles in Cuba brought the superpowers close to nuclear war until a deal was reached.",
    quick: true,
  },
  {
    id: "soc-g11-13",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Civil rights",
    prompt: "The Voting Rights Act became law in...",
    choices: ["1965", "1954", "1920", "1870"],
    answer: 0,
    explanation: "The 1965 act banned literacy tests and other barriers that blocked Black citizens from voting.",
    quick: true,
  },
  {
    id: "soc-g11-14",
    subject: "social",
    grade: "11",
    standard: "AH.B.1.1",
    skill: "American identity",
    prompt: "The idea that the U.S. has a unique mission or character is American...",
    choices: ["Exceptionalism", "Federalism", "Nativism", "Isolationism"],
    answer: 0,
    explanation: "Americans have debated this idea from the colonial era to today.",
    quick: true,
  },
  {
    id: "soc-g11-15",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Recent history",
    prompt: "After the September 11, 2001 attacks, the U.S. led a war in...",
    choices: ["Afghanistan", "Vietnam", "Korea", "Mexico"],
    answer: 0,
    explanation: "U.S. forces entered Afghanistan in October 2001 and withdrew in 2021.",
    quick: true,
  },
  {
    id: "soc-g11-16",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil War",
    passage:
      "On January 1, 1863, President Lincoln declared that all enslaved people 'within any State or designated part of a State, the people whereof shall then be in rebellion against the United States, shall be then, thenceforward, and forever free.'",
    prompt: "What was a limit of the Emancipation Proclamation?",
    choices: ["It applied only to areas in rebellion", "It freed no one at all", "It applied only to the North", "It ended slavery everywhere at once"],
    answer: 0,
    explanation: "It did not cover border states loyal to the Union. The 13th Amendment (1865) ended slavery nationwide.",
  },
  {
    id: "soc-g11-17",
    subject: "social",
    grade: "11",
    standard: "AH.H.1",
    skill: "Civil rights",
    passage:
      "On February 1, 1960, four Black students from NC A&T sat at a whites-only lunch counter in Greensboro. Within about two months, sit-ins had spread to more than 50 cities in 13 states.",
    prompt: "What does this passage show about the sit-in movement?",
    choices: ["Nonviolent protest spread quickly", "The protest failed right away", "Only adults took part", "It started in the North"],
    answer: 0,
    explanation: "The Greensboro Four inspired students across the South to use sit-ins.",
  },
  {
    id: "soc-g11-18",
    subject: "social",
    grade: "11",
    standard: "AH.C&G.1",
    skill: "Progressive Era",
    passage:
      "In 1906, Upton Sinclair's novel The Jungle described filthy conditions in Chicago meatpacking plants, where spoiled meat and waste were packaged for sale.",
    prompt: "Which government action most directly followed this book?",
    choices: ["Meat Inspection Act", "Homestead Act", "Interstate highways", "19th Amendment"],
    answer: 0,
    explanation: "Public outrage led Congress to pass the Meat Inspection Act and Pure Food and Drug Act in 1906.",
  },
];

export default questions;
