import type { Question } from "../../types";

// Grade 1 ELA — NC Standard Course of Study for ELA (2017). RF.1.3 phonological awareness, RF.1.4 phonics (digraphs, final -e, vowel teams, syllables, endings, irregular words), RL.1.1, RL.1.5, RI.1.5, L.1.1, L.1.2, L.1.5
const questions: Question[] = [
  {
    id: "ela-g1-01",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Long and short vowels",
    prompt: "Which word has a long a sound?",
    choices: ["cake", "cat", "cap", "can"],
    answer: 0,
    explanation: "In cake, the a says its name. Cat, cap, and can have the short a sound.",
    quick: true,
  },
  {
    id: "ela-g1-02",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Blending sounds",
    prompt: "Blend /sh/ /i/ /p/. What word is it?",
    choices: ["ship", "chip", "sip", "shop"],
    answer: 0,
    explanation: "Put the sounds together: sh-i-p makes ship.",
    quick: true,
  },
  {
    id: "ela-g1-03",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Segmenting sounds",
    prompt: "How many sounds are in frog?",
    choices: ["4", "3", "5", "2"],
    answer: 0,
    explanation: "Frog has four sounds: /f/ /r/ /o/ /g/.",
    quick: true,
  },
  {
    id: "ela-g1-04",
    subject: "ela",
    grade: "1",
    standard: "RF.1.3",
    skill: "Rhyming words",
    prompt: "Which word rhymes with light?",
    choices: ["night", "lit", "lip", "late"],
    answer: 0,
    explanation: "Light and night both end with the -ight sound.",
    quick: true,
  },
  {
    id: "ela-g1-05",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Digraphs",
    prompt: "Which word begins with ch?",
    choices: ["chin", "shin", "thin", "win"],
    answer: 0,
    explanation: "Chin starts with ch, two letters that make one sound: /ch/.",
    quick: true,
  },
  {
    id: "ela-g1-06",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Silent e",
    prompt: "Add an e to the end of kit. What word do you get?",
    choices: ["kite", "kitty", "kits", "kid"],
    answer: 0,
    explanation: "A silent e at the end makes the i say its name: kit becomes kite.",
    quick: true,
  },
  {
    id: "ela-g1-07",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Vowel teams",
    prompt: "Which word has the long e sound spelled ee?",
    choices: ["tree", "bread", "boat", "rain"],
    answer: 0,
    explanation: "In tree, the two e's team up to say the long e sound.",
    quick: true,
  },
  {
    id: "ela-g1-08",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Syllables",
    prompt: "How many syllables are in sunset?",
    choices: ["2", "1", "3", "4"],
    answer: 0,
    explanation: "Sun-set has two parts, so it has two syllables.",
    quick: true,
  },
  {
    id: "ela-g1-09",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Word endings",
    prompt: "Which word means the jumping already happened?",
    choices: ["jumped", "jumps", "jumping", "jump"],
    answer: 0,
    explanation: "The ending -ed tells us something already happened.",
    quick: true,
  },
  {
    id: "ela-g1-10",
    subject: "ela",
    grade: "1",
    standard: "RF.1.4",
    skill: "Sight words",
    prompt: "Which word is spelled correctly?",
    choices: ["said", "sed", "siad", "sayd"],
    answer: 0,
    explanation: "Said is a tricky sight word. It is spelled s-a-i-d.",
    quick: true,
  },
  {
    id: "ela-g1-11",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Nouns",
    prompt: "Which word is a noun (a person, place, or thing)?",
    choices: ["school", "run", "happy", "quickly"],
    answer: 0,
    explanation: "A school is a place, so it is a noun.",
    quick: true,
  },
  {
    id: "ela-g1-12",
    subject: "ela",
    grade: "1",
    standard: "L.1.1",
    skill: "Verbs",
    prompt: "Which word is an action word (a verb)?",
    choices: ["hop", "cup", "red", "soft"],
    answer: 0,
    explanation: "Hop is something you can do, so it is a verb.",
    quick: true,
  },
  {
    id: "ela-g1-13",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "End marks",
    prompt: "Which mark goes at the end of a question?",
    choices: ["?", ".", "!", ","],
    answer: 0,
    explanation: "A question mark (?) ends a sentence that asks something.",
    quick: true,
  },
  {
    id: "ela-g1-14",
    subject: "ela",
    grade: "1",
    standard: "L.1.2",
    skill: "Capital letters",
    prompt: "Which word should always start with a capital letter?",
    choices: ["Monday", "apple", "dog", "city"],
    answer: 0,
    explanation: "Names of days, like Monday, always begin with a capital letter.",
    quick: true,
  },
  {
    id: "ela-g1-15",
    subject: "ela",
    grade: "1",
    standard: "L.1.5",
    skill: "Sorting words",
    prompt: "Which word does not belong: red, blue, green, dog?",
    choices: ["dog", "red", "blue", "green"],
    answer: 0,
    explanation: "Red, blue, and green are colors. A dog is an animal.",
    quick: true,
  },
  {
    id: "ela-g1-16",
    subject: "ela",
    grade: "1",
    standard: "RI.1.5",
    skill: "Text features",
    prompt: "What are the words under a picture that tell about it?",
    choices: ["caption", "title", "author", "glossary"],
    answer: 0,
    explanation: "A caption is a short label that explains a picture or photo.",
    quick: true,
  },
  {
    id: "ela-g1-17",
    subject: "ela",
    grade: "1",
    standard: "RL.1.5",
    skill: "Fiction and nonfiction",
    prompt: "A book that tells a made-up story is called...",
    choices: ["fiction", "nonfiction", "a glossary", "a label"],
    answer: 0,
    explanation: "Fiction tells made-up stories. Nonfiction gives true information.",
    quick: true,
  },
  {
    id: "ela-g1-18",
    subject: "ela",
    grade: "1",
    standard: "RL.1.1",
    skill: "Key details",
    prompt: "Where did Sam find his kite?",
    passage: "Sam lost his red kite in the wind. He looked in the yard and by the pond. At last he saw it stuck in the big oak tree. His dad got a ladder and helped him get it down. Sam hugged his kite and smiled.",
    choices: ["In a tree", "By the pond", "In the yard", "Under his bed"],
    answer: 0,
    explanation: "The story says Sam saw his kite stuck in the big oak tree.",
  },
];

export default questions;
